### ISSUE TITLE
build enhancement: Python 3: configure with 2to3 of different name

### ISSUE THREAD

**Issue by futatuki** [swig/swig#1001]
On some legacy OS, default version of system Python is too old, users can install newer version of Python and its utilitis with changing name, adding version suffix, etc. In such environment, there can be only 2to3 utility of different name.

So, I'm glad to pass the name of 2to3 utility path to the configure script.

Here is a patch against swig-3.0.12 release, to enhance above function. (and I hope it can be applied latest code tree.)

[swig-3.0.12-2to3-rename.patch.txt](https://github.com/swig/swig/files/1081088/swig-3.0.12-2to3-rename.patch.txt)

**Comment by ojwb** [comment]
Please submit your patch as a pull request - that way it'll get automatically built and CI tested, so we can see if it causes testsuite regressions.

(Also your link doesn't seem to work for me - I just get a blank page).

**Comment by wsfulton** [comment]
Patch in #1003 fixes this.
