### ISSUE TITLE
Support Python 3 stable API

### ISSUE THREAD

**Issue by vadz** [swig/swig#1009]
It would be great if SWIG could generate code using only [stable Python 3 API](https://docs.python.org/3/c-api/stable.html). This isn't trivial to do, i.e. just defining `Py_LIMITED_API` right now doesn't work at all as I wrote at the [old SF issue](https://sourceforge.net/p/swig/feature-requests/78/), but it would be worth spending more effort on this IMO as otherwise distributing binary Python3 modules is really painful because you need to build them for each 3.x version separately (at least with Python 2, you need to support 2 versions at worst, and 90% of people probably only need to support 2.7).

**Comment by mromberg** [comment]
It seems Py_LIMITED_API is documented:

https://www.python.org/dev/peps/pep-0384/#id7

  It would be interesting to see what the script on that page:

http://svn.python.org/projects/python/branches/pep-0384/Tools/scripts/abitype.py

  thinks is wrong with some of the swig generated code.   I have no idea how complete that script is.

  One problem I can foresee is that swig would not only have to generate code that works for Py_LIMITED_API but it would need to also generate code that works for python2.   My guess is that the same code would not work for both.   So... yet another command line python option for swig would have to be done.

   Still, it might be nice to have the swig code for python3 to start heading in this direction.  It will probably have to be done a little bit at a time.

**Comment by vadz** [comment]
Here is a more detailed list of problems that appear when trying to compile
SWIG-generated code with `-DPy_LIMITED_API`, in order from the simplest to
most difficult to solve ("NA" below means "not available in stable ABI"):

- `PyCFunction_GET_XXX()` macros NA, but they can be just replaced with the
  corresponding functions. We could keep macros for non-stable ABI, but the
  tiny gain from doing it is probably not worth it.
- `fastproxy` requires `PyInstanceMethod_New()` which is NA. I don't know
  how useful this option is, ideal (from simplicity point of view) would be to
  just drop it, but we could also keep it but make all the related code
  conditional on `Py_LIMITED_API` being not defined.
- `fastinit` requires `SWIG_Python_InitShadowInstance()` which uses tuple
  functions which are NA. Same analysis as for `fastproxy` above.
- `PyTypeObject` is now opaque, yet we use it *extensively*. There are a
  couple of dozens places where just `tp_name` is used and I don't know how to
  access it using just stable API. In most places, `tp_name` is used only for
  diagnostic purposes, but it would be still a pity to lose it in the error
  messages. And in a couple of places it is used for the type checks, although
  I don't really understand why does e.g. `SwigPyObject_Check()` use it, i.e.
  why do we rely on string comparison instead of the actual type check (which
  is done too, anyhow).
- As `PyTypeObject` is opaque, objects of this type can't be static any more
  and must be created using `PyType_FromSpec()`, so all type initialization
  code must be rewritten. As part of this, we must stop using
  `PyNumberMethods` which is NA. Also, `tp_print` slot and `printfunc` typedef
  are NA neither.

I'm going to try to work on this, starting from the end, probably, as the last
item seems to require the most changes. But in the meanwhile any comments
about the other ones (notably `fastxxx` stuff that I know nothing about (but
then I suspect it's also the case for everybody else...)) would be welcome
too, of course.

**Comment by wsfulton** [comment]
hi @vadz, are you going to work on this with or without the `-builtin` option?

**Comment by vadz** [comment]
@wsfulton I'd like to make it work with `-builtin` because I think it should become the default in the future. But I've started without it because (C++ part of the) code looks simpler without it. I didn't have time to do much yet though, so perhaps I'll discover it was a bad idea soon.

**Comment by Cory-Kramer** [comment]
Has there been any progress on this request?
This would make distributing generated modules much less cumbersome.

**Comment by vadz** [comment]
No, sorry, I got discouraged by all the problems listed above. I could be wrong, but I actually have a feeling that the stable API is just too limited to implement everything (or even most of what) SWIG does.

**Comment by vadimcn** [comment]
So I decided to take a [stab at it](https://github.com/swig/swig/pull/1613), and it doesn't look so bad actually.   My PR passes the whole test suite, with the exception of python_pybuffer test. 
Some bits are admittedly less than optimal, like all that string comparison business in `SwigPyObject_Check`...  
Maybe someone with more Python/SWIG expertise can lend a hand?

**Comment by aundro** [comment]
[Note: I also posted this comment in the branch: https://github.com/swig/swig/pull/1613#issuecomment-522929879]

Hi all,

we (www.hex-rays.com) are long-time SWiG users, and we will soon have to ship our product with support for Python 3.
In an attempt to ship our product with code that doesn't expect a specific version of Python to be installed (we use the one from the system), we would be interested in getting this Py_LIMITED_API-related work, into SWiG.

I can see that the work on this branch is not finished, but at a first glance it seems like a good start.
Can anyone elaborate on what still needs to be done, and perhaps pointers to get me started?
(I don't suppose the PyBuffer-related bits will find a solution any time soon, since the relevant CPython functions are (AFAICT) still not part of the "limited API".
But for the rest, perhaps I can give a hand?)

**Comment by aundro** [comment]
@vadimcn One thing I find a bit on the sketchy side, is the use of define's to redirect e.g., `PyTuple_GET_ITEM` to the Py_LIMITED_API-compliant `PyTuple_GetItem`.
Wouldn't it be best to change e.g., `pyrun.swg` so that it emits code like so?

>   #ifdef Py_LIMITED_API
>       Py_ssize_t l = PyTuple_GetSize(args);
>   #else
>        Py_ssize_t l = PyTuple_GET_SIZE(args);
>   #endif

**Comment by aundro** [comment]
@vadimcn @wsfulton what do you think are the next steps to be done, in the hope of seeing that work make it into SWiG eventually?

**Comment by vadimcn** [comment]
> Wouldn't it be best to change e.g., pyrun.swg so that it emits code like so?

Depends on the metric you are optimizing for.   It's a bit worse for code explicit-ness, but, IMO, much better for readability.   Also, defining macros in terms of functions is much less of a problem than the other way round.   

> what do you think are the next steps to be done

- I'd like some general feedback from SWIG maintainers on whether this patch is going in the right direction.   Is there something I am missing, which makes such a patch a bad idea?   
- This patch does not handle the -builtin mode.  I am not very familiar with code SWIG generates in this mode, and the project I am interested in wrapping uses the Python proxy layer, so I left it for later (or, perhaps, for somebody else).
- There seem to be other switches (-fastinit?) which will need further changes and testing.
- In a few places (SwigPyObject_Check, SwigPyPacked_Check and SWIG_Python_ConvertFunctionPtr) I had to add dictionary lookups in code that previously accessed Python data structures directly.   This may have noticeable performance impact.  I am wondering if there are better ways of doing it in Python3.  Ideas?  
(What does SWIG_Python_ConvertFunctionPtr even do?)

**Comment by vadz** [comment]
First of all, thanks for your work on this!

> > what do you think are the next steps to be done
> 
>     * I'd like some general feedback from SWIG maintainers on whether this patch is going in the right direction.   Is there something I am missing, which makes such a patch a bad idea?

I looked at it and it seems mostly fine to me, in fact it is much simpler than what I would've expected, which is a very nice surprise. I don't know/remember why did I think that it would be so much more complicated. Maybe 3.2 (?) stable API that I tried to use back then didn't have all the functions you used yet? Anyhow, I definitely think it's great and if it works I don't see any reason not to merge it.

This being said, #1613 (intentionally?) fails all the existing tests and doesn't add (AFAICS) a test build in which stable API is used, so it's hard to be sure to know if it works. So the very first thing I'd do would be to add such new build and check that all CI builds pass.

>     * This patch does not handle the -builtin mode.

I think that's fine, as long as using this switch with it is clearly flagged as an error (not sure if it's the case now).

>     * There seem to be other switches (-fastinit?) which will need further changes and testing.

I don't think this is a showstopper neither.
 
>     * In a few places (SwigPyObject_Check, SwigPyPacked_Check and SWIG_Python_ConvertFunctionPtr) I had to add dictionary lookups in code that previously accessed Python data structures directly.   This may have noticeable performance impact.  I am wondering if there are better ways of doing it in Python3.  Ideas?

SWIG-generated code is already quite far from being ideal, so I don't think an extra dict lookup is going to change much, but if you could benchmark comparative performance with and without stable API, it would be useful, of course. In any case, for me it's not the reason to not apply the patch, even if there is no other way to do it with stable API. OTOH, if there is no significant difference in performance, we might avoid some `if`s/`#if`s by always using the "less performant" method to simplify the code.

**Comment by vadimcn** [comment]
> Maybe 3.2 (?) stable API that I tried to use back then didn't have all the functions you used yet? 

AFAIK, the only post-3.2 API I am using is `PyType_GetSlot` which was new in 3.4

>  So the very first thing I'd do would be to add such new build and check that all CI builds pass.

Any guidance on how to do that?   Haven't figured out SWIG's build system yet.   How do I run all CI tests locally?

**Comment by vadz** [comment]
`make check-python-test-suite` runs the full test suite, you can add `SWIG_FEATURES=-py3-stable-api` to use a custom command line option.

To add a new CI build, you need to edit `.travis.yml` and add another element to the matrix (or maybe modify one of the existing Python 3 ones to avoid burdening Travis even more? @wsfulton do you think we could reuse one of 3.x builds for this?), using `SWIG_FEATURES` there as well.

For MSW CI builds, edit `appveyor.yml`, although it's a bit more manual as you will need to do something to pass `SWIG_FEATURES` to SWIG, as it's not used there any more.

Good luck!

**Comment by mromberg** [comment]
I'm assuming this stable ABI feature if/when it is added to swig would be controlled by a command line switch or something.   There are almost certainly swig generated modules that have typemaps and other "user" support code that does not use the stable ABI and has no interest in doing so.

  It would be a good thing if there were a way to either opt in or opt out of the stable ABI.

**Comment by vadz** [comment]
Yes, it's controlled by an option, see the changes to `python.cxx` in #1613.

In principle I think we could make just the definition of `Py_LIMITED_API` optional: if it's _not_ defined, we could still use stable API, but user typemaps/code could continue to use non-stable API too. This could be nicer because we'd always have the same code and the option would control just this `#define`, instead of having another bifurcation in Python module logic.

**Comment by fixthething** [comment]
Has this issue moved at all? Was any of the pull request ever implemented? Frustrating if it hasn't when it seems there has been a solution for some time.  I just learned about the limited API today and it would be great if I could make one wheel to rule them all for my swig module instead of building half a dozen. I saw lots of build errors when I tried defining Py_LIMITED_API on the 4.0.x swig distributed with Ubuntu 20.04, so it hadn't been fixed at that point at least.

**Comment by chausner-audeering** [comment]
Are there any plans to get this work into master? The dependency on version-specific APIs seems like a huge drawback when you want to publish your SWIG-based library to users that may be on any 3.x version. It seems you would need to have separate builds for each minor Python version.

**Comment by ojwb** [comment]
#2392 is another step towards this.

**Comment by wsfulton** [comment]
#2727 finally adds stable ABI support. Please test it in the swig-4.2.0-beta1 version due to be release before end of year.

**Comment by wsfulton** [comment]
> I don't really understand why does e.g. SwigPyObject_Check() use it, i.e.
why do we rely on string comparison instead of the actual type check (which
is done too, anyhow).

Maybe late to answer now, but I'm working towards the stable ABI for `-builtin`, see #3196, and was wondering the same for  f3672e2d6f5f9dae6d30e8df5a4d432d21cc7358 - it's a fallback for multiple modules use case.
