### ISSUE TITLE
C++ Direct initialization is not supported/parsed correctly

### ISSUE THREAD

**Issue by rolftheunissen** [swig/swig#101]
The following line, c++ direct initialization of a integer, leads to a parse error:

```
int a(3);
```

480: Error: Syntax error in input(1).

Furthermore, constants defined using direct initialization are not wrapped as constants:

```
const int b(static_cast<int>(ENUM_ITEM));
```

is translated as function with an argument.

**Comment by ojwb** [comment]
Both still the case for current git master.

**Comment by ojwb** [comment]
Closing as a duplicate of #869 (which was reported well after this, but gives more examples).
