### ISSUE TITLE
How do I build SWIG on Windows

### ISSUE THREAD

**Issue by sid2364** [swig/swig#1016]
Couldn't find instructions to build on Windows.

**Comment by ojwb** [comment]
http://www.swig.org/Doc3.0/Windows.html#Windows_swig_exe

**Comment by yuangu** [comment]
I'm build win32 on xubuntu16.04。
1、install mingw32. 
`sudo apt-get install mingw-w64`
2、cd the swig code and run
`./configure --prefix=/home/yuangu/out --host=x86_64-w64-mingw32  --without-pcre`
3、copy libgcc_s_seh-1.dll and libstdc++-6.dll to the swig dir file. this cmd can find where dll
`x86_64-w64-mingw32-gcc -print-prog-name=cc1plus` -v
4、run ` swig -swiglib` on windows , which your can  get a path where your copy  the swig lib to. 


if your realy lazy to build it.your can dowload my build at here https://pan.baidu.com/s/1geDQoan

sorry for my poor english.and happy func. ^_^

**Comment by sid2364** [comment]
Thanks @yuangu for the reply and the build!

**Comment by ojwb** [comment]
There's a link to an official prebuilt version on the download page:

http://www.swig.org/download.html
