### ISSUE TITLE
Placing CFLAGS and LDFLAGS in generated golang file.

### ISSUE THREAD

**Issue by xoviat** [swig/swig#1020]
Is there a way to place a header like this in the generated go file without manually editing it?

```
// #cgo CFLAGS: -Isrc/include  
// Where doc-capi-tesseract.h is!
// #cgo LDFLAGS: doc-capi-tesseract.a
// #include "doc-capi-tesseract.h"
```

**Comment by ojwb** [comment]
I don't think there currently is, short of running the generated wrapper through `sed` or similar.

For some target languages SWIG does provide a way to do this, e.g. see `%pythoncode` and `%pythonbegin` for Python.  If you fancy implementing similar for Go, I'm sure a patch would be appreciated.

**Comment by ajbouh** [comment]
I had some success with:

```
%insert(cgo_comment_typedefs) %{
#cgo LDFLAGS: ...
%}
```

**Comment by xoviat** [comment]
This currently not needed as flags can be specified in another go file that is not managed by swig. At the time that I created this issue, I was unfamiliar with that option.
