### ISSUE TITLE
Swig fails to parse templated `using` alias with template argument.

### ISSUE THREAD

**Issue by elfprince13** [swig/swig#1021]
I have some code with the following two templates, implementing similar behavior (`conditional` and `is_same` are from the `std` namespace).
```c++
	template<template<typename D, typename ...O> class C, typename T, typename Super, typename Root, typename ...O>
	using DeriveToBase = typename conditional<is_same<T, AnyVal>::value, Root, C<Super, O...> >::type;

	template<class T, class Root, class RParent>
	using ImmediateBase = typename conditional<is_same<T, AnyVal>::value, Root, RParent >::type;
```

Swig has no problem with `ImmediateBase`, but barfs on `DeriveToBase`.

**Comment by ojwb** [comment]
My initial guess was this was due to a missing C++11 feature (at least I don't see the parser explicitly handling `...` in templates) but removing that doesn't seem to fix the parse error.

Possibly related to #624.

As William said there:

> It is entirely reasonable to expect any valid standard C++ like this to work. However in reality, only basic template template parameter support is working in SWIG (such as 8f09d00) . Parsing errors are usually fairly easily fixed in parser.y and the aforementioned patch gives a good idea as to where to look.

**Comment by elfprince13** [comment]
As a work-around for now, I can probably replace my usage of `DeriveToBase` with usage of `ImmediateBase` (I was already testing it, because I'm inheriting from an aliased, templated type, and only the latter of those templates works to call the constructor of the parent class).

**Comment by elfprince13** [comment]
Cheers @wsfulton!
