### ISSUE TITLE
[C#] - creation of shared_ptr of 'T' deriving from 'L' using virtual inheritance

### ISSUE THREAD

**Issue by schullq** [swig/swig#1022]
Hi,

I am still trying to wrap a huge C++ library, and I have come across another issue.

I have a diamond inheritance, which makes me use virtual inheritance for the base common class.

Here is a little standalone to understand my point:
```

%module sample

%include <windows.i>
%include <std_string.i>
%include <std_shared_ptr.i>
%{
#include <memory>

class Ancestor;
class RelativeA;
class RelativeB;
%}

namespace std {
    template <class T> class enable_shared_from_this {
    public:
        shared_ptr<T> shared_from_this();
        //shared_ptr<const T> shared_from_this() const;
	protected:
		enable_shared_from_this();
        enable_shared_from_this(const enable_shared_from_this &);
		~enable_shared_from_this();
    };
}

%shared_ptr(std::enable_shared_from_this<Ancestor>);
%shared_ptr(Ancestor);
%shared_ptr(RelativeA);
%shared_ptr(RelativeB);
%shared_ptr(Son);

%template(AncestorEnableShared) std::enable_shared_from_this<Ancestor>;

%typemap(csout, excode=SWIGEXCODE)
  Ancestor*, std::shared_ptr<Ancestor> {
    System.IntPtr cPtr = $imcall;
    Ancestor ret = samplePINVOKE.createObject(cPtr, $owner);$excode
    return ret;
}

%inline %{

class Ancestor : public std::enable_shared_from_this < Ancestor >
{
public:
	Ancestor() : d_family_name("Unknow") {}

	Ancestor(std::string gname, std::string fname) : d_given_name(gname), d_family_name(fname) {}

	virtual ~Ancestor() {}

	virtual std::string getGivenName() const { return d_given_name; }

	virtual std::string getFamilyName() const { return d_family_name; }

	virtual std::string getType() const { return "Ancestor"; }

private:

	std::string d_given_name;

	std::string d_family_name;
};

class RelativeA : public virtual Ancestor
{
public:
	RelativeA() : Ancestor("Jimmy", "PAGE") {}

	virtual ~RelativeA() {}

	virtual std::string getFamilyName() const override { return "J.P."; }

	virtual std::string getType() const { return "RelativeA"; }

protected:
	RelativeA(std::string name, std::string rname) : Ancestor(name, rname) {}
};

class RelativeB : public virtual Ancestor
{
public:
	RelativeB() : Ancestor("Saul", "HUDSON") {}

	virtual ~RelativeB() {}

	virtual std::string getFamilyName() const override { return "Slash"; }

	virtual std::string getType() const { return "RelativeB"; }

protected:
	RelativeB(std::string name, std::string rname) : Ancestor(name, rname) {}
};

class Son : public RelativeA
{
public:
	Son() : Ancestor("Eric", "CLAPTON"), RelativeA("Eric", "CLAPTON") {}

	virtual ~Son() {}

	virtual std::string getType() const { return "Son"; }

protected:
};

class TheCreator
{
public:
	static std::shared_ptr<Ancestor> createLivingBeing(std::string name)
	{
		if (name.compare("RelativeA") == 0)
			return std::make_shared<RelativeA>();
		else if (name.compare("RelativeB") == 0)
			return std::make_shared<RelativeB>();
		else
			return std::make_shared<Son>();
	}
};
%}

%pragma(csharp) imclasscode=%{

	public static Ancestor createObject(System.IntPtr cPtr, bool owner)
	{
		Ancestor ret = null;
		if (cPtr == System.IntPtr.Zero) {
		  return ret;
		}
		string type = ($imclassname.Ancestor_getType(new System.Runtime.InteropServices.HandleRef(null, cPtr)));
		switch (type)
		{
		case "Ancestor":
			ret = new Ancestor(cPtr, owner);
			break;
		case "RelativeA":
			ret = new RelativeA(cPtr, owner);
			break;
		case "RelativeB":
			ret = new RelativeB(cPtr, owner);
			break;
		case "Son":
			ret = new Son(cPtr, owner);
			break;
		default:
			break;
		}
		return ret;
	}
%}
```

And a C# test to see the problem:

```
using System;

public class Program
{
    public static void Main(string[] arg)
    {
        Ancestor test = TheCreator.createLivingBeing("Son");

        Console.WriteLine(test.getFamilyName()); // <- will throw an exception
        Console.WriteLine(test.getGivenName());
    }
}
```
Exception thrown:

> Exception thrown at 0x0F54E07C (sample.dll) in test_swig.exe: 0xC0000005: Access violation reading location 0x10219748.

There is a memory issue when trying to access to the new object. I think the problem comes from the virtual inheritance, because if you remove it, it works (but my diamond inheritance does not anymore, so I can't change the C++ to fix it). Also, I didn't find anything about virtual inheritance in the docs.

Anyway, the sample I provided here could look a little dumb, I simplified as much as I can in order to let you understand easily, but the problem I have encountered is exactly this one.

If you need more infos to understand, feel free to ask.

**Comment by schullq** [comment]
After more searches and tests, it looks like the problem has nothing to see with shared_ptr. The real problem is that SWIG doesn't handle virtual inheritance at all, or at least when wrapping to C#. Am I right ? Is there a fix or something in the next release ?

I know that a good work is currently in progress around multiple inheritance (e. g. %interface), but a with virtual inheritance ?

**Comment by ojwb** [comment]
http://www.swig.org/Doc3.0/CSharp.html#CSharp_directors

**Comment by schullq** [comment]
I don't understand in which way directors could help me in this case. Could you enlighten me please ?

**Comment by ojwb** [comment]
I know very little about C#, and I don't really understand what you're trying to do, but if you're wanting virtual inheritance to work between the languages you'll need to enable directors.

**Comment by schullq** [comment]
I don't want to make inheritance work between languages, I just want virtual inheritance to be wrapped ! Each class inheriting virtually won't work in the C#. Every time I will try to access a method or property, I will have a memory corruption exception.

**Comment by schullq** [comment]
Maybe am I unclear, but the problem just stands in the class wrapping. If the class inherits virtually from another in the C++, like in my example RelativeA inheriting from Ancestor virtually (`class RelativeA : public virtual Ancestor`), once wrapped in C#, accessing any RelativeA method or property will result to an access violation exception due to "memory corruption". 
Hope I have made myself clear enough. Do not hesitate to ask fore more explanations if you don't understand my point.

**Comment by wsfulton** [comment]
The problem here is your custom code, not the code that SWIG generates. It is unrelated to smart pointers and also unrelated to virtual inheritance. If you replace
```c#
Ancestor test = TheCreator.createLivingBeing("Son");
```
with
```c#
Ancestor test = new Son();
```
The code works. The custom code in `createObject` is wrong because it is treating the C++ pointer (of type `std::shared_ptr<Ancestor>*`) as if it was a `std::shared_ptr<Son>*`. With virtual inheritance, the underlying C++ pointer values for a `Ancestor*` and `Son*` are actually different values. You'll see SWIG handles this difference by using the upcast functions (such as `Son_SWIGSmartPtrUpcast` in the Son constructor), which in turn casts (in C++) a `Son*` to an `Ancestor*`.
