### ISSUE TITLE
C++ integral literals in binary format are not parsed

### ISSUE THREAD

**Issue by luav** [swig/swig#1030]
SWIG fails to parse C++ literals in binary format:
```c++
enum class IntrinsicsFlags {
	NONE = 0,  // OK
	CONDUCTANCE = 0b1  // "Error: Syntax error in input(1)"
}
```

**Comment by ojwb** [comment]
Missing C++14 feature.

Shouldn't be hard to add - if you're able to contribute a patch to add this that would be great.

**Comment by luav** [comment]
I would be glad to contribute and will do it, but not so fast, I have just started with SWIG yesterday :-)  
There some deadlines and priorities, but I really will do it if nobody else fix this issue within several months...

**Comment by luav** [comment]
I even did not find where the hex numeric literals are parsed in the `Source/CParse/parser.y`... The only hint to localize the issue is that `"Error: Syntax error in input(1)"` is generated in [parser.y](https://github.com/swig/swig/blob/master/Source/CParse/parser.y#L1604).

**Comment by ojwb** [comment]
This would be handled at the tokenisation stage, not in the parser grammar.

Look at `Source/Swig/scanner.c` and search for `case 83:`.

**Comment by ZackerySpytz** [comment]
I've been working on scanner.c recently, so I've created a PR for this issue: #1464.
