### ISSUE TITLE
C++ "static_assert" parsing fails

### ISSUE THREAD

**Issue by luav** [swig/swig#1031]
C++ `static_assert` parsing fails:
```c++
using LinkWeight = float;  // float or double
using AccWeight = double;

static_assert(sizeof(AccWeight) >= sizeof(LinkWeight), "Weight types verification failed");  // Error: Syntax error in input(1).
```
or just `static_assert(1, "Test");` also yields "Error: Syntax error in input(1)".

**Comment by ojwb** [comment]
Missing C++11 feature.

Again, shouldn't be hard to add and a patch would be welcome.

SWIG only needs to ignore the `static_assert()` (SWIG can't check a condition like this, as the type sizes are down to the compiler you build the code with, and that compiler will see the assertion anyway), so you can probably workaround it by defining a macro for `static_assert`:

```
swig -D'static_assert(...)=' -c++ ...
```

(Using a variadic macro so it also handles C++17's one-argument version of `static_assert`.)

**Comment by luav** [comment]
Yes, thanks,
I did it at once in my code just adding the conditional definition for the `static_assert` as a workaround. Just it's good to know for everyone and it would be nice to have this feature out of the box.

**Comment by luav** [comment]
By the way, `static_assert` has been [added](https://github.com/swig/swig/blame/master/Source/CParse/parser.y#L1448) to the `Source/CParse/parser.y` 8 years ago, but does not work yet.

**Comment by ojwb** [comment]
Looks like it's handled in functions, but not at the top level - i.e. this tweak to the existing test case makes it fail:

```
diff --git a/Examples/test-suite/cpp11_static_assert.i b/Examples/test-suite/cpp11_static_assert.i
index 8d616f96..e3914026 100644
--- a/Examples/test-suite/cpp11_static_assert.i
+++ b/Examples/test-suite/cpp11_static_assert.i
@@ -1,9 +1,12 @@
 /* This test case checks whether SWIG correctly parses and ignores the
-   keywords "static_assert()" inside the class or struct.
+   keywords "static_assert()" inside the class or struct, or at the top
+   level.
 */
 %module cpp11_static_assert
 
 %inline %{
+static_assert(sizeof(int) >= 2, "What?  int size is invalid!");
+
 template <typename T>
 struct Check1 {
   static_assert(sizeof(int) <= sizeof(T), "not big enough");
```

**Comment by ojwb** [comment]
It was just in the wrong place in the grammar - fixed now.

**Comment by luav** [comment]
Cool! Thanks.
