### ISSUE TITLE
SWIG prepends default include paths with the user-specified overwriting default adapters using "-I" directive

### ISSUE THREAD

**Issue by luav** [swig/swig#1033]
Prepending of the default include paths with the user-specified on `-I ` causes overwriting of the default adapters, which is not intended.

`swig_gen.sh` contains:
```make
SINCLUDE=/usr/local/share/swig/3.0.12/std/
swig $SINCLUDE ...
```
that results in
```make
Language subdirectory: java
Search paths:
   ./
   /usr/local/share/swig/3.0.12/std/     <<< Custom path before the system-defined
   /usr/local/share/swig/3.0.12/java/
  ...
```
and prevents definitions of the target STL containers for Java with the error:
```
/usr/local/share/swig/3.0.12/std/std_except.i:2:
Error: CPP #error ""do not use this version of std_except.i"". Use the -cpperraswarn option to continue swig processing.
```
`std_except.i` exists in `java/` but can't be loaded.
> I added `/usr/local/share/swig/3.0.12/std/` to use `std_list.i`, which is not exists the in `java/` stl adapters.

Paths appending is reasonable only if the user is supposed to overwrite the system includes, which is not a typical case.  
It would be sensible to *append custom include paths to the initially defined system paths* or to have the additional option that specifies whether to append or prepend the default include paths.

**Comment by ojwb** [comment]
`-I` directories being searched first is what the manual clearly documents, so it would be disruptive to change this.

Specifying subdirectories of SWIG's own library with `-I` isn't a sensible thing to do, so that not working doesn't seem a big deal.  Even if we searched `-I` directories last, at best this would have no effect...
