### ISSUE TITLE
C++ template extension with member functions does not work

### ISSUE THREAD

**Issue by luav** [swig/swig#1043]
C++ template extension with member functions does not work:
```c++
template <typename LinksT>
class Cluster: public NodeI<LinksT> {
	using NodeIT = NodeI<LinksT>;
#ifdef SWIG
	// SWIG can't resolve parameters of the base template for the inherited member attribute,
	// so the attribute should be ignored and the accessor function provided
	%ignore owners;
#endif // SWIG
	using NodeIT::owners;  // Ignored
#ifdef SWIG
	Owners<links_type>& ownercls() noexcept  { return this->owners; }  // Issue: ownercls() are not generated
#endif // SWIG
	...
}
```
Compilation of the generated wrapper yields:
```
...: note: in expansion of macro 'SWIG_ConvertPtr'
   res1 = SWIG_ConvertPtr(swig_obj[0], &argp1,SWIGTYPE_p_daoc__ClusterT_std__vec
          ^
swig/wraps/daoc_python2.cxx:10055:144: error: 'class daoc::Cluster<std::vector<daoc::Link<float, false>, std::allocator<daoc::Link<float, false> > > >' has no member named 'ownercls'
 llocator< daoc::Link< float,false > > > >::links_type > *) &(arg1)->ownercls();
```

*Notes:*
- This code could be a kind of workaround for the #1042.
-  Addition to the interface file:
```c++
%extend Cluster {
	Owners<links_type>& ownercls() noexcept  { return this->owners; }
}
```
does not solve the issue (yields the same error).

**Comment by luav** [comment]
As if found, `SWIG` macros is defined only when the wrapper is generated. `SWIG_VERSION` macros is defined always when any code is processed evolving the SWIG, so the correct solution is:
```c++
...
#ifdef SWIG_VERSION
	Owners<links_type>& ownercls() noexcept  { return this->owners; }  // Issue: ownercls() are not generated
#endif // SWIG_VERSION
...
```

I.e. the issue was invalid, it was my misunderstanding.

**Comment by ojwb** [comment]
The `%extend` approach ought to work, except you should use `$self` instead of `this` in the body.

**Comment by luav** [comment]
The problem was that under `SWIG` macros only the interface declaration generated yielding the outlined error. `SWIG_VERSION` macros should be used for the original *source codes* (that are included via both `#include` and `%include`) to have the function definition besides the declaration.

**Comment by luav** [comment]
The outlined solution requires minor tuning for the Java wrapper generation because of the related bug #1050 in SWIG.
