### ISSUE TITLE
request for version 1.3.18

### ISSUE THREAD

**Issue by wenhuizhang** [swig/swig#1048]
Hi, I was trying to use simulavr, which needs version 1.3.18. Any idea where could I get this version please? 

It seems like that there are only latest version online at offical website.

**Comment by ojwb** [comment]
There's an "All releases" link on the download page: http://swig.sourceforge.net/download.html

But it seems unlikely you really need **exactly** 1.3.18 - probably they mean you need **at least** 1.3.18.
