### ISSUE TITLE
SWIG generates improper code for the C++ namespace

### ISSUE THREAD

**Issue by luav** [swig/swig#1051]
SWIG has bugs on code generation for the custom namespace if the namespace members use another namespace (including `std`). For example, I would like to generate SWIG templates in my namespace `daoc`:
```c++
namespace daoc {
...
%template(Item) NodeI<Links<WeightedLink<LinkWeight>>>;
...
}
```
Compilation of the generated wrapper yields the following error:
```
error: 'std' is not a member of 'daoc'
   daoc::Owners< daoc::NodeI< vector< daoc::Link< float,false >,daoc::std::alloc
                                                                ^
compilation terminated due to -Wfatal-errors.
```
the complete code fragment of the wrapper is:
```c++
  daoc::Owners< daoc::NodeI< vector< daoc::Link< float,false >,daoc::std::allocator< daoc::Link< float,false > > > >::links_type > *result = 0 ;
```
As you can see, `std::alloc` is moved  by SWIG to the `daoc` namespace: `daoc::std::alloc`.

*Environment:*
SWIG Version 3.0.12
Compiled with g++ [x86_64-pc-linux-gnu]
Configured options: +pcre

**Comment by wsfulton** [comment]
That close was from the wrong commit. The merge 32a454cfef15154523c014bb8c95496989b3bd2b or 959e6272082e416303d80d7326430d1fd0b4c432 in particular fixed this issue.
