### ISSUE TITLE
Proposal: export of the source code documentation to the generated wrappers

### ISSUE THREAD

**Issue by luav** [swig/swig#1052]
**Export of the source code documentation** besides the functionality to the target languages would be a really nice and convenient feature solving the same issues as SWIG itself: *write once, use everywhere*!

SWIG fortunately provides `%feature("autodoc", "1")` (at least for Python), but it describes only types of the parameters, not the functionality that possibly outlined in the source codes by the developer.

[Doxygen](http://www.stack.nl/~dimitri/doxygen/manual/arch.html) generates documentation in various formats from the source files being an industrial standard. Probably, [parts of] [Doxygen](https://github.com/doxygen/doxygen) could be integrated with SWIG to fetch documentation for the custom types, functions, etc. and export to the target languages.

**Comment by vadz** [comment]
I suspect this is a duplicate of #170.

**Comment by vadz** [comment]
I suspect this is a duplicate of #170.

**Comment by luav** [comment]
Yes, cool!  
So, have it been added to the master or what is the status and what are the plans?
