### ISSUE TITLE
Dylib and Go

### ISSUE THREAD

**Issue by bernex** [swig/swig#1055]
GO: go1.8.3 darwin/amd64
SWIG Version 3.0.12

`swig -c++ -go -soname libapple.dylib -use-shlib -intgosize 64 core/Apple.i`

And I see Apple_gc.c and wanna compile with 6c(go tool compile in )

```
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: core/Apple.i */


/* This file should be compiled with 6c/8c.  */
#pragma dynimport _ _ "libapple.dylib"

#include "runtime.h"
#include "cgocall.h"

#pragma dataflag 16
static void *cgocall = runtime·cgocall;
#pragma dataflag 16
void *·_cgo_runtime_cgocall = &cgocall;


#pragma dynimport _wrap_Swig_free_sdsd_174c5afe4e48040e _wrap_Swig_free_sdsd_174c5afe4e48040e ""
#pragma cgo_import_static _wrap_Swig_free_sdsd_174c5afe4e48040e
extern void _wrap_Swig_free_sdsd_174c5afe4e48040e(void*);
uintptr ·_wrap_Swig_free_sdsd_174c5afe4e48040e = (uintptr)_wrap_Swig_free_sdsd_174c5afe4e48040e;




#pragma dynimport _wrap_Swig_malloc_sdsd_174c5afe4e48040e _wrap_Swig_malloc_sdsd_174c5afe4e48040e ""
#pragma cgo_import_static _wrap_Swig_malloc_sdsd_174c5afe4e48040e
extern void _wrap_Swig_malloc_sdsd_174c5afe4e48040e(void*);
uintptr ·_wrap_Swig_malloc_sdsd_174c5afe4e48040e = (uintptr)_wrap_Swig_malloc_sdsd_174c5afe4e48040e;




#pragma dynimport _wrap_Sum_sdsd_174c5afe4e48040e _wrap_Sum_sdsd_174c5afe4e48040e ""
#pragma cgo_import_static _wrap_Sum_sdsd_174c5afe4e48040e
extern void _wrap_Sum_sdsd_174c5afe4e48040e(void*);
uintptr ·_wrap_Sum_sdsd_174c5afe4e48040e = (uintptr)_wrap_Sum_sdsd_174c5afe4e48040e;
```

But `go tool compile Apple_gc.c` shows:

```
Apple_gc.c:15: illegal character U+0023 '#'
Apple_gc.c:15: syntax error: package statement must be first
```

Why?

PS. File strange with '·' chars

Also I have tried: g++ / gcc commands
```
g++ / gcc -c -fpic Apple.cpp
g++ / gcc -c -fpic Apple_wrap.cxx
g++ / gcc -shared Apple.o Apple_wrap.o -o Apple.so

Undefined symbols for architecture x86_64:
  "__cgo_topofstack", referenced from:
      _swig_topofstack() in Apple_wrap.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by ojwb** [comment]
One for Ian, as he knows about Go.

@bernex You'll probably need to show what's in` core/Apple.i` for us to be able to help.

**Comment by bernex** [comment]
```
%module Apple
%{
#include "Apple.hpp"
%}

int Sum(int in);
```

Thank you!
Hi Ian!

**Comment by bernex** [comment]
My steps:

```
gcc -shared  Apple_wrap.o Apple.o -o Apple.so
Undefined symbols for architecture x86_64:
  "__cgo_topofstack", referenced from:
      _swig_topofstack() in Apple_wrap.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I comment code:
```
static char *_swig_topofstack() {
//  if (_cgo_topofstack) {
//    return _cgo_topofstack();
//  } else {
    return 0;
//  }
}
```
command is working.


But next not:
```
swig -c++ -go -soname libapple.dylib -use-shlib -intgosize 64 Apple.i
gcc -c -fPIC Apple.cpp                        
gcc -c -fPIC Apple_wrap.cxx 
gcc -shared  Apple_wrap.o Apple.o -o Apple.so 
go tool compile Apple.go (go tool 6g not found) - NOT CREATE ANY FILE IN FOLDER?
go tool compile Apple_gc.c (go tool 6c not found) - ERROR?
Apple_gc.c:15: illegal character U+0023 '#'
Apple_gc.c:15: syntax error: package statement must be first
```

**Comment by ianlancetaylor** [comment]
For current versions of Go (since Go 1.5) you must always use the `-cgo` option when running SWIG to generate Go code.

This is documented in the SWIG manual.  What documentation are you looking at?

**Comment by ojwb** [comment]
No further feedback from the reporter, so closing as this seems to be a usage error.

@ianlancetaylor Perhaps we should we make `-cgo` the default for SWIG 4.0?

**Comment by ianlancetaylor** [comment]
@ojwb Yes, we should.

**Comment by ojwb** [comment]
@ianlancetaylor Thanks - we don't seem to have a branch yet, so I've added a note here: https://github.com/swig/swig/wiki/SWIG-4.0-Development#go-changes

**Comment by wsfulton** [comment]
@ianlancetaylor can you do this at some point and apply to master (master is for SWIG 4.0). Also should we change the minimum supported Go version in SWIG 4.0?

**Comment by wsfulton** [comment]
Hi @ianlancetaylor, we're going to release swig 4.0 shortly (within days rather than weeks). Could you please do the change to make -cgo the default?

**Comment by wsfulton** [comment]
-cgo was made the default in 77f075b6e8196ea26aa32855a5ae1ada124a02b8.

**Comment by ianlancetaylor** [comment]
Yes, my apologies for not doing it sooner.

By the way, I'm looking at fixing the SWIG tests for the future Go 1.13, as that release changes the way that the go tool works to use modules, but the tests do not use modules.  This change should not significantly affect SWIG itself, just the testsuite.

**Comment by wsfulton** [comment]
Sounds good. BTW, we don't test very new Go versions in our test-suite (currently 1.7 on Linux and 1.10 on OSX). Is a reasonable approach to use the Gopher ppa - https://launchpad.net/~gophers/+archive/ubuntu/archive? It should be easy to configure on Travis. I can try set it up. There is no 1.12 yet though on the Gopher ppa.

**Comment by ianlancetaylor** [comment]
I think using the Ubuntu archive should be fine, yes.  Not that I'm an expert on this, and not that there is anything wrong with testing with old versions.

**Comment by wsfulton** [comment]
With regard to old versions, the Makefile output for the examples is very complicated when it should be nice and simple like the other target languages so that users can easily identify the steps required to build wrappers. I think some of this complexity is due to supporting some older versions and unnecessary command line options (like -nocgo). I'd like the Makefiles to be much simpler. Can you identify what is in them that is now unnecessary, for example, supporting Go < version 1? We can officially change the minimum supported Go version in version 4.0.0, but the minimum version to support would need deciding before the release on the weekend.

**Comment by wsfulton** [comment]
Travis uses a tool called gimme to install Go versions, so I have experimented with this instead to test version 1.2 to 1.12. Results are at https://travis-ci.org/wsfulton/swig/builds/524853562. 1.2 has some failures, is this expected or should the minimum supported version be raised?

**Comment by ianlancetaylor** [comment]
I'm not surprised that Go 1.2 doesn't work with SWIG.  I'm surprised that it works at all on Travis; on my laptop nothing before Go 1.6 works any more.

The simple rule for using SWIG with Go is to put a `.swig` file in your Go directory and run `go build`.  The Makefiles are complicated because of my desire to test old versions for which that didn't work, and my desire to use the helpers `swig_and_compile_c` and `swig_and_compile_cpp`.  If we drop those requirements then most of the tests could become "copy the files into a temporary directory, renaming the `.i` file to `.swig` or `.swigcxx`, and run `go build`".

**Comment by wsfulton** [comment]
From which version should that 'simple rule' work? How about we stop testing from that version onwards and document that as the minimum version supported. Am I correct in thinking that most Go users are unlikely to have to use an old version? Unlike users of most other languages.

**Comment by ianlancetaylor** [comment]
Just using `go build` should work from Go 1.6 on.

In general only two releases of Go are supported.  It is true that Go users are unlikely to be required to use an old version, as Go works hard to be as backward compatible as possible.
