### ISSUE TITLE
Generic exception handling

### ISSUE THREAD

**Issue by rwslord** [swig/swig#1061]
I currently have a large program that utilizes SWIG to build Python and C# extensions. 

My code throws a lot of exceptions. I currently am using code like this in my .i file:
```
%catches(test::Error_Connection, test::Error_Communication) test::MyObj::myFunction();
```

This (combined with some nasty code to generate the custom errors in C#) seems to work. However, I'm finding that it is very error prone. If I mispell something, or forget to add a line like that, I don't realize it until a user expects the function to be thrown but gets another error.

I'm reading about the [general purpose exception handling](http://www.swig.org/Doc3.0/Customization.html#exception) which I have in my code like this:

```
%exception
{
    try
    {
        $action
    }
    catch(const std::exception& ex)
    {
        SWIG_exception(SWIG_RuntimeError, ex.what());
    }
}
```

However, I want to do that for my custom exceptions, and have it get translated to the correct custom classes in the target languages. I can't seem to find a way to do this. Is it possible?

I understand this will bloat my code, but it seems less error prone which might outweigh the code bloat issue.

**Comment by ojwb** [comment]
There's no out-of-the-box switch to flip for this, but it's certainly possible to do it using `%exception`.

For Xapian's bindings, we have a central description of the C++ exception hierarchy and then generate an `except.i` per target language which handles the exceptions - e.g. this is the script to generate the one for Python:

http://git.xapian.org/?p=xapian;a=blob;f=xapian-bindings/python/generate-python-exceptions;h=f5419bfcd86e4c6c3f9de8b9f208a4b268935fdc;hb=HEAD

One useful trick to reduce the bloat is to just have the `%exception` block call a handler function, and then in that function you can re-throw the exception and catch it to determine its type:

```
%exception {
    try {
        $action
    } catch (...) {
        Xapian::SetPythonException();
        SWIG_fail;
    }
}
```

And the (generated) code of `Xapian::SetPythonException()` looks like:

```
namespace Xapian {
SWIGEXPORT void SetPythonException() {
    try {
        throw;
    } catch (Swig::DirectorException &) {
        /* This happens if a director raised an exception.  The standard SWIG
         * director exception handling code sets the Python error state if
         * necessary, so we don't need to do anything. */
    } catch (const Xapian::WildcardError &e) {
        SWIG_Python_Raise(SWIG_NewPointerObj((new Xapian::WildcardError(e)),
                                             SWIGTYPE_p_Xapian__WildcardError,
                                             SWIG_POINTER_OWN),
                          "Xapian::WildcardError",
                          SWIGTYPE_p_Xapian__WildcardError);
    } catch (const Xapian::RangeError &e) {
        SWIG_Python_Raise(SWIG_NewPointerObj((new Xapian::RangeError(e)),
                                             SWIGTYPE_p_Xapian__RangeError,
                                             SWIG_POINTER_OWN),
                          "Xapian::RangeError",
                          SWIGTYPE_p_Xapian__RangeError);
/// and so on
    } catch (const std::exception& e) {
        SWIG_Error(SWIG_RuntimeError, e.what());
    } catch (...) {
        SWIG_Error(SWIG_UnknownError, "unknown error in Xapian");
    }
}
```

The code to throw a wrapped object as an exception is annoyingly somewhat language-specific though.

This is really a question rather than a bug, so closing.

**Comment by rwslord** [comment]
Ok, Thank you! Is there a better place to ask questions?

**Comment by ojwb** [comment]
> Is there a better place to ask questions?

I'd suggest the swig-user list - many more people read that than read newly created tickets here.

**Comment by jleni** [comment]
Sorry to continue over this issue but it this still the case?
Would it make sense to add an *.i extension to handle these cases?

**Comment by wsfulton** [comment]
Exception handling is rather application specific. Each application ought to have their own tailored SWIG code (possibly in a separate .i file) for exception handling. I don't see what extra interface files that SWIG can provide other than the exception.i and std_except.i files already provided. These cover standard (STL) exceptions and some mappings to language specific exceptions, that may or may not be suitable to everyone. Any other application exceptions necessarily require custom code to handle them, such as the two application specific (Xapian) exceptions that @ojwb posted above. The DirectorException is also mostly not used by projects, so also requires custom additions.

**Comment by jleni** [comment]
Yes, it makes sense. 
Thanks for SWIG!
