### ISSUE TITLE
SWIG optimization: do not require default constructor for the returning objects

### ISSUE THREAD

**Issue by luav** [swig/swig#1062]
## Optimization Proposal
Currently SWIG requires default constructors for the wrapping C++ struct/class to return their objects, which seems could be avoided providing the following **benefits**:
 - *better usability* by the "out of the box" wrapping of the existing well-designed classes that expect mandatory initialization (intentionally does not provide public default constructor)
- *better runtime performance* of the wrapper calls, performing initialization on the construction and avoiding the redundant copy operation (which also requires availability o the copy constructor or assignment operator).

This issue causes especial inconvenience for the members of STL containers (see #866) and accessor/proxy classes (see #322).

## Example
Wrapping C++ data structures:
```c++
#include <vector>

typedef unsigned  Id;
typedef float  LinkWeight;

template <bool WEIGHTED=true>
struct InpLink {
	using Weight = LinkWeight;
	constexpr static bool  IS_WEIGHTED = true;

	Id  id;  //!< Dest node id, expected to be MANDATORY specidied
	Weight  weight;  //!< Link weight

	InpLink(Id lid, Weight lweight=SimpleLink<Weight>::weight)
	: id(lid), weight(lweight)  {}
};

typedef std::vector<InpLink>  InpLinks;
```
SWIG generates the following wrapper code for the functions returning the `InpLink` object, first constructing the empty object (unnecessary and causes the outlined issues) and only afterwards assigning the value:
```java
SWIGEXPORT jlong JNICALL Java_info_exascale_daoc_daocJNI_InpLinks_1doRemove(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  std::vector< InpLink< true > > *arg1 = (std::vector< InpLink< true > > *) 0 ;
  jint arg2 ;
  std::vector< InpLink< true > >::value_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< InpLink< true > > **)&jarg1; 
  arg2 = jarg2; 
  try {
    result = std_vector_Sl_InpLink_Sl_true_Sg__Sg__doRemove(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  
  *(std::vector< InpLink< true > >::value_type **)&jresult = new std::vector< InpLink< true > >::value_type((const std::vector< InpLink< true > >::value_type &)result); 
  return jresult;
}
```
**Suggesting solution**, which has less demands to the wrapping object, works faster and seems does not have any disadvantages comparing to the currently generating code is:
```java
SWIGEXPORT jlong JNICALL Java_info_exascale_daoc_daocJNI_InpLinks_1doRemove(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  std::vector< InpLink< true > > *arg1 = (std::vector< InpLink< true > > *) 0 ;
  jint arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< InpLink< true > > **)&jarg1; 
  arg2 = jarg2; 
  try {
    std::vector< InpLink< true > >::value_type result = std_vector_Sl_InpLink_Sl_true_Sg__Sg__doRemove(arg1,arg2);
    // Output typemap code goes here <<<
    *(std::vector< InpLink< true > >::value_type **)&jresult = new std::vector< InpLink< true > >::value_type((const std::vector< InpLink< true > >::value_type &)result); 
    return jresult;
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
```

Such implementation affects typemaps for the output results only in terms of the inserting their code inside the possible exception handler that wraps the returning value.

**Comment by ojwb** [comment]
If you think you can see how to improve the generated code, please submit a patch (as a PR is best, then CI will run the testsuite for most languages).

**Comment by luav** [comment]
Olly, I know how the code should look like for the best performance and portability (among the C++ standards), but to implement this in SWIG I should also learn how it generates the code... SWIG almost a black box for me yet.

**Comment by srohit0** [comment]
It's annoying working around SWIG enforcement of requiring default constructors. Some object semantics (like bit_vector or tensors) do not allow default constructors.

**Comment by wsfulton** [comment]
I've fixed the bugs in the original example code to wrap it successfully:
```swig
%include <std_vector.i>

%inline %{
template<typename T> struct SimpleLink {
  static T weight;
};
template<typename T> T SimpleLink<T>::weight = 0;
%}

%inline %{
#include <vector>

typedef unsigned  Id;
typedef float  LinkWeight;

template <bool WEIGHTED=true>
struct InpLink {
	using Weight = LinkWeight;
	constexpr static bool  IS_WEIGHTED = true;

	Id  id;  //!< Dest node id, expected to be MANDATORY specidied
	Weight  weight;  //!< Link weight

	InpLink(Id lid, Weight lweight=SimpleLink<Weight>::weight)
	: id(lid), weight(lweight)  {}
};

typedef std::vector<InpLink<true>>  InpLinks;
%}

%template(InpLinkTrue) InpLink<true>;
%template(InpLinks) std::vector<InpLink<true>>;
```
The relevant generated code is:
```
SWIGEXPORT jlong JNICALL Java_exampleJNI_InpLinks_1doRemove(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  std::vector< InpLink< true > > *arg1 = (std::vector< InpLink< true > > *) 0 ;
  jint arg2 ;
  SwigValueWrapper< InpLink< true > > result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< InpLink< true > > **)&jarg1; 
  arg2 = jarg2; 
  try {
    result = std_vector_Sl_InpLink_Sl_true_Sg__Sg__doRemove(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  *(std::vector< InpLink< true > >::value_type **)&jresult = new std::vector< InpLink< true > >::value_type((const std::vector< InpLink< true > >::value_type &)result); 
  return jresult;
}
```
Note the `SwigValueWrapper` which effectively does the single instantiation is desired. SWIG will use `SwigValueWrapper` when a type without a default constructor is parsed. Read about it in the 'Pass and return by value' section in the docs http://swig.org/Doc4.0/SWIGPlus.html#SWIGPlus_nn19. 

Also read about the `optimal` attribute in the "out" typemapat http://swig.org/Doc4.0/Typemaps.html#Typemaps_optimal.
