### ISSUE TITLE
SWIG wrapper generator does not respect `using namespace` inside a namespace

### ISSUE THREAD

**Issue by luav** [swig/swig#1063]
The following interface definition results in the failed wrapper compilation if `namespace tns` is defined (as it shown):
```c++
%module extend
%{
#include <vector>
#include <utility>  // move()
%}
%include <std_vector.i>
using std::vector;

%inline %{
namespace tns {
using std::vector;

struct Obj {
	using Id = unsigned;
	Id id;
	
	Obj(Id id): id(id)  {}
};

struct Holder {	
	using Vec = vector<Obj>;
	Vec  items;
	
	Vec release(Vec&& vec)
	{
		std::swap(items, vec);
		return std::move(vec);
	}
};
}  // tns
%}
```
Yielding the following error:
```
./extend_wrap.cxx: In function ‘jlong Java_extendJNI_Holder_1release(JNIEnv*, jclass, jlong, jobject, jlong)’:
./extend_wrap.cxx:356:21: error: ‘vector’ was not declared in this scope
   SwigValueWrapper< vector< tns::Obj > > result;
                     ^
```
The compilation is successful if the namespace is commented.

*Compilation:*
```
$ swig -v -c++ -java -outdir java extend.i
$ g++ -v -std=c++14 -fPIC -c ./extend_wrap.cxx -I${JAVA_HOME}/include -I${JAVA_HOME}/include/linux
```
*Environment:*
SWIG Version 4.0.0
Compiled with g++ [x86_64-pc-linux-gnu]
Configured options: +pcre

*Note:* relates to #1051 it terms of the issues with namespace, but the issue is distinct.

**Comment by luav** [comment]
In the wrapper file (`extend_wrap.cxx`) the `using std::vector;` declaration should be duplicated before the definition of the wrapping functions to have compilable code. It should be the easy fix.

**Comment by luav** [comment]
Note that
```c++
%inline %{
namespace tns {
using std::vector;
```
causes the compilation error, but 
```c++
%inline %{
using std::vector;
namespace tns {
```
works fine.

**Comment by wsfulton** [comment]
Using declarations to templates were missing in SWIG's internal typedef tables.
Fixed in 96e99416d76c3e0201a7b60417a0c24f845ba5b8 and 9f454234b1e15e421c51c20b42cb1d78a66800ea.

**Comment by luav** [comment]
Thanks @wsfulton! The fix solves several issues, but has some side effects (another issues).

Before this fix the following code in the interface worked fine:
```c++
using namespace daoc;  // Note: RawMembership is declared inside the namespace daoc
...
// Disable setters generation, since the RawMembership::clusters attribute lacks the copy constructor
%immutable RawMembership::clusters;
%template(RawMembership) RawMembership<WeightedLinks>;
```
But after I updated to the latest master, `%immutable RawMembership::clusters` is ignored causing the failed compilation until the explicit namespace specification:
```c++
%immutable daoc::RawMembership::clusters;
%template(RawMembership) RawMembership<WeightedLinks>;
```

Should I open the new "Issue" or the problem will be processed inside this one?

**Comment by wsfulton** [comment]
There is still some way to go to fixing all the `using` bugs, but I'll keep knocking them on the head. Please open a new issue with all the details to replicate for this immutable problem and reference this issue. I try and give precedence to regressions.
