### ISSUE TITLE
Ruby test li_std_wstring fails on machine with byte order Big Endian

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#1064]
I've run test build of the SWIG latest version from git.

All tests passed on architectures with byte order Little Endian.
However, one of Ruby test failed only on ppc64 and s390x with byte order Big Endian.

```
checking ruby testcase li_std_wstring (with run test)
../../../Lib/std/std_basic_string.i:235: Warning 365: operator+= ignored
../../../Lib/std/std_wstring.i:8: Warning 378: operator!= ignored
["./li_std_wstring_runme.rb:26:in `<main>'"]: incompatible character encodings: UTF-8 and UTF-32LE
make[1]: *** [Makefile:61: li_std_wstring.cpptest] Error 1
checking ruby testcase primitive_types (with run test)
```

If you want more info the log files for all architectures can be found here:
https://koji.fedoraproject.org/koji/taskinfo?taskID=21088227

root.log - contains info about installed packages in buildroot
hw_info.log - provides info about build machine

**Comment by wsfulton** [comment]
Hi @jplesnik, I think the failing line was:
`swig_assert_equal("Li_std_wstring.test_pointer_out", "'x'", binding)` which doesn't exist any more since the testcase was refactored in a9a7b03ba6557a6f9c8c8b284d907d6a7017e989. Please re-open if similar issue still exists.

**Comment by jplesnik** [comment]
The same test fails with different error on s390x now.

```
checking ruby testcase li_std_wstring (with run test)
["./li_std_wstring_runme.rb:41:in `<main>'"]: FAILED: Li_std_wstring.test_equal_abc(s) - 
make[1]: *** [Makefile:70: li_std_wstring.cpptest] Error 1
```
https://koji.fedoraproject.org/koji/taskinfo?taskID=41336754

**Comment by ojwb** [comment]
@jplesnik Are you still seeing this?

**Comment by kkaempf** [comment]
swig 4.0.2 has this fixed:
```
2020-06-06  andreas-schwab
            [Ruby] #1801 Fix encoding on big endian systems when wrapping std::wstring.
```

**Comment by jplesnik** [comment]
The test passed with swig 4.0.2 and current Fedora rawhide (F36) on all architectures.
