### ISSUE TITLE
`using namespace X` and explicit namespace qualification `X::` treated differently in the SWIG interface declarations

### ISSUE THREAD

**Issue by luav** [swig/swig#1066]
The following interface `template_class.i` illustrates differently treated namespace qualifiers interpretation in the SWIG interface declaration file (in the global namespace):
```c++
%module template_class

%inline %{
namespace daoc {

using Id = unsigned;
using LinkWeight = float;

template <bool WEIGHTED=false>
struct InpLink {
	using Weight = LinkWeight;  //!< \copydoc LinkWeight

	constexpr static bool  IS_WEIGHTED = WEIGHTED;
	constexpr static Weight  weight = 1; // SimpleLink<Weight>::weight;

	Id  id;  //!< Dest node id

	InpLink(Id lid=0): id(lid)  {}
};

template <>
struct InpLink<true> {
	using Weight = LinkWeight;  //!< \copydoc LinkWeight

	constexpr static bool  IS_WEIGHTED = true;

	Id  id;  //!< Dest node id
	Weight  weight;  //!< Link weight

	InpLink(Id lid=0, Weight lweight=1)  // SimpleLink<Weight>::weight
	: id(lid), weight(lweight)  {}
};

}  // daoc
using namespace daoc;
%}

using namespace daoc;

%template(InpLink) daoc::InpLink<false>;  //!< Simple input link
```
The wrapper generation yields the following warning:
```
template_class.i:55: Warning 302: Identifier 'InpLink' redefined (ignored) (Renamed from 'InpLink< false >'),
template_class.i:24: Warning 302: previous definition of 'InpLink'.
```
However, replacing the template instantiation into:
```c++
%template(InpLink) InpLink<false>;  //!< Simple input link
```
provides silent successful wrapper generation, which means there **two distinct bugs in the wrapper generation**:
&nbsp;&nbsp;**1.** `using namespace daoc;` is not respected even for the global namespace (the interface file), because
```c++
using namespace daoc;
%template(InpLink) daoc::InpLink<false>;
```
and
```c++
using namespace daoc;
%template(InpLink) InpLink<false>;
```
are treated differently by SWIG (the first one yields the listed warning).
&nbsp;&nbsp;**2.** Declarations from distinct namespaces are mixed: `%template(InpLink) daoc::InpLink<false>;` should generate `InpLink` interface class in the global namespace for the `daoc::InpLink` template (located in the `daoc` namespace). So, there should not be any warnings on wrapper generation for the initially listed example.

**Accessory Information**
*Wrapper Generation:*
```
$ swig -v -c++ -python template_class.i
```

*Environment:*
SWIG Version 4.0.0
Compiled with g++ [x86_64-pc-linux-gnu]
Configured options: +pcre

*Notes:*
1. This issue is distinct from #732, since it relates to the global namespace rather than namespace qualifier interpretation in the template parameters.
1. This issue is related to #1065 that show very confusing behavior cause by various bugs in SWIG.

**Comment by wsfulton** [comment]
The restriction on template name for the target language not being able to be the same as the C++ template name has now removed, see #1100. Using declarations and using directives are now supported by %template, see #1063. Together they fix the issues reported here.
