### ISSUE TITLE
Unexpected mutual influence of distinct template instantiations in SWIG interface

### ISSUE THREAD

**Issue by luav** [swig/swig#1067]
Consider the following example, which has errors in the wrapper generation mentioned by @ojwb in #732 (SWIG bug related to the namespace interpretation in the template parameters):
```c++
%module template_class
%{
#include <vector>
%}
%include <std_vector.i>

using std::vector;

%inline %{
namespace daoc {

using Id = unsigned;
using LinkWeight = float;

template <bool WEIGHTED=false>
struct InpLink {
	using Weight = LinkWeight;  //!< \copydoc LinkWeight

	constexpr static bool  IS_WEIGHTED = WEIGHTED;
	constexpr static Weight  weight = 1; // SimpleLink<Weight>::weight;

	Id  id;  //!< Dest node id

	InpLink(Id lid=0): id(lid)  {}
};

template <>
struct InpLink<true> {
	using Weight = LinkWeight;  //!< \copydoc LinkWeight

	constexpr static bool  IS_WEIGHTED = true;

	Id  id;  //!< Dest node id
	Weight  weight;  //!< Link weight

	InpLink(Id lid=0, Weight lweight=1)  // SimpleLink<Weight>::weight
	: id(lid), weight(lweight)  {}
};

}  // daoc
using namespace daoc;
%}

%template(SInpLink) InpLink<false>;  //!< Simple input link
%template(SInpLinks) vector<InpLink<false>>;  // Items<InpLink<false>>;
```
The errors:
```
/usr/local/share/swig/4.0.0/std/std_vector.i:87: Error: Can't copy typemap (directorout) std::vector< daoc::InpLink< false >,std::allocator< daoc::InpLink< false > > > = std::vector< daoc::InpLink< false >,std::allocator< daoc::InpLink< false > > > &DIRECTOROUT
/usr/local/share/swig/4.0.0/std/std_vector.i:87: Error: Can't copy typemap (in) std::vector< daoc::InpLink< false >,std::allocator< daoc::InpLink< false > > > *INPUT = std::vector< daoc::InpLink< false >,std::allocator< daoc::InpLink< false > > > *INOUT
...
```
The unexpected thing, which is the subject of this issue is that changing `SInpLink` declaration to
```c++
%template(SInpLink) daoc::InpLink<false>;  //!< Simple input link
```
provides successful wrapper generation and compilation.

It means that instantiation of the 'daoc::InpLink<false>' as `SInpLink` **affects** also how another types (`vector<InpLink<false>>`) are interpreted. Such side effects should not exist and might cause confusing situations in more complex environment, see #1065.

**Environment:**
SWIG Version 4.0.0
Compiled with g++ [x86_64-pc-linux-gnu]
Configured options: +pcre

**Wrapper Compilation:**
```sh
$ swig -v -c++ -python template_class.i
$ g++ -std=c++14 -fPIC -c ./template_class_wrap.cxx -I/usr/include/python2.7 && g++ -shared -L. template_class_wrap.o -o _template_class.so
```

**Comment by wsfulton** [comment]
Recent changes to support using declarations and using directives in %template means that this is all okay now, in particular see 32a454cfef15154523c014bb8c95496989b3bd2b. Previously the C++ template needed to be fully qualified or declared with in the correct namespace scope to get successful wrappers.
