### ISSUE TITLE
C++ namespace declaration does not work inside the SWIG `%inline` block

### ISSUE THREAD

**Issue by luav** [swig/swig#1068]
According to the [SWIG docs](http://swig.org/Doc3.0/SWIG.html#SWIG_nn43) `%inline` block seems should support any valid C++ code. However, the following interface file `nstpl.i`:
```c++
%module nstpl
%{
#include "nstpl.hpp"
using namespace nst;
%}

%include "nstpl.hpp"
using namespace nst;
```
is compiled well, where is the expected shorter equivalent
```c++
%module nstpl

%inline %{
#include "nstpl.hpp"
using namespace nst;
%}
```
yields a wrapper generation error:
```
nstpl.i:13: Error: Nothing known about namespace 'nst'
```
The header `nstpl.hpp` can contain just the namespace definition:
```c++
namespace nst {
typedef int  Int;
}  // nst
```
Note that
```c++
%module nstpl

%inline %{
#include "nstpl.hpp"
%}
using namespace nst;
```
yields the same error. Thus, the namespaces defined in the files included into the `%inline` blocks are ignored, which is *definitely a bug*.

**Environment:**
SWIG Version 4.0.0
Compiled with g++ [x86_64-pc-linux-gnu]
Configured options: +pcre

**Comment by ojwb** [comment]
Your first two examples aren't equivalent as `#include` is not the same as `%include`, so closing as invalid.

This is really not to do with namespaces, it's just about how `#include` works - if you run with `-includeall` then this works, because SWIG follows the `#include`.

**Comment by luav** [comment]
Thanks for the clarification @ojwb. It would be nice to mention this in the [Inlined code blocks](http://swig.org/Doc3.0/SWIG.html#SWIG_nn43).

**Comment by ojwb** [comment]
To propose an update to the manual, open a PR.

**Comment by wsfulton** [comment]
BTW, the manual is in the Doc/Manual directory in case you aren't sure where the source for it is.
