### ISSUE TITLE
Bug in xml.cxx in swig 3.0.12

### ISSUE THREAD

**Issue by marwar-office** [swig/swig#1074]
In line 312:
      } else if (!xmllite && Cmp(k, "typescope") == 0) {

but the corresponding category is called "typescopes" with an "s" at the end. This generates a lot of strange output in the xml.

**Comment by wsfulton** [comment]
Probably you are referring to [xml.cxx line 139](https://github.com/swig/swig/blob/rel-3.0.12/Source/Modules/xml.cxx#L139). However, there is nothing referring to "typescopes" in the source code or parse tree. Are you looking at some modified unofficial version or something? The parse tree does contain "typescope" elements.

**Comment by marwar-office** [comment]
Hello Mr. Fulton,

actually I downloaded SWIG-Win-3.0.12 and in the folder 
swigwin-3.0.12\Source\Modules
There is the following file:

I just verified that it is still identical to the one from the downloaded 
archive. And in that file there is this line of code in this function:

  void Xml_print_attributes(Node *obj) {
    String *k;
    indent_level += 4;
    print_indent(0);
    Printf(out, "<attributelist id=\"%ld\" addr=\"%p\" >\n", ++id, obj);
    indent_level += 4;
    Iterator ki;
    ki = First(obj);
    while (ki.key) {
      k = ki.key;
      if ((Cmp(k, "nodeType") == 0)
          || (Cmp(k, "firstChild") == 0)
          || (Cmp(k, "lastChild") == 0)
          || (Cmp(k, "parentNode") == 0)
          || (Cmp(k, "nextSibling") == 0)
          || (Cmp(k, "previousSibling") == 0)
          || (*(Char(k)) == '$')) {
        /* Do nothing */
      } else if (Cmp(k, "module") == 0) {
        Xml_print_module(Getattr(obj, k));
      } else if (Cmp(k, "baselist") == 0) {
        Xml_print_baselist(Getattr(obj, k));
      } else if (!xmllite && Cmp(k, "typescope") == 0) { <-- BUG!
        Xml_print_typescope(Getattr(obj, k));
      } else if (!xmllite && Cmp(k, "typetab") == 0) {
        Xml_print_typetab(Getattr(obj, k));
      } else if (Cmp(k, "kwargs") == 0) {
        Xml_print_kwargs(Getattr(obj, k));
      } else if (Cmp(k, "parms") == 0 || Cmp(k, "pattern") == 0) {
        Xml_print_parmlist(Getattr(obj, k));
      } else if (Cmp(k, "catchlist") == 0 || Cmp(k, "templateparms") == 0) 
{
        Xml_print_parmlist(Getattr(obj, k), Char(k));
      } else {
        DOH *o;
        print_indent(0);
        if (DohIsString(Getattr(obj, k))) {
          String *ck = NewString(k);
          o = Str(Getattr(obj, k));
          Replaceall(ck, ":", "_");
          Replaceall(ck, "<", "&lt;");
          /* Do first to avoid aliasing errors. */
          Replaceall(o, "&", "&amp;");
          Replaceall(o, "<", "&lt;");
          Replaceall(o, "\"", "&quot;");
          Replaceall(o, "\\", "\\\\");
          Replaceall(o, "\n", "&#10;");
          Printf(out, "<attribute name=\"%s\" value=\"%s\" id=\"%ld\" 
addr=\"%p\" />\n", ck, o, ++id, o);
          Delete(o);
          Delete(ck);
        } else {
          o = Getattr(obj, k);
          String *ck = NewString(k);
          Replaceall(ck, ":", "_");
          Printf(out, "<attribute name=\"%s\" value=\"%p\" id=\"%ld\" 
addr=\"%p\" />\n", ck, o, ++id, o);
          Delete(ck);
        }
      }
      ki = Next(ki);
    }
    indent_level -= 4;
    print_indent(0);
    Printf(out, "</attributelist >\n");
    indent_level -= 4;
  }

I was actually looking for something to read the data structures from C++ 
files and generating my own code based on it. At first I thought that I 
would need to write my own wrapper but now I think just a bugfix in the 
xml wrapper should provide the xml I need.

kind regards,
Martin

Mit freundlichen Grüßen / Best regards 

Dr. Martin Warnecke
Integration and Verification Engineering Ulm  
C ADAS SEN PD EM EAE IVE

Continental
Division Chassis and Safety

Rechnungsanschrift/Billing address: 
ADC Automotive Distance Control Systems GmbH 
Peter-Dornier-Str. 10, D-88131 Lindau, Germany

Besucheradresse / Visiting address:
ADC Automotive Distance Control Systems GmbH, 
Lise-Meitner Strasse 10, 89081 Ulm, Germany

Tel. +49 (0) 731 55035 2481
Tel. +49 (0) 151 746 164 72
Fax +49 (0) 8382 / 969922 - 371
Email: martin.warnecke@continental-corporation.com
http://www.continental-corporation.com
________________________________________________________________________

ADC Automotive Distance Control Systems GmbH, Peter-Dornier-Str. 10, 
D-88131 Lindau/Bodensee
Vorsitzender des Aufsichtsrats / Chairman of the Supervisory Board: Werner 
Volz
Geschaeftsfuehrer/Managing Director: Karlheinz Haupt, Uwe Grau
Sitz der Gesellschaft/Registered Office: Lindau
Registergericht/Registered Court: Amtsgericht Kempten HRB 6408
USt.-ID-Nr./VAT-ID-No. DE 812185464
________________________________________________________________________

Proprietary and confidential. Distribution only by express authority of
Continental AG or its subsidiaries.



Von:    William S Fulton <notifications@github.com>
An:     swig/swig <swig@noreply.github.com>, 
Kopie:  marwar-office <martin.warnecke@continental-corporation.com>, 
Author <author@noreply.github.com>
Datum:  22.08.2017 08:07
Betreff:        Re: [swig/swig] Bug in xml.cxx in swig 3.0.12 (#1074)



Probably you are referring to xml.cxx line 139. However, there is nothing 
referring to "typescopes" in the source code or parse tree. Are you 
looking at some modified unofficial version or something? The parse tree 
does contain "typescope" elements.

**Comment by wsfulton** [comment]
There is nothing in the source code with an 's' after typescope. The parse tree contains nodes called typescope not typescopes. Possibly you have a corrupted parse tree due to a memory bug. How did you debug this to see typescopes in the parse tree? Can you post some input C++ code somewhere to demonstrate what you are seeing. Preferably you just post the smallest possible piece of C++ code that causes what you see. You could run with the `-E` option and pipe the resulting preprocessed output into a file and post that somewhere as someone else can then use that as an input on their own machine. Note that you can also run with the `-debug-top 4` option to display the parse tree.

**Comment by marwar-office** [comment]
You are right, the mistake was on my side.
