### ISSUE TITLE
Error Passing bool return types

### ISSUE THREAD

**Issue by ayush1999** [swig/swig#1078]
Here are my codes:
(Sorry for the long description)
prime.c:
```
#include "prime.h"
#include <stdio.h>
bool prime(int x){
    int count=0,i;
    for(i=2;i<x;i++){
    	if (x%i==0){
    		count++;
    		break;
    	}
    	else continue;
    }
if (count==0){
	return True;
}
else
	return False;
}
```

prime.h:
```
#ifndef PRIME_H
#define PRIME_H

bool prime(int x);

#endif
```

prime.i:
```
/* prime.i */
/* swig interface file*/
%module prime
%{
#include <stdio.h>

#include "prime.h"
extern bool prime(int x);	
%}

extern bool prime(int x);`

```
And finally, setup.py:
```
from distutils.core import setup, Extension
name="prime"
version="1.0"

ext_modules= Extension(name='_prime', sources=["prime.i","prime.c"])

setup(name=name,
	version=version,
	ext_modules=[ext_modules])

```

Whenever I run `python setup.py install` in the terminal, I get the error: `Error: Unknown type name bool`

Why is this happening?

**Comment by ojwb** [comment]
`bool` is indeed an unknown type in C code.  SWIG needs to be run with `-c++` to understand C++ types such as `bool`.

I don't know anything about distutils' support for SWIG, but I'd suggest you try giving your C++ source a C++ extension (e.g. `.cc`, `.cxx` or `.cpp`) - `.c` indicates C source code.

**Comment by ayush1999** [comment]
Ah, I see. Also, @ojwb What does `Error: Unknown type name class` mean? And how can I remove this?

**Comment by ojwb** [comment]
Again, C vs C++.  If you're wrapping C++ code, the tools need to know that.

Closing this ticket - this isn't a bug.
