### ISSUE TITLE
f(std::shared_ptr<D>& out) will corrupt class D in C# when D derives from B

### ISSUE THREAD

**Issue by Cpt-Kork** [swig/swig#1084]
Consider the following sample code, which breaks .NET proxy classes (i.e. classes generated by SWIG)  when the classes participate in a hierarchy. This might also affect other target languages.

**- just ignore all code comments for now -**
`C++`
```C++
class B { ... };
class D : public B { ... };
void f(std::shared_ptr<D>& out)
{                                     // &out == 0x0a ~> 0xd1
   out = std::shared_ptr<D>(new D()); // &out == 0x0a ~> 0xd2
}
```
The corresponding code calling `f()` from `C#` may look like:
`C#`
```C#
var d = new D(); // (1) d.swigCPtr ~> 0x0a ~> 0xd1, ((B) d).swigCPtr ~> 0x0b ~> 0xd1
f(d);
d.Foo();         // (2) d.swigCPtr ~> 0x0a ~> 0xd2, ((B) d).swigCPtr ~> 0x0b ~> 0xd1 [sic: 0xd1]
```
In this case the following constructor-code is generated by SWIG for `class D` and `class B`:
`C#`
```C#
public class B
{
    internal B(IntPtr cPtr, bool cMemoryOwn)
    {
        swigCMemOwnBase = cMemoryOwn;
        swigCPtr = new HandleRef(this, cPtr); // swigCPtr ~> 0x0b ~> 0xd1
    }
}
public class D : B
{
    public D() : this(NativeInterfacePINVOKE.new_D(), true) { }

    internal D(IntPtr cPtr, bool cMemoryOwn)
        : base(NativeInterface.D_SWIGSmartPtrUpcast(cPtr), true)
    {
        swigCMemOwnDerived = cMemoryOwn;
        swigCPtr = new HandleRef(this, cPtr); // swigCPtr ~> 0x0a ~> 0xd1
    }
}

```
using following SWIG helper functions in `swig.cpp`:
`C++`
```C++
void* CSharp_NativeInterface_new_D___()
{
    auto result = new std::shared_ptr<D>(new D());            // result == 0x0a ~> 0xd1
    return result;
}

std::shared_ptr<B>* CSharp_NativeInterface_D_SWIGSmartPtrUpcast___(std::shared_ptr<D>* jarg1)
{                                                             // jarg == 0x0a ~> 0xd1
    auto result = jarg1 ? new std::shared_ptr<D>(*jarg1) : 0; // result == 0x0b ~> 0xd1
    return result;                                            // C++: now *jarg and *result share ownership of 0xd1
}
```

When `D` is constructed in `(1)` two unrelated `std::shared_ptr<>*` will be created and kept in `d.swigCPtr` and `((B) d).swigCPtr` that will share the same ownership ([C++ reference](http://en.cppreference.com/w/cpp/memory/shared_ptr/shared_ptr)).

Now, when `f()` manipulates `d` in `(2)` only `d.swigCPtr` is updated while `((B) d).swigCPtr` still points to the old instance. Thus `f()`corrupts the state of `d` instance in C# - as its derived part is now represented by a different instance of `D` in C++ than its `base` part. Consider the code comments for more clarity.

May be it's sufficient to create and share just one pointer in `D` and `B` from C#.

**[Update, 2017-09-06]**
The described problem might affect plain-old pointers as well, as there is following code snippet inside `csharp.swg` calling `base` with `SWIGUpcast(cPtr)`:
```
// Derived proxy classes
%typemap(csbody_derived) TYPE %{
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  PTRCTOR_VISIBILITY $csclassname(global::System.IntPtr cPtr, bool cMemoryOwn) 
    : base($imclassname.$csclazznameSWIGUpcast(cPtr), cMemoryOwn) { ... }
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
However, a simple solution to this problem appears to be changing the `%typemap(csbody_derived)` for both plain-old and shared pointers as follows:
```
  ...
  PTRCTOR_VISIBILITY $csclassname(global::System.IntPtr cPtr, bool cMemoryOwn) 
    : base(cPtr, false) { ... }
           ^^^^  ^^^^^
```
Thus, when constructing derived classes (1) no additional pointers will ever be constructed for their bases as `cPtr` are just passed from the derived classes to their bases and (2) since `cMemoryOwn` is set to `false` the pointer will never be deleted by anyone other than by the constructed (derived) class itself. Whereas when base classes are constructed on their own - i.e. `var b = new B()` - they will still create corresponding pointers and also delete them.

**Comment by wsfulton** [comment]
First, sorry, that this hasn't been looked at earlier. I'm afraid that I can't follow what you are really doing as it seems you have highly customised the generated code as swig.cpp is not something that SWIG generates. You need to use `%shared_ptr`. If you are using %shared_ptr as you havn't shown exactly what your input code is, then you may be interested in the upcast fix in #1533 which has has recently been released in swig-4.1.0.

If you still see a problem, please reopen.
