### ISSUE TITLE
`%template` and `%rename` prevent naming interface classes/functions with the C++ template name (break the former interfaces)

### ISSUE THREAD

**Issue by luav** [swig/swig#1100]
In the latest version of SWIG `%rename` and `%template` prevent alias creation for the template in the *global namespace* in case the alias name matches the template name from another namespace. It worked fine in the begin of August, and it seems was broken after 96e9941, see also #1093 (*update: no, it was broken by another commit...*).

The interface file `template_class.i`:
```c++
%module template_class
%{
#include <vector>
%}
%include <std_vector.i>

using std::vector;

%inline %{
namespace daoc {

using Id = unsigned;
using LinkWeight = float;

template <bool WEIGHTED=false>
struct InpLink {
	using Weight = LinkWeight;  //!< \copydoc LinkWeight

	constexpr static bool  IS_WEIGHTED = WEIGHTED;

	Id  id;  //!< Dest node id
	//constexpr static Weight  weight = 1; // SimpleLink<Weight>::weight;
	Weight  weight;  //!< Link weight

	InpLink(Id lid=0): id(lid)  {}
};

template <>
struct InpLink<true> {
	using Weight = LinkWeight;  //!< \copydoc LinkWeight

	constexpr static bool  IS_WEIGHTED = true;

	Id  id;  //!< Dest node id
	Weight  weight;  //!< Link weight

	InpLink(Id lid=0, Weight lweight=1)  // SimpleLink<Weight>::weight
	: id(lid), weight(lweight)  {}
};

}  // daoc
using namespace daoc;
%}

%template(SInpLink) InpLink<false>;  //!< Simple input link
%template(InpLink) InpLink<true>;  //!< Weighted input link

//!< Simple input links
%template(SInpLinks) vector<daoc::InpLink<false>>;  // Items<InpLink<false>>;
////!< Weighted input links
%template(InpLinks) vector<daoc::InpLink<true>>;  // Items<InpLink<true>>;
```
The wrapper generation yields the following warning:
```sh
...
Starting language-specific parse...
template_class.i:53: Warning 302: Identifier 'InpLink' redefined (ignored) (Renamed from 'InpLink< true >'),
template_class.i:24: Warning 302: previous definition of 'InpLink'.
Processing types...
```
All `%template` instantiations create respective wrapper classes except the `InpLink`. Note that 'InpLink<bool>' template declaration is located in the `daoc` namespace (`template_class::daoc`), where is `%template(InpLink)` is instantiated in the global namespace (`template_class`) and should not cause any collisions.

**Environment:**
SWIG Version 4.0.0
Compiled with g++ [x86_64-pc-linux-gnu]
Configured options: +pcre

**Comment by luav** [comment]
As a workaround I tried to rename the template(s) in the interface file to retain the existing interface of the generating wrappers:
```c++
%template(SInpLink) InpLink<false>;  //!< Simple input link
%rename(TInpLink) daoc::InpLink;
%template(WInpLink) InpLink<true>;  //!< Weighted input link
%template(InpLink) TInpLink<true>;  // => Error: Template 'TInpLink' undefined.
//%template(InpLink) TInpLink;  // => Error: Syntax error in input(1).
```
but it does't work:
```sh
template_class.i:57: Error: Template 'TInpLink' undefined.
```

How can I retain the wrappers interface?  
The main interface consisted of the classes and functions having the same names as the respective templates (with default parameters of the templates). This *seemingly insignificant issue*, a side effect of the fixes, **totally breaks the whole interface of ALL existing library wrappers**..

**Comment by luav** [comment]
Omission of the namespace declaration (commenting of `using namespace daoc;`) clarifies the issue.
For these definition in the interface file:
```c++
%template(SInpLink) InpLink<false>;  // Error is expected here (missed namespace)
...
%template(InpLink) daoc::InpLink<true>;  // In theory, this line should be compilable
```
the wrapper generation yields:
```sh
template_class.i:54: Error: Template 'InpLink' undefined.
template_class.i:70: Warning 302: Identifier 'InpLink' redefined (ignored) (Renamed from 'InpLink< true >'),
template_class.i:24: Warning 302: previous definition of 'InpLink'.
```
The template is instantiated in the SOURCE namespace instead of the current (target) namespace (expected by the specification), which is clearly the bug in the SWIG implementation.

Another test with the explicit target namespace (`using namespace daoc;` is retained):
```c++
namespace wci {
%template(SInpLink) InpLink<false>;  //!< Simple input link
...
%template(InpLink) daoc::InpLink<true>;  //!< Weighted input link
}  // wci
```
The wrapper generation yields:
```sh
template_class.i:54: Error: 'InpLink' resolves to 'daoc::InpLink' and was incorrectly instantiated in scope 'wci' instead of within scope 'daoc'.
template_class.i:70: Error: 'daoc::InpLink' resolves to 'daoc::InpLink' and was incorrectly instantiated in scope 'wci' instead of within scope 'daoc'.
```

So, the template instantiation namespace is wrong in the latest versions of SWIG (it seems ~since the middle of August), which is a regression bug.

**Comment by luav** [comment]
@wsfulton  To be sure, I have verified and localized the issue, it was definitely caused by:
commit 96e99416d76c3e0201a7b60417a0c24f845ba5b8
Author: William S Fulton <wsf@fultondesigns.co.uk>
Date:   Tue Aug 15 22:38:03 2017 +0100

In the previous commit (bf98c5304, Aug 12) the warnings are actually the same, but the wrapper classes are generated and work!

**Comment by wsfulton** [comment]
In summary, there is a simple restriction that you can't use the C++ template name for the name in %template and this has always been in place and is unrelated to 96e9941. If you simplify your example right down to the following: 
```swig
%inline %{
namespace daoc {
  template <bool B> struct InpLink {};
}  // daoc
%}

%template(SInpLink) daoc::InpLink<false>;  //!< Simple input link
%template(InpLink) daoc::InpLink<true>;  //!< Weighted input link
```
You get the warning explaining you can't use the name 'InpLink':
```
example.i:11: Warning 302: Identifier 'InpLink' redefined (ignored) (Renamed from 'InpLink< true >'),
example.i:6: Warning 302: previous definition of 'InpLink'.
```
Thinking about this restriction, it is probably unnecessary. The template declaration results in this symbol name being used but in reality this symbol is never used in the target language, so it ought to be freed up and available. I think this corner case can be fixed, so I'll look at that. There may be some clever %rename workarounds, but I think I'll spend time on looking at fixing it rather than getting a workaround. This addresses the original issue/comments, I'll look at your 2nd/3rd comment later.

**Comment by wsfulton** [comment]
The errors/warnings from SWIG in your 2nd and 3rd comments look good and are as intended. Once you know about the `InpLink` symbol name restriction, that is, the name `InpLink` is not available in the target language, all this should make sense. One more thing you may need to fully comprehend is the two different sets of symbol tables (C symbols and target language symbols). Firstly, when using:
```
%template(SInpLink) daoc::InpLink<false>
```
`daoc::InpLink<false>` is a C symbol that a C++ compiler must fully understand. It must be a valid type that can be instantiated in the same way that a C++ template can be instantiated:
```
template daoc::InpLink<false>;
```
I tried to describe this in the additions to SWIGPlus.html in commit 959e6272082e416303d80d7326430d1fd0b4c432. You can see read it here: http://htmlpreview.github.io/?https://github.com/swig/swig/blob/master/Doc/Manual/SWIGPlus.html#SWIGPlus_template_scoping.

Secondly, `SInpLink`  in `%template(SInpLink)` is a target language symbol. There is no 'namespace' for target language symbols if you are targeting Python, all C++ namespaces are collapsed into one global namespace in the target language. For Java, this is also the case by default, but I suggest you read up about the nspace feature which will allow you to create Java packages based on the C++ namespace names (eg daoc.SInpLink).

If anything else needs clarifications, let me know.

**Comment by luav** [comment]
Thank you @wsfulton for the clarification.
> ... you can't use the C++ template name for the name in %template and this has always been in place

No, here is the [working project](https://github.com/eXascaleInfolab/StaTIX/blob/master/src/info/exascale/SimWeighted/main.java#L21), where `libdaoc` is linked to the Java client using SWIG. It worked for the `3.0.12` and some `4.x` versions from the repository, but I don't know the revision (commit number of the working 4.x version, I will probably open another issue to add revision numbers to the version).  
The Java client performs:
```java
import info.exascale.daoc.*;
...
		Graph gr = new Graph(n);
		InpLinks grInpLinks  = new InpLinks();
...
```
where `Graph` and `InpLinks` are the templates defined in `libdaoc` and redefined in the swig interface file as:
```c++
...
%template(SGraph) Graph<false>;  //!< Graph
%template(Graph) Graph<true>;  //!< Weighted graph
...
```

But the library compilation fails in the latest versions of the SWIG `4.x`. I will specify the working commit after find it...

**Comment by luav** [comment]
@wsfulton I have finally found the working version and refined the example to reproduce the problem, `template_class.i`:
```c++
%module template_class
%{
#include <vector>
%}
%include <std_vector.i>

using std::vector;

%inline %{
namespace daoc {

using Id = unsigned;
using LinkWeight = float;

template <bool WEIGHTED=false>
struct InpLink {
	using Weight = LinkWeight;  //!< \copydoc LinkWeight

	constexpr static bool  IS_WEIGHTED = WEIGHTED;

	Id  id;  //!< Dest node id
	constexpr static Weight  weight = 1; // SimpleLink<Weight>::weight;
	//Weight  weight;  //!< Link weight

	InpLink(Id lid=0): id(lid)  {}
};

template <>
struct InpLink<true> {
	using Weight = LinkWeight;  //!< \copydoc LinkWeight

	constexpr static bool  IS_WEIGHTED = true;

	Id  id;  //!< Dest node id
	Weight  weight;  //!< Link weight

	InpLink(Id lid=0, Weight lweight=1)  // SimpleLink<Weight>::weight
	: id(lid), weight(lweight)  {}
};

}  // daoc
using namespace daoc;
%}

%template(SInpLink) daoc::InpLink<false>;  //!< Simple input link
%template(InpLink) InpLink<true>;  //!< Weighted input link
```
Wrapper generation:
```sh
$ mkdir java; swig -v -c++ -java -outdir java template_class.i
```
For the SWIG release (`3.0.12` tarball) and the working SWIG 4 version (ba45861)
```sh
commit ba45861b462e91e266456f510036768c2aa55be5
Author: William S Fulton <wsf@fultondesigns.co.uk>
Date:   Sun Jul 30 16:49:21 2017 +0100
```
the generated wrappers are
```sh
$ ls java-template_class-swig-ba45861_OK/
InpLink.java  SInpLink.java  template_class.java  template_classJNI.java
```

959e627 **breaks Interfaces** generated in `SWIG-3.0.12` and SWIG 4 up to ba45861, yielding only:
```sh
$ ls java-template_class-swig-959e627_FAILS/
SInpLink.java  template_class.java  template_classJNI.java
```
Since 959e627 `Wed Aug 16 00:24:25 2017 +0100 (orig Wed Aug 9 00:06:24 2017 +0100) %template scope enforcement and class definition fixes` the templates can not be instantiated using their name as the interface [class] name.

**Comment by wsfulton** [comment]
```swig
using namespace daoc;
%template(InpLink) InpLink<true>;
```
incorrectly instantiated the template in the global namespace instead of the daoc namespace before the change. It thus did not clash with the primary template declaration in daoc. See #1093 for further discussion on the change.

I will look to see I can lift the symbol name restriction with the template symbol name.

**Comment by luav** [comment]
Yes, I also though about the namespace, rechecked and updated the example outlining in the comment that the issue is not in the absent explicit namespace.  
In the old versions it works for both `%template(InpLink) InpLink<true>;` and `%template(InpLink) daoc::InpLink<true>;`. Since 959e627 it does not work in both cases.

**Comment by luav** [comment]
Thank you William,  it makes possible for me to use the latest revision of SWIG now (I had to stuck on ba45861 for the project before this fix)!
