### ISSUE TITLE
http://www.swig.org Is currently down.

### ISSUE THREAD

**Issue by adragoset** [swig/swig#1103]
Looking for documentation on SWIG but can't reach it due to site being offline.

**Comment by vadz** [comment]
FWIW, you can always view docs [directly from GitHub](http://htmlpreview.github.io/?https://github.com/swig/swig/blob/master/Doc/Manual/Contents.html).

**Comment by adragoset** [comment]
Yeah found the documentation but couldn't find the windows pre built executable in the latest release. Documentation says its available on the website :/

**Comment by ojwb** [comment]
It's hosted at sourceforge and:

"SF.net Operations‏ @sfnet_ops 5h5 hours ago

SourceForge is experiencing issues. We are investigating."

So it looks like they know already...

**Comment by vadz** [comment]
The web site is still quite slow to load (at least from here), but is back up, so I think we can safely close this one.
