### ISSUE TITLE
Default arguments c++ to python: different behavior for windows and linux

### ISSUE THREAD

**Issue by schlagmueller** [swig/swig#1108]
Hello,

I was struggling the last few hours with an issue which came up switching from linux to windows:

example.h
```
class A {
public:
  A(unsigned int a = 0xFFFFFFFFu){ }
};
class B {
public:
  B(unsigned int b = 0x7FFFFFFFu){ }
};
```
and a 
example.i
```
%module example
%{
#include "example.h"
%}
%include "example.h"
```

My swig version is 3.0.12 in linux and windows (swigwin-3.0.12).
Linux creates the python file as I would expect it:
``swig -c++ -python example.i``
```
class A(_object):
    (...)
    def __init__(self, a=0xFFFFFFFF):
    (...)
class B(_object):
    (...)
    def __init__(self, b=0x7FFFFFFF):
```
but with windows I get
```
class A(_object):
    (...)
    def __init__(self, *args):
    (...)
class B(_object):
    (...)
    def __init__(self, b=0x7FFFFFFF):
```
So somehow swig under windows has an issue with the unsinged constant.

Is this a bug? Am I doing something wrong? Is there a workaround for me? I would highly appreciate to use the default argument 0xFFFFFFFF.

Have a nice day
Michael

**Comment by wsfulton** [comment]
The files generated should be identical on both windows and linux if the input is identical (after preprocessing). In your case I would expect the output to be the same. Are you sure you are using the same version of SWIG and the same command line options on both platforms?

**Comment by schlagmueller** [comment]
I was also expecting the very same result :)

So I did the same test again.

swigwin 3.0.12 binary
```
SWIG Version 3.0.12
Compiled with i686-w64-mingw32-g++ [i686-w64-mingw32]
Configured options: +pcre
```
 and the swig 3.0.12 provided by arch
```
SWIG Version 3.0.12
Compiled with g++ [x86_64-pc-linux-gnu]
Configured options: +pcre
```
I also tried an old version for windows (3.0.6) which leads to the same difference.
``diff example.win.py example.linux.py -w``
```
105,106c105,106
<     def __init__(self, *args):
<         this = _example.new_A(*args)
---
>     def __init__(self, a=0xFFFFFFFF):
>         this = _example.new_A(a)
```

**Comment by wsfulton** [comment]
The Windows release binaries are 32 bit compiled executables and your Linux platform is 64 bit. We use `strtol` to check if the default value is a valid number. On the 32 bit operating system `0xFFFFFFFF` is too big for this check to succeed by `strtol`, but on the 64 bit operating system, long is big enough for this function to succeed. This unfortunately means SWIG has a platform specific inconsistency bug as SWIG's goal is to produce identical code on all platforms that SWIG runs on.

The whole idea of successfully converting C constants into a Python equivalent is full of corner case pitfalls and this is another case. I propose we only accept values in the range `2**31-1` to `-2**31`, which is what Python documents as the largest guaranteed range for `sys.maxint`, see https://docs.python.org/2/library/sys.html. These are the only valid values that will definitely work when the default value is specified in Python code.

**Comment by ojwb** [comment]
Sounds reasonable to me.
