### ISSUE TITLE
Wrong args passed to tp_new

### ISSUE THREAD

**Issue by lukaszzek** [swig/swig#1109]
Python expects tuple and dict object for second and third param, please take a look at: https://github.com/python/cpython/blob/90f1d989594f3340c5ffaa2cf9cef1876ac6bb89/Objects/typeobject.c#L3564 

https://github.com/swig/swig/blob/90f9117e10172722c03dcfde74b35ddd93d6072d/Lib/python/pyrun.swg#L1362

**Comment by wsfulton** [comment]
Which version of Python is this for and what is the input code and SWIG command line options for which this code is called? Without looking deeply, Py_None seems a reasonable input for these parameters, how does it fail for you?

**Comment by lukaszzek** [comment]
Hi, I am looking at Python master branch, the same was for 3.6.3rc1. Python expects a tuple object which means it casts this to a struct of a bigger size than PyNone (in my case 40 vs 32 bytes). There's no fail, but this is risky as invalid memory accesses might happen.

**Comment by wsfulton** [comment]
I will look further if you provide a testcase/way to replicate further. Most SWIG developers don't have the time to guess your setup. Why don't you provide the SWIG command line options as requested? Without this info, you'll have to investigate further and help by:

1. Providing links to the appropriate docs showing Py_None is an invalid input.
2. Providing the released version of Python (if any) that this started behaving like this.
3. Doing a git bisect on the Python C code base using your SWIG generated code to show when it started. I mention this as it is possibly a bug in the Python C implementation, but without the full picture it is hard to say. 
4. Providing a patch to fix it which passes the full Python SWIG test-suite running on Travis.

**Comment by lukaszzek** [comment]
Sorry, I thought the error was obvious but it's not anymore. Reproduction scenario is complicated as it needs python compiled with address sanitizer support. I posted a question to python mailing list to clarification on how to use PyTypeObject.tp_new function.
Thanks for looking into it,
Łukasz

**Comment by wsfulton** [comment]
This looks like it is the same issue as #1321 which is now fixed.
