### ISSUE TITLE
Restrict SWIG directive to individual files

### ISSUE THREAD

**Issue by aprokop** [swig/swig#1113]
Right now, I have a single `module.i` file that looks something like this:
```
%module module_name
%include "file1.i"
%include "file2.i"
```
The problem I am experiencing with this is directives in `file1.i` are also applied to `files2.i`. For example, a general `%ignore function_name;` in `file1.i` would also ignore all `function_name` `in file2.i`.

Is there any way to restrict the behavior of `%ignore` and other directives like that to individual `.i` files? Or, any call to reset SWIG state (which would be added to the end of individual `.i` files)? I have been looking around for a while, and cannot seem to find any information on any of these options.

**Comment by wsfulton** [comment]
Including a .i file is akin to including a C header file. There is no such concept as file only scope.

You could rename a symbol back to what it was at the end of the .i file. Probably you aren't using the full power of %rename. A symbol name should be scoped, so use the full power of rename to specify the fully qualified name instead. There is a lot on %rename/%ignore in the docs, you ought to read all the main chapters, however, this section contains a lot: http://swig.org/Doc3.0/SWIGPlus.html#SWIGPlus_nn25. 

Features can be cleared, see http://swig.org/Doc3.0/Customization.html#Customization_clearing_features. Again you probably should be fully qualifying your symbols used for %feature.

Typemaps can be deleted, see http://swig.org/Doc3.0/Typemaps.html#Typemaps_nn14.

**Comment by aprokop** [comment]
@wsfulton Thanks! I knew about the full scope, I was just trying to figure out if we can automatically catch rogue `%ignore` without a scope.
