### ISSUE TITLE
Would be cleaner to be able to use is.null() with R objects holding a pointer

### ISSUE THREAD

**Issue by davidcreasy** [swig/swig#1124]
In R, testing for functions returning a null pointer is hard to handle. In the example below, calling getCircle() with an index other than 0 would return a null pointer. 

tp <- PointerTest()
circ1 <- tp$getCircle(1)

In SWIG wrapped Perl, Python etc. it's easy to test for this. I'm just an R beginner, but I think the natural thing in R would be to test:
 is.null(circ1)
However, this doesn't work because the generated code:
/* Create a new pointer object */
SWIGRUNTIMEINLINE SEXP
SWIG_R_NewPointerObj(void *ptr, swig_type_info *type, int flags) {
  SEXP rptr = R_MakeExternalPtr(ptr, 
  R_MakeExternalPtr(type, R_NilValue, R_NilValue), R_NilValue); 
  SET_S4_OBJECT(rptr);
  return rptr;
}

doesn't do anything different for cases where ptr==0. I think that it would be better if it just set the return value to R_NilValue in this case, because the wrapping object can never do anything useful (apart from crash!). The work-around that I am using is as described here:

https://stackoverflow.com/questions/26666614/how-do-i-check-if-an-externalptr-is-null-from-within-r

but that really seems like a hack.

I may be missing something....

Just in case it's needed:

// C++ code
class circle {
  public:
    circle(double radius) 
    { 
        m_radius = radius;
    }
    double getArea() const
    { 
        return (3.14 * m_radius * m_radius);
    }
    
   private:
     double m_radius;
};

class pointerTest {
  public:
    pointerTest() : m_circle(2) {} 
    const circle * getCircle(int index) const {
      if (index == 0)
        return & m_circle;
      else
        return 0;
    }

    private:
        circle m_circle;
};

**Comment by jonasfoe** [comment]
I think returning R_NilValue would be a straight forward solution.
I have submitted a single purpose package [isnullptr](https://cran.r-project.org/web/packages/isnullptr/index.html) because swig keeps returning null pointers that are untestable via native R.

**Comment by joequant** [comment]
Thanks for reminding me.  I had a fix ready but forget to check it in.  Doing it now.
