### ISSUE TITLE
Python %extend with default args, fastunpack, modernargs and builtin

### ISSUE THREAD

**Issue by jim-easterbrook** [swig/swig#1126]
I'm having a problem using default arguments when adding methods to a C structure and swigging with optimisation and -builtin. Here's a simple example:
```
/* File: test.i */
%module test
struct foo {};
%extend foo {
  void no_arg() {}
  void one_req(int *required) {}
  void one_opt(int *optional = NULL) {}
  void two_arg(int *required, int *optional = NULL) {}
};
```
With `swig -python -py3 -builtin test.i` the wrapper contains the following:
```
SWIGINTERN PyMethodDef SwigPyBuiltin__foo_methods[] = {
  { "no_arg", (PyCFunction) _wrap_foo_no_arg, METH_VARARGS, (char*) "" },
  { "one_req", (PyCFunction) _wrap_foo_one_req, METH_VARARGS, (char*) "" },
  { "one_opt", (PyCFunction) _wrap_foo_one_opt, METH_VARARGS, (char*) "" },
  { "two_arg", (PyCFunction) _wrap_foo_two_arg, METH_VARARGS, (char*) "" },
  { NULL, NULL, 0, NULL } /* Sentinel */
};
```
With `swig -python -py3 -builtin -fastunpack -modernargs test.i` this changes to
```
SWIGINTERN PyMethodDef SwigPyBuiltin__foo_methods[] = {
  { "no_arg", (PyCFunction) _wrap_foo_no_arg, METH_NOARGS, (char*) "" },
  { "one_req", (PyCFunction) _wrap_foo_one_req, METH_O, (char*) "" },
  { "one_opt", (PyCFunction) _wrap_foo_one_opt, METH_O, (char*) "" },
  { "two_arg", (PyCFunction) _wrap_foo_two_arg, METH_VARARGS, (char*) "" },
  { NULL, NULL, 0, NULL } /* Sentinel */
};
```
This means the `one_opt` method's argument is now required, rather than optional. Dropping any one of the `-builtin -fastunpack -modernargs` flags makes all the methods `METH_VARARGS` again. I don't have this problem with functions that are not part of a `%extend` class.

I found issue #607 which appears to be similar, but doesn't mention `%extend`.

**Comment by wsfulton** [comment]
Can you try with swig-3.0.12 if you aren't already. There were some fixes in this area in 3.0.6.

**Comment by jim-easterbrook** [comment]
Sorry for not mentioning the SWIG version. I'm on 3.0.10 but can probably try 3.0.12 on a virtual machine.

**Comment by jim-easterbrook** [comment]
Just checked - I'm getting the same with 3.0.12.

**Comment by wsfulton** [comment]
This is similar to #607 and I'll commit a fix shortly to fix.

**Comment by jim-easterbrook** [comment]
Thanks William.

**Comment by jim-easterbrook** [comment]
Six years later and I've found another manifestation of this problem, or one very like it. Simple example:
```
/* File: test.i */
%module test
%typemap(default) bool optional {$1 = true;}
class foo {
public:
  void one_arg(bool optional) {}
  void two_arg(int required, bool optional) {}
};
```
The default typemap is supposed to convert `one_arg` to a function requiring 0 or 1 arguments, and `two_arg` to one with 1 or 2 arguments.

Using SWIG v4.1.1, `swig -c++ -python -builtin -nofastunpack test.i` generates
```
SWIGINTERN PyMethodDef SwigPyBuiltin__foo_methods[] = {
  { "one_arg", _wrap_foo_one_arg, METH_VARARGS, "" },
  { "two_arg", _wrap_foo_two_arg, METH_VARARGS, "" },
  { NULL, NULL, 0, NULL } /* Sentinel */
};
```
but `swig -c++ -python -builtin test.i` generates
```
SWIGINTERN PyMethodDef SwigPyBuiltin__foo_methods[] = {
  { "one_arg", _wrap_foo_one_arg, METH_O, "" },
  { "two_arg", _wrap_foo_two_arg, METH_VARARGS, "" },
  { NULL, NULL, 0, NULL } /* Sentinel */
};
```
This means that `one_arg` requires one argument, although the wrapper method `_wrap_foo_one_arg` could accept 0 or 1 arguments.

In my (complex) real life case changing `METH_O` to `METH_VARARGS` in the wrapper file, and making no other changes, makes it work as expected.
