### ISSUE TITLE
Question regarding vectors and python

### ISSUE THREAD

**Issue by kungocan** [swig/swig#1127]
I'm having a problem with the usage of vectors from C++ inside python with the str() function.

I have a class called Channel and a std::vector<shared_ptr < Channel > > vector.
In the interface file i extended the Channel class and added a __str__ function for usage within python.
The std::vector<shared_ptr < Channel >> also has a template inside the .i file (%template(vectorChannel) vector<shared_ptr < Channel >>;)

Now when I try to use the str() functionality on the vector/list, it outputs  "<swig.Channel; proxy of <Swig Object of type 'std::shard_ptr < Channel > *' at 0xaddress>>" for each element inside the vector/list.
But when I use the str() on a element inside the vector/list it outputs the correct values.

Is it possible to ouput a vector with a class type  with str()?

**Comment by wsfulton** [comment]
Add in the `__str__` method using %extend and %proxycode. Customise the output to whatever you want. Here is a full example:
```swig
%module example
%{
#include <memory>
%}
%include <std_shared_ptr.i>
%shared_ptr(Channel)

%include <std_vector.i>

%extend std::vector {
%pythoncode %{
def __str__(self):
    s = str(self.__class__.__name__) + "([" + ",".join(["Channel({})".format((i.num)) for i in self]) + "])"
    return s
%}
}
%inline %{
#include <vector>
struct Channel {
  int num;
  Channel(int num = 0) : num(num) {}
};
%}

%template(vectorChannel) std::vector<std::shared_ptr<Channel>>;
```
Here it is working
```python
>>> from example import *
>>> vc = vectorChannel([Channel(10), Channel(20)])
>>> print(str(vc))
vectorChannel([Channel(10),Channel(20)])
>>> print(repr(vc))
<example.vectorChannel; proxy of <Swig Object of type 'std::vector< std::shared_ptr< Channel >,std::allocator< std::shared_ptr< Channel > > > *' at 0x7f4dfd880870> >
```
