### ISSUE TITLE
carrays and warning on char / char*

### ISSUE THREAD

**Issue by jleni** [swig/swig#1132]
Swig documentation says that array_class() should not be used with char or char *.

http://www.swig.org/Doc3.0/Library.html#Library_carrays

Note: %array_functions() and %array_class() should not be used with types of char or char *.
The reason is not explicit in the documentation. Could someone explain the reason? Should the documentation be updated?

Is this to avoid collisions with strings? Is it ok to use array_class with  unsigned char * ?

**Comment by wsfulton** [comment]
On 23 October 2017 at 10:09, jleni <notifications@github.com> wrote:

> Swig documentation says that array_class() should not be used with char or
> char *.
>
> http://www.swig.org/Doc3.0/Library.html#Library_carrays
>
> Note: %array_functions() and %array_class() should not be used with types
> of char or char *.
> The reason is not explicit in the documentation. Could someone explain the
> reason? Should the documentation be updated?
>
> Is this to avoid collisions with strings?
>
Yes, the default handling for char and char * is for character strings and
the macros do not do enough to change this.

Try the following to modify the default handling to treat char as a number
and char pointers/arrays as a regular pointer. The two macros should then
work for char and char *, but you'll break normal usage for char * as
strings.

%apply signed char {char}
%apply SWIGTYPE* {char *, char[ANY], char []}

Is it ok to use array_class with unsigned char * ?
>
It should be.

William

**Comment by ojwb** [comment]
@wsfulton Is there something you think should be addressed in SWIG here, or can this be closed?

**Comment by wsfulton** [comment]
8e733c0b925877f8d5c5fdf6e5bc3f5042cb4225 enhanced the docs. Closing.
