### ISSUE TITLE
varargs passes all params if number of uniform terms specified

### ISSUE THREAD

**Issue by dmulder** [swig/swig#1134]
YCPValue CallYCPFunction(const string & namespace_name, const string & function_name, ...);
%varargs(25, YCPValue = NULL) CallYCPFunction;
Generates a variable function call, but it cannot accept fewer than ALL args.
Calling CallYCPFunction() with fewer args fails, because argc in _wrap_CallYCPFunction() always == 27, regardless of the number of arguments passed.
It will always result in the case of 27 args, which fails because it cannot accept only 2 arguments.

**Comment by ojwb** [comment]
You don't say what SWIG version you're using nor provide a complete reproducer, but testcase `Examples/test-suite/varargs.i` has:

```
%varargs(2, int mode = 0) test_plenty(const char*fmt, ...);
```

and `Examples/test-suite/python/varargs_runme.py` tests that calling `test_plenty` from Python with 1, 2 and 3 args works (and that calling with 4 fails).

This testcase passes with current git master:

```
$ make -C Examples/test-suite/python varargs.cpptest
make: Entering directory '/home/olly/git/swig/Examples/test-suite/python'
if [ -f ./varargs_runme.py ]; then echo "checking python testcase varargs (with run test)" ; else echo "checking python testcase varargs" ; fi
checking python testcase varargs (with run test)
make -f ../../../Examples/Makefile SRCDIR='./' CXXSRCS='' SWIG_LIB_DIR='../../../Lib' SWIGEXE='../../../swig' INCLUDES='-I../../../Examples/test-suite' SWIGOPT='-outcurrentdir -I../../../Examples/test-suite' NOLINK=true TARGET='varargs' INTERFACEDIR='../' INTERFACE='varargs.i' python_cpp
make[1]: Entering directory '/home/olly/git/swig/Examples/test-suite/python'
env SWIG_LIB=../../../Lib  ../../../swig -python  -c++ -outcurrentdir -I../../../Examples/test-suite -o varargs_wrap.cxx ./../varargs.i
g++ -c -fpic -I. -I./ -I/usr/include  varargs_wrap.cxx   -I../../../Examples/test-suite  -I/usr/include/python2.7 -I/usr/lib/python2.7/config
g++ -shared  -I/usr/include     varargs_wrap.o    -o _varargs.so
make[1]: Leaving directory '/home/olly/git/swig/Examples/test-suite/python'
pep8 --ignore=E30,E402,E501,E731,W291,W391 varargs.py
if [ -f ./varargs_runme.py ]; then env LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH PYTHONPATH=.:.:$PYTHONPATH  python varargs_runme.py; fi
make: Leaving directory '/home/olly/git/swig/Examples/test-suite/python'
```

I'd suggest working out what's different in your situation to me running that testcase with current git master.

**Comment by dmulder** [comment]
I was using 3.0.12, but I just tried against master and see the exact same results.

**Comment by dmulder** [comment]
I just wrote a simpler example, and I don't see that behavior. I'll try and see what is causing this.

**Comment by ojwb** [comment]
@dmulder Did you get to the bottom of this?

**Comment by ojwb** [comment]
I couldn't reproduce this in 2017 and there's been no further feedback from submitter in 4 years, so I'm going to close.

@dmulder If you're still seeing this with the latest SWIG please say and I'll reopen.
