### ISSUE TITLE
Code in typesys.c unconditionally sets use_wrapper to 1

### ISSUE THREAD

**Issue by aprokop** [swig/swig#1139]
In the [line 1545](https://github.com/swig/swig/blob/1132bc334b399e20f420b4abdd00eb2c20463887/Source/Swig/typesys.c#L1545) of typesys.c the code seems to always set `is_wrapper` to true because it is in the branch where `n == 0`. This may be a bug.

**Comment by wsfulton** [comment]
This is just badly written code rather than a bug.
