### ISSUE TITLE
build in Visual stdio 2015 

### ISSUE THREAD

**Issue by flywith-liang** [swig/swig#1140]
error C2065: 'PACKAGE_VERSION': undeclared identifier

**Comment by ojwb** [comment]
We don't supply build files for this compiler, so this is a problem either with build files you've created (in which case it's your bug) or with with third party build files (in which case you should take it up with whoever you got them from).

You'll probably find it simpler to build with mingw GCC - I believe that's how binary builds of releases are made, so it should be well supported.
