### ISSUE TITLE
Debug error - The variable 'result' is being used without being initialized

### ISSUE THREAD

**Issue by Liryna** [swig/swig#1141]
Hi,

When the C code is generated by the wrapper, it creates on each functions a result of the return type without being initialized.
Running the application to debug will result in a window error by the runtime library c++ each time a c++ function throw an error.

```
 unsigned int jresult ;
  MyType  *arg1 = (MyType  *) 0 ;
  std::shared_ptr< MyType > *smartarg1 = 0 ;
  bool result;
  
  
  smartarg1 = (std::shared_ptr<  MyType  *)jarg1;
  arg1 = (MyType  *)(smartarg1 ? smartarg1->get() : 0); 
  
  try 
  {
    result = (bool)(arg1)->myFunction(); <== This throw an error
  } 
  FOR_EACH_EXCEPTION( CATCH_CSE )
  catch (std::out_of_range &e)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, e.what(), "unknown");
  }
  catch (std::logic_error &e)
  {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, e.what(), "unknown");
  }
  catch (std::range_error &e)
  {
    SWIG_CSharpSetPendingException(SWIG_CSharpOutOfMemoryException, e.what());
  }
  catch (std::overflow_error &e)
  {
    SWIG_CSharpSetPendingException(SWIG_CSharpOverflowException, e.what());
  }
  catch (std::underflow_error &e)
  {
    SWIG_CSharpSetPendingException(SWIG_CSharpOverflowException, e.what());
  }
  catch (std::runtime_error &e)
  {
    SWIG_CSharpSetPendingException(SWIG_CSharpSystemException, e.what());
  }
  catch (std::bad_cast &e)
  {
    SWIG_CSharpSetPendingException(SWIG_CSharpInvalidCastException, e.what());
  }
  catch (std::exception &e)
  {
    SWIG_CSharpSetPendingException(SWIG_CSharpSystemException, e.what());
  }
  
  jresult = result;  <== result is used without being init
  return jresult;
```

If myFunction throw an error, result will not be set but will be used before return to set jresult.

Is there a way/macro of swig to set a default value to result ?

**Comment by wsfulton** [comment]
You've shown the generated code and not the input code to replicate the given generated code. What I guess your input code is doing is using %exception or maybe the throws typemap to generate the catch handlers, that is, you have customised the output that SWIG normally generates. What you should do is adapt your code and add in `return $null` after the `SWIG_CSharpSetPendingException` calls as we do for the exception handlers provided by SWIG. For example, see std_string.i: https://github.com/swig/swig/blob/master/Lib/csharp/std_string.i.

**Comment by Liryna** [comment]
Hi @wsfulton ,

Thanks a lot ! You are right `return $null;` were missing 👍 this solves my issue.

Since you linked the std_swig.i, I would like to be able to give a null string from c#
Currently https://github.com/swig/swig/blob/master/Lib/csharp/std_string.i#L32 an exception is throwing if string is null. I tried to override it by adding but it seems to be ignored:
```
%{
#include <string>
%}

%typemap(in, canthrow=1) std::string 
%{
	if (!$input) {
		$1.assign("");
	} else {
		$1.assign($input);
	}
%}

%typemap(directorout, canthrow=1) std::string
%{ 
	if (!$input) {
		$1.assign("");
	} else {
		$$result.assign($input);
	}
%}
```
Is there anyway to override this behavior ?

Thank in advance !

**Comment by wsfulton** [comment]
Just put the two typemaps you show above after your `%include <std_string.i>` to override the typemaps in std_string.i. You probably also want to override `const std::string&` to match. BTW, `$1.clear()` is preferable over `$1.assign("")` and the directorout typemap should use `$result` instead of `$1`.

**Comment by Liryna** [comment]
Thank you @wsfulton 
This perfectly working ! ❤️
