### ISSUE TITLE
Use of same namespace across files causes compile errors in *_wrap.cxx

### ISSUE THREAD

**Issue by lovettchris** [swig/swig#1148]
Foo.h
```cpp
namespace microsoft
{
    class Foo
    {
    };
}
```
Bar.h
```cpp
#include "Foo.h"

namespace microsoft
{
    class Bar
    {
    public:
        Foo GetFoo()
        {
            return Foo();
        }
    };
}
```

Wrapping Bar.h creates wrapper with this unqualified reference to "Foo" but no "using namespace microsoft" so it doesn't compile, saying "'Foo': undeclared identifier"

```cpp
SWIGINTERN PyObject *_wrap_Bar_GetFoo(PyObject *SWIGUNUSEDPARM(self), PyObject *args) {
  PyObject *resultobj = 0;
  microsoft::Bar *arg1 = (microsoft::Bar *) 0 ;
  void *argp1 = 0 ;
  int res1 = 0 ;
  PyObject * obj0 = 0 ;
  Foo result;    // <-- this is unqualified, so it doesn't compile.
```

Having to fully qualify every type reference in all my header files just to make SWIG happy is both ugly and a lot of work.  Is there a quick fix ?

Interestingly if I move "Foo" from Foo.h to Bar.h then it works fine and Foo gets correctly qualified with namespace 'microsoft'

```cpp
SWIGINTERN PyObject *_wrap_Bar_GetFoo(PyObject *SWIGUNUSEDPARM(self), PyObject *args) {
  PyObject *resultobj = 0;
  microsoft::Bar *arg1 = (microsoft::Bar *) 0 ;
  void *argp1 = 0 ;
  int res1 = 0 ;
  PyObject * obj0 = 0 ;
  microsoft::Foo result;    // <-- this time it is correct, but all I did was rearrange header files...
```

**Comment by lovettchris** [comment]
Note this is with:
```
%{
#include <Foo.h>
%}
%include <Foo.h>
```
But it does compile if I flatten the include graph:
```
%{
#include <Foo.h>
#include <Bar.h>
%}
%include <Foo.h>
%include <Bar.h>
```

it would be nice if I didn't have to flatten the include graph.

**Comment by wsfulton** [comment]
SWIG does its best if you don't supply the type information or provide it out of order. However, you will be most successful if you provide the appropriate type information in the correct order like it is mandatory to do so for a C++ compiler. Hence you need to %include the file with Foo defined it before you attempt to use it in another wrapped class. This behaviour is by design.

**Comment by lovettchris** [comment]
But my confusion stems from the fact that the first thing "Bar.h" does is include "Foo.h".  Are you saying SWIG doesn't read #includes like the C++ compiler does?

**Comment by wsfulton** [comment]
It doesn't by default, but that can be changed (but is not recommended), see the SWIG Basics chapter http://swig.org/Doc3.0/SWIG.html#SWIG_nn6.

**Comment by lovettchris** [comment]
I see thanks, that explains it.
