### ISSUE TITLE
Function wrapping

### ISSUE THREAD

**Issue by ReDucTor** [swig/swig#1151]
While we can't easily store scripting language functions in a function pointer (w/o trying to take advantage of some 'userdata'), we can probably more easily support storing them within a C++ std::function this would allow callbacks into the target languages to exist.

For example
`void something(std::function<void(std::string)> func) { func("Hello World"); }`

C#
`something(s => Console.WriteLine(s))`

Python 2
`something(lambda s: sys.stdout.write(s))`

Python 3
`something(lambda: s: print(s))`

**Comment by sethrj** [comment]
I think you'd have to add something like a `%director` for each instantiation of `std::function`: it would have to have wrapper code to translate its input and output arguments in addition to holding the function pointer.

Perhaps something like:
```c++
struct SwigPyFuncPointer {
  PyObject* callback;
  void operator()(const std::string& inp)
  {
    PyObject* args;
    // Convert inp to python args
   result = PyObject_CallObject(callback, args)
   // Process exceptions etc.
   return;
  }
};
```
which has the appropriate interface to be wrapped in a `std::function`.

**Comment by wsfulton** [comment]
@sethrj's approach requires hand writing the marshalling of types between the languages which may be okay for you. SWIG's only supported mechanism for callbacks from C++ to target language are the director feature.  There is some pre-release documentation for swig-4.0 which describes how to use directors and C function pointers. You can read it here: https://rawgit.com/swig/swig/master/Doc/Manual/SWIGPlus.html#SWIGPlus_target_language_callbacks. This is also relevant to `std::function`, just replace the C function pointer with `std::function`.
