### ISSUE TITLE
return nullptr for std::shared_ptr does not work

### ISSUE THREAD

**Issue by vrguru** [swig/swig#1154]
Hi 
When using raw pointers from a c++ method:
class Foo {
  void doSometing();
}

Foo *getFoo()
{
  return nullptr;
}

In python this results in:

f = getFoo()
# works just fine
assert f == None

If I try to call
f.doSomething()

I get a proper error about f being None, fine.

However if I use std::shared_ptr _from a class that is declared with shared_ptr() in swig, this does not work:
`
std::shared_ptr<Foo> getFoo()
{
  return nullptr;
}

f = getFoo()
`

f is NOT None, it is a pointer to the class Foo. If I try to use it anything might happen due to the fact that it is a std::shared_ptr around a null pointer.

The issue occurs when the calling class is declared in swig i-file as %shared_ptr(classname).
An example to reproduce the error:
`
%inline {

class A
{
  public:
    A() {}    
};

class B
{
  public:
     B() {}

     std::shared_ptr<A> getA() { return new A(); }
     std::shared_ptr<A> getNull() { return nullptr; }
};

}

%include <shared_ptr.i>

%shared_ptr(A);

%shared_ptr(B); << This is what causes the problem.
`

Without %shared_ptr(B) the method A::getNull() returns a None in Python.
With %shared_ptr(B) the method A::getNull() returns a wrapper object for std::shared_ptr(B) which is really dangerous to touch, as it contains a nullptr.

It is quite obvious from looking at the generated code that the call to %shared_ptr(B) is the cause of this error. Without, there is a check for nullptr return, and it returns a null pointer to Python which is translated to None.

But with the shared, it tries to wrap the nullptr and return it in a std::shared_ptr...tricking python to believe it is a true value.

I read that this potentially was fixed in the master, however I am not able to build it for windows.
Is there anywhere a binary version of the master for windows which I could try?
Or if this issue is not fixed, is there a speedy fix for it? I really depend on it.

**Comment by wsfulton** [comment]
This works fine in swig-3.0.12. Your code is simply incorrect as your %shared_ptr is in the wrong place. See the docs at http://swig.org/Doc3.0/Library.html#Library_std_shared_ptr.

**Comment by wsfulton** [comment]
I have also updated your comment with the appropriate formatting as the code didn't show properly. You should preview what you post!
