### ISSUE TITLE
Add info to UNIX installation instructions that yacc must be installed.

### ISSUE THREAD

**Issue by gbmhunter** [swig/swig#1157]
On Ubuntu 17.04 (and probably other versions), `yacc` is not installed by default, yet required for installation from tarball (SWIG v3.0.12).

I got a `make` error:

    ../Tools/config/ylwrap: line 176: yacc: command not found

That was fixed with `sudo apt install byacc -y`.

**Comment by wsfulton** [comment]
yacc is not required to install from the unmodified distributed tarball. yacc/bison is needed if you are building from git. This is documented. Please, see the README file with the tarball, which points you to http://swig.org/Doc3.0/Preface.html#Preface. If these instructions are not clear, please submit a patch to improve.

**Comment by gbmhunter** [comment]
Hmmmm, I used https://github.com/swig/swig/archive/rel-3.0.12.tar.gz, does this count as a distribution tarball?

**Comment by wsfulton** [comment]
No, that is just something that you grabbed from github and so the relevant info is at http://www.swig.org/svn.html. The releases are on the download page at http://www.swig.org/download.html.

**Comment by gbmhunter** [comment]
Oh right, this all makes sense now! Sorry for the confusion :-)
