### ISSUE TITLE
applying typemaps with $typemap

### ISSUE THREAD

**Issue by SinnersSumit** [swig/swig#1160]
I am wondering if it is possible to apply a typemap within a typemap, using $typemap.
For example, I am representing C++ vectors with C# IEnumerables, and I have this typemap
```
%typemap(in) std::vector<bool> %{
	auto temp$1 = std::vector<bool>();
	for (auto e = $input->GetEnumerator(); e->MoveNext();)
	{
		$typemap(in, bool, input=myInput, output=myOutput);
		(temp$1).push_back();
	}
	$1 = (temp$1);
%};
```
It produces this wrapper code
```
SWIGEXPORT void SWIGSTDCALL CSharp_SPIRType_array_size_literal_set(void * jarg1, Enumerable<unsigned int>* jarg2) {
  spirv_cross::SPIRType *arg1 = (spirv_cross::SPIRType *) 0 ;
  std::vector< bool > arg2 ;
  
  arg1 = (spirv_cross::SPIRType *)jarg1; 
  
  auto temparg2 = std::vector<bool>();
  for (auto e = jarg2->GetEnumerator(); e->MoveNext();)
  {
    arg2 = myInput ? true : false; ;        // note this
    (temparg2).push_back();
  }
  arg2 = (temparg2);
  
  if (arg1) (arg1)->array_size_literal = arg2;
}
```
`$typemap(in, bool, input=myInput, output=myOutput);` gets translated into `arg2 = myInput ? true : false; ;`. However, I had hoped for a result like `myOutput = myInput ? true : false;`.

It seems that `input` is a valid argument to `$typemap(in)`, however, I cannot for the life of me figure out what the name of `output` should be to get my desired result.

Is this even an intended feature? If it is, I would like to know the details of it's use, and I should think others will too. If it isn't, is there another way to apply a typemap as a pattern? and if not, I feel there should be.

**Comment by wsfulton** [comment]
http://swig.org/Doc3.0/Typemaps.html#Typemaps_special_macro_typemap documents all that can be done with `$typemap` and this does not include using variables like `input=myInput`, so I wouldn't use any undocumented behaviour. `vector<bool>` is a template specialization of the primary `vector` template, so I would just expand the bool marshalling by hand in your `vector<bool>` typemap. Can you not do that or is there some bigger picture problem you are trying to solve?

**Comment by SinnersSumit** [comment]
@wsfulton I've examined my problem, and I've found a work around.however, I still think that it would be useful to be able to apply typemaps such as `in` and `out`, inside of other typemaps. That seems like it would probably require an overhaul of the existing methods, so I understand if it isn't possible.

**Comment by wsfulton** [comment]
I think this would get complicated very quickly trying to rename all the special variables that a typemap substitutes and it seems like feature bloat to me. If someone wants to write a proposal with lots of use cases and supply a patch I'll consider it, but for now I'm closing this.

**Comment by theartful** [comment]
+1 for such a feature. It would be great if it's possible to reuse the already implemented std containers typemaps for my custom classes.
