### ISSUE TITLE
java director casting error?

### ISSUE THREAD

**Issue by nssang00** [swig/swig#1161]
I am testing with the example below.

Examples\java\extend\runme.java

I modified the code slightly as shown below.

class CEO extends Manager {
...
//toString add
public String toString()
{
	return "CEO toString";
}

CEO e = new CEO("Alice");
EmployeeList list = new EmplyeeList();
list.addEmployee(e);

System.out.println(e);
Employee emp = list.get_item(3);
System.out.println(emp);
CEO ceo_cast = (CEO)list.get_item(3);
System.out.println(ceo_cast);

Expectations Results
CEO toString
CEO toString
CEO toString

Actual Results

=>
CEO toString
package.Employee@28d93b30
Exception in thread "main" java.lang.ClassCastException: package.Employee cannot be cast to CEO

Because of this feature, work has been stopped for a week.
Should I use typemaps?
Help me.

**Comment by wsfulton** [comment]
Please take a look at http://swig.org/Doc3.0/Java.html#Java_adding_downcasts.
