### ISSUE TITLE
Shared_ptr for inherited types not convertible in python

### ISSUE THREAD

**Issue by TChristophe** [swig/swig#1163]
I have two classes in a C++ header file (myTest.h)

```
namespace myTest {
class Base
{
public:
  virtual void f() = 0;
};

class Derived : public Base
{
public:
  virtual void f() {}
};

class C
{
public:
 void do_something(std::shared_ptr<Base> i){}
}

}
```
In the SWIG interface I declare the following:

```
%include <std_shared_ptr.i>
%shared_ptr(myTest::Base)
%shared_ptr(myTest::Derived)

%include <myTest.h>
```

Now in python:

```
d = myModule.Derived()
c = myModule.C()

c.do_something(d)
```

I received the following error: TypeError: in method 'C_do_something', argument 2 of type 'std::shared_ptr< Base>'

It seems that the conversion from std::shared_ptr<Derived> to std::shared_ptr<Base> is not accepted.

**Comment by TChristophe** [comment]
Found a solution:

```
%include <std_shared_ptr.i>

typedef myTest::Base Base;
typedef myTest::Derived Derived;

%shared_ptr(myTest::Base)
%shared_ptr(myTest::Derived)

%include <myTest.h>
```

This solves the issue

**Comment by wsfulton** [comment]
Your example works for me using swig-3.0.12. You do not need the typedefs.
