### ISSUE TITLE
Improper conversion of std::string to String

### ISSUE THREAD

**Issue by l4l** [swig/swig#1174]
cpp's strings are able to store binary data, so does the java's. But the conversion is lossy :\\
[Here's](https://gist.github.com/l4l/e0a2175b4559a065b479bfd1aa86a88c) the complete gist

I guess the problem is due to assuming that `std::string` is c-str here:
https://github.com/swig/swig/blob/717b7866d4e438e1ae3483f796eb07f96e246fe6/Lib/java/std_string.i#L102

p.s didn't find anything similar in open/closed issues, sorry if it's a dup

**Comment by wsfulton** [comment]
NewStringUTF is documented as taking a 0-terminated byte array. There are lots of things that the char data in a `std::string` could represent. The most common is ascii strings and hence the default is to convert using NewStringUTF as this will convert ascii strings. What does your `std::string` represent? Is it a string and if so, what encoding is it? You need to provide a converter from this encoding to Java's specific view of UTF, see the "Modified UTF-8 Strings" section at https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/types.html for the encoding of Java's strings. Put your conversion into a typemap and use that. Below contains the beginnings to convert ascii zero:
```swig
%typemap(out, fragment="convertString") std::string 
%{
  const std::string &s = $1;
  std::string converted;
  converted.reserve(s.size() * 2);
  for (auto& val : s) {
    if (val != 0) {
      converted += val;
    } else {
      converted += 0xC0;
      converted += 0x80;
    }
  }
  converted += '\0';
  $result = jenv->NewStringUTF(converted.data());
%}
```
You may want to instead use `std::wstring` if you are dealing with non-ascii strings. If all you are trying to do is treat `std::string` as a way to hold C `signed char` data and want to access this as a Java `byte[]`, then use the following typemap which maps `std::string` to a Java `byte[]`:
```swig
%typemap(jni) std::string "jbyteArray"
%typemap(jtype) std::string "byte[]"
%typemap(jstype) std::string "byte[]"
%typemap(out) std::string
%{
  const std::string &s = $1;
  jsize sz = s.size();
  jbyteArray bytearray = jenv->NewByteArray(sz);
  if (!bytearray)
    return NULL;
  jbyte *arr = jenv->GetByteArrayElements(bytearray, 0);
  if (!arr)
    return NULL;
  for (int i=0; i<sz; i++)
    arr[i] = (jbyte)result[i];
  jenv->ReleaseByteArrayElements(bytearray, arr, 0);
  $result = bytearray;
%}
```

**Comment by appapurapu** [comment]
This typemap is good but it converts the string ==> byte[]. 
Instead, can it possible to replace the c++ class member inplace will be helpfull.

For example, 
class example {
private:
std::string data;         // This is required to hold modified utf8 characters.

public:
std::string getData(); 
void setData(const std::string& val);
};

Here when user calls this getData() api, it internally converts to modifyed utf8 characters and return the string object?
How to do this?
Because this is necessary in already deployed applications where we can change the library and new .so files to customer but not the Java UI at customer place.
Please advise

**Comment by pangyujin** [comment]
> NewStringUTF is documented as taking a 0-terminated byte array. There are lots of things that the char data in a `std::string` could represent. The most common is ascii strings and hence the default is to convert using NewStringUTF as this will convert ascii strings. What does your `std::string` represent? Is it a string and if so, what encoding is it? You need to provide a converter from this encoding to Java's specific view of UTF, see the "Modified UTF-8 Strings" section at https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/types.html for the encoding of Java's strings. Put your conversion into a typemap and use that. Below contains the beginnings to convert ascii zero:
> 
> ```c++
> %typemap(out, fragment="convertString") std::string 
> %{
>   const std::string &s = $1;
>   std::string converted;
>   converted.reserve(s.size() * 2);
>   for (auto& val : s) {
>     if (val != 0) {
>       converted += val;
>     } else {
>       converted += 0xC0;
>       converted += 0x80;
>     }
>   }
>   converted += '\0';
>   $result = jenv->NewStringUTF(converted.data());
> %}
> ```
> 
> You may want to instead use `std::wstring` if you are dealing with non-ascii strings. If all you are trying to do is treat `std::string` as a way to hold C `signed char` data and want to access this as a Java `byte[]`, then use the following typemap which maps `std::string` to a Java `byte[]`:
> 
> ```c++
> %typemap(jni) std::string "jbyteArray"
> %typemap(jtype) std::string "byte[]"
> %typemap(jstype) std::string "byte[]"
> %typemap(out) std::string
> %{
>   const std::string &s = $1;
>   jsize sz = s.size();
>   jbyteArray bytearray = jenv->NewByteArray(sz);
>   if (!bytearray)
>     return NULL;
>   jbyte *arr = jenv->GetByteArrayElements(bytearray, 0);
>   if (!arr)
>     return NULL;
>   for (int i=0; i<sz; i++)
>     arr[i] = (jbyte)result[i];
>   jenv->ReleaseByteArrayElements(bytearray, arr, 0);
>   $result = bytearray;
> %}
> ```

Could you please advice if I want to convert std::vector<std::string> to List<byte[]> in Java? I tried the typemap you posted, it works perfectly to convert return type std::string to byte[], but it won't work if I use
`%template(ByteVector) std::vector<std::string>`. Please kindly advice

**Comment by wsfulton** [comment]
@pangyujin raised this last question in#2146.
