### ISSUE TITLE
problem with pcre

### ISSUE THREAD

**Issue by sebacea** [swig/swig#1175]
I got this error:

swig -c++ -python -outdir build/py -o build/py/infomap_wrap.cpp build/py/Infomap.i
swig: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory

I installed as root pcre2-10.21 using autotools, then I installed swig

**Comment by wsfulton** [comment]
Install it using your operating system's package management system instead. Or if you want to build your own with autotools, then you should set the LD_LIBRARY_PATH to the location that you installed it to. Why not just build pcre as a static library:
```
$ Tools/pcre-build.sh --help
Helper script to build PCRE as a static library from a tarball just for use during the
SWIG build. It does not install PCRE for global use on your system.
Usage: pcre-build.sh [--help] [args]
  args   - optional additional arguments passed on to the PCRE configure script (leave out
         unless you are an expert at configure)
  --help - Display this help information.
Instructions:
  - Download the latest PCRE source tarball from http://www.pcre.org and place in the
    directory that you will configure and build SWIG.
  - Run this script in the same directory that you intend to configure and build SWIG in.
    This will configure and build PCRE as a static library.
  - Afterwards run the SWIG configure script which will then find and use the PCRE static
    libraries in the pcre/pcre-swig-install subdirectory.
```
