### ISSUE TITLE
Inconsistency of generation params

### ISSUE THREAD

**Issue by l4l** [swig/swig#1176]
The python's and java's ways (and probably for rest too) of forbidding default constructor generation for `std::vector` is different, so if I want smth like:
```cpp
namespace std {
  %template(VecA) vector<A>;
}
```
Where some type `A` doesn't have default constructor for python I should add
`%std_nodefconst_type(A)`

and for java (thx [this issue](https://github.com/swig/swig/issues/866)) I should explicitly state:
`%ignore vector<A>::vector(size_type)`

It's pretty fine to have different approaches but the main issue that if you'd like to generate both java's and python's bindings you should place **both statements** and imo that not really good at all

**Comment by wsfulton** [comment]
`%std_nodefconst_type(A)` is not documented and not implemented for all languages, so don't recommend it. Consistency where possible is a goal we try and implement in SWIG. I think in your case, you can just add:
```swig 
%ignore std::vector<A>::vector(size_type);
%ignore std::vector<A>::resize(size_type);
```
and it will work for both Java and Python.
