### ISSUE TITLE
The purpose of implementation of director class member functions in java?

### ISSUE THREAD

**Issue by leozzyzheng** [swig/swig#1180]
I'm using director to generate java classes for callbacks, I could see each virturl function will generate some code like:

```
public void VirtualFunction() {
    if (getClass() == A.class) JNIFunction1(...); else JNIFunction2(...);
}
```

If I don't override all the `VirtualFunction`, the code above will be called when callback called from c++. Now, if `JNIFunction1` or `JNIFunction2` is called, I can see it calls the director class in JNI and seems it will call up to java again.

If I didn't misunderstand something, I think give an empty function body will be more clean?

**Comment by wsfulton** [comment]
I think you have overlooked the case when `virtualFunction` is called from Java code rather than C++ code. A JNI call is required to call the the C++`virtualFunction`.

Please reopen if you need more details or need to report a bug in this area.
