### ISSUE TITLE
Is there any way c callback python function ?

### ISSUE THREAD

**Issue by jonwinters** [swig/swig#1181]
https://github.com/swig/swig/blob/0beec3cf7306d7b9d6fe771012bb9421877a9a82/Examples/python/funcptr2/runme.py#L12

When you first wrap something like this into an extension module, you may find the function to be impossible to use. For instance, in Python:
```
>>> def add(x,y):
...     return x+y
...
>>> binary_op(3,4,add)
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
TypeError: Type error. Expected _p_f_int_int__int
>>>
```

In demo code , I just found make c function as a param of python and call c function method to invoke  c function add

is there any way c callback python function

**Comment by wsfulton** [comment]
The documentation for making callbacks from C to the target language (like Python) was recently improved for SWIG 4.0. The pre-release version can be viewed at
https://rawgit.com/swig/swig/master/Doc/Manual/SWIGPlus.html#SWIGPlus_target_language_callbacks. The information still applies to the current release - SWIG 3.0.12. In summary, you need to use C++ and the director feature for this to work.

**Comment by CatsNipYummy** [comment]
Can a target language callback example be added to the repo?

**Comment by wsfulton** [comment]
There are examples already in the Examples directory. Try Examples/python/callback and Examples/python/funcptr.

**Comment by gbala88** [comment]
Hi, curious, why does swig not encourage callbacks for pure C implementation when something like the below is possible:

https://www.oreilly.com/library/view/python-cookbook/0596001673/ch16s07.html

**Comment by gbala88** [comment]
Seems like we have a reference, but from an older version of swig as I found a couple of deprecated usages. I was able to modify this and pass python function as callback to the underlying C functions. 

http://www.fifi.org/doc/swig-examples/python/callback/
