### ISSUE TITLE
Running of test default_arg_expressions failed

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#1182]
I try to build the latest version of SWIG from git repository, but the test failed.

'''
checking tcl testcase default_arg_expressions
Unable to find file './../default_arg_expressions.i'.
make[2]: *** [../../../Examples/Makefile:196: tcl_cpp] Error 1
make[1]: *** [Makefile:33: default_arg_expressions.cpptest] Error 2
'''

The failure is related to commit ef37840. It seems that the file default_arg_expressions.i was not added/created to the repository.

**Comment by wsfulton** [comment]
Fixed. Travis https://travis-ci.org/swig/swig/ shows master is green again.
