### ISSUE TITLE
Problem with swigReleaseOwnership() in Java proxy created with %newobject

### ISSUE THREAD

**Issue by vmicelli** [swig/swig#1184]
I'm wrapping a c++ library using swig and I've tried to run the unit tests using a binary compiled with the master version.

I've got a few tests failing. Digging into the code it seems that  the cause could be the change made in the PR #449. 

In particular I'm trying to wrap a factory method that creates an instance of a class (wrapped using director feature) in c++ and returns it to Java using the %newobject feature (since the object is instantiated by my library code it does not inherit from swig director). 
At some point, I need to release the ownership of that instance to another object and I use swigReleaseOwnership()  to do so. This sometimes leads to a segfault which may be caused by the static cast introduced by PR #449. In the previous swig version (3.0.12) there was a dynamic cast and a check that prevented the call to director functions (in case the object was not a director).

I attach a simple example that reproduces this scenario. 
[example.zip](https://github.com/swig/swig/files/1639280/example.zip)

**Comment by wsfulton** [comment]
Agreed, I'm about to commit a fix restoring the dynamic_cast.
