### ISSUE TITLE
converting c++ std::complex to node-js using swig does not work

### ISSUE THREAD

**Issue by sfgorky** [swig/swig#1187]
I have a c++ API which contains function like this this prototype:
`std::complex<double> getComplex( );`

I am generating a swig (v3.0.12) wrapper with the following command Line:

`swig -c++ -javascript -node -I/usr/local/include/node  -o wrap.cpp swig.swig`

-- node version states: 8.6.0

With my swig definition code given by:
```
%module test
%{
#include <complex>
#include "myAPI.h"
%}
%include stl.i
%include std_complex.i
%include myAPI.h
```

**Issue:**

``
The wrapper code seems wrong. A macro 'SWIGV8_ARRAY_NEW' is defined as:
`#define SWIGV8_ARRAY_NEW() v8::Array::New()`
but called in the 'wrapped' function with an argument, as defined below:
```
SWIGINTERNINLINE v8::Handle<v8::Value>
SWIG_From_std_complex_Sl_double_Sg_  (/*@SWIG:/grid/common/pkgs/SWIG/v3.0.12/share/swig/3.0.12/typemaps/swigmacros.swg,104,%ifcplusplus@*/
const std::complex<double>&/*@SWIG@*/ c)
{
  SWIGV8_HANDLESCOPE_ESC();
  v8::Local<v8::Array> vals = SWIGV8_ARRAY_NEW(2);
  vals->Set(0, SWIG_From_double  (std::real(c)));
  vals->Set(1, SWIG_From_double  (std::imag(c)));
  SWIGV8_ESCAPE(vals);
}
```

**Comment by wsfulton** [comment]
See commit above to fix it by correctly calling `SWIGV8_ARRAY_NEW`.
