### ISSUE TITLE
Can the js generated by swig  run in browsers？

### ISSUE THREAD

**Issue by lokpoi888** [swig/swig#1189]
I want to use swig generate js code from c++， but here generates some .node files. Can the js generated by swig run in browsers, such as chrome and firefox？ BTW: Does the swig use the LLVM technology just like Emscripten? Is there differences between swig and Emscripten when generating js? 
Thank you!

**Comment by wsfulton** [comment]
SWIG generates C/C++ for access from Javascript to talk to your C/C++ compiled code and so your browser's security policies must allow native code to be loaded. I'm no expert on Javascript or browser configuration, but I think there is very little chance this will work out of the box. I suggest you research native code support on the browser support forums. The SWIG docs on the subject at http://swig.org/Doc3.0/Javascript.html#Javascript_overview state:

> Extending a general purpose web-browser is not possible as this would be a severe security issue.

SWIG doesn't use LLVM, it has its own C/C++ parser. Emscripten seems to convert the C/C++ code into pure Javascript code rather than SWIG's approach of generating code to interface to C/C++ code, so would not be restricted by the native code loading issues mentioned above.

**Comment by mmomtchev** [comment]
I have published `node-magickwand@1.0.0-beta.0`, you can install it with

```
npm install node-magickwand@next
```

It includes a WASM version built from the same source files as the Node.js native version.

You can read more about SWIG Node-API WASM on the project's homepage.

**Comment by JensMunkHansen** [comment]
It is an awesome project. I have been using SWIG for more than a decade for other languages and now just started with JavaScript. Looking forward to see the typescript generation in SWIG main, but to be honest that part is not the most important to me. I would love to explore generating type library (or runtimes) with SWIG that can be shared between multiple WASM files.

**Comment by mmomtchev** [comment]
I am planning to do this, but it is a very substantial project and WASM is currently a fast moving target.

I am currently wrapping `PROJ` - the geographic projections library - which is a very basic building block of all GIS projects. When someone uses `PROJ` and lets say `GEOS` (the geometric engine) and `GDAL` (the GIS data engine) in the same C++ project, he will load all three shared libraries and these libraries will use each other, allowing to work on the same objects with all the APIs.

Currently, if one uses SWIG to wrap them, they will be three separate WASM instances and it won't be possible to use a projection obtained from `proj.js` in `gdal.js` as these types won't be compatible. `gdal.js` will have its own copy of `PROJ` which will be independent of the one in `proj.js`.

Ideally, one would want to be able to have an `npm` package will `gdal.js` that depends on another `npm` package `proj.js` - with both being able to work together as in C++.

However, with the current state of the dynamic linker in emscripten, this would require very substantial work in SWIG. Every module will have to have two parts, a main module that interfaces with JavaScript and a side module which contains the library (main/side module are emscripten dynamic linker terms). Only the first main module will be loaded and it will expose all the side modules to JavaScript. This way, when a user loads `gdal.js`, it will load the `gdal.js` main module which will export both the `gdal.js` and the `proj.js` APIs. If another user wants to use only `proj.js`, it will load only the `proj.js` main module which will load only the `proj.js` side module and export only the `PROJ` API.

Not only this is a huge undertaking, but it is also not very future-proof. Currently, there is a new standard emerging, called WASI, which is still not mature enough, but which is supposed to solve many of the quirks of emscripten. WASI will render this work obsolete. It has its own modules system, called WASI components.

Also, WASM is only part of this equation. There are a host of other problems when targeting Node.js with native modules.

I am still hesitating on what approach I will eventually adopt, but as I am currently completely isolated from both the rest of the WASM community and the GIS community, it unlikely that this will be implemented anytime soon.
