### ISSUE TITLE
swig.org is down

### ISSUE THREAD

**Issue by marcban** [swig/swig#1196]
Sourceforge has changed its site ...
Time to use github.io ?

**Comment by wsfulton** [comment]
We were a bit slow in changing the DNS settings for an IP address change on our host. It should come right soon.

**Comment by marcban** [comment]
thanks!

**Comment by hasinitg** [comment]
I have been trying to access the website for about three days. Could I please know when the website will be back or could I know any other place to download the SWIG tarball for installation? I know I can install from source in the GitHub repository, but I also read that it takes more steps than installing from the tarball.

Thanks,
Hasini.

**Comment by wsfulton** [comment]
See https://sourceforge.net/projects/swig/files/swig/ and https://sourceforge.net/projects/swig/files/swigwin/ for downloads.

We're having a few problems getting the site up and running again but are looking at it.
Adding @dabeaz.

**Comment by hasinitg** [comment]
Thank you. I appreciate your reply.

**Comment by ojwb** [comment]
Website is working again now so closing.

**Comment by sqred** [comment]
it's down again...

**Comment by russell-taylor** [comment]
Has been down for about a day

**Comment by ojwb** [comment]
Seems to SF again.
