### ISSUE TITLE
Can't find configure script anywhere

### ISSUE THREAD

**Issue by gbpoole** [swig/swig#1197]
I have cloned SWIG from github just now (commit 7fbdd21).  The instructions in 'INSTALL' say:

  1. `cd' to the directory containing the package's source code and type
     `./configure' to configure the package for your system.

Two things about this: first, "the directory containing the package source code" is a bit vague (I'm guessing this should be the root directory of the repo ... or should it be 'Source'?).  Second, I can not locate (nor can 'find . -name configure') a file called 'configure' anywhere in the directory tree.

**Comment by ojwb** [comment]
`INSTALL` describes how an end-user would build the code of a stable release tarball.

Developers wanting to build the latest code from git need to follow the instructions here (google webcache link as the website is down right now for a server migration):

http://webcache.googleusercontent.com/search?q=cache:L2PjjYFHK3EJ:www.swig.org/svn.html
