### ISSUE TITLE
TypeError in Python of type "'std::vector< std::vector< std::string....'"

### ISSUE THREAD

**Issue by carmesean** [swig/swig#1198]
##### 
-->
- SWIG => 3.0.12
- Operating System / Platform => MacOS Sierra 10.12.6
- Compiler => Python via Terminal
-->

##### Detailed description

I am attempting to create Python modules using SWIG. However, in both of my modules, I am getting the same error (TypeError). So, I will post the header and interface file for both, below.

I get this error when after I import the module and call the function with the appropriate parameters: 

TypeError: in method 'myFunction', argument 6 of type `std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > > &`

I have imported std_string.i and std_vector.i. I am using templates, and I am using namespace std. I am also using the most recent version of SWIG(3.0.12), so I am not sure why I am getting this error. 

##### Foo.i
```
/* File : Foo.i */
%module Foo
%{
#include "Foo.h"
%}

%include <std_string.i>
%include <std_vector.i>

// Instantiate templates used
namespace std {
   %template(IntVector) std::vector<int>;
   %template(IntVectorVector) std::vector< std::vector<int> >;
   %template(DoubleVector) std::vector<double>;
   %template(DoubleVectorVector) std::vector< std::vector<double> >;
   %template(StringVector) std::vector<std::string>;
   %template(StringVectorVector) std::vector< std::vector<std::string> >;
   %template(ConstantCharacterVector) std::vector<const char*>;
}

/* Parse the original header file */
%include "Foo.h"
```
##### Foo.h
```
#include "iostream"
#include "fstream"
#include "sstream"
#include "string"
#include "vector"
#include "algorithm"
#include "cstring"
#include "cstdlib"
#include "cstdio"
#include "cmath"
//using namespace std;
//I am only posting the function in question
extern int myFunction(const std::string &in, int a,int b, int c, std::vector <int> &out, std::vector <std::vector <std::string> > & d_in, std::vector <std::vector <int> > & e_out);

//edited to put include statements in Foo.h in quotations as they do not appear inside of the brackets 
```

**Comment by wsfulton** [comment]
```swig
// Instantiate templates used
namespace std {
   %template(IntVectorVector) std::vector<int>;
   %template(IntVectorVector) std::vector< std::vector<int> >;
   ...
```
This is instantiating `std::std::vector<int>` which is wrong. Remove the encapsulating namespace so that you instantiate it correctly as: `std::vector<int>`. You also have two %template statements for IntVectorVector, you should rename one of them as the 2nd one is being ignored. SWIG warns about this, please use the warnings!

**Comment by carmesean** [comment]
@wsfulton It should be IntVector. It is represented correctly in my actual code, but I made a typo recreating it here.

**Comment by wsfulton** [comment]
Works for me:
```python
out = IntVector()
d_in = StringVectorVector()
e_out = IntVectorVector()

myFunction("hi", 0, 0, 0, out, d_in, e_out)
```

**Comment by carmesean** [comment]
Ah! So I have another module name Boo. So whenever I assign d_in, I had been doing: d_in = Boo.StringVectorVector instead of d_in = Boo.StringVectorVector(). Thanks so much! It works now.

**Comment by carmesean** [comment]
I was getting the same error for my module Boo as I was for Foo. I applied the correct way of assigning the templates, however now I am getting another TypeError with the model. I have a model called myModel. It lies in "/Users/me/Boo/models/myModel.10." When I assign booModel = "/Users/me/Boo/models/myModel", I get the error, `TypeError: in method 'myOtherFunction', argument 2 of type 'booModel *'.` I think this is because the type is actually String, since it is in quotation marks, but how else can I assign a model type to this variable if it is a file?
