### ISSUE TITLE
[php] incorrect generation of .php wrapper for reference parameters

### ISSUE THREAD

**Issue by netx123** [swig/swig#1203]
Tested with 3.0.12 release, using the following parameters:
swig -c++ -php5 reftest.i

According to the documentation chapter 34.2.5 Pointers and References, you can apply the REF typemaps to parameters, whilst the resulting reftest_wrap.cpp file is generated correctly, the reftestWrapper.php file is not correct and is missing the required "&" symbols to ensure that the parameters are correctly passed byref.

Expected result:
abstract class reftestWrapper {
	static function Foo(**&**$ref1,**&**$ref2) {
		Foo($ref1,$ref2);
	}
}

Actual result:
abstract class reftestWrapper {
	static function Foo($ref1,$ref2) {
		Foo($ref1,$ref2);
	}
}

The interface file is as follows:
/* File : reftest.i */

%include <windows.i>
%include "typemaps.i"

#if defined(SWIGPHP)
%include "phppointers.i"
#endif

%module reftestWrapper
%{
#include "reftest.h"
%}

#if defined(SWIGPHP)
%apply int *REF { int *ref1, int *ref2 };
#endif

%include "reftest.h"

The reftest.h is:
/* File : reftest.h */
void Foo(int * ref1, int * ref2)
{
	*ref1=1;
	*ref2=2;
}

I have attached the repro files.
[reftest.zip](https://github.com/swig/swig/files/1758371/reftest.zip)

**Comment by ojwb** [comment]
I get your "expected result" if I generate for PHP7 with master (`swig -php7 reftest.i`).

If I generate for PHP5 (`swig -php reftest.i`) then the `&` are still missing though.

I'm unfortunately very short of time currently, and probably unlikely to have time to look at this (especially as PHP5 is only 10 months for final end of life, even with its greatly extended security support period).

I'm happy to apply a clean patch though.

**Comment by ojwb** [comment]
PHP5 has now reach EOL and we've dropped support for it.

As noted above, SWIG generates the code you expect for PHP7, so closing.
