### ISSUE TITLE
`make check` cannot find `Python.h` when pyenv is used

### ISSUE THREAD

**Issue by gvoysey** [swig/swig#1209]
I manage my python versions with `pyenv`(https://github.com/pyenv/pyenv), which by default builds python from source into `$HOME/.pyenv/` and sets paths appropriately. 

To build swig: 
```
export PYTHON_INCLUDE_DIR=$HOME/.pyenv/versions/3.6.3/include/python3.6m/
export PYTHON_LIBRARY=$HOME/.pyenv/versions/3.6.3/lib/
git clone https://github.com/swig/swig
cd swig
git checkout rel-3.0.12
./autogen.sh
./configure
make
``` 
all of which proceeds without error. 

however, running `make check` results in 
```
checking Examples/python/callback
example_wrap.cxx:174:21: fatal error: Python.h: No such file or directory
compilation terminated.
../../Makefile:354: recipe for target 'python_cpp' failed
make[3]: *** [python_cpp] Error 1
Makefile:14: recipe for target 'build' failed
make[2]: *** [build] Error 2
make[2]: Target 'check' not remade because of errors.
Makefile:255: recipe for target 'callback.actionexample' failed
make[1]: *** [callback.actionexample] Error 2
```
and similar for every python test. 

Are these the wrong environment variables to pass to specify the library locations? 

when i run `./config`, i get: 
```
checking for python... python
checking for python major version number... 3
checking for Python os.name... posix
checking for python3... python3
checking for python3-config... python3-config
checking for python3 major version number... 3
checking for Python 3.x os.name... posix
checking for Python 3.x prefix... /home/gvoysey/.pyenv/versions/3.6.3
checking for Python 3.x exec-prefix... /home/gvoysey/.pyenv/versions/3.6.3
checking for Python 3.x version... python3.6
checking for Python 3.x lib dir... lib
checking for Python 3.x header files... -I/home/gvoysey/.pyenv/versions/3.6.3/include/python3.6m -I/home/gvoysey/.pyenv/versions/3.6.3/include/python3.
6m
checking for Python 3.x library directory... Not found
checking for Python 3.x library... -lpython3.6
```

so it seems like `PYTHON_LIBRARY` is ignored?

**Comment by wsfulton** [comment]
Where did you get PYTHON_INCLUDE_DIR and PYTHON_LIBRARY from? They aren't anything I recognise.

From the output of your configure script, I can see python3 was found and seems to find everything.  The output below is for Windows .lib files, so is expected on your Unix OS:
```
checking for Python 3.x library directory... Not found
```
There is a peculiarity with Python 3 and that is you need to run the test-suite as follows:
```make check-python-test-suite PY3=1```
Can you try that? Without the `PY3=1` it will run Python 2. It's a quirk we ought to improve.

**Comment by gvoysey** [comment]
That works flawlessly; thanks for the quick reply!
