### ISSUE TITLE
Python base class has __init__ in namespace

### ISSUE THREAD

**Issue by wfspotz** [swig/swig#1219]
I am using SWIG to generate a python package, let's call it `Package`, with two submodules, let's call them `Submodule1` and `Submodule2`. I want the `Package` directory structure to be the following:

    Package\
        __init__.py
        Submodule1/
            __init__.py
            ___init__.so
        Submodule2.py
        _Submodule2.so

`Submodule1` has a single header file:

    // Filename Submodule1_Base.hpp
    namespace Submodule1{ class Base{}; }

and `Submodule2` has a single header file:

    // Filename Submodule2_Derived.hpp
    #include "Submodule1_Base.hpp"
    namespace Submodule2{ class Derived : public Submodule1::Base {}; }

The interface file for `Submodule1` is

    // Filename Submodule1.__init__.i
    %module(package="Package/Submodule1") __init__
    %{
    #include "Submodule1_Base.hpp"
    %}
    %include "Submodule1_Base.hpp"

and the interface file for `Submodule2` is

    // Submodule2.i
    %module(package="Package") Submodule2
    %{
    #include "Submodule2_Derived.hpp"
    %}
    %import "Submodule1.__init__.i"
    %include "Submodule2_Derived.hpp"

I run SWIG:

    $ swig -c++ -python -outdir Package/Submodule1 Submodule1.__init__.i
    $ swig -c++ -python -outdir Package Submodule2.i

In the generated `Package/Submodule2.py`, I get the following:

    import Package.Submodule1.__init__
    class Derived(Package.Submodule1.__init__.Base):
        ...

I understand why SWIG generates this, and it is the expected behavior, but it is not proper python. What is desired is

    import Package.Submodule1
    class Derived(Package.Submodule1.Base):
        ...

Is there a workaround for this?

**Comment by ojwb** [comment]
I don't think we support calling your module `__init__` like this - I don't see anything in the manual about it.

What we do for xapian's python bindings is to generate a module with the actual name we want (`Submodule1` in this case) and then just rename `Submodule1.py` to `Submodule1/__init__.py`, and replace the module loading logic using (for Python3):

```
%module(directors="1", moduleimport="from . import _xapian") xapian
```

The `moduleimport` feature was added in SWIG 3.0.11.

**Comment by wfspotz** [comment]
@ojwb OK, I can probably make that work. Thanks.
