### ISSUE TITLE
Unable to load PHP extension created with swig for a c++ Shared library

### ISSUE THREAD

**Issue by linhpnph04070** [swig/swig#1220]
I'm using jsoncpp in my c++ shared library to manipulate json data, the extension that I m creating is successfully built with swig but is unable to load as PHP extension. Can anyone help me find a way to load Shared lib that uses json or jsoncpp to be used in PHP as an extension? 
[hellojso.tar.gz](https://github.com/swig/swig/files/1867304/hellojso.tar.gz)

this is error on comnand:`PHP Warning:  PHP Startup: Unable to load dynamic library 'shared.so' (tried: /usr/lib/php/20170718/shared.so (/usr/lib/php/20170718/shared.so: undefined symbol: _ZTVN4Json12StyledWriterE`

**Comment by ojwb** [comment]
Sounds like you need to link against the library which provides symbol `_ZTVN4Json12StyledWriterE`.

Not a SWIG bug, so closing.  Questions are better sent to the mailing list - far more people read that.

**Comment by linhpnph04070** [comment]
can you  provide more detail about it, because i have to link the lib in php by creating the php extension

**Comment by ojwb** [comment]
Then you'll need to tell PHP to link to the library with that symbol.  I don't know how one does that.  Try the mailing list if you can't work it out.
