### ISSUE TITLE
Swig clutters Python-API with _swigregister objects

### ISSUE THREAD

**Issue by philippkraft** [swig/swig#1225]
# Problem
When I create a Python wrapper for a C++ library (no -builtin flag) the resulting lib.py contains for each class (`CLASS`) something like this:

    CLASS_swigregister = _lib.CLASS_swigregister
    CLASS_swigregister(CLASS)

The extra CLASS_swigregister member of the API is annoying since users of that library do not necessarily know or care that the library was created with swig (of which I am a fan since years). Users see it in an IDE and do not know what to do.

# Possible solution

I have changed my rather large API with some simple regex to the following:

    _lib.CLASS_swigregister(CLASS)

This works without a problem (for me at least). Can SWIG create this single line as standard behaviour? Or is there any need for `CLASS_swigregister` residing in the public API?

**Comment by ojwb** [comment]
It's not documented in the manual as an API for the user.  There are a couple of somewhat cryptic mentions in `CHANGES` which don't really seem to explain how it's useful.

Does the testsuite pass if you change SWIG as you suggest?

**Comment by philippkraft** [comment]
### To clarify the Problem: 
With public API I mean the structure of the lib.py file. If one of my users (who do not care about SWIG) use my library in an IDE or in an interactive prompt, they get the CLASS_swigregister function shown as a public (no underscore) function of the API of my class:

![grafik](https://user-images.githubusercontent.com/16303297/38600652-341ea558-3d65-11e8-9be3-b1b2a750689c.png)

So my users see this and do not know what to do with it.

### Testing

Until now I have not changed anything in the SWIG code, I just modified the output after the SWIG run and run the testsuite of my library - not SWIG's since SWIG is still untouched. I've never tried to compile SWIG myself. However, I can change the relevant 2 lines in python.cxx as a pull request and we see how travis deals with them. Would that be ok?

**Comment by philippkraft** [comment]
Btw, CLASS_swiginit works already exactly as I suggest it for CLASS_swigregister ([see here](https://github.com/swig/swig/blob/3042ff60fe42553df1fe51343d1bcd5aa96c825d/Source/Modules/python.cxx#L4954).

The lines I mean are [here](https://github.com/swig/swig/blob/3042ff60fe42553df1fe51343d1bcd5aa96c825d/Source/Modules/python.cxx#L4635-L4636):

	Printf(f_shadow_file, "%s_swigregister = %s.%s_swigregister\n", class_name, module, class_name);
	Printf(f_shadow_file, "%s_swigregister(%s)\n", class_name, class_name);

And I would change them to:

	Printf(f_shadow_file, "# Register %s in %s:\n", class_name, module);
	Printf(f_shadow_file, "%s.%s_swigregister(%s)\n", module, class_name, class_name);

**Comment by ojwb** [comment]
> However, I can change the relevant 2 lines in python.cxx as a pull request and we see how travis deals with them. Would that be ok?

You should run the testsuite locally **before** opening a pull request.  Flinging untested changes out into the world to see if they pass CI is really abusing both the CI resources (which are provided to us free of charge) and maintainers' limited time.

It's not hard - just make sure you have the python dev stuff installed, and then `make check-python-test-suite` and `make check-python-examples`.

**Comment by philippkraft** [comment]
`make check-python-examples` runs without failures after applying the diff given below, after setting `CPATH` to include python/include and boost.

```diff
diff --git a/Source/Modules/python.cxx b/Source/Modules/python.cxx
old mode 100644
new mode 100755
index 4a1b475..fe42b00
--- a/Source/Modules/python.cxx
+++ b/Source/Modules/python.cxx
@@ -4632,8 +4632,8 @@ public:
                   class_name);
          }
        }
-       Printf(f_shadow_file, "%s_swigregister = %s.%s_swigregister\n", class_name, module, class_name);
-       Printf(f_shadow_file, "%s_swigregister(%s)\n", class_name, class_name);
+       Printf(f_shadow_file, "# Register %s in %s:\n", class_name, module);
+       Printf(f_shadow_file, "%s.%s_swigregister(%s)\n", module, class_name, class_name);
       }
```

The first new line can be deleted instead.

May I do the pull request now?

**Comment by philippkraft** [comment]
Other projects with the same issue, but they handled it post-build (found by searching for "_swigregister":

- https://github.com/rk700/PyMuPDF/issues/36
- https://cta-redmine.irap.omp.eu/issues/832
- https://www.python-forum.de/viewtopic.php?t=27300
- http://docs.ros.org/diamondback/api/wxPython_swig_interface/html/__core__ex_8py_source.html
- https://sourceforge.net/projects/gpstk/files/gpstk/2.5/

**Comment by ojwb** [comment]
> May I do the pull request now?

Sure (there's no need to ask permission to do so - I was just noting that one ought to test locally before opening a PR, but you've done that now).
