### ISSUE TITLE
return c++/java char * but not string

### ISSUE THREAD

**Issue by manang** [swig/swig#1231]
Hi,
I'm trying to use this library. I'm starting with the java/callback example.
The only thing that I can't manage is that I want that the callback function has to return a char * array. I don't want to manage a string, but a byte array, because I will work with binary arrays.
How can I return the array and the size of the array at the end of the java callback function?
Thank you very much
Angelo

**Comment by cuent** [comment]
Hi, I am having the same problems. I found this [issue](https://stackoverflow.com/questions/2740068/how-can-i-make-swig-correctly-wrap-a-char-buffer-that-is-modified-in-c-as-a-jav), hope it helps.

**Comment by ojwb** [comment]
Thanks, that link seems to answer the question.
