### ISSUE TITLE
Numeric overloading sensitive to C++11 support

### ISSUE THREAD

**Issue by jakecobb** [swig/swig#1239]
Discovered during testing of PR #1234.  The `overload_numeric` test fails for me by default on OS X Sierra with the following clang:

```
$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

It chooses the `double` overload instead of the `float` overload for infinity.

This is not the default clang that ships with my Xcode version (8.1), but one I upgraded to from the Apple developer site.  It seems that it does not do C++11 by default and needs the `-std=c++11` flag explicitly, whereas the shipped clang enables C++11 features without the flag.

This is due to the following fragment from `Lib/typemaps/fragments.swg`:

```
%fragment("SWIG_isfinite","header",fragment="<math.h>,<float.h>") %{
/* Getting isfinite working pre C99 across multiple platforms is non-trivial. Users can provide SWIG_isfinite on older platforms. */
#ifndef SWIG_isfinite
/* isfinite() is a macro for C99 */
# if defined(isfinite)
#  define SWIG_isfinite(X) (isfinite(X))
# elif defined __cplusplus && __cplusplus >= 201103L
/* Use a template so that this works whether isfinite() is std::isfinite() or
 * in the global namespace.  The reality seems to vary between compiler
 * versions.
 *
 * Make sure namespace std exists to avoid compiler warnings.
 *
 * extern "C++" is required as this fragment can end up inside an extern "C" { } block
 */
namespace std { } 
extern "C++" template<typename T>
inline int SWIG_isfinite_func(T x) {
  using namespace std;
  return isfinite(x);
}
#  define SWIG_isfinite(X) (SWIG_isfinite_func(X))
# elif defined(_MSC_VER)
#  define SWIG_isfinite(X) (_finite(X))
# elif defined(__sun) && defined(__SVR4)
#  include <ieeefp.h>
#  define SWIG_isfinite(X) (finite(X))
# endif
#endif
%}
```
Interacting with the overflow check:

```
%fragment("SWIG_Float_Overflow_Check","header",fragment="<float.h>,SWIG_isfinite") %{
/* Accept infinite as a valid float value unless we are unable to check if a value is finite */
#ifdef SWIG_isfinite
# define SWIG_Float_Overflow_Check(X) ((X < -FLT_MAX || X > FLT_MAX) && SWIG_isfinite(X))
#else
# define SWIG_Float_Overflow_Check(X) ((X < -FLT_MAX || X > FLT_MAX))
#endif
%}
```

C++11 testing is off by default in the autoconf setup.  If I enable it with `--enable-cpp11-testing` on this same platform, `configure` shows...

```
checking whether to enable C++11 testing... yes
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=c++11... yes
checking for C++11 enabled compiler... yes
```

...and the test passes.

**Comment by ojwb** [comment]
Aha, good sleuthing.

The whole `SWIG_isfinite()` situation is rather unsatisfactory, but at least it seemed to be becoming a non-issue as compilers all seem to be moving to supporting at least C++11 by default these days.  It is annoying if Apple are really moving backwards.

We could use `__builtin_isfinite()` where available, which should cover this situation and quite a lot of others as it's apparently supported by GCC >= 4.2 (from docs) and clang >= 3.6 (oldest version I have to had to test with).  For clang we can use `__has_builtin()` to test for it, so something like:

```
#elif (defined __has_builtin && __has_builtin(__builtin_isfinite)) || (defined __GNUC__ && (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 2)))
# define SWIG_isfinite(X) (__builtin_isfinite(X))
```

@jakecobb Does patching the above in solve this with your setup?

**Comment by jakecobb** [comment]
Yes, that does fix it.  I added it as the next condition after the C++11 check and before the Microsoft compiler check.

For posterity, I may be to blame more than Apple.  They install newer clangs into `/Library/Developer/CommandLineTools` but I copied it into my Xcode.app trying to debug another problem I thought might be compiler version related, so this header situation might not occur under normal circumstances.  That being said, I think the reason it side-stepped the existing SWIG logic is because of the header _<toolchain_path>_`/usr/include/c++/v1/math.h`, which uses the `isfinite` macro to define C++ functions and then `#undef`s it:

```cpp
// isfinite

#ifdef isfinite

template <class _A1> 
_LIBCPP_ALWAYS_INLINE
bool
__libcpp_isfinite(_A1 __lcpp_x) _NOEXCEPT
{
    return isfinite(__lcpp_x);
}

#undef isfinite

template <class _A1> 
inline _LIBCPP_INLINE_VISIBILITY
typename std::enable_if<
    std::is_arithmetic<_A1>::value && std::numeric_limits<_A1>::has_infinity,
    bool>::type
isfinite(_A1 __lcpp_x) _NOEXCEPT
{
    return __libcpp_isfinite((typename std::__promote<_A1>::type)__lcpp_x);
}

template <class _A1> 
inline _LIBCPP_INLINE_VISIBILITY
typename std::enable_if<
    std::is_arithmetic<_A1>::value && !std::numeric_limits<_A1>::has_infinity,
    bool>::type
isfinite(_A1) _NOEXCEPT
{ return true; }

#endif  // isfinite
```

I'm not 100% certain on this though because this file seems to assume C++11 features like `std::is_arithmetic`.  When I compare to the usr/include/c++/v1 that shipped with Xcode 8.1 the latter did not have a `math.h` in it.

**Comment by wsfulton** [comment]
Actually, this problem is also present in later versions of gcc (6 onwards) when using the c++98 standard. The testcase fails using the following (assuming you have all the given versions of gcc installed):
```
~/swig/github/swig/Examples/test-suite/python $ make -s overload_numeric.cpptest CXXFLAGS=-std=c++98 CXX=g++-6
~/swig/github/swig/Examples/test-suite/python $ make -s overload_numeric.cpptest CXXFLAGS=-std=c++98 CXX=g++-7
~/swig/github/swig/Examples/test-suite/python $ make -s overload_numeric.cpptest CXXFLAGS=-std=c++98 CXX=g++-8
```
My clang 3.8 on Linux also fails using c++98:
```
~/swig/github/swig/Examples/test-suite/python $ make -s overload_numeric.cpptest CXXFLAGS=-std=c++98 CXX=clang++-3.8
```
My gcc-5 passes using c++98:
```
~/swig/github/swig/Examples/test-suite/python $ make -s overload_numeric.cpptest CXXFLAGS=-std=c++98 CXX=g++-5
```
@ojwb's fix works for my clang too, but results in this for gcc 6 and later (using -std=c++98):
```
overload_numeric_wrap.cxx:3451:46: error: missing binary operator before token "("
 #elif (defined __has_builtin && __has_builtin(__builtin_isfinite)) || (defined __GNUC__ && (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 2)))
```
It looks like `__has_builtin` is a clang macro and should be used as mentioned at https://clang.llvm.org/docs/LanguageExtensions.html#has-builtin so I've gone with the following addition to fix:
```c
# elif defined(__GNUC__) && (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 2))
#  define SWIG_isfinite(X) (__builtin_isfinite(X))
# elif defined(__clang__) && defined(__has_builtin)
#  if __has_builtin(__builtin_isfinite)
#   define SWIG_isfinite(X) (__builtin_isfinite(X))
#  endif
```
See 3e4b7269c0d8880f1c1dbed38320e1673470288a.

**Comment by ojwb** [comment]
```
# elif defined(__GNUC__) && (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 2))
#  define SWIG_isfinite(X) (__builtin_isfinite(X))
# elif defined(__clang__) && defined(__has_builtin)
#  if __has_builtin(__builtin_isfinite)
#   define SWIG_isfinite(X) (__builtin_isfinite(X))
#  endif
```

With those modifications, I don't think the `__clang__` branch will actually ever get used since clang defines `__GNUC__` to 4 and `__GNUC_MINOR__` to 2 (for all the versions I have to hand from clang 3.6.2 to 7.0.0).
