### ISSUE TITLE
Add support for Node-API for node

### ISSUE THREAD

**Issue by murillo128** [swig/swig#1243]
N-API is no longer experimental in node 10.

https://levelup.gitconnected.com/whats-new-in-node-10-ad360ae55ee4

```
the Node documentation describes N-API as an API for building native Addons. It is independent from the underlying JavaScript runtime (ex V8) and is maintained as part of Node.js itself. This API will be Application Binary Interface (ABI) stable across versions of Node.js. It is intended to insulate Addons from changes in the underlying JavaScript engine and allow modules compiled for one version to run on later versions of Node.js without recompilation.

N-API was experimentally introduced in Node 8 and is going to be to be stable beginning in Node 10. Upgrading between Node versions will no longer cause concern for module breakage. It will also be ported backwards for Node.js v6.x and v8.x compatability.
```
So IMHO it would be a good idea to migrate current swig node support from v8/nan to n-api as it provides binary compatibility and is the now preferred way of implementing native extensions

https://nodejs.org/api/n-api.html

**Comment by p2k** [comment]
Thanks for creating the ticket, should have done it myself now that I think of it... my bad.

I will use this ticket to track progress on the N-API implementation. Currently I'm still fully occupied with work until roughly end of May, but I'll give my best to get myself free for this.

**Comment by murillo128** [comment]
I can help, should we start by creating the skeleton of the empty module so we now what needs to be added and where?

**Comment by p2k** [comment]
Sounds fine, go ahead.

**Comment by stevebaxter** [comment]
Is this something that is likely to get added to SWIG anytime soon? We use SWIG for lots of bindings, we need N-API support for a new project.

**Comment by p2k** [comment]
Things have gone horribly wrong at my company over the last months. Looks like I can't work on this until the end of the year.

**Comment by stevebaxter** [comment]
OK, thanks for the update and hope things look up!

**Comment by ekraihan** [comment]
Has there been any recent movement on this ticket?

**Comment by murillo128** [comment]
seems it would be easier to use the c++ n-api wrapper:

https://github.com/nodejs/node-addon-api

**Comment by dlong11** [comment]
Curious, does SWIG plan to support N-API for future releases?

**Comment by sigmasoldi3r** [comment]
Any updates on this topic?

**Comment by ojwb** [comment]
> Curious, does SWIG plan to support N-API for future releases?

SWIG is a volunteer project - this needs somebody to step up and submit a patch.

**Comment by ojwb** [comment]
N-API seems to now be called Node-API so retitling.

**Comment by ojwb** [comment]
Added by #2545.
