### ISSUE TITLE
Add support for Raku

### ISSUE THREAD

**Issue by sumanstats** [swig/swig#1245]
Hi,

Swig project looks fantastic and promising helping users easily write bindings to C library.

I love to see the swig project [support `Raku`](https://raku.org/).
Raku is different language than Perl and adding support to it would help many libraries in `C` ported to `Raku`.

Thank you

**Comment by vadz** [comment]
This is something I'd like to have too and it should be relatively simple to do: thanks to Perl6 (supposedly, I didn't really test it myself) excellent FFI support, SWIG would just have to generate the `native` functions for the exported C ones. Unfortunately I'm extremely unlikely to have time to work on this in the observable future, so I can just hope someone else is motivated enough to do it.

**Comment by ojwb** [comment]
Support for a new target language really needs to be contributed by someone who knows that language.  Nobody has stepped forward offering to do that in 4 years, so closing.

If someone is genuinely interested we can reopen.  To be merged a patch needs to meet the requirements list for a new "experimental" target language: https://www.swig.org/Doc4.0/Extending.html#Extending_experimental_status so please see that to get some idea what you're signing up for.
