### ISSUE TITLE
%ignore is not stoping creating method in wrap file.

### ISSUE THREAD

**Issue by myproject24** [swig/swig#1249]
//----------------- Interface.i-----------------------
%module(directors="1") TestRuby

%include <windows.i>

%begin %{
#include "Engine.hpp"
#include "ruby.h"
using namespace TEST;
%}

%include "Engine.hpp"

%ignore TEST::Fact(int n);

------------------------Engine.hpp-------------------
namespace TEST {

	class PPR_EXPORT Test {
	public:
		int Add(int a, int b);
		int Sub(int a, int b);
		int Mul(int a, int b);
	};

	int Fact(int n);

}

I don't want to create wrapper method for Fact(int) so I tried to ignore it but fail to ignore, I don't want to expose this method. To solve this please help me

**Comment by vadz** [comment]
You need to use `%ignore` _before_ `%include`, otherwise it's too late.
