### ISSUE TITLE
Seg Fault in Using JNI_CreateJavaVM in c++ wrapper for python

### ISSUE THREAD

**Issue by rmalav15** [swig/swig#1250]
Hey,
We are using JNI to interact between c++ and Java Jars in following programme:

```
 #include <stdio.h>
 #include <jni.h>
 #include<string.h>
 #include <iostream>
 // #include <chrono>
 

 JNIEnv* create_vm(JavaVM **jvm)
 {
     JNIEnv* env;
     JavaVMInitArgs args;
     JavaVMOption options;
     args.version = JNI_VERSION_1_8;
     args.nOptions = 1;
     options.optionString = "-Djava.class.path=jsapi.jar";
    
     args.options = &options;
     args.ignoreUnrecognized = 0;
     int rv;
     rv = JNI_CreateJavaVM(jvm, (void**)&env, &args);
     if (rv < 0 || !env)
         printf("Unable to Launch JVM %d\n",rv);
     else
         printf("Launched JVM! :)\n");
     return env;
 }

 int main_fn()
 {
     JavaVM *jvm;
     JNIEnv *env;
     env = create_vm(&jvm);
     if(env == NULL)
         return 1;
     //invoke_class(env);
     jvm->DestroyJavaVM();
     return 0;
 }
```
 

And its working as expected after compiling with followings:

> g++ -std=c++0x -o out -I jdk1.8.0_144/include -I jdk1.8.0_144/include/linux/ -L jdk1.8.0_144/jre/lib/amd64/server  test_jni.cpp -ljvm

But when we use swig wrapper to call the main_fn() from python we get segmentation fault with following stack trace (There was no error in building the swig wrapper code):

> Received utterance[length=245760] from 10.158.19.119, saved to demo_cache/20180504155105_10.158.19.119.wav.
> *** Aborted at 1525449065 (unix time) try "date -d @1525449065" if you are using GNU date ***
> PC: @                0x0 (unknown)
> *** SIGSEGV (@0x50) received by PID 7060 (TID 0x7fde57e0a700) from PID 80; stack trace: ***
>     @     0x7fde579e6390 (unknown)
>     @     0x7fde57bfe73c (unknown)
>     @     0x7fde57c07851 (unknown)
>     @     0x7fde57c02564 (unknown)
>     @     0x7fde57c06da9 (unknown)
>     @     0x7fde57407f09 (unknown)
>     @     0x7fde57c02564 (unknown)
>     @     0x7fde57408571 (unknown)
>     @     0x7fde57407fa1 dlopen
>     @     0x7fde133fce75 os::Linux::clock_init()
>     @     0x7fde13400049 os::init()
>     @     0x7fde1354cca2 Threads::create_vm()
>     @     0x7fde131aae64 JNI_CreateJavaVM
>     @     0x7fde13daf06e create_vm()
>     @     0x7fde13daf2dc main_fn()
>     @     0x7fde13d46af8 _wrap_main_fn
>     @           0x4c468a PyEval_EvalFrameEx
>     @           0x4c2765 PyEval_EvalCodeEx
>     @           0x4ca099 PyEval_EvalFrameEx
>     @           0x4c2765 PyEval_EvalCodeEx
>     @           0x4ca8d1 PyEval_EvalFrameEx
>     @           0x4c2765 PyEval_EvalCodeEx
>     @           0x4ca8d1 PyEval_EvalFrameEx
>     @           0x4c9d8f PyEval_EvalFrameEx
>     @           0x4c2765 PyEval_EvalCodeEx
>     @           0x4de6fe (unknown)
>     @           0x4b0cb3 PyObject_Call
>     @           0x4f492e (unknown)
>     @           0x4b0cb3 PyObject_Call
>     @           0x4ce5d0 PyEval_CallObjectWithKeywords
>     @           0x4e17e4 PyInstance_New
>     @           0x4b0cb3 PyObject_Call
> Segmentation fault (core dumped)

It looks like there is some problem in using threads with swig. The[ JNI_CreateJavaVM](https://www.cis.upenn.edu/~bcpierce/courses/629/jdkdocs/guide/jni/spec/invocation.doc.html) function description  says that it "Loads and initializes a Java VM. The current thread becomes the main thread." Which is I think causing the problem. (I am not sure, I may be wrong)

We found that there is [-threads](https://github.com/swig/swig/issues/927) option which is used  with swig to add threads support, but it also didn't help. Please let me know how to solve this, it will be huge help.

Above both scenarios were tested inside a nvidia-docker with Ubuntu image, if that's relevant.

Much Thanks

**Comment by rmalav15** [comment]
I am attaching my .i and setup.py file

`%module("threads"=1) swig_decoders
%{
#include "test_jni.h"
#include "grammar.h"
#include "scorer.h"
#include "ctc_greedy_decoder.h"
#include "ctc_beam_search_decoder.h"
#include "decoder_utils.h"
%}


%include "std_vector.i"
%include "std_pair.i"
%include "std_string.i"
%import "decoder_utils.h"


namespace std {
    %template(DoubleVector) std::vector<double>;
    %template(IntVector) std::vector<int>;
    %template(StringVector) std::vector<std::string>;
    %template(VectorOfStructVector) std::vector<std::vector<double> >;
    %template(FloatVector) std::vector<float>;
    %template(Pair) std::pair<float, std::string>;
    %template(PairFloatStringVector)  std::vector<std::pair<float, std::string> >;
    %template(PairDoubleStringVector) std::vector<std::pair<double, std::string> >;
    %template(PairDoubleStringVector2) std::vector<std::vector<std::pair<double, std::string> > >;
    %template(DoubleVector3) std::vector<std::vector<std::vector<double> > >;
}

%template(IntDoublePairCompSecondRev) pair_comp_second_rev<int, double>;
%template(StringDoublePairCompSecondRev) pair_comp_second_rev<std::string, double>;
%template(DoubleStringPairCompFirstRev) pair_comp_first_rev<double, std::string>;


%include "test_jni.h"
%include "grammar.h"
%include "scorer.h"
%include "ctc_greedy_decoder.h"
%include "ctc_beam_search_decoder.h"


%thread create_vm();`


`"""Script to build and install decoder package."""
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from setuptools import setup, Extension, distutils
import glob
import platform
import os, sys
import multiprocessing.pool
import argparse

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument(
    "--num_processes",
    default=1,
    type=int,
    help="Number of cpu processes to build package. (default: %(default)d)")
args = parser.parse_known_args()

# reconstruct sys.argv to pass to setup below
sys.argv = [sys.argv[0]] + args[1]


# monkey-patch for parallel compilation
# See: https://stackoverflow.com/a/13176803
def parallelCCompile(self,
                     sources,
                     output_dir=None,
                     macros=None,
                     include_dirs=None,
                     debug=0,
                     extra_preargs=None,
                     extra_postargs=None,
                     depends=None):
    # those lines are copied from distutils.ccompiler.CCompiler directly
    macros, objects, extra_postargs, pp_opts, build = self._setup_compile(
        output_dir, macros, include_dirs, sources, depends, extra_postargs)
    cc_args = self._get_cc_args(pp_opts, debug, extra_preargs)

    # parallel code
    def _single_compile(obj):
        try:
            src, ext = build[obj]
        except KeyError:
            return
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)

    # convert to list, imap is evaluated on-demand
    thread_pool = multiprocessing.pool.ThreadPool(args[0].num_processes)
    list(thread_pool.imap(_single_compile, objects))
    return objects


def compile_test(header, library):
    dummy_path = os.path.join(os.path.dirname(__file__), "dummy")
    command = "bash -c \"g++ -include " + header \
                + " -l" + library + " -x c++ - <<<'int main() {}' -o " \
                + dummy_path + " >/dev/null 2>/dev/null && rm " \
                + dummy_path + " 2>/dev/null\""
    return os.system(command) == 0



# hack compile to support parallel compiling
distutils.ccompiler.CCompiler.compile = parallelCCompile

FILES = glob.glob('kenlm/util/*.cc') \
        + glob.glob('kenlm/lm/*.cc') \
        + glob.glob('kenlm/util/double-conversion/*.cc')

FILES += glob.glob('openfst-1.6.3/src/lib/*.cc')

FILES = [
    fn for fn in FILES
    if not (fn.endswith('main.cc') or fn.endswith('test.cc') or fn.endswith(
        'unittest.cc'))
]

LIBS = ['stdc++']
if platform.system() != 'Darwin':
    LIBS.append('rt')

ARGS = ['-O3', '-DNDEBUG', '-DKENLM_MAX_ORDER=6', '-std=c++11']

if compile_test('zlib.h', 'z'):
    ARGS.append('-DHAVE_ZLIB')
    LIBS.append('z')

if compile_test('bzlib.h', 'bz2'):
    ARGS.append('-DHAVE_BZLIB')
    LIBS.append('bz2')

if compile_test('lzma.h', 'lzma'):
    ARGS.append('-DHAVE_XZLIB')
    LIBS.append('lzma')


#JNI
#ARGS.append('-ljvm')
LIBS.append('jvm')
#LIBS.append('pthread')

os.system('swig -threads -python -c++ ./decoders.i')

decoders_module = [
    Extension(
        name='_swig_decoders',
        sources=FILES + glob.glob('*.cxx') + glob.glob('*.cpp'),
        language='c++',
        include_dirs=[
            '.',
            'kenlm',
            'openfst-1.6.3/src/include',
            'ThreadPool',
            'jdk1.8.0_144/include',
            'jdk1.8.0_144/include/linux/',
        ],
        library_dirs=['jdk1.8.0_144/jre/lib/amd64/server'],
        libraries=LIBS,
        extra_compile_args=ARGS)
]

setup(
    name='swig_decoders',
    version='1.1',
    description="""CTC decoders""",
    ext_modules=decoders_module,
    py_modules=['swig_decoders'], )
`

**Comment by rmalav15** [comment]
This looks related https://community.oracle.com/thread/3558485.

**Comment by ojwb** [comment]
Sorry, I don't think we have the resources to help debug Python/JVM interactions.  It seems from the link in the most recent comment that this isn't specific to SWIG either.
