### ISSUE TITLE
Add support for c++17 namespace declaration (namespace A::B {})

### ISSUE THREAD

**Issue by bansan85** [swig/swig#1251]
Syntaxe `namespace A::B` is not supported in c++17 header.

Exemple :

`header_17.h`

```
namespace A::B
{
  template <typename T>
  class C
  {
  };
}
```

`namespace_17.i`

```
%module namespace_17

%{
#include "header_17.h"
%}

%include "header_17.h"
%template(a_b_c_int) A::B::C<int>;

```

Result of `swig -c++ -java namespace_17.i` : `Error: Undefined scope 'A::B'`

But without c++17 style :

`header.h`

```
namespace A
{
namespace B
{
  template <typename T>
  class C
  {
  };
}
}
```

`namespace.i`

```
%module namespace_ok

%{
#include "header.h"
%}

%include "header.h"
%template(a_b_c_int) A::B::C<int>;
```

It's working well.

**Comment by ojwb** [comment]
Missing C++17 feature.

At this point I don't think support for anything from C++17 has explicitly been implemented (though probably some features which are new in C++17 work because SWIG doesn't need to do anything differently to support them).

**Comment by wsfulton** [comment]
I've added support for C++17 nested namespace declarations and just merged it into master.

**Comment by bansan85** [comment]
Thanks. I will tell you if I found something wrong.
