### ISSUE TITLE
Unsupported variadic template usage

### ISSUE THREAD

**Issue by diorcety** [swig/swig#1258]
In cpp11_variadic_templates.i add the following lines at 70:
```

template <typename... BaseClasses>
void abcd(MultiInherit<BaseClasses...> &h)
```

The following error appears:
Error: Syntax error in input(1)

valparm or valexpr should support something like type PERIOD PERIOD PERIOD

**Comment by wsfulton** [comment]
Okay, this has potential, there are no additional shift/reduce conflicts in the parser, which is good.

Re this change in cpp11_variadic_templates.i:
```swig
%template (Abcd2) Abcd<A,B>;
```
it needs to be
```swig
%template (Abcd1) Abcd<A>;
```
as only one template parameter is supported and I can't see the patch changing this. The Abcd2 code you show actually results in using MultiInherit1 and not MultiInherit2 in the generated code (a runtime test would flush this problem out, but is  easily spotted looking at the generated Java type names). Actually, this testcase is commented out in Examples/test-suite/common.mk as variadic template support is far from working well. 

The docs in the Doc/Manual/CPlusPlus11.html file (or last published at http://swig.org/Doc3.0/CPlusPlus11.html#CPlusPlus11_variadic_templates) will need updating. Those docs only talk about variadic template parameters for template classes, not for template functions. The docs will need an update to match what SWIG supports at some point, but it will be helpful if you describe the improvements in more detail. I think it just allows parsing of the 

The change results in seg faults in a few of the testcases in the test-suite, eg overload_template. 

I'd like the patch broken into two as the parser changes are also adding support for C++ variadic arguments:
```c++
void foo(const char* fmt, ...); // variadic arguments in C
void foo(const char* fmt...); // variadic arguments also in C++
```
A useful reference for this is at http://en.cppreference.com/w/cpp/language/variadic_arguments.

This change should first ensure that no vararg support is broken and the new syntax for parameters in a function (i.e. not template parameters) is working. Then a 2nd patch should build on this one to add variadic template argument support, which will require a few fixes in your patch as it stands.

**Comment by diorcety** [comment]
https://github.com/diorcety/swig/commit/d0e38e99323d23e320bfab91e19a5a329e2faef1#diff-eaef211ed355012097bff4132a2f0168R5147 allows (MultiInherit<BaseClasses...> &h) which doesn't parse currently.
The two other modifications allows variadic template on functions

**Comment by phcerdan** [comment]
What is the status on supporting variadic templates? From my understanding reading this issue and the [docs](http://www.swig.org/Doc3.0/CPlusPlus11.html#CPlusPlus11_variadic_templates). There is support for parsing it, but not for instantiating it with zero or more than one template argument.

I guess this inherits the difficulty of dealing with [variable length arguments](http://www.swig.org/Doc1.3/Varargs.html), but it would be a tremendous feature to support  modern c++!

**Comment by wsfulton** [comment]
The proposed changes by @diorcety need to be put into a pull request and my comments addressed by suitable changes in the pull request before this fix can be used.

**Comment by KimiWu123** [comment]
Hi
What is the status of variadic templates? I check the [4.0 doc](http://www.swig.org/Doc4.0/CPlusPlus11.html#CPlusPlus11_variadic_templates), it seems the same with old one. 

Could you give me some idea how to write the swag file with variadic templates as below snippet (for template functions). I'm trying to wrap 3rd party library so  I don't plan to change their code.
```
template<typename ... Types>
void UNUSED(Types&&...) {}
```
That would be great if you could give me some samples. Thanks.

**Comment by ojwb** [comment]
@diorcety Could you address the comments above and open a PR?
