### ISSUE TITLE
SWIG unable to parse C++ json object to python object

### ISSUE THREAD

**Issue by arslansaleem-aai** [swig/swig#1263]
I am using swig to use some functionality of c++ in python, but i am stuck at a point where i want to give nlohman::json object to c++ function as parameter and get nlohmann::json value to python json.

I tried to get global variable of json but i am unable to access its json value because of its data type. It has below datatype when i print that object.

<Swig Object of type 'nlohmann::json *' at 0x7f493950e870>

Any help/suggestion will be appreciated thanks

**Comment by wsfulton** [comment]
Make sure SWIG parses all the type information for nlohmann::json. Closing as insufficient information to reproduce the error. Feel free to re-open with a small stand-alone example reproducing your issue.
