### ISSUE TITLE
Python deadlock caused by C++ static initializer(s) used in pyrun.swg

### ISSUE THREAD

**Issue by gpshead** [swig/swig#1275]
Specifically: https://github.com/swig/swig/blob/master/Lib/python/pyrun.swg#L494

Being declared static causes a lock to be held by C++ during the execution of `SwigPyObject_TypeOnce()` which includes Python C API calls that ultimate allocate memory via the Python allocator and thus can trigger Python GC run.  A Python GC run can cause a GIL release while doing destruction of some objects which can in turn switch to a new thread which then calls into a SWIG wrapper hitting the exact same static `SwigPyObject_TypeOnce()` locked call... leading to a deadlock.

**Comment by wsfulton** [comment]
Yes, the lazy initialization of these could be moved to the init function ( SWIG_init ). Patches welcome!

**Comment by petrmitrichev** [comment]
Thanks! I have sent a patch that fixes this, please take a look: https://github.com/swig/swig/pull/1279
