### ISSUE TITLE
Segmentation fault related to interface_impl and using declaration in class definition

### ISSUE THREAD

**Issue by murraypaul** [swig/swig#1276]
```
%module TestMultiple

%include <swiginterface.i>
%interface_impl(Class1);

class Class1
{
	virtual void Add( int );
};

class Combined : public Class1
{
	virtual void Add( double );
	using Class1::Add;
};
```
Swig-3.0.12 crashes on this file when run as either
`swig.exe -c++ -csharp test.i`
or
`swig.exe -c++ -java test.i`

It does not crash if the last class definition is replaced with
```
class Combined : public Class1
{
	virtual void Add( double );
	virtual void Add( int i ) { return Class1::Add(i); };
};
```
It does not crash if the interface_impl line is commented out.
So it seems to be the combination of interface_impl and using that causes the problem.
(The original example had Combined deriving from a second class as well, but that is not required to reproduce the problem.)

**Comment by ojwb** [comment]
There's no crash with SWIG 4.0.2 (I tested both C# and Java) so it seems this was fixed in the meantime.
