### ISSUE TITLE
Minor Release with commit e66d8125a...?

### ISSUE THREAD

**Issue by farao** [swig/swig#1284]
Hi,

I'm working on a project that uses lua files generated by swig. I stumbled upon a warning that is fixed in this commit: https://github.com/swig/swig/commit/e66d8125aae043fc9a3b145116339ea5066ebf4c - unfortunately this is not part of the latest swig release and I shall not use a non-released version. I wanted to ask if there's the possibility to make another minor release using bug/warning fixes like this one or - if that's too much effort - if there's a rough estimation when the next release will be ready?

Thanks a lot for your work!

**Comment by wsfulton** [comment]
The next release is swig-4.0.0. No promises as to when it will be as we are short of developers contributing to the release. It'll be in a couple of months time or later
