### ISSUE TITLE
No module named _pyfreeling

### ISSUE THREAD

**Issue by geraore** [swig/swig#1289]
I installed freeling in Centos 7 with Python2.7 API. Everything went well with the installation procedure. I compiled the library as well the API without any problem, to finally copy everything in the right place However, when I import the pyfreeling library, got the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyfreeling.py", line 26, in <module>
    _pyfreeling = swig_import_helper()
  File "pyfreeling.py", line 18, in swig_import_helper
    import _pyfreeling
ImportError: No module named _pyfreeling

I tried to find the _pyfreeling file on the computer. However, there is no track of the existence of it.
Thanks for your help.

**Comment by wsfulton** [comment]
Please contact the owners of freeling and/or CentOS for this issue. I suspect there is an installation problem with your setup as your PYTHONPATH may need setting to find the missing module.

**Comment by LEXHERRE** [comment]
@geraore did you manage to solve it? I'm having the exact same issue here.
