### ISSUE TITLE
[C#] csout typemap not applied in the member variable getter

### ISSUE THREAD

**Issue by rokups** [swig/swig#1291]
# Short description

CSharp wrapper generator does not apply custom typemap to class member variable getter while typemap is applied to the setter. Typemap should be applied to both getter and setter. csout typemap is applied to the method that returns mapped type.

```
~ % swig -version

SWIG Version 3.0.12

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre
```

# The way it works now

Foo.cs has following code generated for `type_` variable:
```cs
  public global::StringHash type_ {
    set {
      BugReportPINVOKE.Foo_type__set(swigCPtr, value.Hash);
    } 
    get {
      SWIGTYPE_p_StringHash ret = new SWIGTYPE_p_StringHash(BugReportPINVOKE.Foo_type__get(swigCPtr), true);
      return ret;
    } 
  }
```
Setter has typemap applied while getter does not. This triggers generation of `SWIGTYPE_p_StringHash` type even though type is supposed to be typemapped.

# The way it is supposed to work

Foo.cs should have following (or very similar) code for `type_` variable handling:

```cs
  public global::StringHash type_ {
    set {
      BugReportPINVOKE.Foo_type__set(swigCPtr, value.Hash);
    } 
    get {
      //csout
      var ret = new new StringHash(BugReportPINVOKE.Foo_type__get(swigCPtr));
      return ret;
    } 
  }
```

# Testcase

bug.hpp:
```cpp
class Foo
{
public:
    StringHash type_;
    StringHash GetHash();
};
```

bug.i:
```
%module BugReport

%{
#include <bug.hpp>
%}

// StringHash
%typemap(ctype)  StringHash "unsigned"                      // c layer type
%typemap(imtype) StringHash "uint"                          // pinvoke type
%typemap(cstype) StringHash "global::StringHash"            // c# type
%typemap(in)     StringHash %{ $1 = StringHash($input); %}  // c to cpp
%typemap(out)    StringHash %{ $result = $1.Value(); %}     // cpp to c
%typemap(csin)   StringHash "$csinput.Hash"                 // convert C# to pinvoke
%typemap(csout, excode=SWIGEXCODE) StringHash {             // convert pinvoke to C#
    //csout
    var ret = new StringHash($imcall);$excode
    return ret;
  }
%typemap(csdirectorin) StringHash "$iminput /*csdirectorin*/"
%typemap(csdirectorout) StringHash "$cscall /*csdirectorout*/"

%include "bug.hpp"
```

Invocation command: `swig -csharp -c++ bug.i`

**Comment by wsfulton** [comment]
The 'csvarin' typemap is what you are looking for. It is mentioned in the C# docs at http://www.swig.org/Doc3.0/CSharp.html. Note that the typemap's type is a pointer to StringHash. The following example in the docs covers all this: [A date example demonstrating marshalling of C# properties](http://www.swig.org/Doc3.0/CSharp.html#CSharp_date_properties).

```swig
%typemap(csvarout, excode=SWIGEXCODE2) StringHash * %{
    //csvarout StringHash *
    get {
      var ret = new StringHash($imcall);$excode
      return ret;
    } %}
```

P.S. SWIG needs to parse the C definition of StringHash or at least `struct StringHash;` at the minimum. Your bug.hpp file needs adjusting accordingly.

Also if anyone is writing typemaps and wondering why they aren't being used, please read about the `-debug-tmused` command-line option.

**Comment by rokups** [comment]
Hey thank you for reply and sorry for the noise. Swig documentation is amazingly through. This being complex topic i failed to figure this out.

For next poor soul tackling this issue i created a updated/commented interface file detailing changes needed to fix this:

```
%module BugReport

%{
#include <bug.hpp>
%}

// 1. When type is not wrapped by swig (is implemented manually in C# for example) make it known to swig
struct StringHash;

// StringHash
%typemap(ctype)  StringHash "unsigned"                      // c layer type
%typemap(imtype) StringHash "uint"                          // pinvoke type
%typemap(cstype) StringHash "global::StringHash"            // c# type
%typemap(in)     StringHash %{ $1 = StringHash($input); %}  // c to cpp
%typemap(out)    StringHash %{ $result = $1.Value(); %}     // cpp to c
%typemap(csin)   StringHash "$csinput.Hash"                 // convert C# to pinvoke
%typemap(csout, excode=SWIGEXCODE) StringHash {             // convert pinvoke to C#
    //csout
    var ret = new StringHash($imcall);$excode
    return ret;
  }
%typemap(csdirectorin) StringHash "$iminput /*csdirectorin*/"
%typemap(csdirectorout) StringHash "$cscall /*csdirectorout*/"

// 2. Use correct typemaps. Note that class fields are marshalled as pointer types even though they are declared as values.
%typemap(csvarin, excode=SWIGEXCODE2) StringHash * %{
    set {
      $imcall;$excode
    }
%}
%typemap(csvarout, excode=SWIGEXCODE2) StringHash * %{
  get {
    var ret = new StringHash($imcall);$excode
    return ret;
  }
%}

// 3. Make sure StringHash* type has all required typemaps (ctype/imtype/cstype/in/out/csin/csout)
%apply StringHash { StringHash* }

%include "bug.hpp"
```

**Comment by dong2gua** [comment]
Thanks! that's very helpful. I found it's so obscure to understand all these paramters of the typemap method. 

> Hey thank you for reply and sorry for the noise. Swig documentation is amazingly through. This being complex topic i failed to figure this out.
> 
> For next poor soul tackling this issue i created a updated/commented interface file detailing changes needed to fix this:
> 
> ```
> %module BugReport
> 
> %{
> #include <bug.hpp>
> %}
> 
> // 1. When type is not wrapped by swig (is implemented manually in C# for example) make it known to swig
> struct StringHash;
> 
> // StringHash
> %typemap(ctype)  StringHash "unsigned"                      // c layer type
> %typemap(imtype) StringHash "uint"                          // pinvoke type
> %typemap(cstype) StringHash "global::StringHash"            // c# type
> %typemap(in)     StringHash %{ $1 = StringHash($input); %}  // c to cpp
> %typemap(out)    StringHash %{ $result = $1.Value(); %}     // cpp to c
> %typemap(csin)   StringHash "$csinput.Hash"                 // convert C# to pinvoke
> %typemap(csout, excode=SWIGEXCODE) StringHash {             // convert pinvoke to C#
>     //csout
>     var ret = new StringHash($imcall);$excode
>     return ret;
>   }
> %typemap(csdirectorin) StringHash "$iminput /*csdirectorin*/"
> %typemap(csdirectorout) StringHash "$cscall /*csdirectorout*/"
> 
> // 2. Use correct typemaps. Note that class fields are marshalled as pointer types even though they are declared as values.
> %typemap(csvarin, excode=SWIGEXCODE2) StringHash * %{
>     set {
>       $imcall;$excode
>     }
> %}
> %typemap(csvarout, excode=SWIGEXCODE2) StringHash * %{
>   get {
>     var ret = new StringHash($imcall);$excode
>     return ret;
>   }
> %}
> 
> // 3. Make sure StringHash* type has all required typemaps (ctype/imtype/cstype/in/out/csin/csout)
> %apply StringHash { StringHash* }
> 
> %include "bug.hpp"
> ```
