### ISSUE TITLE
TypeError when calling a method in python

### ISSUE THREAD

**Issue by okkhoy** [swig/swig#1292]
I am following the documentation here: http://www.swig.org/Doc3.0/Library.html#Library_stl_cpp_library to write a wrapper to a simple example code involving vectors.

When using the method in Python I get the following error:

`TypeError: in method 'new_Word', argument 3 of type 'std::vector< double,std::allocator< double > > &'`

Here is the header file:

    ### word.h ###
    #include<string>
    #include<vector>
    
    class Word{
    public:
        Word(std::string word, int numWords, std::vector<double> &values);
        ~Word();
    
        void updateWord(std::string newWord);
        std::string getWord();
        void processValues();
    
    private:
        std::string theWord;
        int totalWords;
        std::vector<double> values;
    };

And the source file:

    ### word.cpp ###
    #include "word.h"
    #include <cfloat>
    #include <cmath>
    #include <cstdlib>
    #include <iostream>
    #include <fstream>
    #include <time.h>
    
    Word::Word(std::string word, int numWords, std::vector<double> &values) :
        theWord(word), totalWords(numWords), values(values){
        // TODO: constructor
    }
    
    Word::~Word() {
        // TODO: destructor
    }
    
    void Word::updateWord(std::string newWord) {
        this->theWord = newWord;
    }
    
    std::string Word::getWord() {
        return this->theWord;
    }
    
    void Word::processValues() {
        values.resize(totalWords);
        // do something with values here
    }
    
    /*  
        rest of the code that uses the other includes
    */

Here is the interface file:

    ### word.i ###
    %module word
    %{
    #include "word.h"
    %}
    
    %include "std_string.i"
    %include "std_vector.i"
    
    namespace std {
        %template(vectord) vector<double>;
    }
    
    %include "word.h"

My compilation steps are as follows:

    swig -c++ -python word.i
    g++ -c -fpic word.cpp word_wrap.cxx -I/usr/include/python2.7
    g++ -shared word.o word_wrap.o -o _word.so -lstdc++

The compilation goes through without any errors or warnings. However, on trying to create the object in Python I get the following error:

    In [1]: import word
    
    In [2]: w = word.Word('test', 10, [10.2])
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-2-ee2e5c406fd9> in <module>()
    ----> 1 w = word.Word('test', 10, [10.2])
    
    /home/anarayan/workspace/swig-learn/word.pyc in __init__(self, word, numWords, values)
        276 
        277     def __init__(self, word, numWords, values):
    --> 278         this = _word.new_Word(word, numWords, values)
        279         try:
        280             self.this.append(this)
    
    TypeError: in method 'new_Word', argument 3 of type 'std::vector< double,std::allocator< double > > &'

A bit of searching online leads me to believe that using the template in the SWIG definition solves this problem.  (My interface file reflects the use of the template).

However, in my case it hasn't. Could you please point me in the right direction?

**Comment by okkhoy** [comment]
At the first look the problem looks like #1198 , however it isn't.
I don't have any conflicting module names.

**Comment by okkhoy** [comment]
Update: I get the same error when I try to wrap and use the `halve_in_place` method in the [example](https://github.com/swig/swig/blob/master/Examples/python/std_vector/example.h):


```
example.halve_in_place([10.10, 20.20, 30.30])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-8e8cb45ea5e4> in <module>()
----> 1 example.halve_in_place([10.10, 20.20, 30.30])

TypeError: in method 'halve_in_place', argument 1 of type 'std::vector< double,std::allocator< double > > &'
```


Now my question is, "was it always *not* supposed to work?"
If not, how to get it to work?

**Comment by wsfulton** [comment]
Looks okay to me. Note the difference in behaviour between `const std::vector<double>&` and `std::vector<double>&`. This is in the documentation link you gave. In your case you need to change your script to use:
```python
word.Word('test', 10, word.vectord([10.2, 5.2])))
```
If you want to keep your script as it is, then add this before including the STL .i files:
```swig
%extend std::vector< double > {
  %apply std::vector< double > const & {std::vector< double > & }
}
```
But if the constructor modifies the non-const std::vector, the values will not be reflected back into the Python list. That's because the typemaps don't support this behaviour for Python lists. However, if you use:
```python
vd = word.vectord([10.2, 5.2])
word.Word('test', 10, vd)
```
Then vd, will contain the modified vector.
If your constructor really should be taking a non-const vector, then modify it to do so!

Another way to understand this default behaviour is to think and write it in equivalent C++:
```c++
  Word w("test", 10, {10.2, 5.2});
```
which is invalid for the reasons given by the compiler...
```
example.cxx: In function ‘void tester()’:
example.cxx:37:33: error: invalid initialization of non-const reference of type ‘std::vector<double>&’ from an rvalue of type ‘std::vector<double>’
   Word w("test", 10, {10.2, 5.2});
                                 ^
In file included from /usr/include/c++/5/vector:64:0,
                 from word.h:2,
                 from example.cxx:1:
/usr/include/c++/5/bits/stl_vector.h:373:7: note:   after user-defined conversion: std::vector<_Tp, _Alloc>::vector(std::initializer_list<_Tp>, const allocator_type&) [with _Tp = double; _Alloc = std::allocator<double>; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<double>]
       vector(initializer_list<value_type> __l,
       ^
example.cxx:9:1: note:   initializing argument 3 of ‘Word::Word(std::__cxx11::string, int, std::vector<double>&)’
 Word::Word(std::string word, int numWords, std::vector<double> &values) :
 ^
```
But this is valid:
```c++
  std::vector<double> vd{10.2, 5.2};
  Word w("test", 10, vd);
```
