### ISSUE TITLE
Python type error inconsistencies

### ISSUE THREAD

**Issue by wsfulton** [swig/swig#1293]
When a wrong type is passed to a SWIG wrapped function a TypeError is thrown for example:
```
TypeError: in method 'f', argument 1 of type 'char const *'
```
However, when a wrong type is passed to a SWIG wrapped function that is overloaded a NotImplementedError is thrown for example, when wrapping:
```c++
const char * f(int i);
const char * f(const char *s);
```
The error is:
```
NotImplementedError: Wrong number or type of arguments for overloaded function 'f'.
  Possible C/C++ prototypes are:
    f(int)
    f(char const *)
```
The Python documentation on [TypeError](https://docs.python.org/3/library/exceptions.html#TypeError), says 
> if an object is meant to support a given operation but has not yet provided an implementation, NotImplementedError is the proper exception to raise.

I don't know why SWIG raises NotImplementedError, implying that the function is not fully implemented. This seems inconsistent raising different exceptions whether or not the function is overloaded and I propose changing it to TypeError.

Secondly, when wrapping an overloaded function and when using the -fastdispatch option, which is also turned on by -O, a TypeError is raised instead of a NotImplementedError if the type passed in is wrong. The error message displayed is also different compared to not using -fastdispatch. The error message when calling the above wrapped C++ code is always:
```
TypeError: in method 'f', argument 1 of type 'char const *'
```
It doesn't show all the possible C/C++ prototypes and only ever shows the `char const *` possibility.

This problem is highlighted by the `li_std_string_extra` testcase when running the Python test-suite with -O. 

As the plan is to turn on -fastdispatch by default in SWIG-4.0, now is the time to address these inconsistencies. I propose we change -fastdispatch to show the same error message as when not using -fastdispatch, but change the type of the error from NotImplementedError to TypeError.

**Comment by vadz** [comment]
As you've asked for comments in #1261, let me comment, even though it's not going to be very useful because I basically agree with everything you wrote, i.e. I don't see any sensible reason to use `NotImplementedError` instead of `TypeError` here and, of course, the errors should be identical with and without fast dispatch.

**Comment by wsfulton** [comment]
In the end I didn't make the error messages identical in both fastdispatch mode and the current default nofastdispatch mode. In nofastdispatch mode, the 'Possible C/C++ prototypes ...' message has always been displayed without any other error message. Now, in fastdispatch mode, the 'Possible C/C++ prototypes...' message is displayed and sometimes an additional message.

The reason for this is, by the very nature of the fastdispatch design, the typecheck typemap is sometimes optimised out and the code therein is not called and instead the overloaded function is called directly skipping out the type checking. If the types are wrong, the overloaded function will create a TypeError. So now, whenever a TypeError is thrown, the message in the TypeError exception is modified to include the 'Possible C/C++' prototypes message. I didn't replace the TypeError message altogether (like in nofastdispatch mode) because sometimes a TypeError contains a very useful error message that is not due to type marshalling that the typecheck typemap would have found. In fact I keep the original stack trace from the TypeError because it can contain useful file/line information too, compared to throwing a new TypeError. The director_exception testcase shows one such example where an overloaded function calls a director function which throws a TypeError.

The generated code for the example earlier optimised out the type check code for 'char const *' and used to be simply:


```c++
  ...
  if (argc == 1) {
    return _wrap_f__SWIG_1(self, args);
  }
fail:
  SWIG_SetErrorMsg(PyExc_NotImplementedError,"Wrong number or type of arguments for overloaded function 'f'.\n"
    "  Possible C/C++ prototypes are:\n"
    "    f(int)\n"
    "    f(char const *)\n");
  return 0;
```
Now it is:
```c++
  ...
  if (argc == 1) {
    PyObject *retobj = _wrap_f__SWIG_1(self, args);
    if (!SWIG_Python_TypeErrorOccurred(retobj)) return retobj;
    goto fail;
  }
fail:
  SWIG_Python_RaiseOrModifyTypeError("Wrong number or type of arguments for overloaded function 'f'.\n"
    "  Possible C/C++ prototypes are:\n"
    "    f(int)\n"
    "    f(char const *)\n");
  return 0;
}
```
So the non-error code path is identical, but now if an exception is thrown, a TypeError is checked for and if one has been thrown, SWIG_Python_RaiseOrModifyTypeError will keep the exception (including stacktrace) and just modify the message by adding in the 'Additional Information', so you now get:
```
Traceback (most recent call last):
  File "runme.py", line 3, in <module>
    example.f(9.9)
TypeError: in method 'f', argument 1 of type 'char const *'
Additional Information:
Wrong number or type of arguments for overloaded function 'f'.
  Possible C/C++ prototypes are:
    f(int)
    f(char const *)
```
An alternative approach could have been to generate the typecheck code and call it after the c++ function is called (instead of before like the nofastdispatch mode):
```c++
  ...
  if (argc == 1) {
    PyObject *retobj = _wrap_f__SWIG_1(self, args);
    if (!SWIG_Python_TypeErrorOccurred(retobj)) return retobj;
    ... save the TypeError exception ...
    ... generated typecheck code: 
        int res = SWIG_AsCharPtrAndSize(argv[0], 0, NULL, 0);
        _v = SWIG_CheckState(res);
    ... restore the TypeError exception ...
    if (_v) {
      // no type marshalling error in typecheck code, keep exception unchanged
      return 0;
    } else {
      goto fail;
    }
  }
fail:
  SWIG_SetErrorMsg(PyExc_NotImplementedError,"Wrong number or type of arguments for overloaded function 'f'.\n"
    "  Possible C/C++ prototypes are:\n"
    "    f(int)\n"
    "    f(char const *)\n");
  return 0;
```
This would be somewhat harder to implement, generate more code, run slower when an exception is thrown, but possibly be a better more consistent approach.
