### ISSUE TITLE
Java director crash when OUTPUT argument is a null pointer

### ISSUE THREAD

**Issue by bryanhatwood** [swig/swig#1303]
(I'm new to swig and not sure if this is a bug or working as intended).

I have a C++ function that takes a pointer to hold an output value:

` void Foo:Bar(int *result) { ... }`

I'm using the director function in swig in order to subclass this in Java. In the director override of this function, there is a block of code 

```
SwigDirector_Foo::Bar(int *result) {
...
    jint result_jvalue;
    jenv->GetIntArrayRegion(jresult, 0, 1, &result_jvalue);
    *result = result_jvalue;
```

However, if I happen to pass a null pointer to a subclass of Foo, I get a crash:

```
// From C++, where f points to a subclass of Foo
f->Bar(0); --> crash, since *result in SwigDirector_Foo::Bar is null
```

I'm working with C++ code that often passes null pointers when the output is not needed.

**Comment by wsfulton** [comment]
I've merged #1304 in 934c4022385d9ff570fc1f0104f67bd4dfb933da. I also made some additional fixes to convert a C++ NULL pointer to a Java null, instead of unnecessarily creating the Java array, and added tests, see 61d9dd40a02b20b54fcd0d9701861cc8bd631e92.
