### ISSUE TITLE
Cannot build Node.js project with std::vector

### ISSUE THREAD

**Issue by mac-wac** [swig/swig#1309]
Hi. I'm grateful that SWIG now supports Node 10!

I could not build Node.js project with std::vector. Here's a minimal example.

test.i:

    %include "std_vector.i"
    namespace std{
        %template(vectori) vector<int>;
    } 
    %module test
    %{
    %}

binding.gyp

    { "targets": [
        { "target_name": "test", "source": ["test_wrap.cxx"] }
    ] }

Then, I executed `node-gyp configure build` and saw these error messages:

    ../test_wrap.cxx: In function ‘const value_type& std_vector_Sl_int_Sg__get(std::vector<int>*, int)’:
    ../test_wrap.cxx:1768:72: error: exception handling disabled, use -fexceptions to enable
                         throw std::out_of_range("vector index out of range");
                                                                            ^
    ../test_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_vectori_get(const SwigV8Arguments&)’:
    ../test_wrap.cxx:2099:44: error: ‘_e’ was not declared in this scope
         SWIG_exception_fail(SWIG_IndexError, (&_e)->what());
                                                ^
    ../test_wrap.cxx:868:67: note: in definition of macro ‘SWIG_Error’
     #define SWIG_Error(code, msg)     SWIGV8_ErrorHandler.error(code, msg)
                                                                       ^~~
    ../test_wrap.cxx:2099:5: note: in expansion of macro ‘SWIG_exception_fail’
         SWIG_exception_fail(SWIG_IndexError, (&_e)->what());
         ^~~~~~~~~~~~~~~~~~~
    ../test_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_vectori_set(const SwigV8Arguments&)’:
    ../test_wrap.cxx:2149:44: error: ‘_e’ was not declared in this scope
         SWIG_exception_fail(SWIG_IndexError, (&_e)->what());
                                                ^
FYI, `g++ -c test_wrap.cxx` succeeded with no error.

My environment:

- Ubuntu 18.04
- SWIG https://github.com/swig/swig/commit/fdd2bcf0e6a07093fc541b145e0dfe9fb00254f0
- g++ 7.3.0
- node 10.8.0
- node-gyp 3.8.0

Thank you.

**Comment by wsfulton** [comment]
The wrappers require exception support as std::vector may throw an exception or the wrapper checks may throw. You'll need to use the `-fno-exceptions` flag for wrapping STL containers unless you remove the STL methods that throw exceptions. Use %ignore to ignore the appropriate methods.
