### ISSUE TITLE
Running into a non-descriptive error: "Syntax error in input(1)" 

### ISSUE THREAD

**Issue by Akshay-Venkatesh** [swig/swig#1313]
Hi,

I'm very new to using swig and I'm trying to generate python bindings for an existing open-source communication library written in C (https://github.com/openucx/ucx)

My attempt is based on a fairly old openGL example I see here (http://www.swig.org/papers/PyTutorial98/PyTutorial98.pdf)

UCX is based around three components ucm, ucp, and uct. APIs are exposed in respective headers. I see the following problem when I try swig:
```
$ cat ucm.i
%{
#include "ucm/api/ucm.h"
%}

%include "ucm/api/ucm.h"

$ cat ucp.i
%{
#include "ucp/api/ucp.h"
%}

%include "ucp/api/ucp.h"

$ cat uct.i
%{
#include "uct/api/uct.h"
%}

%include "uct/api/uct.h"

$ cat ucx.i
%module ucx
%include ucm.i
%include ucp.i
%include uct.i

$ swig -python ucx.i 
ucm/api/ucm.h:27: Error: Syntax error in input(1).
```

Yet I don't see obvious problems at the 27th line: https://github.com/openucx/ucx/blob/master/src/ucm/api/ucm.h#L27
```
...
#include <sys/types.h>
#include <stddef.h>
#include <stdio.h>
#include <stdint.h>


/**
 * @brief Memory event types
 */
```
```
typedef enum ucm_event_type {
```
```
    /* Native events */
    UCM_EVENT_MMAP            = UCS_BIT(0),
    UCM_EVENT_MUNMAP          = UCS_BIT(1),
...
```

I'm using the following swig version:
```
$ swig -version

SWIG Version 3.0.12
...
```

Appreciate any help I can get with the problem.

**Comment by wsfulton** [comment]
Run using `swig -E` to view the preprocessed output. Probably `UCS_BIT` is expanding into something wrong because you havn't got SWIG to parse whatever `UCS_BIT` is meant to do. Compare by looking at the preprocessed output from your C compiler.

**Comment by devshgraphicsprogramming** [comment]
It still doesn't work for template classes with SWIG 4.0.2
```cpp
class Base
{
};


template<class T>
class Derived final : public Base
{
};
```

if you don't remove the `final` it will complain ` Error: Syntax error in input(1).`
