### ISSUE TITLE
How to cross compile for openwrt in ubuntu 14.04.5 LTS?

### ISSUE THREAD

**Issue by Grassboy** [swig/swig#1320]
I'm trying to build a swig package for openwrt...
so I downloaded the source in ubuntu and tried to cross-compile swig for openwrt
My env variable is as below:

`export STAGING_DIR=/home/grassboy/crosscompiler/openwrt/staging_dir`
`export TOOLCHAIN_DIR=$STAGING_DIR/target-mipsel_24kec+dsp_uClibc-0.9.33.2`
`export LDCFLAGS=$TOOLCHAIN_DIR/usr/lib`
`export LD_LIBRARY_PATH=$TOOLCHAIN_DIR/usr/lib`
`export PATH=$TOOLCHAIN_DIR/bin:$PATH`

Does anyone can give me some advise to do that?

**Comment by wsfulton** [comment]
You probably don't want to cross-compile SWIG to run on an embedded device. Just run SWIG on your host computer and then cross-compile the generated C code.
