### ISSUE TITLE
SWIG has issues with "chained" preprocessor definitions?

### ISSUE THREAD

**Issue by StakFallT** [swig/swig#1325]
I'm working on a hobby project (I'll spare the details unless people are curious) and I'm using GNURadio which the source straight from their repo makes use of SWIG. So I know the two are supposed to be used together. However, upon trying to run swig against one of the modules GNURadio uses, I get the error:

"**Error: Syntax error in input(1).**"

in my particular case, SWIG was calling out **block_gateway.h**

Here is my environment:

- Manjaro
- Linux <hostname-redacted> 4.9.117-1-MANJARO #1 SMP PREEMPT Fri Aug 3 12:29:48 UTC 2018 x86_64 GNU/Linux

"**_gcc -version_**" output:

> g++ (GCC) 8.1.1 20180531
> Copyright (C) 2018 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

"**_swig -version_**" output:

> [<redacted swig>]$ swig -version
> 
> SWIG Version 3.0.12
> 
> Compiled with g++ [x86_64-pc-linux-gnu]
> 
> Configured options: +pcre
> 
> Please see http://www.swig.org for reporting bugs and further information
> [<redacted swig>]$

gnuradio (source) version 3.7.9

swig command:

> [<redacted> swig]$ **_swig -csharp -c++ -I/usr/include -I/home/<redacted>/ownCloud/CyberSec_Utils/gnuradio-3.7.9/gnuradio-runtime/include -I/home/<redacted>/ownCloud/CyberSec_Utils/gnuradio-3.7.9/gr-blocks/include -I/home/<redacted>/ownCloud/CyberSec_Utils/gnuradio-3.7.9 -l/home/<redacted>/ownCloud/CyberSec_Utils/gnuradio-3.7.9/gnuradio-runtime/swig -l/home/<redacted>/ownCloud/CyberSec_Utils/gnuradio/build/gr-blocks/swig /home/<redacted>/ownCloud/CyberSec_Utils/gnuradio-3.7.9/gr-blocks/swig/blocks_swig0.i_**

my pwd:
/home/<redacted>/ownCloud/CyberSec_Utils/gnuradio-3.7.9/gnuradio-runtime/swig

and yes I'm aware of the -l argument 
> /home/<redacted>/ownCloud/CyberSec_Utils/gnuradio

where all the other directories specify a prefix of:
> /usr/include -I/home/<redacted>/ownCloud/CyberSec_Utils/gnuradio-3.7.9/

I'm pretty sure that's fine. Only reason I'm including the one that's different is because **blocks_swig*_doc.i** don't seem to be in the corresponding **gnuradio-3.7.9/build/gr-blocks/swig** directory. All of this is fine I think because I can get the project to actually compile and part of the compile process uses SWIG **HEAVILY** for Python wrappers. So I'm pretty sure this isn't the issue.

During my investigating a little, I started playing around with the line that SWIG was calling out (block_gateway.h:92) a small snippet from that file is as such:

```C++
  /*!
   * The gateway block which performs all the magic.
   *
   * The gateway provides access to all the gr::block routines.
   * The methods prefixed with gr::block__ are renamed
   * to class methods without the prefix in python.
   */
  class GR_RUNTIME_API block_gateway : virtual public gr::block
  {
  public:
    // gr::block_gateway::sptr
    typedef boost::shared_ptr<block_gateway> sptr;

    /*!
     * Make a new gateway block.
     * \param handler the swig director object with callback
     * \param name the name of the block (Ex: "Shirley")
     * \param in_sig the input signature for this block
     * \param out_sig the output signature for this block
     * \param work_type the type of block overload to implement
     * \param factor the decimation or interpolation factor
     * \return a new gateway block
     */
    static sptr make(gr::feval_ll *handler,
                     const std::string &name,
                     gr::io_signature::sptr in_sig,
                     gr::io_signature::sptr out_sig,
                     const block_gw_work_type work_type,
                     const unsigned factor);

    //! Provide access to the shared message object
    virtual block_gw_message_type &block_message(void) = 0;

    long block__unique_id(void) const {
      return gr::block::unique_id();
    }

    ...
```

Line 92 is the class definition header line:
"**class GR_RUNTIME_API block_gateway : virtual public gr::block**"

at first, I thought it might have been complaining because the namespace gr was being used to fully qualify block's scope-location since this entire file is already part of the gr namespace (though I doubted SWIG to be having an issue with this since specifying the namespace would just be overkill, not necessarily something that should cause an error). However, I took out gr:: anyway, and still received the error. Then I began looking at GR_RUNTIME_API. I eventually found that GR_RUNTIME_API is defined in **gnuradio-runtime/include/gnuradio/api.h** as __GR_ATTR_IMPORT and then __GR_ATTR_IMPORT is defined in **gnuradio/attributes.h**. I think the relevant block here is the block in **gnuradio/attributes.h**:

```C++
 #  if __GNUC__ >= 4
 #    define __GR_ATTR_EXPORT   __attribute__((visibility("default")))
 #    define __GR_ATTR_IMPORT   __attribute__((visibility("default")))
 #  else
 #    define __GR_ATTR_EXPORT
 #    define __GR_ATTR_IMPORT
 #  endif
```

so essentially if the version of GNUC is older than version 4 it defines __GR_ATTR_IMPORT as nothing (not NULL since technically null would be 0x00). However, my gcc version is 8+ so I don't think it's being defined as nothing, then again I'm just running SWIG, not running GCC, so I don't know if SWIG really bothers parsing #if / #else conditionals making the identifier __GR_ATTR_IMPORT  non-existant. Either way, I feel like if it's an issue with a preprocessor macro identifier, shouldn't SWIG be a little bit more specific about the problem (i.e. a C-like error:
identifier '__GR_ATTR_IMPORT' undefined)?

If I take out the GR_RUNTIME_API text in the class definition header-line, SWIG no longer reports it has an issue with that file.

Edits: A fair portion of time and edits were due to attempting to make the post as readable as possible since it's somewhat long.

**Comment by wsfulton** [comment]
`class GR_RUNTIME_API block_gateway` is not ISO C++. SWIG requires standard C++ to work, so a syntax error is not surprising. If you add a macro like this for SWIG to parse:
```
#define GR_RUNTIME_API
```
you can make it non-proprietary C++.

**Comment by StakFallT** [comment]
Hmm.. ok didn't realize that about SWIG (with regards to requiring standard C++). However, the solution you suggessted, doesn't that basically just make GR_RUNTIME_API no longer equal anything (not necessarily undef'ed but just not defined as anything) -- effectively taking the statement "class GR_RUNTIME_API block_gateway" and turning it into "class block_gateway"? Currently, if I visually trace the code across the files correctly, it is basically:

GR_RUNTIME_API -> __GR_ATTR_IMPORT -> __attribute__((visibility("default")))

As such, I believe GR_RUNTIME_API is being defined as just: __attribute__((visibility("default")))
making the effective statement:

class __attribute__((visibility("default"))) block_gateway

so I'm not sure setting GR_RUNTIME_API to just nothing wouldn't cause any issues...

**Comment by wsfulton** [comment]
Yes, `GR_RUNTIME_API` becomes nothing to make the class declaration standards compliant. The gnu extension `__attribute__` is concerned with linking and is platform dependent. With regards to SWIG and 'visibility', SWIG will wrap whatever classes it parses that are not explicitly ignored. If you mistakenly wrap a class that does not have external 'visibility' you are likely to get a link error. Use %ignore in that case.
