### ISSUE TITLE
Swig R module refactoring project

### ISSUE THREAD

**Issue by richardbeare** [swig/swig#1329]
Hi @joequant , @wsfulton ,

I'm wrapping up the funded part of my refactoring project. The bulk of the work is captured by two PRs: #1328 and #1268.

I expect to continue to contribute as many of the recent developments are changing the SimpleITK R project.

Please let me know how to best push these changes through. Some suggestions earlier included helping Joseph with maintenance of the R module.

**Comment by richardbeare** [comment]
Hi Guys,
Anything happening on this? Should I be volunteering to step into a more major role in maintaining the R module?

**Comment by wsfulton** [comment]
@joequant, as the current R maintainer can you either review these patches or are you okay if @richardbeare takes over in some sort of way as the R maintainer?

**Comment by wsfulton** [comment]
As @joequant isn't responding, I'll try and help review your patches with a view to you leading the R module development going forwards. I see you have 7 patches open at the moment https://github.com/swig/swig/issues?utf8=%E2%9C%93&q=is%3Aopen+author%3Arichardbeare+ . Could you please close the out of date / duplicate patches and then let me know which are ready for a review? Please cross reference relevant patches too, such as referencing a first attempt if one patch has superceded another.

**Comment by richardbeare** [comment]
@wsfulton : I've closed all redundant PRs with comments. The two important ones are #1268 and #1328.

**Comment by wsfulton** [comment]
Hi @richardbeare. Your changes in #1511 have been merged in. I'm sorry it has taken so long to get this work into master, but if you have any other improvements to R, please raise as separate bite size patches and please do include lots of tests and explanations as it will then be much quicker and easier for me to merge them in, given my minimal knowledge of R.
