### ISSUE TITLE
Add Support for Node.js Versions >= v10.12.0 

### ISSUE THREAD

**Issue by ghost** [swig/swig#1337]
Node.js version 10.12.0 depreciated several of the C++ interfaces (https://github.com/nodejs/node/pull/23159), and it looks like this breaks the wrappers generated by SWIG.

**Comment by wsfulton** [comment]
This also showed up in our CI testing on Travis. I've stopped Javascript from failing the builds in fe155d75167cbfa67082b7554acf56d134ad64dc until someone provides a patch to fix.

**Comment by wsfulton** [comment]
Fixed by #1500.
