### ISSUE TITLE
Go Wrapping should not prepend a Get to a variable getter.

### ISSUE THREAD

**Issue by fire** [swig/swig#134]
From their style guide: http://golang.org/doc/effective_go.html#Getters

> Go doesn't provide automatic support for getters and setters. There's nothing wrong with providing getters and setters yourself, and it's often appropriate to do so, but it's neither idiomatic nor necessary to put Get into the getter's name. If you have a field called owner (lower case, unexported), the getter method should be called Owner (upper case, exported), not GetOwner. The use of upper-case names for export provides the hook to discriminate the field from the method. A setter function, if needed, will ikely be called SetOwner. Both names read well in practice:

**Comment by ojwb** [comment]
@ianlancetaylor rejected this change in PR #261, so closing.
