### ISSUE TITLE
Customized class in inheritance

### ISSUE THREAD

**Issue by allanj** [swig/swig#1341]
I am trying out a python wrapper with the SWIG-3.0, But an problem about inherit was met.
May I ask is it possible to define a class which inherit a class defined in C++ code,
then pass the python class into c++ functions, and obtain a return result as the type of the orignal python class?
the process is shown as below file:
in the `t_inherit.h` file:
```python
class Input{
public:
    int vx = 111;
};
class Base{
public:
    Base(Input *i);
    ~Base();
    Input *xx;
    Input *GetInput();
};
```
in the `t_inherit.cpp` files:
```c++
#include "t_inherit.h"
Base::Base(Input *i) {
    xx = i;
}
Input *Base::GetInput() {
    return xx;
}
Base::~Base() {
}
```
and in the `tinherit.i` files:
```
%module tinherit
%{
#include "t_inherit.h"
%}
%include "t_inherit.h"
```
At last in the `test.py` files:
```python
import tinherit as st
class ic(st.Input):
    def __init__(self,labels):
        st.Input.__init__(self)
        self.labels = labels
if __name__ == "__main__":
    seq = ic([1, 2])
    inst = st.Base(seq)
    input_st = inst.GetInput()
    print(type(input_st))
    input_st.__class_ = ic
    print(input_st.labels)
```
And the result will be:
```
<class 'tinherit.Input'>
<class '__main__.ic'>
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    print(input_st.labels)
  File "/Users/shike/CLionProjects/test_inherit/tinherit.py", line 102, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Input, name)
  File "/Users/shike/CLionProjects/test_inherit/tinherit.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Input' object has no attribute 'labels'
```
it shows that, after we pass the class into the c++ funtion, it loss the component `lables`,
even if I transfer it into ic class, the labels can not be obtain either.
May I ask, is there any approch to realize this function?

**Comment by wsfulton** [comment]
The `director` feature should be used for inheriting from C++ classes. There is plenty of info in the docs and examples in the Examples/python/extend and Examples/python/callback directories.
