### ISSUE TITLE
Swig calls wrong constructor with enum overload

### ISSUE THREAD

**Issue by adamfowleruk** [swig/swig#1345]
If there are two constructors with the same number of parameters, where in one a parameter is an int and the other overloaded constructor takes an enum whose value is an int, then swig incorrectly always calls the enum typed version. 

I've customised the python enum test to include this scenario, and that will be the subject of a PR in a moment. This test has a class (Boo) with an overloaded constructor. One call takes an enum whose element values are ints. The other constructor takes an int.

A C++ test in this class correctly shows that passing an enum type in or int type in both call the correct constructor. My modifications to the RunMe.py example carries out the same calls on the python class generated by SWIG. This shows that the enum typed constructor is always called whether you pass an int or the enum type.

I believe there are two bugs here:-
1. The enum value in python generated by swig is a simple int with no reference to an enum class, causing it to be treated as an int in the call (This contradicts the documentation), rather than an enum value type
2. Given a simple int value, Swig's generated python should call the int variant of the constructor, not the enum typed variant

I have tested this against the latest published release, and the master branch in GitHub, with the same results.

The real world header that shows up this issue is in the Haiku OS here:
https://github.com/haiku/haiku/blob/master/headers/os/interface/Window.h#L27

The enum type is window_type on line 27.

**Comment by adamfowleruk** [comment]
PR showing test case is #1346

**Comment by wsfulton** [comment]
Closing as working as expected.
