### ISSUE TITLE
Building Enet lib to java problem

### ISSUE THREAD

**Issue by DrOreo002** [swig/swig#1348]
Umm, I'm to lazy to write it down here again. So yeah you can see the problem by yourself here
https://stackoverflow.com/questions/53347698/building-enet-swig-wrap-with-g-shows-this-weird-error

Don't worry its not some kind of 'trash question' I've included everything to reproduce the problem and the error itself. So if you have some time could you help me here?

Thanks

**Comment by vadz** [comment]
Too lazy to copy-and-paste the text from SO to here? This is impressive.

I'd recommend providing a self-contained (ideally _not_ referencing some external library) example of the problem if you'd like anybody to take it seriously. Otherwise this should be closed IMO.

**Comment by wsfulton** [comment]
You are using g++ to compile C code. You need to use gcc for C code or invoke SWIG with -c++ and then use g++ to compile the wrappers.

**Comment by DrOreo002** [comment]
Eh didn't see on the wiki that I need to use -c++, thanks man I really appreciate it
