### ISSUE TITLE
Typedef matching rules for 'char const' inconsistent

### ISSUE THREAD

**Issue by rolftheunissen** [swig/swig#135]
See the debugging output below, the lookup for 'char const [ANY]' is skipped, among others, in the case that a typedef as defined below is used. (in swig 2.0.9)

typedef char A_string[128 + 8];

Searching for a suitable 'default' typemap for: char const prefix[20+1]
  Looking for: char const prefix[20+1]
  Looking for: char const [20+1]
  Looking for: char const prefix[ANY]
  Looking for: char const [ANY]
  Looking for: char prefix[20+1]
  Looking for: char [20+1]
  Looking for: char prefix[ANY]
  Looking for: char [ANY]
  Looking for: SWIGTYPE const prefix[ANY]
  Looking for: SWIGTYPE const [ANY]
  Looking for: SWIGTYPE prefix[ANY]
  Looking for: SWIGTYPE [ANY]
  Looking for: SWIGTYPE prefix[]
  Looking for: SWIGTYPE []
  Looking for: SWIGTYPE *prefix
  Looking for: SWIGTYPE *
  Looking for: SWIGTYPE prefix
  Looking for: SWIGTYPE
  None found

Searching for a suitable 'default' typemap for: A_string const device_name
  Looking for: A_string const device_name
  Looking for: A_string const
  Looking for: A_string device_name
  Looking for: A_string
  Looking for: char const device_name[128+8]
  Looking for: char const [128+8]
  Looking for: char device_name[128+8]
  Looking for: char [128+8]
  Looking for: char device_name[ANY]
  Looking for: char [ANY]
  Looking for: SWIGTYPE const device_name[ANY]
  Looking for: SWIGTYPE const [ANY]
  Looking for: SWIGTYPE const device_name[]
  Looking for: SWIGTYPE const []
  Looking for: SWIGTYPE *const device_name
  Looking for: SWIGTYPE *const
  Looking for: SWIGTYPE const device_name
  Looking for: SWIGTYPE const
  Looking for: SWIGTYPE device_name
  Looking for: SWIGTYPE
  None found

**Comment by ojwb** [comment]
This was actually fixed in 2.0.10 (released 2013-05-27, before this ticket was even opened).

See ee2b46abe0b747bc949538f51c9e2a989a867da9 for the actual change.
