### ISSUE TITLE
Syntax error in input(3), weird error

### ISSUE THREAD

**Issue by DrOreo002** [swig/swig#1351]
Not sure what caused this but this error happens when I try to build enet on windows os, it was working fine on linux os before.

So, here's my .i module https://pastebin.com/FbFThPsy . And basically the error refers to this line of code https://pastebin.com/XRMN962k , also my swig command is `swig -c++ -java java-enet.i`. It would be great if someone can help me here :D. Thanks

`C:\Users\Oreo\Desktop\JavaEnet>swig -c++ -java java-enet.i`
`enet\callbacks.h(12) : Error: Syntax error in input(3).`

**Comment by wsfulton** [comment]
That line is not standards compliant code. What is ENET_CALLBACK? Please read http://swig.org/Doc3.0/Windows.html#Windows_interface_file.
The mailing lists are the best place to get help - Github issues ought to be used for reporting bugs.
