### ISSUE TITLE
[Question] Symbol lookup error problem

### ISSUE THREAD

**Issue by DrOreo002** [swig/swig#1354]
I'm not sure what caused this..., took me 2 hours of googling but I cannot find how to fix this

`/usr/lib/jvm/java-8-openjdk-amd64/bin/java: symbol lookup error: /home/anom/Desktop/GrowtopiaServer/src/resources/libenet.so: undefined symbol: enet_initialize`

Also here's how I loaded it

`static {
        System.out.println("============== ENet Loader ==============");
        System.out.println("Lib Path : " + System.getProperty("java.library.path"));
        System.load(System.getProperty("java.library.path") + "/libenet.so");
        System.out.println("ENet has been loaded!");
        System.out.println("============== ENet Loader ==============");
    }`

That Lib Path sysout is correct it log the path that is configured inside the vm option. Also
I'm currently using IntelliJ and I have configured the VM option to -Djava.library.path="<path>" but its still not working..

**Comment by DrOreo002** [comment]
Nvm. Fixed it

**Comment by vmc-7645** [comment]
@DrOreo002 Hey, do you still have info on your Enet binding? Trying to get one implemented and would like some info/help if available
