### ISSUE TITLE
Leak of SWIG var link object (C++/python bindings)

### ISSUE THREAD

**Issue by adr26** [swig/swig#1360]
I have noticed that some of our tests were detecting a memory leak on process exit (running on Windows):
 
```Detected memory leaks!
Dumping objects ->
{177} normal block at 0x035A1AD0, 25 bytes long.
Data: <DataBlock_EmptyD> 44 61 74 61 42 6C 6F 63 6B 5F 45 6D 70 74 79 44 
{176} normal block at 0x035A2C98, 16 bytes long.
Data: <  Z p    }      > D0 1A 5A 03 70 C4 00 10 F0 7D 09 10 00 00 00 00 
Object dump complete.
```
 
I traced this down to the reference count of `_SWIG_globals` not returning to `0` when our .pyd was unloaded, and hence `swig_varlink_dealloc()` not running.

**Comment by wsfulton** [comment]
Fixed by #1361
