### ISSUE TITLE
Unable to add docstring to Python property

### ISSUE THREAD

**Issue by barreyra** [swig/swig#1367]
I am using attribute.i to morph my c++ getters/setters into Python properties. Works great, except that `%feature("autodoc")` doesn't let me add a docstring to the property. Example:

```
%feature("autodoc", "Blah blah blah") MyClass::Property;

%attribute(MyClass, int, Property, GetProperty);
```

I've tried `MyClass::GetProperty` as an argument as well, but either way the docstring is always `MyClass.Property`.

**Comment by wsfulton** [comment]
Closing as fixed by #728 which has been committed.
