### ISSUE TITLE
perl5 typemaps do not properly extend the argument stack

### ISSUE THREAD

**Issue by tonycoz** [swig/swig#1374]
Originally reported agains Math::Cephes at https://rt.cpan.org/Ticket/Display.html?id=122912 which uses SWIG.

Here's the typemap for double/float from Lib/perl5/typemaps.i :

```C
 %typemap(argout) float    *OUTPUT, float &OUTPUT,
                  double   *OUTPUT, double &OUTPUT
 {
   if (argvi >= items) {
     EXTEND(sp,1);
   }
   $result = sv_newmortal();
   sv_setnv($result,(double) *($1));
   argvi++;
 }
```

Since this code doesn't modify sp, and EXTEND() extends the stack based on sp, if multiple arguments are processed, this will only extend the stack for the first argument.

This is a problem in all of the calls to EXTEND in Lib/perl5/typemaps.i

The simplest solution is probably to just change the EXTEND(sp, 1) to EXTEND(sp, argvi+1) in each case (but I'm not a SWIG user, let along a SWIG developer.)

Debugging builds (with -DDEBUGGING on the Configure command-line) of perl 5.28.0 or later will throw an exception for code that fails to extend the stack properly

This bug can lead to allocated memory write overflows.

**Comment by wsfulton** [comment]
@tlby one for you please.

**Comment by tlby** [comment]
That makes sense.  There is definitely some cleanup & hardening needed here.  I'll investigate, thanks for the report!

**Comment by tlby** [comment]
A v5.28.x build with `-DDEBUGGING` exposes a handful of other issues too, but clearly shows this `EXTEND()` problem.  I've been able to reproduce and will cook up a patch.  Your suggested fix looks great for an immediate solution.  I'd be happiest with a single `EXTEND()` call at the end of wrap functions, but that change would be more involved.  I'll see if I can cook that up quickly and if not we'll fall back on the more surgical solution.

**Comment by tonycoz** [comment]
A single EXTEND() would need to be at the beginning, otherwise you might be writing beyond the end of the buffer before EXTEND() reallocates it.

That said, EXTEND() is fairly cheap unless it needs to reallocate the buffer. The main win in combining several EXTEND() calls is smaller generated code.

**Comment by tlby** [comment]
@tonycoz that's a great point, thank you.  Calculating the number of outputs ahead of time should be possible most of the time, but is definitely a more involved patch.  I'll defer that for now.
