### ISSUE TITLE
Issue in node v10 even after a patch

### ISSUE THREAD

**Issue by cvinodhkumar77** [swig/swig#1380]
I have tried to fix the issue with node v10 provided the patch fix by https://github.com/arfoll/swig/tree/node7 but now I ran into below issues

C:\Users\UAL\Desktop\DeskoPenta\Code\SwigSimpleExample>node-gyp configure build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.14.2 | win32 | x64
gyp info spawn C:\Users\UAL\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Users\\UAL\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\UAL\\Desktop\\DeskoPenta\\Code\\SwigSimpleExample\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\UAL\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\UAL\\.node-gyp\\10.14.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\UAL\\.node-gyp\\10.14.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\UAL\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\UAL\\.node-gyp\\10.14.2\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\UAL\\Desktop\\DeskoPenta\\Code\\SwigSimpleExample',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\UAL\\Desktop\\DeskoPenta\\Code\\SwigSimpleExample\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  example_wrap.cxx
c:\users\ual\desktop\deskopenta\code\swigsimpleexample\example_wrap.cxx(1025): warning C4996: 'v8::Value::ToObject': wa
s declared deprecated [C:\Users\UAL\Desktop\DeskoPenta\Code\SwigSimpleExample\build\example.vcxproj]
  c:\users\ual\.node-gyp\10.14.2\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
c:\users\ual\desktop\deskopenta\code\swigsimpleexample\example_wrap.cxx(1115): warning C4996: 'v8::Value::ToObject': wa
s declared deprecated [C:\Users\UAL\Desktop\DeskoPenta\Code\SwigSimpleExample\build\example.vcxproj]
  c:\users\ual\.node-gyp\10.14.2\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
c:\users\ual\desktop\deskopenta\code\swigsimpleexample\example_wrap.cxx(1210): warning C4311: 'type cast': pointer trun
cation from 'void *' to 'long' [C:\Users\UAL\Desktop\DeskoPenta\Code\SwigSimpleExample\build\example.vcxproj]
c:\users\ual\desktop\deskopenta\code\swigsimpleexample\example_wrap.cxx(1210): warning C4302: 'type cast': truncation f
rom 'void *' to 'long' [C:\Users\UAL\Desktop\DeskoPenta\Code\SwigSimpleExample\build\example.vcxproj]
c:\users\ual\desktop\deskopenta\code\swigsimpleexample\example_wrap.cxx(1242): warning C4996: 'v8::Value::ToObject': wa
s declared deprecated [C:\Users\UAL\Desktop\DeskoPenta\Code\SwigSimpleExample\build\example.vcxproj]
  c:\users\ual\.node-gyp\10.14.2\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
c:\users\ual\desktop\deskopenta\code\swigsimpleexample\example_wrap.cxx(1261): warning C4996: 'v8::Value::ToObject': wa
s declared deprecated [C:\Users\UAL\Desktop\DeskoPenta\Code\SwigSimpleExample\build\example.vcxproj]
  c:\users\ual\.node-gyp\10.14.2\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
c:\users\ual\desktop\deskopenta\code\swigsimpleexample\example_wrap.cxx(1472): error C2664: 'v8::Maybe<bool> v8::Object
::SetAccessor(v8::Local<v8::Context>,v8::Local<v8::Name>,v8::AccessorNameGetterCallback,v8::AccessorNameSetterCallback,
v8::MaybeLocal<v8::Value>,v8::AccessControl,v8::PropertyAttribute,v8::SideEffectType)': cannot convert argument 2 from
'SwigV8AccessorGetterCallback' to 'v8::Local<v8::Name>' [C:\Users\UAL\Desktop\DeskoPenta\Code\SwigSimpleExample\build\e
xample.vcxproj]
  c:\users\ual\desktop\deskopenta\code\swigsimpleexample\example_wrap.cxx(1472): note: No constructor could take the so
  urce type, or constructor overload resolution was ambiguous
c:\users\ual\desktop\deskopenta\code\swigsimpleexample\example_wrap.cxx(1528): warning C4996: 'v8::Value::IntegerValue'
: was declared deprecated [C:\Users\UAL\Desktop\DeskoPenta\Code\SwigSimpleExample\build\example.vcxproj]
  c:\users\ual\.node-gyp\10.14.2\include\node\v8.h(2476): note: see declaration of 'v8::Value::IntegerValue'
c:\users\ual\desktop\deskopenta\code\swigsimpleexample\example_wrap.cxx(1547): warning C4996: 'v8::Value::NumberValue':
 was declared deprecated [C:\Users\UAL\Desktop\DeskoPenta\Code\SwigSimpleExample\build\example.vcxproj]
  c:\users\ual\.node-gyp\10.14.2\include\node\v8.h(2475): note: see declaration of 'v8::Value::NumberValue'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\UAL\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\UAL\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\UAL\Desktop\DeskoPenta\Code\SwigSimpleExample
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by wsfulton** [comment]
Node 10 works now in the upcoming swig-4.1.0 release.
