### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by brgirgis** [swig/swig#1385]
It would be very helpful if there is a simple set of instructions for building on windows. I spent a whole evening trying to do that with no luck. Better yet, it would be great if there was a cmake build option.

**Comment by wsfulton** [comment]
https://github.com/swig/swig/wiki/Getting-Started#windows has instructions for Windows. Those could probably do with updating using msys2. We regularly test using msys2 + mingw on Appveyor, see a recent build at https://ci.appveyor.com/project/swig/swig. It is actually somewhat easier on Ubuntu, see https://github.com/swig/swig/wiki/Getting-Started#windows. See https://github.com/swig/swig/pull/1040 if you want to help with a CMake build.
