### ISSUE TITLE
std::vector returned from attribute is not properly typemapped

### ISSUE THREAD

**Issue by barreyra** [swig/swig#1438]
In the following example:

```
namespace std {
    %template(UnsignedIntVector) vector<uint32_t>;
};

%attributeval(MyClass, std::vector<uint32_t>, Value, GetValue);
```

Retrieving the Value property of the object yields the following in an interactive Python shell:

```
>>> obj.Value
<Swig Object of type 'std::vector< unsigned int > *' at 0x10332d688>
```

instead of

```
>>> obj.Value
[0, 1, 2, 3]
```

**Comment by wsfulton** [comment]
This isn't anything to do with attributes nor typemaps. The std::vector wrappers do not have a `__str__` method to display the vector as you would like/expect. You can add one in quite simply by using `%pythoncode`. Here is a full example:

```swig
%module example

%include <attribute.i>
%include <stdint.i>
%include <std_vector.i>

%inline %{
struct MyClass {
  std::vector<uint32_t> GetValue() {
    return {1, 2, 3};
  }
};
%}
%extend std::vector {
%pythoncode %{
    def __str__(self):
        return str(list(self))
%}
}
namespace std {
    %template(UnsignedIntVector) vector<uint32_t>;
};
%attributeval(MyClass, std::vector<uint32_t>, Value, GetValue);
```

**Comment by ojwb** [comment]
@wsfulton I assuming not closing this was just an oversight.  If you think SWIG should provide this by default, please reopen.
