### ISSUE TITLE
how to create dynamic memory using calloc in c python wrapper.

### ISSUE THREAD

**Issue by myproject24** [swig/swig#1446]
struct *resultFeature = (struct*)calloc(10, sizeof(struct)); in python

**Comment by wsfulton** [comment]
Not sure what aspect of SWIG you need help with. Please re-open and elaborate if you need to report a SWIG bug.

**Comment by myproject24** [comment]
@wsfulton basically I need to null value to c++ API, I found None in python if I pass None to c++ API it is giving unexpected result actually c++ API have to return invalid parameter for NULL but in python, it is giving unexpected result because of None.
