### ISSUE TITLE
SWIG_PythonGetProxyDoc(const char*)’ declared ‘static’ but never defined

### ISSUE THREAD

**Issue by jschueller** [swig/swig#1448]
I've got new a warning when compiling with the swig runtime header (-external-runtime):
```
In file included from /home/devel/project/python/src/PythonDistribution.cxx:22:
/home/devel/project/build/python/src/openturns/swig_runtime.hxx:1008:26: warning: ‘PyMethodDef* SWIG_PythonGetProxyDoc(const char*)’ declared ‘static’ but never defined [-Wunused-function]
 SWIGRUNTIME PyMethodDef *SWIG_PythonGetProxyDoc(const char *name);
                          ^~~~~~~~~~~~~~~~~~~~~~
```
maybe it's related to the recent commit: https://github.com/swig/swig/commit/62c5ca89a61c96df6abe5468354520ae16da805e

**Comment by wsfulton** [comment]
Please try the fix just committed.

**Comment by jschueller** [comment]
still not fixed, and this time I've got this one too:
`warning: ‘PyObject* SWIG_PyInstanceMethod_New(PyObject*, PyObject*)’ declared ‘static’ but`

**Comment by wsfulton** [comment]
I think I've got it right this time, please try again with the latest.

**Comment by jschueller** [comment]
no more warnings, thanks for the fix
