### ISSUE TITLE
Python: swig_import_helper problems in frozen application.

### ISSUE THREAD

**Issue by takluyver** [swig/swig#145]
SWIG [autogenerates](https://github.com/swig/swig/blob/fb96ff9613215782e65ff8500354b518e9d5cf06/Source/Modules/python.cxx#L825) a `swig_import_helper()` Python function, which from what I can see, attempts to do relative imports in a way that remains valid syntax in Python 2.4. Unfortunately, the use of `__file__` doesn't work in frozen applications, and it falls back to `import %s` ([line](https://github.com/swig/swig/blob/fb96ff9613215782e65ff8500354b518e9d5cf06/Source/Modules/python.cxx#L834)), which doesn't work as a relative import in Python 3.

If I change the line to `from . import %s`, it works again. I guess that is invalid syntax on Python 2.4, but I don't have such an old version of Python handy to test. Projects that work on Python 3 rarely support Python 2.4, so it may be practical to make this an option.

This was [reported](https://bitbucket.org/anthony_tuininga/cx_freeze/issue/43/import-errors-when-using-cx_freeze-with) as a bug with cx_Freeze, a Python freezing tool, but I don't see a good way to fix it in cx_Freeze, so I wanted to bring it up here.

**Comment by mromberg** [comment]
This patch fixes this problem (I think) for python-2.7 and up.  It modifies the import_helper to use importlib.load_module() (which will use the full python import machinery) and the modules __name__ attribute (instead of __file__) to determine the package.

https://github.com/swig/swig/pull/612

**Comment by ojwb** [comment]
This indeed now appears to be fixed for 2.7 and up, and for versions prior to 2.6 too - `__file__` is now only looked at in the 2.6.x case:

```
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_overload_numeric', [dirname(__file__)])
        except ImportError:
            import _overload_numeric
            return _overload_numeric
        if fp is not None:
            try:
                _mod = imp.load_module('_overload_numeric', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _overload_numeric = swig_import_helper()
    del swig_import_helper
 ```

What cases is that fall-back import expected to handle?  Perhaps it should be `from . import _overload_numeric`, or if we should try that if `import _overload_numeric` fails.

Also, this code handles `fp is None` badly - we fall off the end of the function, and `_overload_numeric` gets set to `None`, which seems unhelpful.  Docs say:

> If the module does not live in a file, the returned file is None, pathname is the empty string, and the description tuple contains empty strings for its suffix and mode; the module type is indicated as given in parentheses above. If the search is unsuccessful, ImportError is raised. Other exceptions indicate problems with the arguments or environment.
>
> If the module is a package, file is None, pathname is the package path and the last item in the description tuple is PKG_DIRECTORY.

https://docs.python.org/2/library/imp.html#imp.find_module

The docs for `imp.load_module` say it accepts `file = None` in these cases, so I'm unclear why this is checked for.

Maybe that's what now happens in the reported case and removing that check would fix it, but without a simple reproducer it's hard to investigate.

Given we don't have a simple reproducer and that this has now been addressed for Python 2.7 and 3 (and older versions are no longer supported upstream) we should just close this (and perhaps move the `if fp is not None:` check to just protect `fp.close()`).  Thoughts?

**Comment by ojwb** [comment]
I've submitted the change I suggested above as PR#784, as that's the simplest way for me to test it with Python 2.6.

**Comment by ojwb** [comment]
That passed, and while the testsuite doesn't test frozen use, at least this shouldn't break non-frozen use.  Any objections to me merging that PR?

**Comment by wsfulton** [comment]
Looks okay to me.
