### ISSUE TITLE
'swig -help' return failure

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#1453]
I tried to rebuild swig 4.0.0 on Fedora and it failed with following error. 

```
BUILDSTDERR: No target language specified
BUILDSTDERR: make: *** [Makefile:102: check-aliveness] Error 1
BUILDSTDERR: error: Bad exit status from /var/tmp/rpm-tmp.6wVVmp (%build)
BUILDSTDERR:     Bad exit status from /var/tmp/rpm-tmp.6wVVmp (%build)
```

The failure is related to the commit "Stop defaulting to Tcl" (ec7202628). It causes that executing `swig -help` return failure. This command is run as part of check-aliveness.

```
# ./swig -help >/dev/null
No target language specified
# echo $?
1
```

[Source/Modules/main.cxx#L965](https://github.com/swig/swig/blob/master/Source/Modules/main.cxx#L965) - this check should not return 1 in case that help option is defined.

**Comment by ojwb** [comment]
Thanks, have pushed a fix.
