### ISSUE TITLE
%rename("$ignore", regexmatch$name=...) now results in parameter renaming

### ISSUE THREAD

**Issue by ojwb** [swig/swig#1460]
Trying out SWIG git master on Xapian's bindings, I found an unhelpful change in behaviour, which I would argue is a regression - the new behaviour is clearly not useful since it results in invalid Python code.

To demonstrate:

```
olly@gemse:~/git/swig$ cat dollarignore.i
%module dollarignore;
%rename("$ignore", regexmatch$name="_$") "";
%inline %{
int hide_this_one_(int x);
int wrap_me(int class_);
%}
olly@gemse:~/git/swig$ git checkout 3f5c17824c5f20023bac58f7ebfc8de8532d6881
HEAD is now at 3f5c1782 Improve handling parameters clashing with language keywords
olly@gemse:~/git/swig$ ./autogen.sh && make -s && ./preinst-swig -python dollarignore.i
+ test -d Tools/config
+ aclocal -I Tools/config
+ autoheader
+ automake --add-missing --copy --force-missing
+ autoconf
+ cd CCache
+ autoreconf
 cd .. && /bin/bash ./config.status Source/Makefile depfiles
config.status: creating Source/Makefile
config.status: executing depfiles commands
olly@gemse:~/git/swig$ tail -4 dollarignore.py
def wrap_me($ignore):
    return _dollarignore.wrap_me($ignore)


```

The pattern rename has been applied to a function parameter which has been renamed to `$ignore`, which is invalid Python code.

Prior to 3f5c17824c5f20023bac58f7ebfc8de8532d6881 things worked more helpfully - SWIG apparently realised that the special meaning of `$ignore` doesn't apply to a function parameter so it didn't try to rename it:

```
olly@gemse:~/git/swig$ git checkout 3f5c17824c5f20023bac58f7ebfc8de8532d6881^
Previous HEAD position was 3f5c1782 Improve handling parameters clashing with language keywords
HEAD is now at fa0c3fe5 Merge branch 'ZackerySpytz-OCaml-cpp_nodefault-constructor_rename-runtime-tests'
olly@gemse:~/git/swig$ ./autogen.sh && make -s && ./preinst-swig -python dollarignore.i
+ test -d Tools/config
+ aclocal -I Tools/config
+ autoheader
+ automake --add-missing --copy --force-missing
+ autoconf
+ cd CCache
+ autoreconf
 cd .. && /bin/bash ./config.status Source/Makefile depfiles
config.status: creating Source/Makefile
config.status: executing depfiles commands
olly@gemse:~/git/swig$ tail -4 dollarignore.py
def wrap_me(class_):
    return _dollarignore.wrap_me(class_)


```

It's not obvious to me why 3f5c17824c5f20023bac58f7ebfc8de8532d6881 caused this change in behaviour though.  @vadz This was your patch, any ideas?

**Comment by ojwb** [comment]
Oh, I see - although this is Python, previously the Python-specific code wasn't being used because kwargs weren't enabled.  The good parameter name came from the generic version (which just checked for name warnings and left it at that).

The problem is that now `Swig_name_make()` is used, and that looks at rename rules, etc.  There's a comment in there that "Parameter renaming is not fully supported", which suggests that there's some intention to support renaming parameters.  If so, perhaps the simplest fix is to check for `$ignore` and not apply such a rename to a parameter, something like:

```
diff --git a/Source/Swig/naming.c b/Source/Swig/naming.c
index 180e5477..4218b388 100644
--- a/Source/Swig/naming.c
+++ b/Source/Swig/naming.c
@@ -1526,6 +1526,11 @@ String *Swig_name_make(Node *n, String *prefix, const_String_or_char_ptr cname,
       }
     }
   }
+  if (Cmp(result, "$ignore") == 0 && n && Equal(nodeType(n), "parm")) {
+    /* Don't rename a parameter to $ignore. */
+    Delete(result);
+    result = NULL;
+  }
   if (!result || !Len(result)) {
     if (result)
       Delete(result);
```

I'll try that out and open a PR if it looks good and nobody has suggested a better plan by then.

**Comment by vadz** [comment]
Sorry for breaking this @ojwb and thanks for finding it!

I agree that it makes sense to change `Swig_name_make()` to avoid returning `$ignore` for parameters, as this can never be desirable, AFAICS. I wonder if it could be slightly better to do it in `apply_rename()` (which would need to be passed the node too, but otherwise could contain the same code) rather than at the end? But I don't have any better ideas...

As you wrote that you were going to open a PR, I won't do anything here for now, but please let me know if you'd prefer me to do it -- as the one who broke it, I definitely feel responsible for fixing it now.

**Comment by ojwb** [comment]
@vadz If you're happy to fix it, please do - I have some PHP issues to look at still.  FWIW I tested a little more and didn't find any issues.
