### ISSUE TITLE
Is there any plan to support Rust?

### ISSUE THREAD

**Issue by wuzhen42** [swig/swig#1468]
since https://rust-lang.github.io/rust-bindgen/cpp.html has so many unsupported features, can swig be a better tool to generate wrapper for rust?

**Comment by wsfulton** [comment]
A SWIG Rust module ought to solve most of those problems, but be aware that SWIG comes with its own set of quirks. The biggest issue is there is no Rust module in SWIG. SWIG is an all volunteer project, so anyone wanting to contribute a Rust module for SWIG should take a look at http://www.swig.org/Doc4.0/Extending.html and I suggest they mention any intention of doing so on this Github issue.

**Comment by vadz** [comment]
FWIW I think Rust module should build on C one (which is indeed one of the reasons I'm so much interested in the latter) as Rust has transparent interoperability with C.

**Comment by IngwiePhoenix** [comment]
For what I know, SWIG needs to generate a C-style OOP of C++ code and then a Rust file containing structs and implementations to make the C-style OOP available again. That should be possible...but I don't know how, yet.

For instance:
```c++
// Assuming something like this:
#include <inttypes.h> 
class Vector {
  public:
  Vector(uint32_t _x, uint32_t _y) : x(_x), y(_y) {}
  ~Vector() {}
  // put more methods here...
  private:
  uint32_t x;
  uint32_t y;
};

// SWIG should generate this for C-style OOP:
// @file C_Vector.h
typedef void C_Vector;
#ifdef __cplusplus
extern "C" {
#endif
C_Vector* Vector_new(uint32_t _x, uint32_t _y);
void Vector_free(C_Vector* self);
#ifdef __cplusplus
}
#endif

// @file C_Vector.cxx
C_Vector* Vector_new(uint32_t _x, uint32_t _y) {
  return (C_Vector*)(new Vector(_x, _y));
}
void Vector_free(C_Vector* self) {
  delete (Vector*)self; // run destructor
}
```

Now, this is a super, super basic example, but with it, it is quite easy to interface with the C++ library from C already - and this is required to have Rust interface with it as well. Now, I am not a Rust expert and my experience with it is very...low. So take this snippet with a grain of salt :)

```rust
// This is what Swig should also generate.
// @file Vector.rs
extern crate libc;
extern {
  fn Vector_new(_x: libc::uint32_t, _y: libc::uint32_t) -> libc::c_void;
  fn Vector_free(v: libc::c_void) -> ();
}
struct Vector {
  // ... add a reference to the "C_Vector" pointer, which really is a "Vector" pointer.
}
impl Vector {
  fn new(_x: u32, _y: u32) -> Vector {
    // call Vector_new(x, y) and store result.
  }
  fn free(mut* self) {
    Vector_free(self.ptr);
  }
}
```

Again... I am super new to Rust and such ^^;

But essentially, this is what SWIG should generate - abstract C++ code to C, and wrap any C code into an `unsafe` block. Then re-create structs/classes as opaque types by mapping implementations on the C variants.

At least, this is what I think would work best. However, there would be a dependency on the `libc` crate...

**Comment by vadz** [comment]
> But essentially, this is what SWIG should generate - abstract C++ code to C

Yes, this is what C backend does.

> and wrap any C code into an unsafe block.

This doesn't exist at all yet, but should be relatively straightforward, I think.

**Comment by wuzhen42** [comment]
> At least, this is what I think would work best. However, there would be a dependency on the libc crate...

Rust libc type definition is nothing but alias. check [uint32_t](https://docs.rs/libc/0.2.50/libc/type.uint32_t.html)
So generated rust code doesn't need to use libc.

> But essentially, this is what SWIG should generate - abstract C++ code to C, and wrap any C code into an unsafe block.

Rust offical [bindgen](https://github.com/rust-lang/rust-bindgen) generates Rust interface on the fly, but no extra C++ wrapper, or shadow library. That's why it doesn't support inline functions and exceptions, for example. Basically, no extra wrapper function call, directly call the original lib func. Maybe no "wrapper" at all, just symbol interface definition.

To acheive this, Rust doesn't only support transparent C linking, it also support "transparent" C++ linking, by setting C++ mangled symbol name.

For example,
foo.hpp
``` cpp
#pragma once
int square(int x);
```
bindings.rust
```rust
/* automatically generated by rust-bindgen */

extern "C" {
    #[link_name = "\u{1}_Z6squarei"]
    pub fn square(x: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
```

But I believe Swig would be much more convient by generating additonal wrap layer in C++, even with one extra function call.

Struggling to add Rust module and beat Swig test-suite here.

**Comment by vadz** [comment]
Wrapping functions is straightforward enough, but how do you wrap classes, including virtual methods and, in particular, directors?

**Comment by wuzhen42** [comment]
Here's a example showing current work of [rust-bindgen](https://github.com/rust-lang/rust-bindgen).

```cpp
#pragma once

namespace ns {
class A {
public:
    A();

    virtual ~A();

    int method();

    virtual A* vmethod();

private:
    class Impl;
    Impl* pimpl;
};
}
```

generated Rust
```rust
/* automatically generated by rust-bindgen */

#[repr(C)]
pub struct ns_A__bindgen_vtable(::std::os::raw::c_void);
#[repr(C)]
#[derive(Debug)]
pub struct ns_A {
    pub vtable_: *const ns_A__bindgen_vtable,
    pub pimpl: *mut ns_A_Impl,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ns_A_Impl {
    _unused: [u8; 0],
}
#[test]
fn bindgen_test_layout_ns_A() {
    assert_eq!(
        ::std::mem::size_of::<ns_A>(),
        16usize,
        concat!("Size of: ", stringify!(ns_A))
    );
    assert_eq!(
        ::std::mem::align_of::<ns_A>(),
        8usize,
        concat!("Alignment of ", stringify!(ns_A))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<ns_A>())).pimpl as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(ns_A),
            "::",
            stringify!(pimpl)
        )
    );
}
extern "C" {
    #[link_name = "\u{1}_ZN2ns1A6methodEv"]
    pub fn ns_A_method(this: *mut ns_A) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_ZN2ns1AC1Ev"]
    pub fn ns_A_A(this: *mut ns_A);
}
impl ns_A {
    #[inline]
    pub unsafe fn method(&mut self) -> ::std::os::raw::c_int {
        ns_A_method(self)
    }
    #[inline]
    pub unsafe fn new() -> Self {
        let mut __bindgen_tmp = ::std::mem::uninitialized();
        ns_A_A(&mut __bindgen_tmp);
        __bindgen_tmp
    }
}
extern "C" {
    #[link_name = "\u{1}_ZN2ns1AD1Ev"]
    pub fn ns_A_A_destructor(this: *mut ns_A);
}
extern "C" {
    #[link_name = "\u{1}_ZN2ns1A7vmethodEv"]
    pub fn ns_A_vmethod(this: *mut ::std::os::raw::c_void) -> *mut ns_A;
}
```
and this is how it could be consumed
```rust
fn main() {
    unsafe {
        let mut obj = ns_A::new();
        let x = obj.method();
        println!("Hello, {}!", x);
        ns_A_A_destructor(&mut obj);
    }
}

```

As for class directors, I have no idea now what it should be like, since Rust doesn't support inheritance, except interface.

**Comment by vadz** [comment]
> and this is how it could be consumed

This hardly looks like idiomatic Rust :-( I hope we could generate code implementing `Drop` to call the C++ dtor automatically, otherwise it doesn't seem to be very useful in practice.

> As for class directors, I have no idea now what it should be like

Me neither, unfortunately, but it would need to be based on providing a `Fn` to call, somehow...

**Comment by wuzhen42** [comment]
> This hardly looks like idiomatic Rust :-(

Oh I’m just trying to give information about what status this **official** bindgen project are at. Personally get no whole picture in my mind of how things should be done, correctly.

Agree your thoughts here.

**Comment by swagggpickle** [comment]
Has anyone expressed interest in implementing the rust module? I would love to take on this task.

**Comment by ali-ramezani** [comment]
Since the Rust interop with C++ through C FFI I guess extending or using already available wrapper in SWIG would be better.
D, C#,... are using C FFI similarly so we can just generate the rust side boilerplates.
Or XML port also would give whole structure so it could be used to generate both side but it would be better to be inside of swig echosystem.

**Comment by ojwb** [comment]
> Has anyone expressed interest in implementing the rust module? I would love to take on this task.

I don't anyone else has.

**Comment by dameng-wu** [comment]
Is there any progress on this issue?

**Comment by mihaigalos** [comment]
As a potential workaround, I think it would be possible to interop Rust-with-X using a C dll/so:
* generate the bindings for the target language and C.
* write a small C lib wrapper as a dll/shared object.
* use that wrapper in Rust.

**Comment by ojwb** [comment]
Maybe I'm misunderstanding, but it seems people are talking about two rather different things here.

One is supporting Rust as a target language in SWIG, so you'd be able to take a C or C++ library and create wrappers which allow it to be used from Rust.  This seems reasonably feasible - though please be aware that adding a new target language requires someone with a good knowledge of the target language (i.e. Rust) and how it interfaces with C/C++, and also a significant amount of time and determination.

In particular simply repeatedly asking for Rust as a new target language (e.g. by pinging this issue) won't make it happen.  SWIG doesn't have a team of developers on standby itching to being given new things to work on as some people seem to assume.

The other thing being talked about seems to be rather different: "interop Rust-with-X" presumably means something like interfacing Rust and Python using SWIG.  That would really require supporting Rust at the other end, so SWIG would have to support wrapping a Rust library like it can currently wrap a C or C++ library.  That's a whole different kettle of whales in terms of the amount of work and also the amount of determination that would be required.

**Comment by mihaigalos** [comment]
You are not misunderstanding, these are effectively 2 things here.
* The Rust-with-X won't happen until there is SWIG support for Rust.
* The X-to C-to Rust might happen and is more likely than the first. Rust code might get consumed as a lib with FFI bindings.

Do you really think it requires expert-level knowledge on either side? I doubt it but maybe am very wrong.

**Comment by ojwb** [comment]
Not sure which "it" you are asking about.

If you're just wanting to use the SWIG/C target language and call that with FFI you don't need to know anything about SWIG, though bear in mind that work has still not been merged.  I don't know much about Rust, but on the Rust side you'd presumably need to know Rust fairly well, and either know or be prepared to get to grips with FFI.  However, the C target language hasn't yet been merged (see #2086 for the sorry details) so you can't actually rely on it.

If you're wanting SWIG to be involved with generating the Rust FFI layer too, then you're going to need to get to grips with SWIG, but you can probably follow an existing target language that has a similar structure.  I think you'd not use the C target language for that - SWIG can generate a flat C wrapper layer for you, which the existing target languages mostly (maybe all?) use.  The C target language essentially exposes that rather than it being an internal detail, at least AIUI.  Again you're really need a good understanding of Rust to be able to generate appropriate wrappings for various things, and to write suitable `_runme.rs` files for the testsuite.

I think the Rust-with-X would require major wizard-level skills on the SWIG side.  The parser would need to be extended to understand Rust code (or an existing Rust parser could be used except it needs to be extensible to handle SWIG directives - one of the problems with the suggestions that we switch to using the clang parser), and SWIG's type system would presumably need extending to support representing Rust's type system.

I don't think I'd attempt it, even if I knew enough Rust.  It might seem a tempting idea as a way to provide interop between Rust and whole list of other languages in one go, but I suspect you'd end up needing to tweak every target language backend as there's some knowledge of C/C++ embedded at that level.  I also fear you'd struggle to get it all reviewed and merged as we're already backed up with patches and issues.  Overall it seems like too big a scope creep for SWIG to me at least.

**Comment by kassane** [comment]
There is a proposal that may be interesting for this topic 

- https://github.com/rust-lang/rust/pull/105586

**Comment by ojwb** [comment]
Adding a new target language backend is a significant amount of work and SWIG is a volunteer project, so they only get implemented when somebody who wants the support actually does that work.

If that sounds like you then you can find the guide to adding support for a new target language here:

http://www.swig.org/Doc4.1/Extending.html#Extending_nn31

Particularly important to note are the criteria for merging a new target language:

https://www.swig.org/Doc4.1/Extending.html#Extending_language_status

Keeping a feature request ticket open for a new target language doesn't seem useful so I'm going to close this. Realistically someone will implement support because they want it, not because they see a ticket open for it.

**Comment by ojwb** [comment]
Those interested in being able to wrap C/C++ for Rust using SWIG may be interested in #2734.

**Comment by 0warning0error** [comment]
I have been working on this for nearly 2 weeks and have made swig limitedly support Rust.(including limited director mode, function call and simple enum type etc.) I know a little about swig code so I choiced to copy `go.cxx` and modify it to support Rust. I will open a PR once basic features, tests and  documents are finished. Advance features are considered once I am free.
todo list:
- multiple inheritance
- default complex type process
- basic typemap

todo list in the future:
- default parameter and overload function
- operator overloading to Rust Trait
- union type
- etc...

**Comment by wsfulton** [comment]
@0warning0error very interesting. There is a fundamental problem with the GO module in go.cxx with its typemap support and uses a number of non-conventional features I won't accept. I would really discourage you from using it, I am not likely to accept it into master and it will be painful for review and create delays. For a statically typed language like Rust, C# or Java are the best reference implementations. Sorry for the bad news, but I strongly suggest you grab a new reference and recode it.

**Comment by 0warning0error** [comment]
> [@0warning0error](https://github.com/0warning0error) very interesting. There is a fundamental problem with the GO module in go.cxx with it's typemap support and uses a number of non-conventional features I won't accept. I would really discourage you from using it, I am not likely to accept it into master and it will be painful for review and create delays. For a statically typed language like Rust, C# or Java are the best reference implementations. Sorry for the bad news, but I strongly suggest you grab a new reference and recode it.

What's the problem about typemap in `go.cxx` and what's non-conventional features. Do you mean undocumented features?  I tend to change them to standard features and try to solve typemap problem . But if it cost too much to solve, I would consider refactoring it from scratch. As I said, I know a little about Swig and want to start on the shoulders of the gaint. Despite statically typed language, the gramma of Rust looks like Go most. So I choice  `go.cxx` to start. I am not so glad to hear that but thanks for telling me.

**Comment by wsfulton** [comment]
I am really sorry you chose the wrong module to base off. The work you've spent in designing the proxy classes and intermediate functions are likely to be the same. You probably won't spend too long copying csharp.cxx in its entirety, choosing appropriate typemap names and you will have much more advanced support. BTW, I would definitely not tackle directors first, it is not way hard to get bug free than it first looks. I suggest you aim to cover C++ classes and all C functionality first.

Go issues: https://github.com/swig/swig/issues?q=is%3Aissue%20state%3Aopen%20label%3AGo. In particular, Go is the only module where the typemaps are fundamentally flawed and it looked like a rewrite was needed, some more details in #2337. Typemaps are the most important SWIG feature. Go also uses non-standard user-unfriendly function name mangling.

**Comment by 0warning0error** [comment]
> I am really sorry you chose the wrong module to base off. The work you've spent in designing the proxy classes and intermediate functions are likely to be the same. You probably won't spend too long copying csharp.cxx in its entirety, choosing appropriate typemap names and you will have much more advanced support. BTW, I would definitely not tackle directors first, it is not way hard to get bug free than it first looks. I suggest you aim to cover C++ classes and all C functionality first.
> 
> Go issues: https://github.com/swig/swig/issues?q=is%3Aissue%20state%3Aopen%20label%3AGo. In particular, Go is the only module where the typemaps are fundamentally flawed and it looked like a rewrite was needed, some more details in [#2337](https://github.com/swig/swig/issues/2337). Typemaps are the most important SWIG feature. Go also uses non-standard user-unfriendly function name mangling.

alright. I will discard the `go.cxx` based `rust.cxx` and turn to `csharp.cxx` to continue my work. This process may be slow. I have pushed my `go.cxx` based code to my forked [repo](https://github.com/0warning0error/swig/tree/rust-support). Those interested in it can compile by themselves and try it.

By the way, is there a script that helps me debug. I feel tricky when I debug this module in Swig.
