### ISSUE TITLE
C++11 enum class scope issue

### ISSUE THREAD

**Issue by alexey-pelykh** [swig/swig#147]
There are 3 different strong enums defined, like this:
```
enum class /* name */
{
    // ...
    Invalid,
    // ...
}
```
When using latest HEAD version of swig, I get following:
```
/[...]/MapRendererTypes.h:14: Error: 'Invalid_get' is multiply defined in the generated target language module in scope 'OsmAndCoreJNI'.
/[...]/MapTypes.h:30: Error: Previous declaration of 'Invalid_get'
/[...]/MapStyle.h:24: Error: 'Invalid_get' is multiply defined in the generated target language module in scope 'OsmAndCoreJNI'.
/[...]/MapTypes.h:30: Error: Previous declaration of 'Invalid_get'
```

I believe that this is wrong, since "Invalid" doesn't belong to global scope (since it's enum class, not enum). Taking into account that current HEAD is unstable 3.0.0, I wonder if enum classes are already supported, or they are just treated as regular enums.

**Comment by ojwb** [comment]
#215 was merged over two years ago, so closing this.
