### ISSUE TITLE
Build of  hugin fails due to 'Unknown SWIG preprocessor directive'

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#1475]
I am testing rebuild of packages which depends on SWIG in Fedora. I used the latest version of SWIG from git.

The rebuild of package [hugin](https://src.fedoraproject.org/rpms/hugin) fails with following errors:
```
hsi_PanoramaData.h:1: Error: Unknown SWIG preprocessor directive: 1 (if this is a block of target language code, delimit it with %{ and %})
hsi_PanoramaData.h:2: Error: Unknown SWIG preprocessor directive: 1 (if this is a block of target language code, delimit it with %{ and %})
hsi_PanoramaData.h:3: Error: Unknown SWIG preprocessor directive: 1 (if this is a block of target language code, delimit it with %{ and %})
...
```
The head of hsi_PanoramaData.h is 
```
# 1 "/builddir/build/BUILD/hugin-2018.0.0/src/hugin_base/panodata/PanoramaData.h"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "/builddir/build/BUILD/hugin-2018.0.0/src/hugin_base/panodata/PanoramaData.h"
# 48 "/builddir/build/BUILD/hugin-2018.0.0/src/hugin_base/panodata/PanoramaData.h"
```

I found out that the failure appeared after this commit 72964a1.

Is there any way how to fix it?

**Comment by wsfulton** [comment]
Hi @jplesnik. The hsi_PanoramaData.h file shown looks like it is the output from gcc's preprocessor, that is, running something like gcc -E PanoramaData.h. So SWIG is now saying that `# 1` is not a valid pre-processor statement. I've no idea if that is correct, I guess I'd better find out!

**Comment by wsfulton** [comment]
I can't see this in the C11 standard, however gcc documents _linemarkers_ in the form `# linenum filename flags` being generated into the output as a result of preprocessing, see https://gcc.gnu.org/onlinedocs/cpp/Preprocessor-Output.html#Preprocessor-Output . It looks easy enough to add in SWIG, so I'll allow SWIG's preprocessor to accept this again (but just ignore the linenum/filename info like it used to).

The hugin build could alternatively run `gcc -E -P` which suppresses the line markers from appearing in the output.
