### ISSUE TITLE
Python is crashing when i call c++ api

### ISSUE THREAD

**Issue by myproject24** [swig/swig#1478]
> test.cpp
```
int initilizeObj(void* dictPtr, void** dataPtr)
{
        int ret = 0;
    	if (dictPtr== NULL) return S_OD_ERROR_INVALID_PARAM;
	if (dataPtr== NULL) return S_OD_ERROR_INVALID_PARAM;
       void        *BinData;
        ret = Initialize(dictPtr, BinData, &dataPtr);

        return ret;
}
```
> test.py
```
ret, Data = test.initilizeObj(np.array([], np.uint8))
```
When execute test.py file or if i just call initilizeObj() function from python, python is crashing it says "python stopped working" and in test.i file i just included test.h header file. Above function call have 2 parameters one is input parameter and 2nd is output parameter.

**Comment by myproject24** [comment]
@wsfulton Please replay to the above issue.

**Comment by ojwb** [comment]
The example is woefully incomplete - we don't have the definitions of `S_OD_ERROR_INVALID_PARAM` or `Initialize`, we don't have the interface file used to get SWIG to create the bindings, and we don't have the python code to know what `np.array` and `np.uint8` are.

This is essentially impossible for us to usefully do anything with - there are just too many unknowns for us to try to fill them in ourselves - so I'm going to close it as incomplete.  If you want somebody to look at your problem, you need to provide a small, self-contained example so we can reproduce it.
