### ISSUE TITLE
Will support c++/cli(managed c++) as target language?

### ISSUE THREAD

**Issue by Leon-Zhang** [swig/swig#1482]
Do you have a schedule for support c++/cli(managed c++) as target language?

thanks.

**Comment by geefr** [comment]
I can't speak for the swig maintainers but would question why you need this.

For one C++/CLI can use both C++ and .Net classes natively, without any need for a DLLImport or similar calling method

Secondly I would not recommend using C++/CLI for anything. I've found that the C++/CLI keywords and extensions to the C++ syntax are incompatible with modern C++ (11 onwards), meaning you're bound to C++03.

With the .Net wrappers I've worked on we moved away from C++/CLI to C#. Partly to allow the use of swig, and partly to have a clean separation between the 2 languages.

Using C# can also allow the code to run on more than just windows (admittedly haven't tried swig/C# on Linux yet, but think it's possible).

**Comment by Leon-Zhang** [comment]
@geefr Hi, thanks for reply.
The reason I use c++/cli is because I have a large code base of c++ source code, and I need to make a net assembly version of these code that been able to be called from .net environment.
This means, I hope all the classes and its methods written in unmanaged c++ able to be called from .net environment(c#, VB/net etc) as much as possible.
c# is a good language but it can only make P/Invoke call to dll level wrap, not like c++/cli can closely wrap unmanaged c++ code.

**Comment by wsfulton** [comment]
I can speak for the SWIG developers, but @geefr sums it up well. There are no plans to support C++/CLI given C# as a target language provides access to native C++ code from .NET already. It works cross-platform, works with Mono too and so does not have the limitations of C++/CLI.

**Comment by Leon-Zhang** [comment]
>Secondly I would not recommend using C++/CLI for anything. I've found that the C++/CLI keywords and extensions to the C++ syntax are incompatible with modern C++ (11 onwards), meaning you're bound to C++03.
.Net assembly essentially not under c++ standard any more, so no need to port these language specific feature.
