### ISSUE TITLE
swig-4 + python + packages + static linking

### ISSUE THREAD

**Issue by mromberg** [swig/swig#1486]
Got a chance to try out master (which will soon become swig4) last night on a few of the larger projects I have that use swig.   Overall things seems to work well and the simplification of the python code is great.   

  There is one issue I bumped into that I think is worth bringing to attention.   There is a regression in master that also caused havoc in 3.0.9.   Apparently there is no test case that covers this.  I'm 100% certain I remember multiple trouble tickets covering this case when swig-3.0.9 was released.

  The troublesome case is:

- Swig generates a wrapper module for python with a shadow class.  So there are two python modules created by swig.  For example foo.py and foo_wrap.C
- The user does not link foo_wrap.C into _foo.so but instead statically links the module into an embeded interpreter.   This means that _foo is in the global namespace/package
- The user places foo.py into a package such as mypackage/foo.py

  The new simplified swig support module loader will fail to find _foo:
```python
if __package__ or '.' in __name__:
    from . import _foo
else:
    import _foo
```
  The if statement will be true (since foo.py is in a package) but the _foo module is not in that same package.   SWIG has always allowed this.  I personally don't like it and think the support module should be in the same package as the shadow module or it is an error.  However there are a non-zero number of swig users that are doing exactly this.

  Given that swig-4.0 is a major release, there exists an opportunity to address this:

- There is a fairly straight forward workaround by using the %module(moduleimport="import $module") foo feature.   However this should probably be documented explicitly for this failure case here.  And the expectation would be to see multiple tickets on this issue when swig-4 is released.
- Try and make the %module(package="mypackage") option apply the package name into the support module init code so that the support module is not in the global namespace.   I tested this and it does not seem to do that.  I have no idea how much work it involves.  Since swig supports python2 and python3, at least two methods of doing this would have to be supported.   Plus this solution suffers the same problem as the previous workaround.  That is multiple trouble tickets will be created when swig-4 is released.
- Add back in some code to detect the failure to locate _foo in the same package and then look for it in the global namespace.  Personally I dislike this option.   However it would break less code when swig-4 is released.   There is no clean way to do this check (that I have found).   And will probably be more painful in the long run.

  So in my opinion, the best thing for swig to do now is to take advantage of the fact that swig-4 is a major release and declare this old supported technique unsupported, suggest the above workaround (moduleimport), list this clearly as a change related to python in swig4 and finally be prepared for some number of trouble tickets related to it. :)

P.S.  Another downside of doing the above is that the workaround will only function with swig versions after moduleimport was added to swig.

P.P.S. Turns out that using moduleimport is not a workaround that functions on both swig3 and swig4 at the same time for this situation.   It looks like the swig3 code that is removed with moduleimport also has other things like new_instancemethod.   So, to use the moduleimport workaround one will also need to use the swig preprocessor and check for the swig version number to either use moduleimport or not.

**Comment by wsfulton** [comment]
Here is the relevant change note for the release: https://github.com/swig/swig/blob/613ff08150e6264a5a4a964f2badeb6bba221398/CHANGES.current#L337-L358
Look for "split modules" in the [Location of modules](http://swig.org/Doc4.0/Python.html#Python_package_search) section in the docs. This change is indeed expected to cause disruption for anyone using split modules. If any of this isn't clear as to what you or other users need to do, please say and I can improve the communications in this area before we release swig 4.0. #848 #1343 are the relevant Github issues.

The Examples/python/import_packages set of examples shipped with SWIG, see https://github.com/swig/swig/tree/master/Examples/python/import_packages, has the split_modules examples. We don't have an embedded Python example case you described, but a patch to add one in under this directory would be welcome.

**Comment by mromberg** [comment]
OK.  False alarm :).   I know this caused a fair amount of trouble before and wanted to double check that it was intentional.   Now that swig has the moduleimport option, there is a fairly painless way to deal with this now.   

  And it is a much better option to have folks using staticly linked modules use importmodule rather than make the shadow module jump through hoops trying to find the where the heck the C/C++ module may be.   I did a little research and discovered that in this day and age it is still not (easily) possible to load a static module via PyImport_ExtendInittab() and place it into a package.   So, all these static modules are stuck in the global namespace.   Now swig has a clean way to deal with them.   There may be a few trouble tickets to deal with when swig4 is released.  But the fix to the user code is not difficult and documented.

**Comment by wsfulton** [comment]
Yes, it is an improvement, will cause a bit of disruption for some, but is easy to overcome.

**Comment by asselapathirana** [comment]
Useful discussion. Just save time for me when I tried to build an old package after upgrading swig to 4
