### ISSUE TITLE
How to use it for C/C++ pointer?

### ISSUE THREAD

**Issue by zhuyu4839** [swig/swig#1504]
The method in c is "ViStatus _VI_FUNC  viOpenDefaultRM (ViPSession vi);". The param "ViPSession" is a point to long. The auto code is:
  public static int viOpenDefaultRM(SWIGTYPE_p_unsigned_long vi) {
    return SwigVisaJNI.viOpenDefaultRM(SWIGTYPE_p_unsigned_long.getCPtr(vi));
  }
and the SWIGTYPE_p_unsigned_long class is coded:
public class SWIGTYPE_p_unsigned_long {
  private transient long swigCPtr;

  protected SWIGTYPE_p_unsigned_long(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_unsigned_long() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_unsigned_long obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}
The construct is protected method. How do I get an instance of  SWIGTYPE_p_unsigned_long?

**Comment by ojwb** [comment]
It depends how the API you are wrapping expects you to use a `ViPSession` but from the name I'd guess it's an opaque token returned by something like

```
ViPSession CreateSession();
```

You'd then pass this to other functions in the API to tell them the session to operate on.
