### ISSUE TITLE
swig-3.0.12  golang callback example error

### ISSUE THREAD

**Issue by lihaic** [swig/swig#1506]
swig version 3.0.12 
golang version go1.12 linux/amd64

example source path:  swig-3.0.12/Examples/go/callback

description:
in file gocallback.go, struct overwrittenMethodsOnCallback doesn't implement the Run() method, so when the test file runme.go call golang callback method, it failed.
I notified the struct goCallback in file gocallback.go implement Run method, so should we change this to the impelment for struct overwrittenMethodsOnCallback?

**Comment by ojwb** [comment]
This was fixed in 4.0.0 by 5386bf2a2484c0db5d8dcb9c050e480b30f2d28e.
