### ISSUE TITLE
[Ruby] Overloaded function for default and keyword parameter

### ISSUE THREAD

**Issue by datnd** [swig/swig#1507]
Hi,

I am trying to write typemap for a Ruby function from cpp code.  The generated Ruby functions can support for both default and keyword parameter. But I get issue "Overloaded function".

the cpp function : 
Foo(int arg1 = 0, int arg2 = 1, int arg2 = 2)

I want to create Ruby functions which can pass input like:
A: Foo(Hash["arg1" => 3, "arg2" => 5 ... ])
B: Foo(1,2,3)
C: Foo(1,2)
D: Foo(1)

Currently I can use functions A,C,D. But function B: Foo(1,2,3) is overloaded and I can not use this function.

Could you please suggest me any solution for this issue.

Thank you.

**Comment by ojwb** [comment]
This works for me:

```
$ cat test.i
%module xxx
%inline %{
void Foo(int arg1 = 0, int arg2 = 0, int arg3 = 2) {
}
%}
$ swig -c++ -ruby test.i
$ cat extconf.rb
require 'mkmf'  
create_makefile('xxx')
$ ruby extconf.rb 
creating Makefile
$ make
compiling test_wrap.cxx
linking shared-object xxx.so
$ ruby -I. -e 'require "xxx"; Xxx.Foo(1,2,3);'
$
```
