### ISSUE TITLE
Wrappers for C++ contain snprintf / _snprintf macro that may break compilation under Visual Studio 2015 and up

### ISSUE THREAD

**Issue by pbecherer** [swig/swig#1508]
We noticed that the build of the SWIG Tcl wrapper to our C++ library started failing when using Boost 1.69. It turns out that Boost makes use of `std::snprintf()` (which is part of C++11) in one of its header files when compiling with Visual Studio 2015 or later. However, this gives problems with SWIG-generated wrappers that include this Boost header file. The cause seems to be that the wrappers (the Tcl wrappers at any rate) contain a macro to deal with `snprintf()` on older Visual C++ compilers that do not yet properly support it:

```cpp
#include <stdio.h>
#if defined(_MSC_VER) || defined(__BORLANDC__) || defined(_WATCOM)
# ifndef snprintf
#  define snprintf _snprintf
# endif
#endif
```

This may then lead to calls like `std::_snprintf("...")`, which will not compile (`_snprintf()` is not a member of `std`). This is not specific to Boost, but should happen for any `std::snprintf()` in (header) files that are included in the generated wrapper.

I think a usable solution would be to include a version check for the Visual C++ compiler, such that the `snprintf` macro is not used for Visual Studio 2015 and up. These newer versions properly support `snprintf()` and `std::snprintf()`, and they do not need the macro.

As far as I can see, in the 3.0.12 release, the macro comes from this fragment in `Lib/typemaps/fragments.swg`:

```cpp
%fragment("<stdio.h>","header") %{
#include <stdio.h>
#if defined(_MSC_VER) || defined(__BORLANDC__) || defined(_WATCOM)
# ifndef snprintf
#  define snprintf _snprintf
# endif
#endif
%}
```

This was moved to `Lib/swigfragments.swg` in the development source at some point, but the code is still there.

I think the problem can be solved by changing this fragment to

```cpp
%fragment("<stdio.h>","header") %{
#include <stdio.h>
#if (defined(_MSC_VER) && (_MSC_VER < 1900)) || defined(__BORLANDC__) || defined(_WATCOM)
# ifndef snprintf
#  define snprintf _snprintf
# endif
#endif
%}
```

where 1900 is the Visual C++ compiler version corresponding to the initial Visual Studio 2015 release.

For our build, using swigwin-3.0.12, this change sufficed to make the generated Tcl wrapper compile.

I do not now how specific this is to the Tcl wrappers: the only other wrappers we use are Python wrappers, and they do not contain this particular fragment.

**Comment by wsfulton** [comment]
Thanks, I checked the Visual Studio documentation and confirmed that snprintf was first supported in Visual Studio 2015.
