### ISSUE TITLE
Target language callbacks

### ISSUE THREAD

**Issue by CatsNipYummy** [swig/swig#1509]
I've been trying to do target language callbacks according to [this blog](https://www.softwariness.com/articles/api-design-for-swig/#Callbacks) , [Github URL](https://github.com/Softwariness/SwigUsageExample/tree/master/MyLibrary)

The issue is that when I call the override in C#, I get the following error:

`libc++abi.dylib: terminating with uncaught exception of type Swig::DirectorPureVirtualException: Attempt to invoke pure virtual method Vault::Bridge::VaultAPI::ImplementMe`

I've seen documentation for SWIG 4.0 that creates these but there wasn't a good example I could follow. Is the older way of using pure virtual methods depricated?

I've added %module(directors="1") libName and %feature("director"); to my .i file.

**Comment by wsfulton** [comment]
There are working director examples distributed with SWIG. Take a look at the Examples/csharp/extend and Examples/csharp/callback examples.

If you are getting a DirectorPureVirtualException, you can't be overriding the method from either a C# or C++ class that derives from the abstract C++ class.
