### ISSUE TITLE
Changes in mkoctfile with octave 5.1.0

### ISSUE THREAD

**Issue by opoplawski** [swig/swig#1513]
mkoctfile's behavior has changed with 5.1.  Previously mkoctfile -p LFLAGS output something like:
```
-L/usr/lib64/octave/4.4.1 -L/usr/lib64
```
But with 5.1.0:
```
# mkoctfile -p LFLAGS
warning: LFLAGS is deprecated and will be removed in a future version of Octave, use LDFLAGS instead
-L/usr/lib64
# mkoctfile -p LDFLAGS
-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld 
```
Octave does not appear to be concerned about the change:
https://savannah.gnu.org/bugs/?55447
Their suggestion seems to be either "pkg-config --libs octinterp"  or "mkoctfile -p OCTLIBDIR".  The pkg-config option is new with 5.1.  Using OCTLIBDIR seems to be backwards compatible.

**Comment by wsfulton** [comment]
Fixed by #1522.
