### ISSUE TITLE
Doxygen parsing fails if last enum item is followed by comma

### ISSUE THREAD

**Issue by markok314** [swig/swig#1514]
Example of enum with comma after the last item and doxygen comment, which fails:
<pre>
    /**
     * Testing comments after enum items
     */
     enum SomeAnotherEnum3
     {
       SOME_ITEM_100, ///< Post comment for the first item
       SOME_ITEM_200, ///< Post comment for the second item
       SOME_ITEM_300, ///< This comma is valid code but parsing fails with -doxygen flag
     };
</pre>
This is valid C/C++ code and when SWIG is run without -doxygen flag there is no error.
SWIG 4.0.0. beta1

**Comment by vadz** [comment]
I can confirm the problem, it can indeed be reproduced with just the following trivial patch to the test suite:
```diff
diff --git a/Examples/test-suite/doxygen_parsing_enums.i b/Examples/test-suite/doxygen_parsing_enums.i
index 5c48f4801..fcca2c551 100644
--- a/Examples/test-suite/doxygen_parsing_enums.i
+++ b/Examples/test-suite/doxygen_parsing_enums.i
@@ -29,7 +29,7 @@
        {
                SOME_ITEM_10, ///< Post comment for the first item
                SOME_ITEM_20, ///< Post comment for the second item
-               SOME_ITEM_30  ///< Post comment for the third item
+               SOME_ITEM_30, ///< Post comment for the third item
        };

 %}
```

Unfortunately fixing it doesn't look obvious, the part of the grammar in which `edecl_with_dox` appears is complicated and handling trailing comma in enum is mixed up with handling intermixed `#define`s, which really doesn't help...

**Comment by vadz** [comment]
Well, actually, while it still doesn't look obvious (at least to me) how to do it with the left recursion currently used in the `enumlist` production rule, it does look quite straightforward with right recursion -- and this allows us to simplify all these weird currently existing rules checking for all the combinations of pre- and post-comments around `edecl`.

Please see #1515 for the proposed fix.

**Comment by markok314** [comment]
I tested it and it works with my code.
