### ISSUE TITLE
SWIG core-dumps if @return doxygen directive is given in struct comment.

### ISSUE THREAD

**Issue by markok314** [swig/swig#1516]
The following snippet can be used to reproduce the problem:

<pre>
/**
 * My struct.
 *
 * @return this crashes SWIG
 */
struct MyStruct {
};
</pre>

I know it makes no sense to use @return directive in this context, but crashing is a bit too strong reaction.

**Comment by vadz** [comment]
Thanks, I can reproduce the crash with Python backend (but not with Java), looking...

**Comment by vadz** [comment]
[Here](#1517) is the trivial fix.

**Comment by vadz** [comment]
Rebased on d67c133c4a85c72f77bce245b7db4ae047202396 to avoid unrelated Travis test failures.
