### ISSUE TITLE
No properties generated in C# when wrapping C++ with multiple inheritance 

### ISSUE THREAD

**Issue by sandervrijders** [swig/swig#1524]
I have a class in C++ (A) that inherits from two base classes (B and C), both B and C have a public attribute: B has doubleProperty and C has intProperty. I am using swiginterface.i to wrap these base classes to a C# interface:

```
%interface_impl(B);
```

The resulting generated C# code outputs the following in the generated interface for B:

```
  void setDoubleProperty(double value);
  double getDoubleProperty();
```

The generated C# base class of B has the property:

```
  public double doubleProperty {
    set {
      ...
    } 
    get {
      ...
    } 
  }
```

So it appears that the generated C# interface of B has no C# properties generated but uses Java-style getters and setters. Is this a bug in SWIG or am I missing something in my SWIG interface file?

**Comment by wsfulton** [comment]
It's a bug. Fix coming up to not generate the getter and setters into the interface...
