### ISSUE TITLE
"EntryPointNotFoundException: Unable to find an entry point *****" in CSharp PInvoke class.

### ISSUE THREAD

**Issue by ryno1234** [swig/swig#1525]
I'm using Minwg/Msys/Swig to generate a wrapper for the MLT Framework library. I'm able to generate my .o file and link it to create a .dll.  So far, so good.

When referencing this newly generated .dll from my C# program, I'm getting an error 

`EntryPointNotFoundException: Unable to find an entry point named 'SWIGRegisterExceptionCallbacks_mlt' in DLL 'libmltsharp'.`

I looked at the generated .dll's header table and it looks like the export name is actually different: `SWIGRegisterExceptionCallbacks_mlt@44`.

I manually updated the DllImport as follows:

    // Old code - Doesn't work
    // [global::System.Runtime.InteropServices.DllImport("libmltsharp", EntryPoint="SWIGRegisterExceptionCallbacks_mlt")]

    // New code - works!
    [global::System.Runtime.InteropServices.DllImport("libmltsharp", EntryPoint="SWIGRegisterExceptionCallbacks_mlt@44")]

I no longer receive the error for this function. That said, I now get an error for the next function in line and would have to repeat the process.

I understand some about name mangling, but it appears that there is still at least some of that going on here.

For reference, the code I'm using to generate the .dll and C# library code is below:

	# Invoke swig
	mkdir src_swig
	swig -c++ -I../../mlt++ -I../.. -csharp -dllimport libmltsharp -outdir src_swig -namespace Mlt mlt.i || exit $?

	# Compile the wrapper
	${CXX} -v -fPIC -D_GNU_SOURCE ${CXXFLAGS} -c -pthread -I../.. mlt_wrap.cxx  || exit $?
	
	# Create the module
	${CXX} ${CXXFLAGS} -v -Wl,--export-all-symbols -shared mlt_wrap.o -L../../mlt++ -lmlt++ -L../../../../build/ -lmlt-6 -o libmltsharp.dll || exit $?

Any insight?

**Comment by ryno1234** [comment]
Update, I was able to solve this using the `-Wl,--kill-at` argument, but there seems to be more to this story, i.e. why did / does it work for others but not in my situation? Why did I have to use a workaround?

**Comment by ThibaultLesaunier** [comment]
Hi, 
Same problem for me. I'm using SWIG to generate a wrapper for C++ AR dll for Unity3D.
EntryPointNotFoundException: Unable to find an entry point named 'SWIGRegisterExceptionCallbacks_mymodule' in DLL 'myDLL'.

Weird because my code works with the previous version of SWIG 

Thanks

**Comment by ojwb** [comment]
@ryno1234 The `@`+number suffix is something to do with how symbols work in DLLs.  I don't remember all the gory details as I've pretty much only worked on Linux this century, but I think you can either reference a symbol by name or a slot number, and number is faster.  I think some toolchains/toolchain versions handle hiding the details better, so maybe that's why it works for some people/situations.

**Comment by ognyandim** [comment]
@ThibaultLesaunier I cannot find this flag in the [documentation](https://www.swig.org/Doc4.0/SWIGDocumentation.html)
Can you point the place where it is described? 
I am trying to solve this with swig 4.0.2

> Solve my problem using -DSWIG_CSHARP_NO_WSTRING_HELPER in my SWIG command line.

**Comment by ojwb** [comment]
It only seems to be documented in a comment in `Lib/csharp/wchar.i`:

```
/* -----------------------------------------------------------------------------
 * wchar.i
 *
 * Typemaps for the wchar_t type
 * These are mapped to a C# String and are passed around by value.
 *
 * Support code for wide strings can be turned off by defining SWIG_CSHARP_NO_WSTRING_HELPER
 *
 * ----------------------------------------------------------------------------- */
```
