### ISSUE TITLE
Segfaults in PHP 7.2 when wrapping resources to objects

### ISSUE THREAD

**Issue by pavel-charvat** [swig/swig#1527]
Hi, there seems to be a bug in SWIG_SetPointerZval(..., 2) causing segfaults in PHP7.2+, in our project later when releasing the wrapped object from memory.

From PHP sources:
```
/* This function requires 'properties' to contain all props declared in the     
 * class and all props being public. If only a subset is given or the class     
 * has protected members then you need to merge the properties separately by    
 * calling zend_merge_properties(). */                                          
ZEND_API int _object_and_properties_init(zval *arg, zend_class_entry *class_type, HashTable *properties ZEND_FILE_LINE_DC) /* {{{ */
```

This patch helped:
```
<       ALLOC_HASHTABLE(ht);
<       zend_hash_init(ht, 1, NULL, NULL, 0);
<       zend_hash_str_update(ht, "_cPtr", sizeof("_cPtr") - 1, &resource);
<       object_and_properties_init(z, ce, ht);
---
>       object_init_ex(z, ce);
>       zend_update_property(ce, z, "_cPtr", sizeof("_cPtr") - 1, &resource);
```

**Comment by ojwb** [comment]
If you want to propose a change, please open a PR with that change.  Then it undergoes CI testing automatically.

**Comment by ojwb** [comment]
It seems a PR was never opened for the proposed change.

I've tried it locally and the testsuite passes with it.  It also seems a plausible change.

@pavel-charvat We ideally like to add a regression test when fixing a bug - do you have a way to reproduce the segfault we could add to the testsuite?  I'm unable to reproduce your problem - without this change the testsuite passes, and my own SWIG-generated bindings work OK with PHP 7.2 and 7.3.

**Comment by ojwb** [comment]
@pavel-charvat Can you provide a reproducer for this?
