### ISSUE TITLE
swig issue using c++17

### ISSUE THREAD

**Issue by wolfviking0** [swig/swig#1538]
I am currently using swig with our application, and we would like to move to C++17.

Unfortunately when I use it, I receive this error : 

error: no type named 'unexpected_handler' in namespace 'std'     std::unexpected_handler old;

Any suggestion how I can fix this issue ? I am planning to try this macro _LIBCPP_ENABLE_CXX17 REMOVED FEATURES but I don't know if it's the best way to do it.

Thanks

**Comment by wsfulton** [comment]
This hasn't been spotted in our C++17 testing. Please give your compiler name and version, compiler flags anf operating system. This is presumably Ruby or Python too when using directors?

**Comment by wolfviking0** [comment]
Hi @wsfulton,

I am working on macOS High Sierra 10.13.6 
Here the info of the compiler:
        

> Apple LLVM version 10.0.0 (clang-1000.11.45.5)
>         Target: x86_64-apple-darwin17.7.0
>         Thread model: posix
>         InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by wolfviking0** [comment]
FYI It was easy to fix, I just add a condition if we are using c++17 and replace the code with 

std::terminate_handler for unexpected_handler and set_terminate  for set_unexpected.

**Comment by yarco** [comment]
We have the same issue here. Using C++17. How do you fix this again? Do you modify the generated file?

**Comment by wolfviking0** [comment]
@yarco, I made a patch in swig directly, I change those two files: 
https://github.com/swig/swig/blob/master/Lib/python/director.swg
https://github.com/swig/swig/blob/master/Lib/ruby/director.swg

And replace unexpected_handler by terminate_handler and set_unexpected by set_terminate. I am building all my stuff with c++17 so I directly change it. It will be better to use a condition like 

#if __cplusplus > 201402L
#endif

But it's not working on windows.

**Comment by wsfulton** [comment]
The director exception class `UnknownExceptionHandler` uses `std::unexpected_handler`. The suggested change to use `std::terminate_handler` instead could be an alternative. Instead I propose to remove the `UnknownExceptionHandler` class altogether to fix this C++17 incompatibility as SWIG does not generate any code that requires `UnknownExceptionHandler` and this class is not documented. Anyone who is actually using this class can simply add it into their own wrappers going forwards.

**Comment by wsfulton** [comment]
To help preventing these C++17 clang issues from arising in the future, I've added testing of xcode 10.2 with c++17 to our Travis environment in 959c2283818e76903901dddfea041d451eade686. This is actually a slightly later MacOS environment and clang version (10.0.1) to the one mentioned above, but it replicated the errors in this issue before I applied the fixes.
