### ISSUE TITLE
Java director connector not thread safe

### ISSUE THREAD

**Issue by Basskrapfen** [swig/swig#1539]
When using Swig to access C++ logic from an Android/Java app, there is a race condition when connecting a director with multiple threads.

The following logic is generated for a swig_connect_director method:
```C++
<snip>
  static jclass baseclass = 0 ;
  
  if (swig_set_self(jenv, jself, swig_mem_own, weak_global)) {
    if (!baseclass) {  // << totally not thread safe
      baseclass = jenv->FindClass("com/.../JavaClassName");
      if (!baseclass) return;
      baseclass = (jclass) jenv->NewGlobalRef(baseclass);
    }
<snip>
```
There are multiple ways how this can break if multiple threads enter the method initially. In my case, this leads to an SIGABRT - Abort message: 'java_vm_ext.cc:542] JNI DETECTED ERROR IN APPLICATION: use of deleted local reference 0x25'.

One way to fix it would be something like std::atomic (C++11) or changing baseclass to a local variable and losing performance. Is C++11 allowed for the generated Java-Swig adapter code?
I also tried to add some locking logic using typemap, but couldn't find good spots to add this.

It seems the issue was already discussed in the past:
https://sourceforge.net/p/swig/patches/295/

Thanks and best regards.

**Comment by wsfulton** [comment]
Should be fixed now, see issue #1862.
