### ISSUE TITLE
Memory Leak on SWIG Java

### ISSUE THREAD

**Issue by FATIHODACI** [swig/swig#1540]
Hi,

Nowadays I'm trying to change my c++ code to Java with using swig. I have a memory leak problem when I call a method which returns an object.

My C++ code looks like this :
<pre><code>class MyStruct{...}; 
class Consumer {
public:
MyStruct getOneStruct();
....
}
</code></pre>

In the beginning everything works fine but after a while when I call this code from java side many times, it causes a memory leak problem.

Java code:
<pre><code>...
MyStruct result;

while(true){
    result = consumer.getOneStruct();
}
</code></pre>

I tried **%newobject Consumer::getOneStruct();** directive but it didn't work :( 

Is there any solution for this problem?

**Comment by wsfulton** [comment]
It won't leak if your MyStruct class is leak free. Put a Thread.Sleep() call into your loop and you'll most likely find that it will stop leaking. Read about the Java garbage collector and finalizer thread prioriites if it doesn't make sense.

**Comment by FATIHODACI** [comment]
Ops, yes you are right. 
Thanks a lot. I'm not so good in java :)
