### ISSUE TITLE
Allow appending to a typemap

### ISSUE THREAD

**Issue by vadz** [swig/swig#1541]
Not for the first time, I'm running into a problem because I need to define some aspect of custom behaviour typemap for a wrapped class using a typemap which is already defined elsewhere to implement another aspect. I can't easily just define a typemap doing both things at once because the existing typemap is inside a reusable macro and all workarounds are really ugly (it doesn't help that the existing code is already quite complicated).

It would be really helpful if I could just write `typemap(cscode, append=1) MyClass { ... }` instead. And I'm not the first person wishing something like this were possible, see e.g. [this SO question](https://stackoverflow.com/questions/12103206/is-it-possible-to-add-text-to-an-existing-typemap-in-swig).

So would a patch implementing this be acceptable? And, if so, would you have any hints about the best way to do this? In particular, I'm not sure if this should be handled at the parser level or in `typemap.c`, what do you think?

**Comment by vadz** [comment]
Finally, this turned out to be surprisingly simple to do (I spent more time on trying to find an existing test to update than on writing the code), so I just went ahead and did it and it helps me a lot.

**Comment by wsfulton** [comment]
I replied to that SO question with 3 different solutions. Your problem may be subtly different, but I'd like to try and solve it using existing mechanisms as I don't really like the idea of appending to a typemap for a number of reasons I won't try and describe right now. Perhaps you can explain in more details what problem you are trying to solve particularly if my SO solution doesn't work?

**Comment by vadz** [comment]
The problem is pretty similar, but there are 2 macros involved instead of just 1. I'll give the details below, just in case you really need them, but I don't think they matter: the point is that the 2 macros know absolutely nothing about each other (and there is really no reason that they should), but using them together doesn't work because they both modify `cscode` typemap for the same type. This really ought to work, you (?) write in SWIG manual that typemaps are an example of aspect-oriented programming and here we have 2 completely orthogonal aspects that can't be customized together and it seems like a fundamental problem to me. I had no idea you saw it as something to preserve, and, without having access to the reasons that you don't give, I still can't fathom why?

In the most simplified form, if I have a macro which adds support for some `IFoo` to the type given as its parameter and another macro which adds support for some `IBar`, what's wrong with wanting to use both of them for a class that wants to implement both `IFoo` and `IBar`? None of the solutions you gave is going to help with this: I really need to modify `cscode` and I'm not reusing any existing typemap.

To give more details, I have `DEFINE_POLYMORPHIC` which is used to reproduce a naturally looking type hierarchy in C#, i.e. for `D : B` in C++ I want `b as D` work in C#. This macro contains many things to ensure that correctly typed C# objects are created, and among them there is
```
%typemap(cscode, append=1) BaseClass %{
    public static BaseClass CreateConcrete ## BaseClass(global::System.IntPtr cPtr)
    {
        ...
    }
```
(where `BaseClass` is one of the macro arguments). I also have another macro called `DEFINE_SERIALIZABLE` which does what it says on the tin, and, again, among other things, it contains
```
%typemap(cscode, append=1) Class %{
  public void GetObjectData(global::System.Runtime.Serialization.SerializationInfo info,
                            global::System.Runtime.Serialization.StreamingContext context) {
    info.AddValue("my_internal_field", InternalSerialize());
  }
```
where `InternalSerialize()` is some C++ function.

Without `append=1`, as implemented in #1545, I don't see any way of making this work without doing something really horrible, such as having `DEFINE_POLYMORPHIC_SERIALIZABLE` macro sharing pieces with the other ones (and this is even worse than it seems, because `SERIALIZABLE` macro exists in 2 versions, for the base and derived classes... I really shudder just at the thought of doing this).

**Comment by wsfulton** [comment]
You want to add different orthogonal pieces of code to one of a few broad sections of generated code. This is what %insert does, whereas typemaps control a whole (very small specific) section of code related to one type based on the pattern matching rules. That's fundamental. 

In hindsight, I'd say that adding the javacode/cscode (and a few other) typemaps were possibly a mistake (of mine) and a lack of understanding of what the more appropriate solution should have been. A typemap is nearly the right solution, but has the limitations you rightly point out. %insert would have been better.

`%proxycode` is just a` %insert("proxycode")` directive to add code to the proxy class code 'section' and it is modelled after `%pythoncode`. From what you've described, it looks like %proxycode should be the solution for your scenario. Both `%proxycode` and `%typemap("cscode")` generate code into the same section. However, there can only be one "cscode" typemap for a proxy class as typemaps overwrite each other, but `%proxycode%` can be used multiple times for a proxy class. Each time `%proxycode` is used, it adds code to the proxy class. Please try this out and let me know how you get on.

**Comment by vadz** [comment]
I understand your reasoning better now and I somewhat agree that there are clearly _some_ typemaps appending to which is undesirable/doesn't make sense (e.g. `out` or `csout`). However I still believe that it does make sense to append to many other ones, not just `cscode`. Another example, which I already wasted quite some time with, is `csinterfaces`, as it makes perfect sense to also have 2 macros each adding its own interface implemented by the class. It also would, presumably, allow to avoid having `csinterfaces_derived`. Similarly, there is `csattributes` where it again would make a lot of sense to allow appending to it -- except that simple textual append doesn't work for this one (but for me it's a reason to generalize "appending" to be smarter, not to disallow it completely).

So maybe it was indeed a mistake to use "typemap" term for both, but it looks very unlikely that this is ever going to change. And assuming we're stuck for using `%typemap` for `cs{code,interfaces,attributes}` and similar, I still believe it makes sense to allow appending to them. Maybe we should use some other SWIG statement, like `%typeadd`, instead of just an attribute to do it, but it would be really useful to have _some_ of doing this. Do you still disagree with this?

Getting back to my particular case, I don't really see how am I supposed to use `%proxycode`: I need to add a method to the generated class, but I can't insert `%proxycode` into the class declaration, which is in the C++ header that doesn't know anything about SWIG (and I'd very much like to keep it this way). The only possibility I see is to declare the class as `partial` in C# and reopen it inside the macro(s). Is this what you had in mind?

**Comment by lsd1994** [comment]
Can I use append to %typemap(csinterface) twice and make a class with mutil interface?

**Comment by ojwb** [comment]
@lsd1994
> Can I use append to %typemap(csinterface) twice and make a class with mutil interface?

Not currently as this `append` feature is still only a proposal.  If you want to wrap C++ multiple inheritance as C# interfaces then you might find `Examples/test-suite/minherit2.i` useful.

@vadz
> Getting back to my particular case, I don't really see how am I supposed to use `%proxycode`: I need to add a method to the generated class, but I can't insert `%proxycode` into the class declaration, which is in the C++ header that doesn't know anything about SWIG (and I'd very much like to keep it this way). The only possibility I see is to declare the class as `partial` in C# and reopen it inside the macro(s). Is this what you had in mind?

Looking at `Examples/test-suite/proxycode.i` the trick here seems to be to use `%proxycode` inside `%extend`:

```
%extend Proxy2 {
%proxycode %{
  public int proxycode2a(int i) {
    return i+2;
  }
%}
}
```

This solution is actually documented in the manual but only in the `Java.html` chapter (there's no mention of `%proxycode` in `CSharp.html`, and only a fleeting one in `D.html`, which doesn't seem ideal).

**Comment by lsd1994** [comment]
Thank you for your answer.

**Comment by ojwb** [comment]
A thought occurred to me - rather than a way to append to a typemap, we could perhaps support including the existing typemap in the new one.  We have `$typemap()` but that doesn't work in this situation:

```
Error: Likely recursive $typemap calls containing $typemap(cscode, Foo). Use -debug-tmsearch to debug.
```

However something like that but which expanded "eagerly" would  be a bit more flexible as you could prepend or wrap the existing typemap.

I suppose this fails the "doesn't make sense for all typemaps" test too, but then not all operations we support make sense for all the things they can be applied to - for example, as above `$typemap` doesn't make sense when used on the same typemap you're defining.

Either way, it would be good to resolve this issue and the linked PR by either deciding the answer is just "**NO**" or coming up with a way to achieve this that is acceptable to both parties.  This has been open for more than 4 years now, and we have far too many stalled issues clogging up the bug tracker.

**Comment by vadz** [comment]
I'm closing this as `%proxycode` inside `%extend` indeed provides a sufficiently good workaround (thanks Olly!), but I still believe that it would be useful to have some way of constructing the final typemap value from the existing one.

Making `$typemap(foo)` return the previously defined value of the typemap when expanding it from `%typemap(foo)` itself looks like a good idea, but I won't be doing this unless it's approved in advance this time.

**Comment by ojwb** [comment]
> I'm closing this as `%proxycode` inside `%extend` indeed provides a sufficiently good workaround (thanks Olly!), but I still believe that it would be useful to have some way of constructing the final typemap value from the existing one.
> 
> Making `$typemap(foo)` return the previously defined value of the typemap when expanding it from `%typemap(foo)` itself looks like a good idea, but I won't be doing this unless it's approved in advance this time.

There's already #2521 open for that anyway.
