### ISSUE TITLE
Segfault in doxygen code block with empty line

### ISSUE THREAD

**Issue by mcfarljm** [swig/swig#1548]
If an empty line appears within a doxygen `code` block that is itself inside of an `\if` command, it produces a segafault.  To recreate, simply add an empty comment line to test case doxygen_basic_translate.i after line 59:
<pre>
/**
 * A test of some mixed tag usage
 * \if CONDITION
 * This \a code fragment shows us something \.
 * \par Minuses:
 * \arg it's senseless
 * \arg it's stupid
 * \arg it's null
 *
 * \warning This may not work as expected
 * \code
 * int main() { while(true); }
 *
 * \endcode
 * \endif
 */
</pre>

I recreated this with a local build of 9829bdf5b.  Some relevant backtrace info:
<pre>
#0  0x00007ffff772ccbb in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /lib64/libstdc++.so.6
#1  0x00000000004316b3 in Token (this=0x7fffffffca20)
    at Doxygen/doxyparser.h:52
#2  DoxygenParser::parse (this=this@entry=0x798360, endParsingIndex=..., 
    tokList=std::vector of length 84, capacity 128 = {...}, 
    root=root@entry=true) at Doxygen/doxyparser.cxx:964
#3  0x0000000000432ed2 in DoxygenParser::createTree (this=this@entry=0x798360, 
    node=node@entry=0xc285e0, documentation=documentation@entry=0xc28500)
    at Doxygen/doxyparser.cxx:998
#4  0x000000000044e993 in PyDocConverter::makeDocumentation (this=0x798350, 
    n=0xc285e0) at Doxygen/pydoc.cxx:825
</pre>

I'm currently working on some enhancements to handling of code blocks, so may try and look into this.  Not a priority for me because I don't use `\if` statements in doxygen comments, but it is a segfault.

Suspect that the empty line is throwing the parser off in general, because even without the `\if` statement, the empty line within a code block leads to a warning "Unexpected end of Doxygen comment encountered".

**Comment by mcfarljm** [comment]
I have a fix for this and plan to submit after PR #1547 is merged.

**Comment by wsfulton** [comment]
Closed in #1578, thanks.
