### ISSUE TITLE
Python3 possible dangling (lost) shared_ptr causing memory leak

### ISSUE THREAD

**Issue by Dekken** [swig/swig#1549]
Hi there folks

I'm trying to debug https://github.com/X-DataInitiative/tick/

and I'm watching "shared_ptr<T>::use_count" before and after calling this function

```
virtual void set_model(std::shared_ptr<TModel<T, K> > &model);
```
https://github.com/X-DataInitiative/tick/blob/master/lib/swig/tick/solver/sto_solver.i#L57

before calling 

```
SWIGINTERN PyObject *_wrap_SVRGDouble_set_model(PyObject *SWIGUNUSEDPARM(self), PyObject *args) {
```

use_count is 1, as it should be, but it's then 2 in _wrap_SVRGDouble_set_model before we even call sto_solver::set_model where it becomes 3

it should only ever be 2 I wager

**Comment by Dekken** [comment]
I've dug a little deeper, and made another version of 

```
void set_model(std::shared_ptr<TModel<T, K> > &model);
```

with a concrete non-virtual parameter, and it seems fine.

**Comment by Dekken** [comment]
example

```
  void set_model(const std::shared_ptr<TModel<T, K>> &model) override; // not fine

  void set_model_sub(const std::shared_ptr<TModelSCCS<T>> &_model) { // fine
    set_model(_model);
  }
```

**Comment by wsfulton** [comment]
Can you please produce a small standalone testcase reproducing this behaviour including the %template statemtns and definitions for both TModel and TModelSCCS.

**Comment by Dekken** [comment]
I believe I have resolved this, the solver module did not have the declaration of 

```
%shared_ptr(TModel<double, double>);
%shared_ptr(TModel<float, float>);
```

and as a result we had 
```
SWIG_ConvertPtr
```

when we needed
```
SWIG_ConvertPtrAndOwn
```

Could we potentially get a warning for things like this?
These are separate modules, and it's not so obvious how much visibility is required between them
