### ISSUE TITLE
Swig 3 -> Swig 4 regression in the implicit_conv code for Python

### ISSUE THREAD

**Issue by adl** [swig/swig#1553]
I have been debugging a project of mine in which I have a function `spot::formula_Or(const std::vector<spot::formula>&)` with Python bindings. 
With Swig 3, I was able to call this function by passing either a list or a tuple: both were converted to vectors.  After upgrading to Swig 4, I noticed that passing a tuple was not working anymore.

I have found that the culprit is [commit 7c034ead](https://github.com/swig/swig/commit/7c034ead322faa79ad7b94fe72250ce8a4fd5848#r33755181) which applied the following change to `pyrun.swg`:

```patch
 /* A functor is a function object with one single object argument */
-#if PY_VERSION_HEX >= 0x02020000
-#define SWIG_Python_CallFunctor(functor, obj)          PyObject_CallFunctionObjArgs(functor, obj, NULL);
-#else
-#define SWIG_Python_CallFunctor(functor, obj)          PyObject_CallFunction(functor, "O", obj);
-#endif
+#define SWIG_Python_CallFunctor(functor, obj)          PyObject_CallFunction(functor, (char*)"O", obj);
```

I think this change is backwards.  You want to keep `PyObject_CallFunctionObjArgs` documented as faster than `PyObject_CallFunction` for this case.  Also `PyObject_CallFunction` contains some [backward compatibility hacks](https://github.com/python/cpython/blob/a747c3a5edf21fa5670bc30f5e1d804de89ebf62/Objects/call.c#L940) that inline tuples, causing my issue.

**Comment by ojwb** [comment]
Oops, thanks for spotting.  I've reinstated the other version of the code from before.
