### ISSUE TITLE
[Java] JNI ERROR (app bug): local reference table overflow (max=512)

### ISSUE THREAD

**Issue by Pa4o85** [swig/swig#1555]
I have director class and method returning std::string. This method is called in a loop from the native code. At some point this error is thrown. It seems that jstring result reference is not deleted. This is how I fixed it - adding  jenv->DeleteLocalRef($input); in %typemap(directorout) string in std_string.i. Not sure it's a bug in the swig, or it's done this way by purpose.

`%typemap(directorout) string 
%{ if(!$input) {
     if (!jenv->ExceptionCheck()) {
       SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
     }
     return $null;
   } 
   const char *$1_pstr = (const char *)jenv->GetStringUTFChars($input, 0); 
   if (!$1_pstr) return $null;
   $result.assign($1_pstr);
   jenv->ReleaseStringUTFChars($input, $1_pstr);
   jenv->DeleteLocalRef($input); %}`

**Comment by nioncode** [comment]
This is actually mentioned in the documentation and seems to be working as intended: http://www.swig.org/Doc4.0/SWIGDocumentation.html#Java_directors_typemaps

 > The Swig::LocalRefGuard class should be used in directorin typemaps for newly allocated objects. It is used to control local reference counts ensuring the count is decremented after the call up into Java has completed. Its destructor simply calls jenv->DeleteLocalRef(obj) on the obj passed in during construction.

This is only documented for the `directorin` typemap, but probably applies the same way for the `directorout` typemap. Can somebody confirm this? If this is the case, then it should also be added to the `directorout` typemap documentation.

**Comment by ojwb** [comment]
The sequence for how these typemaps are used in the generated C++ code is like so:

* for each parameter:
  * «expanded directorin typemap to marshall parameter from C++ to Java»
* «call into java»
* «expanded directorout typemap to marshall return value from Java to C++»

So `Swig::LocalRefGuard` shouldn't be relevant in `directorout` as it should not be allocating Java objects, but rather taking a Java object and converting it to C++.
