### ISSUE TITLE
[MzScheme] %typemap(argout) arguments are wrong in second replacement

### ISSUE THREAD

**Issue by cwbowron** [swig/swig#1559]
I'm using the homebrew version of SWIG 4.0.0:

I'm seeing an error when trying use `%typemap(argout)` to generate code to convert between Racket (MzScheme) floating point vectors to C++ `float *`. My use case requires me to pass in two buffers, and I see an error in the generated code for the second conversion. It seems to be getting the wrong value for `$input`. I checked the known issues and could not find a report of this. If the error is in my typemap, I apologize. 

My typemaps:

```
%typemap(in) float* {
   const size_t size = SCHEME_FLVEC_SIZE($input);
   $1 = new float[size];
}

%typemap(argout) float* {
   const size_t size = SCHEME_FLVEC_SIZE($input);
   double * elts = SCHEME_FLVEC_ELS($input);
   for (int i = 0; i < size; i++) {
      elts[i] = $1[i];
   }
}

%typemap(freearg) float* {
   delete [] $1;
}

```

The generated code for my function call looks like this:

```
  {
    const size_t size = SCHEME_FLVEC_SIZE(argv[3]);
    arg4 = new float[size];
  }
  {
    const size_t size = SCHEME_FLVEC_SIZE(argv[4]);
    arg5 = new float[size];
  }
  result = (arg1)->fillAudioBuffers(arg2,arg3,arg4,arg5);
  {
    uint32_t * resultptr;
    resultptr = new uint32_t((uint32_t &) result);
    values[0] =  SWIG_NewPointerObj (resultptr, SWIGTYPE_p_uint32_t, 1);
  }
  {
    const size_t size = SCHEME_FLVEC_SIZE(argv[4]);
    double * elts = SCHEME_FLVEC_ELS(argv[4]);
    for (int i = 0; i < size; i++) {
      elts[i] = arg4[i];
    }
  }
  {
    const size_t size = SCHEME_FLVEC_SIZE(argv[4]);
    double * elts = SCHEME_FLVEC_ELS(argv[4]);
    for (int i = 0; i < size; i++) {
      elts[i] = arg5[i];
    }
  }
  {
    delete [] arg4;
  }
  {
    delete [] arg5;
  }
```

You can see in the generated code, the second generated `argout` block is using `argv[4]` instead of `argv[5]`. I don't know if it happens in other backends. 

My work-around is to just directly use the `argv[$argnum]` reference, which is fine for my purposes, but I wanted to report in case others have issues.

```
%typemap(argout) float* {
   const size_t size = SCHEME_FLVEC_SIZE(argv[$argnum]);
   double * elts = SCHEME_FLVEC_ELS(argv[$argnum]);
   for (int i = 0; i < size; i++) {
      elts[i] = $1[i];
   }
}
```

**Comment by wsfulton** [comment]
I've just fixed it for swig-4.0.1. Same problem was present in OCaml too.
