### ISSUE TITLE
Option to disable function annotations when -py3 option is used

### ISSUE THREAD

**Issue by gieseanw** [swig/swig#1561]
At the moment, the `-py3` option unconditionally enables function annotations. I'd like to be able to turn on Python 3, but turn off function annotations. In my workflow, I'm generating stub files automatically via another process. These type hints conflict with the annotations, and the annotations are taking precedence.

Looking at source/Modules/python.cxx, the function `make_pyParmList` sets a boolean 

    bool funcanno = py3 ? true : false;

And this is passed to `make_autodocParmList`

It seems like perhaps another python command line option could be provided that will turn them off. Perhaps it should be handled by the "autodoc" directive in some way?

For now, I'm relegated to post-processing the generated .py files to remove the annotations.

**Comment by wsfulton** [comment]
I actually meant to have function annotations turned off by default when using -py3 for the swig-4.0.0 release and am frustrated now that I didn't get round to it. I suggest a new command line option, `-noannotations` which will suppress the function annotations from being generated when using -py3. In swig-4.1, we can deprecate this option if we hopefully have a proper type hint solution, please see #735.

**Comment by wsfulton** [comment]
@gieseanw, why don't you just drop the `-py3` option? It hardly changes anything else, or is there something from this option that you need?
