### ISSUE TITLE
C# `set` code generation does not support `int`

### ISSUE THREAD

**Issue by nickwinder** [swig/swig#1568]
C# `set` code generation does not support int, or any type other than `string`. 

# Details
When trying to define a `std::set` with type of `int` the C# generated is incorrect because the `Add` method is hardcoded with type of `string` as seen 
https://github.com/swig/swig/blob/d3ae85ee734ec701cea0f67f0ccf3d187199819c/Lib/csharp/std_set.i#L33

When changing this method to support `int` or any other non-nullable type further issues are produced. This is because the type is defined as non-nullable. 
https://github.com/swig/swig/blob/d3ae85ee734ec701cea0f67f0ccf3d187199819c/Lib/csharp/std_set.i#L195
but set to null in 
https://github.com/swig/swig/blob/d3ae85ee734ec701cea0f67f0ccf3d187199819c/Lib/csharp/std_set.i#L202

Further to this when returning the type from the `Current` method it should be cast after a null check is done. 
https://github.com/swig/swig/blob/d3ae85ee734ec701cea0f67f0ccf3d187199819c/Lib/csharp/std_set.i#L215

# Reproduce

For simple reproduction please see example repo.
https://github.com/nickwinder/swig-c-sharp-set-bug

### Interface
```
%module Set
%{
#include "cSharpIntSet.hpp"
%}

%include "std_set.i"

%include "cSharpIntSet.hpp"

namespace std {
    %template(set_int) set<int>;
};

```

### Header
```
#pragma once

#include <set>

class cSharpIntSet {
  std::set<int> getSet();
};
```

### Source
```
#include "cSharpIntSet.hpp"

std::set<int> cSharpIntSet::getSet() { return std::set<int>(); }
```

**Comment by vadz** [comment]
As you can probably see, this typemap was written as a generalization of custom typemaps for `std::set<std::string>` and it hasn't been fully generalized to work with the other types, sorry about this.

I'll try to fix it, but I'm not sure how to deal with non-nullable types, would you have any ideas about this? I guess the best would be to use `T?` for `currentObject`, but I don't think we have any typemap that would allow doing this...

**Comment by nickwinder** [comment]
> sorry about this.
All good, no need to apologize. 

> I guess the best would be to use T? for currentObject

For a simple test I did the something similar, so I believe line 195
```diff
- private $typemap(cstype, T) currentObject;
+ private $typemap(cstype, T)? currentObject; 
```
and line 215
```diff
- return currentObject; 
+ return ($typemap(cstype, T)) currentObject; 
```
I do not have the dev environment setup for SWIG as of yet, so I'm unable to test this fully. 
WDYT?

**Comment by vadz** [comment]
The trouble is that we can't use `Foo?` for the already nullable types (including `string`), so if we change it like this, `set<string>` won't work correctly any longer.

A trivial solution is to have 2 typemaps, one for all the primitive types and another for all the rest, but this is quite ugly and I'd like to find some better solution.

Also, while this is about C#, I've already checked the situation for Java and wrapping `set<int>` doesn't work there neither because it is `AbstractSet<Integer>` on the Java side, yet methods such as `add()` are still defined as taking `int`. So it looks like we have to do something different for the primitive and non-primitive types there too (and I also don't know what).

**Comment by nickwinder** [comment]
Yeah that's a good point. 

Looking at `Lib/csharp/std_vector.i` it seems `object` is used instead. 
https://github.com/swig/swig/blob/7b0402f89bb034a60041c1330dcc62ff6b5cc95a/Lib/csharp/std_vector.i#L145

https://github.com/swig/swig/blob/7b0402f89bb034a60041c1330dcc62ff6b5cc95a/Lib/csharp/std_vector.i#L164

I assume this could be the solution. `object` is always nullable.

**Comment by wsfulton** [comment]
Using `object` seems the way forward as this approach has been used for `std::vector` for a while now without any reported problems.

**Comment by vadz** [comment]
OK, thanks, I'll update the code to use `object` (although I still wonder if adding some `csnullabletype` typemap and using it here wouldn't be more elegant...).

**Comment by vadz** [comment]
Sorry for the delay, but I've finally created #1583 with the trivial changes fixing this.
