### ISSUE TITLE
Support __VA_OPT__

### ISSUE THREAD

**Issue by roth01** [swig/swig#1574]
Hi,

I'm using c macros to generate variadic number of arguments in custom swig macro. In version 4.0.0 it stopped working correctly for definitions without arguments. Look at an example below (configuration c++ to java).

```
#define COUNT_ARGS(...) COUNT_ARGS_(__VA_ARGS__,3,2,1,0)
#define COUNT_ARGS_(_1,_2,_3,cnt,...) cnt

%define %test_args(...)

%typemap(in) long {
    // Number of Arguments
    COUNT_ARGS(__VA_ARGS__)
}

%enddef

%test_args(); // -> incorrect value 1 should be 0
//%test_args(a); // -> correct value 1
//%test_args(a, b); // -> correct value 2

void test(long);
```
Generated cpp function for problematic case with comment on incorrect value:
```
SWIGEXPORT void JNICALL Java_TestSwigJNI_test(JNIEnv *jenv, jclass jcls, jint jarg1) {
  long arg1 ;
  (void)jenv;
  (void)jcls;
  {
    // Number of Arguments
    1 --> incorrect value
  }
  test(arg1);
}
```

**Comment by wsfulton** [comment]
Could be due to #1111, but have not checked.

**Comment by roth01** [comment]
I can confirm that the issue is caused by change you have mentioned.

**Comment by wsfulton** [comment]
@ojwb, any chance you can look at this regression?

**Comment by ojwb** [comment]
Will try, but quite busy right now.

**Comment by ojwb** [comment]
I have taken a look - this doesn't seem to actually be a regression as with SWIG 3.0.12 it fails to process at all:

```
$ swig -module x -c++ -java test.i
test.i:13: Error: Unknown directive '%test_args'.
$ swig -version

SWIG Version 3.0.12

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
```

3.0.12 is predecessor release to 4.0.0, and doesn't contain the fix for #1111:

```
$ git tag --contains 59ebe27
rel-4.0.0
rel-4.0.0-beta1
```

And in fact, this doesn't seem to be supported by current C or C++ standards, as testing with GCC 8.3.0 I don't get `0` in either C or C++ modes:

```
$ cat test.cc
#define COUNT_ARGS(...) COUNT_ARGS_(__VA_ARGS__,3,2,1,0)
#define COUNT_ARGS_(_1,_2,_3,cnt,...) cnt

#define test_args(...) COUNT_ARGS(__VA_ARGS__)

void test0() {
    test_args();
}

void test1() {
    test_args(a);
}

void test2() {
    test_args(a,b);
}

void test3() {
    test_args(a,b,c);
}
olly@gemse:~/git/swig/gh1574$ g++ -std=c++17 -E test.cc 
# 1 "test.cc"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "test.cc"





void test0() {
    1;
}

void test1() {
    1;
}

void test2() {
    2;
}

void test3() {
    3;
}
olly@gemse:~/git/swig/gh1574$ gcc -x c -std=c11 -E test.cc 
# 1 "test.cc"
# 1 "<built-in>"
# 1 "<command-line>"
# 31 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 32 "<command-line>" 2
# 1 "test.cc"





void test0() {
    1;
}

void test1() {
    1;
}

void test2() {
    2;
}

void test3() {
    3;
}
```

It looks like the submitter should be using `__VA_OPT__(,)` here, which is apparently due in C++2a and also supported by GNU C and C++ as an extension: https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html

SWIG doesn't support `__VA_OPT__` currently, so I guess we could morph this into a feature request to support it.  I don't plan to work on that though.

**Comment by ojwb** [comment]
With the fix I've just pushed (which should be in SWIG 4.3.0) the above example works if adjusted to make use of the elision of comma before `##__VA_ARGS__` when `__VA_ARGS__` is empty:

```
#define COUNT_ARGS(...) COUNT_ARGS_(X,##__VA_ARGS__,3,2,1,0)
#define COUNT_ARGS_(X,_1,_2,_3,cnt,...) cnt

%define %test_args(...)

%typemap(in) long {
    COUNT_ARGS(__VA_ARGS__) // Number of Arguments
}

%enddef

%test_args();
%test_args(a);
%test_args(a, b);
%test_args(a, b, c);

void test(long);
```

```
$ ../preinst-swig -python -E hashhash.i|grep 'Number of Arguments'
    0 // Number of Arguments
    1 // Number of Arguments
    2 // Number of Arguments
    3 // Number of Arguments
```

Ideally we should also support `__VA_OPT__` as it's the standardised solution to this whereas `##__VA_ARGS__` is a GCC extension.

**Comment by ojwb** [comment]
I spotted a neat way to implement `__VA_OPT__` and I have a working patch.  I need to update the docs and slot my test interface file into the testsuite.
