### ISSUE TITLE
Debian 8 Swig3 no -php7 option and generated code does not compile

### ISSUE THREAD

**Issue by sbsrouteur** [swig/swig#1577]
Hello,

I started the upgrade of a legacy system using a PHP extension for php5.5
on a debian jessie system.

I upgraded php to v7, and SWIG to v3, but the makefile for the extension
does not work anymore.
The original swig command still work (swig V2 with -php5) but won't load
the generated extension. (complains about module version not matching)

When running the updated building script with the following command :
vlm@...:~/vlmcode/lib/vlm-c/php$ swig3.0 -php7 -outdir . -o vlmc_wrap.c
../vlmc.i
swig error : Unrecognized option -php7
Use 'swig -help' for available options.

php7 option is unknown. Am I misisng a package?

When running with -php option, the code gets generated but will not
compile:
vlm@...:~/vlmcode/lib/vlm-c/php$ swig3.0 -php -outdir . -o vlmc_wrap.c
../vlmc.i
vlm@...:~/vlmcode/lib/vlm-c/php$ gcc `php-config --includes` -fpic -c
vlmc_wrap.c
vlmc_wrap.c: In function ‘SWIG_landfill’:
vlmc_wrap.c:789:51: error: ‘rsrc’ undeclared (first use in this function)
 static ZEND_RSRC_DTOR_FUNC(SWIG_landfill) { (void)rsrc; }
                                                   ^
vlmc_wrap.c:789:51: note: each undeclared identifier is reported only once
for each function it appears in
vlmc_wrap.c: In function ‘SWIG_ZTS_SetPointerZval’:
vlmc_wrap.c:839:36: warning: passing argument 1 of ‘zend_lookup_class’ from
incompatible pointer type
         result = zend_lookup_class(classname, SWIG_PREFIX_LEN +
type_name_len, &ce TSRMLS_CC);

I updated php-config for php7 and my current includes list is :
vlm@...:~/vlmcode/lib/vlm-c/php$ php-config --includes
-I/usr/include/php/20180731 -I/usr/include/php/20180731/main
-I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend
-I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib

The above folders exist and have files in.

Thank you for your help.

**Comment by sbsrouteur** [comment]
FWIW, I downloaded and built swig4, it fixed my issue. Code compiled without issue again, and extension now loads in php7.

**Comment by wsfulton** [comment]
Closing as reported fixed.
