### ISSUE TITLE
AOT support for C# delegates

### ISSUE THREAD

**Issue by JessHolle** [swig/swig#1579]
This is related to https://github.com/swig/swig/issues/1165, but a less ambitious request.

I'm looking to be able to pass C# delegates to C++ APIs that take std::functions (with appropriate corresponding arguments), shared_ptr's to single-abstract-method C++ classes (again with appropriate arguments), or some such -- but under the constraints of IL2CPP's AOT.  In other words, I just want the simplest callback delegation with instance state.  All the general purpose C++ subclass handling, etc, would be awesome, but ... I'll take what I can get.

Is there a way to accomplish this lurking somewhere that I don't quite understand?  I suspect there's got to be a way to use a static C# processing routine, stash a reference to the target C# object and make the former use the latter.  I'm just new to the intricacies of SWIG -- and missing how to approach this other than the big bang of https://github.com/swig/swig/pull/1262, which would seemingly solve my problem but seems to be in a state of permanent limbo.

**Comment by ojwb** [comment]
`std::function` is C++11 so tagging accordingly.

Can't answer the question here though, except to note that if you can hand code handling such a parameter you can probably use a custom typemap to generate that code.

**Comment by ojwb** [comment]
We have #341 for `std::function` in general.  It doesn't seem useful to have per-language issues open for features we don't currently support for any target language, so closing this as a duplicate.
