### ISSUE TITLE
Flatten class hierarchy

### ISSUE THREAD

**Issue by equeim** [swig/swig#1581]
Often I don't need proxy classes for superclasses, I only want their methods. It would be nice if SWIG supported flattening class hierarchy, e.g. for this C++ code:
```C++
class Foo
{
public:
    void one();
    virtual void two();
    virtual void three();
}

class Bar : public Foo
{
public:
    void two() override;
    void three() override;
}
```
if I enabled some feature in the interface file, SWIG wouldn't generate Foo proxy class, and Bar Java class would look like this:
```Java
public class Bar {
    public void one();
    public void two();
    public void three();
}
```

**Comment by vadz** [comment]
You should be already able to ignore `Foo` to achieve this, I think.

**Comment by equeim** [comment]
If I ignore Foo, SWIG won't generate wrapper method for one().

**Comment by ojwb** [comment]
This works:

```
%extend Bar {
    using Foo::one;
}
%ignore Foo;
```

It does require manually listing all the methods you want to do this to though, which might be impractical.

Maybe there's a way to do it for all methods, but I can't think of one.
