### ISSUE TITLE
doxygen: Warning 560: Unknown Doxygen command: } & param[out]

### ISSUE THREAD

**Issue by q-p** [swig/swig#1585]
We use the following syntax for grouping methods together that implement a particular interface. Swig complains with `Warning 560: Unknown Doxygen command: }.`. Weirdly, it doesn't complain about the opening `@{` but only the closing one. It might be ok to just ignore the `@}`.

```c++
  /// @name SomeInterface
  /// @{
     // ... some methods that implement SomeInterface
  /// @}
```

The following spellings of the `param` command are accepted as valid by doxygen  (and are even present as examples in its documentation). It would be nice if SWIG understood these variations as well:
```c++
/**
 * @param[in] foo
 * @param[out] foo
 * @param[inout] foo
 * @param[in,out] foo
 */

As it is, they lead to `Warning 560: Unknown Doxygen command: param[out].` from SWIG.

**Comment by mcfarljm** [comment]
PR #1608 adds support for the doxygen ```param``` options.

**Comment by wsfulton** [comment]
Closing as #1608 fixes this. Note that http://www.doxygen.nl/manual/commands.html#cmdparam does not list `@param[inout]` as valid, in contrast to this original bug report.
