### ISSUE TITLE
Python 3.8 removed _PyObject_GC_UNTRACK

### ISSUE THREAD

**Issue by gicmo** [swig/swig#1586]
See fedora bug [rhbz#1705450](https://bugzilla.redhat.com/show_bug.cgi?id=1705450), where renderdoc fails to compile with Python 3.8 beta 2 because the generated code is using [`_PyObject_GC_UNTRACK`](https://docs.python.org/3/c-api/gcsupport.html#c._PyObject_GC_UNTRACK), which is deprecated since 3.6 and got remove in 3.8.

**Comment by wsfulton** [comment]
Fixed now, see #1587.
