### ISSUE TITLE
Python autodoc typemap

### ISSUE THREAD

**Issue by maufl** [swig/swig#1592]
Hi, I'm generating a Python wrapper for a C++ library and so far it works great. I'm currently trying to generate documentation using `%feature("autodoc", "1");`. It works but often uses C++ types in the documentation.

I can't figure out how to customize the types used in the generated documentation. I tried `%typemap(doctype) std::optional<float> "Optional[float]";` and `%typemap(doc) std::optional<float> "Optional[float]";` but both are not applied.

From the documentation and the `pydocs.swg` file it's not clear to me, when which of the type maps will be applied. Can somebody explain how `typemap(doc)` and `typemap(doctype)` are used?

**Comment by ojwb** [comment]
Those two typemaps are used by the doxygen support, which is different to the older `autodoc` feature:

```
$ cat test.i
%module x
%typemap(doctype) std::optional<float> "Optional[float]";
/** Do something.
 *
 * @param y How much to do.
 *
 * @return A value, maybe.
 */
std::optional<float> x(std::optional<float> y);
$ swig -c++ -doxygen -python test.i
$ tail x.py 

    :type y: Optional[float]
    :param y: How much to do.

    :rtype: Optional[float]
    :return: A value, maybe.
    """
    return _x.x(y)


```

I don't think there's a way to map names of types with the `autodoc` feature.

**Comment by wsfulton** [comment]
See https://github.com/swig/swig/issues/735#issuecomment-455872289 for a summary of deficiencies and what needs doing.
