### ISSUE TITLE
Python -builtin constructors silently ignore keyword arguments

### ISSUE THREAD

**Issue by d-b-w** [swig/swig#1595]
#Summary

I generate my SWIG wrappers using the -builtin option, but not -keyword. This generates wrappers for constructors that silently ignore any keyword arguments passed to them. This means that my users may be creating objects that are not what they expected, and have no warning other than differences in behavior, potentially far away.

#Example

For example, using SWIG 3.0.12 to generate wrappers for demo.h:

    #ifdef SWIG
    %module demo
    #endif

    class Demo {
    public:
        Demo() {}
        int function() {return 3;}
    };

with the command `swig -Werror -DPY_MAJOR_VERSION=3 -python -py3 -c++ -Werror -builtin -o demo_wrap.cxx demo.h`, I get the following constuctor/tp_init:

    SWIGINTERN int _wrap_new_Demo(PyObject *self, PyObject *args) {
      PyObject *resultobj = 0;
      Demo *result = 0 ;

      if (args && PyTuple_Check(args) && PyTuple_GET_SIZE(args) > 0) SWIG_exception_fail(SWIG_TypeError, "new_Demo takes no arguments");
      result = (Demo *)new Demo();
      resultobj = SWIG_NewPointerObj(SWIG_as_voidptr(result), SWIGTYPE_p_Demo, SWIG_BUILTIN_INIT |  0 );
      return resultobj == Py_None ? -1 : 0;
    fail:
      return -1;
    }

If I call this constructor from Python:

    import demo
    d = demo.Demo(param='i thought there was a keyword argument')

`d` is constructed successfully, and `param` is silently ignored. I believe that I should get the same message that I would get when calling `d.act(param='nope')`: `TypeError: act() takes no keyword arguments`.

#Suggested fix

I think that _wrap_new_Demo's prototype should be `int _wrap_new_Demo(PyObject *self, PyObject *args, PyObject *kwargs)` even when not using keyword arguments in the wrapper, and there should be a TypeError if kwargs is non-empty.

**Comment by TobiasWinchen** [comment]
hi - our project is also affected by this problem. A real problem is that not only non existing parameters are ignored, but also existing parameters are ignored when passed as keyword argument. Is there a workaround for this issue?

**Comment by wsfulton** [comment]
Confirmed. I'm working on a fix.

**Comment by d-b-w** [comment]
Thanks! This would make converting to use -builtin much safer, because converting to -builtin often requires dropping keyword support.

**Comment by wsfulton** [comment]
I've fixed it just when using `-builtin -keyword` to begin with. I'll look at just `-builtin` next. The argument handling code is unfortunately fairly complex.

**Comment by wsfulton** [comment]
Closed by 67e8334
