### ISSUE TITLE
Automatic renaming

### ISSUE THREAD

**Issue by rokups** [swig/swig#1600]
I am looking into adding a feature that automatically renames all parsed APIs using idiomatic naming scheme of target language. So far im struggling to figure out where i should make it happen. My understanding is that renaming should happen during parsing source code. `Swig_name_rename_add()` looks like an obvious suspect. Maybe i should execute this function for every parsed symbol? That way i would provide default renaming while user may override it in their template files later on. But where should i look into renaming all symbols? Please point me the right way.

Thanks!

P.S. Posting github issue because sending messages to mailing list fails with following:
>  There was a problem delivering your message to swig-devel@lists.sourceforge.net. See the technical details below, or try resending in a few minutes. 
> The response from the remote server was:
> 550 This message scored 19.9 points. Congratulations!

**Comment by vadz** [comment]
You can use regex `%rename` for this, e.g. I use `%rename("%(regex:/^m_([A-Za-z0-9_]+)/\\u\\1/)s",%$ismember) "";` to rename C++ `m_foo` to `Foo` in C#.

**Comment by rokups** [comment]
I am perpetually amazed by SWIG. Not only this is exactly what i needed - this is way better than anything i would have came up with. Thank you 👍
