### ISSUE TITLE
Naming an argument for a template function with the same name as the function causes an error

### ISSUE THREAD

**Issue by theartful** [swig/swig#1602]
This bug appeared to us after using swig 4.0.0, and wasn't there with swig 3. If an argument of a template function "func" is named as the same name of the function, it's renamed to "func\<(T)\>" for each instantiation, causing errors.

Example:

example.h
```C++
template <typename T>
void labels(T labels) {}
```
example.i
```
%module example

#include "example.h"
%include "example.h"

%template(IntLabels) labels<int>;
```
compiling using `swig -java -c++ example.i`

example.java
```Java
public class example {
  public static void IntLabels(int labels<(int)>) {
    exampleJNI.IntLabels(labels<(int)>);
  }
}
```

**Comment by wsfulton** [comment]
git bisect points to b9350614b5956ffb8664b79ffeba38986b3678ed being the cause of this. I'll take a look at fixing this regression.
