### ISSUE TITLE
C++ to C# : override #define constants

### ISSUE THREAD

**Issue by jano42** [swig/swig#1605]
I'm relatively new to swig, and your making great job !
I'm using swig  from C++ to C#.

All my numeric defines are typed as integer
`#define MYCONSTANT 5`
=> 
 `public static readonly int MYCONSTANT`

I'm just wondering if it would be possible to change them into **byte**
` public static readonly byte MYCONSTANT`

**Comment by wsfulton** [comment]
Yes, use the C `unsigned char` type instead as this is mapped to a C# `byte`. There are two ways to do this:
```swig
%apply unsigned char { int MYCONSTANT }
#define MYCONSTANT 5
```
or if you can modify the code to use a SWIG directive instead, replace the macro with:
```swig
%constant unsigned char MYCONSTANT=5;
```
