### ISSUE TITLE
Go tests fail with GO 1.13-beta1

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#1607]
During regular rebuild of Fedora packages it was appeared that SWIG 4.0.0 failed with Go 1.3-beta1.

The complete build log can be found:
https://jplesnik.fedorapeople.org/swig4-go1.3/build.log
https://jplesnik.fedorapeople.org/swig4-go1.3/root.log

More info about changes in buildroot when it started failing:
https://apps.fedoraproject.org/koschei/build/6719636
Another information:
https://apps.fedoraproject.org/koschei/package/swig

Fedora does not run Go tests on  ppc64le and s390.

BUILDSTDERR: panic: runtime error: index out of range [23] with length 0
BUILDSTDERR: goroutine 1 [running]:
BUILDSTDERR: cmd/link/internal/ld.decodetypeKind(...)
BUILDSTDERR: 	/usr/lib/golang/src/cmd/link/internal/ld/decodesym.go:69
BUILDSTDERR: cmd/link/internal/ld.newtype(0xc000050000, 0xc000702150, 0xc000730e68)
BUILDSTDERR: 	/usr/lib/golang/src/cmd/link/internal/ld/dwarf.go:424 +0x29e1
BUILDSTDERR: cmd/link/internal/ld.defgotype(0xc000050000, 0xc000702150, 0x13)
BUILDSTDERR: 	/usr/lib/golang/src/cmd/link/internal/ld/dwarf.go:419 +0x1c8
BUILDSTDERR: cmd/link/internal/ld.dwarfGenerateDebugInfo(0xc000050000)
BUILDSTDERR: 	/usr/lib/golang/src/cmd/link/internal/ld/dwarf.go:1900 +0x91c
BUILDSTDERR: cmd/link/internal/ld.Main(0x84ade0, 0x10, 0x20, 0x1, 0x7, 0x10, 0x699d89, 0x1b, 0x6968b6, 0x14, ...)
BUILDSTDERR: 	/usr/lib/golang/src/cmd/link/internal/ld/main.go:212 +0xb92
BUILDSTDERR: main.main()
BUILDSTDERR: 	/usr/lib/golang/src/cmd/link/main.go:65 +0x1d6
BUILDSTDERR: make[3]: *** [../../Makefile:1623: go_cpp] Error 1
BUILDSTDERR: make[2]: *** [Makefile:16: build] Error 2
BUILDSTDERR: make[2]: Target 'check' not remade because of errors.
BUILDSTDERR: make[1]: *** [Makefile:216: callback.actionexample] Error 2

I disabled Go tests for now.

**Comment by wsfulton** [comment]
ping @ianlancetaylor - please take a look.

**Comment by jplesnik** [comment]
Thank you for the update, but the tests fail with different error:

BUILDSTDERR: cp: cannot stat '/runme.go': No such file or directory
BUILDSTDERR: make[3]: *** [../../Makefile:1526: go_cpp] Error 1
BUILDSTDERR: make[2]: *** [Makefile:16: build] Error 2
BUILDSTDERR: make[2]: Target 'check' not remade because of errors.
BUILDSTDERR: make[1]: *** [Makefile:216: callback.actionexample] Error 2
BUILDSTDERR: cp: cannot stat '/runme.go': No such file or directory
BUILDSTDERR: make[3]: *** [../../Makefile:1526: go_cpp] Error 1
BUILDSTDERR: make[2]: *** [Makefile:13: build] Error 2
BUILDSTDERR: make[2]: Target 'check' not remade because of errors.
BUILDSTDERR: make[1]: *** [Makefile:216: class.actionexample] Error 2

**Comment by ianlancetaylor** [comment]
Hmmm, the tests are passing for me and they are passing on Travis.  Line 1526 doesn't look right to me.  The only lines of code I can see that could possibly produce that error are, from Examples/Makefile.in, lines 1535 to 1537:

```
	if test -f $(SRCDIR)$(RUNME).go; then \
	  cp $(SRCDIR)/$(RUNME).go gopath/$(GOMOD)/src/runme/; \
	fi
```

but no matter how I look at that code it looks right to me.

Is there any way that you can debug your build procedure?

**Comment by wsfulton** [comment]
I think it is just in-source examples that are broken:
```
$ make check-go-examples 
checking Examples/go/callback
cp: cannot stat '/runme.go': No such file or directory
../../Makefile:1514: recipe for target 'go_cpp' failed
```
I also think you need this:
```diff
diff --git a/configure.ac b/configure.ac
index 73c38a72c..3e95f17a6 100644
--- a/configure.ac
+++ b/configure.ac
@@ -2390,8 +2390,9 @@ else
   GOVERSIONOPTION=
 
   if test -n "$GO" ; then
-    GOVERSIONOPTION=version
     AC_MSG_CHECKING([whether go version is too old])
+    GOVERSIONOPTION=version
+    go_version=$($GO $GOVERSIONOPTION | sed -e 's/go version //')
     case $go_version in
     go1.[012345]*)
       AC_MSG_RESULT([yes - minimum version is 1.6])
@@ -2444,11 +2445,6 @@ fi
 AC_SUBST(GOGCC)
 AC_SUBST(GCCGO)
 AC_SUBST(GO)
-AC_SUBST(GOC)
-AC_SUBST(GO1)
-AC_SUBST(GO12)
-AC_SUBST(GO13)
-AC_SUBST(GO15)
 AC_SUBST(GOOPT)
 AC_SUBST(GCCGOOPT)
 AC_SUBST(GOVERSIONOPTION)
```
which restores the version check. This will fix minimum version checking. However, why is it set to 1.6, Travis shows that 1.3 is working?

**Comment by jplesnik** [comment]
@ianlancetaylor @wsfulton : It works now. Thank you.
