### ISSUE TITLE
Syntax error with Doxygen comment not attached to anything

### ISSUE THREAD

**Issue by caijj-coder** [swig/swig#1609]
Hi!
first at all, thank you for this tool.

when I use the version 4.0.0, I have some question.
1，After enumeration conversion， the first item value is missing.
for example:
public final class TEST_TYPE{
public final static int TEST = ;
}
the version 3.0.5 is normal.

2，Does this tool support incremental conversion?
for example:
The conversion is required only after the file is edited.
If I don't edit any file, the tool doesn't need to do anything.

Thanks in Advance.

**Comment by caijj-coder** [comment]
I use the version 4.0.1. Question one is fixed.
thanks you.

**Comment by caijj-coder** [comment]
Another question:
enum TEST
{
    TEST_NONE = 0,
    TEST_ONE, /** somethiong*/
    TEST_TOW /** somethiong*/
};

the error is in the line (TEST_TOW /** somethiong*/);
..\test.h(10) : Error : Syntax error in input(1).

**Comment by caijj-coder** [comment]
I use the version 4.0.1. Question one has been solved.
Thanks.

**Comment by vadz** [comment]
Please don't open issues with questions (there is a mailing list for this) or multiple problems (create separate issues for each problem).

Concerning your last question, I can indeed reproduce this "Syntax error" with the latest SWIG master from Git, I'll try to look at it soon, but please notice that your Doxygen comment is invalid, as it's not really attached to anything. If you used `///< something` instead, it would work as expected.

**Comment by caijj-coder** [comment]
OK. Thanks for your help

**Comment by wsfulton** [comment]
Only occurs when using the `-doxygen` option.

**Comment by ojwb** [comment]
This is essentially the same problem as #1636, except for enum rather than class members.

**Comment by wsfulton** [comment]
Doxygen attaches a Doxygen comment after the last enum item to the last enum as follows: 
```c++
        enum TESTENUM
        {
          /** something for none */
          TEST_NONE = 0,
          /** something for one */
          TEST_ONE,
          /** something for two */
          TEST_TWO  /** something more for two */
        };
```

| Enumerator | |
| ----------- | - |
| TEST_NONE | something for none |
| TEST_ONE | something for one |
| TEST_TWO | something for two something more for two |

The fix replicates this behaviour in SWIG.
