### ISSUE TITLE
--without arguments don't disable language specific examples/features

### ISSUE THREAD

**Issue by ngie-eign** [swig/swig#1611]
A number of specific languages have hooks, e.g., `--without-tcl` for Tcl bindings/examples. Specifying the flags should control doesn't whether or not a feature and its examples are installed, but it doesn't currently per [this piece of Makefile.in](https://github.com/swig/swig/blob/master/Makefile.in#L438) (the issue is more widespread beyond this point; this is just an example).

**Comment by ojwb** [comment]
As documented at http://swig.org/Doc4.0/Preface.html these configure options only control which languages the testsuite gets run for:

> Note that the --without-xxx options, where xxx is a target language, have minimal effect. All they do is reduce the amount of testing done with 'make check'. The SWIG executable and library files installed cannot currently be configured with a subset of target languages.

**Comment by wsfulton** [comment]
Indeed, closing. Also see comments in #1612.
