### ISSUE TITLE
"Extra long specifier" when trying to produce C# output

### ISSUE THREAD

**Issue by Dmitry-Me** [swig/swig#1617]
I have a large .h file which among other stuff has this line:
    typedef long long __int64; //line X

I run swig 4.0.1 like this:
    swig -csharp -includeall -ignoremissing -lwindows.i -lstdint.i -o result.cs sourceH.h

The output says:
    sourceH.h(X): Extra long specifier.

Should this work? What am I doing wrong?

**Comment by wsfulton** [comment]
1. `__int64` is a type that SWIG already knows about.
2. Your typedef is technically illegal according to the C/C++ standards as the symbol you are defining begins with a double underscore.

For both reasons, remove the typedef from sourceH.h.
