### ISSUE TITLE
"Bad constant name" for "#define P =0"

### ISSUE THREAD

**Issue by Dmitry-Me** [swig/swig#1618]
The following line in a .h file:

#define PURE =0

causes "Warning 305: Bad constant value (ignored).

This is a define to apply "=0" to C++ virtual method declarations:

    virtual ReturnType MethodName(ParamsInHere) PURE;

should yield:

    virtual ReturnType MethodName(ParamsInHere) =0;

The `#define` looks like completely legal code

**Comment by wsfulton** [comment]
The preprocessor still expands the macro correctly for use in `MethodName`. The preprocessor additionally attempts to wrap the macro as a constant so it turns it into a `%constant`, see http://www.swig.org/Doc4.0/SWIG.html#SWIG_nn12. 

You can view the preprocessor output using the `-E` option where you'll see:
```swig
%constant PURE = =0;
...
  virtual ReturnType MethodName(ParamsInHere) =0;
``` 
Ultimately SWIG does not do a perfect job at intelligently choosing the macros that can be wrapped as constants. The preprocessor logic is to convert the macro into a `%constant` if there are no unresolved symbols in the macro. The parser will issue the warning if the `%constant` is then not a valid constant. The warning is intended for hand written `%constant` code. Anyway, this warning can be simply ignored or suppressed using the usual warning suppression techniques. I've updated the docs mentioning this, see 4c86ed4.
