### ISSUE TITLE
Swig csharp: compatibillity question

### ISSUE THREAD

**Issue by ptr1120** [swig/swig#1623]
I did not found anything into the Swig documentation for the following aspects:

1. Is the Swig generated C# code platform independent? So, if I compile the generated code on one platform e.g. Windows (with .net core), does the same binary also run on Linux, Osx, without eg. issues due to different calling conventions?

2.  What is the minimal required targeting framework for the generated C# code (e.g. net45 for netframework, or netstandard 1.0 for netcore)?

Best regards
Peter

**Comment by masterwok** [comment]
Were you able to find an answer to this question? I'm wondering the same thing.

**Comment by geefr** [comment]
I'm not sure on .net core support, but believe it works (It's been asked about previously at least)

The C# side of things could be built for 'anycpu' or similar, which in theory would be cross platform

But the C++ side would also need to be built for each platform and architecture, no change there.
The SWIG output would be a C# wrapper around the C++ library, calling through using PInvoke where needed. SWIG does not perform code translation (that's a different subject entirely).

There's also the issue that the native library name will be baked into the generated C# code. While a change of libfoo.so vs foo.dll or foo64.dll is relatively minor it does mean the output is slightly different for each platform, and maybe architecture depending on your setup.
See #347 for more info on that side of things.

**Comment by wsfulton** [comment]
My take on the original points:

1. The generated C# source code is platform independent. Whether or not the compiled C# assembly binaries are platform independent or not probably depends on the platforms you are using, eg Mono vs Microsoft, .NET core vs .NET framework. The generated C/C++ can be compiled on any platform, but of course the compiled C/C++ binaries are very much platform specific. If it helps your understanding, SWIG will generate identical C# and C++ code when run on all platforms, providing your own code does not introduce platform specifics. So you could run SWIG just on MacOS and then compile the resulting generated code on each of MacOS, Linux and Windows.
2. I've just committed a small improvement to the docs about the minimum version required, see 8122929.

**Comment by ptr1120** [comment]
@wsfulton : thank you very much for clarifying and documenting this.
In the time of .Net Standard it would be also interesting to document the compatibility of the generated code towards .Net Standard. In my opinion, the generated code is not using much higher level .Net features and should be compatible to .Net Standard 1.0 
 (see also https://docs.microsoft.com/de-de/dotnet/standard/net-standard).

Thank you and best regards,
Peter

**Comment by wsfulton** [comment]
If someone knows how to work out which standard is applicable, we can document it. So far no-one has contributed testing for .NET Core, so all I know is it is.NET framework 2.0 and later. Earlier versions of .NET Core were missing some APIs, so I think it is a case requiring later versions of .NET Core/Standard.
