### ISSUE TITLE
Guile: Do not use deprecated aliases

### ISSUE THREAD

**Issue by Arfrever** [swig/swig#1624]
[libguile/boolean.h](https://git.savannah.gnu.org/gitweb/?p=guile.git;a=blob;f=libguile/boolean.h;h=56b30a70c71a7eae4caeab50b295ad25eae6d843;hb=HEAD#l92):
```
/* Older spellings for the above routines, kept around for
   compatibility. */
#define SCM_FALSEP(x)           (scm_is_false (x))
#define SCM_NFALSEP(x)          (scm_is_true (x))
#define SCM_BOOLP(x)            (scm_is_bool (x))
#define SCM_BOOL(x)             (scm_from_bool (x))
#define SCM_NEGATE_BOOL(f)      (scm_from_bool (!(f)))
#define SCM_BOOL_NOT(x)         (scm_not (x))
```
[libguile/pairs.h](https://git.savannah.gnu.org/gitweb/?p=guile.git;a=blob;f=libguile/pairs.h;h=617b4c229a04589501b00ebd897891d74d20fb6e;hb=HEAD#l56):
```
/* Older spellings for these null, nil, and pair predicates. */
#define SCM_NILP(x) (scm_is_eq ((x), SCM_ELISP_NIL))
#define SCM_NULL_OR_NIL_P(x) (scm_is_null_or_nil (x))
#define SCM_NULLP(x) (scm_is_null (x))
#define SCM_NNULLP(x) (!scm_is_null (x))
#define SCM_CONSP(x)            (scm_is_pair (x))
#define SCM_NCONSP(x)           (!SCM_CONSP (x))
```

Fix for SWIG:
```
--- Examples/test-suite/guile/guile_ext_test_external.cxx
+++ Examples/test-suite/guile/guile_ext_test_external.cxx
@@ -19,6 +19,6 @@ SCM test_create()
 SCM test_is_pointer(SCM val)
 {
 #define FUNC_NAME "test-is-pointer"
-  return SCM_BOOL(SWIG_IsPointer(val));
+  return scm_from_bool(SWIG_IsPointer(val));
 #undef FUNC_NAME
 }
--- Lib/guile/guile_scm_run.swg
+++ Lib/guile/guile_scm_run.swg
@@ -123,7 +123,7 @@ SWIG_Guile_NewPointerObj(void *ptr, swig_type_info *type, int owner)
     else
       SCM_NEWSMOB2(smob, swig_tag, ptr, (void *) type);
 
-    if (!cdata || SCM_NULLP(cdata->goops_class) || swig_make_func == SCM_EOL ) {
+    if (!cdata || scm_is_null(cdata->goops_class) || swig_make_func == SCM_EOL ) {
       return smob;
     } else {
       /* the scm_make() C function only handles the creation of gf,
@@ -143,7 +143,7 @@ SWIGINTERN unsigned long
 SWIG_Guile_PointerAddress(SCM object)
 {
   SCM smob = SWIG_Guile_GetSmob(object);
-  if (SCM_NULLP(smob)) return 0;
+  if (scm_is_null(smob)) return 0;
   else if (SCM_SMOB_PREDICATE(swig_tag, smob)
           || SCM_SMOB_PREDICATE(swig_collectable_tag, smob)
           || SCM_SMOB_PREDICATE(swig_destroyed_tag, smob)) {
@@ -156,7 +156,7 @@ SWIGINTERN swig_type_info *
 SWIG_Guile_PointerType(SCM object)
 {
   SCM smob = SWIG_Guile_GetSmob(object);
-  if (SCM_NULLP(smob)) return NULL;
+  if (scm_is_null(smob)) return NULL;
   else if (SCM_SMOB_PREDICATE(swig_tag, smob)
           || SCM_SMOB_PREDICATE(swig_collectable_tag, smob)
           || SCM_SMOB_PREDICATE(swig_destroyed_tag, smob)) {
@@ -184,7 +184,7 @@ SWIG_Guile_ConvertPtr(SCM s, void **result, swig_type_info *type, int flags)
   swig_type_info *from;
   SCM smob = SWIG_Guile_GetSmob(s);
 
-  if (SCM_NULLP(smob)) {
+  if (scm_is_null(smob)) {
     *result = NULL;
     return (flags & SWIG_POINTER_NO_NULL) ? SWIG_NullReferenceError : SWIG_OK;
 #if SCM_MAJOR_VERSION >= 2
@@ -250,7 +250,7 @@ SWIGINTERN void
 SWIG_Guile_MarkPointerNoncollectable(SCM s)
 {
   SCM smob = SWIG_Guile_GetSmob(s);
-  if (!SCM_NULLP(smob)) {
+  if (!scm_is_null(smob)) {
     if (SWIG_Guile_IsValidSmob(smob)) {
       SCM_SET_CELL_TYPE(smob, swig_tag);
     }
@@ -263,7 +263,7 @@ SWIGINTERN void
 SWIG_Guile_MarkPointerDestroyed(SCM s)
 {
   SCM smob = SWIG_Guile_GetSmob(s);
-  if (!SCM_NULLP(smob)) {
+  if (!scm_is_null(smob)) {
     if (SWIG_Guile_IsValidSmob(smob)) {
       SCM_SET_CELL_TYPE(smob, swig_destroyed_tag);
     }
@@ -484,20 +484,20 @@ SWIG_Guile_GetArgs (SCM *dest, SCM rest,
   int i;
   int num_args_passed = 0;
   for (i = 0; i<reqargs; i++) {
-    if (!SCM_CONSP(rest))
+    if (!scm_is_pair(rest))
       scm_wrong_num_args(scm_from_utf8_string(procname ? (char *) procname : "unknown procedure"));
     *dest++ = SCM_CAR(rest);
     rest = SCM_CDR(rest);
     num_args_passed++;
   }
-  for (i = 0; i<optargs && SCM_CONSP(rest); i++) {
+  for (i = 0; i<optargs && scm_is_pair(rest); i++) {
     *dest++ = SCM_CAR(rest);
     rest = SCM_CDR(rest);
     num_args_passed++;
   }
   for (; i<optargs; i++)
     *dest++ = SCM_UNDEFINED;
-  if (!SCM_NULLP(rest))
+  if (!scm_is_null(rest))
       scm_wrong_num_args(scm_from_utf8_string(procname ? (char *) procname : "unknown procedure"));
   return num_args_passed;
 }
--- Lib/guile/typemaps.i
+++ Lib/guile/typemaps.i
@@ -426,7 +426,7 @@ typedef unsigned long SCM;
 %typecheck(SWIG_TYPECHECK_BOOL)
        bool, bool&, const bool&
 {
-  $1 = SCM_BOOLP($input) ? 1 : 0;
+  $1 = scm_is_bool($input) ? 1 : 0;
 }
 
 %typecheck(SWIG_TYPECHECK_DOUBLE)
```

**Comment by wsfulton** [comment]
Which version of Guile were the newer replacement functions introduced? Also, it would help us if you popped this into a pull request.

**Comment by ojwb** [comment]
I didn't find the exact version, but from a quick poke it looks like 2004 for at least `scm_is_bool` and `scm_from_bool`: https://git.savannah.gnu.org/cgit/guile.git/commit/?id=3a684cc6c979b57512af1feb88f1517d506c2088

`Guile.htm` says "SWIG works with Guile versions 1.8.x and 2.0.x. Support for version 1.6.x has been dropped." and 1.8.0 was released in 2006 (based on https://git.savannah.gnu.org/cgit/guile.git/tag/?h=release_1-8-0) so this is probably OK, assuming the others were also introduced before 1.8.0.

@Arfrever Can you confirm these changes should be OK with Guile 1.8.x?

And if so, can you open a pull request with these changes?  That way they get tested automatically by the CI system.

**Comment by ojwb** [comment]
We currently have CI testing for guile 2.0 only.  I've pushed a branch which adds testing for 2.2 and 3.0 which are the other two versions easily available via github actions, and also added the patch here as a commit to test it.  Results of CI are that SWIG's existing guile support works for 2.0, 2.2 and 3.0, and this change seems to as well:

https://github.com/swig/swig/actions/runs/1990810088
https://github.com/swig/swig/actions/runs/1990838298

Ideally we want to confirm this works with Guile 1.8.x, or at least have get an OK from @Arfrever or someone else more familiar with Guile that this change should work there.

Or maybe it's time to consider dropping support for Guile 1.8.x given we can't easily test it in CI now, so can't have much confidence that it still works or will continue to work.

**Comment by wsfulton** [comment]
I think I can find a box that has guile 1.8 to check this. If it works, we can do what we've done before and document '1.8 was known to work, but not tested', supported version is 2.0+. Removing support for this really old version doesn't seem unreasonable.

**Comment by ojwb** [comment]
> I think I can find a box that has guile 1.8 to check this. If it works, we can do what we've done before and document '1.8 was known to work, but not tested', supported version is 2.0+.

Rather than stalling this indefinitely, I've done essentially this, except that we only "believe" 1.8 works.  If you (or someone else) are able to find a box to test guile 1.8 on we can update that to "known".  It seems Ubuntu xenial still had it if that helps:

```
$ rmadison -uubuntu guile-1.8
 guile-1.8 | 1.8.8+1-8ubuntu3  | trusty/universe | source, amd64, arm64, armhf, i386, powerpc, ppc64el
 guile-1.8 | 1.8.8+1-10ubuntu1 | xenial/universe | source, amd64, arm64, armhf, i386, powerpc, ppc64el, s390x
```

But Xenial isn't supported by GHA, and has been in non-free support only for over a year now: https://en.wikipedia.org/wiki/Ubuntu_version_history#Table_of_versions

> Removing support for this really old version doesn't seem unreasonable.

I'd be entirely happy to do so.

**Comment by wsfulton** [comment]
Sorry, I forgot to finish this. I checked 7556ed088917ab04cf10cc27f55ea92146e752b9 by downgrading from guile-2.0 to guile-18 on Trusty with these guile changes and the test-suite works. There is just one failure which was already present before the change:
```
Backtrace:
In unknown file:
   ?: 0* [primitive-load "./overload_null_runme.scm"]
```
But I'd say that it definitely works overall.

**Comment by ojwb** [comment]
Cool - I've adjusted the Guile docs in the light of your testing.
