### ISSUE TITLE
Build error on node 12.x

### ISSUE THREAD

**Issue by georgyfarniev** [swig/swig#1625]
Hello. First of all, thanks for creating swig, it helped me many times.

However, I have a problem: when I try to build simple example from docs with Node 12, I get the following errors:

```
'Handle': is not a member of 'v8'
```

Looks like Handle is deprecated already in current node. Is it possible to support node v12?

**Comment by lissyx** [comment]
See #1520

**Comment by ojwb** [comment]
Closing as a duplicate.
