### ISSUE TITLE
%feature("autodoc") silently overrides -doxygen

### ISSUE THREAD

**Issue by gieseanw** [swig/swig#1635]
When `%feature("autodoc")` is used, it silently takes precedence over command line argument `-doxygen` for generating docstrings.

A warning indicating what is happening would be helpful (and perhaps a note in the SWIG-Doxygen docs, too).

Things get especially weird when `-py3` is used because the resulting python code has the type hinting you'd get on function return types from `%feature("autodoc")`, but with docstrings generated by the doxygen machinery. 

Related to #1561

**Comment by ColinChargyBentley** [comment]
Hi,
What would be great to have is that Doxygen comment takes precedence over autodoc. It means that, with the two enabled, if there is Doxygen comment, let's keep those, otherwise, use autodoc to provide the documentation.
What do you think ?
Regards,
Colin Chargy

**Comment by wsfulton** [comment]
Agreed, when -doxygen is being used, the doxygen comments should have precedence over the autodoc comments. I've labelled this for 4.1 as it is a change in behaviour.

**Comment by n8vm** [comment]
I'm running into this issue too. 
@wsfulton I'm not too familiar with the SWIG codebase, but is this where the problem with autodoc vs doxygen precedence is?

https://github.com/swig/swig/blob/a9731251a4234a390993208098cdcef9c358372d/Source/Modules/python.cxx#L1503
https://github.com/swig/swig/blob/a9731251a4234a390993208098cdcef9c358372d/Source/Modules/python.cxx#L1519
