### ISSUE TITLE
[Perl] free(): *** glibc detected *** perl: invalid pointer

### ISSUE THREAD

**Issue by com-nvidia-yohuang** [swig/swig#1637]
Hi Guys,

I need some help to understand and fix an error reported in one small experiment. It looks like there is issue in the way perl decides to destroy an already deleted object.

Thanks,
Justin

**ERROR**
=====
```
env LD_LIBRARY_PATH=/home/utils/gcc-5.2.0/lib64:. runme.pl
deleting a and b
destructor of FOO
*** glibc detected *** /home/utils/perl5/perlbrew/perls/5.20.2-004/bin/perl: free(): invalid pointer: 0x000000000078e638 ***
======= Backtrace: =========
```

**C++ Header File**
$ cat example.h
```
#include <string>
#include <iostream>

class FOO {
public:
        FOO() {} //FOO(std::string name) {_name = name;}
        ~FOO() { std::cout << "destructor of FOO" << std::endl; }
        void foo() { std::cout << "FOO!" << std::endl; }
private:
        std::string _name;
};

class BAR {
public:
        BAR(FOO *a, FOO *b): _a(a), _b(b) {}
        ~BAR() {
            if (_a) delete _a;
            if (_b) delete _b;
        }
        void bar() { std::cout << "BAR!" << std::endl; }
private:
        FOO *_a;
        FOO *_b;
};
```

**SWIG Interface File**
$ cat example.i
```
%module example

%{
#include "example.h"
%}

%include "example.h"
```

**Swig Command**
$ swig -c++ -perl5 example.i

**Perl File**
$ cat runme.pl
`use example;

my $l   = new example::FOO();
my $r   = new example::FOO();
my $bar = new example::BAR($l, $r);`

**Comment by todeschini-felipe** [comment]
I might have a similar issue. Any updates on how to debug or solve this problem?

**Comment by ojwb** [comment]
You need to tell SWIG that passing `a` and `b` to `BAR`'s constructor transfers ownership of the underlying C++ object - change `example.i` to this and your example works:

```
%module example

%{
#include "example.h"
%}

%apply SWIGTYPE *DISOWN {FOO *a};
%apply SWIGTYPE *DISOWN {FOO *b};
%include "example.h"
```
