### ISSUE TITLE
Image links encoded in base64

### ISSUE THREAD

**Issue by eseite47** [swig/swig#1639]
Hi everyone,

We are running into an issue where some of our images are not being compiled properly.
 
We have a couple of images defined like this in an html template:
```
<td valign="top" style="font-size:15px; color:#fff; font-family:Arial,Helvetica,sans-serif; text-align:center;">
              <a href="[linkToPinterest]">
                <img style="display: inline;" src="https://[host]/pinterestBig.png" alt="Pinterest" />
              </a>
            </td>
```

Larger images in our template, hosted in the same place, are fine, but for smaller images rendered as above, the `src` gets transformed into a base64 string, and the image does not render in most email clients (gmail, etc)

The image renders file when the address is hit directly.

What would cause the image to get encoded? How can we fix it?

**Comment by vadz** [comment]
This is not the right project for this issue.
