### ISSUE TITLE
SWIG-generated code affected by MSVS 2017/2019 optimizer bug

### ISSUE THREAD

**Issue by vadz** [swig/swig#1641]
There is [an issue](https://developercommunity.visualstudio.com/content/problem/757936/regression-in-optimized-code-generation-in-presenc.html) with MSVS 2017/2019 compiler (not present in 2015 and earlier versions) which affects SWIG-generated code and basically optimizes away the entire accessor to always return 0 if the wrapper uses `%exception` to add `try { ... } catch` around it.

I could only find the following workaround for it:
```diff
diff --git a/Source/Modules/java.cxx b/Source/Modules/java.cxx
index cb41781dd..bbbbc7d4b 100644
--- a/Source/Modules/java.cxx
+++ b/Source/Modules/java.cxx
@@ -916,7 +916,7 @@ public:

     is_void_return = (Cmp(c_return_type, "void") == 0);
     if (!is_void_return)
-      Wrapper_add_localv(f, "jresult", c_return_type, "jresult = 0", NIL);
+      Wrapper_add_localv(f, "jresult", "volatile", c_return_type, "jresult = 0", NIL);

     Printv(f->def, "SWIGEXPORT ", c_return_type, " JNICALL ", wname, "(JNIEnv *jenv, jclass jcls", NIL);

```
which, of course, makes the generated code longer and less efficient -- but at least forces MSVS to actually generate it.

I don't know if it's worth doing something at SWIG level about it. OOH, I suppose we're not the only ones to use `%exception` like this, but OTOH it does require doing something non-default.

It would be nice if we could avoid the construction with casting the address of the local variable to a pointer to a pointer of different type and then dereferencing it, as this is probably the root of the problem, but it must have been done on purpose (does anyone know which purpose though?) and so I'm not sure if it's a good idea to change it. FWIW C# does just do the direct assignment and doesn't seem to have any problems with it...

**Comment by ojwb** [comment]
> FWIW C# does just do the direct assignment and doesn't seem to have any problems with it...

It looks like C# gets the parameter in question as a pointer rather than an integer type though - from the `class` example:

```
-SWIGEXPORT jdouble JNICALL Java_exampleJNI_Shape_1x_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
-  jdouble jresult = 0 ;
+SWIGEXPORT double SWIGSTDCALL CSharp_Shape_x_get(void * jarg1) {
+  double jresult ;
   Shape *arg1 = (Shape *) 0 ;
   double result;
   
-  (void)jenv;
-  (void)jcls;
-  (void)jarg1_;
-  arg1 = *(Shape **)&jarg1; 
+  arg1 = (Shape *)jarg1; 
   result = (double) ((arg1)->x);
-  jresult = (jdouble)result; 
+  jresult = result; 
   return jresult;
 }
```

So I'm not sure I see how Java could simply follow C# here.

From the linked issue:
> This seems to be fixed in 19.25.28614, thanks.
> May 14, 2020

I.e. this was acknowledged by the vendor as a bug in their compiler and was fixed approaching 2 years ago.

Unless there's a concrete suggestion (a PR would be ideal) for how to change the generated Java code I'm not sure there's much point keeping this open now.
