### ISSUE TITLE
Directors code yields badly formatted comparison operators

### ISSUE THREAD

**Issue by treitmayr** [swig/swig#1642]
When trying to wrap a C++ class definition which contains a virtual comparison operator for "==", ">=", "<=", or "!=", then the generated directors code  contains additional spaces around each "=" yielding invalid operator names, eg. "operator  =  = ".

Here are the input class definition, the swig command, and the resulting code. The used swig version is current git HEAD (4.0.2 - 97a107ed256b308d).

Input class definition **OperatorEQTest.hpp**:
```cpp
#pragma once

class OperatorEQTest
{
  public:
    virtual ~OperatorEQTest() {};
    virtual bool operator ==(const OperatorEQTest&) const;
};
```
Interface file **OperatorEQTest.i**:
```cpp
%module(directors="1") "OperatorEQTest"
%{
#include "OperatorEQTest.hpp"
%}
%feature("director");
#include "OperatorEQTest.hpp"
```
**swig command**:
```sh
swig  -Wall -ruby -c++ -includeall OperatorEQTest.i
```

The interesting part of the resulting code in **OperatorEQTest_wrap.h**
```cpp
class SwigDirector_OperatorEQTest : public OperatorEQTest, public Swig::Director {
public:
    SwigDirector_OperatorEQTest(VALUE self);
    virtual ~SwigDirector_OperatorEQTest();
    virtual bool operator  =  = (OperatorEQTest const &arg0) const;
};
```
and in **OperatorEQTest_wrap.cxx**
```cpp
[...]
bool SwigDirector_OperatorEQTest::operator  =  = (OperatorEQTest const &arg0) const {
  bool c_result = SwigValueInit< bool >() ;
  VALUE obj0 = Qnil ;
  VALUE SWIGUNUSED result;
[...]
```

I noticed that when I apply the following change the error is gone. However my knowledge about the "historic reason" for adding spaces around "=" is nonexistent, so I cannot say for sure that this solution is valid under all conditions or for satisfying all existing test cases which might expect such spaces in other places.
```diff
diff --git a/Source/Modules/directors.cxx b/Source/Modules/directors.cxx
index a91d5fd9a..c9de1df74 100644
--- a/Source/Modules/directors.cxx
+++ b/Source/Modules/directors.cxx
@@ -177,7 +177,7 @@ String *Swig_method_decl(SwigType *return_base_type, SwigType *decl, const_Strin
 
   // Reformat result to how it has been historically
   Replaceall(result, ",", ", ");
-  Replaceall(result, "=", " = ");
+  //Replaceall(result, "=", " = ");
 
   Delete(args_string);
   Delete(popped_decl);
```

**Comment by ojwb** [comment]
That code was added in ae044c1c2f91ee17669f7b8bb78748affc8f2883 so @wsfulton is probably the one who would know what these historic reasons are.

Does the testsuite pass with your change?

**Comment by ojwb** [comment]
This code also rewrites string constants, e.g.:
```
virtual int test(const char* foo="a=1,b=2");
```
becomes:
```
virtual int test(char const *foo = "a = 1, b = 2");
```

**Comment by treitmayr** [comment]
Thanks for taking a closer look! I now ran all test cases for all supported languages (according to the "Getting Started" instructions) with the latest git version, once unmodified and once with _both_ "Replaceall" instructions commented out. Both runs generated the exact same output, so at least the test cases do not rely on some historic formatting.

However in my opiniton it would make sense to add some test cases with similar inputs to what I described in my initial statement and possibly your string constants (in the course of fixing the problem in directors.cxx).

**Comment by ojwb** [comment]
My suspicion is that the reason for these `Replaceall()` calls was just to make the generated code match what was generated before the changes in ae044c1c2f91ee17669f7b8bb78748affc8f2883.  This would have allowed running the testsuite with and without the change and diff-ing the output to check nothing changed (`diff -w` would allow ignoring all whitespace changes, but some do matter and there isn't a `--ignore-insignificant-c++-whitespace` option to `diff`).  So essentially they're for cosmetic reasons which don't matter going forwards, and removing them should be fine.

**Comment by felix-salfelder** [comment]
> and removing them should be fine.

please do.

In case something else is holding back changes to the test output and diffs, i reckon that adding

      Replaceall(result, " =  = ", "==");

should consistently fix the syntax for the operator== director method.

**Comment by wsfulton** [comment]
Thanks @ZackerySpytz for putting in the fix and testcase. My implementation was indeed intending to put spaces around default arguments to match the previous output before the refactor in  ae044c1, but is clearly too naive. Although the spacing is now missing around the equals in the default args, that seems okay to me.
