### ISSUE TITLE
Testcase newobject2 failed with Ruby 2.6.4

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#1646]
Fedora rawhide was updated to Ruby 2.6.4. One of ruby test fails on x86_64 with error:

```
checking ruby testcase newobject2 (with run test)
["./newobject2_runme.rb:24:in `<main>'"]: FAILED: fooCount == 100 - but is 81
make[1]: *** [Makefile:71: newobject2.ctest] Error 1
```

Dependency changes from the latest successful build:
https://koschei.fedoraproject.org/build/6978510

**Comment by treitmayr** [comment]
newobject2 seems to keep the garbage collector enabled throughout the test case and therefore relies on the Ruby interpreter to not trigger garbage collection by itself. Although I could not reproduce your problem with Ruby 2.6.4, I was able to do so by raising the number of created objects to 4000.
By disabling the garbage collector at the beginning of the test case, you can get the test pass even for high numbers of unreferenced objects.
So my guess is that the Ruby part of this test case (and also newobject1) is a bit brittle and could benefit from an initial "GC.disable".
