### ISSUE TITLE
MSVC Python SWIG generates illegal cast to enum for enum class when deriving from base class templated on scoped enum

### ISSUE THREAD

**Issue by gieseanw** [swig/swig#1657]
We can reproduce the issue with the following sample:

```
%module my_module
%inline %{
enum class MY_ENUM{ALPHA};
template<class T>
struct Base{};
%}

%template(BaseEnum) Base<MY_ENUM>{};

%inline %{
struct Derived : Base<MY_ENUM>{};
%}
```

swig generates the following illegal cast

```
static void *_p_DerivedTo_p_BaseT_MY_ENUM_t(void *x, int *SWIGUNUSEDPARM(newmemory)) {
    return (void *)((Base< enum MY_ENUM > *)  ((Derived*) x));
}
```

Resulting in C3431:
  > 'MY_ENUM': a scoped enumeration cannot be redeclared as an unscoped enumeration

This is using SWIG 4 run as

```
swig.exe -python -Fmicrosoft -outdir <some directory> -c++ my_module.i
```

**Comment by ojwb** [comment]
The provided example is invalid and SWIG gives an error - the `{}` on the `%template` line need to be removed to make it work.

With that change, the generate code contains the construct above, but it compiles OK with GCC.

It seems this is actually legal code but older MSVC was buggy and refused to accept it (see #464).  Apparently MSVC 2017 fixed this problem.  #464 was essentially closed as "wontfix", so closing this too.
