### ISSUE TITLE
seg fault w/ pybuffer_mutable_binary PyBuffer_Release without checking PyObject_GetBuffer result

### ISSUE THREAD

**Issue by greenaddress** [swig/swig#1671]
In the macro `pybuffer_mutable_binary` there is a  `PyBuffer_Release` of the result of `PyObject_GetBuffer` without checking that `PyObject_GetBuffer` succeded https://github.com/swig/swig/blob/master/Lib/python/pybuffer.i#L22

Noticed after a segmentation fault after upgrading from swig3 to swig4 as swig4 deprecated the macro used in swig3 - in the interim we made a variant of the macro that does check in our library swig template.

https://github.com/ElementsProject/libwally-core/commit/77842f0f89b4ed9a5da1a30d1d1be3094cbc6f97#diff-d7a4fb9b50985b4769c4930fb1fbef69R174

Would you like something similar as a PR upstream? Note that it should affect multiple macros

**Comment by greenaddress** [comment]
After a quick search - this seems the same issue as https://github.com/swig/swig/issues/1640

**Comment by ojwb** [comment]
Yes, and it was fixed by 772dfd5dcb0e59459a8ff4924ff5cb2383b7c5d3 which should be in the upcoming SWIG 4.1.0 release.
