### ISSUE TITLE
Python __slots__ break C++ wrapping

### ISSUE THREAD

**Issue by hmaarrfk** [swig/swig#1673]
I think the following breaks things if you add a slot to your C++ wrapper in python
```
// my_class.i

[...]

%extend  my::first_class{
    %pythoncode %{
        __slots__ = ['this']
    %}
};
```

```
SWIGRUNTIME void
SWIG_Python_SetSwigThis(PyObject *inst, PyObject *swig_this)
{
 PyObject *dict;
#if !defined(SWIG_PYTHON_SLOW_GETSET_THIS)
 PyObject **dictptr = _PyObject_GetDictPtr(inst);
 if (dictptr != NULL) {
   dict = *dictptr;
   if (dict == NULL) {
     dict = PyDict_New();
     *dictptr = dict;
   }
   PyDict_SetItem(dict, SWIG_This(), swig_this);
   return;
 }
#endif
 dict = PyObject_GetAttrString(inst, "__dict__");
 PyDict_SetItem(dict, SWIG_This(), swig_this);
 Py_DECREF(dict);
} 
```

I think instead of getting the dictionary, which may not exist if `__slots__` are used, then one should directly set the `"this"` attribute to the instance. The code would look something like:

```
  PyObject_SetAttrString(inst, "this", swig_this);                            
```
instead of the 3 last lines.

**Comment by hmaarrfk** [comment]
Is there a way for me to use my little patch in my builds without recompiling swig from scratch? 

I'm thinking in a CI or something. Would I have to place the .swg interface file in the same directory as my setup.py file?

**Comment by vadz** [comment]
Just to understand the bigger picture: what's the point of setting `slots` like this? Is it just an optimization? If it's significant/noticeable, do you think SWIG should always generate code doing it or are there any drawbacks to it?

**Comment by hmaarrfk** [comment]
I started to use it as you would use Freeze to ensure typos don't make me go crazy when setting attributes.

Maybe it does create smaller classes, but I'm not sure about python compatibility.

**Comment by wsfulton** [comment]
You could also use the `python:nondynamic` feature (mentioned in the CHANGES file in each release or online at http://swig.org/Release/CHANGES) to prevent setting of attributes that don't exist in the C++ class.
