### ISSUE TITLE
A scope identifier "final" is treated as a C++ identifier

### ISSUE THREAD

**Issue by boro1970** [swig/swig#1679]
The following code Snippet generates an error while parsing the the input.
```swig
%module someModule

template<class T> class ObjectDB {
public:
       static  bool insert(T *objectT);
      static bool insert(typename final::smart_ptr<T>::type *objectT);
       static final::smart_ptr<T>::type get(const std::string &name);
};
%template(DBInterpCurve) ObjectDB<CInterpCurve>;
```
Removing the scope identifier "final" resolves the problem. It seems that "final"
is interpreted as a reserved C++11 identifier as the code is processed correctly with Swig 2.0.10.

**Comment by wsfulton** [comment]
"final" is a C++11 identifier with special meaning. There is a bug in SWIG when "final" is used as part of the symbol name.

**Comment by ptizoom** [comment]
still got an "Syntax error in input(3). " compiled with  

> swig -c++ -cppext cpp -directors -v -Wall -debug-symtabs -debug-typedef -debug-classes -macroerrors 

v4.0.0, debian 4.0.2-1.

```
class B { }
class A final : public B { }

```

**Comment by wsfulton** [comment]
Hi @ptizoom, this is a separate issue being tracked in #672.
