### ISSUE TITLE
java - SWIG_PROXY_CONSTRUCTOR

### ISSUE THREAD

**Issue by nssang00** [swig/swig#1682]
swig 3.0.12
%define SWIG_PROXY_CONSTRUCTOR(OWNERSHIP, WEAKREF, TYPENAME...)
%typemap(javaconstruct,directorconnect="\n    $imclassname.$javaclazznamedirector_connect(this, swigCPtr, **swigCMemOwn**, WEAKREF);") TYPENAME {
    this($imcall, OWNERSHIP);$directorconnect
  }
%enddef

swig 4.0.1

%define SWIG_PROXY_CONSTRUCTOR(OWNERSHIP, WEAKREF, TYPENAME...)
%typemap(javaconstruct,directorconnect="\n    $imclassname.$javaclazznamedirector_connect(this, swigCPtr, **OWNERSHIP**, WEAKREF);") TYPENAME {
    this($imcall, OWNERSHIP);$directorconnect
  }
%enddef

java.swg
Is "OWNERSHIP" correct instead of "swigCMemOwn"?
I think 3.0.12 is correct...

**Comment by wsfulton** [comment]
The change was put in 98e67539ddbebc7461b2ece58149ac123e7a4835 as a precursor to fix the director_smartptr test merged in 63a7f3c6b300e6f3aedb481ccdcb6f2ecad06925. Related issues are #230 and #759.

Please post a problem testcase, otherwise close the issue. Thanks.

**Comment by ojwb** [comment]
No response from submitter for 2 years, so closing.
