### ISSUE TITLE
intgosize 64 seems to have no effect

### ISSUE THREAD

**Issue by Keithcat1** [swig/swig#1698]
I was wrapping BASS in Go, using Swig, and I got some errors like this.
```
_/C_/py/b
# _/C_/py/b
.\bass.go:1239:7: constant 4278190080 overflows int
.\bass.go:1993:7: constant 2147483648 overflows int
.\bass.go:2594:7: constant 2147483648 overflows int
.\bass.go:2710:7: constant 2147483648 overflows int
.\bass.go:2742:7: constant 2147483648 overflows int
.\bass.go:2743:7: constant 2147483649 overflows int
.\bass.go:2744:7: constant 2147483650 overflows int
.\bass.go:2745:7: constant 2147483651 overflows int
.\bass.go:2746:7: constant 2147483652 overflows int
.\bass.go:2747:7: constant 2147483653 overflows int
.\bass.go:2747:7: too many errors
```
So, I regenerated the code using -intgosize 64, and the constants still seemed to be declared using int type.
const BASS_DATA_FFT8192 int = 0x80000005

Also, is there a way to insert CGO flags into the interface, to be used if the target language is Go? Right now I have to do it manually.

**Comment by wsfulton** [comment]
@ianlancetaylor could you respond to this one please?

**Comment by ianlancetaylor** [comment]
The `-intgosize` option only tells SWIG the size of Go's `int` type.  It doesn't actually change the size of the type.  The errors you are getting suggest that you are using Go on a 32-bit platform, for which the Go type `int` is 32 bits.  There isn't anything that SWIG can do to change that.

Assuming you are building using `go build` with your SWIG interfaces defined in `.swig` files, then I think you can add, in a Go file, something like

/*
#cgo CFLAGS: -fmy-flag
*/
import "C"

to add flags that will be used when compiling.  Give that a try, anyhow.

**Comment by Keithcat1** [comment]
No, but SWIG can declare the constants as type int64 for example:
const MyConst int64=500

Also thanks, I didn't think of using a separate go file. A way to include code in the target language might be nice though.

**Comment by ianlancetaylor** [comment]
But using an explicit type like `int64` would make it harder to use those constants when calling C functions.

**Comment by Keithcat1** [comment]
Well, it doesn't make sense that I can only compile this code on a 64-bit platforms. That seems quite bad too. Though 32-bit isn't super popular, it should still work to compile for 32-bit.

**Comment by Keithcat1** [comment]
Here is an example that converts constants of various types and works perfectly.

package main
/*
int add(int a, int b) {
	return a+b;
}
*/
import "C"

const testing_long int64=1000000000
const testing_int int=125
const testing_short uint32=100

func main() {
	val:=C.add(C.int(testing_long), C.int(testing_int))
	val=C.add(val, C.int(testing_short))
	print(val)
}

**Comment by ianlancetaylor** [comment]
What does the input to SWIG look like here?  Can you show me a standalone example that doesn't involve BASS?

**Comment by ojwb** [comment]
@Keithcat1 Can you provide a standalone example?
