### ISSUE TITLE
Define for checking if -py3 is enabled in interface code

### ISSUE THREAD

**Issue by nightlark** [swig/swig#1703]
I have a swig interface file (*.i) with some type maps specifically for Python 3 (some PyUnicode stuff added in 3.3) and a separate file with less custom type maps intended for Python 2 (or I suppose older Python 3 versions).

I was looking at combining the two swig interface files and using a #if macro to conditionally include the parts that are just for Python 3.3 and up, but I didn't see any predefined macros for indicating if the `-py3` flag is getting used (or flags for indicating that a piece of the swig interface file is for a specific Python version).

Maybe I overlooked something, but it would be useful to be able to tell if the interface is getting generated using `-py3`.

**Comment by vadz** [comment]
Are you looking for `SWIGPYTHON_PY3`? It doesn't seem to be documented, but it does exist...

**Comment by nightlark** [comment]
Ah yes! That sounds like exactly what I'm looking for. From the commit history it seems like it was first in the 3.0.9 release.

**Comment by nightlark** [comment]
PR #1705 adds `SWIGPYTHON_PY3` to the list of preprocessor defines in the documentation.

**Comment by ojwb** [comment]
Closing since `SWIGPYTHON_PY3` is now documented.
