### ISSUE TITLE
Python SWIG: convert C++ return parameter pointer to return value

### ISSUE THREAD

**Issue by huckw** [swig/swig#1707]
I'm trying to convert a c++ return argument that is a pointer to a custom object into a left hand side return argument in Python.  If my return argument is a reference that uses `&` it works perfect (see the example [here](https://stackoverflow.com/questions/49121312/python-swig-convert-c-return-parameter-to-return-value-and-convert-raw-c-t)).  But, below you will see how I tried to modify that example to work with the `*` instead of the `&` but with errors :(.

**test.h**
```
#ifdef EXPORT
#define API __declspec(dllexport)
#else
#define API __declspec(dllimport)
#endif

struct ResultType
{
    int x;
    double y;
};

API void execute(int x, double y, ResultType* result1, ResultType* result2);
```
**test.cpp**
```
#define EXPORT
#include "test.h"

API void execute(int x, double y, ResultType* result1, ResultType* result2)
{
    result1->x = 2 * x;
    result1->y = 2 * y;
    result2->x = 3 * x;
    result2->y = 3 * y;
}
```
**test.i**
```
%module test

%{
#include "test.h"
%}

%include <windows.i>

%typemap(in,numinputs=0) ResultType* %{
    // Create a persistent object to hold the result;
    $1 = new ResultType;
%}

%typemap(argout) ResultType* (PyObject* tmp) %{
    // Store the persistent object in a PyObject* that will be destroyed
    // when it goes out of scope.
    tmp = SWIG_NewPointerObj($1, $1_descriptor, SWIG_POINTER_OWN);
    $result = SWIG_Python_AppendOutput($result, tmp);
%}

%include "test.h"
```
**Output**
```
>>> import test
>>> r = test.execute(2,3)
```
Gives me this error...
```
Exception ignored in: <built-in function delete_ResultType>
TypeError: delete_ResultType() takes no arguments (1 given)
```
And if I then try to do...
```
print(r[0].x)
```
it gives a similar error...
```
TypeError: ResultType_x_get() takes no arguments (1 given)
```
To see what I've got in python I did this...
```
print(type(r[0]))

<class 'pyml.pyml.ResultType'>

print(dir(r[0]))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__form
at__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_s
ubclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__',
 '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclas
shook__', '__swig_destroy__', '__weakref__', 'this', 'thisown', 'x', 'y']
```
This looks like what I'd expect...in fact, it looks exactly like when you use & instead of *...so it seems like it should work. But alas, it does not.

If I use `0` instead of `SWIG_POINTER_OWN` in the .i file the `TypeError: delete_ResultType() takes no arguments (1 given)` goes away, but I'm not confident that's the right thing to do. I was also able to convert the two ResultTypes to a pair of tuples in the typemap but I'd rather have the python wrapped ResultType like I get when using `&`.

**Comment by sethrj** [comment]
I think your `ResultType*` typemap needs to be applied to a specific argument name (such as `OUT`) and  then `%apply`d.  From the error message about `delete_ResultType` it sounds like the typemap is being automatically used in the automatically created destructor `void delete_ResultType(ResultType* self);`

**Comment by huckw** [comment]
Thanks @sethrj ....but I'm not sure I get what you are saying.  Can you spoon feed me a bit with an example?  I'm not very proficient with Swig.  Thanks in advance!

**Comment by sethrj** [comment]
While I'm composing an answer (may be back tomorrow) try running with `-debug-tmused` and seeing how it applies to the various `ResultType` objects in your interface. Sorry for the delay!

**Comment by huckw** [comment]
The version with the reference shows up a couple times...

```
Typemap for ResultType &result (in) : %typemap(in) ResultType &
```
and
```
Typemap for ResultType &result (typecheck) : %typemap(typecheck) SWIGTYPE &
Typemap for ResultType &result (argout) : %typemap(argout) ResultType &
```

And the one with the pointer also shows up a couple times...

```
Typemap for ResultType  *result (in) : %typemap(in) SWIGTYPE *
```
and
```
Typemap for ResultType  *result (typecheck) : %typemap(typecheck) SWIGTYPE *
```

This doesn't mean much to me....does it provide any clues?

**Comment by sethrj** [comment]
The point I was trying to make is that your new typemap applied to the "self" in the destructor of `ResultType` (which takes `ResultType*`) as well as the other `ResultType*` you intended to wrap:
```
test.h:8: Typemap for ResultType *self (in) : %typemap(in) ResultType *
test.h:8: Typemap for ResultType *self (typecheck) : %typemap(typecheck) SWIGTYPE *
test.h:8: Typemap for ResultType *self (argout) : %typemap(argout) ResultType *
test.h:8: Typemap for ResultType *self (freearg) : %typemap(freearg) SWIGTYPE *
test.h:8: Typemap for void ResultType::~ResultType (out) : %typemap(out) void
```
though with the swig output that's pretty easy to miss.

**Comment by sethrj** [comment]
Try this to apply your typemap only to only apply it to your output variables rather than *every* ResultType pointer (including the "this" pointer passed to the destructor):
```swig
%typemap(in,numinputs=0) ResultType *OUT %{
    // Create a persistent object to hold the result;
    $1 = new ResultType;
%}

%typemap(argout) ResultType *OUT  (PyObject* tmp) %{
    // Store the persistent object in a PyObject* that will be destroyed
    // when it goes out of scope.
    tmp = SWIG_NewPointerObj($1, $1_descriptor, SWIG_POINTER_OWN);
    $result = SWIG_Python_AppendOutput($result, tmp);
%}

%apply ResultType* OUT {ResultType* result1, ResultType* result2};
```

Then your swig debug output will show the normal typemap applied:
```
test.h:10: Typemap for ResultType *self (freearg) : %typemap(freearg) SWIGTYPE *
test.h:10: Typemap for double ResultType::y (out) : %typemap(out) double
test.h:8: Typemap for ResultType *ResultType::ResultType (out) : %typemap(out) SWIGTYPE *
test.h:8: Typemap for ResultType *self (in) : %typemap(in) SWIGTYPE *
test.h:8: Typemap for ResultType *self (typecheck) : %typemap(typecheck) SWIGTYPE *
test.h:8: Typemap for ResultType *self (freearg) : %typemap(freearg) SWIGTYPE *
test.h:8: Typemap for void ResultType::~ResultType (out) : %typemap(out) void
```

**Comment by ojwb** [comment]
The answer from sethrj looks good to me.

No response from the submitter for nearly 2 years so closing.
