### ISSUE TITLE
Generating multiple Java wrappers for a single C function

### ISSUE THREAD

**Issue by Dominaezzz** [swig/swig#1708]
Can swig generate multiple wrappers for the same C function?

This is the C function.
```
void useData(char* buf) {
   // TODO.....
}
```
With swig I've managed to get this generated.
```
public static void useData(SWIGTYPE_p_char buf) {
    // SWIG stuff....
}
```
Now this worked but sometimes I want to pass a ByteBuffer instead of SWIGTYPE_p_char. With another typemap, I've managed to generate this.
```
public static void useData(ByteBuffer buf) {
    // SWIG stuff....
}
```

SWIG only generates one, depending on the last typemap. How can I generate both?

**Comment by vadz** [comment]
AFAIK the only way to generate both is to add a declaration for another (overloaded) function, but the question is, why would you want to generate the former version which is unusable from Java anyhow? You only need (and IMO want) the latter one.

**Comment by Dominaezzz** [comment]
Sometimes I might get the object from a different swig wrapper, so it'll be easier to pass it on with awkward conversation on the Java end of things.

I guess I could make SWIG replace everything with Java buffers. But I find it difficult to make swig differentiate between const and not const.

**Comment by ojwb** [comment]
Try `%extend`?

**Comment by Dominaezzz** [comment]
`%extend` would require me to write a method for every C function that accepts a `char*` myself.

**Comment by wsfulton** [comment]
SWIG pretty much provides a one to one interface of the wrapped C++ code. It doesn't write APIs for you, it wraps existing C++ APIs for use by other languages. You need to provide additional overloaded functions for Java by adding in real C++ overloaded functions or by using `%extend` as mentioned.

A workaround idea if you are unable to write code at the C++/SWIG layer... You could provide a pseudo kind of overloading by creating a Java class that contains the two overloaded types that you want to provide into the C++ layer. So in this case create a pure Java class (or a wrapped C++ class) that will take the two overloaded types that you want to support (`SWIGTYPE_p_char` and `ByteBuffer`). Say you call this new class `ByteBufferOrCharPointer`, then you'd call the wrapped API like: `useData(new ByteBufferOrCharPointer(new ByteBuffer(...)))`.
