### ISSUE TITLE
seg fault using R module

### ISSUE THREAD

**Issue by khoran** [swig/swig#1714]
I'm having trouble using some swig4 generated R code. I had previously been using this code with swig 1 generated R code and it was working fine. I've made whatever changes I could to my own code to try to make this work, but no avail. It seems to me, after spending 15 hours digging through this, that there is a mismatch between what the R wrapper function expects as one of its arguments, and what the C++ wrapper function expects. Unfortunately, the setup is complex and I don't see any way to simplify it. So Here is the whole explanation. 

I maintain the R package ChemmineOB, which wraps the C++ library OpenBabel in R, using SWIG. I had this all working fine with OpenBabel 2.3 and SWIG 1.x. OpenBabel recently released 3.0, so I needed to regenerate the SWIG wrappers, so I thought I would also take the opportunity to upgrade to SWIG 4.0 as well. 

I have generated the R wrapper file as openBabel_R.R. I changed all package references to ChemineOB to match my own package name. I also generated the openBable_R.cpp file. 

The R code that triggers the seg fault is: 
```
        inStr = ChemmineOB:::istreamFromString("C1CCCC1")
        conv = ChemmineOB:::OBConversion(inStr)
        
        if(!ChemmineOB:::OBConversion_SetInFormat(conv,"SMI"))
                stop("failed to set input format: ","SMI")

        mol = ChemmineOB:::OBMol()

        if(!ChemmineOB:::OBConversion_Read(conv,mol))
                stop("failed to read ","molecules from input")

        fpHandle = ChemmineOB:::OBFingerprint_FindFingerprint("FP2")
        #fp = ChemmineOB:::vectorUnsignedInt(1)  #WORKED IN SWIG 1.x
        fp = integer(1)
        ChemmineOB:::OBFingerprint_GetFingerprint(fpHandle,mol,fp)
```
All of these functions are in the openBabel_R.R file, I'm just accessing them through my own package. This part of the setup was working fine with SWIG 1.x. 
The call to `OBFingerprint_GetFingerprint(fpHandle,mol,fp)` causes the seg fault, gdb reports "memory not mapped". 

I've worked out that the problem is that `fp` is not the right type of object. But here is the problem, the R wrapper code checks that `fp` is an R integer vector, but the C++ layer of the wrapper treats it like it's a pointer to an `std::vector<unsigned int>`. So if I define `fp` as `fp = integer(1)`, which is an R integer vector, then it makes it past the checks in the R layer, but seg faults in the C++ layer. If instead I define `fp` as `vectorUnsignedInt(1)`, it fails the checks in the R layer. If I disable those checks, then the function runs through correctly, indicating that the C++ layer expects it as a pointer. 

Here are the relevant chunks from the R layer:

```
`OBFingerprint_GetFingerprint` <- function(...) { argtypes <- mapply(class, list(...)); argv <- list(...);argc <- length(argtypes);
   # dispatch functions 2
     if (argc == 3) {  # THIS BLOCK ENTERED
      if ((extends(argtypes[1], '_p_OpenBabel__OBFingerprint') || is.null(argv[[1]])) &&        
          (extends(argtypes[2], '_p_OpenBabel__OBBase') || is.null(argv[[2]])) && 
          (is.integer(argv[[3]]) || is.numeric(argv[[3]]) )) # <- CHECKS HERE THAT THIRD ARGUMENT IS AN INTEGER VECTOR
      {
       f <- OBFingerprint_GetFingerprint__SWIG_1;
      }
     } else if (argc == 4) {
      if ((extends(argtypes[1], '_p_OpenBabel__OBFingerprint') ||
          is.null(argv[[1]])) && (extends(argtypes[2], '_p_OpenBabel__OBBase') ||
          is.null(argv[[2]])) &&
          ( is.integer(argv[[3]]) || is.numeric(argv[[3]]) ) &&
          ( (is.integer(argv[[4]]) || is.numeric(argv[[4]])) && length(argv[[4]]) == 1 ))
      {
       f <- OBFingerprint_GetFingerprint__SWIG_0;
      }
     }else {
      stop("cannot find overloaded function for OBFingerprint_GetFingerprint with argtypes (",toString(argtypes),")");
     } ;
     f(...);
   }
```

```
 # Start of OBFingerprint_GetFingerprint
   `OBFingerprint_GetFingerprint__SWIG_1` = function(self, pOb, fp, .copy = FALSE) {
     if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
     if (inherits(pOb, "ExternalReference")) pOb = slot(pOb,"ref");  
       fp = as.integer(fp);   
       ;.Call('R_swig_OBFingerprint_GetFingerprint__SWIG_1', self, pOb, fp, as.logical(.copy), PACKAGE='ChemmineOB'); 
}
   attr(`OBFingerprint_GetFingerprint__SWIG_1`, 'returnType') = 'logical'
   attr(`OBFingerprint_GetFingerprint__SWIG_1`, "inputTypes") = c('_p_OpenBabel__OBFingerprint', '_p_OpenBabel__OBBase', 'integer')
   class(`OBFingerprint_GetFingerprint__SWIG_1`) = c("SWIGFunction", class('OBFingerprint_GetFingerprint__SWIG_1'))
```

Here is the C++ wrapper chunk:

```
 SWIGEXPORT SEXP R_swig_OBFingerprint_GetFingerprint__SWIG_1 ( SEXP self, SEXP pOb,   SEXP fp, SEXP s_swig_copy) { 
     bool result;
     
     OpenBabel::OBFingerprint *arg1 = (OpenBabel::OBFingerprint *) 0 ;
    OpenBabel::OBBase *arg2 = (OpenBabel::OBBase *) 0 ;
     
     std::vector< unsigned int,std::allocator< unsigned int > > *arg3 = 0 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    void *argp2 = 0 ;
     
     int res2 = 0 ; 
    void *argp3 = 0 ;
    int res3 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
     
     VMAXTYPE r_vmax = vmaxget() ; 
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_OpenBabel__OBFingerprint, 0 |  0 );
     
     if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "OBFingerprint_GetFingerprint" "', argument " "1"" of type '" "OpenBabel::OBFingerprint *""'");
     }
     arg1 = reinterpret_cast< OpenBabel::OBFingerprint * >(argp1);
     
     res2 = SWIG_R_ConvertPtr(pOb, &argp2, SWIGTYPE_p_OpenBabel__OBBase, 0 |  0 );
    if (!SWIG_IsOK(res2)) {
      SWIG_exception_fail(SWIG_ArgError(res2), "in method '" "OBFingerprint_GetFingerprint" "', argument " "2"" of type '" "OpenBabel::OBBase *""'");
     }
     arg2 = reinterpret_cast< OpenBabel::OBBase * >(argp2);
     
     res3 = SWIG_R_ConvertPtr(fp, &argp3, SWIGTYPE_p_std__vectorT_unsigned_int_std__allocatorT_unsigned_int_t_t,  0 );
     
     if (!SWIG_IsOK(res3)) {
      SWIG_exception_fail(SWIG_ArgError(res3), "in method '" "OBFingerprint_GetFingerprint" "', argument " "3"" of type '" "std::vector< unsigned int,std::allocator< unsigned int > > &""'");
     }
     if (!argp3) {
      SWIG_exception_fail(SWIG_ValueError, "invalid null reference " "in method '" "OBFingerprint_GetFingerprint" "', argument " "3"" of type '" "std::vector< unsigned int,std::allocator< unsigned int > > &""'");
    } 
     arg3 = reinterpret_cast< std::vector< unsigned int,std::allocator< unsigned int > > * >(argp3);
     
     result = (bool)(arg1)->GetFingerprint(arg2,*arg3);
    r_ans = Rf_ScalarLogical(result);
    vmaxset(r_vmax);
     
     if(r_nprotect)  Rf_unprotect(r_nprotect);
    return r_ans;
    }
```

So by the time the OpenBabel `GetFingerprint` function gets called, I don't see anywhere where an R integer vector could have been transformed into an `std::vector<unsigned int>`, which is what `GetFingerprint` expects. I know that whatever gets passed in is cast to that type, but that's not what it really is, hence the segfault. 

I was tempted to just manually change the R wrapper code to make the checks look for a pointer to `std::vector<unsigned int>`, but the class of `fp` just shows up as "externalptr", with no further details. Back in SWIG 1.x, the class was "_p_std__vectorT_unsigned_int_std__allocatorT_unsigned_int_t_t", so it was clear what it was. So while I could make this work by completely disabling any checks at all, I'd rather not have to do that. 

Any help would be greatly appreciated. I'm not sure if I'm just not using the R wrapper correctly, or if this is really a bug. I can't find any documentation about using the R wrapper code. From recent R related issues, it seems some big adjustments have been made in SWIG 4.x.

Let me know if any additional information is needed or would be helpful.

**Comment by khoran** [comment]
I have created simple example now that re-produces the problem.

Create vector_test.i:
```
%module vector_test
%include <stl.i>
%include "std_vector.i"
%inline %{
   int fun1(std::vector<unsigned int>& fp){
      return 8;
   }
%}
namespace std {
   %template(vectorUnsignedInt) vector<unsigned int>;
}
```
Create test.R:
```
dyn.load(paste("vector_test", .Platform$dynlib.ext, sep=""))
source("vector_test.R")

v = c(1,2,3)   #causes seg fault
#v = integer(3) #also seg faults
#v = vectorUnsignedInt(1)  #works after commenting out "fp=as.integer(fp)" in vector_test.R, line 192

fun1(v)
```
build:
```
swig -r -c++ -o vector_test.cpp vector_test.i
c++  -I/usr/share/R/include -fPIC  -o vector_test.o -c vector_test.cpp
c++ -fPIC  -shared -o vector_test.so vector_test.o
```

Run:
`R --vanilla < test.R`

Output:

```
> dyn.load(paste("vector_test", .Platform$dynlib.ext, sep=""))
> source("vector_test.R")
>
> v = c(1,2,3)
> #v = vectorUnsignedInt(1)
>
> fun1(v)

 *** caught segfault ***
address 0x200000021, cause 'memory not mapped'

Traceback:
 1: .Call("R_swig_fun1", fp, as.logical(.copy), PACKAGE = "vector_test")
 2: fun1(v)
An irrecoverable exception occurred. R is aborting now ...

```
It seems like the vector `c(1,2,3)` is supposed to be converted to a true `std::vector<unsigned int>` somewhere before being passed into `fun1`. But instead it is simply cast to that type, but never converted. I'm not sure if I'm just doing something wrong, or if there is a bug here. Any help would be greatly appreciated. Thanks.

**Comment by wsfulton** [comment]
Something isn't quite right in the setup of R's `std_vector.i`. The non-const reference typemaps should work the same way as the const reference typemaps. What I can see when running `swig -debug-tmused` is a difference in the typemaps used. 

There are two workarounds, which you use. Place either one of the two code snippets below just after the `%include <std_vector.i>` in order to pickup the appropriate typemaps:
```swig
%typemap(in) std::vector<unsigned int>& = const std::vector<unsigned int>&;
%typemap(typecheck) std::vector<unsigned int>& = const std::vector<unsigned int>&;
%typemap(freearg) std::vector<unsigned int>& = const std::vector<unsigned int>&;
```
```swig
%apply const std::vector<unsigned int>& { std::vector<unsigned int>& }
```

**Comment by khoran** [comment]
Thanks, that fixed that problem!
There is another problem now, related. The vector is passed in by reference, so the expectation is that changes made by the C function are reflected in the vector passed in. That is not happening though. The original R vector remains unchanged after the GetFingerprint function call. 

A small change the the simplified example shows the problem. 
In vector_test.i,  Change 
```
 int fun1(std::vector<unsigned int>& fp){
      return 8;
   }
```
to 
```
 int fun1(std::vector<unsigned int>& fp){
      fp[0]=42;
      return 8;
   }
```
Then in test.R, just add a print statement to print out `v` after calling `fun1` and you'll see that it is unchanged. So how do I get the modifications reflected in my R vector? Thanks for your help.

**Comment by khoran** [comment]
Got it working by adding: 
%apply std::vector<unsigned int> &INOUT {std::vector<unsigned int> &fp};
