### ISSUE TITLE
Enums with Doxygen comments and odd (but legal) commas produce error

### ISSUE THREAD

**Issue by pyt-viper** [swig/swig#1715]
I am trying to wrap code like this:

    enum myEnum {
        enum1     ///< Doxygen comment for enum1
        ,enum2    ///< Doxygen comment for enum2
        ,enum3    ///< Doxygen comment for enum3
    };

`swig -doxygen` (version 4.0.1) reports a syntax error at the first comma.  My software package uses this format in other places for other types of argument lists, but the syntax error only occurs with `enum`s.

I have access to the code and can change it to put the commas in the more conventional place, but Doxygen parses this code correctly, so I thought SWIG should as well.

**Comment by ojwb** [comment]
Still present on current git master - this patch reproduces:

```
--- a/Examples/test-suite/doxygen_misc_constructs.i
+++ b/Examples/test-suite/doxygen_misc_constructs.i
@@ -97,9 +97,9 @@
         /**
          * Enum description.
          */
-        typedef enum {ONE,  ///< desc of one
-                      TWO,  ///< desc of two
-                      THREE ///< desc of three
+        typedef enum {ONE  ///< desc of one
+                      ,TWO  ///< desc of two
+                      ,THREE ///< desc of three
         } ENested;
 
     };
```
