### ISSUE TITLE
Wrapping std::function from C++ to C#

### ISSUE THREAD

**Issue by ThibaultLesaunier** [swig/swig#1719]
Hi guys,

I'm trying to wrap a c++ std::function using Swig. 
Current wrapping gives me weird SWIGTYPE class.

Current std::function.
using f = std::function<void ( const namespace1::namespace2::T1& v1,  namespace1::namespace2::T2& v2)>;

Swig result

SWIGTYPE_p_std__functionT_void_fnamespace1__namespace2__T1_const_R_namespace1__namespace2__T2_RF_t.cs

################
SWIG version = 4.0.1

I'm not looking for a class as well, this function is a part of one my classes. 

Thanks for help, let me know if you need more info.

**Comment by wsfulton** [comment]
Please read the manual, in particular "type wrapper" classes. There is no explicit support for `std::function` in SWIG, see #341.
