### ISSUE TITLE
std::chrono::nanoseconds from C++ to C#

### ISSUE THREAD

**Issue by ThibaultLesaunier** [swig/swig#1720]
Hi guys,

I'm trying to wrap a C++ class with C# target.

I have a std::chrono::nanoseconds to fix time in my app.

Using swig, it creates a SWIGTYPE_p_std__chrono__nanoseconds.cs. 

Someone has an idea, How to properly include std::chrono in my .i file ? 

Thanks

**Comment by wsfulton** [comment]
SWIG will need to parse a definition of this class. Please read the manual, in particular "type wrapper" classes in the Java chapter.
