### ISSUE TITLE
Unexpected unindent in python docstrings

### ISSUE THREAD

**Issue by FFroehlich** [swig/swig#1730]
swig version 4.0.1, mac os x 10.14.6, sphinx 2.4.3

For doxygen-style C++ docstrings such as 
```
/** @brief ExpData carries all information about experimental or
 * condition-specific data
 */
class ExpData {...}
```
SWIG will generate malformed python docstrings:
```
    r"""
     ExpData carries all information about experimental or
    condition-specific data
    """
```
 which lead to unexpected unindent warnings when parsing with sphinx and malformed documentation.

This can be fixed by changing the C++ docstring to  
```
/** 
 * @brief ExpData carries all information about experimental or
 * condition-specific data
 */
class ExpData {...}
```
which is converted to
```
    r"""
    ExpData carries all information about experimental or
    condition-specific data
    """
```
and can be properly parsed by sphinx

**Comment by mcfarljm** [comment]
I think this is a problem with your comment style.  Try lining up the text on each line, as in:
```
/** @brief ExpData carries all information about experimental or
 *  condition-specific data
 */
class ExpData {...}
```
This is consistent with usage in the doxygen manual: http://www.doxygen.nl/manual/docblocks.html.

With this change, doxygen produces correct output for me.  This comment style is tested as part of the test suite [doxygen_basic_translate_style2.i](../tree/master/Examples/test-suite/doxygen_basic_translate_style2.i).

**Comment by wsfulton** [comment]
Closing as this looks like a user error.
