### ISSUE TITLE
fail to generate Java code

### ISSUE THREAD

**Issue by tokenCthulhu** [swig/swig#1733]
I'm trying to export my C++ code to java. Swig compile passed and target built, but in Java it doesn't generate proper Java class. I find that it produce an empty ExampleModuleJNI.java, but no Example.java.
The whole compile process doesn't raise an error or even warning, thus I can't tell what's going wrong. I want to know possible reasons. If necessary I can paste my code.

**Comment by wsfulton** [comment]
Please try the examples shipped with SWIG. User support is on the swig-user mailing list.
