### ISSUE TITLE
using swig to convert C++ code with latest go1.13

### ISSUE THREAD

**Issue by msherif4** [swig/swig#1734]
I have been following the instructions in Doc however it refer to some go tools that are longer exists in latest version of golang, basically I am trying to create golang interface to open source mabain C++ library https://github.com/chxdeng/mabain

swig -version

SWIG Version 3.0.12

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
root@d4a70b5e31bf:/# go version
go version go1.13 linux/amd64

when I used 
	swig -go -cgo -c++ -intgosize 64 mabain.i
then I tried to build the generated go code
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o libmabain mabain.go
 ---> Running in e85624d642f0
# command-line-arguments
/tmp/go-build216038269/b001/_x002.o: In function `_cgo_86b9c1fc6a54_Cfunc__wrap_Swig_malloc_mabain_001887ee45ff3f46':
/tmp/go-build/cgo-gcc-prolog:64: undefined reference to `_wrap_Swig_malloc_mabain_001887ee45ff3f46'
/tmp/go-build216038269/b001/_x002.o: In function `_cgo_86b9c1fc6a54_Cfunc__wrap_mbAdd_mabain_001887ee45ff3f46':
/tmp/go-build/cgo-gcc-prolog:98: undefined reference to `_wrap_mbAdd_mabain_001887ee45ff3f46'
/tmp/go-build216038269/b001/_x002.o: In function `_cgo_86b9c1fc6a54_Cfunc__wrap_mbFind_mabain_001887ee45ff3f46':
/tmp/go-build/cgo-gcc-prolog:131: undefined reference to `_wrap_mbFind_mabain_001887ee45ff3f46'
/tmp/go-build216038269/b001/_x002.o: In function `_cgo_86b9c1fc6a54_Cfunc__wrap_mbOpen_mabain_001887ee45ff3f46':
/tmp/go-build/cgo-gcc-prolog:150: undefined reference to `_wrap_mbOpen_mabain_001887ee45ff3f46'
/tmp/go-build216038269/b001/_x002.o: In function `_cgo_86b9c1fc6a54_Cfunc__wrap_mbRemove_mabain_001887ee45ff3f46':
/tmp/go-build/cgo-gcc-prolog:170: undefined reference to `_wrap_mbRemove_mabain_001887ee45ff3f46'
/tmp/go-build216038269/b001/_x002.o: In function `_cgo_86b9c1fc6a54_Cfunc__wrap_mb_query_result_data_get_mabain_001887ee45ff3f46':
/tmp/go-build/cgo-gcc-prolog:188: undefined reference to `_wrap_mb_query_result_data_get_mabain_001887ee45ff3f46'
/tmp/go-build216038269/b001/_x002.o: In function `_cgo_86b9c1fc6a54_Cfunc__wrap_mb_query_result_get_mabain_001887ee45ff3f46':
/tmp/go-build/cgo-gcc-prolog:219: undefined reference to `_wrap_mb_query_result_get_mabain_001887ee45ff3f46'
/tmp/go-build216038269/b001/_x002.o: In function `_cgo_86b9c1fc6a54_Cfunc__wrap_mb_query_result_len_get_mabain_001887ee45ff3f46':
/tmp/go-build/cgo-gcc-prolog:237: undefined reference to `_wrap_mb_query_result_len_get_mabain_001887ee45ff3f46'
/tmp/go-build216038269/b001/_x002.o: In function `_cgo_86b9c1fc6a54_Cfunc__wrap_new_mb_query_result_mabain_001887ee45ff3f46':
/tmp/go-build/cgo-gcc-prolog:267: undefined reference to `_wrap_new_mb_query_result_mabain_001887ee45ff3f46'
/tmp/go-build216038269/b001/_x002.o: In function `_cgo_86b9c1fc6a54_Cfunc__wrap_Swig_free_mabain_001887ee45ff3f46':
/tmp/go-build/cgo-gcc-prolog:49: undefined reference to `_wrap_Swig_free_mabain_001887ee45ff3f46'
/tmp/go-build216038269/b001/_x002.o: In function `_cgo_86b9c1fc6a54_Cfunc__wrap_delete_mb_query_result_mabain_001887ee45ff3f46':
/tmp/go-build/cgo-gcc-prolog:79: undefined reference to `_wrap_delete_mb_query_result_mabain_001887ee45ff3f46'
/tmp/go-build216038269/b001/_x002.o: In function `_cgo_86b9c1fc6a54_Cfunc__wrap_mbClose_mabain_001887ee45ff3f46':
/tmp/go-build/cgo-gcc-prolog:113: undefined reference to `_wrap_mbClose_mabain_001887ee45ff3f46'
/tmp/go-build216038269/b001/_x002.o: In function `_cgo_86b9c1fc6a54_Cfunc__wrap_mb_query_result_data_set_mabain_001887ee45ff3f46':
/tmp/go-build/cgo-gcc-prolog:204: undefined reference to `_wrap_mb_query_result_data_set_mabain_001887ee45ff3f46'
/tmp/go-build216038269/b001/_x002.o: In function `_cgo_86b9c1fc6a54_Cfunc__wrap_mb_query_result_len_set_mabain_001887ee45ff3f46':
/tmp/go-build/cgo-gcc-prolog:253: undefined reference to `_wrap_mb_query_result_len_set_mabain_001887ee45ff3f46'
collect2: error: ld returned 1 exit status
is there any updated procedure with go1.13 ?

Thanks!!

**Comment by wsfulton** [comment]
Please try the latest SWIG version - swig-4.0.1. 

@ianlancetaylor, the newest we test with is Go 1.12, is Go 1.13 meant to work?

**Comment by ianlancetaylor** [comment]
As far as I know that `go build mabain.go` procedure won't work with any version of Go.  It's not the documented procedure.  The best and simplest way is put a `.swig` file in the directory with your Go files, and use `go build` and `go install` as usual.  The go tool will invoke SWIG for you.

**Comment by msherif4** [comment]
I updated to swig 4.0.1 and moved the code in the same go folder even though I am using 
swig -go -c++ -intgosize 64 mabain.swig
when I do go build I get the following :-
Step 28/30 : RUN cd ${MABAIN_SRC}/swig/mabainUt; go build
 ---> Running in a9c6ce1c25c2
# mabain
mabain_c_interface.h:4: Warning 301: class keyword used, but not in C++ mode.
# mabain
In file included from mabain_wrap.c:219:0:
./mabain_c_interface.h:4:1: error: unknown type name 'class'
 class mb_query_result {
 ^~~~~
./mabain_c_interface.h:4:23: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
 class mb_query_result {
                       ^

**Comment by ianlancetaylor** [comment]
For C++ code you  need to name the file with a `.swigcxx` extension.  See http://www.swig.org/Doc4.0/Go.html#Go_running_swig.

**Comment by msherif4** [comment]
more errors now shows up when I run go build
go build	
# mabain
/tmp/go-build944865341/b001/_x006.o: In function `_wrap_Swig_free_mabain_001887ee45ff3f46':
/tmp/go-build/mabain_wrap.cxx:244: multiple definition of `_wrap_Swig_free_mabain_001887ee45ff3f46'
/tmp/go-build944865341/b001/_x005.o:/mabain_src/swig/mabainUt/mabain_wrap.cxx:244: first defined here
/tmp/go-build944865341/b001/_x006.o: In function `_wrap_Swig_malloc_mabain_001887ee45ff3f46':
.....
/tmp/go-build944865341/b001/_x004.o: In function `mbOpen':
./mabain_c_interface.cpp:10: undefined reference to `mabain::CONSTS::ReaderOptions()'
./mabain_c_interface.cpp:12: undefined reference to `mabain::DB::DB(char const*, int, unsigned long, unsigned long, unsigned int)'
./mabain_c_interface.cpp:13: undefined reference to `mabain::DB::is_open() const'
./mabain_c_interface.cpp:14: undefined reference to `mabain::DB::StatusStr() const'
./mabain_c_interface.cpp:11: undefined reference to `mabain::CONSTS::WriterOptions()'
/tmp/go-build944865341/b001/_x004.o: In function `mbFind':
./mabain_c_interface.cpp:44: undefined reference to `mabain::MBData::MBData()'
./mabain_c_interface.cpp:45: undefined reference to `mabain::DB::Find(char const*, int, mabain::MBData&) const'
./mabain_c_interface.cpp:44: undefined reference to `mabain::MBData::~MBData()'
./mabain_c_interface.cpp:44: undefined reference to `mabain::MBData::~MBData()'
/tmp/go-build944865341/b001/_x004.o: In function `mbClose':
./mabain_c_interface.cpp:23: undefined reference to `mabain::DB::Close()'
/tmp/go-build944865341/b001/_x004.o: In function `mbAdd':
./mabain_c_interface.cpp:30: undefined reference to `mabain::DB::Add(char const*, int, char const*, int, bool)'
/tmp/go-build944865341/b001/_x004.o: In function `mbRemove':
./mabain_c_interface.cpp:37: undefined reference to `mabain::DB::Remove(char const*, int)'

**Comment by msherif4** [comment]
the multiple definition because I was doing make as well as go build , once I commented out make I see only the undefined references

**Comment by ianlancetaylor** [comment]
Where are those symbols supposed to be defined?

You may need to use something along the lines of

    go build -ldflags=-extldflags=-lmabain

**Comment by msherif4** [comment]
objdump -t /usr/local/lib/libmabain.so | grep ReaderOptions
0000000000022b70 g     F .text	0000000000000003              _ZN6mabain6CONSTS13ReaderOptionsEv

I tried go build -x -ldflags "-lmabain.so" but still didn't sort it out will keep trying Thanks!!

**Comment by ianlancetaylor** [comment]
The `-l` option would be written as `-lmabain`.  No `.so` suffix.

Basically, `-extldflags` should be exactly what you would pass to a C++ compiler when linking C++ code that uses the library.

**Comment by msherif4** [comment]
for some reason not able to link the lib
go install -x -i -ldflags '-w -extldflags "-lmabain"'
 ---> Running in 41d6d401a1c1
# get https://proxy.golang.org/github.com/golang/protobuf/@v/v1.3.2.mod
# get https://proxy.golang.org/github.com/go-logr/logr/@v/v0.1.0.mod
    # get https://proxy.golang.org/github.com/go-logr/logr/@v/v0.1.0.mod: 200 OK (5.126s)
# get https://proxy.golang.org/github.com/golang/protobuf/@v/v1.3.2.mod: 200 OK (5.127s)
WORK=/tmp/go-build259458237
    mkdir -p $WORK/b001/
swig -version
cd $WORK
/usr/local/go/pkg/tool/linux_amd64/compile -o ./b001/_go_.o -trimpath "$WORK/b001=>" -p main -lang=go1.13 -complete -goversion go1.13 -D _$WORK -c=4 ./swig_intsize.go
cd /mabain_src/swig/mabainUt
swig -go -cgo -intgosize 64 -module mabain -o $WORK/b001/mabain_wrap.cxx -outdir $WORK/b001/ -c++ mabain.swigcxx
CGO_LDFLAGS='"-g" "-O2"' /usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/b001/ -importpath mabain -- -I $WORK/b001/ -g -O2 $WORK/b001/_mabain_swig.go
    cd $WORK
gcc -fno-caret-diagnostics -c -x c - -o /dev/null || true
gcc -Qunused-arguments -c -x c - -o /dev/null || true
gcc -fdebug-prefix-map=a=b -c -x c - -o /dev/null || true
gcc -gno-record-gcc-switches -c -x c - -o /dev/null || true
cd $WORK/b001
TERM='dumb' gcc -I /mabain_src/swig/mabainUt -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -o ./_x001.o -c _cgo_export.c
TERM='dumb' gcc -I /mabain_src/swig/mabainUt -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -o ./_x002.o -c _mabain_swig.cgo2.c
    cd $WORK
g++ -fno-caret-diagnostics -c -x c - -o /dev/null || true
g++ -Qunused-arguments -c -x c - -o /dev/null || true
g++ -fdebug-prefix-map=a=b -c -x c - -o /dev/null || true
g++ -gno-record-gcc-switches -c -x c - -o /dev/null || true
cd /mabain_src/swig/mabainUt
TERM='dumb' g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I $WORK/b001/ -g -O2 -o $WORK/b001/_x003.o -c mabain_c_interface.cpp
    cd $WORK/b001
TERM='dumb' g++ -I /mabain_src/swig/mabainUt -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -o ./_x004.o -c mabain_wrap.cxx
    TERM='dumb' gcc -I /mabain_src/swig/mabainUt -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -o ./_cgo_main.o -c _cgo_main.c
cd /mabain_src/swig/mabainUt
TERM='dumb' g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -o $WORK/b001/_cgo_.o $WORK/b001/_cgo_main.o $WORK/b001/_x001.o $WORK/b001/_x002.o $WORK/b001/_x003.o $WORK/b001/_x004.o -g -O2
    # mabain
/tmp/go-build259458237/b001/_x003.o: In function `mbOpen':
./mabain_c_interface.cpp:10: undefined reference to `mabain::CONSTS::ReaderOptions()'
./mabain_c_interface.cpp:12: undefined reference to `mabain::DB::DB(char const*, int, unsigned long, unsigned long, unsigned int)'
./mabain_c_interface.cpp:13: undefined reference to `mabain::DB::is_open() const'
./mabain_c_interface.cpp:14: undefined reference to `mabain::DB::StatusStr() const'
./mabain_c_interface.cpp:11: undefined reference to `mabain::CONSTS::WriterOptions()'
/tmp/go-build259458237/b001/_x003.o: In function `mbFind':
./mabain_c_interface.cpp:44: undefined reference to `mabain::MBData::MBData()'
./mabain_c_interface.cpp:45: undefined reference to `mabain::DB::Find(char const*, int, mabain::MBData&) const'
./mabain_c_interface.cpp:44: undefined reference to `mabain::MBData::~MBData()'
./mabain_c_interface.cpp:44: undefined reference to `mabain::MBData::~MBData()'
/tmp/go-build259458237/b001/_x003.o: In function `mbClose':
./mabain_c_interface.cpp:23: undefined reference to `mabain::DB::Close()'
/tmp/go-build259458237/b001/_x003.o: In function `mbAdd':
./mabain_c_interface.cpp:30: undefined reference to `mabain::DB::Add(char const*, int, char const*, int, bool)'
/tmp/go-build259458237/b001/_x003.o: In function `mbRemove':
./mabain_c_interface.cpp:37: undefined reference to `mabain::DB::Remove(char const*, int)'
collect2: error: ld returned 1 exit status
    The command '/bin/sh -c cd ${MABAIN_SRC}/swig/mabainUt; go install -x -i -ldflags '-w -extldflags "-lmabain"'' returned a non-zero code: 2

**Comment by msherif4** [comment]
I added my code and how to build here https://github.com/msherif4/mabain/tree/gointerface/swig/golang
hopefully we can collaborate
