### ISSUE TITLE
Remove support for umaintained Node.js versions

### ISSUE THREAD

**Issue by yegorich** [swig/swig#1735]
Is there any plan to get rid of the old Node.js versions?

Latest Version | Release Date
------------ | -------------
0.10.48 | 2016-10-18
0.12.18 | 2017-02-22
4.9.1 | 2018-03-29
6.17.1 | 2019-04-03
8.17.0 | 2019-12-17

The background is, I'm trying to take over https://github.com/swig/swig/pull/1702. Getting rid of these old versions would bump v8 to 5.1.x thus, it will greatly simplify the code. For example, we could safely change all v8::Handle occurrences to v8::Local (see [here](https://www.electronjs.org/blog/nodejs-native-addons-and-electron-5) for more information).

I don't know how many people still use these old Node.js versions with SWIG. Hence, it is just a suggestion.

**Comment by lissyx** [comment]
@yegorich I guess from the discussion on https://github.com/swig/swig/issues/1520 it would be fine.

**Comment by yegorich** [comment]
But can this still be done for SWIG 4.x?

According to that discussion only v0.10 and v0.12 should be dropped. But can we also agree on removing v4 as well?

I am using [nvm](https://github.com/nvm-sh/nvm) to manage multiple Node.js versions and I have trouble installing node-gyp for versions older than v6.

@wsfulton @mochizk

**Comment by yegorich** [comment]
If I look at Debian libv8 [packages](https://packages.debian.org/search?keywords=libv8), it looks like it will be replaced via Node.js. See [libnode-dev](https://packages.debian.org/buster/libnode-dev) package.

**Comment by yegorich** [comment]
Do I also understand it correctly that if we remove support for the stand-alone v8 engine, we don't need `Tools/javascript/v8_shell.cxx`?

**Comment by vadz** [comment]
FWIW we only use Node 10 or higher, and AFAICS dropping all versions before 8 would simplify the code even more. This could be too drastic, of course...

**Comment by wsfulton** [comment]
Please see #1520 for a discussion on removal of older versions of Javascript. Removal of the older versions missed the boat for the swig-4.0.x series, so as it stands this patch can only be used for swig-4.1.0 and later. I intend to release-4.0.2 quite soon. Right now there is no target date for 4.1 though as we don't have many patches for the larger 4.1 release, see https://github.com/swig/swig/milestone/3. A patch to swig-4.0.1 for adding in support for newer Javascript versions that don't work, #1735, is very much encouraged though.

**Comment by yegorich** [comment]
OK. Then I'll create my own PR based on https://github.com/swig/swig/pull/1702 and try to get it through CI.

**Comment by wsfulton** [comment]
@yegorich. Can you explain the motivation please for getting rid of 'standalone' v8 and why that is okay? Does it mean we'd get rid of the `-v8` option with `swig -javascript`?

**Comment by yegorich** [comment]
@wsfulton For v8 CI test we install `libv8-dev` package. When I understand it correctly, it is now a virtual package that points to Node.js package (see Debian [database](https://packages.debian.org/en/sid/libv8-dev)). Hence my question, does it still make sense to support Linux distribution-specific Node.js version or just rely on nvm?

**Comment by wsfulton** [comment]
I'm not sure what v8 users expect. If v8 is just a wrapper around node, then dropping SWIG's `-v8` seems sensible, but that wasn't part of your patch in #1746. It looks like there is just a slight difference in the generated code for v8 and node. Seems more sensible if we drop both `-v8` and CI testing for it, or leave as is.

**Comment by yegorich** [comment]
I'm also not sure about that. [v8](https://v8.dev/) is actually a foundation for Node.js but can also be used stand-alone. The problem is, no Linux distro seems to package now. The only sensible way for me seems to be using [Docker image for v8](https://github.com/andreburgaud/docker-v8). Though I have no experience with using v8 directly.

It wasn't part of #1746 because it was a parallel development i.e. another approach via eliminating older versions.

**Comment by vadz** [comment]
There doesn't seem to be many differences between `-v8` and `-node` options anyhow, the only one I can see is that the latter predefines `BUILDING_NODE_EXTENSION=1` (which, somewhat confusingly, is also done manually in `Examples/test-suite/javascript/Makefile.in`). So in principle we could remove one of the options, but removing `-v8` seems undesirable because this is what is used in the code and in the paths for the files under `Lib/javascript`, so it seems like a more natural name (unless we also want to rename everything else). And keeping `-node` doesn't really cost anything and it's probably more user-friendly than `-v8` because more clear for most people.

So I'm not really sure we want/need to do anything about this, there is no real problem here AFAICS. The only thing to do would be to explain things more clearly in the docs, but this would need to wait until #1844 is dealt with.

**Comment by ojwb** [comment]
`Doc/Manual/Javascript.html` says:

> The generator for <code>node</code> is essentially delegating to the <code>v8</code> generator and adds some necessary preprocessor definitions.

So these options are even documented to be very similar.

**Comment by wsfulton** [comment]
The minimum version was changed from v8 version 0.10 to v8 version 6 in #1746 for swig-4.1.
