### ISSUE TITLE
SWIG Scilab generated gateways are not compatible with Scilab 6.1.0 

### ISSUE THREAD

**Issue by davidcl** [swig/swig#1737]
Scilab 6.1.0 introduced zero output argument detection which allows any gateway to have a special behavior without output argument. This effectively change the behavior of `CheckOutputArgument(pvApiCtx, 1, 1)` where the minimal number of output arguments could not be ignored (as it was the case before Scilab 6.1).

IMHO the code generator should be updated to only use `CheckOutputArgument(pvApiCtx, 0, 1)` everywhere.

**Comment by wsfulton** [comment]
Ping @smarchetto, could you take a look please?
