### ISSUE TITLE
Suggestions needed: char** <-> Java String[] interop 

### ISSUE THREAD

**Issue by AlbertoEAF** [swig/swig#1740]
Hello,

At LightGBM we need String[] interop (arrays of strings) between Java and C++/C char** arrays, which need to be allocated and manipulated on the C++ side and read on the Java side.

I have little to no experience in SWIG, thus generated this interfacing code which does the job correctly.
It relies on the already existing char* <-> String Java typemaps by creating a C++ class that encapsulates the memory management of an array of fixed length strings (char**) and is able to return a (char*) to the target language.

 I just wanted to know if this sounds reasonable for you (https://github.com/AlbertoEAF/LightGBM/blob/feat/swig-strings/swig/char_array_helpers.i) or if you suggest a fancier alternative to handle this mapping with some Java typemaps for String[] which I have no idea how to implement.

You can otherwise look at the original issue that prompted for this question: https://github.com/microsoft/LightGBM/issues/2814

**Comment by wsfulton** [comment]
There are some supporting typemaps for mapping NULL terminated arrays of C strings to Java String arrays, see https://github.com/swig/swig/blob/rel-4.0.1/Lib/java/various.i. Perhaps they can be of use or of course you can copy and adapt for the behaviour of the LightGBM code for memory management.

A test of these typemaps is in the distribution:
https://github.com/swig/swig/blob/rel-4.0.1/Examples/test-suite/java_lib_various.i
https://github.com/swig/swig/blob/rel-4.0.1/Examples/test-suite/java/java_lib_various_runme.java

**Comment by AlbertoEAF** [comment]
Thank you so much @wsfulton , I'll study the code more carefully and discuss with the LightGBM devs.
