### ISSUE TITLE
Instantiate %template in a non-global namespace

### ISSUE THREAD

**Issue by matze** [swig/swig#1741]
Considering the following interface
```
%module test

%nspace foo::Foo;

%include <std_vector.i>

namespace std {
%template(FooIntVector) vector<int>;
}

#include <vector>

namespace foo {
    struct Foo {
        std::vector<int> ints;
    };
}
```
from which I generate a Java wrapper via
```bash
$ swig4.0 -c++ -java -package foo -outdir output test.i
```
Is it possible to have the `FooIntVector` be part of the `foo` namespace/package?

**Comment by wsfulton** [comment]
std::vector<int> is in the std namespace. Your choices are to have it in the top level namespace (which would be foo if you use `-package foo`) or if you use `%nspace std::vector<int>` it would go into the std subpackage as vector is in the C++ std namespace. So your choices are `foo.std.FooIntVector` or `foo.FooIntVector` when using `-package foo`. Incidentally the C++ class `foo::Foo` would then be `foo.foo.Foo` (with `-package foo`) or `foo.Foo`.

If you are prepared to mess around with typemaps, you can probably put it in any package you want.

**Comment by matze** [comment]
> So your choices are `foo.std.FooIntVector` or `foo.FooIntVector` when using -package foo.

The latter is what I'm trying to achieve but the `FooIntVector` does not end up in the package `foo` but the root output directory. Can that then be considered a bug?

**Comment by wsfulton** [comment]
The root output directory and package are not necessarily the same thing. Try this:
```swig
%module test

SWIG_JAVABODY_PROXY(public, public, SWIGTYPE) // change default visibility of some elements in proxy class from protected to public so that the proxy classes can be created from different packages.

%nspace foo::Foo;
// Because %nspace is not used everywhere and foo.foo.Foo has a dependency on foo.FooIntVector (in a different package)
%typemap(javaimports) foo::Foo "import foo.FooIntVector;"

%include <std_vector.i>

namespace std {
%template(FooIntVector) vector<int>;
}

#include <vector>

%inline %{
namespace foo {
    struct Foo {
        std::vector<int> ints;
    };
}
%}
```
Run:
```swig -java -c++ -package foo -outdir foo test.i```

You will see the file foo/FooIntVector.java and the first line of code contains the appropriate package statement:
```java
package foo;
```

**Comment by matze** [comment]
> The root output directory and package are not necessarily the same thing.

I know and my expectation was that those templated classes would become part of the package. But yes, looks like "re-importing" that class seems to be the only viable option for now. Thank you very much for your detailed responses!

**Comment by wsfulton** [comment]
Looks sorted.
