### ISSUE TITLE
Error with quotes in Doxygen comment

### ISSUE THREAD

**Issue by mdouze** [swig/swig#1747]
Hi 

We are using SWIG to wrap a large C++ library (https://github.com/facebookresearch/faiss), thanks for this awesome tool!

We are planning to migrate to SWIG 4 to translate the Doxygen comments to python docstrings. 

It seems that the docstring generated when there are double quotes in the doxygen comments can be invalid in 4.0.1 and the current github version. 

To repro:  

```
matthijs@devvm4948:/tmp $ cat > tt.i
%module tt

/// blabla "oh"
void f();
matthijs@devvm4948:/tmp $ /data/users/matthijs/swig4/swig/installed/bin/swig  -doxygen -python -c++ tt.i
matthijs@devvm4948:/tmp $ python3 tt.i
  File "tt.i", line 1
    %module tt
    ^
SyntaxError: invalid syntax
```

**Comment by vadz** [comment]
Thanks for the bug report, but you confused me for a moment there as I was wondering why would you run python on SWIG input file. The real problem is, of course:
```
% python3 tt.py
  File "tt.py", line 66
    r""" blabla "oh""""
                      ^
SyntaxError: EOL while scanning string literal
```

I.e. this happens when there is quote at the end of Doxygen comment and could be worked around by just adding a space before the closing `"""` in SWIG code. I wonder if we could do it unconditionally or could this have any negative consequences (that I don't see right now)?

**Comment by mdouze** [comment]
ah sorry, yes it's a copy/paste error. 

A few additional tests: 

- if the quotes are at the beginning it's not a problem because SWIG inserts a space in front

- it triple quotes """" are used in the string it fails again. Not sure how that could happen in "normal" code.

**Comment by vadz** [comment]
Both problems should be fixed in #1748.

**Comment by wsfulton** [comment]
Shouldn't we generate the following if the last character is double quote:
```python
r""" blabla "oh""" '"'
```
or
```python
r""" blabla "oh""" "\""
```
I don't think we should solve it by adding in a space.

If I've understood the patch correctly, the string will then have a visible backslash in it??? I may have that wrong though.

**Comment by vadz** [comment]
> Shouldn't we generate the following if the last character is double quote:
> 
> ```python
> r""" blabla "oh""" '"'
> ```
> 
> or
> 
> ```python
> r""" blabla "oh""" "\""
> ```

This would indeed work. It's, of course, rather ugly, so perhaps it would be better to generate
```python
r''' blabla "oh"''''
```
instead?

> I don't think we should solve it by adding in a space.

Yes, I agree, this was just the first thing that came to mind.
 
> If I've understood the patch correctly, the string will then have a visible backslash in it??? I may have that wrong though.

No, you're right, I forgot that we used _raw_ triple-quoted strings and so backslash doesn't actually work as escape character in them, although it still does escape the quote (reading the last paragraph of [the manual](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals) shows just how confusing this is).

**Comment by wsfulton** [comment]
#1748 fixes this.
