### ISSUE TITLE
Runtime type discovery / refelection [including in native C/C++]?

### ISSUE THREAD

**Issue by dtugend** [swig/swig#1753]
I am interested in making use of Swig's internal type information / code comments at run-time, including in native C/C++ code (so might need a Swig to C/C++ as well, preferably C).

The reason is that I plan to do a plugin system that is extensible and I'd like people / code to be able to discover new / unknown interfaces at run-time.

I looked in the 4.0 documentation, but could not find something related to that and are new to Swig.

My question is if there's already code or things I can use related to that?
Other option is contributing the missing parts to Swig, but I am not sure if I will have enough time and motivation to do that in the near future to be honest.

**Comment by dtugend** [comment]
Just noticed that this means license problems, since SWIG is some sort of GPLv3 and the utility functions would be GPLv3 too then I guess 😢

**Comment by vadz** [comment]
Just for the record, the licence of SWIG has no bearing on the licence of the code generated by SWIG, in the same way as all code compiled by gcc doesn't automatically fall under GPL neither, even though gcc  itself is GPL.

**Comment by dtugend** [comment]
Thank you for your time and reply.

> Just for the record, the licence of SWIG has no bearing on the licence of the code generated by SWIG, in the same way as all code compiled by gcc doesn't automatically fall under GPL neither, even though gcc itself is GPL.

This is probably true, however I was worried about the usage of current or future utility functions for type discovery and using these would cause problems, for example the libstdc++ has special exceptions for exactly that reason, see "2.2. | So any program which uses libstdc++ falls under the GPL?" at https://gcc.gnu.org/onlinedocs/libstdc++/faq.html#faq.license.what - SWIG currently has no such exceptions, so that use case I had in mind would be a problem.

**Comment by vadz** [comment]
The files under `Lib` are covered by

```
  You may copy, modify, distribute, and make derivative works based on
  this software, in source code or object code form, without
  restriction. If you distribute the software to others, you may do
  so according to the terms of your choice. This software is offered as
  is, without warranty of any kind.
```

see SWIG LICENSE file.

**Comment by dtugend** [comment]
You are right and I am wrong, sorry. I only made it to the GPLv3 part and gave up at that point.
Sorry.

So I could use SWIG without problems if the functions were in that folder.

Would it be okay to reopen the issue in the hope of future comments / ideas, or is that against the rules?

**Comment by vadz** [comment]
To be honest, I don't think this is really a good issue: it doesn't seem to be about anything concrete, i.e. I have no idea what would need to be done in order to close it. Perhaps it would be useful to post to swig-devel mailing list explaining better what do you want to do in some more details and what exactly is lacking in SWIG to allow it and what could be done about it. Good luck!
