### ISSUE TITLE
Using multiple CPU cores with Golang

### ISSUE THREAD

**Issue by elgatito** [swig/swig#1756]
Hello guys.

First of all, thanks for your great work with Swig and especially, Golang extension.

I have a project, where I use Swig to make Golang bindings to C++ library.

When I run `go install`, I see that `swig` is called, then `cc1` is called to compile everything.
And I see that this process is using only one CPU, and the library is pretty big, so compilation takes sometimes a minute. 

Is there a way to use multiple CPUs for CGO compilation?

Not sure this issue is applicable to Swig or Golang team...

**Comment by ojwb** [comment]
That seems to be a question for the Golang team - it's `go install` that runs the compilation not SWIG.
