### ISSUE TITLE
Doxygen parser misses space after \endlink

### ISSUE THREAD

**Issue by HenningJ** [swig/swig#1757]
When using `\link ...\endlink` inside a sentence in the doxygen docu, the parser misses/ignores the space after the `\endlink` tag.

```
struct Foo
{
  /// This is a link to \link b another member\endlink inside a sentence.
  int a;
  int b;
};
```
=> `...another member</a>inside...`

**Comment by mcfarljm** [comment]
Fixed in PR # 1788

**Comment by wsfulton** [comment]
#1788 has been merged.
