### ISSUE TITLE
ETA on Node 12 support 

### ISSUE THREAD

**Issue by wolfviking0** [swig/swig#1760]
Hi, I am using SWIG and I would like to move to a more recent version of node.

I am currently a patch in order to have SWIG running with node 12, but do you have any ETA for an official support from SWIG repository ?

**Comment by yegorich** [comment]
@wolfviking0 if you can find a solution for the `SWIG_Object` definition that I mentioned in https://github.com/swig/swig/pull/1746, support for Node v12/13 can even land in SWIG 4.0.2.
