### ISSUE TITLE
Warning Electron non-context-aware

### ISSUE THREAD

**Issue by wolfviking0** [swig/swig#1761]
I am building Node file using swig generated file.

When I load I have a warning:
```
(node:1824) Electron: Loading non-context-aware native module in renderer: 
This is deprecated, see https://github.com/electron/electron/issues/18397.
```

Any suggestion regarding this one.

Thanks

**Comment by ojwb** [comment]
Should be fixed by b0c01ea85117ba50754aeeaa18875f8bcdae6279.  That will debut in 4.1.0 but meanwhile please test with git and report back if there are any issues.
