### ISSUE TITLE
SWIG Python MinGW64 C++ extensions linked to ucrtbase still crash

### ISSUE THREAD

**Issue by andrewg22** [swig/swig#1763]
Python extensions compiled with MinGW64 7.0.0 (GCC 9.2) should be compatible with recent versions of Windows CPython (which use the ucrt run time rather than msvcrt) if linker options -lucrtbase and -static are used. I have several extensions with interfaces handcoded in C and Fortran working. I have so far failed to make C++ extensions wrapped with SWIG work - they crash when the binary extension is imported. I reported this on the MinGW64 support list - where some examples files are given. The same code compiled and worked on 64-bit Ubuntu.

https://sourceforge.net/p/mingw-w64/support-requests/154/

The compiler/linker commands that I used are given in the pysimcpp.h file. Any help would be gladly appreciated.

**Comment by jschueller** [comment]
it's not swig responsibility to link properly, so not a swig bug

**Comment by ojwb** [comment]
Agreed.  Also according to the linked bug the submitter has solved this:

>Good news: There's now a UCRT toolchain for MSYS2, which fixes the problem.

>pacman -S mingw-w64-ucrt-x86_64-toolchain

>This toolchain installs to MSYS2\ucrt64). To produce a working extension for a 64-bit Python (e.g. 3.8), put this directory on Windows PATH, then compile and link the SWIG wrapper. The necessary commands are given as comments in pysimcpp.h.

>From what I've read, the libstdc++ in MSYS2\Mingw64 is built against msvcrt - which is why C++ extensions linked to ucrt with the normal MinGW64 toolchain crash.
