### ISSUE TITLE
Unclear how to transition from writing Source/Modules/mylang.cxx to working on structuring .swg files

### ISSUE THREAD

**Issue by ahungry** [swig/swig#1768]
https://github.com/ahungry/swig/blob/feature/Add-janet/Source/Modules/janet.cxx#L187

Please see the above link - I'm working on adding a new language (Janet - janet-lang.org), and have been following the guide here:

http://www.swig.org/Doc1.3/Extending.html#Extending_nn39

But at the point it goes into the configuration files, I find it hard to know where to go next, while up until now the guide was more of a step-by-step that took me to the point of setting up my functionWrapper method.

In my original link (line 187) you can see where I added a method / switch construct to translate from the C type to the Janet stuff that is applicable - I feel like this probably belongs in a .swg typepmap, but where and how does that get defined and executed? (Maybe it was mentioned, but I read fast/skimmed over the large technical breakdown before reaching the "Adding a new language" step by step guide).

**Comment by ojwb** [comment]
You're looking at a version of those docs that's over a decade old - the current version is:

http://www.swig.org/Doc4.0/Extending.html#Extending_configuration_files

The current version is improved and more up to date, though I don't think it's very different in this particular area.

It's kind of hard to offer more precise advice here - you need to write autoconf probes to find whatever is needed to compile and run testcases under janet, but I have no idea what that involves.  If Janet is kind of like another support language you could look at how that one is handled (e.g. if it's a scripting language like Python, etc or a compiled language like Java).

The `.swg` typemaps for janet would be in the `Lib/janet/` directory (again look at a similar language for clues).

**Comment by ahungry** [comment]
Thanks!
