### ISSUE TITLE
DOH_POOL_SIZE tweaking

### ISSUE THREAD

**Issue by yairl** [swig/swig#1775]
swig is awesome.

Running it on a large code base is sometimes very slow.
Large in this case means generated swig_wrap is ~700k lines for one module, and we have several similar ones) takes ~7 minutes on a nice, unloaded machine with 32 cores, 256G memory.

Some basic profiling showed that DohCheck() is very expensive; apparently just looking through the pools is now expensive as so much memory is allocated.
Changing the default pool size for 2^14 to 2^22 (16K->4M) made this go away, with processing dropping to <1 minute.

Will be nice if you can either tweak the default (4M isn't a lot these days), or add a argument to the swig binary to control that in runtime.

Highly appreciated, and thanks for swig.

**Comment by ZackerySpytz** [comment]
I agree that the value of DOH_POOL_SIZE should be increased. I've opened GH-1776.

**Comment by wsfulton** [comment]
Implemented by #1776.
