### ISSUE TITLE
Javascript [PACKETS PROBLEM]

### ISSUE THREAD

**Issue by Alexander9673** [swig/swig#1778]
Hello, so i am using https://github.com/linluxiang/node-enet . It uses swig, and i was wandering, when i was receiving packets from it, and access the `data` property by doing `packet.data` , it keeps showing `SwigProxy {}`. Any reason why?

**Comment by vadz** [comment]
Sorry, this is not a SWIG question. It's up to the module developers to implement showing their data in an appropriate way.
