### ISSUE TITLE
Support typemaps for unique pointer

### ISSUE THREAD

**Issue by tobegit3hub** [swig/swig#1781]
Since smart pointers including share pointer and unique are parts of C++11 standard, swig provides the support of  `std_shared_ptr.i` and `boost_shared_ptr.i`. But there is no typemaps and other support for unique pointer now.

I'm not sure if there is technical limitation to support typemap for unique pointers or not. It would be better we can support this feature in the future.

**Comment by vadz** [comment]
This seems to be identical to #692

**Comment by tobegit3hub** [comment]
Thanks @vadz and sorry for the duplicated issue.
