### ISSUE TITLE
Forward declaration of templated class not seen if in a separate header which is included

### ISSUE THREAD

**Issue by gabrieldevillers** [swig/swig#1784]
tested in SWIG 4.0.1

### Reproductible example based on `Examples/csharp/template`
**forward_declarations.hpp:**
>template\<class T> class vector;
>using vecdouble = vector\<double>;

**example.h:**
>#include "forward_declarations.hpp"
>template<class T>
>class vector {
>public:
>	T x;
>};
>void Print(const vecdouble& v); // this line triggers the problem

**example.i**:
>%module example
>%{
>#include "example.h"
>%}
>%include "example.h"
>%template(vecdouble) vector<double>;

### Problems:
- file `SWIGTYPE_p_vecdouble.cs` is created even though there already is `vecdouble.cs`
- the C# prototype of the Print wrapper is: `public static void Print(SWIGTYPE_p_vecdouble v)`
- same behavior if `const vecdouble&` is replaced by `vecdouble`

### Workaround:
Add this in `example.h` after `#include "forward_declarations.hpp"`:
>#ifdef SWIG
>using vecdouble = vector\<double>;
>#endif

### Questions
- is there a better workaround ? (without modifying the C++ source ?)
- is this a bug in SWIG ?
- if yes, where should I search for it if I wanted to fix it ?

Thank you for SWIG, it works well in almost all cases!

**Comment by ojwb** [comment]
SWIG doesn't follow `#include` in nested files by default.  See `-includeall` if you want to change that, but beware it'll probably work badly if any system headers are included because SWIG will then try to parse and wrap everything in those.

Your workaround is probably the way to go.

**Comment by gabrieldevillers** [comment]
@ojwb thank you for this explanation :) , I guess I should have grepped the manual for "include". Feel free to close this issue.

**Comment by gabrieldevillers** [comment]
Other workaround: add #include "forward_declarations.hpp" to example.i:

%module example
%{
#include "example.h"
%}
%include "forward_declaration.hpp" # <- addition
%include "example.h"
%template(vecdouble) vector;

**Comment by ojwb** [comment]
Oh sorry, I misread what you said were doing as a workaround.

Adding `%include "forward_declaration.hpp"` to `example.i` is actually what I'd recommend.
