### ISSUE TITLE
Generated Java class for std::vector complains about missing symbol 'reserve'

### ISSUE THREAD

**Issue by baoilleach** [swig/swig#1787]
Using swigwin 4.0.1, and the interface file at https://github.com/openbabel/openbabel/blob/f96f03580e0844ab366b0d19d1757253824ed65f/scripts/openbabel-java.i, I see (for example):

```
  java\org\openbabel\vectorInt.java:41: error: cannot find symbol
      reserve(initialElements.length);
      ^
    symbol:   method reserve(int)
    location: class vectorInt 
```

The interface file removes ```reserve``` and other methods to reduce the size of the bindings, but the Java code should still work, right? It certainly used to, for an earlier version of SWIG.

[vectorvInt.txt](https://github.com/swig/swig/files/4567586/vectorvInt.txt)

**Comment by wsfulton** [comment]
I'm afraid that `reserve` is required when using std_vector.i to wrap `std::vector`. It is called to provide an important performance optimisation from one of the Java constructors. Unfortunately the addition of this constructor cannot be easily modified by a user of `std_vector.i`.
