### ISSUE TITLE
[Clang build] Swig 4.0.1 not compatible with Python 3.8

### ISSUE THREAD

**Issue by suamor** [swig/swig#1790]
I opened a Canorus issue some time ago because I cannot build a swig 4.0.1 generated interface to python. In python 3.8 tp_print was deprecated causing build issues with swig.

https://github.com/canorusmusic/canorus/issues/163

I applied a development patch (pull-request) to swig 4.0.1 that should fix the issue but it seems it does not or not fully fix the build issue:

`src/canoruspythonPYTHON_wrap.cxx:1764:7: error: 'tp_print' is deprecated
      0,                                    /* tp_print */
      ^`

The generated code looks like this:
`#if (PY_VERSION_HEX >= 0x03080000) && (PY_VERSION_HEX < 0x03090000)
      0,                                    /* tp_print */
#endif
`
This looks to me like an incorrect version check. It should be
#if (PY_VERSION_HEX >= 0x03070000) && (PY_VERSION_HEX < 0x03080000)
      0,                                    /* tp_print */
#endif

Even then I think the minimum version is not correct (should be older, but I do not know since when tp_print is in use).

**Comment by suamor** [comment]
When I change version number I can reduce the number of deprecated issues to 2. So there is one more unpatched tp_print somewhere in the python swig files.

**Comment by suamor** [comment]
Update: I think this issue is not directly a swig issue, even though it occurs in swig code. 
Currently I see no other way but silence this issue until some solution is found.
https://github.com/pandas-dev/pandas/issues/33239.

Drawback is that any deprecation within swig and python will no longer be seen.

**Comment by Dekken** [comment]
we can reproduce this also please see our logs here:
https://github.com/X-DataInitiative/tick/runs/724565000?check_suite_focus=true#step:6:134

**Comment by wsfulton** [comment]
Warning suppression seems to be the only way forward.
