### ISSUE TITLE
compilation failing because of C++ style comment

### ISSUE THREAD

**Issue by RMeli** [swig/swig#1795]
`swig`(ae0efd3d742ad083312fadbc652d4d66fdad6f4d) compilation fails with the following error:

```
make[1]: Entering directory 'XXX/swig/Source'
make  all-am
make[2]: Entering directory 'XXX/swig/Source'
depbase=`echo CParse/parser.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H   -I../Source/Include -I../Source/CParse -I../Source/Include -I../Source/DOH -I../Source/CParse -I../Source/Doxygen -I../Source/Preprocessor -I../Source/Swig -I../Source/Modules   -g -O2 -Wall -W -ansi -pedantic -MT CParse/parser.o -MD -MP -MF $depbase.Tpo -c -o CParse/parser.o CParse/parser.c &&\
mv -f $depbase.Tpo $depbase.Po
CParse/parser.c: In function ‘yyparse’:
CParse/parser.c:13053:3: error: C++ style comments are not allowed in ISO C90
   // Pop stack until we find a state that shifts the error token.
   ^
CParse/parser.c:13053:3: error: (this will be reported only once per input file)
Makefile:930: recipe for target 'CParse/parser.o' failed
make[2]: *** [CParse/parser.o] Error 1
make[2]: Leaving directory 'XXX/swig/Source'
Makefile:599: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory 'XXX/swig/Source'
Makefile:37: recipe for target 'source' failed
make: *** [source] Error 2
```

Changing the C++ style comment in `CParse/parser.c:13053:3` (created by `./configure`?) to a C style comment solves the problem (compilation terminates and all Python tests pass).

## Steps to Reproduce

```
git clone https://github.com/swig/swig.git
cd swig

./autogen.sh
./configure
make -j 6
```

## Infos

OS: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-99-generic x86_64)
GCC: 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
Python: 2.7.17
Python 3: 3.6.9

**Comment by vadz** [comment]
Looks like a bug in yacc to me, as this comment doesn't come from our `parser.y`. Not sure what can we do about it, other than stopping using `-pedantic`.

**Comment by RMeli** [comment]
Makes sense, thanks. FYI, I used [GNU Bison](https://www.gnu.org/software/bison/) instead of `yacc`.

**Comment by RMeli** [comment]
This [appears to be fixed](https://lists.gnu.org/archive/html/bug-bison/2020-05/msg00100.html) in Bison `3.6.1` (I used `3.6.0`).
