### ISSUE TITLE
Invalid wrapper code for returning pointers to director-enabled instances

### ISSUE THREAD

**Issue by treitmayr** [swig/swig#1811]
The following code results in bad wrapper code being generated for the methods `Storage<Element*>::getPtr()` and (less obvious) `Storage<Element*>::getVal()`. This can be observed for Ruby, other languages have not yet been tested. The used swig version is current git HEAD (4.0.2 - ba0154d90a0e4783675e4ecc582cc345903c323c).

Interface definition file **director_template.i**
```cpp
%module(directors="1") director_template

%warnfilter(SWIGWARN_TYPEMAP_DIRECTOROUT_PTR) Storage;

%feature("director") Element;

%inline %{

class Element {
  public:
    virtual ~Element() {}
};

template<class T> class Storage {
   T val;
 public:
   Storage(T v) : val(v) {}
   virtual ~Storage() {}
   virtual T getVal()
   {
     return val;
   }
   virtual T *getPtr()
   {
     return &val;
   }
};

%}

%template(ElementStorage) Storage<Element>;
%template(ElementPtrStorage) Storage<Element *>;
```
For the Ruby wrapper code, the compiler complains in the wrapper of `Storage<Element*>::getPtr()`:
```
director_template_wrap.cxx: In function 'VALUE _wrap_ElementPtrStorage_getPtr(int, VALUE*, VALUE)':
director_template_wrap.cxx:2599:51: error: cannot dynamic_cast 'result' (of type 'class Element**') to type 'class Swig::Director*' (source is not a pointer to class)
   director = dynamic_cast<Swig::Director *>(result);
                                                   ^
```
The root cause can be seen in the XML output of Swig for `Storage<Element*>::getPtr()` (only relevant parts shown):
```xml
<cdecl>
    <attributelist>
        <attribute name="name" value="getPtr"/>
        <attribute name="decl" value="f().p."/>
        <attribute name="type" value="p.Element"/>
    </attributelist>
</cdecl>
```
While the method's return type is `Element**`, the above snippet shows that the two pointer qualifiers "p." are partly specified with the "decl" attribute (the trailing "p.") and partly with the "type" attribute (the leading "p.").
This does not conform to the apparent Swig convention, that the pointer and reference qualifiers of the return type are to be specified with the "decl" attribute. In our case this would mean:
  * decl: `f().p.p.`
  * type: `Element`

This convention is used in the methods `SwigType_ispointer_return` and `SwigType_isreference_return` and further on in https://github.com/swig/swig/blob/master/Source/Modules/ruby.cxx#L1896-L1897 for determining whether the processed method returns a pointer resp. reference to a non-pointer/non-reference type. In the above example we should expect `SwigType_ispointer_return` to return a false value, however due to the "p." qualifier being attached to the "type" attribute rather than the "decl" attribute, the wrong decision is taken.

In a similar, but reverse way, the method `Storage<Element*>::getVal()` is affected. However here the `dynamic_cast` to `Swig::Director` (and subsequent code) is not generated where it actually should be.

This issue only affects template instances and seems to be caused by the way template parameter substitution is performed in the course of template instantiation. In Source/CParse/templ.c all used data types and "cdecl" method signatures of a newly created template instance are collected, and then basically a text replace is performed. As far as I can tell there is no subsequent correction of the methods' "cdecl" and "type" attributes being performed.

**Comment by treitmayr** [comment]
The tests have shown that apart from Ruby, the same error happens with Python.

**Comment by treitmayr** [comment]
The same issue can be triggered without the use of template instances. Knowing that
   * a return type "\<Director-Type> *const *" is translated to decl = "f().p.q(const).p.", and
   *  `SwigType_ispointer_return()` just checks decl for a trailing ").p."

allows constructing the following failing test **director_return_type.i** (failing in Ruby and Python, as with the previous case):
```cpp
%module(directors="1") director_return_type

%feature("director") Element;

%inline %{

class Element {
  public:
    virtual ~Element() {}
};

class Storage {
  public:
    Element* const *getPtrPtr() { return nullptr; }
};

%}
```

**Comment by wsfulton** [comment]
For reference, it looks like the example in the last comment is the same one in #1810. With regard to fixing, I think the non-template example should be tackled first.

**Comment by treitmayr** [comment]
In #1810 the return type is `int *const`, while here there is another indirection added in the return type `int *const *`.
Meanwhile I created a PR which fixes both the non-template and the template example.
