### ISSUE TITLE
how can I analysis multi class with swig?

### ISSUE THREAD

**Issue by mahxn0** [swig/swig#1814]
class A
{
     public:
         class B b;
         class C c;
}

there always different error,like: ImportError: /home/training/mxj_workspace/Face/swig/_FeatureExtract.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN9FaceAlign9meanAxis0ERN2cv3MatE

can somebody help me   thank you very much

**Comment by vadz** [comment]
Please provide [minimal but complete example](http://sscce.org/) of what doesn't work for you.

**Comment by mahxn0** [comment]
@vadz   
Feature_Extract.h
`/*
 * @Description: 
 * @Author: mahxn0
 * @Date: 1970-01-01 08:00:00
 * @LastEditors: mahxn0
 * @LastEditTime: 2020-06-08 22:54:49
 */ 
#ifndef _FEATUREEXTRACT_H_
#define _FEATUREEXTRACT_H_
#include"FaceDetect.h"
#include"FaceRecogntion.h"
#include"calc_time.h"
#include"FaceAlign.h"

typedef struct Feature_PATH
{
    std::vector<float>feature;
    std::string imgname;
};
void GetAllFiles(std::string cate_dir,std::vector<std::string>& files);
std::vector<std::vector<Feature_PATH>>  Extract_Feature(std::string model_path,std::string pic_path1,std::string pic_path2);
//std::vector<std::vector<Feature_PATH>> Extract_Feature(char* path,char* path1,char* path2);

#endif //_FEATUREEXTRACT_H_`

Feature_Extract.cpp
`FaceDetect *FaceDet = new FaceDetect(640,640);
    printf("Begin to Initilize FaceDetectOperation\n");
	FaceDet->InitNetWork(paramsConfig);
    
    printf("Begin to create FaceRecogniseOperation\n");
    FaceRecognise *FaceRec=new FaceRecognise(112,112);
    printf("Begin to Initilize FaceRecogOperation\n");
	FaceRec->InitNetWork(paramsConfig1);
    FaceAlign *FaceAl=new FaceAlign();
    std::vector<std::vector<Feature_PATH>>two_fold_feature_name;
    //fold1
    std::vector<Feature_PATH>results_fold1;
    std::vector<std::string> fileNames1;
    GetAllFiles(imagePath1,fileNames1);
	for(int i = 0; i < fileNames1.size(); i++)
	{
		//get image name
		std::string fileName = fileNames1[i];
        fileName=imagePath1+fileName;
        std::cout<<fileName<<std::endl;
        Feature_PATH feature_path;
        feature_path.imgname=fileName;
        cv::Mat image = cv::imread(fileName.c_str());
        printf("Begin to ExtractFeature\n");
        std::vector<float> feature;
        std::vector<float> score;
        std::vector<BOUNDING_BOX> BoundingBox;
        feature.clear();
        BoundingBox.clear();
        score.clear();
        start = GetCurrentTimeMicros();
        FaceDet->Forward(image,BoundingBox);
        end = GetCurrentTimeMicros();
        cout << "DetFace time cost: " << float(end-start)/1000 << "ms" << endl;`



**I  can  sucess generate .so , but when import it, there are some errors like** 
`ImportError: /home/training/mxj_workspace/Face/swig/_FeatureExtract.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN9FaceAlign9meanAxis0ERN2cv3MatE`

`class FaceAlign
{   
    public:
        FaceAlign();
        ~FaceAlign();
        cv::Mat meanAxis0(const cv::Mat &src);
        cv::Mat elementwiseMinus(const cv::Mat &A, const cv::Mat &B);
        cv::Mat varAxis0(const cv::Mat &src);
        int MatrixRank(cv::Mat M);
        cv::Mat similarTransform(cv::Mat src, cv::Mat dst);
};
#endif //_FACEALIGN_H_`

`/*
 * @Description: 
 * @Author: mahxn0
 * @Date: 1970-01-01 08:00:00
 * @LastEditors: mahxn0
 * @LastEditTime: 2020-06-09 00:35:53
 */ 
#include"FaceAlign.h"

FaceAlign::FaceAlign()
{}
FaceAlign::~FaceAlign()
{}
cv::Mat FaceAlign::meanAxis0(const cv::Mat &src)
{
	int num = src.rows;
	int dim = src.cols;

	cv::Mat output(1, dim, CV_32F);
	for (int i = 0; i < dim; i++)
	{
		float sum = 0;
		for (int j = 0; j < num; j++)
		{
			sum += src.at<float>(j, i);
		}
		output.at<float>(0, i) = sum / num;
	}

	return output;
}

cv::Mat FaceAlign::elementwiseMinus(const cv::Mat &A, const cv::Mat &B)
{
	cv::Mat output(A.rows, A.cols, A.type());

	assert(B.cols == A.cols);
	if (B.cols == A.cols)
	{
		for (int i = 0; i < A.rows; i++)
		{
			for (int j = 0; j < B.cols; j++)
			{
				output.at<float>(i, j) = A.at<float>(i, j) - B.at<float>(0, j);
			}
		}
	}
	return output;
}

cv::Mat FaceAlign::varAxis0(const cv::Mat &src)
{
cv::Mat temp_ = elementwiseMinus(src, meanAxis0(src));
	cv::multiply(temp_, temp_, temp_);
	return meanAxis0(temp_);

}

int FaceAlign::MatrixRank(cv::Mat M)
{
	cv::Mat w, u, vt;
	cv::SVD::compute(M, w, u, vt);
	cv::Mat1b nonZeroSingularValues = w > 0.0001;
	int rank = cv::countNonZero(nonZeroSingularValues);
	return rank;

}

//    References
//    ----------
//    .. [1] "Least-squares estimation of transformation parameters between two
//    point patterns", Shinji Umeyama, PAMI 1991, DOI: 10.1109/34.88573
//
//    """
//
//    Anthor:Jack Yu
cv::Mat FaceAlign::similarTransform(cv::Mat src, cv::Mat dst) {
	int num = src.rows;
	int dim = src.cols;
	cv::Mat src_mean = meanAxis0(src);
	cv::Mat dst_mean = meanAxis0(dst);
	cv::Mat src_demean = elementwiseMinus(src, src_mean);
	cv::Mat dst_demean = elementwiseMinus(dst, dst_mean);
	cv::Mat A = (dst_demean.t() * src_demean) / static_cast<float>(num);
	cv::Mat d(dim, 1, CV_32F);
	d.setTo(1.0f);
	if (cv::determinant(A) < 0) {
		d.at<float>(dim - 1, 0) = -1;

	}
	cv::Mat T = cv::Mat::eye(dim + 1, dim + 1, CV_32F);
	cv::Mat U, S, V;
	cv::SVD::compute(A, S, U, V);

	// the SVD function in opencv differ from scipy .


	int rank = MatrixRank(A);
	if (rank == 0) {
		assert(rank == 0);

	}
	else if (rank == dim - 1) {
		if (cv::determinant(U) * cv::determinant(V) > 0) {
			T.rowRange(0, dim).colRange(0, dim) = U * V;
		}
		else {
			//            s = d[dim - 1]
			//            d[dim - 1] = -1
			//            T[:dim, :dim] = np.dot(U, np.dot(np.diag(d), V))
			//            d[dim - 1] = s
			int s = d.at<float>(dim - 1, 0) = -1;
			d.at<float>(dim - 1, 0) = -1;

			T.rowRange(0, dim).colRange(0, dim) = U * V;
			cv::Mat diag_ = cv::Mat::diag(d);
			cv::Mat twp = diag_*V; //np.dot(np.diag(d), V.T)
			cv::Mat B = cv::Mat::zeros(3, 3, CV_8UC1);
			cv::Mat C = B.diag(0);
			T.rowRange(0, dim).colRange(0, dim) = U* twp;
			d.at<float>(dim - 1, 0) = s;
		}
	}
	else {
		cv::Mat diag_ = cv::Mat::diag(d);
		cv::Mat twp = diag_*V.t(); //np.dot(np.diag(d), V.T)
		cv::Mat res = U* twp; // U
		T.rowRange(0, dim).colRange(0, dim) = -U.t()* twp;
	}
	cv::Mat var_ = varAxis0(src_demean);
	float val = cv::sum(var_).val[0];
	cv::Mat res;
	cv::multiply(d, S, res);
	float scale = 1.0 / val*cv::sum(res).val[0];
	T.rowRange(0, dim).colRange(0, dim) = -T.rowRange(0, dim).colRange(0, dim).t();
	cv::Mat  temp1 = T.rowRange(0, dim).colRange(0, dim); // T[:dim, :dim]
	cv::Mat  temp2 = src_mean.t(); //src_mean.T
	cv::Mat  temp3 = temp1*temp2; // np.dot(T[:dim, :dim], src_mean.T)
	cv::Mat temp4 = scale*temp3;
	T.rowRange(0, dim).colRange(dim, dim + 1) = -(temp4 - dst_mean.t());
	T.rowRange(0, dim).colRange(0, dim) *= scale;
	return T;
}
`


**I'm  vast and hazy.   I guess  swig can't explain class in class?  thank you very much, can you give some advises for me?**

**Comment by vadz** [comment]
Sorry, this is _very_ far from a simple and self-contained example.

**Comment by mahxn0** [comment]
@vadz   
I  have one class A, In class A, i have a class B instantiation b
and a class C instantiation c, but B/C Member functions and member variables can.t be sucessful recognised.  
`
A.h  
#include B.h
#include C.h
Class A{
     B*b=new B;
     C*c=new C;
}
when I use class B/C Member functions and member variables in A.cpp
It seems like they can't be recognised
`
is there  some exemples?
