### ISSUE TITLE
Is it possible to apply more than one %typemap(javainterfaces)?

### ISSUE THREAD

**Issue by lballabio** [swig/swig#1819]
I'm trying to use something similar to the code shown in #1791, that is,
```
%typemap(javaimports) SWIGTYPE %{
import java.lang.AutoCloseable;
%}
%typemap(javainterfaces) SWIGTYPE "java.io.AutoCloseable"
%typemap(javacode) SWIGTYPE %{
  @Override
  public void close() {
    delete();
  }
%}
```

The above works as expected for most classes, but fails with instantiations of std::vector.

Full interface file example:
```
%include std_vector.i

%typemap(javaimports) SWIGTYPE %{
import java.lang.AutoCloseable;
%}
%typemap(javainterfaces) SWIGTYPE "AutoCloseable";

%typemap(javacode) SWIGTYPE %{
  @Override
  public void close() {
   this.delete();
  }
%}

class Foo {};

namespace std {
    %template(FooVector) vector<Foo>;
}
```
processing the above with `swig -c++ -java test.i`, the `javaimports` and `javacode` typemaps are applied to `FooVector` but the `javainterfaces` isn't, leading to a compilation error since `FooVector` declares an `@Override close()` method but doesn't implement the interface that defines it.

This is because `FooVector` already has an interface defined by `java/std_vector.i`, that is,
```
%typemap(javainterfaces) std::vector< CTYPE > "java.util.RandomAccess"
```
which takes precedence on the generic one.

Is there any way to have the generated class implement another interface besides the one already declared?

**Comment by wsfulton** [comment]
Fundamental to typemaps are the typemap rules for choosing a typemap (one typemap is chosen). For all vector classes, you can modify the 'javainterfaces' typemap used like this :
```swig
```
%typemap(javainterfaces) SWIGTYPE "AutoCloseable";
%extend std::vector {
  %typemap(javainterfaces) std::vector "AutoCloseable, java.util.RandomAccess";
};
...
```

**Comment by vadz** [comment]
I couldn't help thinking about #1541 when seeing this question, even if there is another solution for this particular problem, being able to append to an existing typemap would also provide another (and simpler) solution here too.

**Comment by lballabio** [comment]
Follow-up in case someone tries this, as I finally did: besides the generic code for `std::vector`, I also needed to add an explicit override for `vector<bool>`, that is,
```
%extend std::vector<bool> {
%typemap(javainterfaces) std::vector "AutoCloseable, java.util.RandomAccess";
};
```

**Comment by akawarren** [comment]
To override the implements for only instantiating std::vector<T> with specific type T, you can write as

%typemap(javacode) std::vector<CustomType> %{
  @Override
  public void close() {
    delete();
  }
%}

%extend std::vector {
    %typemap(javainterfaces) std::vector<CustomType> "java.util.RandomAccess, java.lang.AutoCloseable"
}

// Declaration of custom std::vector<CustomType> goes here

%template(CustomTypeVector) std::vector<CustomType>;
