### ISSUE TITLE
support for cffi/uffi lisp

### ISSUE THREAD

**Issue by francogrex** [swig/swig#1820]
You didn't need to remove those functionalities, you may still keep them even if there will no longer be active support. This is a weird and bad decision.

**Comment by wsfulton** [comment]
Hi fancogrex. I can see you are frustrated that these languages have been removed, however, these badly implemented and unmaintained language modules frustrate and inhibit SWIG development more widely for the few active SWIG developers. Please see #1447 for background information and details of how they can be brought back if you feel you can the contribute to these languages and if feel these languages are important enough to be in the mainline SWIG distribution.
