### ISSUE TITLE
Release versions have unsupported names

### ISSUE THREAD

**Issue by cobexer** [swig/swig#1825]
The release versions in this repo are not compatible with https://semver.org/ and I'm using https://github.com/renovatebot/renovate to keep my dependencies up to date, which for `rel-4.0.0` complains with: `skipReason: "unsupported-value"`

Now aside from the unsupported and nonstandard `rel-` prefix, your versioning scheme looks like it's semver compatible.

Could you please switch the tag format to be semver compatible by either removing `rel-` completely or by replacing it with `v`?

While renovate supports a whole lot of versioning schemes (https://docs.renovatebot.com/modules/versioning/) it would be very nice if swig switched to a standard version format so that manual configuration for swig is not necessary!

Thanks in advance!
Every developer in the world

**Comment by wsfulton** [comment]
So looks like I need to change all the release tags to strip the `rel-` prefix, for example, `rel-4.0.2` to just `4.0.2`. The older tags are a bit different, so for example, `rel-1-3-37` will change to `1.3.37`.

I'm quite happy to use some sort of standard tags. Any objections from anyone if I do this for all the tags? To be clear, I'll remove the old tag names.

**Comment by vadz** [comment]
If you're going to change the convention, I'd rather switch to the [more standard](https://semver.org/spec/v1.0.0.html#tagging-specification-semvertag) `vX.Y.Z` schema.

I'm also not really sure if you need to recreate all the existing tags, wouldn't just applying the `v` convention for the new ones be enough? If you do create new tags, I'd definitely keep the old ones too, as they could be used in scripts/as references elsewhere and it just seems impolite to break them for no good reason.

**Comment by cobexer** [comment]
Removing the old tags is not a requirement IMO, but also having all existing versions tagged with vX.Y.Z would be nice.

Thanks!

**Comment by wsfulton** [comment]
I overlooked the 'v' prefix should be used for the semantic versioning tags. So I'll use this prefix instead. 

Github doesn't hold our official releases, so I'd hope that no-one is using the old tags, but I'll leave them around for a release or two.

**Comment by wsfulton** [comment]
How does that look?

**Comment by cobexer** [comment]
Nice! Thanks!

**Comment by cobexer** [comment]
Sweet thanks!
