### ISSUE TITLE
swig 4 generated python code does not nest

### ISSUE THREAD

**Issue by schiebel** [swig/swig#1831]
Hi,

My project uses swig to generate python bindings. Our swig interface files that are generated from XML. The swig code is then isolated in a private python module. We do not experience any problems with the way swig 3 handles imports of the bindings, but with the import changes for swig 4, I find that the import of the private (swig generated) module no longer works.

I created a simple example that attempts to duplicate the way the python import happens when we use swig 4. The private, swig generated module in this example is __casac__. The swig python wrappers import the C++ shared object like:

<pre>
if __package__ or "." in __name__:
    from . import _utils
else:
    import _utils
</pre>

where `_utils` in our actual project is something like `_utils.cpython-36m-darwin.so`. In my simplified example, it is just `_utils.py`.

When I try to import my simplified example in a python3 session like `import pystinks`, I get an import error `ModuleNotFoundError: No module named '__casac__'`. To get it to work, I have to add my module directory to allow access to the private module, like `PYTHONPATH=pystinks python3`. If the private module is exposed, then the import works.

Please revert to the swig 3 style of importing generated bindings or catch the import error and fall back to the old swig 3 style of import.

Thanks for your help and consideration,
Darrell

PS: I am using swig 4.0.2 and python 3.6.10

[pystinks.tar.gz](https://github.com/swig/swig/files/4833294/pystinks.tar.gz)

**Comment by wsfulton** [comment]
The swig 3 style import is too complex and fundamentally flawed. Please read "Python Packages" at http://swig.org/Doc4.0/Python.html#Python_nn72 to appreciate import complexities. Background info to the change is in #848 and issues linked to it.

Which of your scenarios in the sub-section "Location of modules" fall under? If the solutions in the docs do not work, can you please elaborate on what you are different to the solutions covered in the docs?

**Comment by schiebel** [comment]
Thanks for the pointers. I think this will resolve my problem, but I have some deliverables I have to get through before I can test.

**Comment by wsfulton** [comment]
Ah good. Feel free to reopen if you don't find a resolution.
