### ISSUE TITLE
Unity AOT support C#

### ISSUE THREAD

**Issue by RealVincentBerthet** [swig/swig#1832]
Hello,

I am currently using SWIG to generate C++ bindings to C# for the development of a Unity plugin for [SolAR Framework](http://solarframework.org/). When I am using C# wrapped in Unity editor or on standalone it is working perfectly. However, while using Unity for mobile development (Android) with IL2CPP compiler its throw an exception : 

*ADB output*
![image](https://user-images.githubusercontent.com/22341309/86009118-1b68f200-ba1a-11ea-8e92-d0badda26e30.png)

This is due to IL2CPP that throws exceptions. It detects that there is not callback emitted ahead and as a consequences it is trying to marshal a function pointer from unmanaged code ([Unity ScriptingRestrictions](https://docs.unity3d.com/Manual/ScriptingRestrictions.html)). The error suggest to add MonoPInvokeCallback to manage it and it works. I have found more details thanks to the issue #1165 and many posts on the web.

**How is it possible to directly add MonopInvoke annotation in SWIG rules for SWIG Helper static method ?** I tried typemap, manage exception but it only works with my declared method.

As a temp hack, we use for the moment a script to parse all *PINVOKE.cs generated to add MonoPInvokeCallback annotation to the static's method of SWIGHelper and it works on Android.

Thanks for your help.

**Comment by wsfulton** [comment]
Please have a look at #1262. If you can improve this patch, we can get it added into SWIG mainline.
