### ISSUE TITLE
Cannot compile example with Visual Studio 2015

### ISSUE THREAD

**Issue by yrzhanov** [swig/swig#1833]
I converted the project Examples/python/class from supplied example.dsp to VS2015's example.vcxproj. However, Properties do not show any Custom build steps or Custom build tools. swig.exe runs and produces example_wrap.cxx
I also changed Target extension to ".pyd" to eliminate one of the warnings.
Linking stage fails:

1>------ Build started: Project: example, Configuration: Debug Win32 ------
1>  Performing Custom Build Tools
1>  In order to function correctly, please ensure the following environment variables are correctly set:
1>  PYTHON_INCLUDE: C:\Program Files\Python37\include
1>  PYTHON_LIB: C:\Program Files\Python37\libs
1>  example_wrap.cxx
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1189,5): warning MSB8012: TargetPath(D:\VariousCodes\swigwin-4.0.2\Examples\python\class\.\Debug\example.pyd) does not match the Linker's OutputFile property value (D:\VariousCodes\swigwin-4.0.2\Examples\python\class\_example.pyd). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1191,5): warning MSB8012: TargetName(example) does not match the Linker's OutputFile property value (_example). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
1>LINK : fatal error LNK1104: cannot open file 'C:\Program Files\Python37\libs.obj'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Obviously, the program should link to C:\Program Files\Python37\libs\python37.lib, not libs.obj that does not exist.

What am I doing wrong?

Thank you,
    Yuri

**Comment by wsfulton** [comment]
It does work with Visual Studio 2015. Take a careful look at http://swig.org/Doc4.0/Windows.html, in particular, select Release build.

**Comment by yrzhanov** [comment]
Hi,

I’ve read this document and followed all instructions. They are somewhat outdated, as VS2015 creates .vcxproj, not .dsw. I also tried Release mode, but the result is the same:

 

1>------ Rebuild All started: Project: example, Configuration: Release Win32 ------

1>  Performing Custom Build Tools

1>  In order to function correctly, please ensure the following environment variables are correctly set:

1>  PYTHON_INCLUDE: C:\Program Files\Python37\include

1>  PYTHON_LIB: C:\Program Files\Python37\libs

1>  example.cxx

1>  example_wrap.cxx

1>  Generating Code...

1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1189,5): warning MSB8012: TargetPath(D:\VariousCodes\swigwin-4.0.2\Examples\python\class\.\Release\example.dll) does not match the Linker's OutputFile property value (D:\VariousCodes\swigwin-4.0.2\Examples\python\class\_example.pyd). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).

1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1190,5): warning MSB8012: TargetExt(.dll) does not match the Linker's OutputFile property value (.pyd). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).

1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1191,5): warning MSB8012: TargetName(example) does not match the Linker's OutputFile property value (_example). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).

1>LINK : fatal error LNK1181: cannot open input file 'C:\Program Files\Python37\libs.obj'

========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

 

Sorry for bothering, but I’m really lost.

 

Yuri

 

===============================================================================

Yuri Rzhanov

Center for Coastal and Ocean Mapping/Joint Hydrographic Center

University of New Hampshire

Tel: 1-603-8620075

 

Let go all your heartaches, it's as easy as being free 
You don't have to wait a while

**Comment by wsfulton** [comment]
```
PYTHON_LIB: C:\Program Files\Python37\libs
```
is incorrect and needs to include the lib file name (probably python37.lib), so change to:
```
PYTHON_LIB: C:\Program Files\Python37\libs\python37.lib
```

**Comment by yrzhanov** [comment]
Thank you very much – I should have noticed that. Just a blind spot…

 

Cheers,

    Yuri

 

===============================================================================

Yuri Rzhanov

Center for Coastal and Ocean Mapping/Joint Hydrographic Center

University of New Hampshire

Tel: 1-603-8620075

 

Let go all your heartaches, it's as easy as being free 
You don't have to wait a while
