### ISSUE TITLE
bindings generation for python using ctypes

### ISSUE THREAD

**Issue by KOLANICH** [swig/swig#1834]
Currently it generates bindings as a cext. It has a drawback it has to be rebuilt against each python version. It is also not very compatible to the impls other than cpython.

But there is ctypes mechanism, it allows to call into native dlls and is widely compatible across the impls.

It may make sense to have a mode generating python code using ctypes instead of cexts.

**Comment by ojwb** [comment]
That sounds like a lot of work.

FWIW, the patch to only use the stable Python API would provide a single build that works across python versions: #1613

**Comment by KOLANICH** [comment]
Thanks for the info, I have never known that such a thing is possible.

**Comment by ojwb** [comment]
#2190 is the current PR for supporting the stable Python ABI (replacing #1613).

That addresses at least the "has to be rebuilt against each python version" part,  It seems a simpler approach as it supports a major subset of the API we use already, and we have a patch for that I'm going to close this ticket in favour of that approach.
