### ISSUE TITLE
%typemap(javaimport) does not work with structs

### ISSUE THREAD

**Issue by nrbrook** [swig/swig#1836]
test.i:
```
%typemap(javaimports) TestStruct %{
import java.util.Arrays;
%}

%module Test
%{
    typedef struct TestStruct {
        int a;
    };
%}

typedef struct TestStruct {
    int a;
};
```
Running swig:
```
$ swig -version

SWIG Version 4.0.2

Compiled with clang++ [x86_64-apple-darwin19.5.0]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
$ swig -outdir test -java test.i
$ cat test/TestStruct.java 
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class TestStruct {
...
```
The import statement is not present.

**Comment by wsfulton** [comment]
```c
    typedef struct TestStruct {
        int a;
    };
```
The above is rather peculiar and possibly not even valid C as you are typedef'ing the struct to nothing. My compiler warns with:
```
warning: useless storage class specifier in empty declaration
```
Anyway, there is a type `struct TestStruct` and there is no type just `TestStruct`. Your typemap needs to use the appropriate type:
```swig
%typemap(javaimports) struct TestStruct %{
import java.util.Arrays;
%}
```
Incidentally, for C++, if you add `-c++` to the SWIG options, just `TestStruct` in the typemap type will work as it is a valid type in C++.

**Comment by nrbrook** [comment]
Apologies, I meant:
```
typedef struct TestStruct_s {
    int a;
} TestStruct;
```

I can see using `%typemap(javaimports) struct TestStruct` does work, and multiple comma separated structs also works. I couldn't see anything about this in the documentation though? It's a bit confusing because for example with `%ignore` you can just provide the struct typedef name, with `%extend` you are supposed to use the struct name, so it seems inconsistent.
