### ISSUE TITLE
SWIG ignoring using declarations for adjusting access to members of base classes

### ISSUE THREAD

**Issue by neworderofjamie** [swig/swig#1840]
These are being ignored if this rename rule is also active:
```swig
%rename("%(undercase)s", %$isfunction) "";
```

### SWIG (test.i):
```swig
%module(package="package") package
%rename("%(undercase)s", %$isfunction) ""; // Enable conversion to under_case
%include "test.h" 
```

### C++ header (test.h)
```c++
#pragma once

class Test
{
protected:
    void finalize();
    bool isRecordingInUse() const;
};

class TestInternal : public Test
{
public:
    using Test::finalize;
    using Test::isRecordingInUse;
};
```

### SWIG command
```bash
swig -python -c++ -relativeimport -outdir . -py3  -o test_wrap.cpp test.i
```

### Resulting python (relevant section of package.py)
```python
class TestInternal(Test):
    __swig_setmethods__ = {}
    for _s in [Test]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TestInternal, name, value)
    __swig_getmethods__ = {}
    for _s in [Test]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, TestInternal, name)
    __repr__ = _swig_repr

    def finalize(self) -> "void":
        return _package.TestInternal_finalize(self)

    def __init__(self):
        this = _package.new_TestInternal()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _package.delete_TestInternal
    __del__ = lambda self: None
```
## Workaround
The issue seems to effect all using declarations refering to functions whose name consists of multiple camelCase words  - I have found the following workarounds which all result in the method being wrapped:
- If you rename ``isRecordingInUse`` to ``isrecordinginuse`` in the C++ header
- Adding an explicit rename rule ``%rename(is_recording_in_use) isRecordingInUse;``
- Remove the rename rule

**Comment by wsfulton** [comment]
This is confusing and there are two subtle problems. 
1. The `%rename` you've used does not apply to using declarations as it is specifically targeting functions.
2. There is a conflict in the target language names (the base class name is `is_recording_in_use`, but the using declaration thinks this introduced method should be `isRecordingInUse`, that is, it is not renamed. 

79a1bbee8b36bf05e42a5c7aaf80ee005101aaad helps diagnose the problem by introducing a new warning. With this you will now see:
```
example.i:57: Warning 526: Using declaration Test::isRecordingInUse, with name 'isRecordingInUse', is not actually using
example.i:50: Warning 526: the method from Test::isRecordingInUse() const, with name 'is_recording_in_use', as the names are different.
```
546062fdf1b4fc1acd00a61074a35609b8ad64fc and f995bad785be06d089ed401deea01d9102559d1d improves  documentation for  `%rename` matching and introduces a `%$isusing` macro. Your fix is to add the following to additionally apply the undercase renaming to all using declarations for class members:
```
%rename("%(undercase)s", %$isusing, %$ismember) "";
```
For versions of SWIG prior to 4.1.0, the macro won't be available, but this is identical:
```
%rename("%(undercase)s", match="using", %$ismember) "";
```
