### ISSUE TITLE
Cannot build wrapper for Python 3.8

### ISSUE THREAD

**Issue by nix7drummer88** [swig/swig#1846]
SWIG 4.0.2
Windows 10
Python 3.8 (all bugfix versions)

I have a C++ API which I have been wrapping to work with Python 3.6 for some time. My project is attempting to update to the most recent Python version possible, so we are looking at Python 3.8.

Python 3.8 is unable to import the module that was generated from linking with Python 3.6, so I updated SWIG to 4.0.2, Python to 3.8, and tried to generate my wrapper again. SWIG is able to build this successfully, however Python cannot import the module.
I repeated this exercise with Python 3.7.8. SWIG was once again able to build the wrapper, but this time Python could successfully import it.

In each case I verified that my environment variables for PYTHON_INCLUDE and PYTHON_LIB were appropriate for the Python version in use at the time.

Is there something else I should be looking at in order for this to work with Python 3.8?

**Comment by geographika** [comment]
@nix7drummer88 - does the project rely on other DLLs to be on the system PATH?
If so it could be the issue as https://github.com/mapserver/mapserver/issues/6101

**Comment by nix7drummer88** [comment]
@geographika thank you so much, that was the issue!
