### ISSUE TITLE
C# improved generated PINVOKE code

### ISSUE THREAD

**Issue by christophe-calmejane** [swig/swig#1854]
The `modulePINVOKE.cs` generated file is repeating the same `global::System.Runtime.InteropServices.DllImport` all over the place, using the exact same dllname as first argument.
I know it's not recommended to edit this file, but when using SWIG in a cross-platform project (mainly Xamarin), I'm not sure there is another choice. For instance, the _dllname_ is different on windows/linux/android and on iOS. You have to use a framework for iOS, so the _dllname_ has to be `module.framework/module` instead of just `module`.

It would be a lot easier if the name of the dll is stored in a static variable at the start of `modulePINVOKE.cs` and used in the file (besides being cleaner). That way, one could easily add some `#ifdef` directive just once in the file (and add it again after each file generation).

**Comment by geefr** [comment]
Related to #347, some info there. If I remember correctly it's a desired feature but no one's provided a possible implementation yet?

Established mechanism is to run swig multiple times with a different '-dllimport <dll name>' parameter. You'll get multiple copies of the pinvoke.cs but they'll be the same other than dll name (Can conditionally include the one you need).

**Comment by christophe-calmejane** [comment]
Thanks for the information, I'll see if I can find something useful in the link :)
Running multiple SWIG runs is not as easy as it sounds, as I'm using CMake UseSWIG module, that do not support running multiple times with the same target name.

**Comment by geefr** [comment]
Ah, always ran it outside the build system here (because history, no valid reason).

I guess you could have multiple targets, or update the target's flags based on cmake's target platform. Looks like the properties CMAKE_SWIG_FLAGS or SWIG_COMPILE_OPTIONS would be handy for setting the module name at least.

**Comment by christophe-calmejane** [comment]
I'm sure there is a solution using CMake, but I don't think it would look pretty. Playing around with multiple targets for the same wrapper lib and support files except one would surely look like a hack (I don't even mention consuming the wrapper library the same way for both arch...) ;)
Anyway, if I can find some time, I'll take a look at swig's c# generated files and see if something can be done.
I'm currently more concerned about #1847 I entered a couple weeks ago.

**Comment by wsfulton** [comment]
We test C# on Windows, Linux and MacOS and use the same dll name for each of these three platforms. Are you sure you need different names on different platforms?

**Comment by christophe-calmejane** [comment]
I do as I’m not using a shared library but a Framework which, for a target named MyProject, will result in the shared module to be loaded being MyProject.framework/MyProject

**Comment by Mizux** [comment]
My 2 cents,
At least on windows/linux/osx the *dllname* is the same since you don't have to provide the extension...
So you can ship one generic .Net package which at runtime will load the correct native code (that can be shipped by platform dependent packages)

Here my working pet examples to create a cross-platform .Net package...
https://github.com/Mizux/dotnet-native

note: extracted from my bigger samples https://github.com/Mizux/cmake-swig

**Comment by christophe-calmejane** [comment]
> At least on windows/linux/osx the _dllname_ is the same since you don't have to provide the extension...

This is only true if **not** building as a `Framework` on macOS, which is not my case as described in the OP.

Nevertheless thanks for the links, looks interesting.

**Comment by christophe-calmejane** [comment]
Sorry for the long delay ;)

I tried to define a const string variable at the begining of the lcomMobilePINVOKE generated class, and use this variable in the whole file, it's working just fine, so maybe it's a way to go to cleanup a little bit the generated file (as well as enabling easy modification of the generated file).
I'm not sure I'll have the time to make and propose a PR for this change, never looked at swig code source

**Comment by wsfulton** [comment]
@christophe-calmejane, invoking swig with `-dllimport "module.framework/module"` is the expected approach to modifying the dll name. 

I don't believe you are unable to invoke swig with different command line options when using CMake. If you are right and CMake is unable to invoke swig with different options, then you really need to enlist CMake advice. This is so simple with make and MSBuild using variables to pass on to the swig executable.

**Comment by Mizux** [comment]
FYI
```cmake
set_property(SOURCE you_swig_file.i PROPERTY COMPILE_OPTIONS
  -namespace ...
  -dllimport "...")
swig_add_library(...
```

> `INCLUDE_DIRECTORIES`, `COMPILE_DEFINITIONS` and `COMPILE_OPTIONS`
New in version 3.12.
Add custom flags to SWIG compiler and have same semantic as properties `INCLUDE_DIRECTORIES`, `COMPILE_DEFINITIONS` and `COMPILE_OPTIONS`.

ref: https://cmake.org/cmake/help/latest/module/UseSWIG.html#properties-on-source-files

**Comment by christophe-calmejane** [comment]
> FYI
> 
> ```cmake
> set_property(SOURCE you_swig_file.i PROPERTY COMPILE_OPTIONS
>   -namespace ...
>   -dllimport "...")
> swig_add_library(...
> ```
> 
> > `INCLUDE_DIRECTORIES`, `COMPILE_DEFINITIONS` and `COMPILE_OPTIONS`
> > New in version 3.12.
> > Add custom flags to SWIG compiler and have same semantic as properties `INCLUDE_DIRECTORIES`, `COMPILE_DEFINITIONS` and `COMPILE_OPTIONS`.
> 
> ref: https://cmake.org/cmake/help/latest/module/UseSWIG.html#properties-on-source-files

Yes indeed, except that this must be set before calling `swig_add_library`, and I can only know the module output name after it has been created by `add_library` (which is internally called by `swig_add_library`).

**Comment by christophe-calmejane** [comment]
There were 2 reasons for this ticket:
- A bug in CMake when C# files are generated from macOS/linux (couldn't be used on windows), which is now fixed (https://gitlab.kitware.com/cmake/cmake/-/issues/25405)
- Impossibility to properly use as `macOS/iOS Framework` without changing the C# generated code

Since we cannot use a variable to replace all strings in the file (see https://github.com/swig/swig/pull/2475), I guess we can close this issue @wsfulton, and the user will have to generate 2 sets of C# files anyway.

**Comment by wsfulton** [comment]
Yes makes sense.
