### ISSUE TITLE
Create internal c#-classes instead of public ones

### ISSUE THREAD

**Issue by ralfkonrad** [swig/swig#1856]
Is there any way to create the resulting c#-wrapper classes as `internal` instead of `public` by default as I do not want to expose them in my interface?

I looked at
https://github.com/swig/swig/blob/46e17f1458e312c5a5b4213adefffbdab4b05540/Lib/csharp/csharp.swg#L881
but couldn't find out how to do this.

**Comment by geefr** [comment]
`%typemap(csclassmodifiers) SomeClassName "internal class"`
If you wanted to set it for everything csharp.swg has the default definition for SWIGTYPE, line 883 - Just copy that definition into your .i file and set to what you need, and it will override the previous/default typemap.

Docs: http://swig.org/Doc4.0/SWIGDocumentation.html#CSharp_differences_java (And read the java section about javaclassmodifiers, java/c# modules are similar.

**Comment by ralfkonrad** [comment]
Thanks for the quick answer, @geefr!
