### ISSUE TITLE
how to use existed c++ libxxx.so in python

### ISSUE THREAD

**Issue by heroazhe** [swig/swig#1865]
I want to invoke other`s lib ,but I only have the .h and .so files ，what should I do if I want to invoke in python.   Can someone give an example?

**Comment by heroazhe** [comment]
can swig handle class thread or future in the c++11?  In the doc, i don`t see related description.

**Comment by wsfulton** [comment]
Get SWIG to parse the methods in the .h file you want, then link against the .so file and make sure the dynamic loader can find the .so file when you run, like you would for any C++ development.

SWIG doesn't provide any library for `<future>`. You should be able to wrap whatever you want out of this yourself.
