### ISSUE TITLE
Global %rename breaks wrapper of std::vector in C#

### ISSUE THREAD

**Issue by Loffe** [swig/swig#1866]
I use the following global rename to follow the C# conventions:

    // Rename everything to UpperCamelCase accoring to C# convention
    %rename("%(camelcase)s", %$isfunction) "";

However, this interferes with the use of:

    %template(FooVector) std::vector<Foo>;

The generated code `FooVector.cs` contains both a property and a private method named `Capacity`. The property `Capacity` expects to call a private method `capacity`, but that was renamed. This applies to a few more methods, and is causing compilation errors in C#.

```csharp
  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  [ ... snip ... ]

  private uint Capacity() {
    uint ret = genirangerPINVOKE.RegionList_Capacity(swigCPtr);
    if (genirangerPINVOKE.SWIGPendingException.Pending) throw genirangerPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }
```
    
I've added the following as a workaround:

```
%rename("%s") std::vector::capacity;
%rename("%s") std::vector::getitem;
%rename("%s") std::vector::getitemcopy;
%rename("%s") std::vector::reserve;
%rename("%s") std::vector::setitem;
%rename("%s") std::vector::size;
```

Perhaps this should go into `csharp/std_vector.i`?
I guess the same issue applies to `std::map` and others as well.

**Comment by wsfulton** [comment]
Your workaround to stop the global rename looks fine to me or you could disable your global renames when including SWIG library files. The lower case names are the original c++ names and are wrapped are not part of the public API provided by the implemented interfaces.
