### ISSUE TITLE
Typemaps for C++ `long` to Java are not always correct.

### ISSUE THREAD

**Issue by asoffer** [swig/swig#1869]
C++ long is guaranteed to be *at least* 32-bits, but can be (and on many modern platforms is) 64 bits. On these platforms, it would be fantastic to have the corresponding Java type be `long` rather than `int`.

**Comment by wsfulton** [comment]
SWIG provides the ability to customise the generated code if the default is not suitable. Please take a look at the documentation, in particular the Java specific typemaps: 'jni'` 'jtype' 'jstype'.

**Comment by asoffer** [comment]
Yes, this is the current workaround we are using. This issue is requesting a change to the defaults. On platforms where C++ long is 8 bytes, the default is subtly wrong, and will cause subtle errors in user code if they ever have a value too large to fit in 4 bytes. I'm wondering about the feasibility of changing the defaults to avoid this pitfall in the future. The choice of typemap would need to be platform dependent.
