### ISSUE TITLE
Actualization of http://swig.org/tutorial.html

### ISSUE THREAD

**Issue by bakwc** [swig/swig#1871]
Tutorial at http://swig.org/tutorial.html is a little outdated. For example, it's not working for java.
1) `loadLibrary` is not loading library at current dir. Instead you should use `System.load(System.getProperty("user.dir") + "/mylibrary.so");`
2) `add-stdcall-alias` is not nesessary (in fact it is missing in clang)
3) instead of `javac main.java` you should run `javac *.java`

I suggest to add http://swig.org/tutorial.html under github so users could make PR and fix issues like that.

**Comment by romintomasetti** [comment]
Should be moved to https://github.com/swig/www/issues, right ?

**Comment by wsfulton** [comment]
1. This is an example for Cygwin. Each system requires something slightly different unfortunately. Cygwin includes "." in the PATH, so the example as shown works.
2. This is an example for gcc on Cygwin. The tutorial clearly gives a link to https://github.com/swig/swig/wiki/FAQ#shared-libraries for compiling for other systems. Please contribute there.
3. `java main.java will compile all the dependencies that main.java needs.
