### ISSUE TITLE
Objective C support

### ISSUE THREAD

**Issue by pvmiseeffoC** [swig/swig#1873]
My fork of swig -> https://github.com/pvmiseeffoC/swig

1. Get test suite up and running for branch gsoc2012-objc
2. Research the previous work done and analyse what works and doesn't work in order to come up with a plan of action to get it up to scratch. 
3. Implement what's not done and get it to Experimental status

Progress so far:
1. Merged the master branch into gsoc2012-objc.
    I've almost got the examples to run locally, I get one fatal error that I have yet to get rid of.
    The test suite is full of errors, have to figure out what's going wrong.
2. I've looked at more than half the commits in the branch or I'd like to believe so

**Comment by pvmiseeffoC** [comment]
https://github.com/swig/swig/issues/827

**Comment by pvmiseeffoC** [comment]
I'll be updating this issue every 5-7 days with my progress

**Comment by wsfulton** [comment]
You may be better off getting the original branch working before merging in master which is likely to completely break the build and test system. Better to establish a working version and then enlist others help, but I'd only be interested in helping with the merge from master once you have a working branch.

**Comment by pvmiseeffoC** [comment]
Ok, sounds good to me, I will do it like that.

**Comment by pvmiseeffoC** [comment]
I got the test-suite running on travis last week https://travis-ci.org/github/pvmiseeffoC/swig/builds/730361995
I'll be investigating the errors this weekend

**Comment by pvmiseeffoC** [comment]
I'll try to implement directors for Objective-C by using CSharp as a reference

**Comment by pvmiseeffoC** [comment]
I sorted through the problems found by the test suite and am going to start looking into ways to fix them.

Here's the list : https://pastebin.com/6yLuPhfL

I'm open to any suggestions/help for any of them.
I'm going to try and fix the first 2 this week

**Comment by pvmiseeffoC** [comment]
Had to deal with some IRL problems, so I couldn't do much.
Fixed only the 2nd problem.

I guess the problem for ordering of classes can be fixed by implementing forward declaration. Not sure how exactly to implement it though, I guess I'll reread the documentation for Extending SWIG and see if I get any ideas where the correct place to implement forward declaration would be.

I'll try and fix problems 3-5 in the following week.

**Comment by wsfulton** [comment]
The forward declarations are implemented in the core. Individual language modules shouldn't have to do anything in this area. How about detailing an example and what is going wrong to get some help.

**Comment by pvmiseeffoC** [comment]
Here's a simple example of the problem:

```
 %module simple_ordering
 
 %inline %{
 
 template<typename T>
 class A{};
 class ABC
 {
     A<int> aint;
     public:
     A<int> getAint() {return aint;} 
 };
 
 %}
 
 %template(Aint) A<int>;
```

As for the generated proxy code header it looks like : 
```
@interface ABC : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(Aint*)getAint;
-(id)init;

-(void)dealloc;

@end

@interface Aint : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end
```
Which generates an error during compilation as Aint is declared after ABC

**Comment by dluco-pdftron** [comment]
Hey, checking in on the status of the work here. I also have a version of the `gsoc2012-objc` branch with latest `master` merged in and some progress on getting some cmdline options working (mainly the output dir).
Is the list of issues in https://github.com/swig/swig/issues/1873#issuecomment-708010170 still relevant?

**Comment by dluco** [comment]
Hey, checking in on the status of the work here. I also have a version of the `gsoc2012-objc` branch with latest master merged in and some progress on getting some cmdline options working (mainly the output dir).
Is the list of issues in https://github.com/swig/swig/issues/1873#issuecomment-708010170  still relevant?

**Comment by pvmiseeffoC** [comment]
Hello, the list is still relevant, some of the minor issues were fixed in my fork of the swig repo in branch gsoc2012-objc.

Sadly I don't have much free time lately and haven't been able to work on fixing the remaining issues.

**Comment by dluco** [comment]
Ok, no worries!

**Comment by mtehver** [comment]
Just a note: there is another 'fork' of gsoc2012-objc branch with lots of modifications here: https://github.com/CartoDB/mobile-swig

The original branch is merged into swig-2.0.11 and the following features are added:

* Support for directors
* Support for C++ smart pointers (`std::shared_ptr`, etc)
* Support for doxygen comment translation
* Several fixes related to string handling, etc

This fork is used to wrap CARTO Mobile SDK C++ API on iOS and has worked without issues for several years

**Comment by vadz** [comment]
@mtehver This looks potentially very useful, but it's going to be pretty difficult to integrate anything of this into official SWIG as it doesn't even share the same Git history with it. It would definitely be great to have PRs with your changes here, even though I can't unfortunately guarantee anything about merging them into SWIG master, I'd like to merge some of them in my own SWIG branch,

**Comment by mtehver** [comment]
@vadz It would be very nice to have ObjC support in master at some point. I am willing to contribute some time on my behalf on this, but not sure how to proceed. Should I create PRs based on the current state of gsoc2012-objc branch or some other branch?

**Comment by vadz** [comment]
I think you should indeed start with this branch and merge your commits and current master into it (not sure in which order). FWIW I'm working on something similar with gsoc2012-c branch in #2086 and I wonder if there could be some commonality between Objective-C and C backends that could be worth exploring?

It could also be a good idea to start by creating smaller PRs for the other fixes mentioned above to merge them first, as this should be simpler to do. TIA!

**Comment by ojwb** [comment]
I'll repeat the comment I just made in #2185 here:

I'd strongly recommend people interested in objective C support in SWIG coordinate and collaborate. It's not trivial to get a new target language merged into SWIG (either for the contributor or for the SWIG maintainers reviewing it) so having competing forks in play is really not a sensible situation..

**Comment by ojwb** [comment]
> I'll be updating this issue every 5-7 days with my progress

It seems work on this has tailed off and the branch referenced at the top hasn't been updated in over three years:

https://github.com/pvmiseeffoC/swig/tree/gsoc2012-objc

@pvmiseeffoC Are you still interested in working on this?

**Comment by ojwb** [comment]
> I've lost interest in this, and don't really have the time to do it

Given this and that there's an active PR for objc (#2791) I'm going to close.

**Comment by nioncode** [comment]
@ojwb can we keep this issue open until Objective C support has been merged? It seems like the linked MR is about to be closed again and then we'd not have a tracking issue anymore.

**Comment by ojwb** [comment]
We can reopen if the active PR for this gets closed - otherwise it's just a redundant ticket and we're already drowning in open tickets.

I'll also reiterate my earlier plea that people interested in objective C support in SWIG **coordinate** and **collaborate**. It's not trivial to get a new target language merged into SWIG (either for the contributor or for the SWIG maintainers reviewing it) so having competing forks in play is really not a sensible situation.

**Comment by Isaina** [comment]
@3xanimo hi can you write me a step by step tutorial how to clone object c git respiratory run test  and start fixing problems , which ide to use
