### ISSUE TITLE
Create internal c#-interfaces instead of public ones 

### ISSUE THREAD

**Issue by ralfkonrad** [swig/swig#1874]
In #1856 I have asked how to **"Create internal c#-classes instead of public ones"**. The answer there works perfectly for me.

Now I have multi inheritance in my project and I can hardly find a workaround for it as I derive from a class from an external project and extend it by a few methods.

So I tried
```cpp
%interface(A::B)
%shared_ptr(A::B)
%nodefaultctor A::B;
namespace A {
    class B {
      public:
        virtual void someMethod(const Date& date) const = 0;
    };
}
```
This creates the expected
```csharp
namespace A {

public interface BSwigInterface {
  [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
  global::System.Runtime.InteropServices.HandleRef GetInterfaceCPtr();
  void someMethod(Date date);
}

}
```
Is there any way to get an ``internal interface BSwigInterface`` as I made the class ``Date`` internal (see #1856) and ``c#`` complains about inconsistent accessability?

**Comment by wsfulton** [comment]
Use the new 'csinterfacemodifiers' (C#) or 'javainterfacemodifiers' (Java) typemap in commit c1b004f.

**Comment by ralfkonrad** [comment]
Thanks @wsfulton for the modification. This will be available in the next release than?! Is there any timeline for that release?

Regards Ralf

**Comment by wsfulton** [comment]
Yes it will be in the next release. There is no exact timelines for the next release at the moment, but probably early next year.
