### ISSUE TITLE
SWIG syntax error on list initializer of template ctor parameter

### ISSUE THREAD

**Issue by performantdata** [swig/swig#1876]
[From the users list](https://sourceforge.net/p/swig/mailman/swig-user/thread/CANGqftARhyURnGYPea%2BtH59FmWj91Ks%3D5z1tu_qaD84Bu_7DvA%40mail.gmail.com/#msg37118918):

I posted my code to https://github.com/performantdata/swig-issue-2020-09/. [The files](https://github.com/swig/swig/files/5307072/swig-issue-2020-09-master.zip) are also attached.

I'm trying to define an instance of a fully-specialized template and make it visible to Java.  The template ctor takes one parameter, a `std::array`. When I use a _braced-init-list_ in the C++ header:

```c++
const A<char, 3> A3(std::array<char, 3>{'A','B','C'});
```

that seems fine to C++.  But when I specify that in the `.i` file, SWIG fails with "Error: Syntax error in input(1)."  If I remove the initializer list, SWIG succeeds, but the C++ compilation of the SWIG-generated wrapper fails, because it doesn't pass a parameter to the A ctor.

**Comment by ojwb** [comment]
I initially thought this was a missing C++11 feature, but actually it looks like it's another case of #869 and indeed the application of **more** C++11 gives a variant which parses OK:

```
const A<char, 3> A3{std::array<char, 3>{'A','B','C'}};
```

I'm going to close this as a duplicate and note this as another example in the older ticket.
