### ISSUE TITLE
SWIG_fail for Java?

### ISSUE THREAD

**Issue by nrbrook** [swig/swig#1879]
When writing typemaps for Python and others you can use the `SWIG_fail` macro to jump to cleanup code. This doesn't exist when wrapping for java so allocations can't be cleaned up if the typemap needs to return early.

Example:

```
%typemap(in,noblock=1) int * {
	$1 = malloc(sizeof(int));
	if($1 == NULL) {
#ifdef SWIGJAVA
		return $null; // doesn't run cleanup code, leaks arg1 if arg2 allocation fails
#else
                SWIG_fail; // jumps to cleanup code
#endif
	}
}
%typemap(freearg,noblock=1) int * {
	free($1);
}


void afunc(int *varA, int *varB);
```

**Comment by ojwb** [comment]
#2402 covers this issue, so closing this in favour of that.
