### ISSUE TITLE
Go: SWIG doesn't work with MSVC

### ISSUE THREAD

**Issue by phanirithvij** [swig/swig#1886]
I see an issue back from 2013 which might be related https://github.com/swig/swig/issues/100

Sample code

```i
/* file: example.i */
%module example
%include <windows.i>
%include "example.h"
```

```h
// file: example.h
#ifndef _EXAMPLE_H_
#define _EXAMPLE_H_

#ifndef DLLAPI
#define DLLAPI extern "C" __declspec(dllexport)
#endif

DLLAPI bool example_func();

#endif // _EXAMPLE_H_
```
```c++
/* file: example.cc */
#include "example.h"
#include <iostream>

bool example_func(){
    std::cout << "example" << std::endl;
    return true;
}
```
Now `swig.exe -c++ -go -intgosize 32 example.i` generates `example_wrap.cxx`

Now in a cmd.exe
`vcvars32.bat` then `cl.exe example.cc example_wrap.cxx` gives the following errors

```c++
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28314 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

example.cc
example_wrap.cxx
example_wrap.cxx(204): error C3646: '__attribute__': unknown override specifier
example_wrap.cxx(204): error C2059: syntax error: '('
example_wrap.cxx(204): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
example_wrap.cxx(212): warning C4551: function call missing argument list
example_wrap.cxx(222): error C2065: '__packed__': undeclared identifier
example_wrap.cxx(222): error C2146: syntax error: missing ';' before identifier 'a'
example_wrap.cxx(222): error C2065: 'a': undeclared identifier
example_wrap.cxx(223): error C2065: 'a': undeclared identifier
example_wrap.cxx(224): error C2065: 'a': undeclared identifier
example_wrap.cxx(224): error C2065: 'a': undeclared identifier
example_wrap.cxx(274): error C3861: 'example_func': identifier not found
Generating Code...
```

Also, I read on stackoverflow that only 32 bit compiling is supported on windows https://stackoverflow.com/a/17429595/8608146 is this still true in 2020 (I'm not able to verify it because of the above errors which also occur when using 64 bit  i.e. `vcvars64.bit` and `-gointsize 64`)

**Comment by ojwb** [comment]
The problem is this code in `Lib/go/goruntime.swg`:

```
#ifndef SWIGGO_GCCGO
// Set the host compiler struct attribute that will be
// used to match gc's struct layout. For example, on 386 Windows,
// gcc wants to 8-align int64s, but gc does not.
// Use __gcc_struct__ to work around http://gcc.gnu.org/PR52991 on x86,
// and https://golang.org/issue/5603.
// See: https://github.com/golang/go/blob/fcbf04f9b93b4cd8addd05c2ed784118eb50a46c/src/cmd/cgo/out.go#L663
%insert(runtime) %{
# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif
%}
#else
# define SWIGSTRUCTPACKED
#endif
```

The linked file there seems to show that cgo also assumes `__attribute__((__packed__))` works, but I guess it doesn't with MSVC.

I'm not familiar enough with Go to give reliable advice here, but I wonder if MSVC just isn't supported by Go.  If you know how to specify the equivalent of `__attribute__((__packed__))` (might be declspec something) then you could try adding a special case for MSVC to the code I quoted above.  If that works, please open a pull request with that change.

**Comment by phanirithvij** [comment]
I believe you are right, cgo doesn't support MSVC yet https://github.com/golang/go/issues/20982.
I was just experimenting with cgo, c++ at that time, and I apologize but I'm not knowledgeable enough to contribute here.

**Comment by wsfulton** [comment]
Until Go supports MSVC, also see https://github.com/golang/go/issues/49080, SWIG is not going to support MSVC compilation + Go.
