### ISSUE TITLE
virtual const std::string* some_method(const some_t& s_t) const = 0;

### ISSUE THREAD

**Issue by neuralsea-lab** [swig/swig#1890]
SWIG 4.0 generates SWIG_p_std_string class when it encounters a return type of 'const std::string*'. How are return types handled in typemaps - for both method body and return type please?

**Comment by wsfulton** [comment]
Apply the `const std::string&` typemaps (which marshall `std::string` to C# `string' like this:
```swig
%include <std_string.i>
%apply const std::string& { const std::string* }
```

**Comment by neuralsea-lab** [comment]
Thank you @wsfulton
