### ISSUE TITLE
include could not find load file: GrSwig 

### ISSUE THREAD

**Issue by skast96** [swig/swig#1891]
Can anybody please help me with this error. Have been stuck with it for 2 weeks now.
This happens when building a block for gnuradio 3.8 and 3.9

``` 
CMake Error at swig/CMakeLists.txt:37 (include):
include could not find load file:

    GrSwig


CMake Error at swig/CMakeLists.txt:51 (GR_SWIG_MAKE):
  Unknown CMake command "GR_SWIG_MAKE". 
```

**Comment by wsfulton** [comment]
`GrSwig` looks like something to do with gnuradio, so please request support from the gnuradio folk.
