### ISSUE TITLE
swig undefined references on Windows

### ISSUE THREAD

**Issue by cyyber** [swig/swig#1894]
I am trying to generate go files with shared library for Windows. The project is https://github.com/theQRL/qrllib . It works completely fine on Linux. Though I face issue when I try to build it on Windows using mingw32 or TDM-GCC-64 which is itself built from mingw64

Following are the errors that it throws when linking to goqrllib.dll

[ 51%] Linking CXX shared module goqrllib\goqrllib\goqrllib.dll
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\goqrllib.dir\link.txt --verbose=1

"C:\Program Files\CMake\bin\cmake.exe" -E remove -f CMakeFiles\goqrllib.dir/objects.a

C:\TDM-GCC-64\bin\ar.exe cr CMakeFiles\goqrllib.dir/objects.a @CMakeFiles\goqrllib.dir\objects1.rsp

C:\TDM-GCC-64\bin\g++.exe   -pthread -fPIC -Wno-deprecated-declarations  -shared -o goqrllib\goqrllib\goqrllib.dll -Wl,--major-image-version,0,--minor-image-version,0 -Wl,--whole-archive CMakeFiles\goqrllib.dir/objects.a -Wl,--no-whole-archive @CMakeFiles\goqrllib.dir\linklibs.rsp

C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\goqrllib.dir/objects.a(pyqrllibGO_wrap.cxx.obj):pyqrllibGO_wrap.cxx:(.text+0x4f): undefined reference to 'crosscall2'

C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: 

CMakeFiles\goqrllib.dir/objects.a(pyqrllibGO_wrap.cxx.obj):pyqrllibGO_wrap.cxx:(.rdata$.refptr._cgo_panic[.refptr._cgo_panic]+0x0): undefined reference to '_cgo_panic'
collect2.exe: error: ld returned 1 exit status
CMakeFiles\goqrllib.dir\build.make:313: recipe for target 'goqrllib/goqrllib/goqrllib.dll' failed
mingw32-make[2]: *** [goqrllib/goqrllib/goqrllib.dll] Error 1
mingw32-make[2]: Leaving directory 'D:/build'
CMakeFiles\Makefile2:255: recipe for target 'CMakeFiles/goqrllib.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/goqrllib.dir/all] Error 2
mingw32-make[1]: Leaving directory 'D:/build'
Makefile:85: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by wsfulton** [comment]
This is a more a C++ user issue than a SWIG issue. You need to link to the code that provides `crosscall2`.

**Comment by cyyber** [comment]
@wsfulton The issue doesn't appear if I try to build the same on Linux and I don't need to provide any special link for crosscall2. The crosscall2 is something also mentioned in swig's own source code https://github.com/swig/swig/blob/master/Source/Modules/go.cxx#L4061

**Comment by ojwb** [comment]
`crosscall2` is indeed part of the go runtime.

The answer to avoiding such issues seems to be to use `go build` (as recommended by the Go chapter of the manual).  Trying to compile by hand seems hard to get right (at least from reading #214 - I've not tried myself).

**Comment by Serg0990** [comment]
Hey folks, SWIG 4.1.1 still generates wrapper code for Go that doesn't link under Windows (MinGW):

D:/work/Tools/mingw64-12.2.0-seh/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\SCPPAlgoSwig.dir/objects.a(SCPPAlgCPPAlgoGO_wrap.cxx:(.text+0x46d): undefined reference to `cgo_panic__SCPPAlgo_7cc590670559d8a6'
D:/work/Tools/mingw64-12.2.0-seh/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\SCPPAlgoSwig.dir/objects.a(SCPPAlgCPPAlgoGO_wrap.cxx:(.text+0x53d): undefined reference to `cgo_panic__SCPPAlgo_7cc590670559d8a6'

Looking at the wrapper code, I see this:

extern
#ifdef __cplusplus
  "C"
#endif
  void cgo_panic__SCPPAlgo_7cc590670559d8a6(const char*);
static void _swig_gopanic(const char *p) {
  cgo_panic__SCPPAlgo_7cc590670559d8a6(p);
}

where void cgo_panic__SCPPAlgo_7cc590670559d8a6(const char*) doesn't seem to be defined anywhere, hence the linker errors.

This Windows definition of swig_gopanic(const char *p) is quite different from the Linux one for exactly the same source code:

static void _swig_gopanic(const char *p) {
struct {
const char *p;
} SWIGSTRUCTPACKED a;
a.p = p;
crosscall2(_cgo_panic, &a, (int) sizeof a);
}

and the Linux wrapper does compile and link successfully! 

I'm using go build as recommended above. 
Any other ideas how to make it link under Windows?
What's the logic behind this mysterious void cgo_panic__SCPPAlgo_7cc590670559d8a6(const char*) not implemented anywhere?
