### ISSUE TITLE
swig python. Unable to create class object. 'Class name' is not defined when build with cmake

### ISSUE THREAD

**Issue by vhnatiuk** [swig/swig#1899]
Hello, I'm trying to create callback example. The only difference, I'm trying to build the example with cmake:

cmake_minimum_required(VERSION 3.18)

find_package(SWIG REQUIRED)
include(${SWIG_USE_FILE})
include (UseSWIG)
find_package(PythonInterp ${PYTHONLIBS_VERSION_STRING} REQUIRED)
find_package(Python3 REQUIRED COMPONENTS Interpreter Development)

find_package(Python3 REQUIRED COMPONENTS Interpreter Development)
find_package(PythonLibs 3 REQUIRED)
// my library name
find_library(${MSC_MAIN_LIB} ${PROJECT_SOURCE_DIR}/build/${MSC_MAIN_LIB})

include_directories(${PYTHON_INCLUDE_PATH} ${CMAKE_CURRENT_SOURCE_DIR} ${MSC_SrcPath} ) 
link_directories(${MSC_SrcPath} 
list of directories) # list of directories

set(CMAKE_SWIG_FLAGS "")
set(MODULE_NAME PyExample)
set(CMAKE_SWIG_OUTDIR ${PROJECT_SOURCE_DIR}/build/${MODULE_NAME})

set_property(SOURCE PyExample.i PROPERTY CPLUSPLUS ON SWIG_FLAGS "-fPIC; -py3 ; -builtin; -extranative")

swig_add_library(${MODULE_NAME} TYPE SHARED LANGUAGE python NO_PROXY SOURCES PyExample.i PyExample.h )
swig_link_libraries (${MODULE_NAME} ${MSC_MAIN_LIB} ${PYTHONE_LIBRARIES} )

Perhaps there should be some additional flags . 
When I try to run code from runme.py I'm getting error that Callback is undefined.
I'm using latest version of SWIG 4.0.1

**Comment by ojwb** [comment]
The example works with SWIG, so this seems to be a problem specific to cmake and its SWIG support - that's nothing to do with us so best to ask the cmake people about such issues.
