### ISSUE TITLE
Perl5 question: how to deal with C++ callback from different thread?

### ISSUE THREAD

**Issue by XiaoyaoFan** [swig/swig#1903]
Hi,

I'm working on a project to use SWIG to create a Perl5 wrapper of C++ lib. 

The C++ lib is using multi-threading, an example scenario is: one thread issue a request to a server, another thread triggers a callback when data is received from server.

I'm wondering how can we deal with the case in the Perl wrapper? Is there any code example?

Thanks!

**Comment by ojwb** [comment]
`Examples/perl5/callback/` is an example of a callback in Perl.  As for the callback coming from another thread, I think SWIG shouldn't mind,
