### ISSUE TITLE
simplest `const` or `constexpr` is ignored

### ISSUE THREAD

**Issue by rpattabi** [swig/swig#1904]
swig version: 3.0.12

```
%include "enums.swg"
%javaconst(1);

constexpr int TEN = 10;
enum Foo { ALE, LAGER=TEN, STOUT, PILSNER, PILZ=PILSNER };
```
generates

```
public enum Foo {
  ALE,
  LAGER(TEN),
  STOUT,
  PILSNER,
  PILZ(PILSNER);
```

However, no definition for `TEN` is generated in java. Same result for `const int TEN = 10;`

**Comment by ojwb** [comment]
Not completely ignored, but wrapped as `example.getTEN()`.

`#define TEN 10` gets wrapped as `exampleConstants.TEN` (as `public final static int TEN = 10;`).

Removing `%javaconst(1);` only changes the `#define` case to be wrapped in slightly less efficient way: `public final static int TEP = exampleJNI.TEP_get();`

This is probably one for @wsfulton.

**Comment by wsfulton** [comment]
We're not able to support all C expressions being automatically converted into Java and this is one such case, hence the default mode is %javaconst(0). Sorry, can't fix. Use the solution from the documentation, replace:
```swig
constexpr int TEN = 10;
```
with
```swig
%javaconstvalue(10) LAGER;
```
which generates
```java
public enum Foo {
  ALE,
  LAGER(10),
  STOUT,
  PILSNER,
  PILZ(PILSNER);
```

**Comment by ojwb** [comment]
Oh, sorry I'd missed that the actual issue here is that `getTEN()` wrapping doesn't work in the `enum`.  Resolution makes sense.
