### ISSUE TITLE
static const string in Java with javaconst(1)

### ISSUE THREAD

**Issue by gavol** [swig/swig#1907]
When javaconst(1) is used, static const string are nor properly mapped and the generated code is not valid.

Example test module:

```
%module jTest

%include <typemaps.i>
%include <stl.i>
%javaconst(1);

struct Test {
    static const std::string aString = "something";
};
```
In Java the static const string is mapped to:

`public final static String aString = something;`

Note the missing quotes.

If javaconst(1) is removed, then valid Java code is generated:

`public final static String aString = jTestJNI.Test_aString_get();`

Using SWIG 4.0.1.

**Comment by ojwb** [comment]
Reproduced with current git master.

**Comment by ojwb** [comment]
Another example from #913 shows an interesting bad handling for an empty string:

```
%constant std::string MY_STRING = "";
```

gives:

```
public final static String MY_STRING = \0;
```
