### ISSUE TITLE
Use fully-tagged so name for python c-extension module shared objects

### ISSUE THREAD

**Issue by mattip** [swig/swig#1912]
Trying to figure out the failure of conda-forge/faiss-split-feedstock#22 to build faiss via CMake and SWIG for PyPy on conda-forge (whew!). Does SWIG, by default, link a shared object with the name, for instance, `_mymodule.so` for `mymodule`? The [documentation for hand-compilation](http://www.swig.org/Doc4.0/Python.html#Python_nn7) seems to suggest this is the case. If so this seems dangerous: the name should be `_mymodule.cpython-38-x86_64-linux-gnu.so` (for cpython 3.8 on linux64-bit). This would prevent errors where the wrong python version tries to import a SWIG c-extension module. If SWIG supports the stable ABI, then the name should be `_mymodule.abi3-x86_64-linux-gnu.so`.

This came up since PyPy does not support loading CPython c-extension modules, so it requires the "full" name in the shared object.

<details>
<summary>The relevant comment from the linked PR:</summary>

The following code 
```
>>> import importlib
>>> importlib._imp.extension_suffixes()
```
prints the valid suffixes for c-extension modules that the interpreter can import. This prints
`['.cpython-38-x86_64-linux-gnu.so', '.abi3.so', '.so']` on CPython3.8, but
`['.pypy37-pp73-x86_64-linux-gnu.so']` on PyPy3.7. 

Note that PyPy does not support `abi3.so` (the "stable API" I referred to above) nor `.so` with no tags.
This is due to PyPy not supporting importing c-extension modules compiled for CPython. See [issue 2617](https://foss.heptapod.net/pypy/pypy/-/issues/2617#note_45057) for a long discussion of possible future work in this direction.

**Comment by ojwb** [comment]
SWIG just generates the source files - it doesn't do the building or linking steps for you at all so it's up to your build system what the built files get named.
