### ISSUE TITLE
AIX 7.1 : CCache tests: CFLAGS is not passed

### ISSUE THREAD

**Issue by trex58** [swig/swig#1924]
I've ported Swig 4.0.2 to AIX 7.1 .

When the CCache tests are done, the CFLAGS is not passed to the test.sh command.
However, on AIX, one can build applications in 32bit (default) or in 64bit, using either -maix32 (default) or -maix64 within GCC.
Thus, in order to test CCache in 64bit, the following change is required on AIX. See the attached defect.

[CCache-64bit.patch.txt](https://github.com/swig/swig/files/5796447/CCache-64bit.patch.txt)

**Comment by ojwb** [comment]
I'd also like to see this one run in CI.

**Comment by ojwb** [comment]
I opened a PR for you, but it causes the ccache testsuite to fail in CI on Linux, and I can reproduce that failure locally - in the `CCache` subdirectory:

```
$ make check
/bin/sh ./config.status
config.status: creating config_win32.h
config.status: creating Makefile
config.status: creating config.h
config.status: config.h is unchanged
SWIG_LIB='.././../Lib' PATH=../..:$PATH SWIG='swig' CC='gcc' CFLAGS='-g -O2 -Wall -W -I.' NOSOFTLINKSTEST='' CCACHE='../ccache-swig' CCACHE_PROG=ccache-swig ./test.sh
starting testsuite base
SUITE: base TEST: CCACHE_UNIFY - Expected cache hit to be 6 got 7
cache directory                     ccache dir
cache hit                              7
cache miss                             6
called for link                        1
multiple source files                  1
compiler produced stdout               1
couldn't find the compiler             1
bad compiler arguments                 1
not a C/C++ file                       1
unsupported compiler option            1
output to a non-regular file           1
no input file                          1
files in cache                        10
cache size                            20 Kbytes
max cache size                     976.6 Mbytes
TEST FAILED
make: *** [Makefile:68: test] Error 1


```
+ make -j2 check-ccache
test -z "1" || (cd CCache && make check)
make[1]: Entering directory '/home/runner/work/swig/swig/build/build/CCache'
SWIG_LIB='../../../../CCache/../Lib' PATH=../..:$PATH SWIG='swig' CC='gcc-7' CFLAGS='-g -O2 -Wall -W -I.' NOSOFTLINKSTEST='' CCACHE='../ccache-swig' CCACHE_PROG=ccache-swig ../../../CCache/test.sh
starting testsuite base
SUITE: base TEST: CCACHE_UNIFY - Expected cache hit to be 6 got 7
cache directory                     ccache dir
cache hit                              7
cache miss                             6
called for link                        1
multiple source files                  1
compiler produced stdout               1
couldn't find the compiler             1
bad compiler arguments                 1
not a C/C++ file                       1
unsupported compiler option            1
output to a non-regular file           1
no input file                          1
files in cache                        10
cache size                            20 Kbytes
max cache size                     976.6 Mbytes
TEST FAILED
```

So sorry, but I'm going to have to reject the proposed patch.

I'd encourage you to rework this such that the tests still pass on Linux, but please **open a PR** with your revised patch - then CI gets run automatically, and you'd have seen this problem with the patch over a year ago rather than only once someone else found the time to open a PR on your behalf.
