### ISSUE TITLE
for Python language, parts of test typemap_qualifier_strip are wrong

### ISSUE THREAD

**Issue by trex58** [swig/swig#1925]
By default, Swig tests are done without any CFlags, thus without any -O option.

So, on Fedora33/x86_64, by default, we have the following instructions being executed for test **typemap_qualifier_strip** test and showing success:

```
g++ -c -fpic -I. -I./ -I/usr/include  typemap_qualifier_strip_wrap.cxx   -I../../../Examples/test-suite  -I/usr/include/python3.9 -I/usr/include/python3.9
g++ -shared  -I/usr/include     typemap_qualifier_strip_wrap.o    -o _typemap_qualifier_strip.so
env LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH PYTHONPATH=.:.:$PYTHONPATH  python3 typemap_qualifier_strip_runme3.py
```

However, if one makes use of CFLAGS with **-O2**, we have an error at runtime:
```
+ cd ./Examples/test-suite/python/
+ g++ -O2 -c -fpic -I. -I./ -I/usr/include typemap_qualifier_strip_wrap.cxx -I../../../Examples/test-suite -I/usr/include/python3.9 -I/usr/include/python3.9
+ g++ -shared -I/usr/include typemap_qualifier_strip_wrap.o -o _typemap_qualifier_strip.so
+ env LD_LIBRARY_PATH=.: PYTHONPATH=.:.: python3 typemap_qualifier_strip_runme3.py
Traceback (most recent call last):
  File "Examples/test-suite/python/typemap_qualifier_strip_runme3.py", line 5, in <module>
    raise RuntimeError
RuntimeError
```

This is due to this code from: ./Examples/test-suite/python/**typemap_qualifier_strip_wrap.cxx** :
```
  3040 SWIGINTERN PyObject *_wrap_testA1(PyObject *SWIGUNUSEDPARM(self), PyObject *args) {
  3041   PyObject *resultobj = 0;
  3042   int *arg1 = (int *) (int *)0 ;
  3043   PyObject *swig_obj[1] ;
  3044   int result;
  3045
  3046   if (!args) SWIG_fail;
  3047   swig_obj[0] = args;
  3048   {
  3049     int temp = 1234;
  3050     arg1 = &temp;
  3051   }
  3052   result = (int)testA1((int const *)arg1);
```
where the variable **temp** is defined INSIDE { ... } and thus exists ONLY inside these { ... }. Thus its address &temp has no meaning outside, and arg1 contents an address to some place that can be reused.
Thus, using:   arg1  OUTSIDE/AFTER the { ... } refers to an address &temp which still has a correct meaning when code is compiled with -O0 but which meaning is volatile (and cleaned) when code is compiled with -O2 which implies to clean un-useful data and memory.

This issue seems to appear for **A1, A2, A3, and A4.**

The bug disappears (with -O2) if the code is rewritten as:
```
    int temp;
    if (!args) SWIG_fail;
    swig_obj[0] = args;
    {
      temp = 1234;
      arg1 = &temp;
    }
    result = (int)testA1((int const *)arg1);
```
where the variable "temp" is defined before the { ... } is opened.

However, since I'm not sure about the goal of that test, I need some Swig expert to look at this and check my analysis.

**Comment by ojwb** [comment]
Fails on x86-64 linux too:

```
$ make -C Examples/test-suite/python -s typemap_qualifier_strip.cpptest PY3=1 CXXFLAGS=-O2
checking python testcase typemap_qualifier_strip (with run test)
Traceback (most recent call last):
  File "/home/olly/git/swig/Examples/test-suite/python/./typemap_qualifier_strip_runme.py", line 5, in <module>
    raise RuntimeError
RuntimeError
make: *** [Makefile:108: typemap_qualifier_strip.cpptest] Error 1
```

**Comment by ojwb** [comment]
It's also not specific to Python, and is a bug in this particular testcase.  I've pushed a fix - thanks for finding, for reporting and for the useful analysis.
