### ISSUE TITLE
Passing shared_ptr and pointer from C++ to Python function

### ISSUE THREAD

**Issue by maisping** [swig/swig#1931]
Hello.

**Brief**
The problem I have encountered - I cannot pass both std::shared_ptr<WrappedClass> and WrappedClass* as arguments for python function from C++.

**Wrapped Class**
I have a simple class for wrapping, and using swigpyrun.h generated file I can pass it to python function.

```
struct MyClass
{
	int foo(); //return  42;
};
```

**.i file**

```
%module swigstvo
%include "windows.i"
%include <std_shared_ptr.i>
%shared_ptr(MyClass)


%{
	#include <memory>
	#include "MyClass.h"
%}

%include "MyClass.h"
```

**The problem**
When I add the line "%shared_ptr(MyClass)" in .i file, the ability to use raw pointer is lost. 
```
PyObject* pArgs = PyTuple_New(1);
PyObject* pObj(NULL);

//SMART CASE: works fine if .i file has the line "%shared_ptr(MyClass)"
auto smart_obj = std::make_shared<MyClass>();
pObj = SWIG_NewPointerObj((void*)&smart_obj, SWIG_TypeQuery("_p_std__shared_ptrT_MyClass_t"), 0);
PyTuple_SetItem(pArgs, 0, pObj);
PyObject_CallObject(pFunc, pArgs);

//TRAW CASE: works fine only if .i file does not have line "%shared_ptr(MyClass)"
auto obj = MyClass{};
pObj = SWIG_NewPointerObj((void*)&obj, SWIG_TypeQuery("_p_MyClass"), 0);
PyTuple_SetItem(pArgs, 0, pObj);
PyObject_CallObject(pFunc, pArgs);
```
**Generated .cxx**

If we look at generated .cxx file, we can see, that it gives us two mangled names: one for raw pointer and another for smart pointer.
```
static swig_type_info _swigt__p_MyClass = {"_p_MyClass", "MyClass *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_std__shared_ptrT_MyClass_t = {"_p_std__shared_ptrT_MyClass_t", "std::shared_ptr< MyClass > *", 0, 0, (void*)0, 0};
```

**What is more interesting?**
If I remove the "%shared_ptr(MyClass)" from .i file and change SMART CASE like this:
```
auto smart_obj = std::make_shared<MyClass>();
pObj = SWIG_NewPointerObj((void*)&smart_obj, SWIG_TypeQuery("_p_MyClass"), 0);
PyTuple_SetItem(pArgs, 0, pObj);
PyObject_CallObject(pFunc, pArgs);
```
The python code still works as intended, though I passed pointer to smart_pointer instead of raw pointer, and still creating PyObject was a success.

**Python code**

```
import swigstvo
   
def boo(mycl):
    try:
        print("value {0}".format(mycl.foo()))
    except BaseException as e:
        print(e)
```

**Conclusion**
It is possible to use both shared_ptr<Wrapped_class> and Wrapped_class* as arguments for python functions?

**Comment by adl** [comment]
> When I add the line "%shared_ptr(MyClass)" in .i file, the ability to use raw pointer is lost.

I stumbled upon this issue while researching another `shared_ptr`-related issue.  I cannot really answer it, but I'd like to point out that the quoted inconvenience is [documented](http://www.swig.org/Doc4.0/Library.html#Library_shared_ptr_overloading).

**Comment by wsfulton** [comment]
It is possible to use raw pointers as well as shared_ptr in wrapped APIs. The typemaps are available for both when using %shared_ptr. So, expanding on your example, you could have:
```c++
void takeRawPointer(MyClass *p);
void takeSmartPointer(std::shared<MyClass> p);
```
and call both functions using the same Python object.
