### ISSUE TITLE
Observable pattern and Directors

### ISSUE THREAD

**Issue by charles-huet-ixxi** [swig/swig#1937]
Hi,

I have encountered an issue with the Observer pattern and directors.

Simply put, I have an observer that can be inherited from in Java to observe a C++ object.
The issue is that the observer created on the java side is not owned by Java and gets deleted before use.

I have written a full reproducer that I have attached.
Simply starting the java program should crash.

```java
public class Main {

	public static void addObserver(Observable foo) {
		Observer bar = new Observer() {
			@Override
			public void update() {
				System.out.println("Java observer");
			}
		};
		foo.setObserver(bar);
	}

	public static void main(String[] args) {
		System.loadLibrary("swigDirectorTestSWIG");

		Observable foo = new Observable();

		foo.change();

		System.out.println("Observable Director Test");
	}
}
```

The full reproducer is here: https://github.com/charles-huet-ixxi/swig-reproducer

I worked around the issue by calling `bar.swigReleaseOwnership();`, but this seems hacky to me. Is this the recommended way of doing this ?

Thanks

**Comment by wsfulton** [comment]
The memory management in your example is not clear to me. Looks like calling `bar.swigReleaseOwnership()` will create a memory leak, but maybe that is okay for you. Otherwise you will need to make sure that the bar instance is kept alive in Java until you have finished with it (add it to a global collection or such like).

**Comment by charles-huet-ixxi** [comment]
So what you mean is we need to hold a reference to these objects on the Java side manually ?
i.e. SWIG will not hold references to them ?

Meaning when I implement the observable pattern, each Observable should hold a list of its observers on the Java side to ensure they will not be deleted ?

**Comment by charles-huet-ixxi** [comment]
Which part is not clear in the example, so that I can make it clearer, if I can ?

I have to admit the memory management is my issue, as I though at first that SWIG would hold a java reference to objects passed to the director.

Is there a typemap or somesuch I could use to indicate to SWIG that I want a reference to be kept on objects passed to these functions ? I could not find any such thing in the documentation.

The only other solution I have in mind is to create a Java base implementation of my observable class and have it hold references to the observers.

**Comment by Nenginyo** [comment]
ci/blank.yml

**Comment by charles-huet-ixxi** [comment]
For anyone finding this and looking for the solution, [This part of the documentation](http://www.swig.org/Doc4.0/SWIGDocumentation.html#Java_memory_management_objects) explains what should be done in those cases
