### ISSUE TITLE
Wrapping c++ enum 

### ISSUE THREAD

**Issue by titimain** [swig/swig#194]
Hello, 
I have enum like this:
```
typedef enum
{
	BinPath,
	SharePath,
	VarPath
} PathType;
```
which not belongs to any class, but a namespace mdl::pkg, I'd like to wrap this enum and use  it in others classes included in mdl python module.
I need your help. 
Thank you

**Comment by fahhem** [comment]
What swig file have you tried? This should just work:

swig3.0 -python -c++ enum_file.i

enum_file.i:
%module enum_module
%{
#include "mdl/pkg/enum_file.h"
using namespace mdl::pkg;
%}

%include "mdl/pkg/enum_file.h"

**Comment by ojwb** [comment]
This should indeed already work.  No response from the submitter in close to a year, so closing.

@titimain If you still thing there's an issue here, please supply a small, self-contained reproducer and we can reopen.
