### ISSUE TITLE
Compiling SWIG without MinGW?

### ISSUE THREAD

**Issue by IngwiePhoenix** [swig/swig#1941]
Hello!

I am currently reading all the way across the SWIG source for two main reasons:
- Creating a language wrapper for AngelScript: http://angelcode.com/angelscript/
- Creating a C++-interop (C++ to C wrapper) for vlang: https://github.com/vlang/v

The first thing that I ran across was that SWIG requires MinGW on Windows. Well, one workaround that I had managed to make work was to use Emscripten + Nodejs to run SWIG as a WASM module. Clunky, but it *did* work. However, I was curious to learn why there is no native Windows build - be it via CMake or Visual Studio? From what I have read so far, it should, in theory, be possible to do build, but I haven't worked through the autoconf files enough to try and reproduce it on the CLI to see if I can compile the whole of SWIG using `cl.exe`. Mainly, what dependencies there are or might be missing and what `-D`efines I would be needing.

Hope you can help me understand :)

Kind regards,
Ingwie

**Comment by vadz** [comment]
SWIG can be built using MSVC, I used to do it and have a simple `makefile.cl` that I used for it, but I had to maintain it manually and it just wasn't worth it. Compiling, or even cross-compiling from Linux, is simpler and in my tests MinGW version is actually slightly faster than the MSVC one (which surprised me a bit), even though it's also much bigger.

**Comment by geographika** [comment]
CMake builds would be great. Any MSVC builds would be useful for being able to step through code using the debugger in Visual Studio for Windows devs. If you make any progress @IngwiePhoenix please post any links to branches etc.

**Comment by IngwiePhoenix** [comment]
@geographika I'll probably stick to master and after getting a good understanding of the autotools setup, I'll see if I can make a CMake version of this. No promises - but I can at least give it a shot. :)

@vadz Considering minGW usually links a static libc and that - depending on what version of MinGW you use - can even be MUSL or another implementation of libc, which might actually improve performance. Just a wild guess though. One would have to profile the two builds call-by-call and see what each of them ends up doing ultimatively. But using a `Makefile.cl` is probably where I'll start to get a basis going which i can work off untill I am sure enough of the requirements.

I am mostly interested in what defines SWIG wants and expects to find either in `config.h` or similiar and other defines that might be used. And, if I can use https://github.com/lexxmark/winflexbison as a replacement on Windows. My main package manager on Windows is Chocolatey, which makes installing these things quite easy (`choco install ninja cmake visualstudio2019community winflexbison`) and might be a good starting point for new users/devs that want to work directly with the source.

**Comment by vadz** [comment]
Note that there is already a PR with CMake support, see #1040. I avoid CMake as much as I can, so I have no idea about its status.

The main problem in practice is PCRE, as it needs to be compiled too.

The rest is simple, especially if you use Cygwin or MSYS2 and I guess should be reasonably simple with Chocolatey as well, i.e. my `Source/Makefile.cl` is just:
```make
all: swig.exe

ifdef DEBUG
    swig_CFLAGS := -Zi -D_DEBUG /MTd
else
    swig_CFLAGS := -DNDEBUG -O2 -GL /MT
endif

swig_CFLAGS += /EHsc /DPCRE_STATIC

swig_INCLUDES := -IInclude/msvc -IInclude -ICParse -IPreprocessor -IDoh -IModules -IDoxygen -ISwig
swig_LIBS := pcre.lib

swig_HEADERS = Include/swigwarn.h Include/msvc/swigconfig.h $(wildcard */*.h)

swig_SOURCES = CParse/parser.c $(wildcard */*.c*)

swig.exe: $(swig_SOURCES) $(swig_HEADERS)
        cl /nologo $(swig_CFLAGS) $(swig_INCLUDES) -MP -DWIN32 -D_CONSOLE $(swig_SOURCES) \
            /link /subsystem:console /out:$@ $(swig_LIBS)

CParse/parser.h: CParse/parser.c

CParse/parser.c: CParse/parser.y
        bison -d -o $@ $<

clean:
        $(RM) *.obj swig.exe swig.ilk *.pdb

.PHONY: clean
```

and here is the top-level makefile:
```make
# Makefile for building SWIG with Microsoft Visual C++ compiler (cl.exe)
#
# Notice that this is a GNU make makefile and not an nmake one and it relies
# on having the usual Unix/Cygwin tools available.

swig: libfiles source

source:
        @$(MAKE) -C Source -f Makefile.cl

libfiles: Lib/swigwarn.swg

Lib/swigwarn.swg: Source/Include/swigwarn.h
        mkdir -p Lib
        echo "/* Automatically generated file containing all the swig warning codes.  */" > $@
        echo "/* Do not modify this file by hand, change 'Source/Include/swigwarn.h'  */" >> $@
        echo "/* and use the command 'make Lib/swigwarn.swg' instead.                 */" >> $@
        echo >> $@; echo >> $@
        awk '/#define WARN/{$$1="%define"; $$2="SWIG"$$2; $$3=sprintf("%d %%enddef", $$3); print $$0; next;}\
              /#/{next;} {print $0}' < $? >> $@

clean:
        @$(MAKE) -C Source -f Makefile.cl clean

.PHONY: clean libfiles source swig
```

**Comment by ojwb** [comment]
#1040 got merged, so closing.
