### ISSUE TITLE
swig-4.0.2 error: ‘kwargs’ was not declared in this scope compiling python

### ISSUE THREAD

**Issue by mwheaton** [swig/swig#1942]
I get this error compiling python (3.4, 3.6, or 3.7)  when I try to use swig-4.0.2.     I do not get this error with swig-4.0.1:

/usr/local/gcc6/bin/g++ -O2 -fpic -fpermissive -I/media/sf_home/OpenAccess_local/oa22.60p036/include -DSWIG_TYPE_TABLE=oa -D_GLIBCXX_USE_CXX11_ABI=0  -I.. -I/usr/include/python3.4m -I/usr/include/python3.4m -c -o build/3.4/64bit-ELF/base_wrap.o build/base_wrap.cc
build/base_wrap.cc: In function ‘int _wrap_new_oaError_private__varargs__(PyObject*, PyObject*, PyObject*)’:
build/base_wrap.cc:80174:36: error: ‘kwargs’ was not declared in this scope
   if (!SWIG_Python_CheckNoKeywords(kwargs, "new_oaError_private")) SWIG_fail;
                                    ^~~~~~
build/base_wrap.cc: At global scope:
build/base_wrap.cc:247458:1: warning: invalid conversion from ‘PyObject* (*)(PyObject*, PyObject*) {aka _object* (*)(_object*, _object*)}’ to ‘objobjproc {aka int (*)(_object*, _object*)}’ [-fpermissive]
 };

Somehow it includes the warning before it dies.  

The offending lines:

Line 80174:
  if (!SWIG_Python_CheckNoKeywords(kwargs, "new_oaError_private")) SWIG_fail;

Line 247458:
#if PY_VERSION_HEX >= 0x03030000
    (PyObject *) 0,                           /* ht_qualname */
    0,                                        /* ht_cached_keys */
#endif
};

base_wrap.cc is generated by swig of course.  

Thanks, 
Matt

**Comment by wsfulton** [comment]
What's a minimal cut down example of SWIG code and command line options you are passing to SWIG to reproduce this?

**Comment by mwheaton** [comment]
Thanks for asking!

Command line options:
/usr/local/swig-4.0.2/bin/swig -c++  -w201 -w362 -w389 -w503 -w383 -w509 -w361 -w394 -w395 -w302 -w401 -w314 -w315 -I/media/sf_home/OpenAccess_local/oa22.60p036/include -includeall -ignoremissing -builtin -O -python -I.. -I. -I/usr/local/swig-4.0.2/share/swig/4.0.2 -o build/base_wrap.cc -outdir oa ../base.i

This is the block of swig code that fails:
SWIGINTERN int _wrap_new_oaError_private__varargs__(PyObject *self, PyObject *args, PyObject *varargs) {
  PyObject *resultobj = 0;
  OpenAccess_4::oaUInt4 arg1 ;
  void *arg2 = 0 ;
  unsigned int val1 ;
  int ecode1 = 0 ;
  PyObject * obj1 = 0 ;
  OpenAccess_4::oaError *result = 0 ;
  
  if (!SWIG_Python_CheckNoKeywords(kwargs, "new_oaError_private")) SWIG_fail;
  if (!PyArg_UnpackTuple(args, "new_oaError_private", 1, 1, &obj1)) SWIG_fail;
  ecode1 = SWIG_AsVal_unsigned_SS_int(obj1, &val1);
  if (!SWIG_IsOK(ecode1)) {
    SWIG_exception_fail(SWIG_ArgError(ecode1), "in method '" "new_oaError_private" "', argument " "1"" of type '" "OpenAccess_4::oaUInt4""'");
  } 
  arg1 = static_cast< OpenAccess_4::oaUInt4 >(val1);
  {
    try {
      result = (OpenAccess_4::oaError *)new OpenAccess_4::oaError(arg1,arg2);
    }
    /*@SWIG:../python/oatype_macrodefs.i,901,LANG_CATCH@*/
    catch (OpenAccess_4::oaException& e) {
      LANG_THROW_OAEXCP(e);
    } catch (const oaCommon::IException& e) {
      SWIG_exception_fail(SWIG_RuntimeError, e.getMsg());
    } catch (const oasIndexErrorException& e) {
      SWIG_exception_fail(SWIG_IndexError, e.what());
    } catch (const oasException& e) {
      SWIG_exception_fail(SWIG_RuntimeError, e.what());
    } catch (const Swig::DirectorException& e) {
#ifdef CATCH_DIRECTOR_EXCEPTIONS
      SWIG_fail;
#else
      fprintf(stderr, "%s\n", e.getMessage());
      PyErr_Print();
      throw;
#endif
    }
    /*@SWIG@*/
  }
  resultobj = SWIG_NewPointerObj(SWIG_as_voidptr(result), SWIG_TypeDynamicCast(SWIGTYPE_p_OpenAccess_4__oaError, SWIG_as_voidptrptr(&result)), SWIG_BUILTIN_INIT |  0 );
  return resultobj == Py_None ? -1 : 0;
fail:
  return -1;
}

The error occurs at the line:    if (!SWIG_Python_CheckNoKeywords(kwargs, "new_oaError_private")) SWIG_fail;
If you want a compileable example, then I'm going to have to figure out how to pare down a file that's  about 330,000 lines long.

I confirmed that the share/4.0.2/python directory has the same list of files as 4.0.1

Matt

**Comment by mwheaton** [comment]
Compare to the 4.0.1 output for the same block of code:
SWIGINTERN int _wrap_new_oaError_private__varargs__(PyObject *self, PyObject *args, PyObject *varargs) {
  PyObject *resultobj = 0;
  OpenAccess_4::oaUInt4 arg1 ;
  void *arg2 = 0 ;
  unsigned int val1 ;
  int ecode1 = 0 ;
  PyObject * obj1 = 0 ;
  OpenAccess_4::oaError *result = 0 ;
  
  if (!PyArg_UnpackTuple(args, "new_oaError_private", 1, 1, &obj1)) SWIG_fail;
  ecode1 = SWIG_AsVal_unsigned_SS_int(obj1, &val1);
  if (!SWIG_IsOK(ecode1)) {
    SWIG_exception_fail(SWIG_ArgError(ecode1), "in method '" "new_oaError_private" "', argument " "1"" of type '" "OpenAccess_4::oaUInt4""'");
  } 
  arg1 = static_cast< OpenAccess_4::oaUInt4 >(val1);
  {
    try {
      result = (OpenAccess_4::oaError *)new OpenAccess_4::oaError(arg1,arg2);
    }
    /*@SWIG:../python/oatype_macrodefs.i,901,LANG_CATCH@*/
    catch (OpenAccess_4::oaException& e) {
      LANG_THROW_OAEXCP(e);
    } catch (const oaCommon::IException& e) {
      SWIG_exception_fail(SWIG_RuntimeError, e.getMsg());
    } catch (const oasIndexErrorException& e) {
      SWIG_exception_fail(SWIG_IndexError, e.what());
    } catch (const oasException& e) {
      SWIG_exception_fail(SWIG_RuntimeError, e.what());
    } catch (const Swig::DirectorException& e) {
#ifdef CATCH_DIRECTOR_EXCEPTIONS
      SWIG_fail;
#else
      fprintf(stderr, "%s\n", e.getMessage());
      PyErr_Print();
      throw;
#endif
    }
    /*@SWIG@*/
  }
  resultobj = SWIG_NewPointerObj(SWIG_as_voidptr(result), SWIG_TypeDynamicCast(SWIGTYPE_p_OpenAccess_4__oaError, SWIG_as_voidptrptr(&result)), SWIG_BUILTIN_INIT |  0 );
  return resultobj == Py_None ? -1 : 0;
fail:
  return -1;
}

**Comment by mwheaton** [comment]
I have been having trouble tracking down a swig code sample that generates the error, but I have tracked it down to this in the C++:

This single line is what causes the error and it happens in about five of the modules we generate (we wrap a suite of shared libraries):
  if (!SWIG_Python_CheckNoKeywords(kwargs, "new_Exception")) SWIG_fail;

This line appears in this block:
SWIGINTERN int _wrap_new_Exception__varargs__(PyObject *self, PyObject *args, PyObject *varargs) {

If I comment the line out, it compiles.  If I change 'kwargs' to 'args' it compiles.  The problem appears to be related to issue #1595   Somehow 'kwargs' is not declared in this scope.

I will try again to generate a small test case.

Matt

**Comment by mwheaton** [comment]
I am fortunate to have a colleague who was able to pare down our extensive code to a size that gives a workable example:
[footest.tar.gz](https://github.com/swig/swig/files/6084312/footest.tar.gz)

Thank you for your help,
Matt

**Comment by wsfulton** [comment]
Looks like it started when #1595 was implemented. If you need a workaround with 4.0.2 let me know. In the meantime, I'll put a fix in for 4.1.0.

**Comment by mwheaton** [comment]
Thanks William!  We are okay using 4.0.1 right now.  Do we know when 4.1.0 will be coming out?

Matt

**Comment by wsfulton** [comment]
Please track https://github.com/swig/swig/milestone/3 for the 4.1.0 release.
