### ISSUE TITLE
How to detect OS platform windows when parsing swig interface file?

### ISSUE THREAD

**Issue by ArchieMeng** [swig/swig#1954]
I am now doing a cross-platform swig for python build. However, I cannot find a way to detect OS in current SWIG (4.0).
I know it used to rely on SWIGWIN macro but it was removed in version newer than 1.3. Docs: http://www.swig.org/Doc1.3/Preprocessor.html
http://www.swig.org/Doc4.0/Preprocessor.html
So how can I detect windows os in interface file now?
I am using Visual Studio 2019 to build the project on windows 10. I tried using
```C
#if _WIN32
....
#else
....
#endif 
```
or
```C
#if __WIN32__
....
#else
....
#endif 
```
None of them works for me when wrote them in the interface file (interface.i).

**Comment by vadz** [comment]
SWIG produces the same output wherever you run it, so testing for the platform just doesn't make sense. Of course, you can have `#ifdef _WIN32` tests in the generated code, but this is rather different.

**Comment by ArchieMeng** [comment]
So does it mean that I cannot detect which platform I am compiling for within SWIG? The only solution for me is to create two different wrapper parts and run the platform specific part from caller rather than wrapper?

**Comment by vadz** [comment]
Why would you want to do it in the first place? SWIG is a transpiler, you don't care about the platform SWIG runs under, even if you may need to test the platform the compiled code runs under.

To put it maximally clearly: you don't "compile for" any platform with SWIG. SWIG output is platform-independent, but the results of compiling that output with the actual C++ compiler may not be.

**Comment by ArchieMeng** [comment]
The reason I want to do this is that, the function I need to wrap have different function signature for windows and other platforms. This is a problem in my project waifu2x-ncnn-vulkan-python with wraping Waifu2x::load(). It uses **load(const std::wstring&, const std::wstring&)** on Windows, but **load(const std::string&, const std::string&)** for other platforms. And this is done by checking _WIN32 macro in the original C++ library source code. 
So I think it will be better if I can detect it in SWIG so that I can correctly wrap the function.

**Comment by vadz** [comment]
You're still mixing up SWIG-time and compile-time. Sorry, I don't know how to explain this any more clearly, but you need to make SWIG output the same code containing `#ifdef _WIN32` everywhere instead of trying to output different code depending on the platform you're running under.

**Comment by ArchieMeng** [comment]
So this is the problem. The function I need to wrap use different parameter types under different platforms. I am afraid I can't archive such wrapping by pass through "same code containing #ifdef _WIN32". 
Thanks for your detailed explanation for saving me a lot of times playing with SWIG preprocessing.
I now give up doing the porting at interface file, but to use union and cpointers.i to do the fitting for such functions.
