### ISSUE TITLE
Syntax error from operator overload template in template

### ISSUE THREAD

**Issue by ganc** [swig/swig#196]
I’m attempting to wrap a C++ class in CSharp using SWIG 3, and I get syntax errors on overload templates of >> and << (lines 10-11) 

I have tried ignoring them and templating them, but neither work. 

Below, I have a minimal version of the header file that still generates the syntax error, and my swig interface file. The presence or nonpresence of the "friend" keywords does not make a difference. 

UPDATE: William Fulton believes this is due to the C++11 support added in SWIG 3. He suggests using swig-2.0.12 until it is resolved. 

 ```cplusplus
/* file: header.h */
template <typename Type> class MyClass;
 
template <typename Type> int operator<<(int un, const MyClass <Type> & x); template <typename Type> int operator>>(int is, MyClass <Type>  & x);
 
template <class Type> class  MyClass
{
 
                friend int operator<< <Type>(double un, const MyClass <Type> & x);   //line 10
                friend int operator>> <Type>(double is, MyClass <Type>  & x);    //line 11
 
};   
``` 
 

 ```cplusplus
/* file: swigfile.i */
%module swigfile_module
%{
#include “header.h”
%}
 
%ignore "operator<<";
%ignore "operator>>";
%include "header.h" 
%template(foo) operator<< <int>;
%template(bar) operator>>  <int>;
%template(MyClassDouble) MyClass<Double>
```

**Comment by wsfulton** [comment]
I've been looking at this bug and found that it doesn't work prior to SWIG 3 either, so it doesn't actually have anything to do with the C++11 additions. I have a fix and will commit it.

**Comment by wsfulton** [comment]
It also isn't just operators, although getting a syntax error is specific to operators. SWIG was unable to support the template '<Type>' after the symbol name in a function declaration as this is quite unusual. In fact, removing 'friend' from the code above is not valid C++ with the <Type> left in as there is no such thing as partial specialization for functions.
