### ISSUE TITLE
Go: Example on using C++ namespace

### ISSUE THREAD

**Issue by m-kru** [swig/swig#1967]
Is there any example on using C++ namespace within Go? Looks like there is none in the `Examples/go`, however maybe it is placed somewhere else.

**Comment by wsfulton** [comment]
Namespace support in SWIG is discussed here http://swig.org/Doc4.0/SWIGPlus.html#SWIGPlus_namespaces. There isn't much different about Go and namespaces, they are effectively ignored as Go does not support `%nspace`.
