### ISSUE TITLE
Javascript pass an anonymous object ?

### ISSUE THREAD

**Issue by wolfviking0** [swig/swig#1970]
Hi Guys,

I am working with SWIG and NODE, and I would like to pass to my C++ function a structure something like :

```
struct Params {
    int version,
    string name,
}

void myParams(const Params& params) {...}
```

Currently in order to initialize my parameter I use :
```
let params = new cg.Params()
params.version = 0
params.name = "test"
```

If there any way I can initialize the javascript side like that (or something similar):
```
let params = {
   version: 0,
   name: "test"
}
```

Thanks

**Comment by wsfulton** [comment]
You can use syntax like this:
```javascript
var p = new example.Params(10, "stringy");
```
if you make use of SWIG's %extend feature to add in a constructor for use from Javascript as follows:
```swig
%extend Params {
  Params(int version, std::string name) {
    Params* p = new Params();
    p->version = version;
    p->name = name;
    return p;
  }
}
```
