### ISSUE TITLE
Nondeterministic __str__ extended Function

### ISSUE THREAD

**Issue by acpaquette** [swig/swig#1972]
Hello!

Currently, the team at USGS Astro is trying to wrap a portion of a large [software package](https://github.com/USGS-Astrogeology/ISIS3) (ISIS) and are running into an interesting issue, specifically a nondeterministic print function.

We have a few objects that we are trying to print out in python with the following extended function:
```
const char * __str__() {
  std::ostringstream os;
  os << *$self;
  std::string str = os.str();
  const char * c_str = str.c_str();
  return c_str;
};
```
This extended function takes advantage of an overloaded `operator <<` function on the objects we are trying to print. The objects specifically are [PvlKeyword](https://github.com/USGS-Astrogeology/ISIS3/blob/pvl_core/isis/src/core/src/PvlKeyword.cpp#L1781), [PvlGroup](https://github.com/USGS-Astrogeology/ISIS3/blob/28e2e212f9f1aa391dc3a26ac104fb4a7696fbec/isis/src/core/src/PvlGroup.cpp#L158), [PvlObject](https://github.com/USGS-Astrogeology/ISIS3/blob/28e2e212f9f1aa391dc3a26ac104fb4a7696fbec/isis/src/core/src/PvlObject.cpp#L538), and [Pvl](https://github.com/USGS-Astrogeology/ISIS3/blob/28e2e212f9f1aa391dc3a26ac104fb4a7696fbec/isis/src/core/src/Pvl.cpp#L235). It seems like the issue has something to do with the stream being written out. Either the string isn't fully written when the return is executed or the data is lost once the program exits the function scoped.

Here is an example of the nondeterministic nature of the print:
<img width="328" alt="Screen Shot 2021-03-10 at 5 14 48 PM" src="https://user-images.githubusercontent.com/17728237/110829329-38b2b900-8255-11eb-801d-5f91dfbf0ecc.png">

Here is another example where we ran into a unicode error on the python side:
<img width="732" alt="Screen Shot 2021-03-10 at 5 29 58 PM" src="https://user-images.githubusercontent.com/17728237/110829340-3a7c7c80-8255-11eb-9722-12cf86e9bd65.png">

Let me know if there is any other information I can provide for better context around this problem. Thank you!

**Comment by acpaquette** [comment]
It seems like the fix for this was allocating the memory for the char * then copying the contents of the string into it before returning. This seems counter to what I have seen on stackoverflow and how other people have been able to write a `__str__` extended function.

**Comment by wsfulton** [comment]
Yeah, basic c++ lifetime bug in your function.
