### ISSUE TITLE
using swig in C# for prebuild dll 

### ISSUE THREAD

**Issue by AbuHelweh** [swig/swig#1980]
Hello,

I'm using swig framework to build C# wrapper on top of prebuild C dll, I need help because I dont have the source code for the dll.

I have created the interface.i and I was able to generate the PINVOKE class but the function is not implemented inside the dll

can you please advice what to do or where to go?

**Comment by wsfulton** [comment]
SWIG requires a matching header file for the dll in order to call code into the dll from C#. You'd have to create a header somehow if you don't have one using whatever information you know about the functions in the dll. That won't be easy if you don't have any information on the dll.

**Comment by AbuHelweh** [comment]
Thanks for sharing the information.

Header files are available.
