### ISSUE TITLE
Tutuorial does not run using python on cygwin 

### ISSUE THREAD

**Issue by bradbell** [swig/swig#1983]
The swig tutorial, see link below, does not work with a recent version of cygwin
http://www.swig.org/tutorial.html

Here is a description of the version of cygwin:
```
$ uname -a
CYGWIN_NT-10.0 DESKTOP-HG8IMEN 3.1.7(0.340/5/3) 2020-08-22 17:48 x86_64 Cygwin
```

Following the tutorial instructions for python I execute the following commands:
```
$  swig -python example.i
$  gcc -c example.c example_wrap.c   -I/usr/include/python3.8
$ ld -shared example.o example_wrap.o -o _example.so
```

I get the following result:
```
ld: example.o:example.c:(.text+0x54): undefined reference to `time'
example.o:example.c:(.text+0x54): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `time'
ld: example.o:example.c:(.text+0x60): undefined reference to `ctime'
example.o:example.c:(.text+0x60): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ctime'
```
... snip ...
```
ld: example_wrap.o:example_wrap.c:(.rdata+0x750): undefined reference to `PyObject_GenericGetAttr'
ld: example_wrap.o:example_wrap.c:(.rdata+0x8f0): undefined reference to `PyObject_GenericGetAttr'
ld: example_wrap.o:example_wrap.c:(.rdata$.refptr.PyObject_GenericGetAttr[.refptr.PyObject_GenericGetAttr]+0x0): undefined reference to `PyObject_GenericGetAttr'
```

**Comment by wsfulton** [comment]
The tutorial clearly states it is shown for Irix. That is not Cygwin! There are many different operating systems and each one has its own quirks. There is a clear link in the tutorial where the community can contribute for different operating systems. 

The linker errors you show above show you havn't linked to the appropriate Python library that comes with your version of Cygwin.

**Comment by bradbell** [comment]
I posted a question about this to swig-user and got no response; see
https://sourceforge.net/p/swig/mailman/message/37243840/

Perhaps I would have tried the the developer list ?
'Feedback and questions concerning this site should be posted to the swig-devel mailing list. '
