### ISSUE TITLE
Finally drop support for $source and $target

### ISSUE THREAD

**Issue by ojwb** [swig/swig#1984]
I noticed these were being set in the PHP backend but were not actually used by any of the PHP typemaps.  Digging a bit I found they're ancient names for typemap parameters supported only for compatibility with user typemaps from before some change long ago - SWIG has been issuing a deprecation warning for uses of them (with a testcase even!) since before "The great merge" in late 2002, and `CHANGES` says they were officially deprecated in late 2001 (so over 19 years and counting).

I think we should drop support for them in 4.1.0 - they make it harder to maintain a SWIG backend or to write a new one, and if anyone has really ignored a deprecation warning about their custom SWIG typemap for over 18 years then they shouldn't be surprised by it stopping working in a new release series.

They don't seem to be entirely consistently supported - e.g. SWIG/D never sets `$source` while SWIG/Go  only sets it in one case.

I'm also dubious they'll actually still work everywhere in languages SWIG has supported for long after this much time given we don't test they actually work anywhere, only that mentioning them in a dummy typemap triggers a deprecation warning.   E.g. on the gsoc2017-php7-classes-via-c-api branch I see:

```
        Replaceall(tm, "$source", &source);
        Replaceall(tm, "$target", ln);
        Replaceall(tm, "$input", source);
```

I'm pretty sure the `&` on the first is wrong...

**Comment by wsfulton** [comment]
Okay by me (for all target languages).

**Comment by ojwb** [comment]
@wsfulton Thanks - I've opened a PR.

What are your thoughts on removing lingering support for other deprecated SWIG 1.1 stuff, such as `%except` and `%name`?  The former seems to now warn and do nothing (and has no test coverage at all), the latter seems to warn but still work (and there's test coverage both that it warns and that it works.)  Neither complicates backend code so there's not such a strong maintenance argument, but both have had better replacements for more than 20 years.

Should we have general policies for how long (in terms of elapsed time and/or release cycles) we keep support for such things around?
