### ISSUE TITLE
java vector of interfaces

### ISSUE THREAD

**Issue by charles-huet-ixxi** [swig/swig#1987]
Hi, 

I am trying to have a simple vector of interfaces wrapped, but I encounter an error (it would seem in the code generation).

Here is a repo with a simple reproducer: https://github.com/charles-huet-ixxi/swig-reproducer/tree/interface_vector

The idea is simple: I have an Interface `interface` that I want to wrap using SWIG's  `%interface` directive. When I use this in a `std::vector`, I end up with the following line in the SWIG-generated java file: `return (cPtr == 0) ? null : ($javainterfacename)new SWIGTYPE_p_p_Interface(cPtr, false);`

The `$javainterfacename` is not resolved correctly to its type, but only in the `doGet` method, all other methods have no issues.

Am I settings things up incorrectly ?

Thanks

**Comment by wsfulton** [comment]
doGet returns a const pointer reference, that is, `Interface *const&`. The typemaps for `%interface` this was not correct and is now fixed.
