### ISSUE TITLE
[Python] Wrapping with -builtin and -noproxy leads to undeclared identifiers (Swig 4.0.2)

### ISSUE THREAD

**Issue by PatTheMav** [swig/swig#1990]
When creating a wrapper with the `-builtin` and `-noproxy` option undefined built-in `SwigPy` objects are created for complex types (e.g. `struct`s) in the generated file. Creating the wrapper without the `-noproxy` option results in no issues.

The error will occur when compiling the wrapped file:
```
example_wrap.c:4609:37: error: use of undeclared identifier 'SwigPyBuiltin__Vector_type'; did you mean 'SwigPyBuiltin_SetMetaType'?
  builtin_pytype = (PyTypeObject *)&SwigPyBuiltin__Vector_type;
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                    SwigPyBuiltin_SetMetaType
example_wrap.c:3058:1: note: 'SwigPyBuiltin_SetMetaType' declared here
SwigPyBuiltin_SetMetaType (PyTypeObject *type, PyTypeObject *metatype)
^
1 error generated.
```

`SWIGTYPE_p_Vector` is created, as well as the wrapped setter and getter methods (e.g. `_wrap_Vector_x_set`), but the `SwigPyBuiltin__[YOUR_STRUCT]_type` is never set. I did observe the same issue with any kind of `struct` in other code.

The offending code in `example_wrap.c` are these lines:
```
  /* type '::Vector' */
  builtin_pytype = (PyTypeObject *)&SwigPyBuiltin__Vector_type;
  builtin_pytype->tp_dict = d = PyDict_New();
```

The documentation states that `builtin` uses "built-in types rather than proxy classes" and `noproxy` doesn't "generate proxy classes", but `builtin` still generates a proxy "wrapper" (as stated in Cmake's documentation to the `UseSwig` module for the `NOPROXY` property: "Prevent the generation of the wrapper layer (swig -noproxy option)").

From the available documentation it is not clear to me if this is truly an issue, the combination of flags is not allowed, or additional manual work in the SWIG module file is required.

# Steps to reproduce

## Example files

*example.i:*
```
%module example

%{
#define SWIG_FILE_WITH_INIT
#include "example.h"
%}

%include "example.h"
```

*example.h:*
```
int fact(int n);

struct Vector {
	double x,y,z;
};
```

*example.c:*
```
#include "example.h"

int fact(int n)
{
    if (n < 0) {
        return 0;
    }

    if (n == 0) {
        return 1;
    } else {
        return n * fact(n-1);
    }
}
```

## Compile steps

* `swig -python -builtin -py3 -noproxy example.i`
* `clang -O2 -fPIC -c example_wrap.c -IPATH_TO_PYTHON_INCLUDE_FOLDER`

**Comment by wsfulton** [comment]
I don't think it makes sense to use `-builtin -noproxy` together as they are imply conflicting requirements. I suppose we could generate an error if an attempt is made to use them together.

**Comment by ojwb** [comment]
```
$ ./preinst-swig -python -builtin -py3 -noproxy example.i
Incompatible options -builtin and -noshadow specified.
```
