### ISSUE TITLE
C wrapper - call a C++ method from C (request for new CPP2C features)

### ISSUE THREAD

**Issue by UnlimitedChild** [swig/swig#2002]
Hi,

I need to generate a C wrapper for each type in C ++, you have support for everything, but not for this type of generation. It would be great if you could adapt such methods to your project.

Here's an example - 
[WrapperCtoCppx64.zip](https://github.com/swig/swig/files/6369295/WrapperCtoCppx64.zip)

**Comment by darkSKULL-labs** [comment]
It isn't trivial at all to do that.

**Comment by wsfulton** [comment]
See #800.
