### ISSUE TITLE
Binding generated by Swig failed to compile

### ISSUE THREAD

**Issue by CretinHo** [swig/swig#2003]
I'm using Swig to generate binding for the FOX toolkit. My interface file is pretty primitive. I have no idea what's going on. I attached both the interface file and the errors output of g++. I'm creating binding for Java.
[build_errors.txt](https://github.com/swig/swig/files/6370045/build_errors.txt)
[errors.zip](https://github.com/swig/swig/files/6370052/errors.zip)
Update: javac failed to compile the generated Java sources, too. It's Java 11.

**Comment by CretinHo** [comment]
Do you consider this is user errors so no one answered? If it's so is there any mailing list I could go asking for help? Thanks.

**Comment by vadz** [comment]
In general, if you want to maximize the possibility of receiving an answer, the best is to try to provide a minimal example rather than a 600KB list of errors. Of course, there are [the mailing lists](http://www.swig.org/mail.html), but I don't know if anybody there would be willing to dive into this without having a [SSCCE](http://sscce.org/).

**Comment by CretinHo** [comment]
I give up.

**Comment by CretinHo** [comment]
> In general, if you want to maximize the possibility of receiving an answer, the best is to try to provide a minimal example rather than a 600KB list of errors. Of course, there are [the mailing lists](http://www.swig.org/mail.html), but I don't know if anybody there would be willing to dive into this without having a [SSCCE](http://sscce.org/).

Look. FOX Toolkit used macros to help declare the object:

https://github.com/CretinHo/fox-1.4-updated/blob/main/include/FX4Splitter.h

FXDECLARE(FX4Splitter)

And FXDECLARE as defined here:

https://github.com/CretinHo/fox-1.4-updated/blob/main/include/FXObject.h

You could clearly see each FXDECLARE has one struct FXMapEntry

This stupid software translate this FXMapEntry struct to FXMapEntry class again and again for each header used FXDECLARE (nearly all of them), it also embedded a piece of FXMetaClass again and again to each translated .java source file. The result is the error above, javac failed to compile because the same classes were already defined being redefined again and again.

It did the same with the C++ wrapper itself. g++ when compile the .cxx file will spit the very same errors as javac.

The way the FOX Toolkit was constructed make it impossible to make binding using the current Swig. I don't know which is the one to blame. This stupid software or FOX Toolkit. FOX Toolkit is a huge mess of hackish macros anyway. It's bad software I will not use.

**Comment by vadz** [comment]
Wow, you really know how to motivate people to look at your bugs.

**Comment by CretinHo** [comment]
> Wow, you really know how to motivate people to look at your bugs.

Do you observed the same thing as me? BTW, I will close this issue again as it's no longer relevant to me anymore.
