### ISSUE TITLE
Callbacks to the target language

### ISSUE THREAD

**Issue by Herve3** [swig/swig#2006]
Hi everybody, 

Using the documentation for [Swig 4.0 ](http://www.swig.org/Doc4.0/SWIGDocumentation.html#SWIGPlus_target_language_callbacks), I am trying to write a callback to the target language: (python to C to python)

This is my code  in example.i:

```
%module(directors="1") example
%feature("director") BinaryOp;

%inline %{
    struct BinaryOp {
        virtual void handle(int a, int b) = 0;
        virtual ~BinaryOp() {}
    };

    static BinaryOp *handler_ptr = NULL;

    int binary_op(int a, int b, void (*op)(int, int)) {
        op(a, b);
    }

    static void handler_helper(int a, int b) {
        printf("handler_helper(): handler_ptr = %x\n", handler_ptr);
        handler_ptr->handle(a, b);
    }

    void binary_op_wrapper(int a, int b, BinaryOp *handler) {
        handler_ptr = handler;
        handler = NULL; // why?
        binary_op(2, 4, &handler_helper); // to be removed, just for first test and this is working
    }

    void *callback(void *param){
        while(1){
            binary_op(2, 4, &handler_helper); // this one is making a segmentation fault, why ???
            sleep(10); 
        }
    }

    void caller_function(){
        pthread_t thread;
        pthread_create( &thread, NULL, callback, NULL);
    }
%}

```
And here is my code in example.py:

```
import example
import time

# PythonBinaryOp class is defined and derived from C++ class BinaryOp
class PythonBinaryOp(example.BinaryOp):
	# Define Python class 'constructor'
	def __init__(self):
		# Call C++ base class constructor
		example.BinaryOp.__init__(self)
	# Override C++ method: virtual int handle(int a, int b) = 0;
	def handle(self, a, b):
		# Return the product
		print("PYTHON: HELLO")

handler = PythonBinaryOp()
# Apr 29th: This 2 lines below were missing in the first post :(
example.binary_op_wrapper(0, 0, handler)
example.caller_function()

while True:
	time.sleep(1)
```
And finally the output of this little program:
```
handler_helper(): handler_ptr = ebf68f40
PYTHON: HELLO
handler_helper(): handler_ptr = ebf68f40
Fatal Python error: Segmentation fault
```

As you can see the first call to binary_op directly inside binary_op_wrapper is working but the call inside the callback function is causing segmentation fault. I do not understand since my handler_ptr seems good.  

Of course this is just an example to reproduce my problem, in fact, my callback function is called in a thread that is receiving ethernet packet. 

Thank you

**Comment by ojwb** [comment]
Your reproducer doesn't give the output shown, or indeed any output - it just sits in its sleep loop.

You don't show the SWIG command line - maybe you didn't pass `-threads` when generated the wrappers?

If it's not that, please include a reproducer that actually works, and also include the SWIG and compiler commands you used to build it.

**Comment by Herve3** [comment]
Thank you very much for the reply. 

Sorry, I forgot to copy/paste 2 lines when I cherry picked to make the reproducer. Just before the while True in example.py:
	iec61850.binary_op_wrapper(0, 0, handler)
	iec61850.caller_function()
	
You are right there was no -threads in the project.  I just added it , but no chance, still the same problem. 

I will extract an independant producer and give you feed back.

Thanks.

**Comment by Herve3** [comment]
Problem solve, the example below work. Had to compile with:

```
/bin/swig -python -c++ example.i
gcc -O2 -fPIC -I/usr/include/python3.6m/ -c example_wrap.cxx
gcc -shared -lm -lstdc++ -o _example.so example_wrap.o
```

Thank you
