### ISSUE TITLE
Actually remove dead target languages

### ISSUE THREAD

**Issue by ojwb** [swig/swig#2009]
(See #1437 and #1447 for background)

The commit messages for these changes all said "Target language be fully deleted in SWIG 4.1 unless a new maintainer brings it up to an acceptable status (experimental or supported)".  We don't seem to have an open issue to track this, so opening one and putting it on the 4.1 milestone so this doesn't get forgotten.

The list seems to be:

allegrocl, ~~cffi~~, chicken, clisp, modula3, pike, s-exp, uffi

Nobody seems to have stepped up to maintain any of them.

**Comment by ojwb** [comment]
I just noticed #1966 to revive CFFI support.  It looks like it's currently missing CI coverage, but it's not helpful to remove CFFI at this point.

**Comment by ojwb** [comment]
There don't seem to be open issues or PRs for any of the other entries on my list.

**Comment by egao1980** [comment]
Please don't kill CFFI :) - I'm still working on it

**Comment by egao1980** [comment]
Getting CI build and C tests in CFFI - https://github.com/egao1980/swig/tree/test-cffi and will have a PR soon.

**Comment by ojwb** [comment]
@egao1980 Don't worry, I'm only proposing to remove the ones nobody's trying to revitalise - I'd just not seen your PR when I originally opened this, but it's great to see you're working on it.

**Comment by wsfulton** [comment]
@ojwb, please remove all the dead languages. Each of the languages should be removed by separate commits. That way each one can be easily revived if required (including CFFI) by reverting one commit.

**Comment by ojwb** [comment]
I'm not comfortable with removing CFFI right now, especially given I essentially said I wouldn't just 2 days ago.  Sure the removal can be reverted pretty easily, but it's discouraging to be actively working on something and have it deleted from under you, and it also makes the history unnecessarily harder to follow going forwards.

I'll work through the others, and we can see how things look when 4.1 is nearer being ready for release.

**Comment by ojwb** [comment]
Checklist of files/directories to remove and places to update to remove language "foo":

* `Source/modules/foo.cxx`
* `Lib/foo/`
* `Doc/Manual/Foo.html`
* `Examples/foo/`
* `Examples/test-suite/foo/`
* edit `Examples/Makefile.in`
* `git grep SWIGFOO`
* update `CHANGES.current`

General check for other references with `git ls-files|grep foo` and `git grep -i foo`, but:

* `Source/Modules/swigmain.cxx`: we should leave the command line option entry so that `swig -foo` says `Target language option -foo is no longer supported.`
* `Source/Include/swigwarn.h`: we should leave a note about any previously used `WARN_FOO_XXX` constant values so they don't get reused (at least not so soon it might cause confusion)

**Comment by ojwb** [comment]
I've pushed a fixup commit for the chicken removal to the branch, as I'd made a mistake there.

Once the CI passes for the branch I'll `git rebase -i --autosquash` so it's one commit per removed language.

**Comment by ojwb** [comment]
I'm going to close this.

There's a very plausible looking attempt in progress to revive CFFI in #1966.  This is still lacking CI, but it seems we've stopped trying to use travis-ci and now have CI via github actions, but only for Python and Tcl.  It would be unreasonable to eject CFFI only because it lacks CI given we don't have CI for most languages right now...
