### ISSUE TITLE
At least some SWIG errors should be PHP exceptions 

### ISSUE THREAD

**Issue by ojwb** [swig/swig#2014]
If the user passes parameters to a wrapped function which don't match those expected by any overridden form, then currently a PHP fatal error is issued, which can't be caught. This makes it harder to build a robust application, and it's hard to debug what the problem really is.

It's also inconsistent with native PHP handling - here we get an exception such as `TypeError` or `ArgumentCountError`:

```
$ php8.0 -r 'function f(int $a) { } f("a");'
PHP Fatal error:  Uncaught TypeError: f(): Argument #1 ($a) must be of type int, string given, called in Command line code on line 1 and defined in Command line code:1
Stack trace:
#0 Command line code(1): f()
#1 {main}
  thrown in Command line code on line 1
$ php8.0 -r 'function f(int $a) { } f();'
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function f(), 0 passed in Command line code on line 1 and exactly 1 expected in Command line code:1
Stack trace:
#0 Command line code(1): f()
#1 {main}
  thrown in Command line code on line 1
```

PHP has supported exceptions since PHP5 and we now support PHP >= 7, so we no longer need to worry about supporting versions without exceptions.

Reviewing current git master, I think all direct calls to `SWIG_PHP_Error` should definitely raise exceptions.

Perhaps any use of `SWIG_Error` in PHP bindings should be an exception?  It looks like this is the approach taken by a number of the other target languages.

This looks fairly straight-forward, so marking for 4.1 at least for now.  There don't seem to be significant compatibility concerns since currently the error is fatal and can't be intercepted in PHP, and an uncaught exception looks pretty similar from outside, but doing this at the same time as other major changes to the PHP support seems better.

(Based on https://sourceforge.net/p/swig/bugs/883/ in the old SF tracker.)

**Comment by wsfulton** [comment]
Seems eminently sensible to me.
