### ISSUE TITLE
[QUESTION] passing array of int pointer

### ISSUE THREAD

**Issue by tarikhagustia** [swig/swig#2018]
Hi, i'm new in c++ but i have a question, if my function in c++ has receipt a int* (array of integer) then on golang wrapper what should i enter the parameters? i have trying to passing int on golang but not woriking

sory for my bad english thanks

**Comment by ojwb** [comment]
Seems you need to pass a Go `*int`.

The only tricky thing is that Go doesn't seem to allow turning an array of `int` into a `*int` without mucking around, but even that isn't difficult once you find the trick, e.g. with `example.i`:

```
%module example
%inline %{
int sum(int v[], int n) {
  int i;
  int r = 0;
  for (i = 0; i < n; ++i) {
    r += v[i];
  }
  return r;
}
%}
```

and `runme.go`:

```
package main

import (
	"fmt"
	"unsafe"

	"swigtests/example"
)

func main() {
	var a [3]int
	a[0] = 1
	a[1] = 2
	a[2] = 3

	fmt.Println("sum() returns", example.Sum((*int)(unsafe.Pointer(&a)), len(a)))
}
```

Output is:

```
sum() returns 3
```

Someone who actually knows Go might be able to give a better answer, but it's been nearly 3 years and nobody with Go knowledge has answered, so I think the above adequately addresses the question hence closing.

**Comment by ojwb** [comment]
Hmm, actually the sum is wrong there - should be `6` not `3`.

If in the C code I print out the index and element I get:

```
0 1
1 0
2 2
```

Changing the array to be `var a [3]int32` instead of `var a [3]int` fixes this so it seems at least on my platform that Go `int` is 64-bit - I'll edit my answer above to fix this.
