### ISSUE TITLE
SWIG garbles Doxygen parameter comments after default values

### ISSUE THREAD

**Issue by bobapl** [swig/swig#2023]
Consider the following legal C++/Doxygen for a class constructor to be wrapped for Python:

    /// Constructor for input from an existing SIO file
    explicit SIOBeam(
        std::string filename,   ///< Name of input SIO file. Filename extension .sio recommended.
        int elevationOrder=1, ///< Interpolation order (0-3) in elevation (default 1)
        int bearingOrder=1,   ///< Interpolation order (0-3) in bearing (default 1)
        int frequencyOrder=1, ///< Interpolation order (0-3) in frequency (default 1)
        Vector offset=Vector(),   ///< Position of beam phase center (vehicle coordinates, meters)
        double delay=0.0          ///< Beam delay (seconds)
    );

The corresponding Python docstring from SWIG is:

    def __init__(self, *args, **kwargs):
        r"""
         Constructor for input from an existing SIO file
        :type offset: :py:class:`Vector`, optional
        :param offset: Position of beam phase center (vehicle coordinates, meters) Interpolation order (0-3) in frequency (default 1) Interpolation order (0-3) in bearing (default 1) Interpolation order (0-3) in elevation (default 1) Name of input SIO file. Filename extension .sio recommended.
        :type delay: float, optional
        :param delay: Beam delay (seconds)
        """

The next-to-last :param entry gets the concatenated docstrings for all previous arguments, in reverse order. The generated Python wrapper works as expected, but the Sphinx autoclass documentation is garbled.

I can fix it by moving all parameter comments up into @param entries in the function's Doxygen block, but my package has HUNDREDS of such functions to be wrapped. Default values avoid overloaded functions, enabling callers to use keyword arguments. That's a bug. Please fix.

**Comment by ojwb** [comment]
Here's a complete reproducer:

```
/// Blah blah.
struct SIOBeam {
    /// Constructor for input from an existing SIO file
    explicit SIOBeam(
        std::string filename,   ///< Name of input SIO file. Filename extension .sio recommended.
        int elevationOrder=1, ///< Interpolation order (0-3) in elevation (default 1)
        int bearingOrder=1,   ///< Interpolation order (0-3) in bearing (default 1)
        int frequencyOrder=1, ///< Interpolation order (0-3) in frequency (default 1)
        Vector offset=Vector(),   ///< Position of beam phase center (vehicle coordinates, meters)
        double delay=0.0          ///< Beam delay (seconds)
    );
};
```

Process with:

```
swig -python -doxygen -c++ -module x test.i
```

Still present in git master.

**Comment by bobapl** [comment]
Another fix is to move each parameter comment to before the parameter's declaration:

    /// Full public constructor, for input from an existing SIO file
    explicit SIOBeam(
        /// Name of input SIO file. Filename extension .sio recommended.
        std::string filename,
        /// Interpolation order (0-3) in elevation (default 1)
        int elevationOrder=1,
        /// Interpolation order (0-3) in bearing (default 1)
        int bearingOrder=1,
        /// Interpolation order (0-3) in frequency (default 1)
        int frequencyOrder=1,
        /// Position of beam phase center (vehicle coordinates, meters)
        Vector offset=Vector(),
        /// Beam delay (seconds)
        double delay=0.0
    );

So the bug arises only when default values are combined with Doxygen trailing comments (///<).

**Comment by ojwb** [comment]
Also affects Java so it's likely in generic doxygen handling code:

```
  /**
   *  Constructor for input from an existing SIO file<br>
   * @param offset Position of beam phase center (vehicle coordinates, meters) Interpolation order (0-3) in frequency (default 1) Interpolation order (0-3) in bearing (default 1) Interpolation order (0-3) in elevation (default 1) Name of input SIO file. Filename extension .sio recommended.<br>
   * @param delay Beam delay (seconds)
   */
  public SIOBeam(SWIGTYPE_p_std__string filename, int elevationOrder, int bearingOrder, int frequencyOrder, SWIGTYPE_p_Vector offset, double delay) {
    this(xJNI.new_SIOBeam__SWIG_0(SWIGTYPE_p_std__string.getCPtr(filename), elevationOrder, bearingOrder, frequencyOrder, SWIGTYPE_p_Vector.getCPtr(offset), delay), true);
  }

  /**
   *  Constructor for input from an existing SIO file<br>
   * @param offset Position of beam phase center (vehicle coordinates, meters) Interpolation order (0-3) in frequency (default 1) Interpolation order (0-3) in bearing (default 1) Interpolation order (0-3) in elevation (default 1) Name of input SIO file. Filename extension .sio recommended.<br>
   * 
   */
  public SIOBeam(SWIGTYPE_p_std__string filename, int elevationOrder, int bearingOrder, int frequencyOrder, SWIGTYPE_p_Vector offset) {
    this(xJNI.new_SIOBeam__SWIG_1(SWIGTYPE_p_std__string.getCPtr(filename), elevationOrder, bearingOrder, frequencyOrder, SWIGTYPE_p_Vector.getCPtr(offset)), true);
  }
```

**Comment by ojwb** [comment]
The problem seems to be failure to update `currentNode` and `previousNode` when handling parameters with `DOXYGENPOSTSTRING` in the parser.  I'll try to fix.

**Comment by wsfulton** [comment]
The `currentNode` and `previousNode` for handling Doxygen comments is only used for function parameters. I'm not sure if this is merely buggy or fundamentally flawed as the parser handles parameters last to first rather than first to last. Anyway, enum item lists are similar in structure to parameter lists and the enum list Doxygen comment handling seems to work well without using `currentNode` and `previousNode` in `enumlist`. 
https://github.com/swig/swig/blob/f7b41273106056e966730a68b5be5f52371d8986/Source/CParse/parser.y#L6473-L6522.

Perhaps parameters should be parsed in the same sort of way requiring changes here:
https://github.com/swig/swig/blob/f7b41273106056e966730a68b5be5f52371d8986/Source/CParse/parser.y#L5170-L5277

Just my current thoughts, not sure when I'll get back to trying to make this change.

**Comment by ojwb** [comment]
I did start to look at this back in March, but wondered if the whole idea of trying to include doxygen comments in the parser grammar was not the best approach.

It has a major weakness that a valid C/C++ comment can cause a syntax error, especially unhelpful given SWIG's syntax error reporting is rather non-specific as to what the problem actually is.  The only thing that really saves us from this is that doxygen support is off by default.  The current approach also complicates the parser grammar, and that tends to make it harder to implement missing C++ features.

I started to look at dealing with this in the scanner instead, with some sort of simple API to communicate when there's a "documentable" node (and when there isn't).  Then a doxygen comment that we can't attach to anything can very easily just be warned about and skipped.  I kind of stalled on working on this, I think mostly because it seemed a rather significant change when we were trying to get 4.1.0 released.

@wsfulton What are your thoughts on this approach?  I can try to take my (currently most a sketch) branch to a working prototype if it seems worth exploring.

**Comment by wsfulton** [comment]
It does not matter whether or not the parameters are garbled, the generated comments were garbled.

Fixed. Output is now as expected. For example, the first two constructor overloads in the Java wrappers is now:
```java
  /**
   *  Constructor for input from an existing SIO file<br>
   * @param filename Name of input SIO file. Filename extension .sio recommended.<br>
   * @param elevationOrder Interpolation order (0-3) in elevation (default 1)<br>
   * @param bearingOrder Interpolation order (0-3) in bearing (default 1)<br>
   * @param frequencyOrder Interpolation order (0-3) in frequency (default 1)<br>
   * @param offset Position of beam phase center (vehicle coordinates, meters)<br>
   * @param delay Beam delay (seconds)
   */
  public SIOBeam(String filename, int elevationOrder, int bearingOrder, int frequencyOrder, Vector offset, double delay) {
    this(exampleJNI.new_SIOBeam__SWIG_0(filename, elevationOrder, bearingOrder, frequencyOrder, Vector.getCPtr(offset), offset, delay), true);
  }

  /**
   *  Constructor for input from an existing SIO file<br>
   * @param filename Name of input SIO file. Filename extension .sio recommended.<br>
   * @param elevationOrder Interpolation order (0-3) in elevation (default 1)<br>
   * @param bearingOrder Interpolation order (0-3) in bearing (default 1)<br>
   * @param frequencyOrder Interpolation order (0-3) in frequency (default 1)<br>
   * @param offset Position of beam phase center (vehicle coordinates, meters)<br>
   * 
   */
  public SIOBeam(String filename, int elevationOrder, int bearingOrder, int frequencyOrder, Vector offset) {
    this(exampleJNI.new_SIOBeam__SWIG_1(filename, elevationOrder, bearingOrder, frequencyOrder, Vector.getCPtr(offset), offset), true);
  }
```
and Python:
```python
    def __init__(self, *args):
        r"""
         Constructor for input from an existing SIO file
        :type filename: string
        :param filename: Name of input SIO file. Filename extension .sio recommended.
        :type elevationOrder: int, optional
        :param elevationOrder: Interpolation order (0-3) in elevation (default 1)
        :type bearingOrder: int, optional
        :param bearingOrder: Interpolation order (0-3) in bearing (default 1)
        :type frequencyOrder: int, optional
        :param frequencyOrder: Interpolation order (0-3) in frequency (default 1)
        :type offset: :py:class:`Vector`, optional
        :param offset: Position of beam phase center (vehicle coordinates, meters)
        :type delay: float, optional
        :param delay: Beam delay (seconds)
        """
        _example.SIOBeam_swiginit(self, _example.new_SIOBeam(*args))
```

@ojwb, I implemented parsing the parameter comments using the same approach as parsing  enum items. Seems to work well. The approach that you suggest may be much better in the longer term, so perhaps explore to see how you get on? I'm not really sure whether it will lead to a good solution, but perhaps my gut instinct is this will be tricky as the lexer will end up doing what the parser should be doing (parsing the tokens) and the lexer won't know what nodes to attach comments to easily without parsing knowledge. If the parser is left to call the new api to reset when a comment should be discarded, I think it will mean nearly every parser rule having to do some sort of comment handling/reset and I can't see how this will help with post doxygen comments.
