### ISSUE TITLE
Can %extend be used outside class like %rename?

### ISSUE THREAD

**Issue by darkSKULL-labs** [swig/swig#2026]
I don't want to modify the class files at all, which is why I hoped it can work the way %rename works.

**Comment by wsfulton** [comment]
Yes, see the docs http://swig.org/Doc4.0/SWIGPlus.html#SWIGPlus_class_extension.

**Comment by darkSKULL-labs** [comment]
Ok thank you, I was looking at a different doc that didn't have that part, there are alot of docs floating around google for swig. Thanks.
