### ISSUE TITLE
Typo in the documentation of SWIG 4.0

### ISSUE THREAD

**Issue by lluisalemanypuig** [swig/swig#2043]
Hello,

I found a typo in SWIG 4.0's documentation in [section 6.18.6](http://swig.org/Doc4.0/SWIGDocumentation.html#SWIGPlus_template_member). There is a box with the following code
```
// Instantiate a few versions
%template(pairii) pair<int, int>;
%template(pairdd) pair<double, double>;

// Create a default constructor only 
%extend pair<int, int> {
  %template(paird) pair<int, int>;         // Default constructor
};

// Create default and conversion constructors 
%extend pair<double, double> {
  %template(paird) pair<double, dobule>;   // Default constructor
  %template(pairc) pair<int, int>;         // Conversion constructor
};
```

The line
```
%template(paird) pair<double, dobule>;   // Default constructor
```
contains a typo inside the `pair` template, in the second type parameter: `doBule` (capital letter used to highlight the typo).

**Comment by ojwb** [comment]
Thanks.  I fixed another instance lower down too.
