### ISSUE TITLE
const enum class reference fails to compile

### ISSUE THREAD

**Issue by romintomasetti** [swig/swig#2047]
# What's the problem ?

If, in a C++ code, there is something like
```c++
class MyClass
{
    public:
        enum class PRINT_SETUP
        {
            TO_CONSOLE,
            TO_CSV
        };
        void my_func(const PRINT_SETUP& e = PRINT_SETUP::TO_CONSOLE);
};
```
SWIG will generate invalid C++ code as follows:
```c++
test_wrap.cxx: In function ‘PyObject* _wrap_MyClass_my_func(PyObject*, PyObject*, PyObject*)’:
test_wrap.cxx:2965:40: error: expected primary-expression before ‘enum’
 2965 |   MyClass::PRINT_SETUP arg2_defvalue = enum MyClass::PRINT_SETUP::TO_CONSOLE ;
      |                                        ^~~~
```

# Workaround

If we just forget about the fact that using `const &` for a `enum class` is debatable, SWIG is not able to parse the statement correctly.

The workaround is simply to remove the reference...

Here is the code (`test.hpp`,`test.cpp`,`test.i`,`test.sh` (to compile)):
[test.zip](https://github.com/swig/swig/files/6782627/test.zip)

**Comment by ojwb** [comment]
I think https://sourceforge.net/p/swig/bugs/923/ was an earlier report of the same issue, but in the old SF tracker and this report is more complete so I'll close that as a duplicate.

Here's a complete reproducer based on that earlier report:

```
%module test
%inline %{
class VR
{
public:
typedef enum {
Foo
} VRType;
static bool IsValid(const char *vr1, const VRType &vr2);
};
%}
```

```
$ swig -c++ -python test.i
$ g++ -Wall -W `python3-config --cflags` test_wrap.cxx -shared -o demo.so
test_wrap.cxx: In function ‘PyObject* _wrap_VR_IsValid(PyObject*, PyObject*)’:
test_wrap.cxx:3413:59: error: using typedef-name ‘VR::VRType’ after ‘enum’
 3413 |   result = (bool)VR::IsValid((char const *)arg1,(enum VR::VRType const &)*arg2);
      |                                                           ^~~~~~
test_wrap.cxx:3090:3: note: ‘VR::VRType’ has a previous declaration here
 3090 | } VRType;
      |   ^~~~~~
test_wrap.cxx:3413:50: error: expected primary-expression before ‘enum’
 3413 |   result = (bool)VR::IsValid((char const *)arg1,(enum VR::VRType const &)*arg2);
      |                                                  ^~~~
test_wrap.cxx:3413:50: error: expected ‘)’ before ‘enum’
 3413 |   result = (bool)VR::IsValid((char const *)arg1,(enum VR::VRType const &)*arg2);
      |                                                 ~^~~~
      |                                                  )
```

**Comment by ojwb** [comment]
This isn't specific to Python - the reproducer I gave above also generates the same problematic code with `-php` for example.

`enum class` is a C++11 feature, so tagging accordingly.

**Comment by ojwb** [comment]
The testcase in `test.zip` didn't seem to reproduce for me - it seems to need `%feature("compactdefaultargs") MyClass::my_func;` adding to get the problematic code generated.  I don't think the default has changed since 2021.

Anyway, here's an all-in-one version of the testcase which reproduces with current git master:

```
%module test

%feature("compactdefaultargs") MyClass::my_func;

%inline %{
 
class MyClass
{
    public:
        enum class PRINT_SETUP
        {
            TO_CONSOLE,
            TO_CSV
        };
        void my_func(const PRINT_SETUP& e = PRINT_SETUP::TO_CONSOLE);
};

#include <iostream>
void MyClass::my_func(const MyClass::PRINT_SETUP& e)
{
    std::cout << "Hello ! Chosen value : " << (e == PRINT_SETUP::TO_CSV ? "CSV" : "CONSOLE") << std::endl;
}
%}
```

**Comment by ojwb** [comment]
The example in https://sourceforge.net/p/swig/bugs/923/ is actually a separate issue with a typedef to an anonymous enum rather than a C++11 class enum.
