### ISSUE TITLE
Doxygen image command translation in javadoc

### ISSUE THREAD

**Issue by Hyrae** [swig/swig#2048]
For the Doxygen image command, the translation in javadoc produces a wrong html img tag.
The following doxygen docstring
```
/**
  * \image html myimage.png
  */
```
Is translated in the .java file to:
```
/**
  *<img src=myimage.png/><br>
  */
```
Which is interpreted by Javadoc to:
```
<img src="myimage.png/">
```
This html tag is well parsed by Firefox but not with Chrome because of the trailing slash character. 
It seems it comes from here in the code:
https://github.com/swig/swig/blob/a2fc5ecaff561b4e3c6c8edc84d46a20eebae731/Source/Doxygen/javadoc.cxx#L466-L472

Where I would replace the line 472 with:
```
 translatedComment += ">"; 
```

**Comment by vadz** [comment]
This looks correct, thanks. But we probably should still also quote the file name, shouldn't we?

**Comment by Hyrae** [comment]
Yes but we should take care of the case where quotes are already present in the doxygen docstring (for file names with spaces for instance). If the first and last characters of the file name are quotes, then no need to add quotes. 
The same goes for the image title I guess.

**Comment by wsfulton** [comment]
This issue is currently tagged with the swig-4.1 milestone. Can an updated patch please be provided for this in the next couple of weeks or I'll have to drop the tag. Thanks.

**Comment by ojwb** [comment]
Nobody's provided an updated patch, but I can have a quick go.

I'm assuming dropping the `/` is OK (if javadoc requires XHTML the closing `/` should be there; I couldn't find a clear statement about this but I found plenty of examples without the closing `/`).

**Comment by vadz** [comment]
Sorry, I should have done this but completely forgot about it. @ojwb please let me know if you'd like me to take it.

**Comment by wsfulton** [comment]
oh, I was just doing this too. I've got it ready to commit and also added in support for the \image command using quotes in the filename.

**Comment by wsfulton** [comment]
Sorry about that @ojwb if you'd started this. I looked at this ticket and started working on it shortly before you did the self assign.

HTML supports a closing / and I certainly put use it when I write HTML, even though it isn't strictly needed for some versions of HTML. I think it is XHTML that does require it. Anyway, I believe the correct approach is to add in the missing quotes as @vadz spotted.

**Comment by ojwb** [comment]
No problem, hadn't actually made a start beyond investigating to decide what to do.

A closing `/` is allowed here by the current HTML spec, but it says about it:

> On [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), it does not mark the start tag as self-closing but instead is unnecessary and has no effect of any kind. For such void elements, it should be used only with caution — especially since, if directly preceded by an [unquoted attribute value](https://html.spec.whatwg.org/multipage/syntax.html#unquoted), it becomes part of the attribute value rather than being discarded by the parser.

(That last part was exactly the issue we had here!)

So there's no good reason to include it either (unless you're writing XHTML, which seems to be out of favour these days).
