### ISSUE TITLE
How to use swig to wrap C++ for golang.

### ISSUE THREAD

**Issue by andyzheung** [swig/swig#2055]
I have class:

![image](https://user-images.githubusercontent.com/22912347/126458144-3f6a9b7a-60da-41af-9829-4aaa401596b0.png)

then I define example.i :
the first try:
%module example
%include "std_shared_ptr.i"

%shared_ptr(std::recursive_mutex)

// the second try like this:
%module example
%include "std_shared_ptr.i"

![image](https://user-images.githubusercontent.com/22912347/126458330-89c8c010-6bf2-4bcb-a3d0-a6719e67e1ad.png)

but both of the above is not ok. How the go use shared_ptr?

**Comment by tamama** [comment]
Hey, I observe that no one seems to own Swig-Golang development. 

From my 2 cents, 
1) private methods are not exposed by Swig-Golang; 
2) you need to be extremely careful with automatic memory management - I am sure that you will run into memory leak issues.
3) I would recommend that you only expose "interface" - i.e. use Swig-Go as some form of IPC. (I advise strongly not to expose meta objects like mutex.)

**Comment by ojwb** [comment]
SWIG indeed only wraps public class members, as is documented in the manual: http://swig.org/Doc4.0/SWIGPlus.html#SWIGPlus_nn15

Not actually a bug, so closing.

**Comment by tamama** [comment]
@ojwb 

Are you the owner of Swig-Go?

**Comment by ojwb** [comment]
No, but SWIG doesn't wrap private class members in any language so I don't need magic Go powers to confirm that point.

The nominal SWIG/Go maintainer is still sometimes active (right now he made the most recent commit to git master, though last commit before that was 2019) but I don't think he has a lot of time spare for SWIG.

**Comment by wsfulton** [comment]
Track shared_ptr support for Go in issue #2030.
