### ISSUE TITLE
Segfault using swig with Python on MacOS BigSur

### ISSUE THREAD

**Issue by CiaranWelsh** [swig/swig#2060]
I am consistently getting a segfault when creating a python module with swig on macos (BigSur 11.5.1). This happens whether I build the module by hand or whether I use CMake (using [procedures](https://github.com/sys-bio/roadrunner/blob/cvodes-2/test/CMakeLists.txt#L101) that work without issue on windows and linux).

I decided to peal everything back and work from the very simple examples in the docs and I'm still getting the same problem.

```
// swig_example.h

int fact(int n);
```

```
// swig_example.c
#include "swig_example.h"

int fact(int n) {
    if (n < 0){ /* This should probably return an error, but this is simpler */
        return 0;
    }
    if (n == 0) {
        return 1;
    }
    else {
        /* testing for overflow would be a good idea here */
        return n * fact(n-1);
    }
}

```

```
// swig_example.i
/* File: example.i */
%module swig_example

%{
#define SWIG_FILE_WITH_INIT
#include "swig_example.h"
%}

int fact(int n);
```

Then 
```
gcc -O2 -fPIC -c swig_example.c swig_example.h
gcc -O2 -fPIC -c swig_example_wrap.c -I/Users/Ciaranwelsh/miniconda3/envs/py39/include/python3.9 
gcc -shared swig_example.o swig_example_wrap.o -o _swig_example.so -L/Users/Ciaranwelsh/miniconda3/envs/py39/lib -lpython3.9 
```
so far so good. But then when importing the module
```
In [1]: import _swig_example
Segmentation fault: 11
```

I'm pretty new to swig and MacOs so I'm hoping this is a noob question and I'm missing something obvious, but I'd appreciate any help you might have in resolving this. 

Thanks

Ciaran

**Comment by jschueller** [comment]
are you importing with the same miniconda interpreter ?

**Comment by CiaranWelsh** [comment]
I'm not 100% sure because I've misplaced these test files now but this is definitely the kind of thing I would have tried before posting an issue. 

In cmake, I resolved the problem that I was debugging by enabling dynamic loading. Aka: 

```
        set_target_properties(${SWIG_TARGET_NAME}
                PROPERTIES
                LINK_FLAGS "-undefined dynamic_lookup"
                INSTALL_RPATH "@loader_path/../../lib;@loader_path/"
                INSTALL_NAME_DIR "@rpath"
                )
```

**Comment by ojwb** [comment]
You shouldn't `import _swig_example` directly - that's the C/C++ glue code.  You should `import swig_example` (which is the generated `.py` wrapper script) which will then import the other module.  This shouldn't segfault though.

From the information give, it seems the explanation probably is the suggested mismatch between the Python interpreter you built for and the one you're running it with.  If this was an actual breakage on a newer macos version we'd have see more reports or other people commenting here by now.

@CiaranWelsh Please can you try to reproduce this from a clean start making sure that you are using the same interpreter for building and running?  If you've misplaced the local test files, you can use the copies you attached here.

Also maybe worth noting that until SWIG 4.1.0 is released you'll need to use git master for full Python 3.9 support:

```
2020-08-16: wsfulton
            [Python] Add missing initializer for member ‘_heaptypeobject::ht_module’ when using
            -builtin to complete Python 3.9 support.

2020-08-16: wsfulton
            [Python] Remove PyEval_InitThreads() call for Python 3.7 and later as Python calls
            it automatically now. This removes a deprecation warning when using Python 3.9.
```

AIUI, that only matters if you use `-builtin` or mind the deprecation warning though.

**Comment by ojwb** [comment]
No follow-up from submitter in 7 months, and we've no other reports of similar SWIG/Python issues on macos so closing on the assumption it was mismatched Python versions.

@CiaranWelsh If you (or anyone else) can reproduce this without mismatched Python versions, please comment and we can reopen.

**Comment by martinfiers** [comment]
Long shot, but could you try with adding the "-flat_namespace" flag to the linker? This seemed to work for me, not sure why (got this from another github issue which I can't find back directly).
