### ISSUE TITLE
Not able to run Javascript example in windows

### ISSUE THREAD

**Issue by cgowda** [swig/swig#2066]
Hello,

      I have created below files with content
binding.gyp
{
  "targets": [
    {
      "target_name": "Targett",
      "sources": [ "Targett.cxx" ],   
    }
  ]
}

commands tried:

swig -javascript -node -c++ Targett.i
node-gyp configure
node-gyp build

Below error is shown during build stage

 error C2664: 'v8::Local<v8::Value> v8::Exception::Error(v8::Local<v8::String>)': cannot convert argument 1 from 'v8::MaybeLocal<v8::String>' to 'v8::Local<v8::String>'

Thanks
chandre

**Comment by vadz** [comment]
This is almost surely not Windows-specific but just due to using a version of Node that SWIG is incompatible with. Which version of SWIG and Node do you use? You need to get the current Git master, which includes changes of #1746, to use any reasonably recent Node version.

**Comment by cgowda** [comment]
Iam currently using Node : v14.17.4, Swig :  3.0.12.  Please tell me node version which Swig 3.0.12 is compatible with ?

**Comment by vadz** [comment]
Probably Node v8 or even earlier.  Definitely not v14.

**Comment by cgowda** [comment]
Thanks, I will check this. Any idea when are we fixing this issue  and releasing?

**Comment by vadz** [comment]
Sorry, I don't know anything about the future release plans.
