### ISSUE TITLE
`configure.ac` non execute bit

### ISSUE THREAD

**Issue by ipatch** [swig/swig#2069]
working with this repo, when one downloads the repo in a packaged form from the the releases section of the repo. the `configure.ac` script in the `.tar.gz` does not have `+x` execute bit set for the file.

this becomes a problem when package managers such as macos homebrew attempt to automate the install process and the package manager attempts to run `./configure` and the script will not run.

i'm not sure if this is the intended behavior for this repo.

however if one downloads the `.tar.gz` from the sourceforge repo. running `./configure` from a package manager allows the _cofigure_ step of the build process to begin.

```
https://downloads.sourceforge.net/project/swig/swig/swig-4.0.2/swig-4.0.2.tar.gz
```

**Comment by vadz** [comment]
`configure.ac` shouldn't be executable, it's an input file for autoconf and only `configure` generated by autoconf needs to be executable. As for the auto-generated "releases" from GitHub, SWIG project has no control over them and you're not supposed to use them.
