### ISSUE TITLE
doxygen output for Python fails if trailing "

### ISSUE THREAD

**Issue by KrisThielemans** [swig/swig#2070]
For a C++ class member like this
```C++
        /// Dot between "this" and "other"
        virtual void dot(const DataContainer& a_x, void* ptr) const;
```
the generated docstring is
```python
    def dot(self, a_x, ptr):
        r""" Dot between "this" and "other""""
```
resulting in a Python syntax error. It could be resolved by adding a trailing space, i.e.
```python
    def dot(self, a_x, ptr):
        r""" Dot between "this" and "other" """
```

**Comment by ojwb** [comment]
4.0.2 fixed this by switching to triple single quote delimiters for this situation, which seems cleaner.
