### ISSUE TITLE
swig/python detected a memory leak, no destructor found

### ISSUE THREAD

**Issue by wolfviking0** [swig/swig#2072]
Hi, 

I was recompiling my c++ code with the latest version of swig, and now my python code give some warning message :
```
swig/python detected a memory leak of type 'ThreadCallback *', no destructor found.
swig/python detected a memory leak of type 'Callback *', no destructor found.
swig/python detected a memory leak of type 'Timer *', no destructor found.
```

I am surprise because my c++ code implement a destructor for all those classes.
Any idea what I am missing ?

**Comment by vadz** [comment]
This would need to be reproduced in a very simple example or, ideally, SWIG test suite, to have any chance of something happening.

Please reopen if you can provide a [SSCCE](http://sscce.org/).

**Comment by wolfviking0** [comment]
Its not possible for me to extract just a simple example unfortunately, do you think you can give me some direction on what I am doing wrong maybe.

I know the generated python code check for destroy, but can you give me maybe more details so I can go more deeper ?

Thanks
```
    swig_type_info *ty = sobj->ty;
    SwigPyClientData *data = ty ? (SwigPyClientData *) ty->clientdata : 0;
    PyObject *destroy = data ? data->destroy : 0;
 ```

**Comment by vadz** [comment]
Sorry, it's really impossible to say what you're doing wrong without knowing what you're doing.

**Comment by wsfulton** [comment]
You are probably not providing these class definitions to SWIG before the class are parsed while wrapping usage of the classes. Check the ordering of your %include files.

**Comment by wolfviking0** [comment]
@wsfulton  thanks for you response, the ordering seems to be ok but I will do a second check on it, but I can give more details on the trouble

This bock will not trigger any issue
```
class MyClass:
    def __init__(self) -> None:
        elt = core.MySwigElt()    
        elt.dump()
        
if __name__ == '__main__':
    test = MyClass()
```


This bock will print the warning
swig/python detected a memory leak of type 'MySwigElt *', no destructor found.
```
class MyClass:
    def __init__(self) -> None:
        self.elt = core.MySwigElt()    
        self.elt.dump()
        
if __name__ == '__main__':
    test = MyClass()
```

**Comment by wolfviking0** [comment]
To complete my previous message:

```
class MyClassNoLeak:
 """Test print no leak message."""
     def __init__(self) -> None:
         elt = core.MySwigElt()
         elt.dump()
 class MyClassLeak:
 """Test print leak message."""
     def __init__(self) -> None:
        self.elt = core.MySwigElt()
        self.elt.dump()
       
 myclassnoleak = MyClassNoLeak()
 myclassleak = MyClassLeak()
 # Explicitely call del no the class remove the warning
 del myclassleak
```
