### ISSUE TITLE
Swig converting python string list to a char ** example fails

### ISSUE THREAD

**Issue by guillaumeguy** [swig/swig#2073]
Hi folks:

I am cross-listing my SO question. In a nutshell, I am following the tutorial and getting a malloc error. Any help welcomed! 

Thanks in advance and amazing work on SWIG.

https://stackoverflow.com/questions/68986552/swig-converting-python-list-to-a-char-example-fails

**Comment by guillaumeguy** [comment]
Mark answered my question on SO and his solution seems to work. Would you like me to update the documentation accordingly? Thx

**Comment by wsfulton** [comment]
Yes please!

**Comment by ojwb** [comment]
I've applied what I understand to be the correct fix - @guillaumeguy please check 005ffc76de05d58c0ec4b7180c69f61b8da42552 and open a PR if I got this wrong.
