### ISSUE TITLE
get or pass bytes value stored in vector<string>  value from c++ to python (python3+) fails

### ISSUE THREAD

**Issue by tilaba** [swig/swig#2076]
As string and bytes are used for python string,  get or pass bytes value stored in vector<string>  value from c++ to python (python3+) fails. it returns a unicode in python3 instead of a  ascii  value (python2)

adding this does not work
%begin %{
#define SWIG_PYTHON_STRICT_BYTE_CHAR
%}

my function defined like this:
void func(char* input, std::vector<string>& list) {}

**Comment by tilaba** [comment]
upgrad the version to 4.1.0, it works

**Comment by vadz** [comment]
Looks like this can be closed then.
