### ISSUE TITLE
ocamlrun.swg not compatible with CAML_SAFE_STRING (new default in ocaml)

### ISSUE THREAD

**Issue by dmacks** [swig/swig#2083]
I originally filed this as a [FTBFS in graphviz](https://gitlab.com/graphviz/graphviz/-/issues/2128#note_687597020), but now I think the actual cause is a bug in swig. In line 372 of ocaml/ocamlrun.swg:
```
	memcpy(String_val(SWIG_Field(vv,0)),p,len);
```
 String_val() might be prototyped to return (char *) or (const char *) in ocaml's mlvalues.h:
```
#ifdef CAML_SAFE_STRING
#define String_val(x) ((const char *) Bp_val(x))
#else
#define String_val(x) ((char *) Bp_val(x))
#endif
```
with CAML_SAFE_STRING being the default in recent ocaml releases. When CAML_SAFE_STRING is defined, swig's memcpy() is a compiler error, for example (from graphviz):
```
gv_ocaml.cpp:1324:2: error: no matching function for call to 'memcpy'
        memcpy(String_val(SWIG_Field(vv,0)),p,len);
        ^~~~~~
/usr/include/string.h:72:7: note: candidate function not viable: no known conversion from 'const char *' to 'void *' for 1st argument
void    *memcpy(void *__dst, const void *__src, size_t __n);
         ^
```
Essentially, swig seems to be trying to copy data to a location that is declared as const. If I undef CAML_SAFE_STRING, compiling succeeds (no problem to write data to a non-const destination). I don't know anything about ocaml or swig, just that CAML_SAFE_STRING is the default in ocaml and therefore graphviz is blocked.

**Comment by ojwb** [comment]
Looking at where `String_val()` is defined, changing to use `Bp_val()` instead should compile, but I've no idea is that would be correct.

@ZackerySpytz Can you take a look?  This seems to stop SWIG working with recently ocaml (I confirmed with 4.13.1).

**Comment by ojwb** [comment]
Using `Bp_val()` in the one place where we need a non-`const` pointer allows our test suite to pass, so I've pushed that as it seems a step forward.

@ZackerySpytz Would still appreciate a review that this is the correct approach.
