### ISSUE TITLE
python_wrap.cxx build failure with VS2022 Preview

### ISSUE THREAD

**Issue by arihannu** [swig/swig#2090]
When building with VS2022 Preview 4.0 onwards, I get a bunch of errors when compiling python wrapper class which was generated with SWIG 4.0.2 on Windows. This compiles fine with VS2019. Using Python 3.9.7 64bit.

```
[777/779] Building CXX object ui\python\CMakeFiles\py3.dir\3\x86_64\PYTHON_wrap.cxx.obj
  FAILED: ui/python/CMakeFiles/py3.dir/3/x86_64/PYTHON_wrap.cxx.obj 
  C:\PROGRA~1\MIB055~1\2022\Preview\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\cl.exe  /nologo /TP -DSWIG_PYTHON_INTERPRETER_NO_DEBUG -D_CRT_SECURE_NO_WARNINGS -Dpy3_EXPORTS -IC:\python\include ...includes removed... /DWIN32 /D_WINDOWS /EHsc /sdl /GR /EHsc /DNOMINMAX /Zi /Ob0 /Od /RTC1 /Od -MDd /W4 /WX /MP /bigobj /WX- /wd5033 -std:c++latest /showIncludes /Foui\python\CMakeFiles\py3.dir\3\x86_64\PYTHON_wrap.cxx.obj /Fdui\python\CMakeFiles\py3.dir\ /FS -c D:\src\ui\python\3\x86_64\PYTHON_wrap.cxx
D:\src\out\build\x64-Debug\cl : Command line warning D9025: overriding '/WX' with '/WX-'
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\xmemory(154): error C2039: '_invalid_parameter': is not a member of '`global namespace''
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\xmemory(154): error C3861: '_invalid_parameter': identifier not found
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\xmemory(164): error C2039: '_invalid_parameter': is not a member of '`global namespace''
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\xmemory(164): error C3861: '_invalid_parameter': identifier not found
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\xmemory(1203): error C2039: '_invalid_parameter': is not a member of '`global namespace''
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\xmemory(1203): error C3861: '_invalid_parameter': identifier not found
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\xpolymorphic_allocator.h(146): error C2039: '_invalid_parameter': is not a member of '`global namespace''
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\xpolymorphic_allocator.h(146): error C3861: '_invalid_parameter': identifier not found
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\xpolymorphic_allocator.h(152): error C2039: '_invalid_parameter': is not a member of '`global namespace''
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\xpolymorphic_allocator.h(152): error C3861: '_invalid_parameter': identifier not found
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\atomic(206): error C2039: '_invalid_parameter': is not a member of '`global namespace''
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\atomic(206): error C3861: '_invalid_parameter': identifier not found
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\atomic(221): error C2039: '_invalid_parameter': is not a member of '`global namespace''
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\atomic(221): error C3861: '_invalid_parameter': identifier not found
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\atomic(237): error C2039: '_invalid_parameter': is not a member of '`global namespace''
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\atomic(237): error C3861: '_invalid_parameter': identifier not found
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\atomic(297): error C2039: '_invalid_parameter': is not a member of '`global namespace''
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30704\include\atomic(297): error C3861: '_invalid_parameter': identifier not found
D:\src\ui\python\3\x86_64\PYTHON_wrap.cxx(4492): warning C4127: conditional expression is constant
  D:\src\ui\python\3\x86_64\PYTHON_wrap.cxx(4492): note: consider using 'if constexpr' statement instead
D:\src\ui\python\3\x86_64\PYTHON_wrap.cxx(4498): warning C4127: conditional expression is constant
  D:\src\ui\python\3\x86_64\PYTHON_wrap.cxx(4498): note: consider using 'if constexpr' statement instead
D:\src\ui\python\3\x86_64\PYTHON_wrap.cxx(4525): warning C4127: conditional expression is constant
  D:\src\ui\python\3\x86_64\PYTHON_wrap.cxx(4525): note: consider using 'if constexpr' statement instead
D:\src\ui\python\3\x86_64\PYTHON_wrap.cxx(4634): warning C4127: conditional expression is constant
  D:\src\ui\python\3\x86_64\PYTHON_wrap.cxx(4634): note: consider using 'if constexpr' statement instead
D:\src\ui\python\3\x86_64\PYTHON_wrap.cxx(4640): warning C4127: conditional expression is constant
  D:\src\ui\python\3\x86_64\PYTHON_wrap.cxx(4640): note: consider using 'if constexpr' statement instead
```

**Comment by thomas-t1** [comment]
I had a similar problem with a completely unrelated project, VS2019 works, VS2022 fails with the above error. The solution for me was to include an additional microsoft/msvc provided header before including the python related headers;

`#include <corecrt.h>`

**Comment by wbinek** [comment]
Hi! Have anyone managed to find a solution to this issue? I can't find a way to force swing to include the `#include <corecrt.h>` before python related headers as the `.cxx` file is autogenerated by swig.

**Comment by wsfulton** [comment]
Has this been reported to the Python project as it sounds like they need to fix their headers?

You can include a file at the very beginning of the wrapper with `%begin`, try:
```swig
%begin %{
#include <corecrt.h>
%}
```

**Comment by wbinek** [comment]
Thank you, it works!

**Comment by arihannu** [comment]
Yes, confirmed this fix worked for us too.

**Comment by ojwb** [comment]
This does seem to be a Python bug (though not one I could find reported at https://bugs.python.org/ - somebody affected really should report this to them), but should we be working around it in `Lib/python/pyruntime.swg` (like we do for a somewhat similar `hypot` issue already)?

I think we should either add a workaround or decide people just have to workaround with `%begin` until it's reported to Python and fixed, and then close this issue.

**Comment by wsfulton** [comment]
The initial report suggests it occurs when defining SWIG_PYTHON_INTERPRETER_NO_DEBUG as mentioned in [docs](https://swig.org/Doc4.0/Python.html#Python_nn12). The fix should thus only be implemented when this macro is defined as also discussed in #325.

I'm testing the following improvement on CI: https://github.com/wsfulton/swig/commit/774c3fa303bbdad8647396aece2aa15081c32abc which also extends the fix to Visual Studio 2019 versions 16.10 + 16.11 onwards

**Comment by wsfulton** [comment]
Some other useful references:
- https://github.com/microsoft/STL/issues/2335 (where Microsoft suggest redefining _DEBUG is not supported)
- https://github.com/pybind/pybind11/pull/3497 where Pybind11 instead uses _MSVC_STL_VERSION instead of _MSC_VER
- https://github.com/KiruyaMomochi/clingo/pull/1 replicating Pybind11 implementation

**Comment by wsfulton** [comment]
dcb2544 has the reworked version committed to master now. Possibly we could use the pybind11 approach, but the one we have is a tad simpler.

**Comment by phetdam** [comment]
> I had a similar problem with a completely unrelated project, VS2019 works, VS2022 fails with the above error. The solution for me was to include an additional microsoft/msvc provided header, which defines `_invalid_parameter`, before including the python related headers;
> 
> `#include <corecrt.h>`

Same issue when compiling a SWIG extension linked against a static library using CMake with VS 2022, SWIG 4.0.2.

The static library is linking against the debug dynamic C runtime while of course `SWIG_PYTHON_INTERPRETER_NO_DEBUG` has been defined in the `%begin` block when `_MSC_VER` is defined. Including `<corecrt.h>`, which contains the declaration for `_invalid_parameter`, has solved the issue for me. Of course 2 C runtimes are being used but that's ok in my case.

Maybe it would be good to mention this useful workaround in the SWIG 4.x docs somewhere?

**Comment by ojwb** [comment]
> Maybe it would be good to mention this useful workaround in the SWIG 4.x docs somewhere?

SWIG 4.1.0 and later should generate code which works around the problem for you, so documenting it in the next release wouldn't be useful; we can't really retrospectively document the workaround in older releases.

**Comment by phetdam** [comment]
> SWIG 4.1.0 and later should generate code which works around the problem for you, so documenting it in the next release wouldn't be useful; we can't really retrospectively document the workaround in older releases.

Sorry, I didn't mean as retroactively amending the doc pages for a release. I was thinking of a "known problems" kind of page somewhere on the web site that could be updated as needed for a specific release.

But it might be enough for the record to remain in this (and related) GitHub issues since Google will index the web pages.
