### ISSUE TITLE
Double-delete crash with %shared_ptr

### ISSUE THREAD

**Issue by torokati44** [swig/swig#2094]
The generated code below (using `%shared_ptr`) calls `delete` manually on the raw pointer returned by `get()`, resulting in a crash later, when the last `std::shared_ptr` tries to also (rightfully so) delete the pointee.

I have substituded the pointee type with `T`.

```c++
SWIGEXPORT void JNICALL ..._delete_1T(JNIEnv *jenv, jclass jcls, jlong jarg1) {
 T *arg1 = (T *) 0 ;
  std::shared_ptr< T > *smartarg1 = 0 ;

  (void)jenv;
  (void)jcls;

  smartarg1 = *(std::shared_ptr<  T > **)&jarg1;
  arg1 = (T *)(smartarg1 ? smartarg1->get() : 0);
  {
    try {
      delete arg1;
    } catch (std::exception& e) {
      SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, const_cast<char*>(e.what()));
      return ;
    }
  }
}
```

This should never ever be done, under any circumstances.

I'm not even sure why the `arg1 = (T *)(smartarg1 ? smartarg1->get() : 0);` line is necessary, as `std::shared_ptr` can be used "transparently", because it overrides the `->` operator.

Is there a `shared_ptr` instance on the heap in these cases, and perhaps _that_ should be deleted? - It doesn't look like it though, as in that case, this shared_ptr would be leaked, and so the pointee would never be deleted again.

**Comment by vadz** [comment]
How was this code generated? I.e. what's your (minimal possible, of course) input file producing this?

**Comment by torokati44** [comment]
Here is a fairly minimal example:

`foobar.h`:
```c++
class FooBar { };
```
----
`foobar.i`:
```swig
%module Test

%include "std_shared_ptr.i"

namespace std {
   %shared_ptr(FooBar);
};

%include "foobar.h"
```
----

`$ swig -c++ -java -o out.cxx foobar.i`

----

I see now that the problem is that `%shared_ptr` is inside `namespace std`. For... historical reasons.
If I move it out of there, `delete arg1;` turns into the correct `delete smartarg1;`.

Still, the fact that the bindings are generated incorrectly without any warnings, they build and appear to work fine, until they crash, seems less than ideal.

**Comment by torokati44** [comment]
I still don't understand how, with the `shared_ptr` on the heap (I found the `new` for it in `..._create_...`) effectively leaked (the pointee is deleted instead of it), the reference count can drop to zero, triggering the crash.
Most likely, there are multiple Java wrappers holding `shared_ptr`s pointing to the same object, and when they are GCd, the second one crashes in this erroneous manual delete - and the recount never actually drops to zero.

**Comment by wsfulton** [comment]
If you delete a shared_ptr created on the heap, it will will in turn decrement the counter of the pointer it is pointing. If you have another specific problem, reopen or create a new issue.

**Comment by torokati44** [comment]
> If you delete a shared_ptr created on the heap, it will will in turn decrement the counter of the pointer it is pointing. 

Yes, that is obvious. However, in this case, the shared_ptr on the heap is _not_ deleted. That's part of the issue.
Anyway, my problem is fixed for now, as mentioned above. Still, if no changes are made to SWIG, nothing will prevent others from running into these kinds of crashes in the future as a result of making the same silly mistake in their `.i` files as I did.
