### ISSUE TITLE
Crash when using embedded Python interpreters

### ISSUE THREAD

**Issue by jsenn** [swig/swig#2101]
We use SWIG to allow users to interact with our SDK by writing Python scripts from within the UI of our application. Each time a user runs a script, a new Python interpreter is created, the extension module is imported, and then the script is run. All of this happens within our application's main process. This looks roughly like the following:
```c++
#include <Python.h>

extern "C"
{
PyObject* PyInit__test(void);
}

void
RunScript( const char* script )
{
	int importSucceeded = PyImport_AppendInittab( "_test", &PyInit__test ); // Import extension module

	Py_Initialize();
	int result = PyRun_SimpleString( script );
	Py_Finalize();
}
```

Our wrapped code looks like the following:
```c++
// Test.h
struct Test
{
    static const int TEST;
};
```
```c++
// Test.cpp
const int Test::TEST = 5;
```
```
// test.i
%module test
%{
#include "Test.h"
%}
%include "Test.h"
```

If you call `RunScript()` with the following script it runs fine, but if you call it again it crashes:
```python
import test
test.Test.__repr__ = lambda self: "Test"
```

The crash is a null pointer dereference in `SWIG_init()`: right at the end of that function, the static `Test::TEST` variable is loaded into the static `globals` var link object. On the second run, this object has been deallocated, which leads to the crash.

I notice that there are multiple issues pertaining to the globals (#1360, #1985, and #2037, which is is still open). Those issues are treating a related issue: in most cases, the globals object is never deleted--a memory leak. In fact, the only reason our application doesn't crash _every_ time you run a script for the second time is that the globals is leaked. For some reason, `swig_varlink_dealloc` is only called if you set a new `__repr__` on a wrapped class, or do some similar things (e.g., adding a new attribute to the module or to a wrapped class).

There are 2 changes to how the globals object is managed that fix the problem. The first is to modify `SWIG_globals()` to check the refcount of the static `globals` variable. If it's 0, create a new one before returning:
```c
SWIGINTERN PyObject *
SWIG_globals(void) {
  static PyObject *globals = 0;
  if (!globals || globals->refcnt <= 0) {
    globals = SWIG_newvarlink();
  }
  return globals;
}
```
The second fix is simpler: get rid of the `SWIG_globals()` function entirely, and just create a new object in `SWIG_init()` itself:
```c
// Instead of globals = SWIG_globals():
globals = SWIG_newvarlink()
}
```
This way there's no static memory available that can get corrupted and cause issues across multiple interpreters. This seems reasonable: if the globals object is supposed to be deallocated when the module is unloaded anyway, why does it have to be static?

EDIT: this was tested against v4.0.1 on Windows

**Comment by wsfulton** [comment]
Is `SWIG_Python_DestroyModule` being called? If so, I think we should set the SWIG_globals singleton in the same way that the SWIG_This singleton works and is destroyed in https://github.com/swig/swig/blob/0304bdb82baaf5da94b6273c93e2623f1522a2a0/Lib/python/pyrun.swg#L1432-L1433. I'd rather keep SWIG_Globals as a function as it could be called outside the wrapper file if SWIGINTERN is defined not to be static for very large projects where the SWIGINTERN functions are not static. BTW, checking or the refcnt < 0 is not healthy, it is indicative of a bug as the count should not go less than zero!
