### ISSUE TITLE
Doesn't work with NodeJS & V8

### ISSUE THREAD

**Issue by matteoturini** [swig/swig#2103]
Steps to reproduce:
Clone https://github.com/matteoturini/nativewebview.git
Run ``git submodule init``
Install NodeJS v17
Install node-gyp via NPM
Install webkit2gtk-4.0 and gtk+-3.0 via your system's package manager
Run ``swig -c++ -javascript -node module.i``
Run ``node-gyp configure``
Run ``node-gyp build``

**Comment by wsfulton** [comment]
The current HEAD of master successfully passes the entire SWIG test-suite using NodeJS v17, see https://github.com/swig/swig/runs/4341234146?check_suite_focus=true. 

I don't know what problem you're having, but If there is a SWIG specific problem in the application you refer to, it probably needs addressing by the application owners.
