### ISSUE TITLE
Make swig available on pypi 

### ISSUE THREAD

**Issue by smasihemami** [swig/swig#2104]
Hello,

What does it take to make swig available on pypi? Just like cmake (https://github.com/scikit-build/cmake-python-distributions/blob/master<->https://pypi.org/project/cmake/). 

I would very much like to contribute, but would probably need some guidance.

**Comment by wsfulton** [comment]
This was discussed on the swig-devel mailing list, see https://sourceforge.net/p/swig/mailman/swig-devel/thread/CAHdctnrkSLm_FFbPWWJbd5rdXTMT%2B4GehdYZM2mAKzvOmm7hzA%40mail.gmail.com/#msg37354834.
