### ISSUE TITLE
Compiling error on Windows

### ISSUE THREAD

**Issue by Mahdi-20** [swig/swig#2107]
Dear SWIG expert,
I am quite new to SWIG and using MingW.
I am trying to make a Python module of a .c code using SWIG on Windows. The files are taken from the SWIG website and I have attached them. [Files.zip](https://github.com/swig/swig/files/7599426/Files.zip)

Running SWIG makes two output files, say, example_wrap.c and exanple.py.

The gcc also works without a problem and makes example.o and example_warp.o.

The problem arises when I want to link the libraries using ld command. I use the following command for linking:

ld -shared example.o example_wrap.o -o _example.so -I "C:\....\Python\Python36\Lib"

There are many errors complaining about the undefined references. I would appreciate it if you can help me with this issue:
......
C:\MinGW\bin\ld.exe: example_wrap.o:example_wrap.c:(.text+0x3d6c): undefined reference to `strcmp'
C:\MinGW\bin\ld.exe: example_wrap.o:example_wrap.c:(.text+0x3db9): undefined reference to `_imp__PyCFunction_Type'
C:\MinGW\bin\ld.exe: example_wrap.o:example_wrap.c:(.text+0x3dfb): undefined reference to `_imp__PyCFunction_NewEx'
C:\MinGW\bin\ld.exe: example_wrap.o:example_wrap.c:(.text+0x3e0b): undefined reference to `_imp__PyInstanceMethod_New'
C:\MinGW\bin\ld.exe: example_wrap.o:example_wrap.c:(.text+0x3e20): undefined reference to `_imp__PyCFunction_Type'
C:\MinGW\bin\ld.exe: example_wrap.o:example_wrap.c:(.text+0x3e62): undefined reference to `_imp__PyCFunction_NewEx'
C:\MinGW\bin\ld.exe: example_wrap.o:example_wrap.c:(.text+0x3e72): undefined reference to `_imp__PyStaticMethod_New'
C:\MinGW\bin\ld.exe: example_wrap.o:example_wrap.c:(.text+0x3ec8): undefined reference to `_imp__PyModule_Create2'
C:\MinGW\bin\ld.exe: example_wrap.o:example_wrap.c:(.text+0x3ed8): undefined reference to `_imp__PyModule_GetDict'
C:\MinGW\bin\ld.exe: example_wrap.o:example_wrap.c:(.text+0x3f15): undefined reference to `_imp__PyExc_TypeError'
C:\MinGW\bin\ld.exe: example_wrap.o:example_wrap.c:(.text+0x3f27): undefined reference to `_imp__PyErr_SetString'
C:\MinGW\bin\ld.exe: example_wrap.o:example_wrap.c:(.text+0x3f4a): undefined reference to `_imp__PyDict_SetItemString'
C:\MinGW\bin\ld.exe: example_wrap.o:example_wrap.c:(.rdata+0x648): undefined reference to `PyObject_GenericGetAttr'
C:\MinGW\bin\ld.exe: example_wrap.o:example_wrap.c:(.rdata+0x728): undefined reference to `PyObject_GenericGetAttr'

**Comment by vadz** [comment]
You need to link with Python import library.
