### ISSUE TITLE
Regression: object destructors no longer called in -php7 mode

### ISSUE THREAD

**Issue by rouault** [swig/swig#2108]
Given the following test.i
```
%module foo;
%inline%{
struct foo { int x; };
struct foo* fooNew(void);
void fooDestructor(struct foo*);
%}


%extend foo 
{
    ~foo() 
    {
        fooDestructor(self);
    }

    %newobject my_new;
    static foo* my_new() {
        return fooNew();
    }
}
```

``./swig -Wall -php7 test.i``, with SWIG master (at 0304bdb82baaf5da94b6273c93e2623f1522a2a0) generates a test_wrap.c file where ~foo() is not called, but instead the foo_free_storage() method calls SWIG_remove() which is just a regular free()
```
/* Garbage Collection Method for class foo */
void foo_free_storage(zend_object *object) {
  swig_object_wrapper *obj = 0;
  if (!object)
    return;
  obj = php_fetch_object(object);
  zend_object_std_dtor(&obj->std);
  if (obj->newobject)
    SWIG_remove((struct foo *)obj->ptr);
}
```

This is a simplified test case of a real world project (https://github.com/MapServer/MapServer/issues/6433). The regression dates back to https://github.com/swig/swig/pull/1982

**Comment by ojwb** [comment]
`SWIG_remove()` is just a macro wrapper to handle calling `free(x)` when wrapping C code and `delete x` when wrapping C++ code.

I think the problem here is that `zend_object_std_dtor()` gets called rather than `fooDestructor()`.

**Comment by ojwb** [comment]
Adding a "runme" for the existing `newobject2` testcase seems to reproduce this:

```
$ cat Examples/test-suite/php/newobject2_runme.php 
<?php

require "tests.php";

check::equal(fooCount(), 0, "no Foo objects expected");
$foo = makeFoo();
check::equal(get_class($foo), "Foo", "static failed");
check::equal(fooCount(), 1, "1 Foo object expected");
$bar = makeFoo();
check::equal(get_class($bar), "Foo", "regular failed");
check::equal(fooCount(), 2, "2 Foo objects expected");
$foo = null;
check::equal(fooCount(), 1, "1 Foo object expected");
$bar = null;
check::equal(fooCount(), 0, "no Foo objects expected");

check::done();
```

The count never goes back down because `~Foo()` is never called.

**Comment by jmckenna** [comment]
Thanks for the fix @ojwb !  Works well on Windows with PHP 8.1.0  (in the MapServer space)

**Comment by ojwb** [comment]
Thanks for confirming.

Especially good to know it works on PHP 8.1.0 as I've not had a chance to try that yet.
