### ISSUE TITLE
Swig and structur (c++, c#)

### ISSUE THREAD

**Issue by Ariouath** [swig/swig#2119]
Hello,
After several attempts to run our project using Visual studio, C ++, SWIG, C # the error message remains the same.
To see how it works, and solve the problem, we tried an example provided by SWIG, this is the example called "nested",
which can be found in: swigwin-4.0.2 \ Examples \ csharp \ nested,
The error message sent for the nested example is the same sent in the case of our project.
 The errors messages : 

public Wheels(MotorCar.Wheels.Shape shape, uint count) : this(examplePINVOKE.new_MotorCar_Wheels((int)shape, count), true) {
    }

System.TypeInitializationException : 'Une exception a été levée par l'initialiseur de type pour 'examplePINVOKE'.'

DllNotFoundException : Impossible de charger la DLL 'example': Le module spécifié est introuvable. (Exception de HRESULT : 0x8007007E)

System.TypeInitializationException
  HResult=0x80131534
  Message=Une exception a été levée par l'initialiseur de type pour 'examplePINVOKE'.
  Source=runme
  Arborescence des appels de procédure :
   à examplePINVOKE.new_MotorCar_Wheels(Int32 jarg1, UInt32 jarg2)
   à MotorCar.Wheels..ctor(Shape shape, UInt32 count) dans C:\swigwin-4.0.2\Examples\csharp\nested\MotorCar.cs :ligne 166
   à runme.Main() dans C:\swigwin-4.0.2\Examples\csharp\nested\runme.cs :ligne 10

Exception interne 1 :
TypeInitializationException : Une exception a été levée par l'initialiseur de type pour 'SWIGExceptionHelper'.

Exception interne 2 :
DllNotFoundException : Impossible de charger la DLL 'example': Le module spécifié est introuvable. (Exception de HRESULT : 0x8007007E)

thank you for helping me

![image](https://user-images.githubusercontent.com/95873610/145441904-468a2135-ee73-46aa-b453-dd4d7b165f51.png)

**Comment by bouazaoui** [comment]
the example works well with swigwin-4.0.2.

**Comment by Ariouath** [comment]
resolved
