### ISSUE TITLE
std basic string issue when trying to generate c# classes

### ISSUE THREAD

**Issue by vasicvuk** [swig/swig#2121]
I tried to generate modsecurity c# classes from modsecurity.i bu I am getting the following error:

```
/usr/local/share/swig/4.0.2/std/std_basic_string.i:44: Error: Syntax error in input(3).
```

I am using modsecurity.i from here:

https://github.com/SpiderLabs/ModSecurity-Python-bindings/blob/master/modsecurity/modsecurity.i

**Comment by wsfulton** [comment]
Best to ask the modsecurity project who set up those interface files. It's probably something to do with their build system and the include paths because the C# module does not use std/std_basic_string.i.
