### ISSUE TITLE
Using an unsigned int in Python

### ISSUE THREAD

**Issue by Mahdi-20** [swig/swig#2123]
Dear SWIG experts,
I have been dealing with SWIG recently and I have generated a Python module from a C library successfully. However, one of the functions in C is defined as:

_short BLKTRANSF(short crate_id, BLK_TRANSF_INFO *blk_info, unsigned int *buffer)_
........

After importing my module into Python, I can call and assign the  crate_id, BLK_TRANSF_INFO *blk_info for the function without a problem. Although I tried to define the _unsigned int *buffer_ which is a pointer, I failed. In C, I can define that variable like   
 _unsigned int blk_transf_buf[49155]_  .

How can do it equivalenlty in Python?

I studied the SWIG manual about typemaps, and pointers but they were quite advanced and I could not solve my problem.

I appreciate your help.

**Comment by wsfulton** [comment]
Search for 'arrays' in the SWIG documentation Python chapter.
