### ISSUE TITLE
SWIG JAVA: Usage of callbackFunction pointer in Structure.

### ISSUE THREAD

**Issue by NitzDKoder** [swig/swig#2124]
Using swig to generate java and C++ wrappers to connect from java to C(vice versa) Code.
JAVA CODE <----> C++ WRAPPER CODE <----> C CODE.

1)**'C' Structure is defined as below having a callbackFunction pointer in
particular.**

BOOL (STDCALL *sendAsyncRequest)(http_req_params *params, http_req **req);

typedef struct plt_http_req_params 
{
    CHAR*                url;
  struct
    {
        UCHAR          name[100];
        UCHAR          val[100];
    }hdrs[10];
    **plt_http_responseCB**    rspCallBack;
	plt_http_type_params           *http_type_params;
    plt_http_req_multipart_info    *multipartReqData;
   }_plt_http_req_params;

typedef struct {
    UINT32                           length;                                                  
    VOID                             *pMultipartContent;                                     
    CHAR                             contentType[10];                
} http_req_multipart_contents;

typedef struct {
    CHAR                             multipartBoundaryInfo[10];    
    UINT32                           multipartContentCount;                                    
    http_req_multipart_contents         **multipartContents;                                   
} plt_http_req_multipart_info;

**2)Now i want to wrap the above struct to Java Object using swig and
also how do we register for the callback function(**plt_http_responseCB**) with Java Layer.**

**3) Response callback function.**

typedef BOOL (STDCALL ***plt_http_responseCB**)(plt_http_rsp_params *rspInfo): //

typedef struct _plt_http_rsp_params
{
	UINT16 reqStatus;
	UINT16 httpStatus;
	VOID * userData;
	plt_buf_info rspData;
	struct
	{
		UCHAR	name[100];
		UCHAR	val[100];
	} hdrs[10];	
}plt_http_rsp_params;

**Callback function usage:**
On some OS events, we need to NOTIFY 'C' layer with the callbackFunction(**plt_http_responseCB**) which we received as part of 'C' struct.

**Please Let us know how do we achieve this using swig and generate java wrappers.**

Thanks

**Comment by wsfulton** [comment]
I would use the directors feature. You will need a C++ wrapper around the C code. Have a look at the Examples/java/callback example.

**Comment by NitzDKoder** [comment]
@wsfulton i do use directors in my project. Help me understand how to apply for this use case here?
