### ISSUE TITLE
test-suite preproc.i and C++-style comments

### ISSUE THREAD

**Issue by KrisThielemans** [swig/swig#2127]
`preproc.i` contains C++ style comments
https://github.com/swig/swig/blob/69b580dfb6e39b5463213908b443a86265bdb23c/Examples/test-suite/preproc.i#L397
but is compile as C for `preproc.ctest`. This could fail on some compilers. (I have a case in the MATLAB test-suite where in some MATLAB versions, the C compiler is called with `-ansi`, which then fails.

Is SWIG supposed to convert C++ style comments to C-style? That seems tough, Even the Python wrapping doesn't do that.

Alternatively, this seems a bug in the test-suite. I think the code with the C++-style comments shouldn't be wrapped in the C case.

**Comment by wsfulton** [comment]
Fixed in 7a9bf33
