### ISSUE TITLE
make check-examples can fail depending on how you run configure

### ISSUE THREAD

**Issue by KrisThielemans** [swig/swig#2128]
I normally use out-of-source builds like this
```sh
mkdir build
cd build
/abspath/to/source/configure
```
This works fine with SWIG, except when building the examples which potentially fail to `TOP_BUILDDIR_TO_TOP_SRCDIR` being an absolute path, which is then used as follows
https://github.com/swig/swig/blob/69b580dfb6e39b5463213908b443a86265bdb23c/Examples/python/class/Makefile#L3
They do work when using
```sh
../rel/path/to/source/configure
```
The reason is `autoconf` sets the `srcdir` variable [different in the 2 cases](https://lists.gnu.org/r/autoconf/2011-04/msg00060.html). This variable is used at
https://github.com/swig/swig/blob/69b580dfb6e39b5463213908b443a86265bdb23c/configure.ac#L2881

So, either we need to update the doc, or use `abs_srcdir`

**Comment by wsfulton** [comment]
You do need to use relative directories when invoking configure. That's how our CI works and what is expected. Any docs to make that clear will be welcome.
