### ISSUE TITLE
How to change the accessiblity of the generated C# classes from `public class` to `internal class`

### ISSUE THREAD

**Issue by Prajwal-Jadhav** [swig/swig#2130]
I am using swig 4.0.x to wrap a c++ file.

Everything is working fine except I want to change the accessibility of the generated C# classes from `public class` to `internal class`.

So far what I have tried is this:
In swig interface file
```
%module example

%{
    #include "include/exampleapi.h"
%}

%include <windows.i>
%include "include/exampleapi.h"

%typemap(csclassmodifiers) SWIGTYPE "internal class"
%pragma(csharp) moduleclassmodifiers="internal class"
```

The above code seems to work for the module class (`example`) and some other files. But it is not changing the accessibility modifier of all the generated classes.

Particularly, classes whose name starts with `public class SWIGTYPE_xxx` (probably known as proxy classes?). These classes contain `internal members` and have a `private` member with type `private global::System.Runtime.InteropServices.HandleRef`.

How do I make them `internal class`?

**Comment by wsfulton** [comment]
`SWIGTYPE_xxx` classes are called [Type Wrapper Classes](http://swig.org/Doc4.0/Java.html#Java_type_wrapper_classes). 

You need to use the C type for the typemap that causes the type wrapper class to be generated. For example `SWIGTYPE_p_int` is wrapping an `int *`. Hence you'd use:
```swig
%typemap(csclassmodifiers) int * "internal class"
```
The defaults for all generated proxy and type wrapper classes comes from csharp.swg:
https://github.com/swig/swig/blob/48eba82ac8847f8422710fac677875baf88566df/Lib/csharp/csharp.swg#L892
So just override these typemaps to provide your customised code and read the chapter on Typemaps.
