### ISSUE TITLE
Python: overload problem in applying OUTPUT to void **const

### ISSUE THREAD

**Issue by mawenhua** [swig/swig#2135]
### Discussed in https://github.com/swig/swig/discussions/2133

<div type='discussions-op-text'>

<sup>Originally posted by **mawenhua** December 30, 2021</sup>
In interface file, I want to make the 4th parameter as OUTPUT
`dds_reg_pub(const uint8_t , const char *const , const char *const , void **const );`
but it seems I cannot directly apply it to OUTPUT, and when I try `typedef void * VOIDP;`
I got 
> TypeError: Wrong number or type of arguments for overloaded function 'dds_reg_pub'.
  Possible C/C++ prototypes are:
    dds_reg_pub(uint8_t const,char const *const,char const *const,VOIDP *const)
    dds_reg_pub(uint8_t const,char const *const,char const *const,void **const)
I tried kinds of combination of (%ignore, %rename, %apply), but either it still request for 4 args, or it cause overload, or the definition got problem. Can some experts help? Thanks in adv.</div>

**Comment by wsfulton** [comment]
You need to write your own `void ** OUTPUT` typemap for this depending on what you want.
