### ISSUE TITLE
How I wrap C++ with Swig

### ISSUE THREAD

**Issue by JunkTheory** [swig/swig#2139]
I learned alot along the way, as I swig in my yellow submarine. C/C++ are very complex. Things like macros, esoteric compiler flags, and even style can make swig unhappy. At last, I realized the deep secrets of swig. It works best when everything is uniform. So, when I wrap C/C++ I will reduce the header into something simpler. Macros can all go away because I do not think Swig even cares about them. Strange compiler flags that annoy swig, can be ignored. I will parse the classes and reduce them into a simpler C++ object. Then I can swig the simplified wrapper and not the direct C++ code. Usually, most header files have things in them that Swig doesn't like. It is such a complex language, swig needs a filter to help it reduce and wrap them. 

Thank you for swig, keep on swig'n it.

**Comment by JunkTheory** [comment]
I do not understand that compiler theory at all. I understand swig inductively and intuitively. You can experiment with it. I know the algorithm exists but I have no idea how you define it.

**Comment by ojwb** [comment]
> Macros can all go away because I do not think Swig even cares about them.

Actually SWIG can wrap `#define`-d constants, and also expands macros.

> Thank you for swig, keep on swig'n it.

Thanks for your support

This doesn't seem to be a bug report, so closing.
