### ISSUE TITLE
go wrapper making link error

### ISSUE THREAD

**Issue by nullbus** [swig/swig#214]
Hi, I'm trying to write some code with c++ and go.
It parses header file great but when I build shared library using the generated wrapper file (eg: example_wrap.cxx), it generates link errors like

```
ccCPMNx5.o:example_wrap.cxx:(.text+0x1f): undefined reference to `_cgo_allocate'
ccCPMNx5.o:example_wrap.cxx:(.text+0x24): undefined reference to `crosscall2'
ccCPMNx5.o:example_wrap.cxx:(.text+0x56): undefined reference to `_cgo_panic'
ccCPMNx5.o:example_wrap.cxx:(.text+0x5b): undefined reference to `crosscall2'
```

It says like I have to link some go-specific libraries and generated example_wrap.cxx file have just forward definition of these functions.
Am I did wrong step? 
I've done same as documentation (http://www.swig.org/Doc2.0/Go.html) in MinGW environment, Windows 7 64bit.

**Comment by cfishbein** [comment]
This is quite old, but has anyone been able to resolve or identify this problem even for Go 1.12+ and Swig 3.x+? I have a similar error set, with `undefined reference to '_cgo_panic'` when trying to create a shared library. I've tried linking the static libraries I found in the go pkg, but I'm not very familiar with a lot of this.

**Comment by wsfulton** [comment]
Have you looked at the latest documentation: http://www.swig.org/Doc4.0/Go.html ? The `go build` approach ought to work.

**Comment by cfishbein** [comment]
That is my current work around. It compiles as expected when I let Go do its thing with a `.swigcxx` interface. But I'd like to compile my own shared library so the user doesn't have to have swig installed to use the code. It appears to be something related to MingGW as far as I can tell. The setup compiles just fine on various linux environments I've tried.

**Comment by cfishbein** [comment]
I was able to isolate the problem, although I don't know much about the underlying C++ library or how it is successfully built and used for other languages (specifically Ruby and PHP).

In the interface file:
```
%include <std_string.i>
%{
#include "MyDefs.h"
#include "MyUtil.h"
using namespace mine;
%}
namespace mine {
std::string toString(MyMap map);
}
```

Where `MyMap` is defined as `std::map<std::string, std::string> MyMap;` in `MyDefs.h` and `toString(MyMap map` is defined in `MyUtil.cpp`

It seems the `toString` definition in the interface is the issue. And specifically only when creating a shared library with MinGW, as mentioned it worked on my linux machine(s).

**Comment by cfishbein** [comment]
I've setup a small demo of it. The readme contains the error and env on my windows setup. It compiled correctly across several Linux setups/versions, so I didn't bother including those.

https://github.com/cfishbein/go-swig-windows

**Comment by ojwb** [comment]
The repo link in the previous comment seems to be dead.

It doesn't make much sense that the `toString` wrapping is the cause.  It seems this should just be a question of what library (or object file perhaps) to link with to provide the missing symbols.

> But I'd like to compile my own shared library so the user doesn't have to have swig installed to use the code

The current Go chapter of the manual (http://www.swig.org/Doc4.0/Go.html) also documents the approach of running `swig -go ...` then `go install` - probably with that approach you can run SWIG, then package up the generated files to give to someone else who can then run `go install` on them.

If that isn't suitable, all I can suggest is running `go build -a -n` to see what the compiler command line is and in particular what libraries it links.

**Comment by ojwb** [comment]
The original report here is really old (2014) and go support on mingw has improved over time - using `go build` as wsfulton suggests should address that.  If you really want to build by hand, look at the commands `go build` runs for you as I describe in the previous comment.

The more recent report seems most likely to be an unrelated problem due to failing to link the definition of `toString`, but the reporter has since deleted their github account (including the repo with the testcase) so we're not likely to get useful closure on that.

I don't see any real benefit in keeping this open at this point.  If anyone reading still has problems build SWIG-generated Go modules on mingw please open a new issue with details.
