### ISSUE TITLE
Having problems with int64_t

### ISSUE THREAD

**Issue by TensorMechanic** [swig/swig#2149]
When I use int64_t in templates in a swig wrapper it gets confused. The compiler sees it as long int, swig sees it as long long int.  I don't understand exactly what causes the problem. Do I need to define something to swig to see it as long long int? I am using gcc on ubuntu linux 20.04 and I have both the ubuntu swig and the github swig in usr/local and it happens with both. I am %include "stdint.i" and also #include cstdint

**Comment by TensorMechanic** [comment]
Well I solved it by defining the types in the interface and not using stdint.i. I think my stdint.i is not in date with the gcc compiler and I will look in it and adjust them to the same thing gcc uses.

**Comment by kokostek** [comment]
It's an old (and self-resolved) issue, but I encountered same problem and end up here after doing some search. So i'm sharing my solution.

Seems like now days swig has `SWIGWORDSIZE64` macro to control this behavior. Here is a fragment from `stdint.i`:
```c
#if defined(SWIGWORDSIZE64)
typedef unsigned long int       uint64_t;
#else
typedef unsigned long long int  uint64_t;
#endif
```

So you can either add this define to the swig compile line:
```
swig -DSWIGWORDSIZE64 ...
```

Or add it to your interface file:
```c
// wrapper.i
#define SWIGWORDSIZE64
```

Or use more portable solution with CMake:
```cmake
include(CheckTypeSize)

check_type_size("long" SIZEOF_LONG)

if(SIZEOF_LONG EQUAL 8)
  set_property(
    TARGET your_target_name
    PROPERTY SWIG_COMPILE_DEFINITIONS SWIGWORDSIZE64
  )
endif()
``` 
I've tested the last one on Windows (MSVC) and on Linux (clang).
