### ISSUE TITLE
pivy: SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by looooo** [swig/swig#2150]
Not sure if this is an issue with swig, but with python3.10 I must define  PY_SSIZE_T_CLEAN before including Python.h. Is there a way to do this with swig?

ref.: https://github.com/coin3d/pivy/issues/88

**Comment by wsfulton** [comment]
```swig
%begin %{
#define PY_SSIZE_T_CLEAN
%}
```

**Comment by looooo** [comment]
Thanks

**Comment by hramrach** [comment]
Can this be generated automagically by swig?

This is required on this python version, generating code without the define is broken.

**Comment by wsfulton** [comment]
It is for swig-4.1.0, see abc8e0bb277f7a54ff4ee209845dde910d267819 and issue #2277.
