### ISSUE TITLE
Issue with std::vector in director function

### ISSUE THREAD

**Issue by cminyard** [swig/swig#2160]
The following swig code:
```
%module(directors="1") tst

%{
#include <vector>
%}

%include <std_vector.i>

%feature("director") HandleBytes;

%inline %{
class HandleBytes {
 public:
    virtual void handle(const std::vector<unsigned char> data) = 0;
    virtual ~HandleBytes() { }
};

 void bytes_wrapper(const std::vector<unsigned char> data,
		    HandleBytes *handler) {
    handler->handle(data);
}
%}
```
generates code that fails to compile:
```
$ swig -python -py3 -c++ tst.i
$ g++ -fPIC -g -shared -I /usr/include/python3.8 -o _tst.so tst_wrap.cxx 
tst_wrap.cxx:4034:283: error: macro "SWIG_as_voidptr" passed 2 arguments, but takes just 1
 4034 | har_std__allocatorT_unsigned_char_t_t, SWIG_POINTER_OWN |  0 );
      |                                                              ^

tst_wrap.cxx:3418: note: macro "SWIG_as_voidptr" defined here
 3418 | #define SWIG_as_voidptr(a) const_cast< void * >(static_cast< const void * >(a))
      | 
tst_wrap.cxx: In member function ‘virtual void SwigDirector_HandleBytes::handle(std::vector<unsigned char>)’:
tst_wrap.cxx:4034:29: error: ‘SWIG_as_voidptr’ was not declared in this scope
 4034 |   obj0 = SWIG_NewPointerObj(SWIG_as_voidptr(new std::vector< unsigned char,std::allocator< unsigned char > >((const std::vector< unsigned char,std::allocator< unsigned char > > &)data)), SWIGTYPE_p_std__vectorT_unsigned_char_std__allocatorT_unsigned_char_t_t, SWIG_POINTER_OWN |  0 );
      |                             ^~~~~~~~~~~~~~~
tst_wrap.cxx:1100:89: note: in definition of macro ‘SWIG_NewPointerObj’
 1100 | (ptr, type, flags)            SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
      |                                                               ^~~
```

**Comment by ojwb** [comment]
Your example code contains invalid C++ in the `%inline` - the second error reported is in your `bytes_wrapper()` function.

Also, please set meaningful issue titles.

**Comment by cminyard** [comment]
I'm not sure what happened with the title, but I fixed it.  I also fixed the code and the errors with my dumb error.  I wasn't focusing on that part, so I was sloppy.  Sorry about that.

**Comment by ojwb** [comment]
Like #2162, you're including an undocumented internal interface file.  Use `std_vector.i` instead.

**Comment by cminyard** [comment]
@ojwb, this has the same failure even if I include the standard std_vector.i.  It seems to have something to do with the directorin typemap.  It's not having an issue with the in typemap passing it to the bytes_wrapper() method.  Hmm, no way to re-open an issue.

**Comment by ojwb** [comment]
Reopening.

Looks like the issue is the argument to macro `SWIG_as_voidptr` contains a comma which the preprocessor sees as two macro parameters:

```
SWIG_as_voidptr(new std::vector< unsigned char,std::allocator< unsigned char > >((const std::vector< unsigned char,std::allocator< unsigned char > > &)data))
```

We ought to generate code that compiles and works here, though you'd do better here to pass by const reference rather than value - maybe the compiler can elide the implicit copy here, but SWIG ends up calling `new` to create a copy of the vector and I doubt the compiler can eliminate that.  If I change the parameters to `const std::vector<unsigned char>& data` then there's no `new` and the generated wrapper compiles.

**Comment by ojwb** [comment]
I've tweaked the example at the top to use `std_vector.i` to avoid future confusion.
