### ISSUE TITLE
Warnings when including std_string.i

### ISSUE THREAD

**Issue by cminyard** [swig/swig#2162]
The following swig code:
```
%module tst2

%include <std/std_string.i>
```
produces the following warnings:
```
$ swig -python -py3 -c++ tst2.i
/usr/local/share/swig/4.1.0/std/std_basic_string.i:216: Warning 509: Overloaded method std::basic_string< char >::insert(std::basic_string< char >::iterator,std::basic_string< char >::size_type,char) effectively ignored,
/usr/local/share/swig/4.1.0/std/std_basic_string.i:195: Warning 509: as it is shadowed by std::basic_string< char >::insert(std::basic_string< char >::iterator,std::basic_string< char >::size_type,std::basic_string< char >::value_type).
```
I don't know if that's harmful, but it probably shouldn't do this.  Tried with end of tree and with 4.0.1.

**Comment by ojwb** [comment]
`std/std_string.i` is an internal implementation detail - there's no mention in the docs of `std/std_string.i` and you should not be including it directly.  The public interface file you should be including here is `std_string.i`.
