### ISSUE TITLE
%delobject doesn't seem to be working

### ISSUE THREAD

**Issue by cminyard** [swig/swig#2163]
Copying the example from the manual:
```
%module tst3;

%{
    #include <iostream>
%}

%delobject Foo::destroy;

%inline %{
class Foo {
public:
    void destroy() { delete this;}

private:
    ~Foo() { std::cout << "Deleted!" << std::endl; }
};
%}
```
with things added to make it work and print something out on delete.  A small test script is:
```
import tst3

a = tst3.Foo()
del a
```
Compile and run with:
```
$ swig -python -py3 -c++ tst3.i
$ g++ -fPIC -g -shared -I /usr/include/python3.8 -o _tst3.so tst3_wrap.cxx 
$ python3 usetst3.py 
swig/python detected a memory leak of type 'Foo *', no destructor found.
```
It should print out "Deleted!", but that's not happening.

This is a case I can't figure out a workaround for.  I have an object with a protected destructor that can't be directly freed due to multi-threading concerns.  But I need some way to write a destructor for it.  If you %ignore the destructor, you can't do %extend and add a destructor and no amount of renaming I tried could handle it.  %delobject seems to be exactly what I want. but I can't make it work.

Since the example doesn't seem to work, I'm suspicious that it's broken.

It's also unclear to me that it blocks the use of the destroy() function from the target language.  That's probably pretty important, as it would cause a double free if the user called it.  Since I can't make it work, I can't look at the output code.

Tested on 4.0.1 and end of tree.

Sorry for writing so many defects.  I have a swig implementation of something that's a mess and I'm trying to get a cleaner implementation without so much custom code for the language, so I can use it on different languages.

**Comment by ojwb** [comment]
I think you're misunderstanding what `%delobject` does:

> %delobject instructs SWIG that the first argument passed to
the method will be destroyed, and therefore, the target language
should not attempt to deallocate it twice. This is similar to use the
DISOWN typemap in the first method argument, and in fact, it also
depends on the target language on implementing the 'disown' mechanism
properly.

I.e. it affects an **explicit** call `a,destroy()` - there isn't any magic hooking up of an implicit call to `a.destroy()` on `del a` or similar.

I think the trick you're missing is to revert the `%ignore` of the destructor before the `%extend`, which you can do by `%rename` to `""` (`%ignore` is internally just a rename to the magic value `$ignore`, so this `%rename` overrides that):

```
$ cat tst3.i
%module tst3;

%{
    #include <iostream>
%}

%delobject Foo::destroy;

%ignore Foo::~Foo();

%inline %{
class Foo {
public:
    void destroy() { delete this;}

private:
    ~Foo() { std::cout << "Deleted!" << std::endl; }
};
%}

%rename("") Foo::~Foo();

%extend Foo {
    ~Foo() { $self->destroy(); }
}
$ ../preinst-swig -c++ -python tst3.i 
$ g++ -fPIC -g -shared -I /usr/include/python3.8 -o _tst3.so tst3_wrap.cxx 
$ python3.8 usetst3.py
Deleted!
```

> Sorry for writing so many defects. I have a swig implementation of something that's a mess and I'm trying to get a cleaner implementation without so much custom code for the language, so I can use it on different languages.

Opening issues for genuine problems that don't have an open issue already is helpful. but please try to make sure they're valid - some of the recent ones have just been including internal interface files.

**Comment by cminyard** [comment]
Ok, thanks for the info.  That wasn't obvious to me from the docs.
