### ISSUE TITLE
Python 3.10 Support

### ISSUE THREAD

**Issue by isaacsanders** [swig/swig#2171]
What are the details on supporting Python 3.10?

**Comment by ojwb** [comment]
I think you'll need to wait for SWIG 4.1.0 or use git master (which supports Python 3.11 as of 7246cfa6c6e1877cd679a23970da477cad039a28).

Closing as there's already 3.10 support so nothing to actually do.

**Comment by isaacsanders** [comment]
:+1: Thanks for the prompt response.
