### ISSUE TITLE
Python3 Dynamic Module does not define "PyInit_xxx

### ISSUE THREAD

**Issue by siberguy** [swig/swig#2187]
I'm attempting to switch from native mac python3.8 to a conda python3.9 install.  I have a bunch c code that I've been using as a python module for some time now on mac's and linux.  I'm building two _xx.so files.  The first includes an buch of routines to call. The second came later and only gives access to some data pointers to access  stuff in memory.  I had to make a number of changes to the link step to get a conda compile and link.  I found some changes for the link step o  the web
Old link step
**_tgs_typedef3.so : typedef3_wrap.o
	$(LD) $(PY_LIB)  -dynamiclib $< $(TGSLIB) $(MYLIBS)  -o $@**
New link step
**_tgs_typedef3.so : typedef3_wrap.o
	$(LD)   -bundle -flat_namespace -undefined suppress $(TGSLIB) $(MYLIBS) -L$(PY_LIB)  -o $@**
Now for the module that only access's data I get the error:

ImportError: dynamic module does not define module export function (PyInit__tgs_typedef3)

when I import to python. The other so files seems OK.
I might add I'm using gfortran as the linker as I'm also including some fotran code that was previously wrapped into the C code a long time ago. The python calls C and the C calls some fortran.  This code has worked on a variety of platforms for about 6 years now.  Trying to get it going in conda has me stumped.  I don't know if there is enough here for getting some advice but I would appreciate any advice and I can share more info if that would help. Thanks Tim

**Comment by ojwb** [comment]
The bit after `PyInit_` is just the value you specified via `%module` in your interface file or `-module` on the command line.  If you're going to call the .so `_tgs_typedef3.so` then you need to specify `tgs_typedef3` as the module name or else Python will look for a different symbol to the one that's in the .so.

**Comment by siberguy** [comment]
There is something more going on here.  First of all my source code works fine on Mac native python and linux.  Here,s the top of my swig file

module tgs_typedef3
%{
    #include "define.h"
    #include "typedef3.h"
    #include "proto.h"
    #include "fcalls.h"
%}

If I look in my wrapper created by swig I see:

#if PY_VERSION_HEX >= 0x03000000
#  define SWIG_init    PyInit__tgs_typedef3

#else
#  define SWIG_init    init_tgs_typedef3

#endif
#define SWIG_name    "_tgs_typedef3"

This is all as it should be  agrees with the _tgs_typedef3.so I build in my makefile.o.  This has something to do with the conda python. I have built other python modules on conda but it doesn't like this one for some reason.  If I've done something wrong it's been fortuitously working for years on other python versions.

**Comment by siberguy** [comment]
I was able to switch some things around on my link command and get a module that loads.  I'm still not sure why it wasn't working or why is is now but I'll take it.
