### ISSUE TITLE
-DFOO works different to a real compiler preprocessor

### ISSUE THREAD

**Issue by ojwb** [swig/swig#2193]
In a C/C++ compiler, `-DFOO` on the command line sets `FOO` to `1`.

In SWIG it sets `FOO` to an empty value.

(In both SWIG and compilers, `#define FOO` in a file sets `FOO` to an empty value.)

Reproducer (same result with 4.0.2 and git master):

```
$ cat emptydefine.i 
#define EMPTY2
[EMPTY1] [EMPTY2]
$ gcc -E -xc -DEMPTY1 emptydefine.i 
# 0 "emptydefine.i"
# 0 "<built-in>"
# 0 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 0 "<command-line>" 2
# 1 "emptydefine.i"

[1] []
$ clang-13 -E -xc -DEMPTY1 emptydefine.i 
# 1 "emptydefine.i"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 343 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "emptydefine.i" 2

[1] []
$ swig -E -python -DEMPTY1 emptydefine.i |tail -n3

[] []
%endoffile
```

The only SWIG documentation for `-D` seems to be this which says nothing about the value (not even that `-DFOO=bar` is supported):

>      -D<symbol>      - Define a symbol <symbol> (for conditional compilation)

Overall it seems better to fix this to me.  It does have a slight potential to break existing use of SWIG, but it's easy to fix - `-DFOO=` if you really want an empty value works now and would continue to work), but it would mean expectations based on compilers would be met going forwards (this quirk just tripped me up while trying to test something).  4.1.0 seems a reasonable release to address this in.

**Comment by wsfulton** [comment]
Agreed, the preprocessor should exhibit standard C preprocessor behaviour. While this change to bring line with C compilers might break existing usage of SWIG, if it is documented in the CHANGES file for the 4.1.0 release, it's okay.

I checked visual C++ and it behaves the same as gcc/clang.
