### ISSUE TITLE
`externc` storage is not set for variables inside `extern "C"` blocks

### ISSUE THREAD

**Issue by sethrj** [swig/swig#2198]
The `storage` attribute for variables is only set to `externc` when the declaration itself is annotated as `extern "C"`, but not when they're embedded in an `extern "C"` block. For example, the following only marks `int1` as `externc`, but it sets storage of `int2` only to `extern`.
```c++
%module extern_c

%inline %{
extern "C" int int1;
extern "C" { extern int int2; }
%}

%{
extern "C" {
  int int1 = 123;
  int int2 = 456;
}
%}
```

The `-debug-module 1` output shows:
```
+++ cdecl - 0x7fd80e931be0 ----------------------------------------
| sym:name     - "int1"
| name         - "int1"
| decl         - ""
| storage      - "externc"
| kind         - "variable"
| type         - "int"
| sym:symtab   - 0x7fd80e800620
| sym:overname - "__SWIG_0"
| 
+++ extern - 0x7fd80e931fe0 ----------------------------------------
| name         - "C"

      +++ cdecl - 0x7fd80e931f00 ----------------------------------------
      | sym:name     - "int2"
      | name         - "int2"
      | decl         - ""
      | storage      - "extern"
      | kind         - "variable"
      | type         - "int"
      | sym:symtab   - 0x7fd80e800620
      | sym:overname - "__SWIG_0"
      | 
```

This doesn't affect anything in current SWIG but is needed for the Fortran `%fortranbindc` feature.

**Comment by ojwb** [comment]
See comment on PR (I still hate the github concept of splitting the issue and the patch to fix the issue into separate tickets as it leads to splitting the discussions of an issue; it's also unhelpful that there doesn't seem to be a way to convert a PR into an issue when someone submits "the wrong fix" but the issue it attempts to address is valid).

**Comment by sethrj** [comment]
Sorry about that @ojwb : I thought about explaining "the issue this PR tries to fix" on the PR itself since some workflows do that -- I'll not open redundant issues in the future.

**Comment by ojwb** [comment]
I think at least for SWIG (and especially for PRs such as your recent ones) if you have a patch which isn't for an already reported issue it makes sense to only open a PR and put any required additional explanation there.  We're kind of drowning in tickets as it is (things have improved significantly over the past couple of months, but we still have close to 500 tickets here and over 200 still in the old SF trackers).
