### ISSUE TITLE
Go doesn't handle nil passed to C++ pointers

### ISSUE THREAD

**Issue by cminyard** [swig/swig#2203]
If you have the following swig code, name tst.i
```
%module tst;

%inline %{
#include <iostream>
struct asdf { int a; };

void tester(struct asdf *a) {
    if (a)
	std::cout << "It's not NULL" << std::endl;
    else
	std::cout << "It's NULL" << std::endl;
}
%}
```
put it in the tst directory in the current directory.  Set it up using:
```
~/t1/tst9$ cd tst
~/t1/tst9/tst$ swig -go -intgosize 64 -c++ tst.i
~/t1/tst9/tst$ go mod init tst
go: creating new go.mod: module tst
go: to add module requirements and sums:
	go mod tidy
~/t1/tst9/tst$ go mod tidy
~/t1/tst9/tst$ cd ..
```
Then create the following go code named use.go in the current directory:
```
package main

import "tst"

func main() {
	a := tst.NewAsdf()
	tst.Tester(a)
	tst.Tester(nil)
}
```
and compile and run it:
```
~/t1/tst9$ go mod init use
go: creating new go.mod: module use
go: to add module requirements and sums:
	go mod tidy
~/t1/tst9$ go mod edit -replace tst=./tst
~/t1/tst9$ go mod tidy
go: found tst in tst v0.0.0-00010101000000-000000000000
~/t1/tst9$ go build
~/t1/tst9$ ./use
It's not NULL
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x45855e]

goroutine 1 [running]:
tst.Tester({0x0, 0x0})
	/home/cminyard/t1/tst9/tst/tst.go:114 +0x1e
main.main()
	/home/cminyard/t1/tst9/use.go:9 +0x47
```
I would expect that this would be handled like Python, where None is converted to NULL.  There's no documentation that handles this, but I have interfaces that need to take NULLs in some cases.

I have a fairly ugly workaround.  Rewrite the swig code to:
```
%module tst;

%go_import("reflect")

%typemap(imtype) (asdf *) "uintptr"
%typemap(goin) (asdf *) {
    if ! reflect.ValueOf($input).IsValid() {
	$result = 0
    } else if reflect.ValueOf($input).IsNil() {
	$result = 0
    } else {
	$result = $input.Swigcptr()
    }
}

%inline %{
#include <iostream>
struct asdf { int a; };

void tester(asdf *a) {
    if (a)
	std::cout << "It's not NULL" << std::endl;
    else
	std::cout << "It's NULL" << std::endl;
}
%}
```
Then the go code to:
```
package main

import "tst"

type myAsdf struct {
	tst.Asdf
}

func NewMyAsdf() *myAsdf {
	return &myAsdf{tst.NewAsdf()}
}

func main() {
	a := NewMyAsdf()
	tst.Tester(a)
	tst.Tester(nil)
}
```
and it will work ok.  But you have to pass in a struct pointer, not an interface.  IMHO swig should handle this without issue.

**Comment by cminyard** [comment]
Oh, and I didn't find anything about this in the docs.

**Comment by ojwb** [comment]
@ianlancetaylor Can you take a look please?

**Comment by cminyard** [comment]
Another bit of information.  There is also an issue if the function is overloaded.

If you change the function of tester to:
```
void tester(asdf *a = NULL) {
```
swig will generate:
```
func Tester(a ...interface{}) {
	argc := len(a)
	if argc == 0 {
		Tester__SWIG_1()
		return
	}
	if argc == 1 {
		Tester__SWIG_0(a[0].(Asdf))
		return
	}
	panic("No match for overloaded function call")
}
```
and if you pass in nil the cast "a[0].(Asdf)" will fail.

**Comment by cminyard** [comment]
Note that you also can't pass in nil to a "char *" from Go to C++.  That's a common practice on the C/C++ side, but I'm not quite sure what to do about that.  This one is causing me some pain.

**Comment by ianlancetaylor** [comment]
The Go language overloads the meaning of `nil`.  The identifier `nil` is both the zero value of an interface type and the zero value of a pointer type.  This does lead to some confusion: https://go.dev/doc/faq#nil_error.

SWIG treats all C++ classes (and structs) as Go interface types.  The Go function `tst.tester`, which takes a C++ argument of type `struct asdf *`, takes a Go argument of type `tst.Asdf`, and `tst.Asdf` in an interface type.  So when you pass `nil` as the argument, you are passing `nil` as the interface type, which is not the same as passing `nil` as a pointer type.  It crashes when the SWIG tries to convert from the interface type to the C++ pointer type.

The pointer type is `wrap.SwigcptrAsdf`, and your code would work if you wrote `tst.Tester(tst.SwigcptrAsdf(0))`.  That passes a `tst.Asdf` containing the zero pointer type.

That said, it should be possible to check for an interface `nil` and treat that as a pointer `nil`, and that may be easier to understand for C++ code working with pointers to classes and structs.

**Comment by ojwb** [comment]
> Note that you also can't pass in nil to a "char *" from Go to C++. That's a common practice on the C/C++ side, but I'm not quite sure what to do about that. This one is causing me some pain.

Now #2242.
