### ISSUE TITLE
Director locks can lead to crashes on Win32

### ISSUE THREAD

**Issue by skochinsky** [swig/swig#2209]
This was reported by a user for our Python wrapper generated by SWIG 4.0.1. It seems [current code](https://github.com/swig/swig/blob/master/Lib/python/director.swg) switched to Python locks so likely not problematic anymore but [ruby](https://github.com/swig/swig/blob/master/Lib/ruby/director.swg) and [ocaml](https://github.com/swig/swig/blob/master/Lib/ocaml/director.swg) backends still use the old approach so probably have the issue.

Briefly,  the _simple thread abstraction for pthreads on win32_ tried to use `CRITICAL_SECTION` as a replacement  of `pthread_mutex_t`. Unfortunately, `CRITICAL_SECTION` cannot be initialized statically; [`InitializeCriticalSection`](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-initializecriticalsection) **must** be called before one can use `EnterCriticalSection` or `LeaveCriticalSection`. Our approach was to replace it by a class which automatically initializes and destroys the underlying critical section object:

```
/* simple thread abstraction for pthreads on win32 */
#ifdef __THREAD__
# define __PTHREAD__
# if defined(_WIN32) || defined(__WIN32__)
#  include <windows.h>
class pthread_mutex_t {
private:
  CRITICAL_SECTION m_CS;
public:
  pthread_mutex_t() 
  {
    InitializeCriticalSection(&m_CS);
  }
  ~pthread_mutex_t() 
  {
    DeleteCriticalSection(&m_CS);
  }
  void lock()
  {
    EnterCriticalSection(&m_CS);
  }
  void unlock()
  {
    LeaveCriticalSection(&m_CS);
  }
};
#  define pthread_mutex_lock(var) (var)->lock()
#  define pthread_mutex_unlock(var) (var)->unlock()
#  define SWIG_MUTEX_INIT(var) var
# else
#  include <pthread.h>
#  define SWIG_MUTEX_INIT(var) var = PTHREAD_MUTEX_INITIALIZER 
# endif
#endif

```

**Comment by ojwb** [comment]
> This was reported by a user for our Python wrapper generated by SWIG 4.0.1.

I'm dubious about that - `git grep` only shows Ocaml and Ruby (and the testsuite) in 4.0.1:

```
$ git grep CRITICAL_SECTION v4.0.1 --
v4.0.1:Examples/test-suite/swig_examples_lock.h:  CRITICAL_SECTION mutex_;
v4.0.1:Lib/ocaml/director.swg:#define pthread_mutex_t CRITICAL_SECTION
v4.0.1:Lib/ocaml/director.swg:#define MUTEX_INIT(var) CRITICAL_SECTION var
v4.0.1:Lib/ruby/director.swg:#  define pthread_mutex_t CRITICAL_SECTION
```

It looks like SWIG-generated Python code hasn't used `CRITICAL_SECTION` since SWIG 1.3.32:

```
commit 4aaf48d65055bd68cc55e81f915af39693e9a7a6
Author: Olly Betts <olly@survex.com>
Date:   Sat May 12 13:55:19 2007 +0000

    swig -python -threads now generates C/C++ code which uses Python's
    own threading abstraction (from pythread.h) rather than OS specific
    code.  The old code failed to compile on MS Windows.  (See SF patch
    tracker #1710341).
    
    
    git-svn-id: https://swig.svn.sourceforge.net/svnroot/swig/trunk@9806 626c5289-ae23-0410-ae9c-e8d60b6d4f22
```

(Though #2190 would change that at least when `-py3-stable-abi` is passed.)

**Comment by skochinsky** [comment]
Oh indeed, we use a [fork](https://github.com/idapython/swig) with `-py3-stable-abi` support. Sorry for the confusion.

**Comment by ojwb** [comment]
@skochinsky Please can you submit a PR for your suggested change above.

Looks like we don't have CI for Ruby or Ocaml on appveyor currently, but at least we can check it doesn't regress anything for Linux, and we'll know your manual testing was with the patch we actually apply.

**Comment by erezgeva** [comment]
I see "corrupted double-linked list" in Linux when using Ruby director.
Nut sure if it is related.

**Comment by erezgeva** [comment]
I added PR #2870, which uses the same code for Python and Ruby.
Ocaml had the  Guard code, but did not use it.
The PR also uses C++ 11 std::mutex.
MSVC from 2015 onward uses C++ 11 or above, and need the compilation flag `/Zc:__cplusplus` as explained in #2860.

**Comment by wsfulton** [comment]
Please see #2870.

**Comment by erezgeva** [comment]
Hi @skochinsky 

Can you check if the bug persist after merging #2870?
I do not have a Windows machine, and I can not verify.

Thanks
  Erez
