### ISSUE TITLE
python: comments in pythoncode

### ISSUE THREAD

**Issue by fabiencastan** [swig/swig#221]
The following code creates an error in the master branch.
The same code was working in version 2.0.11.

```python
%pythoncode
{
def function_with_comment():
    a = 3
    # b = 4
    c = 5
}
```

**Comment by ojwb** [comment]
I've now documented the need to use the correct delimiters, explaining why this is more important as of SWIG 3.0.3, so closing this ticket.  While warning about this might be nice, I don't see an easy way for the SWIG parser to know it is in a block of Python code.

**Comment by ojwb** [comment]
It occurred to me that the error doesn't actually need to be context sensitive, so the error given is now:

```
issue221.i:5: Error: Unknown SWIG preprocessor directive: b (if this is a block of target language code, delimit it with %{ and %})
```

Hopefully that should help those hitting this issue, without confusing those who just can't spell `#elif`.
