### ISSUE TITLE
Add documentation for XML output

### ISSUE THREAD

**Issue by ojwb** [swig/swig#2213]
Looking at the XML backend, it doesn't even come close to meeting the criteria for 'Supported' status - annotating the list from the manual:

* It is in a mature, well functioning state.  _Does old count as mature?  It's hard to tell if it functions well due to lack of any docs or tests. Open bugs: #874 https://sourceforge.net/p/swig/bugs/1005/ https://sourceforge.net/p/swig/bugs/1007/_
* It has its own comprehensive chapter in the documentation. _No chapter on XML at all_
* The level of documentation should be comprehensive and match the standard of the other mature modules. _I failed to find **any** useful docs. Seems `swig -help` is about all there is!_
* It passes all of the main SWIG test-suite. _No testsuite (while testcases can't be "run" as such, the generated XML could perhaps be normalised and diffed with an expected version, or be tested with something like XPath to look for expected features)._
* The test-suite must also include at least twenty wide-ranging runtime tests. _FAIL!_                                                                                                               
* It supports the vast majority of SWIG features. _Maybe - hard to tell due to lack of docs and tests_                                                                                                        
* It provides strong backwards compatibility between releases. _It does well here due to the code hardly ever being touched: no changes at all since 2016; only 4 changes ignoring global cleanups in the last decade._
* Examples must be available and run successfully. _There are examples in `Examples/xml` but `make` in that directory fails - looks like the expected XML is radically different to the XML actually produced; `make check-xml-examples` at the top level just says `xml unknown`!_
* The examples and test-suite must be fully functioning on the Github Actions Continuous Integration platform. _No CI for XML_

It doesn't really meet the criteria even for "experimental" status - if it were a new backend we clearly wouldn't accept it in its current state.

However I think disabling it right now is too aggressive and it should be moved to "experimental" status for 4.1.0.  That way the problems with it are made clear to users and they have a chance to step up to sort it out, but we don't suddenly break it for users who might actually be successfully using it.

**Comment by ojwb** [comment]
Some other candidates for experimental status:

* SWIG/Tcl's `-itcl` options has no test coverage, no docs beyond "-itcl           - Enable ITcl support", and [an open bug since 2005](https://sourceforge.net/p/swig/bugs/537/) because it doesn't support C++ function overloading (which seems a significant limitation gives according to Wikipedia "incr Tcl (commonly stylised as [incr Tcl], and often abbreviated to itcl) is a set of object-oriented extensions for the Tcl programming language").
* SWIG/Lua's `-elua` option has no test coverage.  It is at least documented, but the docs say "Due to substantial changes between SWIG 2.x and SWIG 3.0 and unavailability of testing platform, eLua status was downgraded to 'experimental'."  We really should handle this "experimental" status consistently with experimental full target languages and emit a warning.

**Comment by ojwb** [comment]
Demoting XML seems the obvious move and nobody's spoken up for it in 5 months so I went ahead.

We don't currently have similar warnings for any other parts of target languages, so I'd appreciate feedback on whether there's consensus that use of `-itcl` and `-elua` should issue similar warnings.  It seems to make sense to me - like with a whole target language, options which select some "flavour" of that language really need to be documented and have automated tests to be supportable, and if they aren't it's better for users to be aware of that (and being aware of it may motivate someone to step up and improve the situation).

**Comment by ojwb** [comment]
I notice we have quite a few other casual mentions that some feature or other is experimental, some of which are ancient - e.g. `Examples/test-suite/aggregate.i` warns that "Note: Contracts are still experimental.  The runtime interface may change in future versions" but the contract interface appears to be unchanged since that comment was added in 2003 (c27b0572ec76ff4325f7ed1980ef90b4e5135ded)

I can try to clean up those too at some point.

**Comment by wsfulton** [comment]
@ojwb, XML isn't really a target language at all and it never will be! It's not much different to the `-debug-top` debug option which dumps internal parse tree information. The main difference is the format of the output. I can't honestly see the point of labelling this as experimental, it's like labelling `-debug-module` as experimental. It is what it is, but could do with a simple test and can definitely be better documented (like a lot of other things). How about just not labelling it a target language instead?

**Comment by ojwb** [comment]
It seems like a double standard to me to rip out CFFI which has at least had someone care about it this year, but to argue against demoting (not even removing at this point) XML which it seems nobody has cared about for a very long time.

In my opinion XML's status is far below that of CFFI.  The last SWIG/xml specific change I can see is 2d871655e37d2e587a935aaba5023735767f291e which is 6 years ago; 2012 before that.  Bugs reports about it have been ignored (except for my triaging efforts) since 2009: https://sourceforge.net/p/swig/bugs/1005/ https://sourceforge.net/p/swig/bugs/1007/

And if there are people out there using it, moving it to experimental status is probably the best way we have to communicate to them that the code is neglected and really needs someone to give it some love.  If someone comes forward to fix it, that's a result.  If there's total silence, that gives us a stronger indication that it really isn't used by anyone.  This is true regardless of whether you view it as a target language or not.

If it's not a target language but just `-debug-top` in a different format, is that useful?

XML is really not a human readable format whereas `-debug-top` is fairly readable - I'd say the problems with `-debug-top` are (a) potentially too much information and (b) you need to have some idea what it all means, and transcoding it to XML addresses neither of those.  I'd never even consider using `-xml` to debug something personally.  I assumed SWIG/XML was intended for people wanting to automatically parse the output of to extract C/C++ declaration information to use in other tools, but libclang, etc would be a better choice for that as they don't have the limitations of SWIG's parser.

If it's not going to be demoted, it'd be helpful for someone to `Examples/xml` really needs fixing or deleting - it's just pointless source tree bloat currently.

**Comment by ojwb** [comment]
There's also a long-open bug with no response (aside from my triaging efforts) in this tracker: #874

**Comment by wsfulton** [comment]
Honestly, I can't see how XML output can be compared against another target language. There are no inputs that are fundamental to a target language (SWIG typemaps, features). It really is a dump of the parse tree, nothing more. The debug options are useful for human reading, but XML output is much more friendly for consumption by tools, so they each have their purpose.

I don't know how many people use it, but it is mentioned every now and again. It is so simple, it is quite unlikely to have any meaningful bugs in it, in the same way I don't ever recall seeing a bug against the debug options.

Yes, let's just delete Examples/xml and write a section in the documentation on XML usage. I'd have to go work some of this out myself, but it's worthy of a Github issue to improve it. Let's tag this for improvement for 4.2, it won't take long to figure it out and document it. Should we just hijack this issue or create a new one?

**Comment by ojwb** [comment]
@wsfulton Are you confusing `-xml` and `-xmlout`/`-dump_xml`?

The latter seems much more akin to `-debug-top`:

`-debug-top <n>  - Display entire parse tree at stages 1-4, <n> is a csv list of stages`

vs

`-xmlout <file>  - Write XML version of the parse tree to <file> after normal processing`

(`-dump_xml` seems to be `-xmlout /dev/stdout` but more portable - it's not actually documented at all except for the briefest mention in an CHANGES entry from 2004.)

I'm talking about `-xml` here, which is presented as a target language which generates "XML wrappers":

```
Experimental Target Language Options
     -mzscheme       - Generate MzScheme/Racket wrappers
     -ocaml          - Generate OCaml wrappers
     -xml            - Generate XML wrappers
```

The documentation for `-xmlout` is very thin (just that one line in `-help` output and the ancient CHANGES entry), but a comment above the function it calls in `Source/Modules/xml.cxx` says:

```
 * Dump an XML version of the parse tree.  This is different from using the -xml
 * language module normally as it allows the real language module to process the
 * tree first, possibly stuffing in new attributes, so the XML that is output ends
 * up being a post-processing version of the tree.
```

**Comment by wsfulton** [comment]
`-xmlout` and `-xml` are the same thing but with one main difference. `-xmlout` dumps the parse tree after a target language has completed and `-xml` dumps the parse tree without any target language. `-xml` is really the 'no target language' option for dumping the parse tree as XML, it simply dumps the parse tree at stage 3 with no further processing in stage 4 (which is normally the target language stage). The code that dumps the XML for both options is the same and lives in xml.cxx, the supposed 'target language'. Again, documentation should clarify all this.

**Comment by ojwb** [comment]
OK, so one is like `-debug-top 3` but with virtually no documentation and in a much less readable format, the other like `-debug-top 4` but with virtually no documentation and in a much less readable format.

I'm still really not seeing even a weak case for keeping them.  Without a tool to process the XML output, being in XML just makes things harder to read (especially anything involving C++ references or templates).  They're just adding more code we have to maintain, and accumulating more bug reports that nobody is dealing with but which contribute to clogging up the bug trackers and making it harder to see the wood for the trees.

Looking at it the other way, if someone opened a PR with a new `-json` "target language" and a `-jsonout` option with a secret `-dump_json` option, I find it hard to believe you'd accept it with the same lack of useful documentation and with a broken set of examples.  Why does this particular existing feature get a free ride?  "People might be using it" doesn't seem convincing because we've dropped whole target languages which people might have been using, but also I really don't see any evidence of people actually using it.  Debian codesearch doesn't find anything; I believe wxPython used use the XML output but they've since stopped using SWIG entirely.  Also moving to experimental status would provide a chance for anyone using it to speak up.

If you're going to override me and revert the changes here, I really think you need to commit to documenting these properly, sorting out `Examples/xml` (which exists, but isn't hooked up at the top level and fails badly if run directly), and resolving the open XML tickets.  Really the better way round would be to leave this change in, then move the status back once these issues have actually been addressed.

**Comment by ojwb** [comment]
> [XML output] is so simple, it is quite unlikely to have any meaningful bugs in it

I've already linked to these above, but it seems you must have missed them - here are the open (all for years, two for over a decade) bugs:

* #874
* https://sourceforge.net/p/swig/bugs/1005/
* https://sourceforge.net/p/swig/bugs/1007/

If SWIG/XML isn't meant to be regarded as a target language then at least "%ignore not utilized for xml output" could probably be closed as "wontfix", but we currently do list `-xml` as a target language so in the absence of useful documentation for it users trying it are going to assume it supports things other target languages do.

**Comment by mi-hol** [comment]
> If it's not a target language but just `-debug-top` in a different format, is that useful?
> 
> XML is really not a human readable format

I just started to use XML output for automating document creation from source code.
It is useful because it avoids the hassle of parsing C/C++ correctly.

**Comment by mi-hol** [comment]
The reason for considering SWIG for my use case is:
"Tagline: SWIG is a compiler that integrates C and C++ with languages
         including Perl, Python, Tcl, Ruby, PHP, Java, C#, D, Go, Lua,
         Octave, R, Scheme (Guile, MzScheme/Racket), Scilab, Ocaml.
         **SWIG can also export its parse tree into XML**."
found in https://github.com/swig/swig#readme

This should be amended first before changing the XML feature status to experimental!

**Comment by ojwb** [comment]
> This should be amended first before changing the XML feature status to experimental!

Both MzScheme/Racket and Ocaml support are also listed there but both were demoted to experimental a while ago (looks like SWIG 4.0.0).  SWIG still supports them for now, but issues a warning because that support has reached the point where someone really needs to step up and actually maintain it (and Ocaml has seen some attention since, so it seems that warning users that the feature they are using needs some work does indeed motivate some to contribute).

That's also a realistic summary of the current status of XML support.  If you're finding it useful that person could be you!

I'd also point out that SWIG's parsing (particularly of modern C++) has numerous deficiencies, especially lagging behind features added by newer C++ standards but there are still [C++11 parser features missing](https://github.com/swig/swig/issues?q=is%3Aopen+label%3AC%2B%2B11+label%3Aparser).  We're gradually improving the situation, but every few years a new C++ standard adds more.  There are also things SWIG just doesn't need to parse to do its job and it's likely it'll continue to just cheat and skip over those.

So if you want a general purpose C/C++ parser, something like libclang would likely be a more appropriate choice - it's been suggested SWIG should switch to using this instead of our current bison-based parser (#918) but we need to be able to parse not just C/C++ but also the SWIG-specific syntaxes (directives and a few other things) so that's probably an unrealistically large project.

**Comment by mi-hol** [comment]
> want a general purpose C/C++ parser, something like libclang would likely be a more appropriate choice

From comments [here](https://stackoverflow.com/questions/46383902/use-clang-to-extract-documentation-comments-as-xml) and [clang doc ](https://clang.llvm.org/docs/ClangFormat.html?highlight=xml)the only available XML output seems:
"--output-replacements-xml      - Output replacements as XML."

At this stage the scope is limited to parsing a header file used for embedded micro-processors

**Comment by ojwb** [comment]
> `Examples/xml` really needs fixing or deleting - it's just pointless source tree bloat currently.

I've removed this directory and the autotools references to it.

These examples aren't hooked up to `make check-xml-examples`, and runnning `make -C Examples/xml` fails showing more than 10000 lines of differences from the expected output (and has done for years).  If we're never going to ever actually demote XML to the experimental status it deserves (or just remove it as unmaintained and not actually useful) we really should have test coverage for it, but keeping these very broken examples in the tree doesn't help anyone.

**Comment by ojwb** [comment]
@mi-hol You'd write code to use clang for this, e.g. its [libClang API which allows "iterating through an AST with a cursor"](https://clang.llvm.org/docs/Tooling.html), rather than getting an XML file which you then have to parse.

**Comment by wsfulton** [comment]
I plan to add some docs, but don't see this as being necessary before the release candidate has been put out. So something to work on after release candidate has been released.

With regards to testing this, we could add  xml validation on the generated xml to ensure it is well formed, that's about all that is guaranteed in the output.

**Comment by ojwb** [comment]
Good that this now has some documentation.

> The XML is a dump of SWIG's internal parse tree and as such it is subject to change at any time as and when SWIG's implementation changes.

So "XML output is much more friendly for consumption by tools" except the format is just a dump of internal state and so can change at any time, so those tools can't rely on the format of it...
