### ISSUE TITLE
Change -php7 parameter back to -php

### ISSUE THREAD

**Issue by abdulmueid** [swig/swig#2219]
Versions 4.0.x of SWIG do not support PHP below version 7, and in my brief testing, the -php7 flag works and builds fine against PHP versions 7.4.x, 8.0.x, 8.1.x

The time is right to update the -php7 flag back to -php, and update the documentation to minimize confusion for new users.

**Comment by ojwb** [comment]
`-php` is already supported as an alias for `-php7`, and dropping support for `-php7` would also be unhelpful as it would break makefiles (and similar) which currently work and also make it unnecessarily difficult to write a makefile which works with both SWIG 3.0.x and SWIG 4.0.x.
