### ISSUE TITLE
variadic template causing syntax error

### ISSUE THREAD

**Issue by mwheaton** [swig/swig#2232]
The following code is causing a syntax error.  Is this something that swig should parse, or is there a workaround?: 

```
private:
    template <typename... Args>
    static void                           notifyMyTypes(void        (MyType::*function)(T *, Args...),
                                                        const char  *fname,
                                                        T           *database,
                                                        Args...     params);
```

Also, thanks to Olly Betts for all the work you do, and for directing me to the right place to enter an issue.

Matt

**Comment by ojwb** [comment]
I think this may be the same as #1863.  Unhelpfully there are 4 different issues mentioned in that ticket, but the complete example for the remaining one there is:

```
%module test1
#include <type_traits>
class Container {
public:
template<typename T, typename... Args>
void emplace(Args &&... args) noexcept(
    std::is_nothrow_constructible<T, Args &&...>::value) {}
};
```

**Comment by ojwb** [comment]
I've added a reproducer for this variant to #1863 so closing this as a duplicate now.

**Comment by wsfulton** [comment]
The originally posted problem and subsequent example are working in swig master as at 041ec797478ec1a3dc0da6f05784f1db11fc11ce for swig-4.2.

**Comment by mwheaton** [comment]
Thank you!
