### ISSUE TITLE
Go handling of C++ exceptions doesn't pull the what() information from the exception

### ISSUE THREAD

**Issue by cminyard** [swig/swig#2234]
If you register a function to return a C++ exception that go should handle, it produces code like:
```
  try {
    (arg1)->proc_setup();
  } catch(gensio::gensio_error &_e) {
    (void)_e;
    _swig_gopanic("C++ gensio::gensio_error exception thrown");
    
  }
```
which is ok, but it would be much better if the string from e.what() could be added to the panic string.  That would remove the need for the (void) cast and give more useful information for the panic.

**Comment by ojwb** [comment]
Note that the thrown object may not have a `what()` method (a C++ class doesn't have to derive from `std::exception` to be thrown).  Probably solvable with a bit of template magic to only call `what()` if there is such a method.

**Comment by wsfulton** [comment]
@cminyard, have you looked at the throws typemaps? These control the output for specific exception types and what you should be using.

**Comment by cminyard** [comment]
Ok, it wasn't altogether clear to me from what those docs say how it was supposed to work.  Since I didn't have a throw on the function, I thought %throws wouldn't work.  But after playing with it a bit I see that a %catch acts the same as having a throw on the function.

There is a typo in the docs:
```
%typemap(throws) const char * %{
  PyErr_SetString(PyExc_RuntimeError, $1);
  SWIG_fail;
%}
```
that last "%" shouldn't be there.  But I'm good now.

**Comment by ojwb** [comment]
Looks right to me - the `%}` is needed to match the `%{` opening delimiter (if it opened with `{` then it would indeed need to close with `}`).

The difference between the two types of delimiters is that text inside `%{`...`%}` delimiters is not run through SWIG's preprocessor.

**Comment by cminyard** [comment]
On Thu, Mar 31, 2022 at 07:04:10PM -0700, Olly Betts wrote:
> Looks right to me - the `%}` is needed to match the `%{` opening delimiter (if it opened with `{` then it would indeed need to close with `}`).
> 
> The difference between the two types of delimiters is that text inside `%{`...`%}` delimiters is not run through SWIG's preprocessor.

Ah, you are right.  I think I copied part from one an part from another.
Sorry about that.
