### ISSUE TITLE
A "std::string *" argument from a Go function does not check for nil/NULL

### ISSUE THREAD

**Issue by cminyard** [swig/swig#2245]
Consider the following code:
```
%module tst;

%include <std_string.i>

%inline %{
#include <string>
#include <iostream>
void tester(const std::string *s) {
    if (s) {
        std::cout << "string: " << *s << std::endl;
    } else {
        std::cout << "Got NULL" << std::endl;
    }
}
%}
```
Called from:
```
package main

import "tst"

func main() {
	s := "test1"
	tst.Tester(&s)
	tst.Tester(nil)
}
```
Running this results in:
```
$ ./use
string: test1
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x459345]
```
There are no NULL checks in the code.  This is new from the recent changes dealing with string.  I worked around this with the following typemaps:
```
%typemap(in) (const std::string *) (std::string temp) {
    if ($input) {
	temp.assign($input->p, $input->n);
	$1 = &temp;
    } else {
	$1 = NULL;
    }
}
%typemap(argout) (const std::string *) {
    if ($1) {
	*$input = Swig_AllocateString($1->data(), $1->length());
    }
}
%typemap(goargout) (const std::string *) { }
```
The first typemap is obvious.  The second is required because the return code expects newly allocated data.  The third could check for nil, but I don't care about the value coming back.

**Comment by ojwb** [comment]
@ianlancetaylor Looks like a regression from your recent changes.

**Comment by ojwb** [comment]
> Also, since this is "const", it shouldn't be modifying the value from what is returned, since it can't change.

Yeah, I don't think there should be an `argout` typemap for a `const` pointer or references.

Probably not `goargout` either, just based on the name (not sure what that actually does).
