### ISSUE TITLE
Can't wrap a C++ function that takes `std::string*` as a parameter to Python

### ISSUE THREAD

**Issue by Rabahjamal** [swig/swig#2254]
Hi,

I have a function in my C++ interface that looks something like this:
```
void fun(std::string* str);
```

when I try to call this function from python like this:
```
str = ""
fun(str)
```

I receive the following error:
```
TypeError: in method 'fun', argument 1 of type 'std::string *'
```

However, it works nicely if the function receives just `std::string` instead of `std::string*`.

Could anyone help me with how I can overcome this issue?

Thanks in advance!

**Comment by TomCoalfish** [comment]
you need a typemap why are you passing it as a pointer?
typemap(in) std::string* (char * temp)
{
   temp = new std::string($input)
   $1 = temp;
}
typemap(freearg) std::string*
{
   if($1) delete $1;
}

**Comment by Rabahjamal** [comment]
Thanks, that's really helpful. 

I need to pass it as a pointer because it's an optional parameter and I want to give it a default value of `nullptr` so the caller can pass `None` from python if he doesn't want to pass a value.

**Comment by ojwb** [comment]
This has been answered so closing.

> `if($1) delete $1;`

FWIW `delete` handles `NULL` so no need for the `if($1)` check.
