### ISSUE TITLE
Ruby 3.2 warning: undefining the allocator of T_DATA class swig_runtime_data

### ISSUE THREAD

**Issue by robinst** [swig/swig#2257]
When running generated bindings with Ruby 3.2 (e.g. 3.2.0-preview1 or `rbenv install 3.2.0-dev`), the following warning is printed:

```
mybindings.so: warning: undefining the allocator of T_DATA class swig_runtime_data
```

The change where this warning was introduced is here: https://bugs.ruby-lang.org/issues/18007 – looks like before that, Ruby was just silently happy with it.

`swig_runtime_data` is defined here:

https://github.com/swig/swig/blob/c8bec185541a5839a2a1728d3d83a180d4cd93ad/Lib/ruby/rubyrun.swg#L414-L415

It looks like all that's needed to fix the warning is to add `rb_undef_alloc_func(cl);` after that. Will raise a PR.

(Blocks https://github.com/robinst/taglib-ruby/issues/115)

**Comment by ngan** [comment]
Hi, we're still seeing the warning. I noticed there's another usage of `rb_define_class_under ` without `rb_undef_alloc_func`. Eg  https://github.com/swig/swig/blob/master/Lib/ruby/rubyrun.swg#L160

**Comment by robinst** [comment]
@ngan Nice catch. Can you please open a new issue for this? You could also prepare a PR similar to the one I did.
