### ISSUE TITLE
PyHeapTypeObject errors with PyPy

### ISSUE THREAD

**Issue by KrisThielemans** [swig/swig#2262]
(Originally sent to swig-user mailing list)

Our conda-forge feedstock received an automatic PR to add PyPy support. Unfortunately, I get a lot of errors when compiling the SWIG wrapper like this:
```
$SRC_DIR/build/src/swig/CMakeFiles/_stir.dir/stirPYTHON_wrap.cxx:158287:1:
   error: too many initializers for 'PyHeapTypeObject' {aka '_heaptypeobject'}
```
This is with swig 4.0.2 and pypy 3.8. You can find the log at [Pipelines - Run 20220414.1 logs (azure.com)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=492070&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0&l=6141)

I find the following in the wrapped file (EDIT: generated locally by swig 3.0.12)
```
#if PY_VERSION_HEX < 0x02030000
typedef struct {
  PyTypeObject type;
  PyNumberMethods as_number;
  PyMappingMethods as_mapping;
  PySequenceMethods as_sequence;
  PyBufferProcs as_buffer;
  PyObject *name, *slots;
} PyHeapTypeObject;
#endif

/// stuff

static PyHeapTypeObject SwigPyBuiltin__swig__SwigPyIterator_type = {
  {
#if PY_VERSION_HEX >= 0x03000000
    PyVarObject_HEAD_INIT(NULL, 0)
#else
    PyObject_HEAD_INIT(NULL)
    0,                                        /* ob_size */
#endif
    "stir.SwigPyIterator",                    /* tp_name */
    sizeof(SwigPyObject),                     /* tp_basicsize */
    0,                                        /* tp_itemsize */
    _wrap_delete_SwigPyIterator_destructor_closure,               /* tp_dealloc */
    (printfunc) 0,                            /* tp_print */
    (getattrfunc) 0,                          /* tp_getattr */
    /// more stuff
```

I cannot find any reference to `PyHeapTypeObject` but wonder if the `#if PY_VERSION_HEX` statements are failing with PyPy.

**Comment by KrisThielemans** [comment]
reply from @wsfulton:
> Can you try with master please? There is one fix since 4.0.2 was released that looks like it might be relevant: https://github.com/swig/swig/pull/1843.

**Comment by KrisThielemans** [comment]
I haven't tried this with `master` yet, but cannot see how #1843 can fix this.

The relevant code is generated at https://github.com/swig/swig/blob/1aeaa2a64424e5ffa3797063e23591854a7a5399/Source/Modules/python.cxx#L4134
Looks like it is only generated with the `builtin` option (which we do use).

**Comment by KrisThielemans** [comment]
This is well beyond what I know about Python, but I've done some digging.

;`PyHeapTypeObject` is not documented, see for instance https://docs.python.org/3.8/c-api/typeobj.html?highlight=pyobject_head_init#heap-types. (This is also mentioned at https://github.com/python/cpython/pull/22242#discussion_r524380946). 

For CPython, it is [defined in `object.h`](https://github.com/python/cpython/blob/3b0f1c5a710eff289dc44bec972dbaea353cc54f/Include/cpython/object.h#L240-L259)

For PyPy, it is [defined in `cpyext_object.h`](https://foss.heptapod.net/pypy/pypy/-/blob/branch/default/pypy/module/cpyext/parse/cpyext_object.h#L314), which is [included in `object.h`](https://foss.heptapod.net/pypy/pypy/-/blob/branch/default/pypy/module/cpyext/include/object.h#L10)

SWIG makes sure the wrapper includes `Python.h`, which includes `object.h`.

**Comment by ojwb** [comment]
> `#if PY_VERSION_HEX < 0x02030000`

That's weird as there are no such conditionals in 4.0.2 (there is `#if PY_VERSION_HEX < 0x03020000` with the `2` and `3` switched).

**Comment by KrisThielemans** [comment]
> > `#if PY_VERSION_HEX < 0x02030000`
> 
> That's weird as there are no such conditionals in 4.0.2 (there is `#if PY_VERSION_HEX < 0x03020000` with the `2` and `3` switched).

aargh. Sorry. I actually copied wrapping code locally generated with swig 3.0.12 (as I didn't have access to the wrap.cxx on conda). Apologies. However, the rest of the issue remains.

**Comment by KrisThielemans** [comment]
I've now installed swig 4.0.2 via conda on Windows to generate the wrapper. Compilation with VS 2019 gives a different error, but related to the same code (edited to remove the file path for brevity):
```
1>...\stirPYTHON_wrap.cxx(156696,17): error C2440: 'initializing': cannot convert from 'printfunc' to 'Py_ssize_t'
1>...\stirPYTHON_wrap.cxx(156696,17): message : There is no context in which this conversion is possible
```
This points to the middle line in generated code like
```
    _wrap_delete_ios_destructor_closure,      
    (printfunc) 0,                            
    (getattrfunc) 0,                          
```

I've also manually applied the patch from #1843 to my wrapped file, but that didn't help.

**Comment by KrisThielemans** [comment]
Some more digging shows that the error (at least in VS) is due to a change in `PyTypeObject` introduced in [PET 590](https://peps.python.org/pep-0590/), which since Python 3.8 has  a `Py_ssize_t tp_vectorcall_offset` member where it used to have a `printfunc tp_print` member. Compare https://docs.python.org/3.7/c-api/typeobj.html with https://docs.python.org/3.8/c-api/typeobj.html

It appears that in CPython, this change doesn't give SWIG any trouble due to [the following lines](https://github.com/python/cpython/blob/3b0f1c5a710eff289dc44bec972dbaea353cc54f/Include/cpython/object.h#L142-L144)
```c
/* Allow printfunc in the tp_vectorcall_offset slot for
 * backwards-compatibility */
typedef Py_ssize_t printfunc;
```
but this is [not the case in PyPy](https://foss.heptapod.net/pypy/pypy/-/blob/branch/default/pypy/module/cpyext/parse/cpyext_object.h#L30)
```c
typedef int (*printfunc)(PyObject *, FILE *, int);
```

From some [PyPy code](https://foss.heptapod.net/pypy/pypy/-/blob/branch/default/pypy/module/cpyext/test/specmethdocstring.c#L2919), I believe we should generate code like this
```c
  #if PY_VERSION_HEX < 0x030800b4
  (printfunc)0, /*tp_print*/
  #else
  (Py_ssize_t)0, /*tp_vectorcall_offset*/
  #endif
```
It seems simple enough to modify https://github.com/swig/swig/blob/1aeaa2a64424e5ffa3797063e23591854a7a5399/Source/Modules/python.cxx#L4148 accordingly, but I have no idea what repercussions this would have elsewhere (in particular when people defined the `tp_print` slot.

**Comment by ojwb** [comment]
So it seems `tp_print` was used by Python 2 but until now was unused in Python 3 and that slot has now be reused with a different type.  Anyone still defining it for Python 3 presumably isn't actually doing anything useful, and can just drop that code.

Can you open a PR with your proposed change?  Then CI will test it with a wide range of Python versions for us.

**Comment by TomCoalfish** [comment]
Since when did swig support pypy? I didn't think you could because it doesn't have CPython compatibility

**Comment by wsfulton** [comment]
https://www.pypy.org/ seems to indicate that it does:

> Compatibility: PyPy is [highly compatible](https://www.pypy.org/compat.html) with existing python code. It supports [cffi](https://cffi.readthedocs.org/), [cppyy](https://cppyy.readthedocs.org/), and can run popular python libraries like [twisted](https://twistedmatrix.com/), and [django](https://www.djangoproject.com/). It can also run NumPy, Scikit-learn and more via a c-extension compatibility layer.

**Comment by wsfulton** [comment]
Related to #922 and #1645.

**Comment by KrisThielemans** [comment]
Unfortunately I still have these errors now that conda uses SWIG 4.1.0. I'll try to investigate this later but thought to update this issue. Links to errors in the conda-forge runs are in https://github.com/conda-forge/stir-feedstock/issues/60

**Comment by ojwb** [comment]
@KrisThielemans I don't see any changes in SWIG git since your fix was merged which look likely culprits.

I think adding a pypy CI job is really a priority as part of any further attempts to fix this - if you'd added one at the time we would (a) be sure that the initial fix actually worked and (b) have seen right away if a later commit broke this.
