### ISSUE TITLE
complex and other standard c++

### ISSUE THREAD

**Issue by TomCoalfish** [swig/swig#2268]
I have made interfaces for std::complex and am integrating other parts of c++ stl into swig interface to put in the library. Have alot of swigs for other libraries too if people want them.

**Comment by ojwb** [comment]
We have limited development resources so need to contain the scope of what SWIG aims to do, so we don't maintain wrappers for libraries other than the C and C++ standard libraries within the SWIG project (there are some boost smart pointer wrappers, but they're essentially the same as the wrappers for the standardised versions of those same smart pointers but in a different namespace so don't really add maintenance load).

In most cases a SWIG wrapper for another library is best maintained by the developers of that library or as its own project anyway.

If you have patches for standard C/C++ library features, please open PRs.  Please note they'll need documentation and test coverage to be accepted.

I should also point out that `std::complex` is already supported via `std_complex.i` for some languages (csharp, javascript, ocaml, python and ruby it looks like).
