### ISSUE TITLE
Swig doesn't generate PHP8 wrapper for openbabel 3.1.1

### ISSUE THREAD

**Issue by shanj-github** [swig/swig#2270]
When compiling openbabel 3.1.1 binding PHP8 with SWIG (current version 4.1), SWIG doesn't generate openbabel.php at all.

**Comment by cwolcott** [comment]
A little more insight from the question above.  Previously used SWIG 4.0.2 with PHP 7.4.27 to build openbabel.php from openbabel 3.1.1

**Comment by ojwb** [comment]
This isn't a bug - from `CHANGES.current`:

            [PHP] #1982 #1457 https://sourceforge.net/p/swig/bugs/1339/
            SWIG now only use PHP's C API to implement its wrappers, and no
            longer generates PHP code to define classes.  The wrappers should
            be almost entirely compatible with those generated before, but
            faster and without some previously hard-to-fix bugs.
            
            The main notable difference is SWIG no longer generates a .php
            wrapper at all by default (only if %pragma(php) code=... or
            %pragma(php) include=... are specified in the interface file).
            This also means you need to load the module via extension=...
            in php.ini, rather than letting the dl() in the generated
            .php wrapper load it (but dl() has only worked for command-line
            PHP for some years now).
