### ISSUE TITLE
python: can't return an object of a struct type that holds std::vector successfully

### ISSUE THREAD

**Issue by Rabahjamal** [swig/swig#2279]
Hi,

I'm using SWIG to wrap the following interface to python:

```C++
struct Data
{
    std::vector<float> vec;
};

Data run();
```

Now, I want to use this interface from python like this:
```python
def fun():
    output_data = run()
    return output_data.vec

def main():
    out = fun()
    print(list(out))
```
But, the output of the returned data is corrupted in this case. However, if I tried something like this:
```python
def fun():
    output_data = run()
    return output_data

def main():
    out = fun()
    print(list(out.vec))
```
it works without any issues.

Could anyone help me figure out why the second script works while the first one doesn't? And how can I make it work in both cases?

Thanks in advance!

**Comment by wsfulton** [comment]
Accessing member variables is via a pointer and is discussed in:
https://www.swig.org/Doc4.0/SWIGPlus.html#SWIGPlus_member_data
https://www.swig.org/Doc4.0/SWIG.html#SWIG_structure_data_members

In the second case the pointer is pointing to invalid memory as the struct has been garbage collected. Solutions are to copy the vector or keep a reference to the underlying structure.
