### ISSUE TITLE
argcargv.i - merge of PR #2275 #2276 

### ISSUE THREAD

**Issue by erezgeva** [swig/swig#2281]
When using argcargv.i,

The compiler warn in php, Perl5 and TCL:
`‘arg3’ may be used uninitialized in this function`

I understand why the `%typemap(default)` was removed from their argcargv.i.
And that `%typemap(default)` is generic.
But perhaps a remark in Doc/Manual/Library.html#Library_argcargv could help.

**Comment by wsfulton** [comment]
I can't get gcc to produce this warning. Which gcc and flags are you using and does it occur with the argcargvtest.i testcase? I suspect that it is a false positive warning by the compiler. You probably want to use the 'arginit' typemap rather than the 'default' typemap in any case.

**Comment by erezgeva** [comment]
Good remarks

I use:
`$ g++ --version`
`g++ (Debian 10.2.1-6) 10.2.1 20210110`

I test and add '-Wall' to compilation, But do not see any argN uninitialized warning.
`Examples/test-suite/php (master)$ make  argcargvtest.cpptest`
`Examples/test-suite/perl5 (master)$ make  argcargvtest.cpptest`
`Examples/test-suite/tcl (master)$ make  argcargvtest.cpptest`

Look on generated code, I can see the reason.
Though I use `SWIG Version 4.0.2`
The generated code is different.

Comparing Perl5 code:
### In test
`char **arg2 = (char **) 0 ;`

### In my project I see
`    char **arg3 ;`

This bug was probably fixed.
I will try to use  'arginit' typemap in my project, to support old swig.
Thanks for the support.
Sorry for my mistake, I should check with last swig.

**Comment by wsfulton** [comment]
No problem, thanks for clarifying.
