### ISSUE TITLE
is swig support c call go 

### ISSUE THREAD

**Issue by nice-cooker** [swig/swig#2285]
thanks

**Comment by wsfulton** [comment]
SWIG supports Go calling C/C++ code and limited calling of Go code from C. Can you expand your question please as to what you are looking for, perhaps you want callbacks from C to Go?

**Comment by nice-cooker** [comment]
thanks for the reply.
i mean, for example, a C function  do_op(int a, int b,   int (*op)(int, int))，i want to call do_op from Go with passing a go function as op param。

**Comment by wsfulton** [comment]
Look for callbacks in the documentation. Go example: https://github.com/swig/swig/tree/v4.0.2/Examples/go/funcptr. Alternatively read about the C++ director feature.
