### ISSUE TITLE
call __disown__() from generated python

### ISSUE THREAD

**Issue by alex4747-pub** [swig/swig#2287]
I have a director class that should never go away. If I explicitly call __disown()__ on the instance of the class it works fine.

```
app = MyApp()
app.__disown__()
```
However, I could not figure out a way to change my .i file to create a class with either thisown zero or to call __disown()__ from the generated __init__() method. I hope it is possible.

**Comment by ojwb** [comment]
Have you tried monkey patching?  Something like:

```
MyApp.orig__init__ = MyApp.__init__
def x(self):
    self.orig__init__(); self.__disown__()
MyApp.__init__ = x
```

**Comment by ojwb** [comment]
You could use `%pythoncode` to inject the extra code into the SWIG generated `.py` wrapper so it just works for a user of the bindings.

**Comment by alex4747-pub** [comment]
I could not figure out how to do it with %pythoncode.

It seems so simple and common need that I am really surprised that there is no simple way to achieve it.

In the meantime, I added a sed step to my makefile to patch the __init__ function in generated .py. It looks ugly and I would prefer to avoid it.

**Comment by ojwb** [comment]
Just realised `%pythonappend` allows doing this cleanly and more simply:

```
%pythonappend MyApp::MyApp {
    self.__disown__()
}
```

**Comment by alex4747-pub** [comment]
Did not work for me. I used the following code, it was simply ignored with no messages emitted
```
%pythonappend MyApp::MyApp() %{
    self.thisown = 0
%}

%pythonappend MyApp::MyApp(char const*) %{
    self.thisown = 0
 %}
 
 I found StackOverflow discussion, it did not help much either https://stackoverflow.com/questions/50259152/adding-swig-pythoncode-to-set-thisown-flag-on-python-object. Is it possible to get a working example, I would say that this need is a pretty basic one.

**Comment by ojwb** [comment]
Glad you got it working.

FWIW, it seems to work after the class definition for me, e.g. with this patch to the `callback` example:

```
diff --git a/Examples/python/callback/example.i b/Examples/python/callback/example.i
index cf61ef9d..7e191b04 100644
--- a/Examples/python/callback/example.i
+++ b/Examples/python/callback/example.i
@@ -9,3 +9,6 @@
 
 %include "example.h"
 
+%pythonappend Callback::Callback {
+    self.thisown = 0 # XXX
+}
```

Run `make` and:

```
$ grep -B15 XXX example.py
class Callback(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _example.delete_Callback

    def run(self):
        return _example.Callback_run(self)

    def __init__(self):
        if self.__class__ == Callback:
            _self = None
        else:
            _self = self
        _example.Callback_swiginit(self, _example.new_Callback(_self, ))

        self.thisown = 0 # XXX
```

(The `XXX` was just so I could easily pick out this addition easily.)

**Comment by alex4747-pub** [comment]
In my case I have %include and %extend for my class, if put %pythonappend before %include it works, if I put it anywhere else (between %include and %extend, inside %extend,  after %extend) it is silently ignored
