### ISSUE TITLE
Can't parse `int mlockall(int);` ?

### ISSUE THREAD

**Issue by yay** [swig/swig#2288]
For example:

`./swig -javascript -node /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/sys/mman.h`

prints

`/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/sys/mman.h:231: Error: Syntax error in input(1).`

where line 23 is simply:

`int     mlockall(int);`

Full `mman.h` source: https://gist.github.com/yay/d7a32051efca6460f497f58581ba8e9f

**Comment by ojwb** [comment]
It's` __BEGIN_DECLS` on the line just above there that's the problem.  That's a valid identifier at least, but an identifier followed by `int` is a syntax error, which gets reported on the `int`.

Add `-D__BEGIN_DECLS=` and SWIG gets further (the next problem is `__DARWIN_ALIAS` on line 238).

Note that SWIG doesn't follow `#include` so won't find a definition of `__BEGIN_DECLS` in an included header.

**Comment by ojwb** [comment]
You can run swig with `-includeall` and it will then follow all `#include` statements, but I've never found the resulting behaviour to be useful if any system headers get included as they almost inevitably use some non-standard constructs which SWIG doesn't understand.  Resolving the includes to make a single file to pass to SWIG will tend to suffer from the same problem.

If you just picked this header as an experiment to explore using SWIG, there are probably better choices for that.

If you're really trying to wrap `sys/mman.h` to use it then defining the macros to suitably values (often empty) as above is probably going to be the least painful approach.

**Comment by yay** [comment]
Thank you. Yes, I picked both `sys/mman.h` and JavaScript as an experiment. My interest is actually a new target language.
