### ISSUE TITLE
undefined reference to `wasm_runtime_full_init

### ISSUE THREAD

**Issue by oznfc** [swig/swig#2296]
Hi , I want to use wasmer so ı added  ```wasm_export.h``` library.   but  I'm getting this error 
```undefined reference to `wasm_runtime_full_init ```. How can ı add  functions from another ```...h```?

**Comment by ojwb** [comment]
You've not really provided much to go on, but based on what you have this really isn't anything to do with SWIG.

The error suggests you haven't linked to whatever library provides `wasm_runtime_full_init`.  I'm not familiar with wasmer so I've no idea what library that might be called - you probably need to read the wasmer, docs, or ask its developers for help if the docs don't say.
