### ISSUE TITLE
 ‘register’ storage class specifier issue for c++17

### ISSUE THREAD

**Issue by break2make** [swig/swig#2302]
I'm getting the following error during compilation swig 4.0.2 generated .cc code with g++ with -std=c++17 option:

error: ISO C++17 does not allow ‘register’ storage class specifier [-Werror=register]
  564 |  register size_t i = (l + r) >> 1;

How to resolve this issue for TCL extension?

**Comment by wsfulton** [comment]
As far as I can see, swig-4.0.2 does not generate any code using the `register` keyword. It probably comes from your own interface code or perhaps from the TCL headers.

**Comment by ojwb** [comment]
Indeed, this isn't coming from SWIG 4.0.2.

If it's in your interface file, just drop `register` - it's pointless when it comes to code gen with modern compilers.

Tcl 8.5 and 8.6 headers don't seem to use `register` either, but it's pretty plausible some older Tcl headers did.  If you're stuck with an older Tcl version which uses this then you can pass `-Wno-register` to the compiler when using GCC or clang to disable this warning/error.  You could instead disable it from your interface file with a `#pragma`:

```
#pragma GCC diagnostic ignored "-Wregister"
```
