### ISSUE TITLE
Use a better hash function?

### ISSUE THREAD

**Issue by ojwb** [swig/swig#2303]
I noticed the current hash function is ... odd:

```
static int String_hash(DOH *so) {
  String *s = (String *) ObjData(so);
  if (s->hashkey >= 0) {
    return s->hashkey;
  } else {
    char *c = s->str;
    unsigned int len = s->len > 50 ? 50 : s->len;
    unsigned int h = 0;
    unsigned int mlen = len >> 2;
    unsigned int i = mlen;
    for (; i; --i) {
      h = (h << 5) + *(c++);
      h = (h << 5) + *(c++);
      h = (h << 5) + *(c++);
      h = (h << 5) + *(c++);
    }
    for (i = len - (mlen << 2); i; --i) {
      h = (h << 5) + *(c++);
    }
    h &= 0x7fffffff;
    s->hashkey = (int)h;
    return h;
  }
}
```

So we limit the length of the string data that's hashed to 50 bytes, then process 4 bytes at a time as an optimisation, and then the last few bytes individually.  The optimisation doesn't affect the result.

But we purely shift and add, and mask the result to 31 bits, so if we process more than 6 bytes, only the last 6 affect the result AFAICS.  That seems likely to cause a lot of collisions in practice given the names actually used - e.g. `symtab` and `sym:symtab` will collide, anything ending `:noblock` will collide, etc.  Only the bottom bit of the 6th byte from last matters too, which makes this worse.

More typically for a hash function of this style is to mix the high bits back into the low ones, e.g. https://en.wikipedia.org/wiki/PJW_hash_function

(The current optimisation actually seems a bit silly as we could just process exactly 6 bytes in the majority of cases, instead of trying to efficiently batch process up to 50!)

Adding a line to print the computed value I get 93724 hash computations from an example run of SWIG.  There are 2209 different byte sequences hashed (that's with the clamping to 50 bytes) but only 1345 different hash values.  I looked at how many different clamped byte sequences gave each hash value, and the worst one is a 30-way collision - out of interested I checked what this was and it is:

```
SWIGWARN_CSHARP_TYPEMAP_CLASSMOD_UNDEF hash is 1131944166
SWIGWARN_CSHARP_TYPEMAP_CSCONSTRUCT_UNDEF hash is 1131944166
SWIGWARN_CSHARP_TYPEMAP_CSDIRECTORIN_UNDEF hash is 1131944166
SWIGWARN_CSHARP_TYPEMAP_CSDIRECTOROUT_UNDEF hash is 1131944166
SWIGWARN_CSHARP_TYPEMAP_CSIN_UNDEF hash is 1131944166
SWIGWARN_CSHARP_TYPEMAP_CSOUT_UNDEF hash is 1131944166
SWIGWARN_CSHARP_TYPEMAP_GETCPTR_UNDEF hash is 1131944166
SWIGWARN_D_TYPEMAP_CLASSMOD_UNDEF hash is 1131944166
SWIGWARN_D_TYPEMAP_DCONSTRUCTOR_UNDEF hash is 1131944166
SWIGWARN_D_TYPEMAP_DDIRECTORIN_UNDEF hash is 1131944166
SWIGWARN_D_TYPEMAP_DIN_UNDEF hash is 1131944166
SWIGWARN_D_TYPEMAP_DOUT_UNDEF hash is 1131944166
SWIGWARN_JAVA_TYPEMAP_CLASSMOD_UNDEF hash is 1131944166
SWIGWARN_JAVA_TYPEMAP_GETCPTR_UNDEF hash is 1131944166
SWIGWARN_JAVA_TYPEMAP_JAVACONSTRUCT_UNDEF hash is 1131944166
SWIGWARN_JAVA_TYPEMAP_JAVADIRECTORIN_UNDEF hash is 1131944166
SWIGWARN_JAVA_TYPEMAP_JAVADIRECTOROUT_UNDEF hash is 1131944166
SWIGWARN_JAVA_TYPEMAP_JAVAIN_UNDEF hash is 1131944166
SWIGWARN_JAVA_TYPEMAP_JAVAOUT_UNDEF hash is 1131944166
SWIGWARN_PARSE_EXTEND_UNDEF hash is 1131944166
SWIGWARN_PARSE_TEMPLATE_SP_UNDEF hash is 1131944166
SWIGWARN_TYPEMAP_CONST_UNDEF hash is 1131944166
SWIGWARN_TYPEMAP_DIRECTORIN_UNDEF hash is 1131944166
SWIGWARN_TYPEMAP_DIRECTOROUT_UNDEF hash is 1131944166
SWIGWARN_TYPEMAP_IN_UNDEF hash is 1131944166
SWIGWARN_TYPEMAP_OUT_UNDEF hash is 1131944166
SWIGWARN_TYPEMAP_UNDEF hash is 1131944166
SWIGWARN_TYPEMAP_VARIN_UNDEF hash is 1131944166
SWIGWARN_TYPEMAP_VAROUT_UNDEF hash is 1131944166
SWIGWARN_TYPEMAP_VAR_UNDEF hash is 1131944166
```

And the second worst was:

```
%cleardelobject hash is 1683398868
%clearrefobject hash is 1683398868
%clearunrefobject hash is 1683398868
%delobject hash is 1683398868
%nodelobject hash is 1683398868
%norefobject hash is 1683398868
%nounrefobject hash is 1683398868
%refobject hash is 1683398868
%unrefobject hash is 1683398868
*::SwigPtr_PyObject hash is 1683398868
*::SwigVar_PyObject hash is 1683398868
PyObject hash is 1683398868
SWIG_Object hash is 1683398868
SwigPtr_PyObject hash is 1683398868
SwigVar_PyObject hash is 1683398868
VOID_Object hash is 1683398868
object hash is 1683398868
p.PyObject hash is 1683398868
p.p.PyObject hash is 1683398868
r.q(const).SwigPtr_PyObject hash is 1683398868
r.q(const).SwigVar_PyObject hash is 1683398868
r.q(const).p.PyObject hash is 1683398868
r.q(const).swig::SwigPtr_PyObject hash is 1683398868
r.q(const).swig::SwigVar_PyObject hash is 1683398868
swig::PyObject hash is 1683398868
swig::SwigPtr_PyObject hash is 1683398868
swig::SwigVar_PyObject hash is 1683398868
```

There are over 2 billion possible hash values so I'd expect very few collisions - e.g. with the DJB hash function (https://theartincode.stanis.me/008-djb2/) I get zero collisions with this example.

I think it would be best to pick a well known existing string hash function with good properties instead.  The [DJB one](https://theartincode.stanis.me/008-djb2/) seems to be well regarded, and is only one extra integer addition per character compared to the current function (plus a constant load for the initial value rather than 0 which is typically cheaper to load), so I'd propose that.  (I actually wonder if someone was trying to implement the DJB hash here from memory but missed the `+ h`!)

As to what different this makes it practice, I tried timing SWIG on a random testsuite case for Python:

```
env SWIG_LIB=../../../Lib time ../../../swig -python -c++ -outcurrentdir -I../../../Examples/test-suite -o li_std_list_wrap.cxx ./../li_std_list.
```

This seems to show about a 4% reduction in wallclock time.  It's quite noisy, but there's almost no overlap in the ranges of times I get with the current and with the DJB hash functions so there seems a clear improvement.

Using 0 instead of 5381 for the initial value seems to work similarly well too, which is more similar to the existing hash function.  I think the 5381 initial value choice helps spread out the hash values more, which can help in some situations (e.g. if linear probing is used after a collision) - it looks like SWIG has a chain of entries in each hash bucket, and each hash starts with 7 buckets with the hash value reduced modulo the number of buckets, so spreading out the hash values probably doesn't help.

@wsfulton Thoughts?

**Comment by wsfulton** [comment]
Hi @ojwb, are you getting notifications about Github Action failures for your commits? Master has been red for 4 days, apparently due to 5a96a39, wondering if you're looking at this?

**Comment by ojwb** [comment]
I do get notification emails, but they really aren't very useful as failure just says "CI: Some jobs were not successful"  and then just lists the first 10 jobs, which are never the ones which failed unless the build is totally broken.

Combine that with minor flakiness in some of the 100+ jobs resulting in a lot of bogus CI failures means it's all too easy to miss breakage.

I'd even seen some Java and Python jobs were failing, but hadn't guessed it might be this change that caused it.

So thanks for the ping.  I'll take a look.

**Comment by ojwb** [comment]
I looked at the failure of multiple_inheritance_interfaces for Java and it looks to me like that is must be a latent bug due to the order of hash iteration (or something similar) mattering, and it just happens to work for the cases exercised by the testsuite with the old hash function.

I eliminated the new hash function from the picture, and found just patching the old hash version to use a different initialiser for the hash value is enough to break this testcase:

```
--- a/Source/DOH/string.c
+++ b/Source/DOH/string.c
@@ -182,7 +182,7 @@ static int String_hash(DOH *so) {
   } else {
     char *c = s->str;
     unsigned int len = s->len > 50 ? 50 : s->len;
-    unsigned int h = 0;
+    unsigned int h = 1;
     unsigned int mlen = len >> 2;
     unsigned int i = mlen;
     for (; i; --i) {
```

Comparing generated files for this one testcase from git master with the hash change reverted and that plus the hash initialiser change above:

```
diff -ru base/multiple_inheritance_interfaces/multiple_inheritance_interfacesJNI.java multiple_inheritance_interfaces/multiple_inheritance_interfacesJNI.java
--- base/multiple_inheritance_interfaces/multiple_inheritance_interfacesJNI.java	2022-07-12 11:04:28.927050321 +1200
+++ multiple_inheritance_interfaces/multiple_inheritance_interfacesJNI.java	2022-07-12 11:05:04.975084910 +1200
@@ -69,6 +69,8 @@
   public final static native void delete_W(long jarg1);
   public final static native void delete_UndesirablesSwigImpl(long jarg1);
   public final static native void UndesirablesSwigImpl_Method(long jarg1, Undesirables jarg1_, int jarg2);
+  public final static native int UndesirablesSwigImpl_UndesiredEnum1_get();
+  public final static native int UndesirablesSwigImpl_UndesiredEnum2_get();
   public final static native void UndesirablesSwigImpl_UndesiredStaticMethod(int jarg1);
   public final static native void UndesirablesSwigImpl_UndesiredVariable_set(long jarg1, Undesirables jarg1_, int jarg2);
   public final static native int UndesirablesSwigImpl_UndesiredVariable_get(long jarg1, Undesirables jarg1_);
diff -ru base/multiple_inheritance_interfaces/multiple_inheritance_interfaces_wrap.cxx multiple_inheritance_interfaces/multiple_inheritance_interfaces_wrap.cxx
--- base/multiple_inheritance_interfaces/multiple_inheritance_interfaces_wrap.cxx	2022-07-12 11:04:28.927050321 +1200
+++ multiple_inheritance_interfaces/multiple_inheritance_interfaces_wrap.cxx	2022-07-12 11:05:04.975084910 +1200
@@ -1024,6 +1024,30 @@
 }
 
 
+SWIGEXPORT jint JNICALL Java_multiple_1inheritance_1interfaces_multiple_1inheritance_1interfacesJNI_UndesirablesSwigImpl_1UndesiredEnum1_1get(JNIEnv *jenv, jclass jcls) {
+  jint jresult = 0 ;
+  Undesirables::UndesiredEnum result;
+  
+  (void)jenv;
+  (void)jcls;
+  result = (Undesirables::UndesiredEnum)Undesirables::UndesiredEnum1;
+  jresult = (jint)result; 
+  return jresult;
+}
+
+
+SWIGEXPORT jint JNICALL Java_multiple_1inheritance_1interfaces_multiple_1inheritance_1interfacesJNI_UndesirablesSwigImpl_1UndesiredEnum2_1get(JNIEnv *jenv, jclass jcls) {
+  jint jresult = 0 ;
+  Undesirables::UndesiredEnum result;
+  
+  (void)jenv;
+  (void)jcls;
+  result = (Undesirables::UndesiredEnum)Undesirables::UndesiredEnum2;
+  jresult = (jint)result; 
+  return jresult;
+}
+
+
 SWIGEXPORT void JNICALL Java_multiple_1inheritance_1interfaces_multiple_1inheritance_1interfacesJNI_UndesirablesSwigImpl_1UndesiredStaticMethod(JNIEnv *jenv, jclass jcls, jint jarg1) {
   Undesirables::UndesiredEnum arg1 ;
   
diff -ru base/multiple_inheritance_interfaces/UndesirablesSwigImpl.java multiple_inheritance_interfaces/UndesirablesSwigImpl.java
--- base/multiple_inheritance_interfaces/UndesirablesSwigImpl.java	2022-07-12 11:04:28.915050310 +1200
+++ multiple_inheritance_interfaces/UndesirablesSwigImpl.java	2022-07-12 11:05:04.963084898 +1200
@@ -65,8 +65,8 @@
   }
 
   public final static class UndesiredEnum {
-    public final static UndesirablesSwigImpl.UndesiredEnum UndesiredEnum1 = new UndesirablesSwigImpl.UndesiredEnum("UndesiredEnum1");
-    public final static UndesirablesSwigImpl.UndesiredEnum UndesiredEnum2 = new UndesirablesSwigImpl.UndesiredEnum("UndesiredEnum2");
+    public final static UndesirablesSwigImpl.UndesiredEnum UndesiredEnum1 = multiple_inheritance_interfacesJNI.UndesirablesSwigImpl_UndesiredEnum1_get();
+    public final static UndesirablesSwigImpl.UndesiredEnum UndesiredEnum2 = multiple_inheritance_interfacesJNI.UndesirablesSwigImpl_UndesiredEnum2_get();
 
     public final int swigValue() {
       return swigValue;
```

I had a look at `java.cxx` and didn't spot an obvious culprit there, but I've really no idea what's going on in detail.  It could also be happening somewhere in non-backend specific code too.

I'll revert the hash change for now, but having successful code generation depend on the hash iteration order is clearly undesirable as it's brittle and liable to fail for some inputs.  Perhaps that is better looked at by you as I'm not familiar with the Java backend (nor the Python `-builtin` support).

**Comment by wsfulton** [comment]
Mmm, interesting, I'll take a look.

**Comment by wsfulton** [comment]
Today I only got as far as replicating the problem changing the original hash algorithm for h from 0 to 1. If you run `swig -debug-module 1` you can see that `feature:java:enum - "typesafe"` is missing from the parse tree when h=1. This points to something going wrong in attaching the features to the parse tree in parser.y, so I'll try debug that tomorrow. naming.c has the code to attach features and setting SWIG_DEBUG in those files didn't show any diffs in the debug output. I see `Swig_feature_set: '' '' 'feature:java:enum' 'typesafe'` in the debug output, so could be something wrong in Swig_feature_set.

**Comment by wsfulton** [comment]
I debugged the problem to `features_get` in naming.c to failing to return a feature for an empty string. The cause being an empty string being inconsistent in the hash being returned. The hash should be consistent. Using this to diagnose:
```patch
diff --git a/Source/DOH/string.c b/Source/DOH/string.c
index 543c3e3f8..a863264e8 100644
--- a/Source/DOH/string.c
+++ b/Source/DOH/string.c
@@ -178,11 +178,12 @@ static int String_equal(DOH *so1, DOH *so2) {
 static int String_hash(DOH *so) {
   String *s = (String *) ObjData(so);
   if (s->hashkey >= 0) {
+Printf(stdout, "hash %d '%s' (early)\n", s->hashkey, so);
     return s->hashkey;
   } else {
     char *c = s->str;
     unsigned int len = s->len > 50 ? 50 : s->len;
-    unsigned int h = 0;
+    unsigned int h = 1;
     unsigned int mlen = len >> 2;
     unsigned int i = mlen;
     for (; i; --i) {
@@ -196,6 +197,7 @@ static int String_hash(DOH *so) {
     }
     h &= 0x7fffffff;
     s->hashkey = (int)h;
+Printf(stdout, "hash %d '%s' (late)\n", h, so);
```
and then running the following to show the two different hashes being returned for '':
```
~/swig/github/swig/Examples/test-suite/java ((216c7f72c...) *)$ make multiple_inheritance_interfaces.cpptest | grep "^hash " | sort | uniq | grep "''"
./UndesirablesSwigImpl.java:68: error: incompatible types: int cannot be converted to UndesiredEnum
    public final static UndesirablesSwigImpl.UndesiredEnum UndesiredEnum1 = multiple_inheritance_interfacesJNI.UndesirablesSwigImpl_UndesiredEnum1_get();
                                                                                                                                                      ^
./UndesirablesSwigImpl.java:69: error: incompatible types: int cannot be converted to UndesiredEnum
    public final static UndesirablesSwigImpl.UndesiredEnum UndesiredEnum2 = multiple_inheritance_interfacesJNI.UndesirablesSwigImpl_UndesiredEnum2_get();
                                                                                                                                                      ^
2 errors
make: *** [multiple_inheritance_interfaces.cpptest] Error 1
hash 0 '' (early)
hash 1 '' (early)
hash 1 '' (late)
```
Fixing the cause (to not assume the hash is 0 for an empty string):
```diff
@@ -1182,7 +1184,7 @@ DOHString *DohNewString(const DOHString_or_char *so) {
 DOHString *DohNewStringEmpty(void) {
   int max = INIT_MAXSIZE;
   String *str = (String *) DohMalloc(sizeof(String));
-  str->hashkey = 0;
+  str->hashkey = -1;
   str->sp = 0;
   str->line = 1;
   str->file = 0;
```
Fixes the testcase.

However, with the new hash calc in 5a96a39aa48fe35fa0bd0b92f5fb5615447ea6e8, an empty string results in a hash of -1 and repeated re-calculations of the hash. @ojwb over to you to please to tweak the hash algorithm calc again.

**Comment by ojwb** [comment]
Aha, that all makes sense. Thanks for resolving the mystery. Happy to take
it from here.

**Comment by ojwb** [comment]
I've poked this a bit and you're right for my simplified case of just changing the initialiser for the old hash to 1 breaking because of this assumption elsewhere that the hash of an empty string is 0.

However, if I apply the first patch above, revert the hash initialiser to 0, and cherry-pick 5a96a39aa48fe35fa0bd0b92f5fb5615447ea6e8 then:

```
olly@gemse:~/git/swig/Examples/test-suite/java$ make multiple_inheritance_interfaces.cpptest|grep "hash .* ''"|sort|uniq -c
Exception in thread "main" java.lang.RuntimeException: Expected interfaces for multiple_inheritance_interfaces.L: 
[interface multiple_inheritance_interfaces.IJ, interface multiple_inheritance_interfaces.IK, interface multiple_inheritance_interfaces.IL]
Actual interfaces: 
[interface multiple_inheritance_interfaces.IL, interface multiple_inheritance_interfaces.IJ, interface multiple_inheritance_interfaces.IK]
	at multiple_inheritance_interfaces_runme.checkBaseAndInterfaces(multiple_inheritance_interfaces_runme.java:23)
	at multiple_inheritance_interfaces_runme.main(multiple_inheritance_interfaces_runme.java:58)
make: *** [Makefile:91: multiple_inheritance_interfaces.cpptest] Error 1
    201 hash 0 '' (early)
      7 hash 0 '' (late)
```

So the new hash function as applied still gives a hash of 0 for an empty string.

> However, with the new hash calc in https://github.com/swig/swig/commit/5a96a39aa48fe35fa0bd0b92f5fb5615447ea6e8, an empty string results in a hash of -1 and repeated re-calculations of the hash. @ojwb over to you to please to tweak the hash algorithm calc again.

I see how this can happen - as above the hash of an empty string is `0` still, but also there's a `h &= 0x7fffffff;` before assigning to `s->hashkey` so even if the calculated hash were `-1`, we'd actually store `0x7fffffff` and not repeatedly recalculate.

Applying the second patch to not assume the hash of an empty string is 0 does fix my simplified reproducer, but applying it along with the new hash calculation this java testcase still fails.

I did a grep for `hashkey.*=` and there don't seem to be any other cases assuming particular hash values, so I think there's still an assumption about hash iteration order or similar somewhere.

**Comment by ojwb** [comment]
I tried with `swig -debug-module 1` like you did above both with and without the "hash is always 0" change. Address randomisation means the addresses aren't the same in the debug output, but after `:%s/0x7......../0xZZZZZZZZZZ` on both, the two outputs are bit for bit identical.

Both `make check-python-test-suite` and `check-php-test-suite` pass with this new reduced version.

**Comment by wsfulton** [comment]
Looking at the diffs in the generated code for Java there is a change in the order of the generated interfaces when using multiple inheritance and the %interface family of macros. The ordering comes out wrong, but probably I can get to grips with that easily enough using a List instead (which has a defined ordering).

There are tons of diffs in Python, notably also an ordering change, this time in the runtime structures. I'm not comfortable with this change really as it is a very sensitive area and not one that I'd say I understand all the consequences of the change in ordering without a good look at it.

But before I start looking at it, I'm trying to understand the current ordering guarantees or more likely unintended ordering consequences. From what you've said the current algorithm has a high number of collisions, and from what I can make out in Hash_setattr, collisions result in nodes being added into a linked list in the collided bucket. So iterating over the entire hash table is likely to give a sort of defined order depending on the order that the strings were added to the hash table as a linked list gives an ordering depending on the order added, whereas the ordering from the independent hash buckets is pretty random. Anyway, just dumping my thoughts out there before diving into the code. Seem reasonable logic?

**Comment by ojwb** [comment]
My understanding of the code is that the hash key is reduced modulo the number of buckets to determine which bucket to add an element to.  The number of buckets in each Hash starts at 7 and increases by `s=s*2+1`when the number of elements reaches double the current number of buckets.  Iteration runs over each element in the first bucket in chained order, then each element in the second in chained order, etc.

As you say, setting the hashkey to zero always forces everything into a single bucket, so there we'll iterate in the order items were added to the hash.

In the existing code on master with a lot of collisions, the colliding elements will iterate in order of being added, with other elements which map to the same bucket potentially interspersed.

With the new hash function, there are fewer (often no) collisions on hashkey, but items can still map to the same bucket due to the modulo.  I think the significant change is really that items will map to different hash buckets so the iteration order isn't the same.

So there aren't really ordering guarantees for iterating a DOH Hash.  Perhaps you can assume that iterating a second time without any intervening additions of items will give the same order.  If you add items the number of hash buckets may change, and then all the items get redistributed across the new buckets, so the iteration order is likely to change.

The iteration order is presumably deterministic independent of the number of hashkey (or modulo bucket) collisions - for a given sequence of items added to the hash in the same order, the order of iteration should be the same.  Changing the hash function will give a different order, but it's still going to be deterministic for any hash function (since the hash function needs to be deterministic to work).

It all seems worrying brittle - I suspect it's possible to take one of these testcases that fail with the new hash function and tweak it to fail with SWIG 4.0.2 (either by renaming things, or changing the order of things in the input), though I haven't tried.  I also wonder if addressing this will resolve some of the bug pile.

Perhaps once this is fixed it's worth having some sort of "smoker" build where the hashing is perturbed differently each time to try to catch any introduction of similar problems.

**Comment by wsfulton** [comment]
7592722e39a7595d20d2d81a5bc1f9eb91f2e35b has modified the interface to use a Hash instead of a List so that the order of the generated interfaces is deterministic and is now in the same order as the multiple base classes are declared in C++. The C++ base classes were actually stored as a list and then added to, but stored as a hash, so keeping to lists throughout makes sense.

The test-suite ought to pass now pass with the new hash algorithm. However, please let me try and understand the consequences of the ordering change in the runtime before committing it again.

I'm not sure the benefits of smoker builds to test different hash algorithms is worth the effort, there's always more testing to be done and this seems like low priority to me.

**Comment by ojwb** [comment]
> The test-suite ought to pass now pass with the new hash algorithm. However, please let me try and understand the consequences of the ordering change in the runtime before committing it again.

Sure - the patch gives a nice little speed-up, but I think the important thing here is to root out where the generated code depends on hash iteration order, since that's liable to result in bugs.

I'll open a WIP PR for it so we can see if there are any further problems in the testsuite at least.

**Comment by wsfulton** [comment]
I've fixed the ordering problems in the type tables, see 3bf1da429...15b2ec53e. @ojwb, feel free to re-apply af263e2623bba7111d1fba80d7ee1ef2b884cc01.

**Comment by ojwb** [comment]
Good stuff.

af263e2623bba7111d1fba80d7ee1ef2b884cc01 doesn't seem to be a valid commit hash, but I assume you must mean the reverted commit, i.e. 5a96a39aa48fe35fa0bd0b92f5fb5615447ea6e8

(Looks like I didn't get around to a WIP PR.)
