### ISSUE TITLE
swig is not on PyPI

### ISSUE THREAD

**Issue by andreatramacere** [swig/swig#2304]
I remember that in the past I was able to `pip install swig`. Now , it looks like that. the package is not there anymore.
I can install it from conda. Is there anything that I am missing?
Thanks

**Comment by wsfulton** [comment]
The SWIG project does not build any packages. Best to ask the PyPI community who own them.

My own opinion is that Conda is a general package manager and would be a suitable place to obtain SWIG, whereas pip is for installing Python packages. SWIG is not a Python package and hence should not be available as a pip package.
