### ISSUE TITLE
%immutable not working for struct members?

### ISSUE THREAD

**Issue by Schmiedwerk** [swig/swig#2306]
Using` %immutable foo::bar;` prior to a struct

```
typedef struct {
    int bar;
} foo;
```

does not seem to work when wrapping for Python. Is this intentional or a bug?

**Comment by wsfulton** [comment]
`%immutable` is a SWIG feature directive and SWIG does not use typedefs for feature matching. The real type name must be used. In this case this is challenging as the struct is unnamed. Easiest is not use unnamed structs, but given that might require you modifying code you cannot, the workaround is to use either `%immutable foo`, which will, according to the matching rules, make all members in all structs with the name bar immutable. The next best is to use the C++ global scope operator `%immutable ::foo` to target all structs with unnamed members called bar (as well of course as a global variable called bar). 

You can also use `%clearimmutable` to remove this feature from affecting other types, such as bar in Thing below.
```
%immutable ::bar;

%inline %{
typedef struct {
    int bar;
} foo;
%}

%clearimmutable ::bar;

%inline %{
typedef struct {
    int bar;
} Thing;
%}
```
