### ISSUE TITLE
Change value of $1/2/* in nested typedef possible?

### ISSUE THREAD

**Issue by Basskrapfen** [swig/swig#2308]
Hi,

is it possible to change the value of $1/2/... for nested typedef? I would like to reuse existing typedefs by embedding them. Same is for $result.

Here is an example:
```
%typemap(out) std::optional<TYPE>, const std::optional<TYPE>& %{
    if ($1.has_value()) {
        $typemap(out, NESTED_TYPE)  // error as $1 is not of TYPE but of std::optional<TYPE>
    } else {
        $result = nullptr;
    }
%}
```

Is something like this possible?
`$typemap(out, NESTED_TYPE) ($1 = "$1_unwrapped")`

Here is the workaround I've found using a lambda to hide and re-add $1, but this is not very nice.
```
%typemap(out) std::optional<TYPE>, const std::optional<TYPE>& %{
    if ($1.has_value()) {
        [jenv, &$result](NESTED_TYPE $1) $typemap(out, NESTED_TYPE)($1.value());
    } else {
        $result = nullptr;
    }
%}
```

Thanks and regards

**Comment by wsfulton** [comment]
Is NESTED_TYPE a typo, should this be TYPE??

**Comment by Basskrapfen** [comment]
> Is NESTED_TYPE a typo, should this be TYPE??

NESTED_TYPE is correct here. I'm using, as example, a std::optional<std::string> as type. The nested type is std::string for which I want to reuse the typemap which already exists in SWIG. But of course the existing std::string typemap expects $1 to be std::string too. So I need to somehow give the existing typemap a different $1 to use which has the correct type.

**Comment by ojwb** [comment]
So where is `NESTED_TYPE` coming from?

It would help a lot to provide a complete example of what you're attempting rather than just this single `out` typemap.

**Comment by ojwb** [comment]
I think the answer the original question here is "no" as it doesn't seem to be "possible to change the value of $1/2/... for nested typedef".  The documentation for `$typemap` says:

> The special variables within the matched typemap are expanded into those for the matched typemap type, 
not the typemap within which the macro is called.

Without a complete example it's hard to provide useful advice here, but you seem to have found a workaround at least.

**Comment by wsfulton** [comment]
Thread died, closing.
