### ISSUE TITLE
Certain trailing return types fail to parse

### ISSUE THREAD

**Issue by allanleal** [swig/swig#231]
The following trailing return  type usage cannot be parsed be `swig 3.0.2`.

**example.hpp**

```
#pragma once

struct Hello
{
    auto output() -> Hello&;
};
```

**example.cpp**

```
#include "example.hpp"
#include <iostream>

auto Hello::output() -> Hello&
{
    std::cout << "Hello" << std::endl;
    return *this;
}
```

**example.i**

```
%module example
%{
#include "example.hpp"
%} 
%include "example.hpp"
```

This code causes the following error with swig: `Error: Syntax error in input(3).`, where the error line is `auto output() -> Hello&;`.

If instead I write `Hello& output();`, then no errors occur.

**Comment by ojwb** [comment]
It looks like the parser doesn't handle returning a reference in this way.

**Comment by ojwb** [comment]
This patch does at least make it parse, but I don't have time right now to check it actually works and to sort out a testcase.  Putting this here in case anyone else wants to look, so as to avoid duplicated effort:

```
diff --git a/Source/CParse/parser.y b/Source/CParse/parser.y
index 5e4dc24..240d6e3 100644
--- a/Source/CParse/parser.y
+++ b/Source/CParse/parser.y
@@ -3071,6 +3071,7 @@ cpp_alternate_rettype : primitive_type { $$ = $1; }
               | TYPE_TYPEDEF template_decl { $$ = NewStringf("%s%s",$1,$2); }
               | TYPE_RAW { $$ = $1; }
               | idcolon { $$ = $1; }
+              | idcolon AND { $$ = NewStringf("%s&",$1); }
               | decltype { $$ = $1; }
               ;
 
```

I suspect references (and probably pointers) may also need adding for other cases.
