### ISSUE TITLE
can not import the generated module

### ISSUE THREAD

**Issue by zhang-qiang-github** [swig/swig#2312]
I have generated a python module that wrapping up some c++ code. The code is a toy:

```
// example.h
#ifndef example_header_h
#define example_header_h

class try_class
{
public:
    try_class();
    void class_func(int a);
};

#endif

// example.cpp

#include "example.h"
#include <iostream>
try_class::try_class()
{
    std::cout << "try class" << std::endl;
}

void try_class::class_func(int a)
{
   
}

// example.i
%module example

%{
#include "example.h"
%}
%include "example.h"
```
The compiling is ok. Then, I collect `example.py`, `_example.pyd` in a folder. In this folder, I open a python interpreter.

When I import `example`, a bug is reported:

```
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import example
Fatal Python error: _PyInterpreterState_GET: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: unknown
```

My environment is:
```
win 10
vs 2022
CMake 3.22.1
swig 4.0.2
python 3.10.5
```

**Comment by ojwb** [comment]
A web search for your error message suggests the problem might be a mismatch in debug settings between your module and the Python interpreter being used:

https://stackoverflow.com/questions/67007843/python3-c-module-exception-gil-not-held

**Comment by wsfulton** [comment]
No response, closing.

You can also use the Visual Studio project files in Examples\python.
