### ISSUE TITLE
swig cannot wrap exported c++ file into python

### ISSUE THREAD

**Issue by zhang-qiang-github** [swig/swig#2313]
I am using swig to wrap c++ into python.

My PackA.h is:
```
#ifndef PACKA_HEADER_H
#define PACKA_HEADER_H

#include <string>
class  PackA
{
public:
    PackA();

};

#endif
```
And my PackA.i is:
```
%module PackA

%{
#define SWIG_FILE_WITH_INIT
#include "PackA.h"
%}
%include "PackA.h"
```
It successfully generate python module.

However, if I declare PackA to dll by:

```
// #include "PackAGlobal.h"

#ifndef PACKA_EXPORTES_H
#define PACKA_EXPORTES_H

#if (WIN32)
    #ifdef PackA_EXPORTS
        #define PackA_EXPORT __declspec(dllexport)
    #else
        #define PackA_EXPORT __declspec(dllimport)
    #endif
#else
    #define PackA_EXPORT
#endif


#endif

// PackA.h
#ifndef PACKA_HEADER_H
#define PACKA_HEADER_H

#include "PackAGlobal.h"
#include <string>
class  PackA
{
public:
    PackA();

};

#endif

```
VS reports bugs:

```
c4430 missing type specifier - int assumed. note c++ does not support default-int
c2071 abstract declarator illegal storage class
c2513: PackA:  no variable declared before =

```

I have uploaded my code to [github](https://github.com/zhang-qiang-github/SwigTest).

I have read the `swig/Examples/python`, but I can not find an example to wrap a class with export declare. 

How can I wrap this export class into python? Any suggestion is appreciated~~~

**Comment by ojwb** [comment]
You need to `%include "PackAGlobal.h"` in your `PackA.i` too as SWIG doesn't follow `#include` recursively by default (or use `swig -includeall` but I've rarely found that to work as it typically ends following into system headers and choking on something there).
