### ISSUE TITLE
Proposal to drop support for Python 3.2

### ISSUE THREAD

**Issue by wsfulton** [swig/swig#2314]
Currently SWIG supports Python 2.7 as well as Python 3.2 and later. Recently the Github Actions CI has stopped working for Python 3.2 and I don't have the time to investigate why this Python package stopped working. Feb 2016 is when security fixes were last provided for 3.2, which seems far enough back to drop support for in the pending swig-4.1.0 version, especially as this is one of the earlier Python 3 versions.

**Comment by jschueller** [comment]
good idea, I can give a hand

**Comment by ojwb** [comment]
Seems sensible to me - better to direct our finite efforts elsewhere.
