### ISSUE TITLE
C++17 Attributes

### ISSUE THREAD

**Issue by Diyou** [swig/swig#2326]
I get a 
```cpp
Syntax error in input(3)
```
when wrapping a class to csharp on a method that looks like:
```cpp
[[nodiscard]] std::string updateInformation() const;
```
Removing the [[[nodiscard]]](https://en.cppreference.com/w/cpp/language/attributes/nodiscard) results in a successful build.
Is this not supported yet  or did I setup anything wrong?

**Comment by ojwb** [comment]
This was recently fixed in git master (e56ce01dfe7169b0e47cf8be8dd2458df70f6606) - the fix should be in the upcoming SWIG 4.1.0 release.
