### ISSUE TITLE
Template parse error

### ISSUE THREAD

**Issue by sethrj** [swig/swig#2335]
The Trilinos Tpetra MultiVector package (for which I maintain Fortran SWIG bindings) has an amazingly inscrutable function declaration:
```c++
template<class TargetDeviceType>
typename std::remove_reference<decltype(std::declval<dual_view_type>().template view<TargetDeviceType>())>::type::const_type
getLocalView (Access::ReadOnlyStruct) const;
```

which causes both readers and SWIG parsers much consternation. 

A simple failing example is:
```swig
%module template_parse_error

%{
#include <utility>
%}

%inline %{

template<class T>
struct A
{
template<class U>
U get_it() { return {}; }
};

template<class V>
struct B
{

template<class W>
decltype(std::declval<A<V>>().template get_it<W>()) get_it_indirectly();

};

%}
```

but I'm also able to produce a failure *without* decltype (though still using C++11):

```c++
template<int I>
struct A
{
template<int J>
static constexpr int sum() { return I + J; }
};

template<int K>
struct B
{
template<int L>
A<A<K>().template sum<L>()> should_be_sizeof_int();
};
```

This seems to be independent of the other C++11 template issues currently active in the tracker.

**Comment by ojwb** [comment]
SWIG doesn't evaluate constant expressions in template parameters (https://sourceforge.net/p/swig/bugs/1198/) which may be related.  (I think we could probably handle simple expressions like the one in the other ticket by using the existing evaluation code which is use for preprocessor expressions, but expecting SWIG to evaluate `constexpr` functions is probably unrealistic.)

**Comment by sethrj** [comment]
Aha, fair enough. C++ is getting increasingly dynamic (automatic types etc) and SWIG is always going to be restricted to compile-time-resolvable interfaces. There's a definite advantage to having high-level library functions being "human-readable" (unlike that Trilinos garbage that motivated this example) so I hope SWIG will still remain relevant outside of C and C++03-style code.

**Comment by ojwb** [comment]
Some newer C++ features are problematic for SWIG, but a lot are OK (or at least they "only" need a patch).  Some just aren't relevant to SWIG as it only parse declarations and skips over function bodies (the lexer still handles them as we need to find the matching closing `}` but it's unlikely a new C++ feature would break lexing for this purpose).

There are some C++98 and C features that SWIG doesn't handle, but a lot of people still find SWIG useful.  For example, in current releases you can't use `<` and `>` in a constant expression (git master handles them in commonly reported cases, but they need to be inside a parenthesised expression).

**Comment by sethrj** [comment]
That's cool to know, thanks @ojwb ! I've indeed found SWIG useful over the years (and helped other projects replace hand-rolled code with it).

**Comment by ojwb** [comment]
With the patch from #2593, the first two examples now parse.  You get a warning in each case because SWIG can't deduce the type for anything non-trivial:

```
test.i:2: Warning 344: Unable to deduce decltype for 'std::declval<dual_view_type>().template view<TargetDeviceType>()'.
```
and

```
test2.i:21: Warning 344: Unable to deduce decltype for 'std::declval<A<V>>().template get_it<W>()'.
```

The third example still fails to parse.

**Comment by ojwb** [comment]
@sethrj Do you know what the problematic (to SWIG) construct in the third example is called?

I tried to look it up, but without a name or useful description of it the closest I got was:

https://en.cppreference.com/w/cpp/keyword/template

I guess this must be the second case there ("Inside a template definition, template can be used to declare that a [dependent name](https://en.cppreference.com/w/cpp/language/dependent_name) is a template.")  However, following that link doesn't help me at all.

**Comment by sethrj** [comment]
@ojwb I've always heard it as a "disambiguator"

**Comment by ojwb** [comment]
Ah, thanks for the pointer - that's exactly what I was after.  I'll open a new issue for that.
