### ISSUE TITLE
Call python function from c++ with swig wrapped arguments

### ISSUE THREAD

**Issue by by1e11** [swig/swig#2347]
Hi, there

I know that SWIG is a tool to generate bindings from target language to c++. 

However, I'm currently working on a scenario that I need to call a python function from c++. 

Normally, this is nothing to do with SWIG, I can do that with the method provided by "embedding python" in the Python documentation. However, when come to my scenario, one of the arguments in the python function to be called was a "SWIG wrapped object (a large c++ class under the hood)", then I think I have to somehow get access to the wrapped codes (at least the type conversion part).

My naive idea is that I can somehow generate (either manually or automatically) a header file of the wrapped file (*_wrap.cxx) and call the SWIG_ConvertPtr function to convert my c++ object to PyObject before sending to the python function with PyObject_CallObject.

Thus, my question is: is there any nice way to implement that? Any suggestion to avoid too many manual work?

Thanks a lot
Bo

**Comment by wsfulton** [comment]
Please read about the %callback and %director features for calling python functions from C++.
