### ISSUE TITLE
About swig for Golang's special flag -intgosize

### ISSUE THREAD

**Issue by KuoKongQingYun** [swig/swig#2348]
Firstly,thank all guys that provide the swig that help me using some complex C/C++ libraries in other languages.

When I use golang to link a library that is huge by swig,I find a inconvenient point.

If I set intgosize to 64 when I build for x86, the program would crash.

so when I build for arch amd64, it should be set intgosize to 64,
otherwise,when I build for arch 386, it should be set intgosize to 32.
It is very "unsmart".

If I want to release a Go module using swig that supports both x64 and x86,I have to make two defferent packages.
Golang provides a solution to solve this problem:

https://pkg.go.dev/cmd/go#hdr-Build_constraints

so I just add defferent build tag for files that swig generates, then those files can be in the same package/dir.

I compared those files, and find that they have only a little defference.

```
typedef int intgo;
typedef unsigned int uintgo;
```

```
typedef long long intgo;
typedef unsigned long long uintgo;
```

saving two copies with a little defference is a little "unkind".
so is there any solution to combine them and remove the intgosize flag?

**Comment by ojwb** [comment]
This is already fixed in git: #2233
