### ISSUE TITLE
Failing octave test

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#2353]
I tried to rebuild SWIG 4.1.0 on Fedora Rawhide, but octave test is failing with error:

```
error: swig_ref/horzcat method failed
error: called from
    horzcat
    runme at line 50 column 3
make[3]: *** [../../Makefile:473: octave_run] Error 1
make[2]: *** [../example.mk:11: check] Error 2
make[1]: *** [Makefile:215: operator.actionexample] Error 2
```

Fedora rawhide contains octave-7.2.0
Fedora build and logs could by found [here](https://koji.fedoraproject.org/koji/taskinfo?taskID=91700112)
I enabled only octave tests for the build. Other tests, which we run on Fedora, are passing.

**Comment by ojwb** [comment]
There are fixes in 4.1.0 for "Octave 4.4 - 6.0" and "Octave 6 up to and including 6.4".  I know little about Octave, but I suspect Octave 7 support needs work.

**Comment by jschueller** [comment]
cc @kwwette

**Comment by wsfulton** [comment]
@friedrichatgc would you be able to look at this? The failing test was introduced by your #1672 pull request. BTW, why was the subdirectory given such an odd name with a leading at sign: `@swig_ref` ?

**Comment by wsfulton** [comment]
@jplesnik if it isn't hard, could you run the octave test-suite and perhaps suppress all the new noisy annoying gcc warnings? These ones: `-Wmisleading-indentation -Wdeprecated` and the `_FORTIFY_SOURCE requires compiling with optimization` ? Hopefully, it is just this one test that is broken.

**Comment by friedrichatgc** [comment]
@wsfulton The horzcat.m function extends the octave class named "swig_ref" (SWIG introduces this name) by the member function horzcat.
From the octave docu [https://docs.octave.org/v4.0.1/Creating-a-Class.html#Creating-a-Class]
"All object oriented classes in Octave must be located in a directory that is the name of the class prepended with the ‘@’ symbol."
That's why this subdirectory must be named exactly like this.

I'm out for the next week and don't know when I find time to look at this. But I will try.

**Comment by jplesnik** [comment]
> @jplesnik if it isn't hard, could you run the octave test-suite and perhaps suppress all the new noisy annoying gcc warnings? These ones: `-Wmisleading-indentation -Wdeprecated` and the `_FORTIFY_SOURCE requires compiling with optimization` ? Hopefully, it is just this one test that is broken.

@wsfulton  I disabled the warnings and you are right only one test is failing.

https://koji.fedoraproject.org/koji/taskinfo?taskID=91820914

**Comment by wsfulton** [comment]
@friedrichatgc, regarding `@swig_ref`. From what I can make out swig_ref is defined in C++:
```
DEFINE_OV_TYPEID_FUNCTIONS_AND_DATA(octave_swig_ref, "swig_ref", "swig_ref");
```
I suppose `@swigref/horzcat.m` a way to extend this C++ defined class?? Any chance this can be explained/suggested in the SWIG manual in Octave.html for folk like me who aren't all that familiar with Octave?

**Comment by wsfulton** [comment]
I've disabled this part of the test for now in 0a0743f25cc0bbb395d03a27ac62887c8cbee5cf. @jplesnik could you try again? If the examples pass then the test-suite should run. I hope that nothing fails in the test-suite then.

**Comment by jplesnik** [comment]
@wsfulton The examples passed now.

**Comment by wsfulton** [comment]
#2374 fixes this in master.
