### ISSUE TITLE
typemap pattern matching not working

### ISSUE THREAD

**Issue by RalfJahns** [swig/swig#2355]
-debug-tmsearch gives me this output:

../../../../../../workspace/sources/gnss-component/asf_lib/generated/asf100/gnss/cmt/src-gen/topas/gnss/GnssTypes.h:3386: Searching for a suitable 'out' typemap for: ::boost::ptr_vector< topas::gnss::GnssTypes::NavSatPerSatellite > const &topas::gnss::GnssTypes::NavSat::getNavSatPerSatelliteList
  Looking for: ::boost::ptr_vector< topas::gnss::GnssTypes::NavSatPerSatellite > const &topas::gnss::GnssTypes::NavSat::getNavSatPerSatelliteList
  Looking for: ::boost::ptr_vector< topas::gnss::GnssTypes::NavSatPerSatellite > const &getNavSatPerSatelliteList
  Looking for: ::boost::ptr_vector< topas::gnss::GnssTypes::NavSatPerSatellite > const &
  Looking for: ::boost::ptr_vector const &topas::gnss::GnssTypes::NavSat::getNavSatPerSatelliteList
  Looking for: ::boost::ptr_vector const &getNavSatPerSatelliteList
  Looking for: ::boost::ptr_vector const &
  Looking for: ::boost::ptr_vector< topas::gnss::GnssTypes::NavSatPerSatellite > &topas::gnss::GnssTypes::NavSat::getNavSatPerSatelliteList
  Looking for: ::boost::ptr_vector< topas::gnss::GnssTypes::NavSatPerSatellite > &getNavSatPerSatelliteList
  Looking for: ::boost::ptr_vector< topas::gnss::GnssTypes::NavSatPerSatellite > &
  Looking for: ::boost::ptr_vector &topas::gnss::GnssTypes::NavSat::getNavSatPerSatelliteList
  Looking for: ::boost::ptr_vector &getNavSatPerSatelliteList
  Looking for: ::boost::ptr_vector &
  Looking for: SWIGTYPE const &topas::gnss::GnssTypes::NavSat::getNavSatPerSatelliteList
  Looking for: SWIGTYPE const &getNavSatPerSatelliteList
  Looking for: SWIGTYPE const &
  Looking for: SWIGTYPE &topas::gnss::GnssTypes::NavSat::getNavSatPerSatelliteList
  Looking for: SWIGTYPE &getNavSatPerSatelliteList
  Looking for: SWIGTYPE &
  Using: %typemap(out) SWIGTYPE &

In my .i file I provide this typemap:

%typemap(out) ::boost::ptr_vector< topas::gnss::GnssTypes::NavSatPerSatellite > &getNavSatPerSatelliteList{
.
.
.

But as you can see, it is not considered.
Other typemaps in my .i file work fine.
I also tried other alternatives, that -debug-tmsearch lists.
In my build environment I have to use swig version 3.0.12

Best regards
Ralf Jahns

**Comment by wsfulton** [comment]
Does SWIG parse your typemap before the function requiring it?

**Comment by RalfJahns** [comment]
Exactly what I feared has happened. I opened an issue and it's my own fault (as always). Very embarrassing for me. But on the other hand - now my problem is solved. So probably it was worth it :-)
