### ISSUE TITLE
TCL testcase integers failed on i686

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#2356]
I tried to rebuild SWIG 4.1.0 (commit db432300a) and one TCL testcase is failing.
```
checking tcl testcase integers (with run test)
Runtime test 1 failed
make[1]: *** [Makefile:43: integers.ctest] Error 1
```

https://koji.fedoraproject.org/koji/taskinfo?taskID=91822451

**Comment by wsfulton** [comment]
This test problem was introduced in 06d375cdab63842b223ea5b9091ad0336144e899. I replicated this on a 32-bit box and have committed a fix for the test in ad1688055dea4f07cd4023d5e0301d97f7759151 although the testcase could be more enhance in the future by using different max and min values for 32-bit and 64-bit systems.
