### ISSUE TITLE
SWIG exception handling in C# causes significant performance overhead

### ISSUE THREAD

**Issue by emmenlau** [swig/swig#2359]
I find SWIG really awesome and very helpful to my work. Thanks to all involved!

A small thing that I found is that my hand-written P/Invoke can achieve better performance than SWIG, to give roughly twice the data transfer rate: ~5 GB/sec compared to ~2.2 GB/sec in my case. In my concrete case, I am passing a 10MB array of `byte[]` through P/Invoke to C++, and receive it there as `const unsigned char*` without any marshalling, and that achieves on the order of 5 GB/sec on Windows with .Net 6.0.

In SWIG I was following https://stackoverflow.com/a/58326927/7200132 and added
```
%include "arrays_csharp.i"
%apply unsigned char INPUT[]  {const unsigned char* aData}
```
It seems the SWIG-generated code is then pretty similar to my own.

*Edited:*
~But it uses marshalling with `global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)] byte[]`. I'm under the impression that this is the main difference. And it drops performance to 50% or less.~

~Are there reasons for the current behavior in SWIG? I'm not too knowledgeable with blittable types. But it seems there are combinations where marshalling could be avoided, possibly without downsides? I could look into working on this, but I feel not knowledgeable if my findings are even correct and sensible...~

There seems to be a performance difference related to exception handling. When I disable the use of `exception.i` in the generator then the performance is on par with my hand-written code.

**Comment by wsfulton** [comment]
We'd welcome changes that improve performance or add additional typemaps. It should be clear that the MarshalAs is specified in arrays_csharp.i and that is where changes would go. I don't know that we can deduce any reason for the way it is other than look at the Git history of that file and see what tests (if any) break if it is changed. Here is where it is tested:
```bash
~/swig/github/swig (master *=)$ grep arrays_csharp Examples/test-suite/*
Examples/test-suite/csharp_lib_arrays_bool.i:%include "arrays_csharp.i"
Examples/test-suite/csharp_lib_arrays.i:%include "arrays_csharp.i"
~/swig/github/swig (master *=)$ grep arrays_csharp Examples/csharp/ -r
Examples/csharp/arrays/example.i:%include "arrays_csharp.i"
```

**Comment by emmenlau** [comment]
Awesome, thanks!

**Comment by emmenlau** [comment]
Dear @wsfulton, I investigated further and found that the difference in performance is *not* due to marshalling, but somehow related to the exception handling. It seems the exception handling (when activated) causes quite some performance overhead.

If I find some time, I may try to look into that and report back here.

**Comment by emmenlau** [comment]
After a long investigation I can not really identify slow parts. The issue may actually be due to wrong assumptions about the data transfer rate in P/Invoke, when using blittable types. Closing this issue as invalid.
