### ISSUE TITLE
PHP testcase default_args failed on i686

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#2360]
I tried to rebuild SWIG 4.1.0 (commit ad1688055) and one PHP testcase is failing.

```
checking php testcase default_args (with run test)
/builddir/build/BUILD/swig-4.1.0/Examples/test-suite/php/default_args_runme.php:114: Failed on: min_32bit_int1 failed: '-2147483648'!=='-2147483648'
make[2]: *** [../../../Examples/Makefile:1074: php_run] Error 1
make[1]: *** [Makefile:53: default_args.cpptest] Error 2
```

https://koji.fedoraproject.org/koji/taskinfo?taskID=91854113

**Comment by ojwb** [comment]
Odd, those do seem to be the same.

We use `!==` here so I suppose it could be failing because one is a string, but it shouldn't be from looking at the generated wrapper code.  I can't trivially test on a 32-bit platform, but does this help?

```
diff --git a/Examples/test-suite/php/default_args_runme.php b/Examples/test-suite/php/default_args_runme.php
index c793b08a..f64e2ba0 100644
--- a/Examples/test-suite/php/default_args_runme.php
+++ b/Examples/test-suite/php/default_args_runme.php
@@ -111,7 +111,7 @@ check::equal($tricky->value_m01(10), -1, "trickyvalue_m01 failed");
 check::equal($tricky->booltest2(), True, "booltest2 failed");
 
 check::equal($tricky->max_32bit_int1(), 0x7FFFFFFF, "max_32bit_int1 failed");
-check::equal($tricky->min_32bit_int1(), -2147483648, "min_32bit_int1 failed");
+check::equivalent($tricky->min_32bit_int1(), -2147483648, "min_32bit_int1 failed");
 check::equal($tricky->max_32bit_int2(), 0x7FFFFFFF, "max_32bit_int2 failed");
 
 $tricky->too_big_32bit_int1();
```

**Comment by jplesnik** [comment]
@ojwb  The change fixed the failure.

**Comment by ojwb** [comment]
Seems `-2147483648` is a PHP float when C long is 32-bit, even though it's representable as a long - I found an ancient report of this: https://news-web.php.net/php.dev/71707

Looks like we could probably use `-2147483647 - 1` here instead but we know `check::equivalent()` works so I went with that as the fix.

Thanks for catching this.
