### ISSUE TITLE
Build of COPASI Python binding fails with swig 4.1.0

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#2363]
I am testing rebuild of SWIG dependencies against version 4.1.0 in Fedora rawhide/38.

The build of COPASI is failing with this version.

```
[ 37%] Generating UI/moc_CLNAResultSubwidget.cpp
cd /builddir/build/BUILD/COPASI-Build-258/copasi/UI && /usr/lib64/qt5/bin/moc @/builddir/build/BUILD/COPASI-Build-258/copasi/UI/moc_CLNAResultSubwidget.cpp_parameters
/builddir/build/BUILD/COPASI-Build-258/copasi/bindings/python/../../copasi.h:37: Error: Syntax error in input(1).
gmake[2]: *** [copasi/bindings/python/CMakeFiles/binding_python_lib.dir/build.make:185: copasi/bindings/python/copasi_wrapper.cpp] Error 1
gmake[2]: Leaving directory '/builddir/build/BUILD/COPASI-Build-258'
gmake[1]: *** [CMakeFiles/Makefile2:1053: copasi/bindings/python/CMakeFiles/binding_python_lib.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```

Complete build log is [here](https://download.copr.fedorainfracloud.org/results/jplesnik/swig-rebuild/fedora-rawhide-x86_64/04830370-COPASI/builder-live.log.gz). Other information about the build can be found [here](https://copr.fedorainfracloud.org/coprs/jplesnik/swig-rebuild/build/4830370/).

If you want to look at source code of used COPASI, please check [COPASI 4.35 (build 258)](https://github.com/copasi/COPASI/tree/release/Version-4.35)

**Comment by ojwb** [comment]
It's unfortunate this is causing some existing code to break, but do I think we want to keep the change as it aligns SWIG better with how compiler preprocessors work.

`-DLIBSBML_CPP_NAMESPACE_USE=` should work with existing SWIG releases as well as fixing this for SWIG 4.1.0.

I'll add a note to the `CHANGES.current` entry about this.
