### ISSUE TITLE
Build of libsolv with SWIG 4.1.0

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#2366]
The build of libsolv is failing with SWIG 4.1.0.

```
+ /usr/bin/python3 -c 'import solv'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/builddir/build/BUILDROOT/libsolv-0.7.22-1.fc38.x86_64/usr/lib64/python3.11/site-packages/solv.py", line 12, in <module>
    import _solv
ImportError: /builddir/build/BUILDROOT/libsolv-0.7.22-1.fc38.x86_64/usr/lib64/python3.11/site-packages/_solv.so: undefined symbol: XSolvable___eq__
error: Bad exit status from /var/tmp/rpm-tmp.El0FDg (%check)
    Bad exit status from /var/tmp/rpm-tmp.El0FDg (%check)
```
Complete build log is [here](https://download.copr.fedorainfracloud.org/results/jplesnik/swig-rebuild/fedora-rawhide-x86_64/04830436-libsolv/builder-live.log.gz). 

If you want to look at source code of used libsolv, please check [libsolv github](https://github.com/openSUSE/libsolv).

**Comment by jschueller** [comment]
definetely 26bf86322b18040e2f2156c34a47b44c927d1399, cc @vadz

**Comment by jschueller** [comment]
```
curl -L https://github.com/openSUSE/libsolv/archive/refs/tags/0.7.22.tar.gz | tar xz
cd libsolv-0.7.22
cmake -DENABLE_PYTHON=ON -DCMAKE_INSTALL_PREFIX=/usr .
make install -j8
python3 -c "import solv"
```

**Comment by jschueller** [comment]
for this on it seems libsolv relies on the old swig-generated name, with this patch it goes to another similar error:
```
diff --git a/bindings/solv.i b/bindings/solv.i
index 1d35bf6..b4ab667 100644
--- a/bindings/solv.i
+++ b/bindings/solv.i
@@ -3261,7 +3261,7 @@ returnself(matchsolvable)
   %rename("!=") __ne__;
 #endif
   bool __ne__(XSolvable *s) {
-    return !XSolvable___eq__($self, s);
+    return !XSolvable___eq__SWIG($self, s);
   }
 #if defined(SWIGPYTHON)
   int __hash__() {
```

**Comment by vadz** [comment]
Right, I didn't think of that, but while the change was indeed perfectly compatible from SWIG point of view, it doesn't help if some code outside SWIG relied on the old internal name.

I guess I'm going to have to make this optional and generate compatible names for the existing modules and turn it off only for C, where it's not needed (and actually actively harmful).

**Comment by ojwb** [comment]
@jplesnik Please can you retest with b9fa8c2 or newer.

**Comment by jplesnik** [comment]
I used https://github.com/swig/swig/commit/ed333b6b9720e0569cd3c7ccee8f1fc1b60da9f8 for test and libsolv was built [successful](https://copr.fedorainfracloud.org/coprs/jplesnik/swig-rebuild/build/4863199/)

**Comment by jschueller** [comment]
could you close these too ?

**Comment by vadz** [comment]
I've done this now, thanks for testing!
