### ISSUE TITLE
Build of med is failing with SWIG 4.1.0

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#2370]
I am testing rebuild of SWIG dependencies against version 4.1.0 in Fedora rawhide/38.

The build of `med-4.1.0` is failing with this version.
```
/builddir/build/BUILD/med-4.1.0/redhat-linux-build/python/med/medequivalence_modulePYTHON_wrap.cxx:5410:5: error: 'std_vector_Sl_med_float_Sg__operator_Sa__Se_' was not declared in this scope; did you mean 'std_vector_Sl_med_float_Sg__operator_Sa___SWIG'?
 5410 |     std_vector_Sl_med_float_Sg__operator_Sa__Se_(&v,value);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     std_vector_Sl_med_float_Sg__operator_Sa___SWIG
/builddir/build/BUILD/med-4.1.0/redhat-linux-build/python/med/medequivalence_modulePYTHON_wrap.cxx: In function 'std::vector<double, std::allocator<double> > std_vector_Sl_med_float_Sg__operator_Ss___SWIG(const std::vector<double, std::allocator<double> >*, const std::vector<double, std::allocator<double> >&)':
/builddir/build/BUILD/med-4.1.0/redhat-linux-build/python/med/medequivalence_modulePYTHON_wrap.cxx:5426:5: error: 'std_vector_Sl_med_float_Sg__operator_Ss__Se_' was not declared in this scope; did you mean 'std_vector_Sl_med_float_Sg__operator_Ss___SWIG'?
 5426 |     std_vector_Sl_med_float_Sg__operator_Ss__Se_(&v,value);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     std_vector_Sl_med_float_Sg__operator_Ss___SWIG
```
Complete build log is [here](https://download.copr.fedorainfracloud.org/results/jplesnik/swig-rebuild/fedora-rawhide-x86_64/04830441-med/builder-live.log.gz). Other information about the build can be found [here](https://copr.fedorainfracloud.org/coprs/jplesnik/swig-rebuild/build/4830441/).

**Comment by jschueller** [comment]
seems to come from 26bf86322b18040e2f2156c34a47b44c927d1399, any clue what happens @vadz ?

**Comment by vadz** [comment]
Sorry, none at all. I'll try to look at this a.s.a.p. but I'm not sure if I can do it before 4.1.0 if it's really planned for this Sunday.

Also, I'm completely unfamiliar with Fedora build infrastructure, so while this information is probably available somewhere there, I can't find it immediately and if someone could please point me to the actual source used for this build, so that I could at least reproduce the problem, it would be great, TIA!

**Comment by jschueller** [comment]
no need for fedora, just need cmake + hdf5 on your favorite distro, here's how I bisected:
```
apt install libhdf5-dev cmake
cd /tmp
curl -L https://files.salome-platform.org/Salome/other/med-4.1.1.tar.gz | tar xz
cd med-4.1.1_SRC
cmake -D MEDFILE_BUILD_PYTHON=ON -D MEDFILE_BUILD_TESTS=OFF .
make -j8
```

**Comment by vadz** [comment]
Just to confirm the reason of the problem, there is this comment in med typemaps:
```cpp
    /*
       %mangle(Type); Le mangling du nom de la méthode semble être générée par le parseur C
     J'ai l'impression que l'on a pas le moyen d'y accéder par une directive.
    */
```
which, translated from French, means that they hardcode the names of the wrapper functions, so the solution mentioned in [this comment](https://github.com/swig/swig/issues/2366#issuecomment-1249590901) seems to be the only possible one. I'll make a PR implementing it soon.

**Comment by ojwb** [comment]
@jplesnik Please can you retest with b9fa8c2 or newer.

**Comment by jplesnik** [comment]
I used ed333b6b9 for test and med was built [successful](https://copr.fedorainfracloud.org/coprs/jplesnik/swig-rebuild/build/4863182/)
