### ISSUE TITLE
Subversion python tests segfault with SWIG 4.1.0

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#2373]
I am testing rebuild of SWIG dependencies against version 4.1.0 in Fedora rawhide/38.

The build of `subversion-1.14.2` is failing with this version.
```
+ make check-swig-py
mkdir /builddir/build/BUILD/subversion-1.14.2/subversion/bindings/swig/python/libsvn
if [ "LD_LIBRARY_PATH" = "DYLD_LIBRARY_PATH" ]; then for d in /builddir/build/BUILD/subversion-1.14.2/subversion/bindings/swig/python/libsvn_swig_py /builddir/build/BUILD/subversion-1.14.2/subversion/bindings/swig/python/../../../libsvn_*; do if [ -n "$DYLD_LIBRARY_PATH" ]; then LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$d/.libs"; else LD_LIBRARY_PATH="$d/.libs"; fi; done; export LD_LIBRARY_PATH; fi; \
cd /builddir/build/BUILD/subversion-1.14.2/subversion/bindings/swig/python; \
  /usr/bin/python3 /builddir/build/BUILD/subversion-1.14.2/subversion/bindings/swig/python/tests/run_all.py

RPM build errors:
make: *** [Makefile:947: check-swig-py] Segmentation fault (core dumped)
+ : Python swig test failure.
+ exit 1
```

Complete build log is [here](https://download.copr.fedorainfracloud.org/results/jplesnik/swig-rebuild/fedora-rawhide-x86_64/04830453-subversion/builder-live.log.gz). Other information about the build can be found [here](https://copr.fedorainfracloud.org/coprs/jplesnik/swig-rebuild/build/4830453/).

**Comment by jschueller** [comment]
not really a swig bug, upstream relies on the an internal define SWIGPYTHON_PY3 in its code:
https://github.com/apache/subversion/blob/trunk/subversion/bindings/swig/include/proxy.swg#L69

it was removed since a343b7e254567a64761bc1be7dc55b7b7424ec52
maybe `#if defined(SWIGPYTHON_PY3) || (SWIG_VERSION >= 0x040100)` ?

**Comment by jplesnik** [comment]
Thanks it helps. I'll report it to upstream and Fedora maintainer.
