### ISSUE TITLE
nordugrid-arc tests fails with SWIG 4.1.0

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#2376]
I am testing rebuild of SWIG dependencies against version 4.1.0 in Fedora rawhide/38.

The test of `nordugrid-arc-6.16.0` is failing with this version.
```
[slurmpy.t] [WARNING] [95031] PERL: Subroutine done_testing redefined at InfoproviderTestSuite.pm line 85.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/builddir/build/BUILD/nordugrid-arc-6.16.0/python/python/arc/lrms/slurm.py", line 11, in <module>
    from .common.cancel import cancel
  File "/builddir/build/BUILD/nordugrid-arc-6.16.0/python/python/arc/lrms/common/__init__.py", line 15, in <module>
    arc.Logger_getRootLogger().addDestination(_logstream)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'arc' has no attribute 'Logger_getRootLogger'
[ARC0mod] [ERROR] [95031] No ARC0 module for SLURMPY
Failed 1/1 test programs. 0/0 subtests failed.
```
Complete build log is [here](https://download.copr.fedorainfracloud.org/results/jplesnik/swig-rebuild/fedora-rawhide-x86_64/04863222-nordugrid-arc/builder-live.log.gz). Other information about the build can be found [here](https://copr.fedorainfracloud.org/coprs/jplesnik/swig-rebuild/build/4863222/).

**Comment by ojwb** [comment]
I think that's a deliberate change - see #2137.

You can pass `-flatstaticmethod` if you want the old flat name, or update to use `arc.Logger.getRootLogger().addDestination(_logstream)` (which should also work with any older SWIG version which is still relevant).

**Comment by jplesnik** [comment]
@ojwb It solved the issue. Thank you
