### ISSUE TITLE
Is there any way to optimize code generated by swig in golang?

### ISSUE THREAD

**Issue by kkqy** [swig/swig#2384]
I have a library that has many functions and types,but many of those types are alias of string,
but swig generate so many "typedef" lines (4800+ lines?) .
why  not using  _gostring_ directly?

```
typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
...
typedef _gostring_ swig_type_4834;
typedef _gostring_ swig_type_4835;
typedef _gostring_ swig_type_4836;
typedef _gostring_ swig_type_4837;
typedef _gostring_ swig_type_4838;
```

File : [cto.go](https://gist.github.com/kkqy/cd22d0bb73790a7e26d3fbb1d82520c8)

**Comment by ojwb** [comment]
I can't really speak as to why, but is this actually a problem?

I see you originally wrote

> which make the time of compilation too long (about 15 minutes).

but have since deleted that part.

If the current approach really makes the wrapper much slower to compile it seems more worth worrying about.  Did you try replacing all these in the generated wrapper to confirm this is actually contributing to the compile time?

**Comment by kkqy** [comment]
> I can't really speak as to why, but is this actually a problem?
> 
> I see you originally wrote
> 
> > which make the time of compilation too long (about 15 minutes).
> 
> but have since deleted that part.
> 
> If the current approach really makes the wrapper much slower to compile it seems more worth worrying about. Did you try replacing all these in the generated wrapper to confirm this is actually contributing to the compile time?

Thank you for your reply.
Sorry, I can't confirm that this is the main reason why compile time is so long , so I edit this issue before.
I watch the CPU usage when compile, and I find that It takes too long when GCC compiler deal with this file but CPU usage is very low and memory usage increase slowly, so I speculate that the compiler takes too much time to parse this “redundant” code? but I have no certain evidence.

by the way,I tried replacing the GCC with LLVM/Clang,and then the compile time decrease from 15 minutes to less than 30 seconds! 
so maybe It is a performance issue about GCC ?

**Comment by kkqy** [comment]
so this issue is resolved by using LLVM/Clang instead of GCC actually.
I forgot to close this issue before
Thanks.

**Comment by kkqy** [comment]
@ojwb 
here is my uncompleted go module with swig generated code 
https://github.com/kkqy/ctp-go

`go install -a`

If I rebuild it with GCC.
It takes 25-30 minutes....
but when using LLVM/Clang, it takes less than 30 seconds.
How strange it is...

( this module is developed in Windows, and I didn't test it in Linux, so I am not sure that it can be compiled succesfully in Linux)

**Comment by ojwb** [comment]
Sounds like a bug to report to the GCC developers, though do check it's still reproducible with the latest GCC release first.

**Comment by kkqy** [comment]
This problem relates to Swig, Golang , GCC, MinGW , LLVM/Clang , CTP and so on, so it is difficualt to describe it.
I don't plan to post issues to GCC because Clang works well.
Clang is faster than original GCC because Clang can tidy and arrange codes before compiling like a preprocessor.
Maybe it is an advantage of Clang instead of a problem of GCC. 😄
LLVM/Clang and Swig are very nice tools.

Thank you for all your help.
