### ISSUE TITLE
unused swig_call_defargs ?

### ISSUE THREAD

**Issue by jschueller** [swig/swig#2390]
seems swig_call_defargs is not used anywhere, should it be removed (python/defarg.swg) ?

**Comment by ojwb** [comment]
This file was added by d2032af50ab0c561d7fe475ff48e51d953354a77 back in 2000, and there's no documentation I can find aside from the comments in the file itself plus `Lib/python/README` which says "for processing default arguments with shadow classes" and lists it as "Backward compatibility and deprecated".

It seems to claim to implement a `__call_defarg` helper on the Python side but I don't see that in the generated wrappers, nor any code which would generate it in the history (`git log -Scall_defarg` only shows two copies of the original commit).

So think the whole file should be removed.  I'll open a PR, thanks.
