### ISSUE TITLE
C++ overloaded function matching ignores char* typemaps (Python)

### ISSUE THREAD

**Issue by fixthething** [swig/swig#2404]
Sometime recently (swig 4.0.1?) swig python wrapper code generation added more rigorous type checking to resolve which method is being called if there are multiple prototypes with the same name. This also applies to functions with optional parameters, even if there is no actual function name overloading.

In the particular case where a C++ function takes a char * parameter (without using SWIG_PYTHON_STRICT_BYTE_CHAR), the prototype checking will add code doing a test with SWIG_AsCharPtrAndSize. This is great if it is actually a string getting passed, but in my case I had an explicit typemap for (char *, size) that treated it as PyBytes. The code generates fine and my typemap code is included, but it never gets to my typemap code because the function matching wrapper errors out before it gets there.

See the attached "swigtoy" demo for the problem.

[swigtoy.zip](https://github.com/swig/swig/files/9792353/swigtoy.zip)

Execute/test with the following command line:
```
$ python3 setup.py bdist_wheel && python3 -m pip install dist/swigtoy*.whl --force && python3 test_swigtoy.py
```

The test explodes with the following error:
```
Traceback (most recent call last):
  File "test_swigtoy.py", line 4, in <module>
    swigtoy.printbytes(b'\x83\xff\xdd\xee', 0)
  File "/home/fixthething/swigtoy/swigtoy.py", line 66, in printbytes
    return _swigtoy.printbytes(bytes, arg3)
TypeError: Wrong number or type of arguments for overloaded function 'printbytes'.
  Possible C/C++ prototypes are:
    printbytes(char const *,int,int)
    printbytes(char const *,int)
```

This problem does not occur if:
- SWIG_PYTHON_STRICT_BYTE_CHAR is used (but let's say I have other functions in the real project for which I actually want to use char * as strings so this is not a suitable solution)
- The optional argument "int arg3=0" is a regular option and not optional (because then the overloaded function resolution is not generated)
- Older version of swig is used that does not check argument types

**Comment by fixthething** [comment]
I should note that older SWIG code generation just checks the number of arguments in this case to decide which prototype to use. This solution is just fine for a function with optional parameters and no actual function overloading. If there is actual function overloading going on where there are two function prototypes with the same number of arguments but different types, then this older solution would be insufficiently strong which is why I suppose the new type checking code was added.

**Comment by wsfulton** [comment]
For overloading, which includes methods with default arguments, you need to provide a custom "typecheck" typemap for every custom "in" typemap. See https://swig.org/Doc4.1/Typemaps.html#Typemaps_overloading and https://swig.org/Doc4.1/Python.html.

**Comment by fixthething** [comment]
Yes, that is exactly it; added this to fix the problem in the toy example:
```
%typecheck(SWIG_TYPECHECK_STRING) const char *bytes{
    $1 = PyBytes_Check($input) ? 1 : 0;
}
```
Thanks for pointing this out; I had never dug into that corner of the manual because I didn't even think about function overloading until I ran into this problem.
