### ISSUE TITLE
warning 305: Bad constant value (ignored) with define  P *

### ISSUE THREAD

**Issue by bmiyuan** [swig/swig#2406]
hi, I'm getting error:warning 305: Bad constant value (ignored) when use swig to convert c++ to python
**swig version**:4.0.2
**code**:
`%inline %{
#define P *
%}`

**Comment by ojwb** [comment]
That seems correct since `*` isn't a valid constant...

If you want to suppress this warning, you can pass `-w305` on the SWIG command line.

**Comment by bmiyuan** [comment]
ok... thanks
