### ISSUE TITLE
how to export type to python when use swig convert c++ to python

### ISSUE THREAD

**Issue by bmiyuan** [swig/swig#2407]
Hi, I want to use SWIG interface file to export type .for example I define TEST_TYPE in .i file
`%inline %{
typedef unsigned int TEST_TYPE;
%}`
and I also can find it in XXXPYTHON_wrap.cxx
`typedef unsigned int TEST_TYPE;`
but I can't find it in the XXX.py which is converted from c++ to python.

anyone can help on this ? thanks a lot!

**Comment by wsfulton** [comment]
That's correct, the type system (which understands typedefs) is implemented in C++ code.
