### ISSUE TITLE
Beta 4.1.0, Windows CMake installation fails at building: '/Foswig.dir\Debug\/Source/CParse/parser.c.obj' not allowed with multiple source files [C:\Dev\Software\swig-build\build\swig.vcxproj]

### ISSUE THREAD

**Issue by zikuth** [swig/swig#2409]
The compilation was done with VS2022 instead of VS2019 as it's described in the documentation

**Comment by geographika** [comment]
@zikuth - not sure what documentation (or installation) you are referring to?
The docs at https://www.swig.org/Doc4.1/SWIGDocumentation.html#Windows_cmake refer to VS 2019 and 2019 is used in the [CI](https://github.com/swig/swig/blob/master/.github/workflows/nuget.yml).

**Comment by zikuth** [comment]
There in 3.3.1 step 6. If one compiles with vs 2022 instead of 2019 one gets that error

**Comment by jschueller** [comment]
maybe the cmake version 3.15 proposed in the doc is too old for vs 2022, maybe try with something newer

**Comment by geographika** [comment]
> maybe the cmake version 3.15 proposed in the doc is too old for vs 2022, maybe try with something newer, the /Fo option should not be there

This seems to be the case: https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2017%202022.html

> New in version 3.21.

I'm not sure how @zikuth got that far as it crashes out with "CMake Error: Could not create named generator Visual Studio 17 2022" for me. 

The latest version of CMake on Nuget is 3.15.5: https://www.nuget.org/packages?q=cmake
@zikuth if you need to build in VS 2022 you'll need to manually download a more recent version from https://cmake.org/download/ until the nuget package is updated.

**Comment by zikuth** [comment]
I used CMake 3.22.1 (sorry that I didn't said it before) It also fails compiling with the same error with VS2022 using the v142 Toolset (VS2019). Do you know where "Foswig" is used in the project? I made a search and couldn't find it anywhere. And thanks a lot for your asnwers :)!

**Comment by jschueller** [comment]
did you set any option ? please provide full logs and CMakeCache.txt

**Comment by zikuth** [comment]
I set the install path, and my folders differ a bit, but that's all, the configure step works well. Here is the CMake Cache, but I doubt that the problem is there:
[CMakeCache.txt](https://github.com/swig/swig/files/9833747/CMakeCache.txt)

Here is the VS build output (probably more interesting, notice the warning). It happens both in Debug and Release:

Build started...
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>Checking Build System
2>------ Build started: Project: swig, Configuration: Debug x64 ------
2>[BISON][swig_parser] Building parser with bison 3.7.4
2>Building Custom Rule C:/Dev/Software/swigwin-4.1.0-beta1/CMakeLists.txt
2>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(1091,5): warning MSB8027: Two or more files with the name of parser.c will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are C:\Dev\Software\swigwin-4.1.0-beta1\Source\CParse\parser.c, C:\Dev\Software\swigwin-4.1.0-beta1\build\Source\CParse\parser.c.
2>cscanner.c
2>templ.c
2>util.c
2>base.c
2>file.c
2>fio.c
2>hash.c
2>list.c
2>memory.c
2>string.c
2>void.c
2>cwrap.c
2>deprecate.c
2>error.c
2>extend.c
2>fragment.c
2>getopt.c
2>include.c
2>misc.c
2>naming.c
2>Generating Code...
2>Compiling...
2>parms.c
2>scanner.c
2>stype.c
2>symbol.c
2>tree.c
2>typemap.c
2>typeobj.c
2>typesys.c
2>wrapfunc.c
2>cpp.c
2>expr.c
2>Generating Code...
2>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6006: "CL.exe" exited with code 2.
2>cl : command line error D8036: '/Foswig.dir\Debug\/Source/CParse/parser.c.obj' not allowed with multiple source files
2>Done building project "swig.vcxproj" -- FAILED.

**Comment by jschueller** [comment]
oh you have two files named parser.c, maybe because you configured multiple times in different build dirs ?

**Comment by zikuth** [comment]
Yes, that was what I thought, but no, I deleted the folder and unzipped it gain and the error was still there

**Comment by jschueller** [comment]
oh, maybe you're using the tarball, which provides the parser.c, in that case seems you have to configure in the source dir, not in a build dir (or just remove CParse/parser.c)
if that works that means we could just rename the generated file in the CMakeList
