### ISSUE TITLE
Deduce "%shared_ptr(T)" automatically for classes that inherit from `std::enable_shared_from_this`

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [swig/swig#2416]
It would help a lot with having to remember to put `%shared_ptr` on all classes that inherit from some other class that we use as a shared pointer.

**Comment by emmenlau** [comment]
Nice idea!

**Comment by devshgraphicsprogramming** [comment]
hmm its probably not that great of an idea, as it violates a certain pattern in Directors.

If you inherit from an object, then you essentially have the same object, even if you're not literally inheriting in the C++/language-builtin-in sense.

The problem with `%shared_ptr` is that it replaces all references passed by SWIG via the PRoxy Classes with `shared_ptr<T>` and its the shared_ptr thats `new`-ed on the heap.

This means even the `swigCPtr` in the wrapper class of the other language.

I was almost at the point in my project where I considered Cross Component Tracing, but I realized that sometimes it makes sense not to have swig substitute every usage of a type with a shared pointer to that type.
