### ISSUE TITLE
`-php7` is still described as “Generate PHP 7 wrappers”

### ISSUE THREAD

**Issue by Smattr** [swig/swig#2420]
IIUC https://github.com/swig/swig/pull/1978 adapted the `-php7` option to generate code that is also compatible with PHP 8. This also updated the description of `-php7` in the manual. But this seems to have missed the help information for this in Source/Modules/swigmain.cxx. In SWIG 4.1.0 I see the following:

```
$ swig -help
…
     -php7           - Generate PHP 7 wrappers                                                                        
…
```

which I think should say “PHP 7 or later”.

CC @ojwb

**Comment by ojwb** [comment]
Thanks, will fix shortly.
