### ISSUE TITLE
Template instantiation in original namespace

### ISSUE THREAD

**Issue by christophe-calmejane** [swig/swig#2427]
Hi,

I've the following c++ code
```

%include <std_set.i>

%nspace Foo::Bar;

namespace Foo
{
class Bar
{
public:
    Bar() = default;
    int get() const noexcept;
};
using Bars = std::set<Bar>;
}

%template(Bars) std::set<Bar>;
```

When I generate c# code, the `Bars` class is not part of the `Foo` namespace, like it is in the original code.
This is just a small showcase, my project has a lot of namespaces and a lot of templated containers that I don't really want to see at the root of the package.

Is there a way to generate the templated class in the same namespace as the original code, so I can do
```
var bars = new Foo.Bars();
bars.Add(new Foo.Bar());
```

Thanks

**Comment by devshgraphicsprogramming** [comment]
It would be nice to control the namespace of a variable in the target language, or be able to make them be declared as nested classes inside another class to at least get a semblance of namespacing

**Comment by christophe-calmejane** [comment]
This is getting more and more problematic for me (c# target language). Is there a workaround for this?

I can probably help adding this feature if it's not too deep in the code and if I'm guided to the correct part of the source :)

**Comment by wsfulton** [comment]
Alas, I think the solution would be deep in the internals messing with the symbol tables. Hard to know for sure, but perhaps not too hard to implement if based on something like %rename, which is in implemented in parser.y rename_directive. symbol.c contains the symbol table implementation. I'm sorry, I just don't have the bandwidth to look at this.

**Comment by macdew** [comment]
I'd like to add a "me too" to this issue.  We're also targeting C# and with a ton of classes we've enabled %feature("nspace", 1), but now all the %template containers are in the "std" namespace which really isn't great...  I haven't found any way to break them out of that and put them in our namespace.

**Comment by nolankramer** [comment]
I'll bump this. It would be extremely valuable to be able to produce natural APIs in target languages.

**Comment by wsfulton** [comment]
See #2782 for the new `%nspacemove` directive. The example posted should be modified to:

```swig
%nspacemove(Foo) std::set;
%include <std_set.i>

%nspace Foo::Bar;

%inline %{
#include <set>

namespace Foo
{
class Bar
{
public:
    Bar() = default;
    int get() const noexcept;
    friend bool operator<(Bar b1, Bar b2)
    {
        ...
    }
};
// using Bars = std::set<Bar>; // not needed really
}
%}

%template(Bars) std::set<Foo::Bar>;
```

then the desired C# user code works exactly as shown.

**Comment by nolankramer** [comment]
Thank you @wsfulton! For anyone using my example code, I highly recommend switching to the new `%nspacemove`!

**Comment by christophe-calmejane** [comment]
@wsfulton While `%nspacemove` does fix this very simple example, it doesn't really work for more complex (real life) projects.

What would be the solution for this slightly modified version of my example:
```SWIG
%include <std_set.i>

%nspace Foo::Bar;
namespace Foo
{
class Bar
{
public:
    Bar() = default;
    int get() const noexcept;
};
}
%template(Bars) std::set<Bar>;

%nspace Other::Bar;
namespace Other
{
class Bar
{
public:
    Bar() = default;
    int get() const noexcept;
};
}
%template(OtherBars) std::set<Other::Bar>;
```

This is the kind of use cases I have in most projects I need to SWIG.
Thanks.

**Comment by wsfulton** [comment]
The modified version has some fundamental SWIG and C++ problems, so I'm not entirely sure what you want, but I've made some assumptions and the following code:
```swig
%module example

%include <std_set.i>

%nspace;
%nspacemove(Foo) std::set<Foo::Bar>;
%inline %{
namespace Foo
{
class Bar
{
public:
    Bar() = default;
    int get() const noexcept;
    friend bool operator<(Bar b1, Bar b2)
    {
        return false; // TODO
    }
};
}
%}
%template(Bars) std::set<Foo::Bar>;

%nspacemove(Other) std::set<Other::Bar>;
%inline %{
namespace Other
{
class Bar
{
public:
    Bar() = default;
    int get() const noexcept;
    friend bool operator<(Bar b1, Bar b2)
    {
        return false; // TODO
    }
};
}
%}
%template(OtherBars) std::set<Other::Bar>;
```
results in the `std::set` wrappers in the same namespace as the set's type, so that this is how you'd use them from C#:
```csharp
      var bars = new Foo.Bars();
      bars.Add(new Foo.Bar());

      var otherBars = new Other.OtherBars();
      otherBars.Add(new Other.Bar());
```

**Comment by christophe-calmejane** [comment]
I may have oversimplified the example (with some SWIG copy/paste error) but you got it right.

Thanks a lot for the clarification I confirm it does work perfectly. Based on your first example and the documentation I didn't clearly understand that we can move the fully templated type (eg. `std::set<Foo::Bar>`), I thought it was only the template itself that could be moved (eg. `std::set`) which rendered it useless in case of multiple instantiation.

It may prove useful for other people though :)

**Comment by wsfulton** [comment]
I'm more than happy to accept documentation improvements. The "More about the nspace feature" section https://htmlpreview.github.io/?https://github.com/swig/swig/blob/master/Doc/Manual/SWIGPlus.html#SWIGPlus_nspace_more might be the place to improve. I specifically put in a template in that section to show templates working, covering an easy way to move all templates instantiated within a particular namespace being easily move to another namespace. Think of all std::vector templates being moved from the `std` namespace to some other namespace.
