### ISSUE TITLE
Building 4.1.0 with cmake on Mac 

### ISSUE THREAD

**Issue by snarkhunter** [swig/swig#2431]
After building 4.1.0 with cmake 3.23.4 on macOS 11.7, swig fails on a simple input file.  The input file is just
```
%module dummy
void f();
```

Running `swig -python -c++ -o dummy.cxx dummy.i`  yields
`/Users/langer/stow/swig-4.1.0/share/swig/4.1.0/swig.swg:431: Error: Syntax error in input(1).`

If swig is built with configure and make, it works properly.  It also worked properly with cmake 3.23.4 on macOS 12.6.

**Comment by jschueller** [comment]
can you try master branch ?

**Comment by jschueller** [comment]
bison 2.3 is pretty old, maybe try a more recent version ?

**Comment by snarkhunter** [comment]
Yikes.  macOS ships with bison 2.3.  I installed 3.8.2 from MacPorts, but get the same error.  CMake does confirm that it's using 3.8.2.
 -- Steve

From: Julien Schueller ***@***.***>
Reply-To: swig/swig ***@***.***>
Date: Thursday, November 10, 2022 at 9:51 AM
To: swig/swig ***@***.***>
Cc: "Langer, Stephen A. (Fed)" ***@***.***>, Author ***@***.***>
Subject: Re: [swig/swig] Building 4.1.0 with cmake on Mac (Issue #2431)


bison 2.3 is pretty old, maybe try a more recent version ?

**Comment by jschueller** [comment]
I just fired a job on macos, everything is ok: https://github.com/jschueller/swig-mac, maybe something was wrong with that bison setup ?

**Comment by jschueller** [comment]
what the minimal bison version version swig requires ?

**Comment by snarkhunter** [comment]
I'm still getting the LESSEQUALGREATER error mentioned above.  I updated the master branch from github and ran cmake in a clean build directory.

**Comment by jschueller** [comment]
please post full cmake log then & make log (make VERBOSE=1)

**Comment by snarkhunter** [comment]
I started again with a completely new clone from github, and it all worked.  Could the LESSEQUALGREATER error from cmake have been caused by something leftover from building with configure/make? 

I tried to reproduce the sequence of steps I had used before in the new clone, but now it won't build with configure.   The new clone has no configure file.  I generated one with autoconf, but it complains about missing config.guess and config.sub.

 -- Steve

**Comment by jschueller** [comment]
yes, definetely, it is generated in the source dir
try "autoreconf -vfi"

**Comment by snarkhunter** [comment]
Thanks.  I can build 4.2.0 and I can't reproduce the problem with it. 

I can't reproduce it with 4.1.0 either, unfortunately.  My only guess is that something was left over from the bad build with the old system version of bison.

**Comment by wsfulton** [comment]
Closing due to dirty build directory.

**Comment by snarkhunter** [comment]
Can CMake check the version of bison?  Other Mac users with only the outdated system version will presumably have the same problem that I did.

 -- Steve

**Comment by jschueller** [comment]
it succeeded on my end with the old 2.3
