### ISSUE TITLE
get callback params from c++

### ISSUE THREAD

**Issue by duanchengwen** [swig/swig#2433]
There is a callback function in c++. Every time a new message is received, the callback function will be called automatically. I want to pass the parameters of the callback function to the python code. How can I achieve this?

//hpp file
class A
{
    A(){};
    void on_data_receive(string msg){
           // pass msg to python code
    }
}

// py file
def on_data_receive(msg):
       # the msg is from c++

**Comment by ojwb** [comment]
See `Examples/python/callback/` in the source tree

**Comment by ojwb** [comment]
Closing as solved.
