### ISSUE TITLE
How to properly provide an interface file along a library for transitive use

### ISSUE THREAD

**Issue by christophe-calmejane** [swig/swig#2434]
Hi,

I've a few libraries and I want each of them to provide a `.i` interface file in the distribution package (along with the swig generated files).
It's working fine, as long as libraries don't have dependencies with each other.

Here is an example:
### foo.hpp
```c++
namespace foo
{
class Foo
{
// ...
};
}
```

### foo.i
```swig
%module foo
%{
#include <foo.hpp>
%}
%include <foo.hpp>
```

I can distribute the generated c# file, along with the shared library, and use it in a c# project easily. I can do the same for my other `standalone` libraries.

But now, I've another library that publicly depends on `Foo`, so I have to provide the c# definition for the `Foo` class.

### bar.hpp
```c++
#include <foo.hpp>
namespace bar
{
class Bar
{
public:
  void fromFoo(foo::Foo const& foo);
// ...
};
}
```

### bar.i
```swig
%module bar
%{
#include <bar.hpp>
%}
%include <bar.hpp>
```

If I do that, the c# files for `Foo`  are generated again, and they point `bar` shared library.

Is there a way to tell swig that it is already defined elsewhere? Since the included `foo.i` file already defined a `module` I expected swig to understand it is declared elsewhere and there is no need to generate types for it again.

Thanks for your answers, possible or not ;)

**Comment by ojwb** [comment]
Try `%import foo.i`

**Comment by christophe-calmejane** [comment]
Oh I feel dumb, thank you so much ;)
