### ISSUE TITLE
Can not run test suite due to `SUITE: base TEST: BASIC - Expected cache miss to be 1 got 2`

### ISSUE THREAD

**Issue by emmenlau** [swig/swig#2437]
I'm trying to run the SWIG test suite, but fail on the first test, using current master c0026d036. Here is what I try:

```
./autogen.sh
./configure --without-android --without-d --without-go --without-guile --without-java --without-javascript --without-lua --without-mzscheme --without-ocaml --without-octave --without-perl5 --without-php --without-python --without-python3 --without-r --without-ruby --without-scilab --without-tcl --prefix=/data/Tools --with-pic
make && make install
make check
```
This fails after the first test with
```
SUITE: base TEST: BASIC - Expected cache miss to be 1 got 2
cache directory                     ccache dir
cache hit                              0
cache miss                             2
files in cache                         4
cache size                            16 Kbytes
max cache size                     854.5 Mbytes
TEST FAILED
make[1]: *** [Makefile:68: test] Error 1
```
I googled for this error for quite a while but could not find anything relevant. I also found some issues here in the SWIG issue tracker where people reported something along the lines of `CFLAGS` may be missing in `CCache`, but applying the provided patches did not help.

**Comment by wsfulton** [comment]
The ccache test-suite has worked reliably for years, so I don't know how we can replicate this.

Please see #2449. Does that fix this problem by any chance?

**Comment by emmenlau** [comment]
Ok, I've found the problem: We use ccache in our CI, and that breaks the tests of swig. It may be a good idea that swig would check for that, but now that the issue is known, maybe it is not such a high priority - people can find it via google and solve the issue on their side...
