### ISSUE TITLE
winsparkle.h:76: Error: Syntax error in input(1)

### ISSUE THREAD

**Issue by yogiraturimansyah** [swig/swig#2438]
### Discussed in https://github.com/swig/swig/discussions/2382

<div type='discussions-op-text'>

<sup>Originally posted by **purejava** September 25, 2022</sup>
I try to parse https://github.com/vslavik/winsparkle/blob/master/include/winsparkle.h

```
%module winsparkle
 %{
 /* Includes the header in the wrapper code */
 #include "winsparkle.h"
 %}
 
 /* Parse the header file to generate wrappers */
 %include "winsparkle.h"
```
```
swig -java winsparkle.i
```

What's the problem? Thanks.</div>

**Comment by ojwb** [comment]
The line the error points to is:

```
WIN_SPARKLE_API void __cdecl win_sparkle_init();
```

And `WIN_SPARKLE_API` is defined as:

```
#ifdef BUILDING_WIN_SPARKLE
    #define WIN_SPARKLE_API __declspec(dllexport)
#else
    #define WIN_SPARKLE_API __declspec(dllimport)
#endif
```

This is the problem - `__declspec` is not a standard C or C++ feature.

SWIG generally aims to support standard C and C++.  Even that's an ambitious scope (there are plenty of standardised features we don't yet support, especially in newer C++ standards) so trying to support compiler-specific extensions is probably too much of an ask.

I'd suggest just defining `__declspec(X)` away for SWIG's preprocessor - e.g. `swig -D__declspec(X)= ...` (you can also use `#define` in your interface file before the `%include "winsparkle.h"`).
