### ISSUE TITLE
What's the use of `%template()` a.k.a. "empty template declaration" ?

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [swig/swig#2440]
Hi,

I saw this in some example interface files, but documentation is silent about it.

When I tried it, it made no difference.

Can you exaplain what's the purpose for an unnamed template?

**Comment by devshgraphicsprogramming** [comment]
I was hoping `%template()` would save me from having to pick unique identifiers and just use what SWIG generates anyway when it encounters an unknown type.

Because it would let me define a little `MyNamespace_MyTemplatedType.` interface file with a macro
```
%define MyTemplatedType(T)
    %template() MyNamespace::MyTemplatedType<T>;
%enddef
```

as opposed to 
```
%define MyTemplatedType(T, NAME)
    %template(MyNamespace__MyTemplatedType_##NAME) MyNamespace::MyTemplatedType<T>;
%enddef
```

obviously using `T` instead of `NAME` would completely break with a very non-descriptive and cryptic error message when `T` would be a fully qualified name, such as `std::size_t`

**Comment by ojwb** [comment]
It's documented in SWIGPlus.html:

> Occasionally, you may need to tell SWIG about base classes that are defined by templates, but which aren't supposed to be wrapped.  Since SWIG is not able to automatically instantiate templates for this purpose, you must do it manually.  To do this, simply use the empty template instantiation, that is, <tt>%template</tt> with no name. For example:
>
> `// Instantiate traits<double, double>, but don't wrap it.`
> `%template() traits<double, double>;`

**Comment by wsfulton** [comment]
BTW, I've enhanced the docs in this area, see the new section "Empty template instantiation" in SWIGPlus.html committed in 4729cf2b1f44e57f46d13758009b10cec5af47b6

**Comment by dkz-phys** [comment]
Hi,

Could someone clarify what unnamed instantiations actually do? For the following inheritance

Base -> Foo<typename T> -> Bar<typename T>

why the target language only knows Bar is a  derived class of Base when the instantiation of Foo is named?

Source code:

```
class Base {... };
template<class T> class Foo : public Base {...}
template<class T> class Bar : public Foo<T> {...};

 // Instantiate unnamed base classes first 
%template() Foo<int>;

// Now instantiate derived classes
%template(intBar) Bar<int>;
 
 bar=Bar(...);
 Base(bar) //TypeError is raised unless Foo<int> is named
```

**Comment by wsfulton** [comment]
Take a look at the enhanced docs where it says that the template instantiation is added to the type system. SWIG does it's best without seeing all type information, but you usually get more usable wrappers if you provide all the type info for the type system. If you use the empty template instantiation instead of a name, then no proxy class is wrapped for `Foo<int>` and then intBar is not derived from `Foo<int>`. The inheritance chain is broken and so you'll also see the Type conversion tables do not have the ability to convert up the inheritance chain.
