### ISSUE TITLE
Error with Python 3.9

### ISSUE THREAD

**Issue by kisvegabor** [swig/swig#2442]
I'm trying to create a Python 3.9 wrapper for [LVGL](https://github.com/lvgl/lvgl) with this `.i` file:
```
/* File: lvgl.i */
%module lvgl

%{
#include "lvgl.h"
%}

%ignore _lv_txt_set_text_vfmt;
%include "lvgl.h"
```

This command:
```
swig -python -py3 -I/usr/include -ignoremissing -includeall lvgl.i
```

And this Makefile (only the relevant parts):
```
CFLAGS ?= -O3 -I$(LVGL_DIR)/ $(WARNINGS) -fPIC -I/usr/include/python3.9 \
	
LDFLAGS ?= -lSDL2 -shared -I/usr/local/lib/python3.9/config \
	-L/usr/local/lib/python3.9/config -lpython3.9 -lm -ldl \
	-o _lvgl.so

```

And when I try to `import lvgl` I get this error:
```
>>> import lvgl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kisvegabor/projects/lvgl/eclipse-workspace/lv_port_pc_eclipse_arch_driver/lvgl/lvgl.py", line 117, in <module>
    class __fsid_t(object):
  File "/home/kisvegabor/projects/lvgl/eclipse-workspace/lv_port_pc_eclipse_arch_driver/lvgl/lvgl.py", line 120, in __fsid_t
    __val = property(_lvgl.__fsid_t___val_get, _lvgl.__fsid_t___val_set)
AttributeError: module '_lvgl' has no attribute '_fsid_t__fsid_t___val_get'
```

The related part of `lvgl.py` from line 117:
```py
class __fsid_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __val = property(_lvgl.__fsid_t___val_get, _lvgl.__fsid_t___val_set)

    def __init__(self):
        _lvgl.__fsid_t_swiginit(self, _lvgl.new___fsid_t())
    __swig_destroy__ = _lvgl.delete___fsid_t
```

Do you have any ideas?

**Comment by wsfulton** [comment]
Sorry, no. Given you are using `-includeall`, I suggest using %ignore to ignore anything that doesn't seem to work. Otherwise, please open an issue with a small reproducible cutdown testcase.

**Comment by kisvegabor** [comment]
`fsid_t` doesn't seem to be LVGL related. LVGL has `lv_fs_file_t` and `lv_fs_drv_t`. Can is be related? 

So `isn't fsid_t` an internal SWIG type?

**Comment by wsfulton** [comment]
Add `-E` to the swig command to view the preprocessed code. That way you can work out where it comes from. fs_id_t does not come from SWIG.

**Comment by kisvegabor** [comment]
Okay, thank you. It's good to know that the issue is on my side so I can fix on my own :slightly_smiling_face:
