### ISSUE TITLE
%feature for adding __annotations__ in python

### ISSUE THREAD

**Issue by phwuil** [swig/swig#2443]
Hi,

If you want to wrap such a class in python :

```cpp
class Container {
   public:
    Container(int n);
    std::vector<int> getContent(int n) const;
};
```

For the method `Container::getContent()`, You can specify a `typemap(out)` for returning a `list of int` instead of an (even wrapped) `std::vector` :

```cpp
%typemap(out) std::vector<int> {
  $result = PyList_New(0);
  for (const auto& i : $1) {
    PyList_Append($result, PyInt_FromLong(i));
  }
}
```

You can even specify a documentation as a specific autodoc :
```cpp
%feature("autodoc") Container::getContent
"return the content (by copy)

Parameters
----------
n : int

Returns
-------
List[int]
"
```

However, do we (or could we) have a way to specify the annotations for this method, in order to generate 

```python
def getContent(self,n : int)->List[int]:
```

? For instance, even if it is kind of redundant with the autodoc, something like :

```cpp
%feature("python:annotations") Container::getContent
"
n: int
returns: List[int]
"
```

**Comment by ojwb** [comment]
We already have #735 open for this so closing as a duplicate.
