### ISSUE TITLE
syntax error with c++14 auto without trailing return type

### ISSUE THREAD

**Issue by burlen** [swig/swig#2446]
Swig 4.0.2 fails to parse the following and other similar variadic template functions. This one uses a fold expression (C++17) I'm not sure if that is the issue.
```
namespace teca_variant_array_util
{
template <typename TT, typename... PP> 
auto va_static_cast(PP &&... args)
{
    return std::make_tuple(static_cast<TT*>(args.get())...);
}
}
```
SWIG reports
```
teca_variant_array_util.h:21: Error: Syntax error in input(1).
```
21 is the opening brace of the function. I'm not trying to wrap this, it's included in the header of a wrapped class. In that context it's easy enough to hide from swig with preprocessor conditions. However, swig probably should probably parse it with out error or perhaps ignore and issue a warning.

**Comment by wsfulton** [comment]
SWIG supports the C++11 variadic template syntax, see https://swig.org/Doc4.1/CPlusPlus11.html#CPlusPlus11_variadic_templates. 

The problem is actually the `auto` return. SWIG has support for C++11 auto which requires the trailing return type. SWIG needs a tweak for C++14 auto. Compiling that code with g++ -std=c++11 gives:
```
example_wrap.cxx:248:34: error: ‘va_static_cast’ function uses ‘auto’ type specifier without trailing return type
 auto va_static_cast(PP &&... args)
                                  ^
example_wrap.cxx:248:34: note: deduced return type only available with -std=c++14 or -std=gnu++14
```

**Comment by wsfulton** [comment]
Cutdown testcase:
```c++
#include <tuple>
namespace teca_variant_array_util
{
auto va_static_cast()
{
    return std::make_tuple(0, 0);
}
}
```

**Comment by ojwb** [comment]
I'm not sure it's really feasible for SWIG to actually deduce the return type here.  Currently it just skips over function bodies entirely, but even if it parsed them it doesn't seem easy to deduce the type in general.

Fixing the parse error and skipping such functions would be a useful improvement though - then they could at least be wrapped by use of `%extend` or writing an inline forwarding function in the interface file for SWIG to wrap.

I had a very quick stab at adding a rule to the parser for this case, but it adds 11 additional shift/reduce conflicts:

```
diff --git a/Source/CParse/parser.y b/Source/CParse/parser.y
index 61fac2b2..7dc18987 100644
--- a/Source/CParse/parser.y
+++ b/Source/CParse/parser.y
@@ -3346,6 +3346,10 @@ c_decl  : storage_class type declarator cpp_const initializer c_decl_tail {
 	      if ($4.qualifier && $1 && Strstr($1, "static"))
 		Swig_error(cparse_file, cparse_line, "Static function %s cannot have a qualifier.\n", Swig_name_decl($$));
            }
+           | storage_class AUTO declarator cpp_const virt_specifier_seq_opt initializer LBRACE {
+	      Swig_warning(999, cparse_file, cparse_line, "FIXME.\n");
+	      skip_balanced('{','}');
+	   }
            ;
 
 /* Allow lists of variables and functions to be built up */
```

**Comment by ojwb** [comment]
If I drop `virt_specifier_seq_opt initializer` from the new grammar rule in the patch above that avoids introducing additional conflicts.  It means we wouldn't parse every possible case, but we don't parse any of these cases currently so this seems an improvement, especially as it should handle most of the more common cases.

**Comment by Future2100** [comment]
so how can we solve the issue?

**Comment by ojwb** [comment]
@Future2100 If you're happy for such methods to be skipped, my patch above with `virt_specifier_seq_opt initializer` removed would do that for a subset of such cases (including the one originally reported here and wsfulton's cut-down version).

It needs finishing off (sensible warning message writing explaining that SWIG doesn't support deducing the return type and ideally suggestions on what to do to ignore or wrap such cases, allocate a warning number and document it, and add a regression testcase for it).  I'll get to it when I can, but if you need it urgently feel free to work on it.

It'd be very helpful if SWIG parser could recover usefully from these sort of parse errors.  It's pretty common that a parse error is on something a user would be happy for SWIG to skip over.  I've pondered this a bit, and it seems we might be able to skip to a `;` or `}` (taking matching `{`...`}` into account) then start parsing from there.  Somebody needs to explore this a bit.  I might get to it at some point, but haven't yet got beyond the thought stage.

If you're hoping for SWIG to actually deduce the return type for an `auto` in a case like this, I'm really not sure that's feasible.  We don't try to parse function bodies at all currently (we just lex them and skipping matching `{` and `}` tokens), so parsing them is likely a big can of worms by itself even without the type deduction part.  However we could probably support a way to specify the return type, e.g. for wsfulton's case it might be something like:

```
%feature("returntype", "std::tuple<int, int>") va_static_cast();
```

Somebody would need to implement that, but it's probably fairly easy even if you're new to SWIG development.  I don't have a personal motivation to work on it though, and too much to do already.

**Comment by ojwb** [comment]
For how to manually specify the return type, I suspect wsfulton's neat trick from the decltype docs works here too, i.e. put something like this in the interface file:

```
std::tuple<int, int> va_static_cast();
%ignore va_static_cast();
%include header_to_wrap.h
```

Once the parse error here is fixed, the `%ignore` means SWIG will ignore the `va_static_cast` declaration in the header, but it'll wrap the one from the interface file, and call the actual `va_static_cast()` from the generated wrapper for that.

**Comment by ojwb** [comment]
I've tidied up the patch above and opened #2596.

I've spotted a hack to extend that to allow parsing the cases which need `virt_specifier_seq_opt initializer` in the rule, which is to abuse error recovery:

```
-          | storage_class AUTO declarator cpp_const LBRACE {
+          | storage_class AUTO declarator cpp_const error LBRACE {
```

The nasty thing it that then SWIG will accept anything in place of `error`, even if it isn't remotely valid C++.

There's precedent for doing this though, e.g.:

```
/* Out of class conversion operator.  For example:
     inline A::operator char *() const { ... }.
               
   This is nearly impossible to parse normally.  We just let the   
   first part generate a syntax error and then resynchronize on the
   CONVERSIONOPERATOR token---discarding the rest of the definition. Ugh.
               
 */
                 
               | error CONVERSIONOPERATOR {
                  $$ = 0;
                  skip_decl();
               }
               ;
```

**Comment by ojwb** [comment]
I've just had a look at the fuller version, but I'm failing to come up with a valid testcase.

`virt_specifier_seq_opt` can be empty or one of `overrride`, `final`, `final override` or `override final`.  However those are only valid on a virtual method, but GCC says a virtual method can't have a deduced return type:

```
cpp14_auto_return_type_wrap.cxx:1111:13: error: virtual function cannot have deduced return type
 1111 |     virtual auto b() const = 0 {
```

The `initializer` part is there to support `= 0`, `= delete` and `= default`, but these don't seem to be valid on a function definition - GCC rejects them at least:

```
cpp14_auto_return_type_wrap.cxx:1122:14: error: pure-specifier on function-definition
 1122 |     auto c() = default {
      |              ^
cpp14_auto_return_type_wrap.cxx:1126:20: error: pure-specifier on function-definition
 1126 |     auto d() const = 0 {
```

Also `= 0` doesn't seem to make sense for a non-virtual method anyway.

Looking at the C++ grammar, `function-definition` doesn't seem to allow anything after the `declarator`: https://alx71hub.github.io/hcb/#function-definition

Can anyone come up with a valid C++ example which isn't handled by the fix I committed?  This was:

```
storage_class AUTO declarator cpp_const LBRACE
```

In SWIG's grammar, `cpp_const` also allows `volatile`, `register`, `&` and `&&`, and combinations thereof.

**Comment by ojwb** [comment]
> Can anyone come up with a valid C++ example which isn't handled by the fix I committed?

The more I look into this the more confident I am that the fix is actually complete, so I've pushed a change to adjust the documentation to reflect that.

My works for all the examples provided here, but if anyone can come up with a valid C++ counter-example which it doesn't handle I'm happy to look into this more.

I also added some class methods to the testcase, and found that I can't seem to use the trick of providing a declaration with an explicit return type for those.

@wsfulton Any ideas?  This is essentially the same trick you documented for `decltype`, but applied to a function:

```
std::tuple<int, int> va_static_cast();
%ignore va_static_cast();
#pragma SWIG nowarn=SWIGWARN_CPP14_AUTO

%inline %{
#include <tuple>

auto va_static_cast()
{
    return std::make_tuple(0, 0);
}
```

However I couldn't find a way to make it work for class methods, e.g. consider:

```
struct X {
  auto a() {
    return "a";
  }
  auto e() const {
    return 2.71828;
  }
  static auto s() {
    return true;
  }
};
```

That's part of `Examples/test-suite/cpp14_auto_return_type.i` if you want to experiment.

**Comment by wsfulton** [comment]
> Any ideas? This is essentially the same trick you documented for decltype, but applied to a function

See 0893aa34caf0eea40cd06245c459656bfc1d04f2

**Comment by ojwb** [comment]
Ah cool.

@wsfulton Being able to `%ignore` them individually rather than suppressing the warning globally (ba2939097f24581df288c14a614d03729af220da) is much nicer too.  Can we easily make that work for `auto` variables too (i.e. WARN_CPP11_AUTO)?

**Comment by ojwb** [comment]
D'oh, the next commit does exactly that!

**Comment by SmrtSmrtnik** [comment]
Hello,
I think I am running into a case of this, but I am not well versed enough in SWIG or C++ to tell (I do a lot of Java and have been tasked to write SWIG conversion of a large C++ library into Java).

There is a templated method that takes in a std::string and parses it into one of several structs (think deserializing). That struct is what the template signifies.  Then, there is a conversion function it runs on that struct to get a different struct, and returns that as auto.  The conversion function is just a set of parameter type driven calls i.e.
```
FooC convert(Foo in);
BarC convert(Bar in);
// and so on
```
Then a templated struct is instantiated that takes as template those returned types (FooC, BarC, etc...), and that's returned as auto.
```
template <typename T>
struct DataHolder
{
  T data;
  //other metadata fields that are not templated
}
```

Method in question:
```
template <typename T> 
auto load(std::string str)
{
   //bunch of error checking on string
   T in = *reinterpret_cast<const T*>(d);
   auto data = convert(std::move(in));
   DataHolder<decltype(data)> retval;
   retval.data = data;
   //set retval metadata
   return retval;
}
```

In my .i file, I try to account for all the templates
```
%{
   #include "the hpp file holding the load method"
%}
%include "the hpp file holding the load method"

#define TEMP_WRAP(affectedClass)
%template(load_ ## affectedClass) load< ## affectedClass ## >;
#enddef

TEMP_WRAP(Foo)
TEMP_WRAP(Bar)
//etc...
```

`swig -C++ -java example.i`

Error messages:
```
the hpp file holding the load method: Warning: Unable to deduce auto return tyupe for 'load' (ignored).
example.i: Error: Template 'load' undefined.
//the Template 'load' undefined. is repeated for each TEMP_WRAP
```
