### ISSUE TITLE
syntax error with __forceinline

### ISSUE THREAD

**Issue by Guyiming** [swig/swig#2461]
I have the below code:
```cpp
#define FORCEINLINE __forceinline
```

```cpp
class Math
{
   //...
   template<class T>
   static __forceinline constexpr T Max(const T A, const T B)
   {
         return (A >= B) ? A : B;
   }

   template<class T>
   static FORCEINLINE  constexpr T Min(const T A, const T B)
   {
       return (A <= B) ? A : B;
   }
}
```
The `Max` and `Min` method both prompt `Error: Syntax error in input(3).`。

Does SWIG doesn't support `__forceinline`?

**Comment by Guyiming** [comment]
When remove `__forceinline` or `FORCEINLINE`, all works good.

**Comment by ojwb** [comment]
SWIG generally aims to support standard C and C++.  Even that's an ambitious scope (there are plenty of standardised features we don't yet support, especially in newer C++ standards) so trying to support compiler-specific extensions is probably too much of an ask.

I don't know what the exact semantics your compiler uses for `__forceinline` are, but you can probably just define it to be `inline` for SWIG's preprocessor - e.g. `swig -D__forceinline=inline ...`.  Another option is to define it to be empty.

**Comment by Guyiming** [comment]
Noted, Thanks @ojwb  👍
