### ISSUE TITLE
use of deleted function 'std::atomic_bool& std::atomic_bool::operator=(const std::atomic_bool&)

### ISSUE THREAD

**Issue by jigelang** [swig/swig#2462]
after genrate wrap file . compile it i got a error . it seems used a delete function.

the orignal cpp code:
`std::atomic_bool g_initialized(false);`
error :
/swig/swig_wrap.cxx: In function 'void CSharp_Test_g_initialized_set(void*)':
/swig/swig_wrap.cxx:336:8: error: use of deleted function 'std::atomic_bool& std::atomic_bool::operator=(const std::atomic_bool&)'
   arg1 = *argp1;

**Comment by ojwb** [comment]
Closing as duplicate of #1185, which contains a solution.
