### ISSUE TITLE
%array_class with complicated types

### ISSUE THREAD

**Issue by Guyiming** [swig/swig#2464]
I want to define a `PairUlongUlongArray` and try the below:
![image](https://user-images.githubusercontent.com/1835638/208387271-004d35a3-12d6-47bd-8597-05e64122fc29.png)
But there is an error when generating: ` Error: Macro '%array_class' expects 2 arguments`。

I know the complicated types are not allowed in `%array_class`. 
![image](https://user-images.githubusercontent.com/1835638/208386394-54a212d7-7f3b-468f-a463-76a0dbe87f2c.png)

Can someone help tell me what should I do?

**Comment by Guyiming** [comment]
I tried add a `%inline` block :
```
//...
%typemap(cstype) unsigned int "uint";
%typemap(imtype) unsigned int "uint";

%inline %{
	std::pair<unsigned __int64,unsigned __int64> GetUlongUlongArrayItem(std::pair<unsigned __int64,unsigned __int64>* items,int index)
	{
		return items[index];
	};
%}
%template(PairUlongUlong) std::pair<unsigned __int64,unsigned __int64>;
//...
```
But the generated code is a little weird:
```csharp
public class TestModule {
  public static PairUlongUlong GetUlongUlongArrayItem(PairUlongUlong items, int index) {
    PairUlongUlong ret = new PairUlongUlong(ChaosEditorModulePINVOKE.GetUlongUlongArrayItem(PairUlongUlong.getCPtr(items), index), true);
    return ret;
  }
}
```
I doubt it can work normally.

**Comment by wsfulton** [comment]
A couple comments/pointers:

* Use the std_pair.i library file for wrapping `std::pair`.
* As `%array_class` only supports simple types, write a similar struct by hand that does something similar. 
* You might be able to work around the _2 arguments_ error via varargs tricks like adapting the macro to use varargs or passing the argument within () brackets.

Closing, not an issue.
