### ISSUE TITLE
To convert a Perl hash to a C++ map using SWIG

### ISSUE THREAD

**Issue by shashisonam** [swig/swig#2466]
Need a Simple example in c++ and perl where we can convert Perl Hash into C++ stl map via SWIG interface.
Below are the version in my linux supporting .
Swig Version - swig/4.0.1
GCC Version - gcc/10.3.0
Perl Version - perl/5.18.2_64
Need a working example for this as I am working on this part but stuck in Perl Hash to C++ Map conversion.

I am new to SWIG and I wanted to write SWIG interface where we can pass the Perl Hash and then it converts it into C++ stl map or unordered_map.
Do you have any example for that like swig interface file and then c++ file and then perl file.
I tried with those but it seems not working for me.
tried with below sample code but it seems not working for me.

example.i - swig interface file;

%module example

%{
#include "example.h"
%}

%include "std_map.i"

%template(StringIntMap) std::map<std::string, int>;

%include "example.h"

example.h - C++ header file

#include <map>
#include <string>

void processMap(std::map<std::string, int> &m) {
 
}

perl file - test.pl
#!/opt/perl_5.18.2/bin/perl

use strict;
use warnings;
use Data::Dumper;
use lib '.';
use example;

my %hash = (
  "key1" => 1,
  "key2" => 2,
  "key3" => 3
);

example::processMap(\%hash);

the compilation and then linked with the shared object of that but it is not working , then could you please provide me the proper solution for that like we need to pass Perl Hash and then this hash will get stored into c++ stl map or unordered_map via SWIG .This needs to be finished by this week as next week I have to do the presentation to my senior official.Please do help me on this please.

**Comment by ojwb** [comment]
Reporter opened discussion #2473 with the same question, and that's been answered so closing this as a duplicate.  Please try to avoid duplicate tickets, but especially so for your own tickets - it uses up limited volunteer time handling them.
