### ISSUE TITLE
Feature Proposal- Support for editing alloc routines(malloc,calloc etc) in _wrap.c file via interface file

### ISSUE THREAD

**Issue by mayank-2105** [swig/swig#2482]
Hi, Using default malloc, calloc and free in _wrap.c file may cause memory leaks in code, so I have written custom alloc routines like my_malloc, my_calloc and my_free wherein I pass the type of structure as a string as well for better tracking. For using them instead of default routine, I am editing Printf statements in code files like Souce/Swig/cwrap.c file(or basically any other file)  for ex-

String *Swig_cconstructor_call(const_String_or_char_ptr name) {
  //swig src code
  Printf(func, "calloc(1, sizeof(%s))", name); //edit this line
  //swig src code
}

to be edited to something like

String *Swig_cconstructor_call(const_String_or_char_ptr name) {
  //swig src code
  Printf(func, "my_calloc(1, \"%s\", sizeof(%s))", name, name); //new Printf statement
  //swig src code
}

**We can edit this in the file itself and then compile via make.

We wish to make these edits via some command/option from the interface file.**

**Sample Proposal- Some %edit statement in interface file which can replace some x piece of code with y piece in _wrap.**c file

For ex- %edit(x,y) x gets replaced with y

In our case this will be like-
%edit(Printf(func, "calloc(1, sizeof(%s))", name),Printf(func, "my_calloc(1, \"%s\", sizeof(%s))", name, name))

**Comment by ojwb** [comment]
It's probably possible, though a potential wrinkle is that there may be cases where SWIG allocates things with `malloc()` which are deallocated by the target language and/or where the target language allocates and returns a pointer which SWIG releases with `free()` as these couldn't just be replaced with a different allocator.  A simple search and replace of all uses of `malloc()`, etc may break things.

However, for your end goal of leak checking I'd suggest a dedicated leak checking tool - based on personal experience I'd suggest trying either valgrind (which can be applied at runtime) or leak sanitiser (which requires recompilation, but is lower overhead).  These are likely to be much more useful - for example they can tell you exactly when a block got leaked (i.e. a backtrace for the code location when the last pointer to a leaked block went away)

**Comment by wsfulton** [comment]
Also if you off-the-shelf memory analyser tools are not suitable, consider using glibc malloc hooks https://www.gnu.org/savannah-checkouts/gnu/libc/manual/html_node/Hooks-for-Malloc.html. LD_PRELOAD is also a common trick that can be used to override malloc/calloc etc.

**Comment by ojwb** [comment]
There are numerous existing tools/approaches which are as good or better than anything we could realistically support specifically within SWIG, and we're already stretched in terms of developer time, so I'm going to close this as being unnecessary scope creep.
