### ISSUE TITLE
how to use enum of array for python ?

### ISSUE THREAD

**Issue by Tysonliang** [swig/swig#2485]
I have a class as flow:

class TPC_ConsoleAct{
enum TPC_FDState : uint32_t
{
    FD_STATE_UNKNOWN,
    FD_STATE_MACHINE
};
std::array<TPC_FDState, 2>& TPC_ConsoleAct::funcState()
{
    return m_funcState;
}
std::array<TPC_FDState, 2> m_funcState;
}

When i wrapper through swig:
i use it in my python code as flow:
a1 = TPC_ConsoleAct()
b1 = a1.funcState()[1]

It thow up a expection:
return _tpc_consoleWrapper.TPC_FDState_2_array___getitem__(self, *args)
TypeError: Wrong number or type of arguments for overloaded function 'TPC_FDState_2_array___getitem__'.
  Possible C/C++ prototypes are:
    std::array< TPC_FDState,2 >::__getitem__(PySliceObject *)
    std::array< TPC_FDState,2 >::__getitem__(std::array< TPC_FDState,2 >::difference_type) const

**Comment by wsfulton** [comment]
This works for me:
```swig
%include <std_array.i>

%inline %{
#include <array>
class TPC_ConsoleAct {
public:
  enum TPC_FDState : uint32_t
  {
    FD_STATE_UNKNOWN,
    FD_STATE_MACHINE
  };
  std::array<TPC_FDState, 2>& funcState()
  {
    return m_funcState;
  }
  std::array<TPC_FDState, 2> m_funcState;
};
%}

%template(Array_TPC_FDState_2) std::array<TPC_ConsoleAct::TPC_FDState, 2>;
```

**Comment by Tysonliang** [comment]
when i use three file(xx.hpp,xx.cpp,xx.i), it is not work.

**Comment by Tysonliang** [comment]
this is tpc_consoleact.hpp file
`
#include <array>
enum TPC_FDState : uint32_t
  {
    FD_STATE_UNKNOWN,
    FD_STATE_MACHINE
  };
class TPC_ConsoleAct {
public:
  std::array<TPC_FDState, 2>& funcState();
  std::array<TPC_FDState, 2> m_funcState;
};`
this is tpc_consoleact.cpp file:
#include "tpc_consoleact.hpp"
std::array<TPC_FDState, 2>& TPC_ConsoleAct::funcState()
  {
    return m_funcState;
  }

this is tpc_consoleact.i file:
%module tpc_consoleact
%inline%{
#include "tpc_consoleact.hpp"
%}
