### ISSUE TITLE
swig crash when attempting to parse header with std::numeric_limits template

### ISSUE THREAD

**Issue by yayay** [swig/swig#2486]
I get an error and a crash when trying to generate a wrapper for the following C++ code:

```
#pragma once

#include <limits>

typedef struct {
   unsigned char myarray[std::numeric_limits<unsigned char>::max()];
} array_t;
```

The error is as follows:
> Bad template type passed to SwigType_remember: a(std::numeric_limits< unsigned char >::max()).unsigned char
> swig: Swig/typesys.c:1706: SwigType_remember_clientdata: Assertion `0' failed.
> Aborted (core dumped)

**Comment by yayay** [comment]
It seems to relate to this issue: https://sourceforge.net/p/swig/bugs/983/

**Comment by ojwb** [comment]
I think you're right that it's related - essentially we're not coping with an array dimension expression which contains a `<` character.

**Comment by yayay** [comment]
For our use case, looks like we can remove this "bad template type check" to fix this issue.

```
--- a/Source/Swig/typesys.c	2023-01-24 08:05:40.616618362 -0500
+++ b/Source/Swig/typesys.c	2023-01-24 08:05:47.560535891 -0500
@@ -1596,14 +1596,6 @@
   /*Printf(stdout,"t = '%s'\n", t);
      Printf(stdout,"fr= '%s'\n\n", fr); */
 
-  if (t) {
-    char *ct = Char(t);
-    if (strchr(ct, '<') && !(strstr(ct, "<("))) {
-      Printf(stdout, "Bad template type passed to SwigType_remember: %s\n", t);
-      assert(0);
-    }
-  }
-
   h = Getattr(r_mangled, mt);
   if (!h) {
     h = NewHash();

```

**Comment by ojwb** [comment]
I tried the approach of relaxing the check in 2227dc9e53dfe7aa236523058de139b5b3d5b6cc.  The relaxed check there wouldn't help for your case, but my point here is that this broke with SWIG/Go so it's not a suitable fix to apply even if it happens to work for you.  Other parts of SWIG's "type string" type system also need changes for this to work properly.

I made a second attempt in 0ff9a0959ab0fc537c7db53fb94efb7534b45925 but that broke with C# and Java, so I had to revert both commits (hmm, except I don't seem to have fully reverted the first, only the new testcase it added).

Incidentally, you don't seem to be using the latest SWIG version as the code you quote above is only like that in SWIG 4.0.0 and earlier (my attempted fix and incomplete revert left it changed).  Not testing with the latest release is a useful thing to mention in a bug report.

**Comment by yayay** [comment]
You are right that the patch I mention above is not for the latest master branch as we are developping with a older SWIG release (3.0.12). However, during my testing, I did test the master branch which also show the "Bad template type" error with the code snippet found in my first post. The error shown in my first post is from a SWIG compiled with the master branch.

**Comment by ojwb** [comment]
I've improved the error and eliminated the abort and core dump - now you get this error and an exit with non-zero status:

```
:1: Error: Array size expressions containing a '<' character not fully supported
```

(The `:1:` is meant to be FILE:LINE, but for some reason that's not set on the SwigType object at this point.)

As noted above my original attempted fix for https://sourceforge.net/p/swig/bugs/983/ is actually still in place (just without the testcase) and nobody's reported problems with it so reverting it doesn't seem warranted.  I've discovered the testcase works for Go if I change the type to `char` instead of `int` so I'm going to add that back as a regression test.  

Need to investigate if we can just relax/remove this check to solve this case too.

**Comment by ojwb** [comment]
I've pushed a branch with the check removed completely (https://github.com/swig/swig/tree/template-in-array-size-fix) and a simple test case.

We do know that some such cases can trip up SWIG/Go, but I've not seen problems with any other target language, and such cases working for most target languages seems an improvement over them being rejected at parse time.  I'm not clear exactly what's going wrong for Go - perhaps I need to get my head round that to understand the possible downsides here.

**Comment by ojwb** [comment]
Hmm, some compilation failures in tests such as:
```
arrays_global_wrap.cxx:410:66: error: array bound is not an integer constant before ‘]’ token
  410 |   unsigned char myarray[std::numeric_limits<unsigned char>::max()];
      |                                                                  ^
```

Looks like this code is only valid in C++11 and later:

```
$ g++ -std=c++11 -xc++ -c test.i
$ g++ -std=c++98 -xc++ -c test.i
test.i:6:65: error: size of array ‘myarray’ is not an integral constant-expression
    6 |    unsigned char myarray[std::numeric_limits<unsigned char>::max()];
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
```

I'll need to move the testcase to a different file.
