### ISSUE TITLE
Using swig from `FetchContent`

### ISSUE THREAD

**Issue by LecrisUT** [swig/swig#2487]
Will it be possible to make the `swig_add_library` use a bundled version of swig, or more ideally one retrieved from `FetchContent` in the event of `find_package` failing? This would be useful for HPC environments that either might not have a recent version of swig, if they have one at all. The users there tend to not be code developers, but often still expected to compile the code from scratch, so it would be beneficial to make the swig integration as smooth as possible.

**Comment by ojwb** [comment]
As best I can make out from `git grep`, `find_package` is a cmake thing and the only uses of it we have are for finding PCRE2 and bison if you choose to build swig with cmake (which isn't the primary build system).

It sounds like you're not asking about that though, but about cmake's SWIG support - we don't maintain that so probably need to ask elsewhere (cmake developers I'd guess but not sure).

**Comment by ojwb** [comment]
No response so closing.

**Comment by LecrisUT** [comment]
I forgot to get back on this.

Yes this is a CMake support thing, but it is not part of upstream cmake. Basically the cmake project file should be improved a bit.

The thing is that using this will allow easier compilation workflow for cmake project, particularly on HPCs where you do not have access to install to system, the Swig version is significantly outdated, and the users are not developers/coders. For this it is worth making compilation of a project as easily as possible, i.e. just running:
```console
# On my_application folder (that uses Swig internally) 
$ mkdir build && cd build
$ cmake ..
$ cmake --build .
$ cmake --install .
```

To implement this, we need to migrate the `find_package` from cmake upstream to the Swig project itself. Then with minimal changes we can convert the custom commands like [`add_swig_library`](https://cmake.org/cmake/help/latest/module/UseSWIG.html#command:swig_add_library) to use the target executable that is [already implemented](https://github.com/swig/swig/blob/b9153698db0162934ec82b3a2023e78836af79a6/CMakeLists.txt#L140-L151). This will make sure swig is built with the options we want (like with the Fortran support that is not merged yet), and will use that executable.

**Comment by LecrisUT** [comment]
@ojwb can you re-open this issue, I want to address it in #2646
