### ISSUE TITLE
Syntax error - possibly a missing semicolon

### ISSUE THREAD

**Issue by OLFDB** [swig/swig#2496]
I'm using swig 4.1.1 on macos Ventura 13.1 with OpenJDK Runtime Environment Temurin-19+36 (build 19+36) and try to create java classes for attr_def.h using

`swig -java -module example example.i`

I simply get a `attr_def.h:54: Error: Syntax error - possibly a missing semicolon (';')` even with all debug options enabled.

I think there occurs an issue during the macro expansion for ATTR_UNUSED (see example.i). 

The macro expansion works fine in clang, 
If I remove %include "attr_def.h" from example.i swig creates example_wrap.c and

`gcc -E -c example_wrap.c  -I$JAVA_INCLUDE -I/$JAVA_INCLUDE/darwin`

Shows 
```
enum attr_type {
# 205 "example_wrap.c"
# 1 "./attr_def.h" 1
# 46 "./attr_def.h"
attr_none=0x00000000,
attr_any,
attr_any_xml,

attr_type_item_begin=0x00010000,
attr_town_streets_item,
ATTR_UNUSED_52,
ATTR_UNUSED_53,
attr_street_item,
ATTR_UNUSED_55,
attr_position_sat_item,
attr_current_item,
attr_type_item_end=0x0001ffff,
...
```

[Archiv.zip](https://github.com/swig/swig/files/10532245/Archiv.zip)

**Comment by ojwb** [comment]
Looking at the error location, this is the context:

```
    52	ATTR_UNUSED
    53	ATTR_UNUSED
    54	ATTR(street_item)
    55	ATTR_UNUSED
    56	ATTR(position_sat_item)
```

Looking at the output of SWIG's preprocessor (`swig -E -java example.i`) shows the problem - you've not defined `ATTR_UNUSED` for SWIG (the definition inside `%{`...`%}` is only inserted into the generated code not used for SWIG's preprocessing) so those lines become:

```
ATTR_UNUSED
ATTR_UNUSED
extern int street_item;
ATTR_UNUSED
extern int position_sat_item;
```

Your example processes successfully with `swig -DATTR_UNUSED= -java example.i` so closing as this isn't a bug in SWIG.

**Comment by OLFDB** [comment]
Thank you for looking into it. This is not a solution, as the value ATTR_UNUSED is wrong. It needs to be a unique value which is created by the macros

```
#define ATTR_UNUSED ATTR_UNUSED_L(__LINE__)
#define ATTR_UNUSED_L(x) ATTR_UNUSED_WITH_LINE_NUMBER(x)
#define ATTR_UNUSED_WITH_LINE_NUMBER(x) ATTR_UNUSED_##x,
```

The swig preprocessor output needs to look like:

```
attr_none=0x00000000,
attr_any,
attr_any_xml,

attr_type_item_begin=0x00010000,
attr_town_streets_item,
ATTR_UNUSED_52,
ATTR_UNUSED_53,
attr_street_item,
ATTR_UNUSED_55,
```

How can I achieve that?

**Comment by ojwb** [comment]
You aren't defining those for SWIG though, only for the compiler, so SWIG uses the other "mode" that your header can work in rather than the "contents of an enum" mode you want it to.

Your example works for me with these changes:

```
diff -u orig/attr_def.h ./attr_def.h
--- orig/attr_def.h	2023-01-29 23:37:58.000000000 +1300
+++ ./attr_def.h	2023-04-19 18:18:25.159189462 +1200
@@ -34,6 +34,9 @@
 #endif
 
 /* prototypes */
+#ifdef SWIG
+enum {
+#endif
 
 /* common */
 #ifndef ATTR
@@ -541,6 +544,11 @@
 ATTR2(0x000dffff,type_group_end)
 ATTR2(0x000e0000,type_item_type_begin)
 ATTR2(0x000effff,type_item_type_end)
+
+#ifdef SWIG
+};
+#endif
+
 #ifdef __cplusplus
 }
 #endif
diff -u orig/example.i ./example.i
--- orig/example.i	2023-01-30 17:23:17.000000000 +1300
+++ ./example.i	2023-04-19 18:18:38.531218080 +1200
@@ -27,4 +27,9 @@
 
 /* Let's just grab the original header file here */
 
+#define ATTR2(x,y) attr_##y=x,
+#define ATTR(x) attr_##x,
+#define ATTR_UNUSED ATTR_UNUSED_L(__LINE__)
+#define ATTR_UNUSED_L(x) ATTR_UNUSED_WITH_LINE_NUMBER(x)
+#define ATTR_UNUSED_WITH_LINE_NUMBER(x) ATTR_UNUSED_##x,
 %include "attr_def.h"
```

Note that unfortunately you currently can't include the contents of an enum block from another file, so I've had to put the `enum {` and `};` in the header, with a `#ifdef SWIG` conditional around them (that's bug #233).
