### ISSUE TITLE
Incorrect Wrapper Generated for `constexpr` in Node 19 on Mac OS 

### ISSUE THREAD

**Issue by maschad** [swig/swig#2506]
Environment Details:

```
Node.js v19.7.0

Mac OS X 13.2.1

Darwin x86_64
```

I know this is a bit pre-mature considering [the current stage of compatibility with C++20](https://swig.org/Doc4.1/SWIGDocumentation.html#CPlusPlus20) but it seems that when generating Node 19 (which is not a stable current release)  the incorrect wrappers are generated _seemly_ due to toolchain incompatibility. 

```bash
In file included from /usr/local/include/node/v8-object.h:9:
/usr/local/include/node/v8-maybe.h:106:69: error: expected '(' for function-style cast or type construction
  template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/include/node/v8-maybe.h:123:43: error: no template named 'is_lvalue_reference_v' in namespace 'std'; did you mean 'is_lvalue_reference'?
template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
                                     ~~~~~^~~~~~~~~~~~~~~~~~~~~
                                          is_lvalue_reference
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:910:29: note: 'is_lvalue_reference' declared here
struct _LIBCPP_TEMPLATE_VIS is_lvalue_reference : _BoolConstant<__is_lvalue_reference(_Tp)> { };
                            ^
In file included from blst_wrap.cpp:178:
In file included from /usr/local/include/node/node.h:73:
In file included from /usr/local/include/node/v8.h:24:
In file included from /usr/local/include/node/v8-array-buffer.h:13:
In file included from /usr/local/include/node/v8-object.h:9:
/usr/local/include/node/v8-maybe.h:123:67: error: expected '(' for function-style cast or type construction
template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
``` 

The `is_lvalue_referencev` is added for `constexpr` as mentioned [here](https://stackoverflow.com/questions/64286346/error-no-template-named-is-same-v-in-namespace-std-did-you-mean-is-same) and thus the [correct `blst` bindings for Node 19 cannot be generated](https://github.com/ChainSafe/blst-ts/issues/80). 

This could be potentially resolved using a helper variable template defined [here](https://en.cppreference.com/w/cpp/types/is_same)

**Comment by wsfulton** [comment]
There is a misunderstanding here of compatibility with C++20. The generated code is C++20 compatible. What is incomplete in SWIG is if you feed some C++20 features into SWIG you might get a SWIG syntax error.

I've run the SWIG test-suite with node 19 and C++20 and the it passes fine, including the two supported C++20 test cases we have. See https://github.com/wsfulton/swig/actions/runs/4321291675/jobs/7542358030. I also tried node 19 and C++17 as the errors reported are C++17 related and the test-suite works fine again, see https://github.com/wsfulton/swig/actions/runs/4321291675/jobs/7542357949.

Regarding your errors reported above, it looks to me as though you are compiling your wrappers without the correct c++ std flags. The error above is something from Node headers (not SWIG generated code!) that is using a C++17 template. Either you are not using `-std=c++17` or higher or you are not including `type_traits` which provides `std::is_lvalue_reference_v`. More likely the former as I would expect node.h to include the appropriate headers it requires.

**Comment by maschad** [comment]
You were correct @wsfulton ! Thanks so much for your help.
