### ISSUE TITLE
"Error: Syntax error in input(3)" when any identifier is called "complex"

### ISSUE THREAD

**Issue by ThomasJClark** [swig/swig#252]
This .i file produces a syntax error:

```
struct foo {
    int complex;
};
```

This one doesn't:

```
struct foo {
    int simple;
};
```

I guess this is because SWIG assumes that I'm using the `complex` macro, even though I didn't include complex.h.  `complex` isn't a reserved word in C, so it's perfectly valid to use it as an identifier.

**Comment by ojwb** [comment]
If you aren't using `<complex.h>` anywhere, then you can define complex to something else which at least allows SWIG to process this example, and may provide a workaround for at least some situations:

```
$ swig -module xxx complex.i
complex.i:2: Error: Syntax error in input(3).
$ swig -module xxx -Dcomplex=complex_ complex.i
$
```

I'm wondering if SWIG should be changed to understand `_Complex` and not treat `complex` as a reserved keyword.  Then if you want to wrap an API which uses `complex`, you can just use `#define complex _Complex` in your SWIG interface file.

**Comment by wsfulton** [comment]
This is fixed now and required one small change in addition to the patch in #1770.
