### ISSUE TITLE
SWIG preprocessor: problem when expanding macros with arguments to macros w/o arguments

### ISSUE THREAD

**Issue by mmomtchev** [swig/swig#2525]
Consider this:

`attr.i`
```
#define __attribute__(x)
%include "attr.h"
```

`attr.h`
```cpp
#define my_bad_attr __attribute__
#define my_good_attr(x) __attribute__(x)

int bad my_bad_attr((used));
int good my_good_attr((used));
```

Launch:
```
swig -E -javascript -node -c++ attr.i 
```

Result:

```
%endoffile
%endoffile
%includefile(maininput="attr.i") "attr.i" %beginfile

%includefile "attr.h" %beginfile



int bad __attribute__((used));
int good ;
%endoffile
%endoffile
```

**Comment by ojwb** [comment]
Probably the same underlying problem as #1881.

**Comment by mmomtchev** [comment]
@ojwb yes, this might be the same issue
I just found it:
* `expand_macro` does `my_bad_attr` expansion on this line `int bad my_bad_attr((used));`
* it ends applying the transformation `my_bad_attr` -> `__attribute__`
* it recursively launches a second `expand_macro` - but this time it does `__attribute__` on `__attribute__` - it uses only the replaced part for the second expansion
* it correctly identifies that its `__attribute__` macro requires an argument - which is absent in its string - and skips the expansion
