### ISSUE TITLE
Warning 472

### ISSUE THREAD

**Issue by alex4747-pub** [swig/swig#2528]
Hi I am working on wrapping c++ into python3 using swig 4.0.2 and I got warning 472 - that is not documented anywhere. Please, help.

**Comment by ojwb** [comment]
Looking at the code, it seems like you have an `in` typemap with no corresponding `typecheck` typemap - you need the latter in order for the dispatch function to resolve a function overloaded on that type.

**Comment by ojwb** [comment]
See https://www.swig.org/Doc4.1/Typemaps.html#Typemaps_nn27 for more details.

**Comment by ojwb** [comment]
I did
