### ISSUE TITLE
Swig requires default constructor for no good reason

### ISSUE THREAD

**Issue by jwuttke** [swig/swig#2530]
In C++ code like this
```
class SimulationResult {
public:
    SimulationResult(); // required by Swig
    SimulationResult(const Datafield& data, const ICoordSystem* coords);
    ~SimulationResult();

    SimulationResult(const SimulationResult& other);
    SimulationResult(SimulationResult&& other) noexcept;

    SimulationResult& operator=(SimulationResult&& other) noexcept;
    ...
};
```
I would like to remove the default constructor `SimulationResult()`, which would allow for further improvements of my code. However, I cannot do so because compilation of the Swig-generated xxx_wrap.cpp then fails in the following code fragment
```
SWIGINTERN PyObject *_wrap_FitObjective_simulationResult__SWIG_0(PyObject *self, Py_ssize_t nobjs, PyObject **swig_obj) {
  PyObject *resultobj = 0;
  FitObjective *arg1 = (FitObjective *) 0 ;
  size_t arg2 ;
  void *argp1 = 0 ;
  int res1 = 0 ;
  size_t val2 ;
  int ecode2 = 0 ;
  SimulationResult result;
  
  if ((nobjs < 2) || (nobjs > 2)) SWIG_fail;
  res1 = SWIG_ConvertPtr(swig_obj[0], &argp1,SWIGTYPE_p_FitObjective, 0 |  0 );
  if (!SWIG_IsOK(res1)) {
    SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "FitObjective_simulationResult" "', argument " "1"" of type '" "FitObjective const *""'"); 
  }
  arg1 = reinterpret_cast< FitObjective * >(argp1);
  ecode2 = SWIG_AsVal_size_t(swig_obj[1], &val2);
  if (!SWIG_IsOK(ecode2)) {
    SWIG_exception_fail(SWIG_ArgError(ecode2), "in method '" "FitObjective_simulationResult" "', argument " "2"" of type '" "size_t""'");
  } 
  arg2 = static_cast< size_t >(val2);
  result = ((FitObjective const *)arg1)->simulationResult(arg2);
  resultobj = SWIG_NewPointerObj((new SimulationResult(result)), SWIGTYPE_p_SimulationResult, SWIG_POINTER_OWN |  0 );
  return resultobj;
fail:
  return NULL;
}
```
The SimulationResult default constructor is required for no other reason than the very old-style advance declaration
```
SimulationResult result;
```
Why not just omit that line, and merge the type declaration with the assignement in
```
SimulationResult result = ((FitObjective const *)arg1)->simulationResult(arg2);
```
?

**Comment by ojwb** [comment]
You don't provide a full reproducer, but hacking the snippet provided I can't reproduce this:

```
%module x

class SimulationResult {
public:
//    SimulationResult(); // required by Swig
    SimulationResult(int x, int y);
    ~SimulationResult();

    SimulationResult(const SimulationResult& other);
    SimulationResult(SimulationResult&& other) noexcept;

    SimulationResult& operator=(SimulationResult&& other) noexcept;
};

SimulationResult f();
```

With this as `test.i`, `swig -c++ -python test.i` generates:

```
SWIGINTERN PyObject *_wrap_f(PyObject *self, PyObject *args) {
  PyObject *resultobj = 0;
  SwigValueWrapper< SimulationResult > result;
  
  (void)self;
  if (!SWIG_Python_UnpackTuple(args, "f", 0, 0, 0)) SWIG_fail;
  result = f();
  resultobj = SWIG_NewPointerObj((new SimulationResult(result)), SWIGTYPE_p_SimulationResult, SWIG_POINTER_OWN |  0 ); 
  return resultobj;                                                             fail:
  return NULL;
}
```

SWIG sees there's no default constructor and uses `SwigValueWrapper` (declaring at the point of assignment is hard to do in general as that assignment may be inside a block in the typemap that provides the assignment code, hence `SwigValueWrapper` was invented).

If that's not happening for you, we really need a small self-contained reproducer demonstrating the problem.

**Comment by ojwb** [comment]
If instead of commenting out the default constuctor I explicitly delete it then I can reproduce the problem:

```
    SimulationResult() = delete;
```

@jwuttke Is that what your full case is doing?  If so, that's #1644.

If not, I think we need a small, self-container reproducer.

**Comment by jwuttke** [comment]
No, delete is not needed. If another constructor is provided, then the default constructor is automatically deleted.

Extracting a self-contained reproducer from our huge project would be quite some work. I'd better start from scratch. Is there some minimal CMake/C++/Python/Swig example that could help me to get started?

Anyway, that example will just confirm that Swig generates old-fashioned C++ code like
```
MyClass result;
...
result = ((FitObjective const *)arg1)->MyClass(arg2);
```
instead of just the one line
```
MyClass result = ((FitObjective const *)arg1)->MyClass(arg2);
```

So the more important question is: Which parts of the Swig source code are generating the above, and how difficult would it be to improve them?

**Comment by ojwb** [comment]
> So the more important question is: Which parts of the Swig source code are generating the above, and how difficult would it be to improve them?

It comes from the `out` typemaps in many (maybe even most) of the files under `Lib/`, but it's going to be hard to fix - as I already said above: "_(declaring at the point of assignment is hard to do in general as that assignment may be inside a block in the typemap that provides the assignment code, hence `SwigValueWrapper` was invented)._"

`SwigValueWrapper` was invented to solve this problem and should just get used automatically when needed, but for some reason SWIG doesn't spot that it should be using it in your situation.  Working out why not really is the best place to focus investigations, and that's the reason why a reproducer would be really useful.  A reproducer would also give us the basis of a regression testcase.

**Comment by wsfulton** [comment]
@jwuttke use the preprocessor `swig -E` to generate the input code for diagnosis. You should then be able to feed this back into SWIG to replicate the problem and post it somewhere for us to have a look.

For a workaround to force SwigValueWrapper, use
```swig
%feature("valuewrapper") SimulationResult;
``` 

see https://swig.org/Doc4.1/SWIGPlus.html#SWIGPlus_nn19.

**Comment by jwuttke** [comment]
Here comes my minimal example: https://github.com/jwuttke/swig2530/tree/main.

As far as I can tell, it takes two Swig libraries to reproduce the problem.
