### ISSUE TITLE
Remove SWIG/D - it doesn't work with current D releases

### ISSUE THREAD

**Issue by ojwb** [swig/swig#2538]
The CI for D has been disabled since the switch to GHA.

I had a poke at it to try to get it running.  The conclusions aren't good.

We use pre-built D packages from https://downloads.dlang.org/releases/2.x/ - the older builds here don't work on the Ubuntu releases which GHA still supports (due to depending on libcurl3, which 20.04 and newer releases don't have).  I did a kind of binary chop and found the oldest build which installs on ubuntu-20.04 is D 2.080.0.  However this and every newer version I've tried (2.081.0, 2.081.2, 2.082.1, 2.084.1, 2.086.1 and 2.103.0 - currently the most recent there) don't like the code SWIG generates:

```
+ make -j2 check-d-examples 'CFLAGS=-Werror -fdiagnostics-show-option -std=gnu89 -Wno-long-long -Wreturn-type -Wmissing-field-initializers -Wdeclaration-after-statement' 'CXXFLAGS=-Werror -fdiagnostics-show-option -std=c++98 -Wno-long-long -Wreturn-type -Wmissing-field-initializers'
checking Examples/d/callback
checking Examples/d/class
example.d(81): Error: mutable method `example.Callback.run` is not callable using a `const` `this`
example.d(63): Error: template instance `example.Callback.swigIsMethodOverridden!(void delegate(), void function(), run)` error instantiating
make[3]: *** [../../../Makefile:322: d_compile] Error 1
make[2]: *** [../example.mk:48: build] Error 2
make[2]: Target 'check' not remade because of errors.
make[1]: *** [Makefile:215: callback.actionexample] Error 2
checking Examples/d/constants
checking Examples/d/enum
checking Examples/d/extend
checking Examples/d/funcptr
example.d(105): Error: mutable method `example.Employee.getTitle` is not callable using a `const` `this`
example.d(71): Error: template instance `example.Employee.swigIsMethodOverridden!(string delegate(), string function(), getTitle)` error instantiating
example.d(105): Error: mutable method `example.Employee.getName` is not callable using a `const` `this`
example.d(76): Error: template instance `example.Employee.swigIsMethodOverridden!(string delegate(), string function(), getName)` error instantiating
example.d(200): Error: mutable method `example.Employee.getTitle` is not callable using a `const` `this`
example.d(182): Error: template instance `example.Manager.swigIsMethodOverridden!(string delegate(), string function(), getTitle)` error instantiating
example.d(200): Error: mutable method `example.Employee.getName` is not callable using a `const` `this`
example.d(187): Error: template instance `example.Manager.swigIsMethodOverridden!(string delegate(), string function(), getName)` error instantiating
make[3]: *** [../../../Makefile:322: d_compile] Error 1
make[2]: *** [../example.mk:48: build] Error 2
make[2]: Target 'check' not remade because of errors.
make[1]: *** [Makefile:215: extend.actionexample] Error 2
checking Examples/d/simple
checking Examples/d/variables
example.d(161): Deprecation: `example_im.SwigPendingException` is not visible from module `example`
example.d(161): Deprecation: `example_im.SwigPendingException` is not visible from module `example`
example.d(166): Deprecation: `example_im.SwigPendingException` is not visible from module `example`
example.d(166): Deprecation: `example_im.SwigPendingException` is not visible from module `example`
make: *** [Makefile:200: check-d-examples] Error 2
```

It's likely this isn't the first version where this fails, just that the failures for older versions are masked by the libcurl3 issue.

@vadz wrote in a comment in 51cb07711f02e95f45ace5e580a75e5846f96881:
```
        # D support can't be enabled because dmd 2.066 fails to build anything
        # under Ubuntu 18.04 due to its standard library (libphobos2.a) not
        # being compiled with -FPIC, but system gcc using -fpie by default,
        # resulting in linking errors for any output. And later versions, such
        # as 2.086.1, are not supported and result in errors in SWIG test suite.
```

So maybe that means that the newest D which SWIG works with is 2.066?

Either way, SWIG doesn't work with any D release since somewhere between 2014-08-18 ([2.066](https://dlang.org/changelog/2.066.0.html)) and 2018-05-01 ([2.080.0](https://dlang.org/changelog/2.080.0.html)) yet apparently no users have reported this to us in 5 years (or possibly nearly 9 years).

I gather from #880 that D now supports linking directly to C++ code with "new extern(C++)" functionality (that's "new" as of 2017), so perhaps this situation reflects that SWIG/D is no longer very useful.

I propose we demote D to experimental status in 4.2.0, given:

* We don't seem to have had an active SWIG/D maintainer for years (2014 from grep in git logs)
* SWIG doesn't work with any D release made in at least the last 5 years...
* ...yet no users seem to have noticed
* Since SWIG added D support, D has gained native support for C++ interop
* We have had no functioning CI coverage for it for approaching two years (since travis stopped being useful)

**Comment by ojwb** [comment]
I just noticed @wsfulton already suggested essentially the same last October in https://github.com/swig/swig/issues/56#issuecomment-1274967203:
> I'll have a look, I've got a vague understanding of what is going on, but not enough to solve all the errors with the new versions of D.
>
> BTW, I was going to suggest discuss removing/deprecating D during the 4.2 dev cycle if there isn't someone contributing to fixing this soon as the last working version of D is now ancient.

**Comment by ojwb** [comment]
I kicked off a CI run hacked to just try ldc and gdc for Ubuntu 20.04 and 22.04 (the two versions GHA currently supports) but they fail too (looks like the same errors as with the upstream compiler): https://github.com/swig/swig/actions/runs/4856429855

(If someone resurrects SWIG/D then the patch there to add `gdc` to the list of D compilers configure checks for would probably be worth applying, at least assuming it works.)

**Comment by ojwb** [comment]
In #2567 @erezgeva pointed out:
>  I think we can drop D language version 1 (D1).
>
> According to Wikipedia.
> https://en.wikipedia.org/wiki/D_(programming_language)
> D1 is discontinued from 2012.

`git ls-files '*.1.d'|wc -l` shows 51 runme files for D1.

Manual says:
> By default, SWIG generates code for D1/Tango. Use the `-d2` flag to target D2/Phobos instead.

**Comment by wsfulton** [comment]
Agreed let's drop the old D version 1.

**Comment by wsfulton** [comment]
We also can't keep supporting D version 2 given the changes in the language and no-one is around to help maintain the SWIG D module. If no-one steps up with a patch to fix the D test-suite with latest D compilers then I propose we remove D like we did for other languages in version 4.0, that is, disable D from 4.2 but leave the source and examples etc in the repo until 4.3. Then remove complete completely in 4.3 if still not resolved.

Pinging known D contributors and interested users: @dnadlinger @timotheecour @msteinbeck. @buckle2000.

**Comment by ojwb** [comment]
@erezgeva expressed interest earlier today in trying to get SWIG to work with recent D releases.

**Comment by erezgeva** [comment]
I find the D language a nice language.
It is similar to go.
So, I did not use it myself, yet.

I'll try to fix it, after dropping obsolete version 1.
We can use Ubuntu own packages to install the compilers
https://packages.ubuntu.com/search?keywords=gdc
https://packages.ubuntu.com/search?keywords=ldc
So we do not waste our time with backward compatible of the D compiler.

**Comment by erezgeva** [comment]
First draft:

https://github.com/swig/swig/pull/2570

Any help on fixing the  proper use of `override` in D code is welcomed.

**Comment by ojwb** [comment]
I've merged the change to remove D1, thanks.

@erezgeva See #56 re `override`.  There's even a patch there which may help (or may be a terrible idea).

More generally, I'd suggest you review https://github.com/swig/swig/labels/D so you're aware of existing known issues and discussion of them as it may well save you from having to rediscover things that someone already investigated.

**Comment by erezgeva** [comment]
> I've merged the change to remove D1, thanks.
> 
> @erezgeva See #56 re `override`. There's even a patch there which may help (or may be a terrible idea).
> 
> More generally, I'd suggest you review [ D](https://github.com/swig/swig/labels/D) so you're aware of existing known issues and discussion of them as it may well save you from having to rediscover things that someone already investigated.

I'd have a look, thanks.

**Comment by dnadlinger** [comment]
Yep, just to confirm, I unfortunately don't have the bandwidth to maintain D support myself (nor would I have had it for many years at this point – apologies, William!). It shouldn't be too hard to bash it into shape, though, as the language hasn't had many breaking changes.

(Personally, if I had more chances to use D again for daily development, I suppose I would be more interested in pursuing a lower-overhead approach – while much of the SWIG layer should disappear after combined LDC/Clang LTO, something catering more specifically to the more extended interfacing capabilities that got added to D2 would look more attractive; perhaps even more tightly integrated with the compiler. SWIG could still be interesting for pre-existing, older libraries, though.)

**Comment by erezgeva** [comment]
`I gather from https://github.com/swig/swig/issues/880 that D now supports linking directly to C++ code with "new extern(C++)" functionality (that's "new" as of 2017), so perhaps this situation reflects that SWIG/D is no longer very useful.`

@ojwb:  my reply:

1. Go also support extern in the 2 direction. You can call C functions directly and call Go functions from C/C++.  Also most of C type are easily mapped. 
2. C# is better in passing array to C++. It is the only language that pass string array to a perfect C null terminated string array (char pointer pointer). Nor Go neither D do that.
3.  C#  and Go do not have any C/C++ API. C# map all directly using native binding. And Go do that like D using extern calling.

**Comment by ojwb** [comment]
I haven't looked into it in any detail, but `extern(C++)` sounds like it allows calling C++ functions directly from D (at least based on the similarity of its form to C++ `extern "C"`).  Sure the "not via a C/C++ API" structure is similar to Go and C#, but I don't believe you can easily call directly to C++ from them.  You'd have to at least mangle the symbol names yourself, which varies between compilers/platforms.

I realise not everyone who hits a bug bothers to report it, but there's clearly not widespread use of SWIG/D or else at least one person would have told us that it doesn't work with any vaguely recent D version.  Being able to call C++ directly from D now would at least partly explain that.

SWIG clearly doesn't just provide the ability to call C++ functions, it also provides features to customise what's wrapped and how.  D seems modelled after C++ which probably means there's less need for such customisation compared to wrapping C++ to a target language where there's more of a mismatch.

But don't take the text you quoted as meaning I'm against someone resurrecting SWIG/D.

The key point really is that SWIG/D is currently broken and needs either fixing or removing (after a one release cycle demotion to "experimental" status).  I'm happy for either, I just want all our target languages to be usable, useful and maintainable.

**Comment by erezgeva** [comment]
> he key point really is that SWIG/D is currently broken and needs either fixing or removing (after a one release cycle demotion to "experimental" status). I'm happy for either, I just want all our target languages to be usable, useful and maintainable.

I totally agree.
I did not disregard this point.
If D is not popular. No one step in and maintain and solve the CI errors, than it should go.
On the same ground other languages were removed.

> SWIG clearly doesn't just provide the ability to call C++ functions, it also provides features to customise what's wrapped and how. D seems modelled after C++ which probably means there's less need for such customisation compared to wrapping C++ to a target language where there's more of a mismatch.

I saw [using_cpp_classes_from_d](https://dlang.org/spec/cpp_interface.html#using_cpp_classes_from_d)
This does seems to be more than C#, and Go can do today.
And yet, the way C# map complex types to C, seems more smooth than D to C++.
Basic type of integer and float are probably pass.
But not sure about array and strings pass directly.
D strings are build different from C null terminated string or C++ std::string.
Also D dynamic arrays are different from C arrays or C++ std::vectors.
Only D static arrays of fixed size elements are the same as C arrays.

SWIG can help map with type-maps.

**Comment by ojwb** [comment]
Thanks to @erezgeva's hard work, SWIG/D is back to being usable with current D releases.  Moreover we now have CI testing with the gdc and ldc compilers as well as dmd.

**Comment by wsfulton** [comment]
Thanks @erezgeva, this is really great.
