### ISSUE TITLE
Add Julia support

### ISSUE THREAD

**Issue by clickingbuttons** [swig/swig#2539]
Julia has [C support](https://docs.julialang.org/en/v1/base/c/) but I'd love to be able to use my existing `.i` files to generate wrappers. [This](https://groups.google.com/g/julia-dev/c/C_9ModNoiQU/m/OYVvTrKPh1kJ) is the only related thread I could find on this topic.

**Comment by ojwb** [comment]
Support for a new target language really needs to be contributed by someone who knows that language.

I'd caution that it's a significant amount of work to implement such support and get it merged - sadly several new target languages have got to the "kind of working" stage and progress stagnated before they were finished enough to get merged.

If you (or someone else reading) is interested, there are documented requirements for a new target language to be merged to give you some idea what you'd be volunteering for:

https://www.swig.org/Doc4.1/Extending.html#Extending_prerequisites

**Comment by ojwb** [comment]
Keeping a feature request ticket open for a new target language doesn't seem useful so I'm going to close this.  Realistically someone will implement support because they want it, not because they see a ticket open for it.
