### ISSUE TITLE
BUG: `%copyctor` causes duplicate wrapper function when class has template<> constructor

### ISSUE THREAD

**Issue by CraigHutchinson** [swig/swig#2541]
# Issue
Enabling `copyctor` for a class which does not have explicit copy constructor results in compiler error:
`error C2084: function 'void *CSharp_pxr_new_GfVec2f__SWIG_6(void *)' already has a body`

The problem was first identified when generating C# bindings for [PixarAnimationStudios/USD/blob/release/pxr/base/gf/vec3f.h](https://github.com/PixarAnimationStudios/USD/blob/release/pxr/base/gf/vec3f.h)

The issue appears to require:
- Explicit default constructor
- no defined copy-constructor (therefore requires `copyctor`)
- 1 or more templated constructor **[Crucial part that contributes to the issue]**
- 1 or more other constructor

## 🛗 Reproducer
```
%module CtorBug
​
%copyctor;
​
struct Bar{};
​
struct Foo
{
    Foo() = default;
    template <class T> Foo(const T* p);
    Foo(const Bar& other);
};
```

## 🐞 Outcome
- The function name `CSharp_pxr_new_Foo__SWIG_2` is duplicate for both the `Bar` and `Foo` constructor.
- There is no `SWIG_1` wrapper function (only `SWIG_0` and `SWIG_2`)
```
  public Foo() : this(CtorBugPINVOKE.new_Foo__SWIG_0( ), true);
  public Foo(Bar other) : this(CtorBugPINVOKE.new_Foo__SWIG_2( Bar.getCPtr(other)), true);
  public Foo(Foo other) : this(CtorBugPINVOKE.new_Foo__SWIG_2( Foo.getCPtr(other)), true);
```

### 1. Add explicit default-copy constructor
Modify the C++ source (when viable) to include  `Foo(const Foo&) = default`
Otherwise extend the class to provide a new wrapper function
```
%extend Foo {
    Foo(const Foo& other) { return new Foo(other); }
}
```
💡 There is a Bug here as  `..._SWIG_2` is omitted as only `SWIG_1` and `SWIG_3` are generated. This behavior may aid in isolating source of the off-by-one issue.

### 2. Remove the `template` constructor
Either modify the class source to ommit the `tenmplate` constructor or simply use the `%ignore` directive as follows:
```
%ignore Foo::Foo(const T* p);
```

**Comment by ojwb** [comment]
This issue rang a vague bell so I went digging and the old bug I was remembering was https://sourceforge.net/p/swig/bugs/678/ - this doesn't have a template constructor though, but noting it here as it would be good to recheck it once this gets fixed.

Seems to need an explicit `= default` so tagging as C++11.

**Comment by ojwb** [comment]
Same issue affects Java:

```
$ grep new_1Foo test_wrap.cxx 
SWIGEXPORT jlong JNICALL Java_CtorBugJNI_new_1Foo_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
SWIGEXPORT jlong JNICALL Java_CtorBugJNI_new_1Foo_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
SWIGEXPORT jlong JNICALL Java_CtorBugJNI_new_1Foo_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
```

and PHP:

```
$ grep 'NAMED.*new_Foo' test_wrap.cxx 
static ZEND_NAMED_FUNCTION(_wrap_new_Foo__SWIG_0) {
static ZEND_NAMED_FUNCTION(_wrap_new_Foo__SWIG_2) {
static ZEND_NAMED_FUNCTION(_wrap_new_Foo__SWIG_2) {
```

So it seems this is a bug in generic code.

**Comment by ojwb** [comment]
Reproduced with 595009cf2ff952d963a663113e82b032c4fa770f, so not fixed by the recent template constructor changes.
