### ISSUE TITLE
Slightly different handling when resolving `const` types vs the base type

### ISSUE THREAD

**Issue by mmomtchev** [swig/swig#2553]
```swig
%module typedefs

%inline 
%{
namespace nspace1 {
  typedef struct _Abstract Abstract;
}

using nspace1::Abstract;

// compiles
int fn3(Abstract *a) { return 0; };
// does not compile
int fn3(const Abstract *a) { return 0; };
%}
```

The produced type conversion rule is:
```c
static swig_type_info _swigt__p__Abstract = {"_p__Abstract", "Abstract *|nspace1::Abstract *|_Abstract *", 0, 0, (void*)0, 0};
```

**Comment by mmomtchev** [comment]
Is this expected, given the flattening of the namespaces?

**Comment by mmomtchev** [comment]
No, this is clearly a bug. The problem is distinguishing it from this case:
```swig
%module typedefs

%inline 
%{
namespace nspace1 {
  typedef int Abstract;
}

using nspace1::Abstract;

int fn3(Abstract *a) { return 0; };
int fn3(const Abstract *a) { return 0; };
%}
```

Both types - `int` and `_Abstract` are not defined elsewhere. However one requires a namespace qualifier while the other one does not. A real compiler will recognize `int` which is defined elsewhere. However SWIG has no such notion?

**Comment by mmomtchev** [comment]
The decision to qualify or not is taken here:
https://github.com/swig/swig/blob/d45884bab5a881cb1420625ad27c5fccb5b4f6b1/Source/Swig/typesys.c#L784

The only question is how to distinguish the two cases

**Comment by mmomtchev** [comment]
I have a very elegant, albeit very radical solution: simply do not resolve the types when generating the type cast for a function call. In fact, you don't need it at this point - no need for complex type aliasing rules - here we just want to use the compiler type cast logic to generate a conversion - leave it to resolve the type itself.

**Comment by ojwb** [comment]
> Both types - `int` and `_Abstract` are not defined elsewhere. However one requires a namespace qualifier while the other one does not. A real compiler will recognize `int` which is defined elsewhere. However SWIG has no such notion?

(Do you mean `Abstract`?  I don't see `_Abstract` anywhere in your example...)

SWIG knows about `int` and the like - see `SwigType_type()` in `Source/Swig/typesys.c`.

**Comment by ojwb** [comment]
Oh, `_Abstract` is in the earlier example, not the one just above.

**Comment by mmomtchev** [comment]
This was solved by https://github.com/swig/swig/commit/65be8812959aa0d2e9805e31549bbeac0cc89691
