### ISSUE TITLE
Cannot import python module (.pyd) which is compiled with MSVC "/MDd" option

### ISSUE THREAD

**Issue by ryankamanri** [swig/swig#2568]
I was trying to use CMake to build my wrapper code and invoke it from python, but it returns  exit code -1073741819 (0xC0000005) without any exception. Is this a problem relate to memory collision? I also use command line to built it and finally find it works abnormally when I  added "/MDd" option in MSVC and linked to "msvcrtd.lib".

**Comment by ojwb** [comment]
I'd guess you would need to use the same C runtime for your module as for Python itself, so this doesn't seem like a problem with SWIG.

**Comment by ryankamanri** [comment]
Yeah it seems that the runtime library used in Python is "msvcrt.lib". So i add a statement in my CMakeList.txt:
``` cmake
# https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreadedDLL) 
```
and it works.
