### ISSUE TITLE
scilab: Output file path folders not created

### ISSUE THREAD

**Issue by ibell** [swig/swig#257]
If the output target path does not already exist (common for out-of-source builds and CMake), swig generally will make the required folders, but with scilab, it doesn't and we have to manually generate the requisite folders.

**Comment by vadz** [comment]
Actually, I think it would be pretty convenient if SWIG did create the output folder, even (especially?) for Java. The analogy with gcc is not really convincing as SWIG generates sources, not binaries, so they must almost inevitably go to a different directory to avoid mixing them with up the non-generated sources, and hence the use of an output directory is much more common. In fact, gcc doesn't even have `-outdir` option, unlike SWIG.

IMHO it would be nice if the `-outdir` argument were created if it doesn't exist. Of course, this is not at all Scilab-specific and if it's done, it should be done for all backends.

**Comment by ibell** [comment]
I think for me at least this is an issue in combination with CMake.  CMake tends to create the output folder if necessary with swig, but that's not the case with the scilab wrapper.

**Comment by ojwb** [comment]
@ibell That sounds like an issue with cmake's support for SWIG, rather than with SWIG...

**Comment by ibell** [comment]
I've completely given up on scilab support in swig.  It was driving me
insane, and we have a python wrapper of our library anyway, which is much
easier to work with.  This issue can be closed.

On Sep 8, 2016 9:34 PM, "Olly Betts" <notifications@github.com> wrote:

@ibell <https://github.com/ibell> That sounds like an issue with cmake's
support for SWIG, rather than with SWIG...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/swig/swig/issues/257#issuecomment-245810050>, or mute
the thread

**Comment by smarchetto** [comment]
@ibell SWIG for Python does not create output folder too :

```
#error if the out folder does not exist
$ /home/.../swig/preinst-swig -python -o out/test_wrap.c test.i
Unable to open file out/test_wrap.c: No such file or directory

#if we create the folder, it works
$ mkdir out
$ /home/.../Dev/swig/preinst-swig -python -o out/test_wrap.c test.i

$ ls out
%test.py  test_wrap.c
```

And I agree with @wsfulton, a command line tool such as swig or gcc should not create an output folder. Its job is to generate code, not folder tree structure.

So for me the issue can be closed, but not for the reason you invoke (you have given up with scilab).

About SWIG for Scilab we've been using it in my company on several projects (on C and C++ librairies) . I can't give you all the links (some of them are private), here are just a few (and more are coming):
[scinetcdf](https://forge.scilab.org/index.php/p/netcdf4/)
[MED](https://forge.scilab.org/index.php/p/med/)

Not always simple, I agree but it do works. I know there are still open issues, I try to maintain it when I can, SWIG is my secondary project.
