### ISSUE TITLE
Having trouble building the swig.exe file

### ISSUE THREAD

**Issue by NyR3x** [swig/swig#2574]
Hi,
I followed the windows document on how to build it but I always get the same error after running make.

-L/c/msys/1.0/src/swig/pcre/pcre-swig-install/lib -lpcre
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lpcre: No such file or directory
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:925: eswig.exe] Error 1

dont know what to do cause when I ran the Tools/pcre-build.sh command it returned with no problems at all.

he SWIG configure script can now be run, whereupon PCRE will automatically be detected and used from /c/msys/1.0/src/swig/pcre/pcre-swig-install/bin/pcre-config.
 
I hope someone can help me.

**Comment by NyR3x** [comment]
Just stupid.

**Comment by ojwb** [comment]
> Just stupid.

@NyR3x Do you mean you solved your problem?

**Comment by ojwb** [comment]
No response so assuming solved.  Comment if you want this reopening.
