### ISSUE TITLE
[Python] %feature("shadow") does not work on methods introduced by %extend

### ISSUE THREAD

**Issue by iakovts** [swig/swig#2578]
I am trying to shadow some methods introduced with `%extend` but that does not seem to work. Coincidentally, when extending the class with overloads that were previously shadowed successfully (before extending), `shadow` no longer works.
A simple example: 
`test.i`
``` test.i
%module test

%{
        #include "test.hpp"
%}

%feature("shadow") myClass::method1 %{
def method1(self):
    return 2
%}

%extend myClass {
int method2() { return 100; }
}

%feature("shadow") myClass::method2 %{
def method2(self):
    return 4
%}

%include "test.hpp"

``` 
`test.hpp`
```test.hpp
class myClass
{
public:
        int method1() { return 1; }
};
```
`test.cpp`
```test.cpp
#include "test.hpp"
```
`test.py`
```test.py
class myClass(object):
[...]

    def method1(self):
        return 2

    def method2(self):
        return _test.myClass_method2(self)
[...]
```
I am using 
```
swig -c++ -python test.i 
g++ -c -fPIC test.cpp test_wrap.cxx -I/usr/include/python3.10 
g++ -shared test.o test_wrap.o -o _test.so
```

---

So, is it possible to use `feature("shadow")` on methods introduced with `%extend`? The example above is just a simple one to demonstrate the issue (or limitation? or something I am doing wrong?), but I am working with a codebase that would greatly benefit from such usage.

Thank you.

**Comment by ojwb** [comment]
I'd think it's reasonable to expect it to work (but I'm not overly surprised to hear it doesn't currently as it's a corner-case that I suspect nobody tried before).

If I follow it seems you add a method implemented in C/C++ with `%extend` then replace it with a pure-Python `%feature(shadow)` - instead could you just add the pure-Python method with `%pythoncode`?

**Comment by iakovts** [comment]
Hey @ojwb,

Yes you do understand this correctly.

Essentially I just want some methods implemented only for python, but make calls to the underlying C++ implementation.

A more illustrative example would hopefully be something like this:
`test.i` (using the class provided before)
```
%extend myClass {
    int fnc(objA& x) { $self->do_something(*x) ;}
    int fnc(objB& x) { $self->do_something(*x) ;}
    int fnc(objC& x) { $self->do_something(*x) ;}
   ...
}
%feature("shadow") myClass::fnc %{
def fnc(self):
    obj = choose_obj() # dummy expl -> returns an appropriately python-wrapped objA, objB etc
    result = $action(self, obj)
%}

```

**Comment by ojwb** [comment]
> Essentially I just want some methods implemented only for python, but make calls to the underlying C++ implementation.

Did you look at the example in the manual for `%pythoncode`?

https://www.swig.org/Doc4.1/Python.html#Python_nn42

**Comment by iakovts** [comment]
Thanks @ojwb, this seems to do the trick :).
Obviously python (or well Pyright) complains about declaring twice the same method. My `.py` now has both methods using the same name in the class, the original and the one I added. Thankfully, it does run but I would much rather have it done cleaner at some point.

**Comment by ojwb** [comment]
Sure, not saying this isn't a bug - there's at least a way that works with existing releases though.

You could probably `%rename _fnc myClass::fnc;` or similar so the original method gets wrapped as `_fnc` instead (I'm not very into Python but IIRC a `_` prefix conventionally indicates internal implementation stuff in Python).  You'd get an unused `_fnc` in the Python wrapper layer still, but at least avoid the duplicate names.

Does the example in the manual end produce duplicate names as well?  If so and the `%rename` avoids that it'd be helpful if that demonstrated that trick.

**Comment by iakovts** [comment]
> Does the example in the manual end produce duplicate names as well?

Yes it does.
>  If so and the `%rename` avoids that it'd be helpful if that demonstrated that trick.
 Renaming seems to do the trick, I'll have it to test it on the actual codebase but it works on the toy example.
Still, swig complains when using the same argument list, but that is to be excepted (also not my use case):
```
example.hpp:5: Warning 302: Identifier '_method2' redefined by %extend (ignored),
example.i:16: Warning 302: %extend definition of '_method2'.
```


> You could probably `%rename _fnc myClass::fnc;` or similar so the original method gets wrapped as `_fnc` instead (I'm not very into Python but IIRC a `_` prefix conventionally indicates internal implementation stuff in Python). You'd get an unused `_fnc` in the Python wrapper layer still, but at least avoid the duplicate names.
 
Yeah, renaming to `_fnc` avoids the issue with the duplicate names, plus internally I am actually calling it or at least have access to it if needed.

Thanks again for your help! :) 

P.S.: Maybe this issue should be left open as it is probably a bug or at least a missing feature?

**Comment by ojwb** [comment]
> P.S.: Maybe this issue should be left open as it is probably a bug or at least a missing feature?

Yes, or maybe an unsupported combination, but if that's the answer then it should be rejected with a clear error saying that.

**Comment by wsfulton** [comment]
`%feature` must come before the function that it is targetting. Correct code, which works is:
```swig
%module test

%{
        #include "test.hpp"
%}

%feature("shadow") myClass::method1 %{
def method1(self):
    return 2
%}

%feature("shadow") myClass::method2 %{
def method2(self):
    return 4
%}

%extend myClass {
int method2() { return 100; }
}

%include "test.hpp"
```
