### ISSUE TITLE
Mishandling of sizeof on string literal in array size

### ISSUE THREAD

**Issue by ojwb** [swig/swig#2579]
```
$ cat test.i
%module x
%inline %{
unsigned char x[sizeof"hello world"];
unsigned char y[sizeof("hello world")];
%}
$ ../preinst-swig -python test.i
$ grep 'hello world[^"]' test_wrap.c 
      SWIG_exception_fail(SWIG_ArgError(res), "in variable '""x""' of type '""unsigned char [sizeof(hello world)]""'");
      for (; ii < (size_t)sizeof(hello world); ++ii) *(unsigned char *)&x[ii] = *((unsigned char *)inp + ii);
      SWIG_exception_fail(SWIG_ValueError, "invalid null reference " "in variable '""x""' of type '""unsigned char [sizeof(hello world)]""'");
      SWIG_exception_fail(SWIG_ArgError(res), "in variable '""y""' of type '""unsigned char [sizeof(hello world)]""'");
      for (; ii < (size_t)sizeof(hello world); ++ii) *(unsigned char *)&y[ii] = *((unsigned char *)inp + ii);
      SWIG_exception_fail(SWIG_ValueError, "invalid null reference " "in variable '""y""' of type '""unsigned char [sizeof(hello world)]""'");
```

Note SWIG loses the double quotes around the string literal inside the `sizeof`.

I spotted this while exploring additional tests for #2575 rather than in real world code, but while in this case `sizeof(hello world)` fails to compile, potentially the string without the quotes could be a valid thing to apply `sizeof` to though, so this bug could quietly produce incorrect code which compiles.

**Comment by ojwb** [comment]
May be related to #904.

BTW, I test `sizeof` with and without parentheses above as they get handled in different ways by the parser grammar.

**Comment by ojwb** [comment]
#1907 too.

**Comment by ojwb** [comment]
The more I look at this the less sure I am how any of it is meant to work.

@wsfulton Do you understand exactly what the `rawval` and `val` members of `dtype` in the parser mean?  I can't find any documentation of this.  I'm fairly sure in some places they aren't being set/updated correctly, but it's really hard to work out exactly what's wrong without a clear idea of what they're meant to be.

FWIW, this patch seems to fix the issue here and `make check-php-test-suite` still passes, which is promising:

```
diff --git a/Source/CParse/parser.y b/Source/CParse/parser.y
index b37e8354..914df122 100644
--- a/Source/CParse/parser.y
+++ b/Source/CParse/parser.y
@@ -6655,6 +6655,7 @@ exprsimple     : exprnum {
                }
                | string {
 		    $$.val = $1;
+		    $$.rawval = NewStringf("\"%(escape)s\"", $$.val);
                     $$.type = T_STRING;
                }
                | SIZEOF LPAREN type parameter_declarator RPAREN {
@@ -6675,7 +6676,7 @@ exprsimple     : exprnum {
 		* for sizeof(<type>) because it matches that syntactically.
 		*/
 	       | SIZEOF LPAREN exprsimple RPAREN {
-		  $$.val = NewStringf("sizeof(%s)", $3.val);
+		  $$.val = NewStringf("sizeof(%s)", $3.rawval ? $3.rawval : $3.val);
 		 $$.type = T_ULONG;
 	       }
 	       /* `sizeof expr` without parentheses is valid for an expression,
@@ -6683,7 +6684,7 @@ exprsimple     : exprnum {
 		* addition to the case not supported above.
 		*/
 	       | SIZEOF exprsimple {
-		  $$.val = NewStringf("sizeof(%s)", $2.val);
+		  $$.val = NewStringf("sizeof(%s)", $2.rawval ? $2.rawval : $2.val);
 		  $$.type = T_ULONG;
 	       }
 	       | wstring {
```

I see `rawval` is already being set for `wstring` so this reduces the inconsistency there at least, but maybe it's actually wrong that this is being set for `wstring` - I could believe that was incorrectly copied from the handling for `CHARCONST` when `WCHARCONST` and `wstring` were added in  7d800a655de565826fd2404fd11d85dccd9c11d1.

I'd really like to understand this as there we seem to have multiple issues in the area and I've tried to fix issues in this area before and had to revert - e.g. 07c40f5f75e8d56be612b4b4db253329f159d7ec (back in 2006!)

**Comment by wsfulton** [comment]
I'm afraid that I've never really understood why we have both. It could do with a cleanup and clarifying with some comments in the code, but will require harmonising all the target language modules wrt quoting chars and strings which would be great for consistency.

**Comment by ojwb** [comment]
If neither of us understand it, then it's probably not a surprise that they don't seem to be consistently used, and that there are bugs as a result.

I'll see what I can do.  My initial thoughts are that maybe it's best to effectively start again with some new members with clearly defined and documented semantics (e.g. maybe a `c_expr` member in which the result as a valid C expression gets built up) and work from the parser through the code that currently consumes `val` and `rawval` moving it over to using these new members until `val` and `rawval` are no longer used and we can drop them.  It's not like `val` and `rawval` seem to be well chosen names (`val` seems "rawer" to me than `rawval`).

**Comment by ojwb** [comment]
I've been looking at this, and I think the "rawval" mess is essentially down to slightly buggy initial implementation which various people over the years (including me) have attempted to fix in various different wrong places.

I think the best way to resolve it is to make `val` be the value as a C/C++ expression, and have another member for string and character types (including the wide ones) which holds the actual string value (used where we want to emit that string value in the target language).  This could be called `rawval` though I think "raw" here is a confusing term (the history of trying to fix this is some evidence of this) and better avoided, and we should call it something like `stringvalue` instead.  I'd suggest we already rename the `rawvalue` attribute similarly, though if that's visible in typemaps that's a compatibility concern.

However I've run into an unrelated problem which is that for the original example here, for `y` `$type` is `unsigned char [sizeof("hello world")]` and SWIG does not cope with a type with a `"` in it because it naively uses `"$type"` when constructing error message strings for parameter type errors.

@wsfulton Any ideas how best to address this?

I did try making SWIG's preprocessor backtick quoting use `%(escape)s` on the value and then using that in `%varfail_fmt(_type,_name)` and similar, but that doesn't actually seem to help because `$type` appears to actually gets substituted after these macros are expanded so they just see `$type`.

Maybe we need something like `$type_as_string` to complement `$type`?

The other approach that occurs to me is that SWIG could actually evaluate `sizeof()` on a literal string or literal character and then `$type` here would be something like `unsigned char [((size_t)12))]` and wouldn't contain the problematic `"` characters.  For wide literals we can multiple by `sizeof(wchar_t)` so SWIG wouldn't need to assume the width of a wide character.  This requires fewer changes to the library files as then current `$type` usage in strings would be fine, but I don't think we currently attempt to evaluate expressions in other cases (outside of the preprocessor).

**Comment by ojwb** [comment]
> The other approach that occurs to me is that SWIG could actually evaluate `sizeof()` on a literal string or literal character and then `$type` here would be something like `unsigned char [((size_t)12))]` and wouldn't contain the problematic `"` characters. For wide literals we can multiple by `sizeof(wchar_t)` so SWIG wouldn't need to assume the width of a wide character. This requires fewer changes to the library files as then current `$type` usage in strings would be fine, but I don't think we currently attempt to evaluate expressions in other cases (outside of the preprocessor).

(BTW literal characters are potentially problematic because of cases like `'"'`...)

I've already thought of a couple of problems with this approach.

One is that we currently handle `SIZEOF LPAREN` by just skipping to the closing `)` and grabbing the skipped text to use as the value of the expression, which was to fix a case you hit a few months ago.  We'd either need to try to parse the expression and use error recovery to grab the text if parsing fails, or poke the skipped text to see if it looks like a string literal.

The other is that there are many more cases where a string literal can appear in a constant expression - without much thought I came up with 4 more:

```
void foo(const char*) noexcept {}
int x[alignof(decltype("x"))];
int y[noexcept(foo("x"))];
int z[*"a"]; 
int z2["a"[0]]
```

Admittedly these are getting quite obscure, but as a general approach I don't think we can eliminate double quotes by having SWIG evaluate bits of expressions

**Comment by wsfulton** [comment]
Agreed, evaluating expressions, or even just snippets of expressions, is a can of worms and a big project in itself. The only real chance of this happening is grabbing a robust expression evaluator from a tried and tested implementation, such as from a C++ compiler that is being actively maintained.

With regard to `val` and `rawval`, changing the names is fine. I don't really mind what as long as it is documented. I've just one suggestion, feel free to ignore... how about `strippedval` for the value with the quotes stripped off.

Tricky problem, I don't have any silver bullet I'm afraid! 

With regard to `$type` containing a string as reported here and given the problems you've outlined of `$type` being used within a string in typemaps, it is a bigger problem if you consider the full family of related special variables for types such as `$1_ltype`, `$*1_type`, etc etc. Ideally SWIG knows to auto escape these, but I doubt we can get that always right. Adding in a new special variable macro to escape, might work, such as having to replace usage like `"problem with $type"` with something like `"problem with $escape($type))"`. Or add in a new escaping mechanism syntax to all the types, such as `$(1_type)` or ``$`1_type`` will escape what `$1_type` would output for usage within a string. All these solutions require massive changes to so many typemaps, so in summary, I would be inclined to perhaps not bother supporting types being used within a string. Workarounds might be to specialise a typemap removing `$type` from strings or replacing a string with a hand coded type with correct escaping. Maybe your time @ojwb is better spent on something else?? Up to you of course.

Even if supporting such types does not work, I think the `rawval` cleanup would be useful with a view to fully supporting expressions as values. Maybe there are more challenging issues there, but I don't think there are the same challenges as expanding special variables within strings.

**Comment by ojwb** [comment]
> Agreed, evaluating expressions, or even just snippets of expressions, is a can of worms and a big project in itself. The only real chance of this happening is grabbing a robust expression evaluator from a tried and tested implementation, such as from a C++ compiler that is being actively maintained.

I think there would be significant challenges with bolting something like that into SWIG, particular if we continue to have SWIG generate portable code and so need to be agnostic about the sizes of most types (whereas a compiler knows the sizes of types).  It seems we'd inevitably need to effectively fork the code to make handle type sizes not being fixed, and then it being actively maintained is almost unhelpful as keeping our modified version in sync would become another chore.

We do have an expression evaluator already for preprocessor expressions which is arguably tried and tested, though has a more limited scope so could realistically only cope with a subset of possible expressions if reused.

Writing and maintaining a full constant expression evaluator from scratch really doesn't seem any more appealing though.

> With regard to `val` and `rawval`, changing the names is fine. I don't really mind what as long as it is documented. I've just one suggestion, feel free to ignore... how about `strippedval` for the value with the quotes stripped off.

I think `strippedval` is emphasising the wrong thing.  It's not just "the value with the quotes stripped off" and it seems to me thinking about it that way tends to lead to problems like the lack of escaping when `$type` is substituted into a string literal.  So I'd prefer a name that emphasise it's the actual value of the string (or character literal) in a SWIG `String`.  Maybe something like `value_as_string` is clearer than `stringvalue`.

> Tricky problem, I don't have any silver bullet I'm afraid!

OK.  I wondered if I was just missing an easy answer.

> With regard to `$type` containing a string as reported here and given the problems you've outlined of `$type` being used within a string in typemaps, it is a bigger problem if you consider the full family of related special variables for types such as `$1_ltype`, `$*1_type`, etc etc. Ideally SWIG knows to auto escape these, but I doubt we can get that always right.

Perhaps we can just special case `"$type"` etc?  I.e. if the placeholder has a `"` right before and right after its value gets `%(escape)s`-ed, so you would need to say `"problem with ""$type"` in your example below.  This change actually looks like it would just solve the problem without needing any typemap changes in the library (user typemaps might need a tweak if they want to support types with double quotes in, but shouldn't work any worse than now).

> Adding in a new special variable macro to escape, might work, such as having to replace usage like `"problem with $type"` with something like `"problem with $escape($type))"`. Or add in a new escaping mechanism syntax to all the types, such as `$(1_type)` or `` $`1_type `` will escape what `$1_type` would output for usage within a string. All these solutions require massive changes to so many typemaps, so in summary, I would be inclined to perhaps not bother supporting types being used within a string.

Most of the uses seem be be via macros already, so while there are quite a lot of places to change for something like `$`type`, a lot of it is mechanical, e.g.:

```
    %argument_fail(res,"$type",$symname, $argnum);
```

becomes something like:

```
    %argument_fail(res,"$`type",$symname, $argnum);
```

>  Workarounds might be to specialise a typemap removing `$type` from strings or replacing a string with a hand coded type with correct escaping. Maybe your time @ojwb is better spent on something else?? Up to you of course.

Maybe.  The problematic cases are rather obscure.

> Even if supporting such types does not work, I think the `rawval` cleanup would be useful with a view to fully supporting expressions as values. Maybe there are more challenging issues there, but I don't think there are the same challenges as expanding special variables within strings.

Indeed, I should probably not get too sidetracked and focus on sorting out the `rawval` mess first anyway.

I think I've now understood things well enough that it's a solvable problem.  If we make `value` always be a valid C/C++ code expression then most target languages just need to use `value` and stop looking at `rawval`; Java and C# need more changes but are at least handling things similarly to one another; I don't really understand what Go is doing currently.

Thanks for all the thoughts.

**Comment by wsfulton** [comment]
> I think strippedval is emphasising the wrong thing. It's not just "the value with the quotes stripped off" and it seems to me thinking about it that way tends to lead to problems like the lack of escaping when $type is substituted into a string literal. So I'd prefer a name that emphasise it's the actual value of the string (or character literal) in a SWIG String. Maybe something like value_as_string is clearer than stringvalue.

I don't really understand what it contains if it isn't the quotes stripped off. But whatever, as long as it's clear/documented in the code when committed, that's all that counts. The attribute names are short and snappy (for performance) by convention as well as without underscores. So maybe stringvalue is better in that respect.

**Comment by ojwb** [comment]
It contains the string literal's value as a DOH `String*` (and similarly for a character literal, which gets handled as a single character long string).  Its value coincides with "quotes stripped of" in some cases, but I don't think that's a helpful way to think about it.  Here are a few examples:

<table>
<tr><th>C source<th>string value<th>quotes stripped off
<tr><td>"foo bar"<td><tt>foo bar</tt><td><tt>foo bar</tt>
<tr><td>"foo\x20bar"<td><tt>foo bar</tt><td><tt>foo\x20bar</tt>
<tr><td>"no" "table"<td><tt>notable</tt><td><tt>no" "table</tt>
<tr><td>'x'<td><tt>x</tt><td><tt>x</tt>
<tr><td>'\\'<td><tt>\</tt><td><tt>\\</tt>
<tr><td>'\''<td><tt>'</tt><td><tt>\'</tt>
<tr><td>'\000'<td>a single zero byte<td><tt>\000</tt>
</table>

The actual value of the string is what we want to have available for cases where we want to emit the string in the target language, since target languages don't typically have 100% C-compatible syntax for string literals (for example, C# doesn't support octal escape sequences, many target languages don't concatenate adjacent string literals, there are different rules about when to terminate a `\x` escape sequence).

The problem here is that program code is held as strings in SWIG, so the string literal represented in C/C++ syntax is a string too, and it's easy to get confused.  Thinking of the mapping as "stripping quotes" (and the reverse as "adding back quotes") seems unhelpful, and I think this is part of what's lead to the current mess where simple cases mostly work but some more complex cases don't.

The situation for other types is less confusing, probably mostly because the program code of the literal inside SWIG is still a string, but the literal's value is a different type.  Also the syntax perhaps helps - it seems easier to think about `10u`, `012U`, `0x0au` and `1'0u` all having unsigned integer value `10` without slipping into thinking of the conversion as "stripping the u-suffix".

**Comment by ojwb** [comment]
My branch now passes CI for all target languages, but I still need to tidy up and check through the changes.

Perhaps not surprisingly, straightening this out actually removes more code than it adds despite the added code having significantly more comments than the removed code - in crude diffstat terms:

```
 22 files changed, 328 insertions(+), 414 deletions(-)
```

**Comment by ojwb** [comment]
The substituting of `$type` into error message strings when the type contains double quote characters still results in us generating wrapper code which fails to compile, but it seems a rather contrived case so I'm thinking it's not worth opening a bug to track as it's there's unlikely to be work done on it, and if it's actually a problem for users someone will open a bug report.
