### ISSUE TITLE
[Python] %feature("shadow")  doesn't work properly on constructors.

### ISSUE THREAD

**Issue by erezinman** [swig/swig#2582]
Consider the following code:

### example.h
```c++
class Foo {
    public:
        Foo() {}
        ~Foo() {}
};
```
### example.i
```
%module example

%{
#include "example.h"
%}

%feature("shadow") Foo::Foo() {
def __init__(self):
    print(1)
    $action
    print(1)
}

%include "example.h"
```

(and there are also`build.sh`. and a dummy `example.cpp` but they're not interesting).

The generated class in `example.py` doesn't have a proper construction:
```python

class Foo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        print(1)
        _example.new_Foo
        print(1)


    __swig_destroy__ = _example.delete_Foo
```

Without it I get:
```
class Foo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _example.Foo_swiginit(self, _example.new_Foo())
    __swig_destroy__ = _example.delete_Foo
```
---------
As a side-note, this might've been useful in overriding the default constructor (`__init__` function). Another method I tried was using 

```
%extend Foo {
    %pythoncode %{
          __prev_init = __init__
          def __init__(self): __prev_init(self)
    %}
}
```
but alas the extension occurred before the `__init__`'s definition and not after. If you have an idea on how to do that, it would be great!

**Comment by ojwb** [comment]
Seems `$action` is wrong in this case.

Can presumably be worked around by using `%pythonprepend` and `%pythonappend` instead.

**Comment by wsfulton** [comment]
Agreed `%pythonprepend` and `%pythonappend` would be better:
```swig
%feature("pythonprepend") Foo::Foo() %{print("pythonprepend 1")%}
%feature("pythonappend") Foo::Foo() %{print("pythonappend 1")%}
```
which generates:
```python
    def __init__(self):
        print("pythonprepend 1")

        _example.Foo_swiginit(self, _example.new_Foo())
        print("pythonappend 1")
```
066ad401323d44119ada260169a5072c6595700a clarifies that the arguments are not included in `$action`.
