### ISSUE TITLE
Generate flags from C++ Attribute Specifier ([[]])

### ISSUE THREAD

**Issue by medismailben** [swig/swig#2604]
Hi,

I see in #1158 that swig now support parsing c++ attribute specifiers (i.e. `[[deprecated]]`) however it seems that the attribute is discarded on the generated file.

I'd like to use that attribute information in the generated file, to mark an API generated in the target language as deprecated, for instance.

For lldb, we use swig to generate a python API from our C++ API and we would like to have the deprecated C++ methods be also marked deprecated in Python. The way I'd see that working is by having the attribute specifier match a swig interface user-defined  function that would be used as a callback.

For instance, swig could use it as a function decorator / wrapper around the function that would run if that function as a certain attribute specifier.

Is that possible in the current state of things ?

Thanks!

**Comment by ojwb** [comment]
See #490. Closing as a duplicate.
