### ISSUE TITLE
rtypecheck changes for SWIG 4.2.0

### ISSUE THREAD

**Issue by ojwb** [swig/swig#2605]
In `Source/Modules/r.cxx` there's a comment:

```
        // Below should be migrated into rtypecheck typemaps
        // Preparation for this has started by warning in swig-4.1.1 for "numeric", "integer", "character" typemaps
        // For swig-4.2: remove the code block below and uncomment typemaps marked 'Replacement rtypecheck typemaps' in rtype.swg.
        // There is a slight difference in output as the typemap approach fixes some bugs due to a missing type resolution below
```

I can't see a ticket for this, so opening one and putting it on the swig-4.2 milestone as otherwise there's a risk this will get overlooked.

**Comment by wsfulton** [comment]
Yes. Anyone looking for more information can take a look at 973590ff915745ade6adf2ae6340db7bdcb94c5a for help transitioning using the warning message that appears in swig-4.1.1.
