### ISSUE TITLE
C# Indentation Level

### ISSUE THREAD

**Issue by adj123** [swig/swig#2607]
Hi, is there any way to customise the indent size of C#-side generated code? At the moment I see my code coming out with a level of 2 spaces, which is not the norm for C# (4 is). Not sure if I've misconfigured it or if this hard-wired but it looks particularly odd sat alongside the typemap code I have generated which correctly uses 4 spaces. Thanks.

**Comment by ojwb** [comment]
Looks like it's hard-wired.  FWIW, 2 space indent is the SWIG coding style.  I'd suggest running the generated code through a code formatting tool if you want it to follow a particular style.

**Comment by ojwb** [comment]
I've answered the question actually asked, provided a workaround, this is at worst a cosmetic issue, and I don't think it's likely anyone's going to contribute a mechanism to specify the indentation level for generated C# code, so closing.
