### ISSUE TITLE
macro in macro is parse error  %define

### ISSUE THREAD

**Issue by qd1308504206** [swig/swig#2610]
wrapper from c++  to java
version : swig 4.1.1
system: windows 10 X64

```
//my interface file as bellow.

%define TEST_MY_MACRO_t(name, dosomething)

#ifndef TEST_MY_MACRO_t##name

#define TEST_MY_MACRO_t##name

dosomething;

#endif
%enddef

TEST_MY_MACRO_t(ccc, typedef int intaa);

TEST_MY_MACRO_t(ddd,TEST_MY_MACRO_t(ccc,intaa i));

```

then I get the error message as bellow:

 : Error: Missing identifier for #ifndef.
// problem with the last line in inerface file.

**Comment by ojwb** [comment]
I can reproduce with SWIG 4.1.0 but SWIG built from git master processes your example file without errors, so this has already been fixed.

**Comment by qd1308504206** [comment]
thank you, I update my code to today from git master.
and then the error disappeared. 
thank you so much.
