### ISSUE TITLE
Template instantiation name clash with -builtin (Python)

### ISSUE THREAD

**Issue by eltoder** [swig/swig#2614]
Consider the following example:
```swig
%module example

%inline %{
template <class T>
struct Foo {
    T n;
};
%}

%template(Foo) Foo<int>;
%template(LegacyFoo) Foo<int>;
```
Here template `Foo<int>` is instantiated twice with different names, probably for backward compatibility reasons. This works fine without -builtin, but with -builtin it gives compilation errors:
```
example_wrap.cxx:4126:24: error: redefinition of ‘PyGetSetDef SwigPyBuiltin__FooT_int_t_getset []’
 4126 | SWIGINTERN PyGetSetDef SwigPyBuiltin__FooT_int_t_getset[] = {
```
and several similar ones.

The issue here is that the names of generated structures are derived from the template name and its arguments (FooT_int_t) rather than from the names given to each instantiation. The former are the same and cause the name clash. The latter are unique and would have worked.

This would be good to fix since it works without -builtin and also works when using other languages (at least C#, Java, R, and Scala). Alternatively, it may be nice to get some support for aliasing, which is handy for migrations/backward compatibility reasons. My understanding is that currently [only renaming is supported](https://github.com/swig/swig/issues/1069). Aliasing is more efficient, since we will not duplicate the whole template class.

**Comment by ojwb** [comment]
> also works when using other languages (at least C#, Java, R, and Scala)

Um, SWIG doesn't have Scala support...

The mzscheme wrapper won't compile as it has duplicate definitions of `_swig_struct_type__FooT_int_t`.

The ruby wrapper won't compile as it has duplicate definitions of `free_Foo_Sl_int_Sg_`.

Looks like SWIG also use names based on `FootT_int_t` for guile, javascript, lua, ocaml, octave, perl5, php, python (without `-builtin`), r, scilab and tcl  but those wrappers all compile OK so this may not be a problem (from a quick peer at the generated code, I think the types essentially end up aliased together).  I just tested compilation though so it is possible there may be runtime problems in some cases.

**Comment by eltoder** [comment]
@wsfulton so the second definition will be ignored, correct?

Re creating the alias manually, that's easy enough if one only targets python. However, if I generate bindings for several languages, I have to write similar code for each with ifdefs. And for Java and C# I'm not sure that's even possible.
