### ISSUE TITLE
Segmentation fault with miniconda python

### ISSUE THREAD

**Issue by byildiz** [swig/swig#2637]
Hi everyone,

I compile the simple example (https://github.com/swig/swig/tree/f6fa291f1aae4a292a6c05b6ca8ff0b0eae3b89b/Examples/python/simple) on an OSX machine with the following cmake file:

```
cmake_minimum_required(VERSION 3.26)

project(Example)

find_package(SWIG 4.1 REQUIRED)
include(${SWIG_USE_FILE})
message(STATUS ${SWIG_VERSION})
message(STATUS ${SWIG_EXECUTABLE})

find_package(Python COMPONENTS Development)
include_directories(${Python_INCLUDE_DIRS})
message(STATUS ${Python_VERSION})
message(STATUS ${Python_INCLUDE_DIRS})
message(STATUS ${Python_LIBRARIES})

include_directories(${CMAKE_CURRENT_SOURCE_DIR})

set(CMAKE_SWIG_FLAGS "")

set_source_files_properties(example.i PROPERTIES SWIG_FLAGS "-includeall")
swig_add_library(example LANGUAGE python SOURCES example.i example.c)
target_link_libraries(example ${Python_LIBRARIES})
```

I have the following python versions installed with both `brew` and `pyenv`:
```
with brew:
3.11.3

with pyenv:
3.11.3
3.10.11
miniconda3-latest: python version 3.10.11
```

For all of the python versions, the simple example compiles without any error and except _miniconda3-latest_ version all of them works. When it comes to _miniconda3-latest_, while importing `example.py` python gives `segmentation fault` error and exits. I tried swig 4.1.1 installed with brew, pip and conda. Everytime I had the same result.

Am I doing something wrong or something missing for miniconda?

Thanks in advance.

**Comment by byildiz** [comment]
After I run `./autogen.sh`, `./configure` and `make` on the top directory of the _swig_ project `make` in `Examples/python/simple` worked and created `example.py` which I could import. But I still don't understand why it doesn't work with _cmake_ with above _CMakeList.txt_ file content.

**Comment by ojwb** [comment]
I'd suggest comparing the commands that your cmake build runs with the working commands that our build system uses.

If that doesn't help, then we don't maintain cmake's SWIG integration so probably best to ask whoever does (not sure who that is, maybe the cmake developers themselves?)

Not a SWIG bug so closing.

**Comment by byildiz** [comment]
I compared the build command from cmake with the one from swig's build system and the difference is these linker options: `-flat_namespace -undefined suppress`. The problem was solved with the following line added to _CMakeLists.txt_ file:

```
set_property(TARGET example APPEND PROPERTY LINK_FLAGS "-flat_namespace -undefined suppress")
```

I don't know what those linker options are for but maybe this solution will be useful for others, too.
