### ISSUE TITLE
Syntax error parsing expression calling function using ()

### ISSUE THREAD

**Issue by wsfulton** [swig/swig#2640]
Below results in `Error: Syntax error in input(3)`
```swig
%inline %{

#include "example.h"
#include <limits>

class Piece {
public:
    typedef size_t size_type;
    typedef int difference_type;
    static constexpr size_type kMaxSize = (std::numeric_limits<difference_type>::max)(); 
};
%}
```
I was hoping this would be fixed with the various commits leading up to closing #2486, but it is in fact unrelated.

@ojwb, would you be able to assist with this one? I've got a particular interest in this one working and so have tagged it with the 4.2 milestone.

**Comment by ojwb** [comment]
It parses with an extra set of parentheses around it:

```
static constexpr size_type kMaxSize = ((std::numeric_limits<difference_type>::max)());
```

So it seems we have grammar rules to handle such expressions, just not as the top level of an expression.  I worry they may be where they are currently to avoid introducing more conflicts.  I'll have a quick poke and see what I can see.

**Comment by ojwb** [comment]
We seem to parse this expression fine in a `%constant` (`kOk3`) or as an enum initialiser (`kOk4`) but not as a function default argument:

```
%module x
%inline %{

#include "example.h"
#include <limits>

class Piece {
public:
    typedef size_t size_type;
    typedef int difference_type;
    static constexpr size_type kOk1 = ((std::numeric_limits<difference_type>)::max()); 
    static constexpr size_type kOk2 = std::numeric_limits<difference_type>::max(); 
    %constant kOk3 = (std::numeric_limits<difference_type>)::max(); 
    enum { kOk4 = (std::numeric_limits<difference_type>)::max() }; 

    // Fails to parse:
    static constexpr size_type kMaxSize = (std::numeric_limits<difference_type>::max)(); 
    // Also fails to parse:
    int f(int x = (std::numeric_limits<difference_type>::max)()); 
};
%}
```

That seems odd as all of these cases look like they should try to parse the expression as `expr`.  I'm wondering the resolution of one of the existing conflicts in the grammar is stopping that.  Or maybe I'm just not seeing this right.  I can try poking it again later.

**Comment by ojwb** [comment]
I had an idea and tried building the parser as a GLR parser (add `%glr-parser` and then hack at places where the parser currently modifies $N variables which are `const` in when built as a GLR parser).  A GLR parser effectively parses both alternative resolutions in parallel until it can rule out one.

However this doesn't fix the parse error, which I think probably means it isn't a problem due to conflict resolution.

(I'll probably tidy up and merge my currently hacky changes as it seems cleaner not to modify those $N variables even though we're able to when the parser is generated as LALR.  It also enables experimenting with making the parser a GLR parser which may be worth considering as it should make it much easier to parse the various C++ cases we currently fail to because it's too hard to modify the grammar without introducing more conflicts.)

Anyway, I really need to get on with other stuff now!

**Comment by ojwb** [comment]
Looking through the expression grammar, I don't actually see a case for handling this, and trying to add one introduces conflicts.  Even trying a really specific new rule by adding this to `exprmem` introduces a new S/R conflict:

```
| LPAREN ID DCOLON ID LESSTHAN ID GREATERTHAN DCOLON ID RPAREN LPAREN RPAREN { }
```

I think `kOk3` and `kOk4` must parse as something else and that's what the conflicts are with, but I'm not immediately seeing what.  Probably looking at the verbose output of bison would tell us, but I think this is a can of worms.

Probably the most feasible option for fixing this case (which would also solve other expressions SWIG fails to parse in this context) is to handle this case via error recovery (by skipping to the closing `;`).  The simple approach is probably to then just ignore the declaration, but we might be able to just grab the expression text and use it verbatim.

**Comment by ojwb** [comment]
@wsfulton This patch warns and ignores such declarations:

```
diff --git a/Source/CParse/parser.y b/Source/CParse/parser.y
index 740d876e..ddfa59be 100644
--- a/Source/CParse/parser.y
+++ b/Source/CParse/parser.y
@@ -3253,6 +3253,10 @@ c_decl  : storage_class type declarator cpp_const initializer c_decl_tail {
 	      if ($4.qualifier && $1 && Strstr($1, "static"))
 		Swig_error(cparse_file, cparse_line, "Static function %s cannot have a qualifier.\n", Swig_name_decl($$));
            }
+	   | storage_class type declarator cpp_const EQUAL error SEMI {
+	      Swig_warning(999, cparse_file, cparse_line, "Ignoring declaration of '%s' due to parser limitation.\n", $3.id);
+	      $$ = 0;
+	   }
            /* Alternate function syntax introduced in C++11:
               auto funcName(int x, int y) -> int; */
            | storage_class AUTO declarator cpp_const ARROW cpp_alternate_rettype virt_specifier_seq_opt initializer c_decl_tail {
```

Obviously a warning number would need allocating, and the message could probably be improved.  However it'd be better to actually pull out the value instead, but we seem to lack existing helpers to do that for such a case.

This doesn't help the default parameter value case above either.

**Comment by wsfulton** [comment]
That would be a reasonable workaround. We could even use the declarator and add it to the parse tree and change the warning to something like `Value assigned to <id> not used due to limited parsing implementation`. By and large the values the assigned to an identifier are not used further, so I can't think of much loss of functionality in this case. The warning could even be one of those that is suppressed by default.

The error recovery approach will probably provide a reasonable solution to other cases that don't parse (yet!).

I know that max in this case does not take any parameters, but assuming it does, then when an argument, such as 123, is passed to it, there are no parser errors.

Stating the obvious probably: this fixes Piece::kMaxSize, but Piece::f still fails to parse.

I'm afraid that I can't contribute much of a solution here as this part of the parsing is just not something I fully follow, so thanks for looking, much appreciated.

**Comment by ojwb** [comment]
> Stating the obvious probably: this fixes Piece::kMaxSize, but Piece::f still fails to parse.

Yes, I explicitly noted this: "This doesn't help the default parameter value case above either."

Finding the end of the expression by scanning would be much more complicated there (something like "the next `,` or `)` which isn't inside balanced `(`...`)`, `{`...`}` or `<`...`>`, except that `<` and `>` can occur unbalanced...)

Not storing the value seems a reasonable approach.  Even if this gets handled as a constant where we might want to use the expression as a target language constant, that's not going to work for `(std::numeric_limits<difference_type>::max)()` anyway.

**Comment by ojwb** [comment]
Trying to handle `<` and `>` by scanning rather than parsing seems hard to do without risking skipping to the wrong place.  E.g. here we the default value for `x` is `a<b` and so ends just before the `,`:

```
int a, b, c;
typedef int y;
int foo(int x = a<b, y = b>::c);
```
but here the default value for `x` is `a<b, y == b>::c` and so ends just before the `)`:

```
constexpr int b = 1, y = 2;
template<int I, bool B> struct a {
    constexpr static int c = I;
};
int foo(int x = a<b, y == b>::c);
```

There's one difference between the two `foo`s (`=` vs `==`) but this demonstrates we can't decide based only on considering delimiter pairs.  I also suspect there's an example with the exact same token sequence which I've just failed to come up with right away.

Maybe for the default parameter case we could have a partial solution which tried to skip to the end of the expression but gave up if it encountered a `<` token.  That wouldn't solve the artificial case I made up above, but would solve a subset of cases including some users have actually hit such as https://sourceforge.net/p/swig/bugs/1167/ (which I couldn't work out how to parse without additional shift/reduce conflicts).

**Comment by ojwb** [comment]
> That wouldn't solve the artificial case I made up above

i.e.:

```
int f(int x = (std::numeric_limits<difference_type>::max)()); 
```

Actually it could because the `<` is inside surrounding `(` and `)` tokens which we know must be balanced.  The problematic case is a `<` token outside of any `(`...`)` or `{`...`}` (or `[`...`]` since that must appear balanced in an expression too).

**Comment by ojwb** [comment]
> (I'll probably tidy up and merge my currently hacky changes as it seems cleaner not to modify those $N variables even though we're able to when the parser is generated as LALR. It also enables experimenting with making the parser a GLR parser which may be worth considering as it should make it much easier to parse the various C++ cases we currently fail to because it's too hard to modify the grammar without introducing more conflicts.)

Tidied up and committed as f3101c6f78280ad2c935af3de1d05783cfe23f9e.

**Comment by wsfulton** [comment]
Actual source of the code causing this problem is at 
https://github.com/protocolbuffers/protobuf/blob/v21.0/src/google/protobuf/stubs/stringpiece.h#L182

BTW, the following two in the example appear not to be valid c++:
```c++
    static constexpr size_type kOk1 = ((std::numeric_limits<difference_type>)::max()); 
    enum { kOk4 = (std::numeric_limits<difference_type>)::max() }; 
```
gcc and clang result in: `error: ‘::max’ has not been declared` and
`error: no member named 'max' in the global namespace` respectively.
I think the C++ compilers think it as an attempt to cast the type return from a global function called max.

**Comment by ojwb** [comment]
> BTW, the following two in the example appear not to be valid c++: [...]

Oh sorry, those were typos!  I meant them to be testing the same problematic expression as your original case, i.e.:

```
    static constexpr size_type kOk1 = ((std::numeric_limits<difference_type>::)max());
    enum { kOk4 = (std::numeric_limits<difference_type>::max)() };
```

With your merged changes the first line is now handled with the new warning (SWIG 4.1.0 fails on that) but we still give `Error: Syntax error in input(3)` for the second line.  We could handle that using error recovery but we'd need code to skip to the next `,` or `}` which not inside balanced delimiters.  I think this probably isn't a corner case we need to prioritise though.
