### ISSUE TITLE
C++ using directive does not work with ctor

### ISSUE THREAD

**Issue by joeBlinx** [swig/swig#2641]
Hi! 

I'm using swig 4.1.1 downloaded through pip on an Ubuntu 20.04. I'm trying to wrap this C++ code into Java
```cpp
// file.h
struct A {
  A(int, double, float){}
  A() = default;
};
struct B : A {
  using A::A;
};
```
My `.i` file look like this
```
%module Wrapper
%{
#include "file.h"
%}
%include "file.h"
```
It compile with swig without error or warning but the B class in java only have the default ctor and do not have the ctor with the `int, double, float` parameters that comes from the A class.

Do I miss something or is it a swig limitation ?

Thanks for your help !

**Comment by ojwb** [comment]
> Do I miss something or is it a swig limitation ?

Probably the latter.  Seems to be the same in git master too.

(There may be an open ticket for this but "using" is a noisy search term and github's poor search feature isn't helping me check - is there really no way to search just in ticket titles?)

**Comment by ojwb** [comment]
Looks like you can work around this using `%extend` - try adding this to your `.i` file:

```
%extend B {
  B() { return new B(); }
  B(int a, double b, float c) { return new B(a, b, c); }
}
```

The resulting `_wrap.cxx` contains plausible code and compiles.

**Comment by joeBlinx** [comment]
That works !  Thanks!

**Comment by wsfulton** [comment]
This is a C++11 feature which allows using declarations to inherit constructors.

**Comment by ojwb** [comment]
@wsfulton There seems to be a warning from your new testcase (not specific to ocaml, it happens for python and php too at least, and probably all target languages):

```
checking ocaml testcase cpp11_using_constructor
../../../../../Examples/test-suite/ocaml/../cpp11_using_constructor.i:253: Warning 315: Nothing known about 'Superclass::TypedefBase1'.
```

Is there a reason why we don't use swig's `-Werror` for the testsuite to stop warnings creeping in?

**Comment by wsfulton** [comment]
> Is there a reason why we don't use swig's -Werror for the testsuite to stop warnings creeping in?

Would be nice, except there are numerous warnings to fix first. Probably better to have test that warn actually running with a warning rather than completely disabled, given some of the warnings will be hard to fix.

I noticed this warning, which is a mistake as I'd forgotten to add the cpp11_using_constructor.i file and when I noticed I had already started modifying it for my next improvement, so a future state of it got committed by mistake. Will sort out in a future commit, but harmless atm.

**Comment by wsfulton** [comment]
> (There may be an open ticket for this but "using" is a noisy search term and github's poor search feature isn't helping me check - is there really no way to search just in ticket titles?)

Use 'is:title' in your Github search.
https://github.com/swig/swig/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+using+
