### ISSUE TITLE
[C#] Support for movable std::unique_ptr

### ISSUE THREAD

**Issue by christophe-calmejane** [swig/swig#2650]
As discussed in #2411 move support for unique_ptr is missing.
I've implemented it for C# but I've question before I can push a PR.

@ojwb
I've made a test that checks that my fix in working, but there is currently no compilation issue whatsoever. The behavior is for swig to generate the default void* typemap (eg. SWIGTYPE_p_std__unique_ptrT_int_t.cs). When working correctly (after my fix), that file doesn't exist.
Is it possible with the existing framework to setup a test that will check that condition for success/failure? If yes, how?

I plan on adding this test:
```swig
%module cpp11_unique_ptr_move

%include <std_unique_ptr.i>

%unique_ptr(Bar);

%inline %{

#include <memory>

class Bar
{
public:
	Bar() = default;
};

class Foo
{
public:
  using UniquePtr = std::unique_ptr<Bar>;

  Foo() = default;

  void set_ptr(UniquePtr&& ptr) { _ptr = std::move(ptr); }

private:
  UniquePtr _ptr{ nullptr };
};

%}
```

Thanks.

**Comment by wsfulton** [comment]
Since this was raised, generic move semantics support was improved considerably in swig-4.1.0, see #999. @christophe-calmejane, can you check if that has made a difference or not here?

**Comment by christophe-calmejane** [comment]
I tried to compile the latest master branch but cannot due to visual studio compilation errors:
```
swig\Source\CParse\cscanner.c(422,24): error C2065: 'NUM_DOUBLE': undeclared identifier
swig\Source\CParse\cscanner.c(428,28): error C2065: 'NUM_LONGDOUBLE': undeclared identifier
swig\Source\CParse\cscanner.c(619,18): error C2065: 'NUM_DOUBLE': undeclared identifier
swig\Source\CParse\cscanner.c(625,22): error C2065: 'NUM_LONGDOUBLE': undeclared identifier
swig\Source\CParse\cscanner.c(619,3): error C2051: case expression not constant
swig\Source\CParse\cscanner.c(625,3): error C2051: case expression not constant
```

I went back to the commit just before the one that broke this, and I confirm that my fix (https://github.com/christophe-calmejane/swig/commit/0f069b8ee523991449324c3c601fb45e7bfe662a) is still required for the snippet in the OP to properly generate C# files.
Without my fix, a `SWIGTYPE_p_std__unique_ptrT_Bar_t.cs` useless file is created. With my patch it's correctly usable from C#.

**Comment by ojwb** [comment]
Sounds like you need to rerun bison to re-generate the parser.  This ought to happen automatically if the grammar file is newer than the generated files.

If the parser isn't getting regenerated there's not much point testing as you're potentially using a different version of the parser to the rest of the code...

**Comment by CorrM** [comment]
Any updates?
