### ISSUE TITLE
Support pure virtual functions in %extend (so they can use directors)

### ISSUE THREAD

**Issue by MeFisto94** [swig/swig#2651]
I'm wrapping a class that contains a pure virtual function that has a lot of c++isms I'd love to avoid from the API/Wrapping (in fact, I can't get proper types out of it, but even if I could, it would be undesireable).

Thus, my idea was to `%extend` the existing class, so swig sees a new pure virtual function that it will create a director for.
I'd then implement the existing pure virtual function using `%{` and make it call into the director. Both of that would happen in the `_wrap.cxx` and thus being transparent to the ABI.

My problem now is, that `%extend` seems to ignore all functions without a body in general.
Is this a reasonable feature suggestion?

For more context, I've created a write up at [stackoverflow](https://stackoverflow.com/questions/76608072/swig-method-that-only-exists-on-the-binding-layer) with the actual code I'm trying to wrap as well.

**Comment by ojwb** [comment]
`%extend` actually creates a C/C++ non-class function, taking the object as a first parameter, then wraps it as if it were a method of the class in question. This means you can't usefully add a virtual method via `%extend`, though it'd be more helpful if SWIG warned about this if you try.

To work as you want, `%extend` would need to instead create a C++ subclass with the actual additional methods, and then wrap that in place of the original class.

There's some discussion of this in #503.

For your situation, I'd suggest defining an actual C++ subclass yourself with the virtual method(s) you want and get SWIG to wrap that instead (e.g. define this subclass in a `%inline` block in your interface file).  You can use `%ignore` and `%rename` so the original class doesn't get wrapped and so your subclass is wrapped with the name of the original class.

**Comment by MeFisto94** [comment]
I hope you guys don't mind a second question that isn't exactly related to the title of the issue anymore, but still in the context of my problem. Essentially I am having a hard time at typemapping the resulting method of the subclass, as it contains directors, arrays and `out` parameters.

Essentially I am coming from 
```c++
virtual void getDataForSuspensionComponentCSharp(PxVehicleAxleDescription* &axleDescription,
[...]
         PxReal **steerResponseStates,
```

into
```csharp
public virtual void getDataForSuspensionComponentCSharp(out PxVehicleAxleDescription axleDescription, [...], out float[] steerResponseStates)
```

So, simply applying `OUTPUT[]` isn't enough.
I think I made quite some progress, by typemapping the `ctype`, `cstype`, `imtype` and `directorin`, I could at least get the native side to compile, example
```
%typemap(ctype)   physx::vehicle2::PxVehicleAxleDescription*& "physx::vehicle2::PxVehicleAxleDescription**"
%typemap(cstype)  physx::vehicle2::PxVehicleAxleDescription*& "out PxVehicleAxleDescription"
%typemap(imtype)  physx::vehicle2::PxVehicleAxleDescription*& "global::System.IntPtr"
%typemap(directorin) physx::vehicle2::PxVehicleAxleDescription*& "$input = (physx::vehicle2::PxVehicleAxleDescription**) $1;"
```

now the problem is the director method. With something like:
```
%typemap(csdirectorin) physx::vehicle2::PxVehicleAxleDescription*& "out var var_$iminput"
```
I could get the method call inside the director method to support the `out` paradigm, but I have yet to find a typemap that allows me to insert code into the method body, so I can copy `var_$iminput`s CPtr into the address pointed at by the IntPtr that is part of the Pinvoke signature:

```
private void SwigDirectorMethodgetDataForSuspensionComponentCSharp(global::System.IntPtr axleDescription,
```

So, my current state looks like
```
private void SwigDirectorMethodgetDataForSuspensionComponentCSharp(global::System.IntPtr axleDescription[...}) {
    getDataForSuspensionComponentCSharp(out var var_axleDescription, [...]));
  }
```

And I fear like arrays will make that even more complicated, but I guess in theory I'd just need to `Array.Convert` all the types into their cptr (unless we're talking primitives such as the floats here) and then just write all of them to the IntPtr.

**Comment by ojwb** [comment]
It'd be better to open a fresh ticket for unrelated matters.

**Comment by ojwb** [comment]
This is really covered by #503, so closing this as a duplicate.
