### ISSUE TITLE
Calling one typemaps from another typemaps

### ISSUE THREAD

**Issue by Vikzy** [swig/swig#2668]
Hi,
Is there a way to call a typemap (out )  from my another custom typemap (out).

I have custom typemap 
typemap (out) std::pair < std::vector< customClass* >,std::vector < std::string > >
{
    if($1.first.empty() == false || $1.second.empty() == false)
    {
          if($1.first.empty() == false)
                  //call std_vector.i typemap with S1.first
          else
               //call std_vector.i typemap with S1.first
    }
}

I want to call the typemaps defined here https://github.com/swig/swig/blob/master/Lib/tcl/std_vector.i

**Comment by ojwb** [comment]
You can use e.g. `$typemap(out, std::vector< customClass* >)` to expand that typemap within your, but I think that only supports applying that typemap to the same `$1` you're already dealing with whereas you want `$1.first` instead it seems (at least I assume that's what your "S1.first" is meant to be).  Maybe `$typemap` could be extended to provide a way to specify what you want (e.g. via an optional third argument).

I think there's a mistake in your example though as both branches of the else are the same comment, so I don't follow what you're actually trying to do.

**Comment by wsfulton** [comment]
I think @ojwb answered this on how to use `$typemap`. There are many more example usages in the Lib directory and Examples/test-suite/*.i tests which you can search.

**Comment by ojwb** [comment]
@wsfulton I did explain how to use `$typemap` but also noted that doesn't seem to work for this case as it uses the same `$1` but it seems they want to expand a typemap with `$1.first` in place of `$1`.  Or is there a way to do that which I missed?

**Comment by wsfulton** [comment]
I see, this works for me:
```swig
%typemap (out) std::pair < std::vector< customClass* >,std::vector < std::string > >
{
  if($1.first.empty() == false || $1.second.empty() == false)
  {
    if($1.first.empty() == false) {
      std::vector< customClass* >& result_first = $1.first;
      std::vector< customClass* >& result = result_first;
      $typemap(out, std::vector< customClass* >);
    } else {
      std::vector< std::string >& result_second = $1.second;
      std::vector< std::string >& result = result_second;
      $typemap(out, std::vector< std::string >);
    }
  }
}
```
