### ISSUE TITLE
Variables of array type are not initialized by `Swig_cargs`

### ISSUE THREAD

**Issue by mmomtchev** [swig/swig#2675]
In the `javascript_lib_arrays` unit test, the `arg1` argument of `sum2` is of type `a(3).int`.

This variable is declared without being initialized:

```
int *arg1;
```

Which becomes a problem once the `freearg` typemaps are applied on the error path.

`Swig_cargs` does not initialize arrays:
https://github.com/swig/swig/blob/68ec78b37abbfe11d0274411320e1320750c7bff/Source/Swig/cwrap.c#L299

**Comment by mmomtchev** [comment]
According to the comment in `Swig_lstr`, arrays are converted to single pointers, to these can always be initialized.

**Comment by wsfulton** [comment]
The "in" typemap could alternatively do the initialisation with `$1 = 0;`. However, it makes sense for consistency for variable to always be initialised to zero like pointers are. Sometimes the pointer typemaps are applied to array types and vice-versa so the initialisation should be consistent.
