### ISSUE TITLE
windows swig python dll couldn't load issue

### ISSUE THREAD

**Issue by LoadLife** [swig/swig#2678]
[https://stackoverflow.com/questions/77111000/windows-swig-python-dll-couldnt-load-issue](url)
1. i make `sub.dll` and linked by `_example.pyd`, the produt of my project is `_example.pyd exaple.py and sub.dll`
2. now i start set directories that `sub.dll` and `_example.pyd` locate in as ENV "PATH"
3. when i use python import example, it says that dll module load failed: no specified dll(it means that it can't found sub.dll)
4. when i move '_example.pyd, example.py and sub.dll' in the same folder, it works. why? i'm confused. :(
![cmake](https://github.com/swig/swig/assets/35225514/6d36ff11-8592-4e02-bed0-727f6d5f288a)
![swig_pj](https://github.com/swig/swig/assets/35225514/9d633edc-bb7e-4f96-abbd-3c63e0652700)

**Comment by jschueller** [comment]
since python 3.8 the dll search changed a bit, look for add_dll_directory:
https://docs.python.org/3.8/library/os.html#os.add_dll_directory

**Comment by LoadLife** [comment]
> since python 3.8 the dll search changed a bit, look for add_dll_directory: https://docs.python.org/3.8/library/os.html#os.add_dll_directory

thanks, it solves my problem

**Comment by LoadLife** [comment]
thanks for yours help!
