### ISSUE TITLE
C# usage %varargs example: bug or feature?

### ISSUE THREAD

**Issue by burnss887** [swig/swig#2680]
Hello all,

I have a sample of swig code:
`
%varargs(int arg) fooTest;
%varargs(char* arg) fooTest;

%inline 
%{
void fooTest(SomeType* ptr, ...) {}
%}
`

But in result I see only applying second %varargs rule. The usage of first rule was excluded. 

Is this a feature or am I doing something wrong?

Because I expect the result in C# API as:
void fooTest(SomeType ptr, int arg);
void fooTest(SomeType ptr, String arg);

Thanks.

**Comment by ojwb** [comment]
`%varargs` just sets `feature:varargs` on the node, so setting it a second time overwrites the first setting - I think that probably makes it a feature.

I'd suggest just defining forwarding overloads inline in your interface file for SWIG to wrap, e.g.:

```
%ignore fooTest;
%rename("fooTest") fooTest_;
%inline %{
void fooTest_(SomeType* ptr, int arg) { fooTest(ptr, arg); }
void fooTest_(SomeType* ptr, char * arg) { fooTest(ptr, arg); }
%}
```

Note that I've given the forwarding functions a different name in C/C++ to avoid them just calling themselves, then told SWIG to rename them in the target language (and to not try to wrap the original function).

If this were a class function then you could use `%extend` to add similar wrappers as methods.
