### ISSUE TITLE
[JavaScript] uint64_t as the target type for BigInt throws TypeError

### ISSUE THREAD

**Issue by nrkramer** [swig/swig#2682]
It seems that the underlying logic for numeric conversion does not support BigInt -> uint64_t conversions, even though the NodeJS NAPI supports it: https://nodejs.org/api/n-api.html#napi_get_value_bigint_uint64

Adding code that queries the Node API for the underlying type returns true (in this example, the first parameter is a BigInt):
```
info[0].IsBigInt(); // returns true
```

However the code that does the conversion:
```
res1 = SWIG_ConvertPtr(info[0], &argp1, SWIGTYPE_p_uint64_t,  0 );
```

throws a TypeError exception: `TypeError: in method 'myMethod', argument 1 of type 'uint64_t'`

Now - I'm not super familiar with the SWIG codebase, however I'd like to help provide diagnostics and code as necessary. I'm hoping a SWIG expert can take a look.

**Update**: I found a workaround is to do a number -> double conversion instead, then cast the double to uint64_t in C/C++, however this is not ideal.

**Comment by ojwb** [comment]
The `SWIGTYPE_p_uint64_t` is a clue that SWIG doesn't have type information.

You probably just need to add `%include <stdint.i>` to your interface file (like how you need `#include <stdint.h>` in C).

**Comment by nrkramer** [comment]
Ah! That worked! Great pointer, thanks!
