### ISSUE TITLE
director_finalizer_runme.php is failing with PHP 8.3

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#2685]
Rebuild of SWIG 4.1.1 is failing with PHP 8.3 which is in Fedora Rawhide now.

```
/builddir/build/BUILD/swig-4.1.1/Examples/test-suite/php/director_finalizer_runme.php:20: Calling get_parent_class() without arguments is deprecated
make[2]: *** [../../../Examples/Makefile:1216: php_run] Error 1
make[1]: *** [Makefile:53: director_finalizer.cpptest] Error 2
```

Fedora Rawhide (F40) contains  `swig-4.1.1` and `php-8.3.0~RC3`

It is related to [this change](https://php.watch/versions/8.3/get_class-get_parent_class-parameterless-deprecated)

**Comment by ojwb** [comment]
FYI I've also added a CI job testing PHP 8.3 which passes, so it seems that was the only compatibility issue.
