### ISSUE TITLE
Excecute piece of code at python object creation

### ISSUE THREAD

**Issue by MaduxCaster** [swig/swig#2688]
Hello,

I met some problems by using SWIG. I don't know if I am in the good place to ask some help, so please excuse me if it is not the case.
I meet some trouble when trying to execute some pieces of code every time a specific python object is created by SWIG. I think my problem is identical to this one (https://stackoverflow.com/questions/15260000/swig-and-python-different-object-instantation), but I have not found any solution.

I have tried to make an minimal reproducible test of my problem :

// test.h
```
#ifndef TEST
#define TEST
#ifdef __cplusplus
extern "C" {
#endif
typedef struct{int value;} mystru;
mystru mystru_create();
#ifdef __cplusplus
}
#endif
#endif
```

// test.c
```
#include "test.h"
mystru mystru_create()
{
   mystru result ;
   result.value = 3 ;
   return( result ) ;
}
```

// swigtest.i
```
%module swigtest
%{
#include "test.h"
%}
%feature("ref")   mystru "printf(\"Object mystru created\\n\");"
%feature("unref") mystru "printf(\"Object mystru deleted\\n\");"
%include "test.h"
```

The swig command:
`swig -c++ -python -o swigtest.cpp swigtest.i`

The compilation command:
`g++ -shared -fPIC test.c swigtest.cpp -I/TMPLOCAL/monod-rap/Logiciels/anaconda3/include/python3.7m/ -o _swigtest.so`

The python script:
```
#!/usr/bin/env python3
import swigtest
print("C function returning a new object..." )
b1 = swigtest.mystru_create()
print("Direct python creation..." )
b2 = swigtest.mystru()
print("---")
```

Output:
```
C function returning a new object...
Direct python creation...
Object mystru created
---
Object mystru deleted
Object mystru deleted
```

We can observe that the feature "ref" is executed only when the object is directly created by python, and not when the object is created by C++ to encapsulated the result of a C/C++ function.

Is that behaviour expected, and is there any way to execute some piece of code each time a python object is created, at the end of initialization step ?

Thanks a lot for any help

**Comment by ojwb** [comment]
You need to use `%newobject mystru_create();` - there's actually an example of this in the manual section about `ref`/`unref`.

**Comment by MaduxCaster** [comment]
Oh yes ! I am sorry I have seen this keyword before. Thanks a lot for your help.
