### ISSUE TITLE
OCaml 5.x support ?

### ISSUE THREAD

**Issue by chetmurthy** [swig/swig#2695]
Hello,

It appears that SWIG as-released doesn't support OCaml 5.x (5.0, 5.1).  IIUC, it stopped working after OCaml 4.07.1.  In any case, a SWIG user asked me about it, and I wrote a (small) patch.   If this is something that the SWIG developers might be interested in, I can send a PR.  I read some documentation that suggested I should first open an issue before sending a PR, hence this issue.

For your amusement, the branch is: https://github.com/chetmurthy/swig/tree/ocaml-5.x-patches

**Comment by ojwb** [comment]
There's already an open PR: #2649

**Comment by chetmurthy** [comment]
Oh excellent!  I hadn't seen it!  Closing.

**Comment by ojwb** [comment]
@chetmurthy I've merged changes which hopefully make ocaml 5 work, but I don't have an easy way to check it.  Also there are some unresolved issues with SWIG's ocaml support which I've summarised at: https://github.com/swig/swig/pull/2649#issuecomment-1960605984
