### ISSUE TITLE
Inheritance of inner class from outer template class that uses another inner class as type generates unresolvable 401 warning

### ISSUE THREAD

**Issue by michael-schaller** [swig/swig#270]
SWIG version in use:
3.0.3 dev,  commit 2749771 (2014-11-25)

Example code:
https://gist.github.com/michael-schaller/7635ee22a0da17b055b3

Unresolvable warning:
```
example.swigcxx:24: Warning 401: Base class 'OuterT< InnerS >' undefined.
example.swigcxx:21: Warning 401: 'OuterT< InnerS >' must be defined before it is used as a base class.
```

For some reason SWIG expects the base class 'OuterT< InnerS >' that doesn't exist.
SWIG should instead expect the existing base class 'OuterT< OuterC::InnerS >'.

@wkalinin Vladimir, can you also have a look on this issue?

**Comment by wsfulton** [comment]
While SWIG might not perform type checking, it does attempt type resolution. This is required, for example, for template partial specialization in order to obtain the correct class in template specialization. Updating the docs with this example probably would be helpful.

**Comment by michael-schaller** [comment]
@wsfulton Where would you add this example to the documentation - 6.18 (Templates) or 6.27 (Nested Classes)?

**Comment by wsfulton** [comment]
Templates section is probably best and add a link to it from the Nested classes section.

**Comment by michael-schaller** [comment]
@wsfulton, @wkalinin: Please comment on pull request #295.

**Comment by wkalinin** [comment]
Thanks Michael, I think, that illustration is generally useful for understanding how %template works.
