### ISSUE TITLE
Use SWIG with Conan invalid swiglib path

### ISSUE THREAD

**Issue by anthonyliot** [swig/swig#2700]
I am currently using Conan 1.60 to get all my dependencies from ConanCenter. But when I want to do the same for swig I am facing an issues with the swiglib path.

The swiglib path is hardcoded inside the binary with an invalid path.

Is there anyway I can specify the swiglib manually via parameter or environment variable ?

Thanks

**Comment by ojwb** [comment]
`-I` option or`SWIG_LIB` env var, as documented in the manual: https://swig.org/Doc4.0/Library.html#Library_nn2

**Comment by wsfulton** [comment]
I suspect Conan has not built or configured the build of SWIG correctly. I'd raise an issue with them.
