### ISSUE TITLE
Can references to a namespace be forced to start lookup from global::?

### ISSUE THREAD

**Issue by nrkramer** [swig/swig#2708]
For example, if I have the following generated code:
```
namespace My.FunNamespace {
   class AClass { ... }
}

namespace FunNamespace {
   class BClass { ... }
}
```

such a nested namespace requires disambiguation when operating with any code inside "My". Such as:
```
namespace My.OtherNamespace {
    class CClass {
       public void doSomething(global::FunNamespace::BClass bObject) {
            ....
       }
     }
}
```

Notice that disambiguating the namespace lookup with `global::` is _required_, because the `FunNamespace` already exists under `My.`, but we want to refer to the `FunNamespace` namespace under the global namespace.

Is there a way to force any generated code to prefix the namespace with `global::` outside the generated class?

I've tried something like `%typemap(cstype) FunNamespace::BClass "global::FunNamespace::BClass"` with no luck

**Comment by wsfulton** [comment]
The cstype typemap is the right way to prefix with `global::`. For example:
```swig
%typemap(cstype) FunNamespace::BClass "global::FunNamespace.BClass"
```
You have however, used C++ syntax for the C# name. Note the subtle difference to what you posted.

You can also do this across the board by looking in csharp.swg and copying and changing the SWIGTYPE family of typemaps from, for example:
```swig
%typemap(cstype) SWIGTYPE "$&csclassname"
```
to
```swig
%typemap(cstype) SWIGTYPE "global::$&csclassname"
```

**Comment by ojwb** [comment]
Is there anything left to do here or can this be closed?

**Comment by nrkramer** [comment]
I'll need some time to verify this. Will ping you once I have.

**Comment by nrkramer** [comment]
Ah I meant, "global::FunNamespace.BClass". Sorry about the typo.

The cstype typemap seems to do nothing for me (Version 4.2.0). I've double, triple, quadruple-checked the fully-qualified name in C++.

**Comment by wsfulton** [comment]
Here's my complete standalone example for you:
```swig
%module example

%typemap(cstype) SWIGTYPE "global::$&csclassname /*overridden SWIGTYPE typemap*/"

%nspace FunNamespace::BClass;
%inline %{
namespace FunNamespace {
   class BClass {};
}
  class CClass {
  public:
    void doSomething(FunNamespace::BClass bObject) {
    }
  };
%}
```
Run using:
```
swig -csharp -c++  -o example_wrap.cxx example.i
```
CClass.cs contains this line:
```csharp
public void doSomething(global::FunNamespace.BClass /*overridden SWIGTYPE typemap*/ bObject) {
```

Please thoroughly study [Typemaps](https://swig.org/Doc4.1/Typemaps.html), it is an advanced topic. There are typemap examples in the C# docs too.
