### ISSUE TITLE
Ownership transfer when assigning to pointer field in a struct

### ISSUE THREAD

**Issue by mdouze** [swig/swig#2709]
SWIG is used to wrap Faiss a rather large C++ library in Python (https://github.com/facebookresearch/faiss). This is working very well and saves us tons of manual wrapping code that we'd have to write with other wrapping methods like pybind11. 

We are running into an issue where 
```C++ 
struct B {};
struct A { 
   struct B * b; 
}
```
When called like this
```python
b = B()
a = A()
assert b.this.own() 
a.b = b
assert b.this.own() 
```
the second assertion fails. This is consistent with the doc ([ section 33.4.3](https://www.swig.org/Doc4.1/SWIGDocumentation.html#Python_nn30)).

We would like to revert this behavior, ideally for all pointer fields in structs or otherwise by having some macro / typemap that we can apply to selected struct fields.

**Comment by wsfulton** [comment]
Either grab the ownership back using `acquire()` as follows:
```python
b = B()
a = A()
assert b.this.own() 
a.b = b
b.this.acquire()
assert b.this.own() 
```
or provide a typemap that doesn't disown. The default typemap is
https://github.com/swig/swig/blob/22303787eb8b254954bfbc5b43ddcfd833b42314/Lib/typemaps/swigtype.swg#L5-L11
Just remove `$disown` which is replaced with `SWIG_POINTER_DISOWN` for implementing the disown and target the member variable in question:
```swig
%typemap(in, noblock=1) B *b(void  *argp = 0, int res = 0) {
  res = SWIG_ConvertPtr($input, &argp,$descriptor, /* $disown | */ %convertptr_flags);
  if (!SWIG_IsOK(res)) { 
    %argument_fail(res, "$type", $symname, $argnum); 
  }
  $1 = %reinterpret_cast(argp, $ltype);
}
```
Put this typemap before the `B *b` member is parsed. You may  want to clear the typemap after the struct is parsed so that it does not accidentally get used again.
```swig
 %clear B *b;
```
 It's a low risk leaving out the clear unless you have other instances of the same type and variable name and don't want to disown them.

**Comment by mnorris11** [comment]
Hi @wsfulton , thanks for your detailed prior reply to Matthijs. I know it has been a while, but I am looking into this again on the Faiss side. I am attempting to get the typemap to match first, before looking into ownership of ConvertPtr.

The setup is like this:
```
struct B {};
struct C : B {}; // C is a sub-struct of B
struct A { 
   struct B * b; 
}
```

Then it is called like:
```
c = C()
a = A()
a.b = c
```

I was not able to get the typemap to match when assigning `a.b = c`. These are the typemap signatures I tried:
```
%typemap(in, noblock=1) B *b(void  *argp = 0, int res = 0) {
  printf("foo");
  $1 = NULL;
}
%typemap(in, noblock=1) B *b { ... etc ...
%typemap(in, noblock=1) B * {  ... etc ...
%typemap(in, noblock=1) C *b(void  *argp = 0, int res = 0) {  ... etc ...
%typemap(in, noblock=1) C *b {  ... etc ...
%typemap(in, noblock=1) C * {  ... etc ...
%typemap(memberin, noblock=1) B * { ... etc ...
%typemap(memberin, noblock=1) B * sel { ... etc ...
```

None of these print. How might we match a typemap to the above setup? Apologies if I missed it in SWIG docs.

**Comment by wsfulton** [comment]
> Put this typemap before the B *b member is parsed. 

Make sure you do this! If it is any help here are the files I developed for posting the info above:

example.i:
```swig
%module example

%inline %{
#include <iostream>
struct B {
  B() { std::cout << " B " << this << std::endl; }
  ~B() { std::cout << "~B " << this << std::endl; }
};
%}
%typemap(in, noblock=1) B *b(void  *argp = 0, int res = 0) {
  res = SWIG_ConvertPtr($input, &argp,$descriptor, /* $disown | */ %convertptr_flags);
  if (!SWIG_IsOK(res)) { 
    %argument_fail(res, "$type", $symname, $argnum); 
  }
  $1 = %reinterpret_cast(argp, $ltype);
}

%inline %{
struct A { 
  struct B * b; 
  A() { std::cout << " A " << this << std::endl; }
  ~A() {
    std::cout << "~A " << this << std::endl; 
//    delete b;
    b = 0;
  }
};
%}
```
runme.py
```python
from example import *

def ff():
    b = B()
    a = A()
    assert b.this.own() 
    a.b = b
    # b.this.acquire()
    assert b.this.own() 
    del a

print("calling ff")
ff()
print("called ff")
```
output:
```text
calling ff
 B 0xfc5a50
 A 0xf59390
~A 0xf59390
~B 0xfc5a50
called ff
```
and the generated `_wrap_A_b_set` function:
```c++
SWIGINTERN PyObject *_wrap_A_b_set(PyObject *self, PyObject *args) {
  PyObject *resultobj = 0;
  A *arg1 = (A *) 0 ;
  B *arg2 = (B *) 0 ;
  void *argp1 = 0 ;
  int res1 = 0 ;
  void *argp2 = 0 ;
  int res2 = 0 ;
  PyObject *swig_obj[2] ;
  
  (void)self;
  if (!SWIG_Python_UnpackTuple(args, "A_b_set", 2, 2, swig_obj)) SWIG_fail;
  res1 = SWIG_ConvertPtr(swig_obj[0], &argp1,SWIGTYPE_p_A, 0 |  0 );
  if (!SWIG_IsOK(res1)) {
    SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "A_b_set" "', argument " "1"" of type '" "A *""'"); 
  }
  arg1 = reinterpret_cast< A * >(argp1);
  res2 = SWIG_ConvertPtr(swig_obj[1], &argp2,SWIGTYPE_p_B, /* SWIG_POINTER_DISOWN | */  0 );
  if (!SWIG_IsOK(res2)) {
    SWIG_exception_fail(SWIG_ArgError(res2), "in method '" "A_b_set" "', argument " "2"" of type '" "B *""'"); 
  }
  arg2 = reinterpret_cast< B * >(argp2);
  if (arg1) (arg1)->b = arg2;
  resultobj = SWIG_Py_Void();
  return resultobj;
fail:
  return NULL;
}
```
