### ISSUE TITLE
Append pythoncode to the end of python file.

### ISSUE THREAD

**Issue by iakovts** [swig/swig#2714]
Hi,
I was wondering if there is a way to add python code to the end of the .py file produced by swig, in the exact opposite way that  %pythonbegin does. I want to attach methods with `setattr` to some of the exposed classes, but there seems to be no way to have that code after the definition (in python) of these.

**Comment by ojwb** [comment]
Just use `%pythoncode` at the end of your interface file:

```
%module test

%inline %{
class Foo {
public:
   Foo() {}
};
%}

%pythoncode %{
    Foo.x = 42
%}
```

```
$ swig -c++ -python test.i
$ tail test.py
    def __init__(self):
        _test.Foo_swiginit(self, _test.new_Foo())
    __swig_destroy__ = _test.delete_Foo

# Register Foo in _test:
_test.Foo_swigregister(Foo)

Foo.x = 42


```
