### ISSUE TITLE
Support the Vala language

### ISSUE THREAD

**Issue by iahung3** [swig/swig#2716]
Please add the ability to generate bindings for Vala (vapi files). Thank you.

**Comment by ojwb** [comment]
Adding a new target language backend is a significant amount of work and SWIG is a volunteer project, so they only get implemented when somebody who wants the support actually does that work.

If that sounds like you then you can find the guide to adding support for a new target language here:

http://www.swig.org/Doc4.1/Extending.html#Extending_nn31

Particularly important to note are the criteria for merging a new target language:

https://www.swig.org/Doc4.1/Extending.html#Extending_language_status

**Comment by ojwb** [comment]
I stumbled on https://github.com/radare/valabind which says:

> Valabind is a tool to parse vala[1] or vapi files to transform them into swig[2] interface files, C++, NodeJS-ffi or GIR.
>
> With swig, you can create language bindings for any API written in vala or C with a vapi interface.

I've not tried it, but assuming it works it sounds like a reasonable alternative to having Vala support in SWIG itself.

**Comment by iahung3** [comment]
Seems to be dead project: https://github.com/radare/valabind/issues/60

**Comment by ojwb** [comment]
3 days seems a little bit soon to conclude that.

But even if it is no longer being actively maintained, assuming it actually works it's bound to be much less work to adopt it versus implementing support for a whole new target language in SWIG and then having to maintain that.
