### ISSUE TITLE
About ruby import_fragments test failure on ruby3.3.0dev

### ISSUE THREAD

**Issue by mtasaka** [swig/swig#2721]
CI says with ruby3.3.0dev ruby import_fragments test is failing: e.g.
https://github.com/swig/swig/actions/runs/7042263395/job/19166163000

If possible, please try the latest ruby3.3.0dev (I don't know how to update ruby on CI). This should be fixed by:
https://github.com/ruby/ruby/commit/ca4755b59a7bdaaffbaef05474c8d8ee187e8d7d
https://bugs.ruby-lang.org/issues/20023

**Comment by ojwb** [comment]
It gets installed from rvm.io - looks like we can ask for `ruby-head` as the version so will try that.

**Comment by ojwb** [comment]
@mtasaka Great, that passes: https://github.com/swig/swig/actions/runs/7049728057/job/19188856986.

**Comment by ojwb** [comment]
So on the SWIG side, the thing left to do here is revert 940b41f40a3530331c4593e1e5a871b42b6796a9 once this fix is part of what we get for `3.3` from rvm.io (presumably with 3.3.0-preview4 or -rc1 or whatever).

**Comment by mtasaka** [comment]
@ojwb ruby3.3RC1 is released. Would you retest this? (BTW I am not ruby upstream, but one of the contributor for ruby on Fedora)

**Comment by ojwb** [comment]
It'll get tested on the next CI build after rvm.io updates its "3.3" to be 3.3RC1 - I can't easily test it before then.

**Comment by ojwb** [comment]
CI now passing (d03851d71c752ea861a5319a76bb2bc847991450) so closing.
