### ISSUE TITLE
Different result on CentOS and MacOS

### ISSUE THREAD

**Issue by OftenDream** [swig/swig#2726]
I'm trying to use swig to automatically generate java code from C++ code. there are classes in C++ that have the original constructors (long, boolean).
In macos swig, this conflicts with the proxy classes generated by swig. (Similar to this issue [https://github.com/swig/swig/issues/1057](https://github.com/swig/swig/issues/1057))
But in linux swig, there is no such problem. swig automatically converts constructor arguments of this type to (int, boolean).
I would like to know how to have this effect on mac as well.

proxy class:
`protected RangeSearchResult(long cPtr, boolean cMemoryOwn) `
`{`
 `   swigCMemOwn = cMemoryOwn;`
 `   swigCPtr = cPtr;`
 ` }`

constructor on macOS：
`public final static native long new_RangeSearchResult__SWIG_0(long jarg1, boolean jarg2);`
（long, boolean） is the type of the original construct in C++ code, but it conflicts with the proxy class.

constructor on CentOS：
`public final static native long new_RangeSearchResult__SWIG_0(int jarg1, boolean jarg2);`

**Comment by ojwb** [comment]
SWIG should generate the same output for a given input and options regardless of the platform it is run on.

Are the API headers you're feeding to SWIG different on each platform perhaps?

**Comment by OftenDream** [comment]
> SWIG should generate the same output for a given input and options regardless of the platform it is run on.
> 
> Are the API headers you're feeding to SWIG different on each platform perhaps?

I'm wondering if linux swig has a conversion mechanism that automatically converts the original constructor (long,boolean) to (int,boolean) if the original constructor (long,boolean) is duplicated in the parameters of the generated java proxy class (long,boolean).

**Comment by ojwb** [comment]
No

**Comment by ojwb** [comment]
@OftenDream Did you resolve this?

If not and the inputs to SWIG are identical in each case, check the SWIG versions are the same (including any vendor-applied patches if you're using packaged versions of SWIG rather than building it yourself).

If the inputs and SWIG versions are the same but you're still getting different output then I think we'll need a self-contained reproducer.

**Comment by ojwb** [comment]
No response for a month so assuming resolved and closing.
