### ISSUE TITLE
How external projects implement passing C++ objects to Python

### ISSUE THREAD

**Issue by mujinjia** [swig/swig#2731]
I have a large C++ library that I generated into a Python library using SWIG, and now I need to create a C++ program that creates an object from the C++ library, and I want to be able to pass this object into a global scope in Python, and use a previously wrapped Python interface to this global object in python.
I used the SWIG_NewPointerObj command to generate the function declarations and implementations needed for the SWIG runtime
However, when using the SWIG_NewPointerObj function, I can't pass the ‘ swig_type_info *type’ parameter

**Comment by ojwb** [comment]
You can get it with `SWIG_TypeQuery(name)` (or `SWIG_MangledTypeQuery(name)` if you have the SWIG-mangled type name already, e.g. `_p_MyClass` for `MyClass *`).

You probably want to read `Modules.html` if you haven't already.

**Comment by mujinjia** [comment]
I didn't find a detailed description of the SWIG_TypeQuery and SWIG_MangledTypeQuery methods in the manual.
I tried to use SWIG_TypeQuery I can get a type and convert a C++ object to a Python object and pass it to Python, but I can't call any of the member methods of this object in my Python code (I've imported the corresponding python library).
As for the call to SWIG_MangledTypeQuery always returning null, do I still need to add the so file compiled from the SWIG code to my C++ project's dynamic linking library?
My current C++ project only brings in the original C++ libraries, and Python and other related environments.
The so files of the Python libraries generated by SWIG are only added to the PYTHONPATH path as Python third-party libraries.

**Comment by mujinjia** [comment]
I added the so file compiled with SWIG code to the DLL of my C++ project and I can't get the type via SWIG_MangledTypeQuery. Even if I include the wrap.cxx code directly.
I noticed the "-DSWIG_TYPE_TABLE" option described in the manual, but even if I use this option the generated cxx code doesn't change anything. I couldn't find any more information about "-DSWIG_TYPE_TABLE"

**Comment by ojwb** [comment]
I've never tried to do this myself so I really can't offer much advice I'm afraid.  I don't think `SWIG_TYPE_TABLE` is useful here though - e.g. CHANGES seems to say it's about sharing type systems between modules:

```
10/21/2004: wuzzeb (John Lenz)
            - If you define SWIG_TYPE_TABLE when compiling a wrapper file,
              the runtime types will be stored in the given type table name.     
              Using this, you can seperate different modules to share their
              own type systems.  -DSWIG_TYPE_TABLE=Mytable
```

The mailing list is a better place to ask questions about using SWIG - more people read that than monitor the bug tracker so you're more likely to find someone who's tried this before.
