### ISSUE TITLE
create C bindings from C++ code

### ISSUE THREAD

**Issue by gogo2464** [swig/swig#2733]
I would like to use my c++ library in C using a c logic.

I could create a c program with python bindings but it would break the OOP logic.

I could create a c++ library usable in C as well as usable in python with swig bindings but then it remains the importation issue.

How could I use my C++ library code in a C program in a way that does not break the C syntax philosophy please?

Then my plan is to:

generate a .h wrapper with the -C option
```C
// C++Wrapper.h
#ifdef __cplusplus
extern "C" {
#endif

// Function declarations for C interface
void* createCppClass();
void cppMethodWrapper(void* cppClass);
void destroyCppClass(void* cppClass);

#ifdef __cplusplus
}
#endif
```

and to generate a .c wrapper as well such as:

```C
// C++Wrapper.cpp
#include "CppLibrary.hpp"

extern "C" {

void* createCppClass() {
    return new CppClass();
}

void cppMethodWrapper(void* cppClass) {
    static_cast<CppClass*>(cppClass)->cppMethod();
}

void destroyCppClass(void* cppClass) {
    delete static_cast<CppClass*>(cppClass);
}

}
```

what do you think of this idea?

Best regards.

**Comment by vadz** [comment]
This is what #2086 is about.

**Comment by gogo2464** [comment]
great! When should it be ready please? I can not wait!

**Comment by vadz** [comment]
You should be able to use it in the current state. Of course, there are a lot of things which don't work and conflicts would need to be resolved if you merge it into the current master, but nothing prevents you from just using that branch.

**Comment by gogo2464** [comment]
My cicd is currently running swig from chocolatey. I will need to compile from source. then if you could merge it would be really better.


Thank you a lot of anyway.

**Comment by gogo2464** [comment]
@vadz for my project I would like to install your swig branch from chocolatey. Could you package it please?

**Comment by vadz** [comment]
No, sorry, but please feel free doing it if you'd like to.
