### ISSUE TITLE
fix dll issue from chocolatey

### ISSUE THREAD

**Issue by gogo2464** [swig/swig#2739]
Hello,

I got the error:

```
import _process
ImportError: DLL load failed while importing _process: module not found
```

when using swig on cpp program.

According to this post:
https://stackoverflow.com/a/69887857/12671313

I am now sure I am not the origin of the error.

Could you fix it please?

The full discussion is here:
https://github.com/swig/swig/discussions/2735

**Comment by ojwb** [comment]
> Could you fix it please?

I suspect not - this sounds more like a usage problem but I don't really do windows so I can't usefully help.

Closing as this doesn't seem to be a SWIG bug and having both an issue and a discussion open for the same thing isn't useful.  Not many people ready issues or discussions - if you want to find a wider audience, try the mailing list.
