### ISSUE TITLE
Local jobject references are not released instantly on finished

### ISSUE THREAD

**Issue by zbqf109** [swig/swig#274]
It seems that java will only hold at most 512 local references at a single time. This is ok for most use. But if in C/C++ code there is a loop in which a JNI method is invoked, it easily runs overflow. Unfortunately I met this problem today. The auto generated code was like this below:
```
void SwigDirector_CBroipSipCallback::onLogging(char const *log) {
  JNIEnvWrapper swigjnienv(this) ;
  JNIEnv * jenv = swigjnienv.getJNIEnv() ;
  jobject swigjobj = (jobject) NULL ;
  jstring jlog = 0 ;
  
  swigjobj = swig_get_self(jenv);
  if (swigjobj && jenv->IsSameObject(swigjobj, NULL) == JNI_FALSE) {
    jlog = 0; 
    if (log) {
      jlog = jenv->NewStringUTF((const char *)log);
      if (!jlog) return ;
    }    
    jenv->CallStaticVoidMethod(Swig::jclass_broipJNI, Swig::director_methids[2], swigjobj, jlog);
    jthrowable swigerror = jenv->ExceptionOccurred();
    if (swigerror) {
      jenv->ExceptionClear();
      throw Swig::DirectorException(jenv, swigerror);
    }    
    
  } else {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null upcall object in CBroipSipCallback::onLogging ");
  }
  if (swigjobj) jenv->DeleteLocalRef(swigjobj);
}
```
In my C code, a function contains a loop and the onLogging method was called continuously. When I ran my Java app, I got an exception like this: JNI ERROR (app bug): local reference table overflow (max=512). So I add a line in the auto generated code:
```
jenv->DeleteLocalRef(jlog);
```
simply after the swigerror branch and my app ran properly. Sure there are many ways to avoid this problem, but I thought it is an issue of swig.

**Comment by tobilau** [comment]
Will this issue be fixed in the near future?

**Comment by wsfulton** [comment]
It was fixed in the distant past in f38f6371a34a153531a7f8d5351de15621ed0387. I suggest you upgrade.

**Comment by tobilau** [comment]
@wsfulton Thanks for the reply! This is indeed fixed for the std_string callbacks, but should be also included for the std_wstring types

**Comment by tobilau** [comment]
Please see my pull request https://github.com/swig/swig/pull/821

**Comment by wsfulton** [comment]
I see this has extended the fix to wstring too, thanks.
