### ISSUE TITLE
Improve Tcl9 support

### ISSUE THREAD

**Issue by PaulObermeier** [swig/swig#2750]
The attached patch (using SWIG 4.2.0) adds improved support for Tcl9.
Changes done are as explained in chapters **Init stubs** and **64-bit data support** at the Tcl9 porting site:
https://core.tcl-lang.org/tcl/wiki?name=Migrating%20C%20extensions%20to%20Tcl%209

[Tcl9.patch](https://github.com/swig/swig/files/13854942/Tcl9.patch)

**Comment by ojwb** [comment]
@PaulObermeier Please can you open a PR for your patch?

**Comment by PaulObermeier** [comment]
PR done.

**Comment by ojwb** [comment]
Thanks - let's close this and keep discussion in the PR.
