### ISSUE TITLE
[CSharp] LNK2001, very strange problem

### ISSUE THREAD

**Issue by jcyuan** [swig/swig#2753]
The problem:
gfxCSHARP_wrap.cxx.obj : error LNK2001: "public: static class bn::math::Vec3 const bn::math::Vec3::ZERO" (**?ZERO@Vec3@math@bn@@2V123@B**)

c++ h:
```c++
class DLL_FLAG Vec3 {
public:
 /** equals to Vec3(0,0,0) */
    static const Vec3 ZERO;
    /** equals to Vec3(1,1,1) */
    static const Vec3 ONE;
    /** equals to Vec3(1,0,0) */
    static const Vec3 UNIT_X;
    /** equals to Vec3(0,1,0) */
    static const Vec3 UNIT_Y;
    /** equals to Vec3(0,0,1) */
    static const Vec3 UNIT_Z;
    /** equals to Vec3(0,0,-1) */
    static const Vec3 FORWARD;
}
```

these static fields are implemented in cpp and in the output lib/dll, i can use `dumpbin` to find the symbol manually: **?ZERO@Vec3@math@bn@@2V123@B**
![image](https://github.com/swig/swig/assets/850854/70c85143-f05f-405d-8db2-cb478d718574)

so why? really have no idea...

**Comment by jcyuan** [comment]
why i feel it's something related to compiler?  because other errors are strange too:

```c++
struct ALIGNAS(8) BufferInfo {
    BufferUsage usage{BufferUsageBit::NONE};
    MemoryUsage memUsage{MemoryUsageBit::NONE};
    uint32_t size{0};
    uint32_t stride{1}; // in bytes
    BufferFlags flags{BufferFlagBit::NONE};
    uint32_t _padding{0};
};
```

and i got this error:
E:\hs\cmm.h(1008) : Error: Syntax error in input(1).

...   line 1008 is ***struct alignas(8) BufferInfo {***
so `alignas(8)` makes it confused? 😅

**Comment by ojwb** [comment]
Are you linking in code to actually define these?  E.g. an object compiled from a `.cpp` file with something like:

```
const Vec3 Vec3::ZERO(0,0,0);
// And similarly for all the others.
```

**Comment by jcyuan** [comment]
> Are you linking in code to actually define these? E.g. an object compiled from a `.cpp` file with something like:
> 
> ```
> const Vec3 Vec3::ZERO(0,0,0);
> // And similarly for all the others.
> ```

yeah, here is the code:

```c++
// h
class DLL_FLAG Vec3 {
public:
    /** equals to Vec3(0,0,0) */
    static const Vec3 ZERO;
    /** equals to Vec3(1,1,1) */
    static const Vec3 ONE;
    /** equals to Vec3(1,0,0) */
    static const Vec3 UNIT_X;
    /** equals to Vec3(0,1,0) */
    static const Vec3 UNIT_Y;
    /** equals to Vec3(0,0,1) */
    static const Vec3 UNIT_Z;
    /** equals to Vec3(0,0,-1) */
    static const Vec3 FORWARD;
}

// cpp

const Vec3 Vec3::ZERO(0.0F, 0.0F, 0.0F);
const Vec3 Vec3::ONE(1.0F, 1.0F, 1.0F);
const Vec3 Vec3::UNIT_X(1.0F, 0.0F, 0.0F);
const Vec3 Vec3::UNIT_Y(0.0F, 1.0F, 0.0F);
const Vec3 Vec3::UNIT_Z(0.0F, 0.0F, 1.0F);
const Vec3 Vec3::FORWARD(0.0F, 0.0F, -1.0F);

```

btw, may i ask for another question about a basic usage on class pointer please?
mmm i think better create in another one.
