### ISSUE TITLE
Is there a simpler way to deal with those class/method who needs the pointer proxy class?

### ISSUE THREAD

**Issue by jcyuan** [swig/swig#2756]
let me use an example to explain what i mean:

```c++
struct ObjInfo {}

public class ObjImpl {
public:
       ObjImpl();
       ~ObjImpl();
      void initialize(const ObjInfo &info);
}
public Factory {
public:
        ObjImpl *createObject(const ObjInfo &info);
}
```

so i'll have 
`class SWIGTYPE_p_ObjInfo` for `ObjInfo &` or `ObjInfo *`
`class SWIGTYPE_p_ObjImpl` for `ObjImpl &` or `ObjImpl *`
in my c# side, and then, i will have to create an object by the `Factory` like this way, whick makes me feel painful..... 
```c#
using var info = new ObjInfo();    // using = auto release
var winSize = window.ViewSize;
info.Width = (uint)winSize.Width;
info.Height = (uint)winSize.Height;

var pObj = _factory.CreateObject(new SWIGTYPE_p_ObjInfo(ObjInfo.getCPtr(info).Handle, false));
var obj = new ObjImpl(SWIGTYPE_p_ObjImpl.getCPtr(pObj).Handle, true);
_objList.Add(obj);

```

if only a few methods like this i can actually accept it, but too many methods (all type pointer & type references) needs to call like this way it makes me head scratching.
my question is that is there a way to simply this?
thanks a lot!

**Comment by jcyuan** [comment]
now i need to alwasy care about the object lifetime.... 😰

for example:

```c#
using var info = new ObjInfo();    // using = auto release
var winSize = window.ViewSize;
info.Width = (uint)winSize.Width;
info.Height = (uint)winSize.Height;

CreateInAnotherMethod(info);

public void CreateInAnotherMethod(info) {
   swigMethodCreate(info);
}
```

if in the C++ side the code holds this info, it will crash later... so tired....

**Comment by wsfulton** [comment]
You are not passing SWIG the full type information if you have a type wrapper class such as `SWIGTYPE_p_ObjInfo`. Get SWIG to parse the `ObjInfo` struct, then you will get a proxy class called `ObjInfo` to use.
