### ISSUE TITLE
AttributeError: module 'example' has no attribute 'mynamespace'

### ISSUE THREAD

**Issue by nglih** [swig/swig#2759]
---hpp and cpp---
all function with a namespace: "mynamespace"

---example.i---
%module example
%{
#include "example.hpp"
%}
%include "example.hpp"
%{
namespace mynamespace {}
using namespace mynamespace;
%}

---test.py---
import example
c = example.mynamespace.Circle(10)
AttributeError: module 'example' has no attribute 'mynamespace'

**Comment by nglih** [comment]
Who can help me solve this problem？ thank you very much！

**Comment by ojwb** [comment]
You don't seem to have put anything in `mynamespace`, but anyway SWIG flattens namespaces by default so you're seeing the expected and documented behaviour:

https://www.swig.org/Doc4.2/SWIGPlus.html#SWIGPlus_namespaces

Some target languages support wrapping namespaces via the `nspace` feature but this isn't currently implemented for Python.  We already have #2289 as a feature request for that, so closing.
