### ISSUE TITLE
Generated Lua bridge file throws "C4100: unreferenced formal parameter" MSBuild Warning for release build

### ISSUE THREAD

**Issue by ribhukhaneja** [swig/swig#2760]
**To reproduce the issue:**
Compile the Lua bridge file generated by SWIG using a release build in Microsoft Visual C++ (MSVC) with C++14.

**Result:**
Upon compilation, MSBuild generates warning C4100 indicating an unreferenced formal parameter 'first_arg' in both `SWIG_Lua_class_do_get_item()` and `SWIG_Lua_class_do_get()`.

**Comment by ojwb** [comment]
It's marked as `int SWIGUNUSED first_arg` but it looks like someone needs to contribute an implementation of `SWIGUNUSED` for MSVC as we don't have one currently, see `Lib/swiglabels.swg`:

```
/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)                                            
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif
```

A simple workaround is to just disable this warning when compiling SWIG-generated wrapper files.
