### ISSUE TITLE
swig opencv error

### ISSUE THREAD

**Issue by nglih** [swig/swig#2763]
I have added several functions to the c++ source code of opencv. I need to use swig to package the rewritten library into a python package. cmake build keeps reporting errors. Can you help me find out what the problem is?
All my source files are attached, please unzip and run, and help me solve this error, thank you

[surface_matchig.zip](https://github.com/swig/swig/files/13971289/surface_matchig.zip)

**Comment by ojwb** [comment]
This issue tracker is intended for bugs in SWIG itself, not as a general support forum for helping SWIG users.  Please use the swig-user mailing list (https://www.swig.org/mail.html) for such questions, or perhaps talk to the opencv developers if you haven't already.
