### ISSUE TITLE
std::pair SWIGTYPE_p behavior change in 4.2.0

### ISSUE THREAD

**Issue by sloriot** [swig/swig#2772]
Hi,

With the update from 4.1.0 to 4.2.0, I noticed a regression in our bindings generated by swig (https://github.com/CGAL/cgal-swig-bindings). During the generation of one module we have a compilation error that is complaining about a type that does not exist.

Looking at the generated code, I have:

```
typedef std::pair<Polyhedron_3_Facet_handle_SWIG_wrapper,Polyhedron_3_Facet_handle_SWIG_wrapper>  Facet_pair_SWIG_wrapper; 
typedef SWIG_Polyhedron_3::CGAL_Facet_handle<Polyhedron_3_>  Polyhedron_3_Facet_handle_SWIG_wrapper; 

#define SWIGTYPE_p_std__pairT_Polyhedron_3_Facet_handle_SWIG_wrapper_Polyhedron_3_Facet_handle_SWIG_wrapper_t swig_types[54]

static swig_type_info _swigt__p_std__pairT_Polyhedron_3_Facet_handle_SWIG_wrapper_Polyhedron_3_Facet_handle_SWIG_wrapper_t = {"_p_std__pairT_Polyhedron_3_Facet_handle_SWIG_wrapper_Polyhedron_3_Facet_handle_SWIG_wrapper_t", "Facet_pair_SWIG_wrapper *|std::pair< Polyhedron_3_Facet_handle_SWIG_wrapper,Polyhedron_3_Facet_handle_SWIG_wrapper > *|std::pair< SWIG_Polyhedron_3::CGAL_Facet_handle< Polyhedron_3_ >,SWIG_Polyhedron_3::CGAL_Facet_handle< Polyhedron_3_ > > *", 0, 0, (void*)0, 0};
```

But the type used later in the function is 

```
SWIGTYPE_p_std__pairT_SWIG_Polyhedron_3__CGAL_Facet_handleT_Polyhedron_3__t_SWIG_Polyhedron_3__CGAL_Facet_handleT_Polyhedron_3__t_t
```

Basically, `swig_types[54]` with SWIG 4.1.0 corresponds to the type *was not declared in this scope* while compiling. I tried replacing std::pair with an locally defined pair type and all seems to be working correctly. So I was wondering if there is anything specific to `std::pair` in 4.2 that could explain that?

I know the report does not contain a minimal example but I can (try to) create one if that could help.

**Comment by sloriot** [comment]
Note that Java is OK, I only have an issue with python.

**Comment by wsfulton** [comment]
A cut down version will be best to diagnose. Otherwise add `-E` to the command line options passed to swig and pipe the resulting preprocessed output to a file. Attach the file here for us to replicate the generated code. But this will still need cutting down in order to debug easily/

One thing you can check for is any relevant `%template` directives, make sure you are using fully resolved types and not typedefs.

**Comment by wsfulton** [comment]
I took at this code base and managed to view the preprocessed output. From what I can make out, this is a cutdown version:
```swig
%{
// EPIC_Kernel, Polyhedron_items_with_id_3, Polyhedron_3 not wrapped and defined elsewhere

// in Polyhedron_3_/typedefs.h, but not included
typedef CGAL::Polyhedron_3<EPIC_Kernel, CGAL::Polyhedron_items_with_id_3>     Polyhedron_3_;
%}

%inline %{
namespace SWIG_Polyhedron_3
{
  template <class Polyhedron_base>
    class CGAL_Halfedge_handle{
    // ...
    };
}
%}

%inline %{ typedef SWIG_Polyhedron_3::CGAL_Halfedge_handle<Polyhedron_3_>  Polyhedron_3_Halfedge_handle_SWIG_wrapper; %}

%template (Polyhedron_3_Halfedge_handle) SWIG_Polyhedron_3::CGAL_Halfedge_handle<Polyhedron_3_>;

%include <std_pair.i>

%template (Halfedge_pair) std::pair<Polyhedron_3_Halfedge_handle_SWIG_wrapper,Polyhedron_3_Halfedge_handle_SWIG_wrapper>;
```

[CGAL_Polygon_mesh_processing.i#L134](https://github.com/CGAL/cgal-swig-bindings/blob/7d971288d84d12e40fa9eb96407b7b37470905a7/SWIG_CGAL/Polygon_mesh_processing/CGAL_Polygon_mesh_processing.i#L134)
hard codes to use a SWIGTYPE_p descriptor and this has changed in the new version and may change in any future version. These are internal mangled names and should really be obtained by using `$descriptor`. So I recommend changing this line replacing:
```
SWIGTYPE_p_std__pairT_SWIG_Polyhedron_3__CGAL_Halfedge_handleT_Polyhedron_3__t_SWIG_Polyhedron_3__CGAL_Halfedge_handleT_Polyhedron_3__t_t
```
with
```
$descriptor(std::pair<SWIG_Polyhedron_3::CGAL_Halfedge_handle<Polyhedron_3_>,SWIG_Polyhedron_3::CGAL_Halfedge_handle<Polyhedron_3_>> *)
```

Alternatively, but it will be brittle going forwards, you can obtain the same descriptor in both versions by replacing the last %template instantiation with:
```
%template (Halfedge_pair) std::pair<SWIG_Polyhedron_3::CGAL_Halfedge_handle<Polyhedron_3_>,SWIG_Polyhedron_3::CGAL_Halfedge_handle<Polyhedron_3_>>;
```

As SWIG is not parsing the full type information, these descriptors are more liable to changing from one version to the next.

**Comment by wsfulton** [comment]
Same issue as #2793.

**Comment by sloriot** [comment]
I did not know this function. It works now. Thanks!
