### ISSUE TITLE
Syntax error in input with constructor call.

### ISSUE THREAD

**Issue by diegosogari** [swig/swig#2773]
```swig
// test.i
%module test;
%include "test.hpp"
```
```cpp
// test.hpp
const int a(0);
```
```sh
# windows
g++ test.hpp
clang++ test.hpp
swig -python -c++ test.i
test.hpp(2) : Error: Syntax error in input(1).

swig -version

SWIG Version 4.1.1

Compiled with i686-w64-mingw32-g++ [i686-w64-mingw32]

Configured options: +pcre

Please see https://www.swig.org for reporting bugs and further information
```
```sh
# linux
g++ test.hpp
clang++ test.hpp
swig -python -c++ test.i
src/test.hpp:2: Error: Syntax error in input(1).

swig -version

SWIG Version 4.0.2

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
```

**Comment by ojwb** [comment]
I'm afraid this is a known limitation of the parser.  We already have #869 open for it, so closing this as a duplicate.

If you're able to modify the declarations being wrapped, SWIG handles `const int a = 0;` and `const int a{0};`.

If you're not able to modify them, you might be able to hack around the problem by defining a macro for SWIG in your interface file:

```
#define a(X) a{X}
```

That should work unless there are other instances of `a(X)` which can't be validly changed to `a{X}` - e.g. a function prototype such as `int a(double x);`.

**Comment by diegosogari** [comment]
I see. That's okay, I can patch the code being wrapped. Thanks.
