### ISSUE TITLE
Build of sphinxbase failed with SWIG 4.2.0

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#2777]
The build of `sphinxbase-5-0.17.prealpha` is failing against SWIG 4.2.0 in Fedora rawhide/40.

The issue is similar to https://github.com/swig/swig/issues/2747

```
sphinxbase_wrap.c: In function '_wrap_NGramModel_add_class':
sphinxbase_wrap.c:5823:19: error: implicit declaration of function 'SWIG_Python_str_AsChar'; did you mean 'SWIG_Python_str_FromChar'? [-Wimplicit-function-declaration]
 5823 |         arg5[i] = SWIG_Python_str_AsChar(o);
      |                   ^~~~~~~~~~~~~~~~~~~~~~
      |                   SWIG_Python_str_FromChar
sphinxbase_wrap.c:5823:17: error: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
 5823 |         arg5[i] = SWIG_Python_str_AsChar(o);
      |                 ^
sphinxbase_wrap.c:5842:9: error: implicit declaration of function 'SWIG_Python_str_DelForPy3'; did you mean 'SWIG_Python_str_FromFormat'? [-Wimplicit-function-declaration]
 5842 |         SWIG_Python_str_DelForPy3(arg5[i]);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
      |         SWIG_Python_str_FromFormat
sphinxbase_wrap.c: In function '_wrap_NGramModel_prob':
sphinxbase_wrap.c:5889:17: error: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
 5889 |         arg3[i] = SWIG_Python_str_AsChar(o);
      |                 ^
make[2]: Leaving directory '/builddir/build/BUILD/sphinxbase-5prealpha/swig/python'
```

Complete build log is [here](https://download.copr.fedorainfracloud.org/results/jplesnik/swig-rebuild/fedora-rawhide-x86_64/06943526-sphinxbase/builder-live.log.gz). Other information about the build can be found [here](https://copr.fedorainfracloud.org/coprs/jplesnik/swig-rebuild/build/6943526/).

**Comment by ojwb** [comment]
This looks like further fallout from @wsfulton's changes.

**Comment by wsfulton** [comment]
I've attached a patch for sphinxbase, I'm not entirely sure where their code is maintained. I've tested this using a simple test example I created rather than in the sphinxbase build. Could you add this as a patch to copr, it ought to fix the build on copr. It also fixes a potential memory leak on error, such as when one of the list items is not a string.

[sphinxbase-swig-4.2.0-array-typemap-fix.diff.txt](https://github.com/swig/swig/files/14044530/sphinxbase-swig-4.2.0-array-typemap-fix.diff.txt)

**Comment by jplesnik** [comment]
@wsfulton I used your fix and the build in copr passed. I'll apply the fix in Fedora. 

Thank you
