### ISSUE TITLE
Build of pygraphviz failed with SWIG 4.2.0

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#2778]
The build of `python-pygraphviz-1.11` is failing against SWIG 4.2.0 in Fedora rawhide/40.

```
pygraphviz/graphviz_wrap.c: In function ‘SWIG_AsCharPtrAndSize’:
pygraphviz/graphviz_wrap.c:3255:17: error: implicit declaration of function ‘SWIG_Python_str_AsChar’; did you mean ‘SWIG_Python_str_FromChar’? [-Wimplicit-function-declaration]
 3255 |         *cptr = SWIG_Python_str_AsChar(obj);
      |                 ^~~~~~~~~~~~~~~~~~~~~~
      |                 SWIG_Python_str_FromChar
pygraphviz/graphviz_wrap.c:3255:15: error: assignment to ‘char *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 3255 |         *cptr = SWIG_Python_str_AsChar(obj);
      |               ^
error: command '/usr/bin/gcc' failed with exit code 1
```

Complete build log is [here](https://download.copr.fedorainfracloud.org/results/jplesnik/swig-rebuild/fedora-rawhide-x86_64/06943525-python-pygraphviz/builder-live.log.gz). Other information about the build can be found [here](https://copr.fedorainfracloud.org/coprs/jplesnik/swig-rebuild/build/6943525/).

**Comment by ojwb** [comment]
This looks like further fallout from @wsfulton's changes.

**Comment by wsfulton** [comment]
pygraphviz has an ancient outdated copy of pystrings.swg as an override to SWIG's version. https://github.com/pygraphviz/pygraphviz/pull/508 should fix this and restore it to use the SWIG maintained version which of course doesn't have the SWIG_Python_str_AsChar problem.

**Comment by jplesnik** [comment]
@wsfulton The fix works for Fedora. Thank you
