### ISSUE TITLE
AccessViolationException on Dispose

### ISSUE THREAD

**Issue by nref** [swig/swig#2779]
This is not a bug report in the sense that "I think this is SWIG's fault" but more that "I have no idea what's going on and hope to learn"

I have a CPP class hierarchy like this:

```cpp
class Base : public QObject { ... }; // QObject from QT
class Derived : public Base { ... };
```

When I create a C# wrapper of `Derived` with SWIG, I get a .NET `AccessViolationException` every time `Derived`'s `Dispose` method runs:

```csharp
using (var derived = new Derived())
{
}; // Crash when scope closes
```

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at TestCpp.TESTCPPPINVOKE.delete_QObject(System.Runtime.InteropServices.HandleRef)
--------------------------------
   at TestCpp.QObject.Dispose(Boolean)
   at TestCpp.Base.Dispose(Boolean)
   at TestCpp.Derived.Dispose(Boolean)
   at TestCpp.QObject.Dispose()
   at Program.<Main>$(System.String[])
```

My best guess is there is a double delete, because this sequence of deletes will happen:

- `Derived.cs` calls `delete_Derived(swigCPtr);`
- `Base.cs` calls `delete_Base(swigCPtr);`
- `QObject.cs` calls `delete_QObject(swigCPtr);`

but these three `swigCPtr` pointers point to the same C++ object.

If I remove the inheritance of `Base` from `QObject` in the C++, the crash goes away.

Update: if I comment out the second line below from my swig interface file, the crash goes away:

```
// testcpp.i
...
%include "std_shared_ptr.i"
%shared_ptr(TestCpp::Derived); // Causes crash
```

Any assistance will be appreciated.

**Comment by nref** [comment]
I have created a minimal repro of the issue: https://github.com/nref/SwigQObjectCrashRepro/

**Comment by ojwb** [comment]
Not my area of expertise, but are you sure delete_X actually gets called for each derived class?

Each `Dispose()` should check a flag member of the base class (called `swigCMemOwnDerived` or `swigCMemOwn` - not sure why the variation) which should be set to `false` after the first delete_X is called and prevent further calls.

If that's not enough to help you solve it, the swig-user mailing list is likely a better place to ask questions.

**Comment by nref** [comment]
Thanks for the mailing list tip!

**Comment by wsfulton** [comment]
This looks like a problem in the implementation of the user's code or QT code, not SWIG generated code, so closing. There are loads of runtime examples we test in the test-suite using the type of inheritance hierarchy shown and these work just fine. I suggest regular C++ debugging techniques are used to diagnose the issue.

**Comment by nref** [comment]
This is overall a pretty useless comment. I left it open since I still have not resolved the issue.

**Comment by nref** [comment]
Thanks for an excellent library though. It's been useful for me as a C# dev to make use of C++ libraries.

**Comment by wsfulton** [comment]
SWIG is a tool to help C++ developers wrap C++ code into other target languages. As such, the expectation for SWIG users is to know basic C++ and debugging techniques and if these are not your area of expertise, it would be best to seek help from C++ beginner support forums. The SWIG support site is for SWIG problems and it seems to me that your problem is specific to your C++ code, so you'd be better off formulating your problem as a pure C++ problem and seeking appropriate C++ help. Once you have analysed the issue with a C++ debugger and found it to be a SWIG marshalling problem, then please detail exactly where the memory related issues are and re-open this ticket.

**Comment by wsfulton** [comment]
Oh and having a quick look at your .i file, have you looked at the warnings that SWIG generates? Can you post those and what you did to address them?

**Comment by nref** [comment]
Thanks for the clear articulation of who SWIG is for. I wasn't very clear, but I am quite capable in C++ (enough to use it professionally for 5 years) but these says more so in C#.

I appreciate your time and at this point I would not want to use more of it on this minor issue. We'll cross paths again as a number of my projects use SWIG.
