### ISSUE TITLE
[feature request] is it possible to custom the prefix of the exported symbols?

### ISSUE THREAD

**Issue by jcyuan** [swig/swig#2780]
https://github.com/swig/swig/blob/6c496f5b5b9ee585e4d7376835d9acb41e55ea33/Source/Modules/csharp.cxx#L432-L437

i mean, is it possible to custom the 'CSharp_' prefix for:

![image](https://github.com/swig/swig/assets/850854/28691153-6412-4606-b76b-16d2c5c92a2c)

thanks

**Comment by ojwb** [comment]
It's not currently possible.

It would be useful to explain why you want to be able to customise this.

**Comment by ojwb** [comment]
@jcyuan Why do you want to be able to customise this?

**Comment by jcyuan** [comment]
> @jcyuan Why do you want to be able to customise this?

ah, sorry for late reply, that's just a personal customzing requirement... so, yeah, if it couldn't be a feature request, just feel free to close this, and thanks~    :)
