### ISSUE TITLE
Fix Java static inspection warnings on synchronization

### ISSUE THREAD

**Issue by ekeithkw** [swig/swig#279]
SWIG 3.0.2 generates a Java proxy class with a synchronized delete() method per the finalizer thread issue.  However, synchronizing just that one method results in a couple of static code inspection warnings:

Field 'swigCPtr' is accessed in both synchronized and unsynchronized contexts
Non-private field 'swigCMemOwn' accessed in synchronized context

I'm not sure why 'swigCMemOwn' is not private.  It's set by the constructor and thereafter managed internally.  My first suggestion is to make this private.

To fix the concurrency warnings and make the proxy class thread safe, my suggestion is to add an atomic boolean that tracks if the object has been deleted or not, and to make the 'swigCPtr' and 'swigCMemOwn' members final.  The 'deleted' boolean can be either an AtomicBoolean object or a synchronized boolean member.  Since only this boolean will need synchronization, I would pick the AtomicBoolean.  For example, for the C structure:
```c
typedef struct _CharInfo {
    xCharInfo   metrics;    /* info preformatted for Queries */
    char       *bits;   /* pointer to glyph image */
}           CharInfoRec;
```
..the generated proxy class would be:
```java
import java.util.concurrent.atomic.AtomicBoolean;

public class CharInfoRec {
  private final long swigCPtr;
  private final boolean swigCMemOwn;
  private final AtomicBoolean deleted = new AtomicBoolean(false);

  protected CharInfoRec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CharInfoRec obj) {
    if (obj == null) {
      return 0; 
    } else {
      obj.assertNotDeleted();
      return obj.swigCPtr; 
    }
  }

  protected synchronized void assertNotDeleted() {
    assert !deleted.get();
  }

  protected void finalize() throws Throwable {
    super.finalize();
    delete();
  }

  public void delete() {
    if (!deleted.getAndSet(true)) {
      if (swigCMemOwn) {
        RXFontProxyJNI.delete_CharInfoRec(swigCPtr);
      }
    }
  }

  public void setMetrics(xCharInfo value) {
    assertNotDeleted();
    RXFontProxyJNI.CharInfoRec_metrics_set(swigCPtr, this, xCharInfo.getCPtr(value), value);
  }

  public xCharInfo getMetrics() {
    assertNotDeleted();
    long cPtr = RXFontProxyJNI.CharInfoRec_metrics_get(swigCPtr, this);
    return (cPtr == 0) ? null : new xCharInfo(cPtr, false);
  }

  public void setBits(String value) {
    assertNotDeleted();
    RXFontProxyJNI.CharInfoRec_bits_set(swigCPtr, this, value);
  }

  public String getBits() {
    assertNotDeleted();
    return RXFontProxyJNI.CharInfoRec_bits_get(swigCPtr, this);
  }

  public CharInfoRec() {
    this(RXFontProxyJNI.new_CharInfoRec(), true);
  }

}
```
This code is thread safe due to immutability of the members, and provides protection against using a manually deleted object.  The assertNotDeleted() method could alternatively throw a RuntimeException.  (The above implementation is a no-op unless Java asserts are enabled.)

**Comment by wsfulton** [comment]
The swigCMemOwn variable can be used by derived classes, although your struct doesn't have any structs deriving from it in this case, the code needs to work when wrapping C++ inheritance.

Your can generate the code you suggest using typemaps. SWIG is designed to be flexible like this. Your suggestions for the default/general use case will need some rethinking or further justification though. 

- You've removed `transient`, this is a security flaw.
- All methods call assertNotDeleted which makes all methods blocking and is thus an unnecessary performance hit. BTW, users should make targeted methods synchronized if a thread-safety layer needs adding on top of the C++ layer.
- Currently, delete is synchronized ensuring the underlying object could never be deleted twice. That is the main goal of the default generated code. I'm not sure what the real life use case is for your suggested changes. I think you are trying to ensure defined behaviour if someone calls delete and is using the class from other threads at the same time. If this is the case, this is daft and the use of the object in a multi-threaded environment and manual control of the life-time of the object requires a rethink.
- The assertNotDeleted is subject to a race condition as once it has finished executing and before a line following it is executed, another thread might come along and delete the swigCPtr. You'd need to make all methods synchronized to fix this. But as mentioned earlier, I think there is something fundamentally flawed to a thread design if one needs this class to work like this.
- If you don't call delete(), you should find the class thread-safe for use in multiple threads (if the underlying C++ methods are thread-safe). Plus the garbage collector will not finalize the object until all threads have finished using the object. Note that `this` is passed to the JNI layer specifically to prevent GC until after the JNI method has completed. If delete being public is the main problem, then make it non-public or remove it and move the body of the code into the finalizer.

**Comment by ojwb** [comment]
@wsfulton So in summary if I follow it seems some static analysis tool complained about the code SWIG generates but those complaints aren't actually problems in practice, and the suggested changes to make the tool happy actually make things worse not better.

Is there something we can actually address here, or should this ticket be closed?

**Comment by wsfulton** [comment]
Yes, no response to my comments since 2017, so probably not worth keeping open. Closing.
