### ISSUE TITLE
Can not override typemap of std::shared_ptr

### ISSUE THREAD

**Issue by emmenlau** [swig/swig#2792]
This issue has been split out of https://github.com/swig/swig/issues/2788

I'm experiencing something that looks to me like a bug in SWIG. When I try to override a typemap for std::shared_ptr, SWIG does not resolve the type correctly any more. So without any override, I can just define and use a `std::shared_ptr<BaseObject>` successfully, no problems. But when I try to override one of the typemaps of `std::shared_ptr`, then SWIG will suddenly create a new type definition `SWIGTYPE_std__shared_ptrT_BaseObject_t.cs` that seems like an unresolved `std::shared_ptr`.

Here is a slightly simplified example of **what works**:
```
%shared_ptr(BaseObject)

%{
#include "BaseObject.hh"
%}

%include "BaseObject.hh"
```

Then when I try to override a typemap, it **fails**:
```
%typemap(csout, excode=SWIGEXCODE) std::shared_ptr<BaseObject> {
  // some code here...
}

%shared_ptr(BaseObject)

%{
#include "BaseObject.hh"
%}

%include "BaseObject.hh"
```

After adding the typemap override, SWIG will generate `SWIGTYPE_std__shared_ptrT_BaseObject_t.cs` and try to use it.
I could not get this to work, independently where I put this typemap, before or after including the header of `BaseObject`, and/or before defining `BaseObject` as a `shared_ptr`.

Is there some way how typemaps of `std::shared_ptr` can be changed?

**Comment by wsfulton** [comment]
```swig
%typemap(csout, excode=SWIGEXCODE) std::shared_ptr<BaseObject> {
  // some code here...
}

%shared_ptr(bda::BaseObject)
```

Is BaseObject in the bda namespace or not? You need to be consistent here.

**Comment by emmenlau** [comment]
Thanks @wsfulton , sorry for the mistake, I fixed the examples. In my case, BaseObject is consistently in the bda namespace, but in the example I have now removed all namespaces, since I assume they are not required to reproduce the problem.

**Comment by wsfulton** [comment]
Adjust your code as shown below. 

```swig
%module example

%include <std_shared_ptr.i>

%shared_ptr(BaseObject)

// Override typemap provided by %shared_ptr
%typemap(csout, excode=SWIGEXCODE) std::shared_ptr<BaseObject> {
  // some code here...
}

%{
#include <memory>
#include "BaseObject.hh"
%}

%include "BaseObject.hh"

%inline %{
std::shared_ptr<BaseObject> make() {
  return std::shared_ptr<BaseObject>();
}
%}
```

Checkout the preprocessed output using `swig -E`. You'll see that your desired typemap now overrides the collection of typemaps provided by `%shared_ptr` instead of the other way round. Also have a good look at the [Typemaps](https://swig.org/Doc4.2/Typemaps.html) documentation and the debugging options.
