### ISSUE TITLE
[Python][Swig 4.2][Ubuntu 24.04] - Problem when installing PyKCS11

### ISSUE THREAD

**Issue by SixK** [swig/swig#2793]
Hi, 

System: Noble (Ubuntu 24.04)
Swig version: 4.2.0
PyKCS11 version : 1.5.13

Got a problem when installing PyKCS11 library on Noble (Ubuntu 24.04)
Installation finish with the following error (undefined variable: SWIGTYPE_p_std__vectorT_unsigned_char_std__allocatorT_unsigned_char_t_t):
```
src/pykcs11_wrap.cpp:17129:60: error: ‘SWIGTYPE_p_std__vectorT_unsigned_char_std__allocatorT_unsigned_char_t_t’ was not declared in this scope
  17129 |     int res = SWIG_ConvertPtr(swig_obj[1], (void **)&vect, SWIGTYPE_p_std__vectorT_unsigned_char_std__allocatorT_unsigned_char_t_t, 0);
        |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Corresponding error seem's to be introduced by the following file near line 284:
https://github.com/LudovicRousseau/PyKCS11/blob/master/src/pykcs11.i

If compairing generated pykcs11_wrap.cpp from ubuntu 22.04 and 24.04, I see the following difference:
Ubuntu 22.04 --> src/pykcs11_wrap.cpp:#define SWIGTYPE_p_std__vectorT_unsigned_char_std__allocatorT_unsigned_char_t_t swig_types[29]
Ubuntu 24.04 --> src/pykcs11_wrap.cpp:#define SWIGTYPE_p_std__vectorT_unsigned_char_t swig_types[29]

I try to understand if this is a wanted change in swig 4.2.0 or a side effect ?

Here is corresponding issue reported in PyKCS11:
https://github.com/LudovicRousseau/PyKCS11/issues/107

**Comment by wsfulton** [comment]
I see a change has now been made to handle both versions:

https://github.com/LudovicRousseau/PyKCS11/blob/b92b4f20e42ecf2386c3f5dcb31a3128915a1b64/src/pykcs11.i#L291-L295

The correct way to do this is to use descriptor, so replace those lines with:

```swig
descriptor(std::vector<unsigned char>
```
and SWIG will generate the appropriate descriptor for your use in that typemap in all versions of SWIG.

**Comment by wsfulton** [comment]
Same issue as https://github.com/swig/swig/issues/2772
