### ISSUE TITLE
Lacking runme.py in one of the Python examples

### ISSUE THREAD

**Issue by rlaboiss** [swig/swig#2805]
I get this when trying to run the libffi example for Python:

```
make -C  Examples/python/libffi
make: Entering directory '/var/data/rlaboiss/debian/PKGS/swig/swig/Examples/python/libffi'
make -f ../../Makefile SRCDIR='' SRCS='' \
SWIG_LIB_DIR='../../../Lib' SWIGEXE='../../../swig' \
TARGET='example' INTERFACE='example.i' LIBS='-L/usr/local/lib -lffi' python
make[1]: Entering directory '/var/data/rlaboiss/debian/PKGS/swig/swig/Examples/python/libffi'
env SWIG_LIB=../../../Lib  ../../../swig -python  -o example_wrap.c example.i
gcc -c -fpic -I.  example_wrap.c    -I/usr/include/python3.12 -I/usr/include/python3.12
gcc -shared     example_wrap.o  -L/usr/local/lib -lffi -o _example.so
make[1]: Leaving directory '/var/data/rlaboiss/debian/PKGS/swig/swig/Examples/python/libffi'
make -f ../../Makefile SRCDIR='' python_run
make[1]: Entering directory '/var/data/rlaboiss/debian/PKGS/swig/swig/Examples/python/libffi'
make[1]: *** No rule to make target 'runme.py', needed by 'python_run'.  Stop.
make[1]: Leaving directory '/var/data/rlaboiss/debian/PKGS/swig/swig/Examples/python/libffi'
make: *** [Makefile:9: check] Error 2
make: Leaving directory '/var/data/rlaboiss/debian/PKGS/swig/swig/Examples/python/libffi'
```

Could you please provide the file `runme.py` for that example in the next release, please?

**Comment by wsfulton** [comment]
This example was committed over 20 years ago without a runtime test. We don't run it during our testing and so it's as good as ignored.

Why may I ask do you need it? Contributions for a runme file are welcome, but otherwise we probably ought to delete this example.

**Comment by rlaboiss** [comment]
> Why may I ask do you need it? Contributions for a runme file are welcome, but otherwise we probably ought to delete this example.

I do not need it, personally. It just happened that I was making an autopkgtest suite for the swig package for Debian, based on the `Examples/*` directories, and stumbled on that failing example. I thought someone had forgotten to commit the associated `runme.py` file.

If the example is deleted, it is fine for me.

**Comment by ojwb** [comment]
You can run all the examples for languages configure detected tools for with: `make check-examples`

Or just for a specific target language with e.g.: `make check-python-examples`

(Similarly `make check-test-suite` and `make check-python-test-suite` for the test-suite, which is probably more useful for an autopkgtest since the test suite actually checks the results of things and fails if they aren't as expected).

**Comment by ojwb** [comment]
I'm not sure that will catch many problems as the examples don't tend to fail when run so it'd only catch build-time problems (`git grep 'exit\|assert\|raise' Examples/python/*/runme.py` shows they'll probably only fail at runtime if the module itself raises an exception or segfaults).

AIUI the intent of autopkgtests is to catch if an updated package of (say) python breaks any of the packages that depend on it.  For SWIG my experience is that breakage of this sort is often limited to just a few runtime testcases in the testsuite.  Sometimes a new major release series makes changes to the C (or C++) API SWIG uses and that can break more widely (including the examples).  Running the examples isn't entirely useless, but it won't be nearly as effective.

It certainly does take a while to run the full testsuite though.  It's much worse for some target languages than others - Python is one of the more complete in terms of `_runme.py` files, which will tend to make it take longer.

You could perhaps pick out a representative subset of testcases and run those (you can run individual testcases with e.g. `make -C Examples/test-suite/python director_basic.cpptest`).

**Comment by ojwb** [comment]
Also if disk space is actually more of a concern here than run-time you could clean up after each target language which should significantly reduce the peak disk usage - something like:

```
for lang in perl php python ; do
  make "check-$lang-test-suite"
  make -C "Examples/test-suite/$lang" clean
done
```

We could probably even provide a single make target for that upstream.

**Comment by ojwb** [comment]
I had a few minutes spare so I've knocked up a simple `runme.py`.

Currently the wrapped API is a bit quirky - at least with Python 3 some parameters need to be byte strings while others must be Unicode strings!  It was like that when I got here.
