### ISSUE TITLE
[R, Octave] Error in R and Octave container

### ISSUE THREAD

**Issue by erezgeva** [swig/swig#2806]
Hi,

After fixing ruby container #2284. Following python container.

I found the same error in `setslice()`  in `Lib/r/rcontainer.swg`, `Lib/octave/octcontainer.swg`.

We need to add a fix:

After calling `self->erase(sb,se);`
`sb` need to initialise again with:
`      sb = self->begin();`
`      std::advance(sb,ii);`

* As R and Octave container are not tested, there could be more fixes needed.

**Comment by wsfulton** [comment]
Committed in 72803625a120622236e95aa10e74022fdf8b7be6. I just don't have the bandwidth to test this, but these changes are clearly needed given the same fixes were applied to Python and Ruby.
