### ISSUE TITLE
FastProxy not compatible with 'stable-api' python wrapping

### ISSUE THREAD

**Issue by bartoli** [swig/swig#2817]
I tried building my C++ -> python swig module using python limited API, which swig 4.2.0 seems to have added support for.
However, when swig is run with -O, the output c++ source has SWIGPYTHON_FASTPROXY defined.

Then in pyinit.swg fragment, this adds code  for SWIG_PyInstanceMethod_New and SWIG_PyStaticMethod_New, which depend on symbols that are not 'stable'.

I am not sure if they could be written in a stable version, but if not, i guess there could be a #error macro when Py_LIMITED_API is defined to warn that the stable/fastproxy configs are not compatible to make it clearer?

**Comment by ojwb** [comment]
This limitation is explicitly documented in both `CHANGES` and the manual:

```
2023-12-20: vadz, vadimcn, wangito33, wsfulton, clintonstimpson                                                                                                              
            [Python] #1613 #1687 #1727 #2190 #2727 #2428 Add support for the Python stable                                                                                   
            ABI using default Python options. Code is generated that compiles when                                                                                           
            setting the C macro Py_LIMITED_API to 0x03040000 (at C/C++ compile time).                                                                                        
            Note that the -builtin, -fast (used by -O) options are not supported.                                                                                            
```

and:

```
Some options, such as <tt>-builtin</tt>, <tt>-fast</tt> (used by <tt>-O</tt>) do not use the limited API and hence when <tt>Py_LIMITED_API</tt> is defined there will be missing symbols during compilation.
Compatibility of user's custom typemaps is of course dependent on the Python APIs used in the typemaps.
```

**Comment by bartoli** [comment]
Oh, sorry, i mostly looked at some commits in the pull request, and not the final release notes file
