### ISSUE TITLE
testsuite fails with  java-21-openjdk

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#2819]
System JDK is updated from java-17-openjdk to [java-21-openjdk](https://fedoraproject.org/wiki/Changes/Java21) in Fedora 40/Rawhide.

Java tests are failing with this version. [BZ#2266693](https://bugzilla.redhat.com/show_bug.cgi?id=2266693)

Example of errors:
```
checking java testcase li_std_list (with run test)
./BoolList.java:221: error: removeLast() in BoolList cannot implement removeLast() in List
  public void removeLast() {
              ^
  return type void is not compatible with Boolean
  where E is a type-variable:
    E extends Object declared in interface List
./BoolList.java:225: error: removeFirst() in BoolList cannot implement removeFirst() in List
  public void removeFirst() {
              ^
  return type void is not compatible with Boolean
  where E is a type-variable:
    E extends Object declared in interface List
```

Example of warnings:
```
checking java testcase java_director (with run test)
./java_director_runme.java:19: warning: [removal] runFinalization() in System has been deprecated and marked for removal
    System.runFinalization();
          ^
1 warning
```

**Comment by ojwb** [comment]
I already reported these errors in #2767 (though with "22-ea").

The need to replace use of finalizers is #1550.  So far we've just been squashing the gradually escalating warnings, but that's not a long term answer assuming they actually get removed.

**Comment by ojwb** [comment]
I've updated #2767, and pushed a fix to suppress the warnings (the finalizers issue really needs addressing, but meanwhile the noise is unhelpful and we already suppress related ones).

I also fixed use of a different deprecated method in the `doxygen` example (8a19cb77adfec168236e2c63d1a9d1a310f886cc).
