### ISSUE TITLE
Can we get prebuilts for all platforms? 

### ISSUE THREAD

**Issue by jeffwitthuhn** [swig/swig#2832]
I want to use swig on mac win and linux, but I'm finding it really hard and complicated to build/install from github or the 4.2.1 release. Could we get mac-arm/mac-intel/win/linux binaries published somewhere to simply download and execute?

**Comment by jeffwitthuhn** [comment]
Windows has the "just works" executable, but I'd love to have a similar experience for linux/mac.

**Comment by wsfulton** [comment]
It should be easy to build from scratch and https://github.com/swig/swig/wiki/Getting-Started will be of help. 

Failing that conda-forge has prebuilt binaries for all platforms. `conda install swig' once you have installed and configured Conda.
For mac, install brew and then 'brew install swig', see https://formulae.brew.sh/formula/swig#default.

**Comment by ojwb** [comment]
We also struggle to keep up with bug reports and patches as it is - adding additional jobs like creating and maintaining binaries for all the different platforms people might want would mean we'd have less time for that.

Building from source shouldn't be complicated, especially not from a release (since you don't need autotools or bison installed then).  If there are obstacles there, probably better to try to make that experience smoother.

**Comment by jeffwitthuhn** [comment]
Thanks for the reply all! 

For more context, the dependencies make building from source really bad in my environment. For example I can't simply apt install anything which immediately makes the Getting Started page intractable. Maybe there's something that could be done to simplify the build from source, like remove/embed dependencies in the repo? 

The windows executeable is really convenient since I can just copy/paste it and the libs into my repo.  Similarly, I can't brew/conda install in my environment right now, but could use a binary I can "just call" like windows. 

Totally understandable if its too expensive to do anything here though.

**Comment by ojwb** [comment]
I think you need to talk to whoever controls your environment as it seems to be too restrictive for the work they're expecting you to do in it.  I doubt they intend to be pushing you towards downloading and using pre-built binary versions of things as that has more security concerns than using packaged versions from the distro (e.g. if we bundle libpcre we'll inevitably fail to keep it up with security fixes all the time as we're too stretched already, whereas distros have security teams who ensure that security patches get applied in a timely fashion).

You can build also build without libpcre, though regexp features in SWIG won't work then.
