### ISSUE TITLE
SWIG fails to parse `List-initialization` for default function arguments

### ISSUE THREAD

**Issue by mmomtchev** [swig/swig#2842]
This declaration is a valid C++11 declaration that SWIG fails to parse:
```cpp
void Func(int s = int{}) {}
```

```swig
%module Func

void Func(int s = int{}) {}
```
`Func.i:3: Error: Syntax error in input(1).`

**Comment by ojwb** [comment]
We already have #2798 open and I'm almost certain this is the same underlying issue as we just don't seem to have a grammar rule for this, so I've noted your reproducer there and am closing as a duplicate
