### ISSUE TITLE
string_view typemap code is not inserted with block scope

### ISSUE THREAD

**Issue by DylanEtris** [swig/swig#2844]
Swig version: 4.2.0

### Description

Using SWIG to generate a python interface for a function with two `std::string_view` arguments generates invalid code. Specifically, the typemap code is not surrounded by a block, so some variables are declared more than once.

### How to reproduce
Given the file `example.i`:
```i
%include "std_string_view.i"

%module "example"
%{
  #include "string"
%}

void do_something(std::string_view name, std::string_view version) {
  // Do something
}
```

Run the following swig command:

```
swig -c++ -python example.i
```

Which generates the wrapped method:

```cpp
SWIGINTERN PyObject *_wrap_do_something(PyObject *self, PyObject *args) {
  PyObject *resultobj = 0;
  std::string_view arg1 ;
  std::string_view arg2 ;
  PyObject *bytes1 = NULL ;
  PyObject *bytes2 = NULL ;
  PyObject *swig_obj[2] ;
  
  (void)self;
  if (!SWIG_Python_UnpackTuple(args, "do_something", 2, 2, swig_obj)) SWIG_fail;
  
  Py_ssize_t len;
#ifdef SWIG_PYTHON_STRICT_BYTE_CHAR
  const char *p = PyBytes_AsString(swig_obj[0]);
  if (!p) SWIG_fail;
  len = PyBytes_Size(swig_obj[0]);
#else
  const char *p;
  if (PyUnicode_Check(swig_obj[0])) {
    p = SWIG_PyUnicode_AsUTF8AndSize(swig_obj[0], &len, &bytes1);
    if (!p) SWIG_fail;
  } else {
    p = PyBytes_AsString(swig_obj[0]);
    if (!p) SWIG_fail;
    len = PyBytes_Size(swig_obj[0]);
  }
#endif
  arg1 = std::string_view(p, len);
  
  
  Py_ssize_t len;
#ifdef SWIG_PYTHON_STRICT_BYTE_CHAR
  const char *p = PyBytes_AsString(swig_obj[1]);
  if (!p) SWIG_fail;
  len = PyBytes_Size(swig_obj[1]);
#else
  const char *p;
  if (PyUnicode_Check(swig_obj[1])) {
    p = SWIG_PyUnicode_AsUTF8AndSize(swig_obj[1], &len, &bytes2);
    if (!p) SWIG_fail;
  } else {
    p = PyBytes_AsString(swig_obj[1]);
    if (!p) SWIG_fail;
    len = PyBytes_Size(swig_obj[1]);
  }
#endif
  arg2 = std::string_view(p, len);
  
  do_something(SWIG_STD_MOVE(arg1),SWIG_STD_MOVE(arg2));
  resultobj = SWIG_Py_Void();
  
  Py_XDECREF(bytes1);
  
  
  Py_XDECREF(bytes2);
  
  return resultobj;
fail:
  
  Py_XDECREF(bytes1);
  
  
  Py_XDECREF(bytes2);
  
  return NULL;
}
```
Notice that `Py_ssize_t len` and `const char *p` are defined more than once.

**Comment by ojwb** [comment]
Looks like this was correct in my original implementation but broken by 84f6031aa50443dc0ea9b0632acfd1c11813b90b which changed the typemap delimiters here (and in some other places that are also now broken) from `{`...`}` to `%{`...`%}`.  @wsfulton Is there some reason I'm missing for these delimiter changes?

I guess we could instead put a `{`...`}` block inside the `%{`...`%}` or maybe declare these variables in the typemap bit above (then they should get suffixed differently per expansion if memory serves).

**Comment by wsfulton** [comment]
I don't recall why I changed the braces, but I'll fix this blunder shortly.
