### ISSUE TITLE
Failure to clone repo

### ISSUE THREAD

**Issue by pushheap** [swig/swig#2857]
gh repo clone swig/swig

Cloning into 'swig'...
remote: Enumerating objects: 179508, done.
remote: Counting objects: 100% (143/143), done.
remote: Compressing objects: 100% (101/101), done.
error: 20 bytes of body are still expected.29 MiB | 159.00 KiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
failed to run git: exit status 128

$ git clone --branch v4.2.1 https://github.com/swig/swig.git
Cloning into 'swig'...
remote: Enumerating objects: 179508, done.
remote: Counting objects: 100% (143/143), done.
remote: Compressing objects: 100% (101/101), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 2062 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by ojwb** [comment]
I don't use the proprietary tools, but the latter command works fine for me.

From the error message this sounds like either a problem with your setup, a transient github issue, or something on the network route between you and github.
