### ISSUE TITLE
Should SWIG workaround MSVC stupidity?

### ISSUE THREAD

**Issue by ojwb** [swig/swig#2860]
By default in MSVC it seems `__cplusplus` has the value for C++98 **even if you explicitly request a newer language version with e.g. `/std:c++17`** - see the last line in the table here:

https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170

This seems a nasty trap - I've just wasted a fair bit of time trying to debug a problem which turned out to be SWIG's move semantics support not getting enabled due to this (because the SWIG-generated code checks the value of `__cplusplus` which reports C++98).

You can make MSVC do the sensible thing with command line option `/Zc:__cplusplus`, but you somehow need to know that you need to do this, and the docs for `/std:` don't seem to tell you: https://learn.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170

MSVC defines `_MSVC_LANG` with the value `__cplusplus` would have with a sensible compiler.  SWIG could check this, though the obvious approach would make any check for the `__cplusplus` value a bit unwieldly - a current check such as:

```
#if defined(__cplusplus) && __cplusplus >=201103L
```

becomes something like:

```
#if define(__cplusplus) && (defined(_MSVC_LANG) ? _MSVC_LANG : __cplusplus) > 201103L
```

We could define a SWIG-specific macro at the top of the generated C/C++ wrapper, which could actually simplify these checks by being defined (to say `-1L`) for C:

```
#ifdef __cplusplus
# ifdef _MSVC_LANG
#  define SWIG_CPPSTD _MSVC_LANG
# else
#  define SWIG_CPPSTD __cplusplus
# endif
#else
# define SWIG_CPPSTD -1L
#endif
```

Then the check above can just be:

```
#if SWIG_CPPSTD >= 201103L
```

(Such a macro could also solve #2818 if we take into account whether SWIG was run with `-c++` when generating the code to set it.)

Or we could instead alert users about the need to use `/Zc:__cplusplus` by generating something like this in the C++ wrapper:

```
#if defined(_MSVC_LANG) && _MSVC_LANG != __cplusplus
# warning Use MSVC option /Zc:__cplusplus to get __cplusplus correctly defined
#endif
```

**Comment by wsfulton** [comment]
> By default in MSVC it seems `__cplusplus` has the value for C++98 **even if you explicitly request a newer language version with e.g. `/std:c++17`** -

Agreed, unbelievable that a flag to explicitly set the C++ standard does not actually correctly set the all important `__cplusplus` macro. Microsoft have their reasons, so kind of tough on visual c++ users. I think all visual c++ developers eventually work this out, it's good to fully understand the quirks of a compiler one has to use and I went through the same journey in getting cccl to work correctly. I was thinking the best solution, given the sad state of this, would be for Microsoft to document this clearly. Remarkably, I've managed to more or less get this done via MicrosoftDocs/cpp-docs#5010.

> You can make MSVC do the sensible thing with command line option `/Zc:__cplusplus`, but you somehow need to know that you need to do this, and the docs for `/std:` don't seem to tell you: https://learn.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170

the link now references `/Zc:__cplusplus` in a big blue **Important** section.

I'm hesitant to add warnings telling people how to use their compiler, no matter how good the intentions are. With the improved Microsoft docs, perhaps we can also document in a few useful places, like in the Windows and CPlusPlus sections or put some advice in the code where in swiglabels.swg. I'd rather not replace `__cplusplus` with some other SWIG_CPPSTD macro as `__cplusplus` is so fundamental and well understood by all C++ developers and so keeping to it makes the generated code somewhat more readable. Readability is not essential, but very helpful. SWIG is documented to generate code that is standards compliant and users should ensure they are using standards compliance.

**Comment by erezgeva** [comment]
I saw you add support in `cccl` [Conversion of -std options for C++ fixes](https://github.com/swig/cccl/commit/23035b9fc0cee9359b2f1ebfbb2edb6a44e18cd0).

Yet AppVeyor uses older version.
In #2813, I use the latest `cccl`.

**Comment by wsfulton** [comment]
cccl-1.2 is currently being used which does include https://github.com/swig/cccl/commit/23035b9fc0cee9359b2f1ebfbb2edb6a44e18cd0. We could upgrade to cccl-1.3, but it doesn't offer anything we need. I'll try take a look at your pull request though.

**Comment by erezgeva** [comment]
> cccl-1.2 is currently being used which does include [swig/cccl@23035b9](https://github.com/swig/cccl/commit/23035b9fc0cee9359b2f1ebfbb2edb6a44e18cd0). We could upgrade to cccl-1.3, but it doesn't offer anything we need. I'll try take a look at your pull request though.

The #2813, pull request is about using GitHub with Windows.

My point for this issue was regarding using the newer version of `cccl`,
 so when we use the `-std` flag with C++, we would get the proper `__cplusplus` value.

Juts though we can do both :-)
