### ISSUE TITLE
[python, ruby, ocaml] Director mutex move to C++ 11 std::mutex

### ISSUE THREAD

**Issue by erezgeva** [swig/swig#2861]
Follow #2209 
As I also see issues in Ruby director on Linux (I got "corrupted double-linked list").

I though, perhaps we should use
[std::mutex](https://en.cppreference.com/w/cpp/thread/mutex)
I is supported from C++ 11.
It will improve our portability, may solve the issue with Windows and may also solve issues on Linux.
I think POSIX is getting obsolete, so we can keep it for old compilers and move on :-)

@wsfulton, what do you think?

**Comment by ojwb** [comment]
SWIG still aims to generate code requiring only C++98 (unless you're wrapping a feature which requires a newer C++ version - e.g. a wrapper for C++11 move functionality can require support for rvalue references), so requiring C++11 for directors doesn't fit.

**Comment by wsfulton** [comment]
I presume you are referring to the director code for Ruby here:
https://github.com/swig/swig/blob/a7eca8b4159840801c911c0d7b2a3325c3cbfa1e/Lib/ruby/director.swg#L219-L234
and similar for other languages.

There is no C or C++ standards based approach to threading and synchronisation primitives prior to C++11 and the next best standard was pthreads. The pthreads support is there to help if you are able to use pthreads, which was the best threading support available way back. With the improved C++11 threading support, we should definitely add in C++11 standards support and use it if available. The fallback of not having threading support is fine and can remain. In fact we ought to have a macro to turn off threading support for those that prefer performance over multiple threads.

The question then is what is the priority in the event both can be detected, pthreads or C++11 mutex? I'd vote for C++11 mutex in this case as directors are a C++ feature.

Also, the code ought to be abstracted into a separate file with just one implementation for use from different target languages. Unfortunately, there is a lot of similar code for directors and could be abstracted into a common directors file, but this is not priory if you just want to modify the sole two SWIG_GUARD implementations.

**Comment by erezgeva** [comment]
> I presume you are referring to the director code for Ruby here:
> 
> https://github.com/swig/swig/blob/a7eca8b4159840801c911c0d7b2a3325c3cbfa1e/Lib/ruby/director.swg#L219-L234
> 
> 
> and similar for other languages.
> There is no C or C++ standards based approach to threading and synchronisation primitives prior to C++11 and the next best standard was pthreads. The pthreads support is there to help if you are able to use pthreads, which was the best threading support available way back. With the improved C++11 threading support, we should definitely add in C++11 standards support and use it if available. The fallback of not having threading support is fine and can remain. In fact we ought to have a macro to turn off threading support for those that prefer performance over multiple threads.
> 
> The question then is what is the priority in the event both can be detected, pthreads or C++11 mutex? I'd vote for C++11 mutex in this case as directors are a C++ feature.
> 
> Also, the code ought to be abstracted into a separate file with just one implementation for use from different target languages. Unfortunately, there is a lot of similar code for directors and could be abstracted into a common directors file, but this is not priory if you just want to modify the sole two SWIG_GUARD implementations.

Yap, that is what I though.
I like the idea of using a common swig guard for all languages.
I agree it is not priority.
I saw an issue in the Ruby director (probably not related to guard itself) and I though I can improving the guard part :-)
And perhaps solve the windows issue on the way ...

**Comment by erezgeva** [comment]
Add C++ 11 in #2870
