### ISSUE TITLE
Any plans for Python 3.13 support?

### ISSUE THREAD

**Issue by hvbtup** [swig/swig#2863]
Python 3.13 (ATM there is an Alpha 5 available) is scheduled for Oct 2024.
From what I've heard, in comparison to 3.12 there are quite a lot of changes at the C API level.

Are there any plans for SWIG to support Python 3.13?

**Comment by wsfulton** [comment]
SWIG always supports the new Python versions, someone always contributes them or I will eventually get round to it. I havn't been tracking the latest C API changes, but any pull requests making python-3.13 work are likely to be accepted into master even if raised before the final version is released.

**Comment by ojwb** [comment]
@hvbtup If you want to help make it happen, a good starting point would be installing the latest pre-release of Python 3.13 and running SWIG's examples and testsuite with it.  That would at least show if any changes are actually needed, and give some idea of the scope (though one minor low-level incompatible change can break a lot of testcases so the variety of errors seen probably gives a better idea than the number of failing testcases).

**Comment by jschueller** [comment]
swig will probably compile with 3.13, but it uses deprecated APIs (PyErr_Restore, PyErr_Restore since py>=3.12)
