### ISSUE TITLE
Called C++ object pointer is null

### ISSUE THREAD

**Issue by behrisch** [swig/swig#2865]
I run a static code analysis on my code and it complains on several occasions about possible nullptr dereferencing.
The SWIG generated code looks always something like this (removed unrelated parts for clarity): 

```
SWIGEXPORT jstring JNICALL Java_org_eclipse_sumo_libsumo_libsumoJNI_TraCIResult_1getString(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  libsumo::TraCIResult *arg1 = (libsumo::TraCIResult *) 0 ;
  std::shared_ptr< libsumo::TraCIResult const > *smartarg1 = 0 ;
  std::string result;
  
  smartarg1 = *(std::shared_ptr< const libsumo::TraCIResult > **)&jarg1;
  arg1 = (libsumo::TraCIResult *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((libsumo::TraCIResult const *)arg1)->getString();
```

and the analyzer complains (in my opinion rightfully) that arg1 may be a nullptr.

The input here is actually very simple:
```
struct TraCIResult {
    virtual ~TraCIResult() {}
    virtual std::string getString() const {
        return "";
    }
    virtual int getType() const {
        return -1;
    }
};
```

Is this a SWIG bug or something on my side?

The full analysis is here: https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=org.eclipse.sumo&open=AYu3V6V_cCBGz8tOdO5j

The corresponding interface files are here: https://github.com/eclipse-sumo/sumo/blob/main/src/libsumo/libsumo_typemap.i https://github.com/eclipse-sumo/sumo/blob/main/src/libsumo/libsumo.i

A related discussion may be #2295 and I am using swig 4.0.2 on Windows and Linux with similar results

**Comment by wsfulton** [comment]
While technically possible for arg1 to be a null pointer, it's highly unlikely as it is the underlying 'this' pointer held in the Java proxy class. This is set to null when the object is garbage collected and can no longer be used to call the getString member wrapper. You can of course put in a check as mentioned in the links you provide. Here is the solution for your examples:

```swig
%typemap(check) TraCIResult *self %{
  if (!$1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "NULL self");
    return $null;
  }
%}
```
and that will keep the static code analyser happy.

**Comment by behrisch** [comment]
@wsfulton Thanks a lot, this worked as expected.

**Comment by behrisch** [comment]
I have one more question, though. I just noticed that in the code generated for `set...` functions  there is actually a check like `if (arg1) ...`. Wouldn't it be more consistent then to do the same in the getter as well?
