### ISSUE TITLE
Parsing issue when fvirtual is enabled in SWIG 4.1.2

### ISSUE THREAD

**Issue by leakec** [swig/swig#2872]
Noticed this issue on a much larger codebase and was able to create a smaller, standalone version. Basically, the issue is that when enabling `-fvirtual` in SWIG 4.2.1, there is an instance where a wrapped Python method should have two options (and thus uses `*args` when passing things to SWIG), but it only has one. Disabling the `-fvirtual` flag causes things to be wrapped correctly. This appears to be a new issue in 4.2.1, as 4.1.1 works as expected. I've included the files I used in my standalone test in the expandable section below. I'll also include them as a `.zip` attached to this issue to make re-creating it easier.

<details><summary> Click to expand files used in the standalone test </summary>

`test.h`
```c++
#ifndef TEST_H
#define TEST_H
class Base
{
public:
    virtual int works(){return _x;};
    virtual void does_not_work(int x) = 0;
protected:
    int _x = 0;
};

class D1 : public virtual Base
{
public:
    using Base::works;
    virtual void works(int x){_x = x;};
    virtual void does_not_work(int x){_x = x;};
};

class D2 : public virtual D1
{
public:
    using D1::does_not_work;
    virtual int does_not_work() const {return _x;};
};
#endif
```

`test.i`
```swig
#ifndef MY_SWIG_EXAMPLE
#define MY_SWIG_EXAMPLE

%module(directors="1") test_Py

%{
#include "test.h"
%}

%include "test.h"

#endif
```

`test.cxx`
```c++
#include "test.h"
```

`test.py`
```python
from test_Py import D2

d2 = D2()

d2.works()
d2.works(4)

d2.does_not_work()

# This call is broken if -fvirtual is included and we use the 
# "using" keyword to include functions
d2.does_not_work(5)
```

Commands run by make (this example with `-fvirtual`):
```
swig -python -c++ -fvirtual -module test_Py -o test_swigwrap_Py.cxx test.i                                                                                                   
g++ -fPIC -o test_swigwrap_Py.o -c test_swigwrap_Py.cxx -I/usr/include/python3.12                                                                                            
g++ -fPIC -o test.o -c test.cxx -I/usr/include/python3.12                                                                                                                    
g++ -shared -o libtest.so test.o                                                                                                                                             
g++ -shared -o _test_Py.so test_swigwrap_Py.o -L. -ltest -I/usr/include/python3.12
```
</details>

Running `LD_LIBRARY_PATH=. python -i test.py` yields an error 
```
Traceback (most recent call last):                                                                                                                                           
  File "/home/leake/Downloads/test2/test.py", line 12, in <module>                                                                                                           
    d2.does_not_work(5)                                                                                                                                                      
TypeError: D2.does_not_work() takes 1 positional argument but 2 were given 
```

Essentially, SWIG does not create wrappers for both versions of `does_not_work`. It only creates a wrapper for the version defined in `D2`, even though `Base` defines another version. 

## Other notes
Here are some other notes that may be useful:
* If I remove `-fvirtual` from the `swig` command, things work as expected.
* If I use `using Base:does_not_work` rather than `D1:does_not_work`, then things work as expected.
* If I use SWIG 4.1.1 rather than 4.2.1 things work as expected.

[test.zip](https://github.com/swig/swig/files/14960769/test.zip)

**Comment by leakec** [comment]
Using `git bisect` it looks like this is the first commit where the problem arises: 655d43769e818d06e67123606090e3c25b64f71b

**Comment by wsfulton** [comment]
Thanks for the bisect info. I'll take look at this, but not sure when at the moment.

**Comment by leakec** [comment]
@wsfulton Sounds good, thank you! I'll also try and take a look at this if I have some free time over the next few days/weeks. However, I have never taken a look at the SWIG source code before, so may take me a little bit to get my bearings.

**Comment by wsfulton** [comment]
Alas, correctly handling a mix of using declarations and virtual functions has been a long ongoing battle. I thought I'd sorted it all out :(. And there are so many tests for it including `python -O` which includes the `-fvirtual` option.

**Comment by leakec** [comment]
> Alas, correctly handling a mix of using declarations and virtual functions has been a long ongoing battle. I thought I'd sorted it all out :(. And there are so many tests for it including `python -O` which includes the `-fvirtual` option.

No worries, it looks/sounds incredibly complicated. A huge thanks to you and the rest of the community for this amazing tool! 

I'm thinking maybe the example case I've included here is hitting a corner case where we have a using declaration for parent class, but the parent class doesn't override the function from the grandparent class. Likely somewhere just needs to be searching up the inheritance tree. In the notes, if the `using` declaration points directly to the grandparent class, things get wrapped correctly. Will have a look through the code this weekend or next week to see what I can find.

**Comment by leakec** [comment]
Making some headway here, just going to use this as a spot to keep notes while I go:

* When `-fvirtual` is set, when we parse `D1` we will end up setting `feature:ignore` of `does_not_work` to `1`. As a  result, when we loop through all the nodes of the `D1` class, we will skip the `does_not_work` node. Consequently, `set_firstChild` is never run, and we never have a change to slot the `using` node's method in. 
* Tried with adding in a new `feature:fvirtual_ignore` so we could push through and try to run these blocks if the method was ignored because of `fvirtual`. This allows us to try and slot the `using` node's method in, but I'm still seeing it ultimately ignored in the end.

**Comment by leakec** [comment]
Okay, I've got a patch that fixes this! It is based on adding an extra flag as mentioned above.

```patch
diff --git a/Source/Modules/allocate.cxx b/Source/Modules/allocate.cxx
index a53be0756..2afedcab8 100644
--- a/Source/Modules/allocate.cxx
+++ b/Source/Modules/allocate.cxx
@@ -234,6 +234,7 @@ class Allocate:public Dispatcher {
 			// Don't eliminate if an overloaded method as this hides the method
 			// in the scripting languages: the dispatch function will hide the base method if ignored.
 			SetFlag(n, "feature:ignore");
+            SetFlag(n, "feature:ignored_by_fvirtual");
 		      }
 	      } else {
 		// Some languages need to know about covariant return types
@@ -633,6 +634,14 @@ class Allocate:public Dispatcher {
  * ----------------------------------------------------------------------------- */
 
   void add_member_for_using_declaration(Node *c, Node *n, int &ccount, Node *&unodes, Node *&last_unodes) {
+    if (GetFlag(c, "feature:ignored_by_fvirtual"))
+    {
+        // This node was ignored by fvirtual. Thus, it has feature:ignore set. 
+        // However, we may have new sybling overrides that will make us want to keep it.
+        // Hence, temporarily unset the feature:ignore flag.
+        UnsetFlag(c, "feature:ignore");
+    }
+
     if (!(Swig_storage_isstatic(c)
 	  || checkAttribute(c, "storage", "typedef")
 	  || Strstr(Getattr(c, "storage"), "friend")
@@ -665,6 +674,10 @@ class Allocate:public Dispatcher {
 	Swig_warning(WARN_LANG_USING_NAME_DIFFERENT, Getfile(c), Getline(c), "the method from %s, with name '%s', as the names are different.\n", Swig_name_decl(c), csymname);
       }
     }
+    if (GetFlag(c, "feature:ignored_by_fvirtual"))
+    {
+        SetFlag(c, "feature:ignore");
+    }
   }
 
   bool is_assignable_type(const SwigType *type) {
```

The next thing to do is make sure this doesn't break anything else, e.g., the other tests. Will check this and then submit a PR if the tests pass.

**Comment by leakec** [comment]
@wsfulton I've got a PR created that applies the draft above. The PR is #2873. Please let me know what you think of the suggested fix and any improvements that could be made to it. I think it may also be a good idea to add the test case included with this issue (or some version of it), but I'm not sure of the best way to do that.
