### ISSUE TITLE
Ignored class leads to spurious "Warning 520: Derived class 'Derived' of 'Base' is not similarly marked as a smart pointer."

### ISSUE THREAD

**Issue by q-p** [swig/swig#2879]
Using Swig Version 4.2.1 (on macOS, but I think that's irrelevant here).
Regression compared to Swig Version 4.0.2 where the reproducer is warning free.

When ignoring a class whose base is declared for use as a `shared_ptr` (via `%shared_ptr`), swig gives a 520 warning irrespective of whether the derived class is also declared as `%shared_ptr` or not.

Consider the following interface
```swig
%module repo

%include <std_shared_ptr.i>
%shared_ptr(Base);
%shared_ptr(Derived);

%ignore Derived;

%inline %{
struct Base { };
struct Derived : Base { };
%}
```

compiling via

```bash
> swig -c++ -python shared_ptr_warning.i
shared_ptr_warning.i:11: Warning 520: Derived class 'Derived' of 'Base' is not similarly marked as a smart pointer.
```

I'm not sure what to do to work around / avoid this warning. `Derived` is marked as smart pointer (but then ignored since we don't actually want to wrap it, but it's in a header from which we want to wrap other stuff).

**Comment by ojwb** [comment]
> I'm not sure what to do to work around / avoid this warning.

You can suppress most warnings with `%warnfilter` - this adjusted version doesn't warn:

```
%module repo

%include <std_shared_ptr.i>
%shared_ptr(Base);
%shared_ptr(Derived);

%warnfilter(SWIGWARN_LANG_SMARTPTR_MISSING) Derived;

%ignore Derived;

%inline %{
struct Base { };
struct Derived : Base { };
%}
```

SWIG shouldn't warn about this by default though.  Still reproducible with current git master.

**Comment by ojwb** [comment]
git bisect indicates this is indeed a regression, introduced by 3be670e8db5b45195b670c91eac3fb413cf8427b.  @wsfulton That was one of yours.
