### ISSUE TITLE
Using swig in golang and using Eigen Vectors c++ package

### ISSUE THREAD

**Issue by sdoshidensity** [swig/swig#2885]
Hi,

We are trying to use c++ eigen vectors c++ package and calling it from golang. We are facing issue such as eigen vector package not found. 

How should we fix it? Or is this not possible through swig.

**Comment by ojwb** [comment]
This sounds like a bug in your wrapping rather than a problem with SWIG.

**Comment by ojwb** [comment]
Closing - seems likely to be a usage problem, and if it isn't there's not enough information provided to do anything about it.
