### ISSUE TITLE
Go doesn't track C++ object ownership

### ISSUE THREAD

**Issue by michael-schaller** [swig/swig#289]
Go currently doesn't track C++ object ownership like other target languages do. Tracking the C++ object ownership would allow Go to automatically free C++ objects once they are no longer referenced and thus simplify the usage of a SWIG wrapper as objects wouldn't need to be freed manually unless the wrapper would specifically demand it.

Generated Java code for an example C++ class:
``` java
public class Test {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Test(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Test obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  // Call C++ destructor
  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      exampleJNI.delete_Test(swigCPtr);
    }
    swigCPtr = 0;
  }

  // Call C++ constructor
  public Test() {
    this(exampleJNI.new_Test(), true);
  }
}
```

In order for Go to track the C++ object ownership all structs that represent a C++ class would need to have an ownership boolean, the ownership boolean would need to be initialized properly (tracked or not tracked) on object creation and in case a C++ object is tracked runtime.SetFinalizer needs to be called after object creation with its delete function as finalizer function.

This topic has been previously discussed with @ianlancetaylor in issue #266.

**Comment by ianlancetaylor** [comment]
I've seen existing SWIG code fail due to runtime.SetFinalizer.  To briefly sketch the problem, class C1 had a field that was a vector of items of class C2.  The C1 destructor destroyed the vector and all the C2 elements.  The Go code had a variable of type wrap.C1, and retrieved a value of type C2.  The value of type C2 was then passed to various other functions.  Although the variable of type C2 was not returned, the function made no further references to the variable of type C1.  Therefore, the C1 variable was not live, and the Go garbage collector observed that, freed it, and ran the finalizer.  Running the finalizer ran the C++ destructor, which destroyed the C1 object and the C2 object.  However, the Go code was still using the Go version of the C2 object, which in effect became a dangling pointer.

My point is that automatic destruction of SWIG objects takes great care in Go, because objects can be finalized at points where many programmers would consider them to be obviously live.  I don't know if Java has similar problems.

**Comment by michael-schaller** [comment]
Ian, that is a great example for discussion. Other languages have solved this problem. Unfortunately the respective implementation differs a lot from target language to target language. :-(

Here is the Java documentation: http://www.swig.org/Doc3.0/SWIGDocumentation.html#Java_memory_management_member_variables

Here is the Ruby documentation:
http://www.swig.org/Doc3.0/SWIGDocumentation.html#Ruby_nn60

As you can see the solutions are completely different and so I guess we should first discuss what would be actually desired for Go. Maybe we should start a design doc. Ian, what do you think?

**Comment by ianlancetaylor** [comment]
I think the Java approach requires the person writing the interface to have a deep knowledge of the C++ code and an understanding of what destructors do what.  Unfortunately in practice I think that the person writing the SWIG interface often has only a superficial knowledge of the C++ code.  The person writing the interface is primarily a Go developer, not primarily a C++ developer.

When C++ objects need to live across multiple calls to C++, the reliable approach is to store the C++ value into a Go object, and give that Go object a type with a Close method that deletes the C++ object.  Then call the Close method when you are done with it.  That will rarely go wrong.

I think that the only time people should use finalizers on the Go object is when the lifespan of the Go object can not be known.  We should support that case but it should never be the default.

So it's not clear to me that there is anything to be done here other than better documentation.

**Comment by michael-schaller** [comment]
I agree that often times people only have a superficial knowledge of the C++ code they are trying to wrap. I also agree that manual memory management is the most reliable and most deterministic way - which in general I think is what one would want with Go. ;-)

On the other hand there are way too often cases in which the C++ object lifetime isn't known or hard to predict. It's also sometimes hard to wrap C++ code in a way so that it can be idiomatically used from Go without having to bother someone with manual memory management. For these cases I would prefer if a C++ object could be owned on demand by Go. Of course one can do it manually - like it has been documented - or even better would be if the generated wrapper code would support it. How would a simple 'TakeOwnership' or 'Own' method sound?

Maybe I should also give an example to illustrate. Let's take this C++ iterator example:
``` C++
for(
    MyClass::iterator MyClassIter = MyClass.begin();
    MyClassIter != MyClass.end();
    MyClassIter ++)
{
    (*MyClassIter)->DoSomething();  
}
```

How would you wrap/implement a similar iterator in Go so that it is idiomatic to use?
How would you implement it so that you can use it for something as common as a linear search and make sure that everything is freed/destroyed behind the scenes when the search is done?

**Comment by ianlancetaylor** [comment]
Go code isn't full of iterators the way that C++ code is.  When there are iterators, they usually use Next.  So, using a close method, this would be something like

func StartIteration() *Iterator
func (*Iterator) Next() (*Val, bool)
func (*Iterator) Close()

and using it would be

p := StartIteration()
defer func() { p.Close() }()
for {
    v, done := p.Next()
    if done {
        break
    }
    ...
}

**Comment by ianlancetaylor** [comment]
I think the default should be to not use finalizers, so Own doesn't sound right.

I suppose we could add a method to every C++ class type that, when called, returns a new Go value with a finalizer that has all the methods of the original Go value.  Maybe.

**Comment by michael-schaller** [comment]
Thanks for the example, Ian. I think I would handle it the same way and I guess it wasn't a good example after all... *sigh*

Anyhow. I agree with you that finalizers should NOT be used by default. I don't think that adding a method to every C++ class type is a good idea though. How about adding a SWIG feature - similarly to the director feature - to decide if a C++ class type has a finalizer?

**Comment by ianlancetaylor** [comment]
Sure, a SWIG %feature works for me.

**Comment by michael-schaller** [comment]
Okay. Let's play that through real quickly.
If a C++ class has the "finalizer" feature enabled then I assume:
* On NewClassName call a SwigcptrClassName object would be registered with runtime.SetFinalizer and DeleteClassName would be used as finalizer function.
* The DISOWN typemap (or a similar mechanism) needs to be implemented so that objects given to C++ code aren't deleted by the finalizer.
* [optional] The %newobject feature could be implemented to support factory functions/methods.

Ian, does that sound about right? The only thing I'm missing would be a way to check from Go if a C++ object is owned by Go.

BTW: The SWIG documentation points 23.3.1 (Additional Commandline Options) and 23.3.2 (Go Output Files) need an update regarding the recent changes for Go 1.5. Should I open a bug for you?

**Comment by ianlancetaylor** [comment]
A finalizer can only be associated with a Go pointer, which SwigcptrClassName is not.  I think it would be confusing to change the type of SwigcptrClassName to be a pointer.  So I guess that using this feature means that we have to change the return type of NewClassName.  It could be, for example, *SwigcptrClassName.  All the methods should still work, so it should still implement the ClassName interface.

I suppose DISOWN would set the finalizer to nil.

I can't think of any way to check whether an object has a finalizer.  I'm also not sure why it matters.  We could keep a map of objects with finalizers, but then of course they would never be finalized.  I suppose we could keep a map on the C++ side.

I thought I did update the docs for the Go 1.5 changes.  If there is something else I need to add, then, sure, open an issue.  Thanks.

**Comment by michael-schaller** [comment]
I've opened issue #371 for the documentation update.

I knew I was missing something! Ian, thank you for reminding me that runtime.SetFinalizer needs a type compatible to interface{}. Do you think that the return type of NewClassName can be changed? Wouldn't that break existing code that has the return type hardcoded? I don't know how much code doesn't use a short variable declaration but I guess there is some code out there...

DISOWN would indeed set the finalizer to nil. In addition - if the ownership state is somehow represented - it would update that as well. The ownership state is tricky though as it would be needed for the SWIG test suite. See the disown Python test as an example [1]. As you've pointed out there is no way to check from the Go side if a finalizer has been set. Maintaining a map on the C++ side is also tricky as it needs to be thread safe. FWIW tracking the ownership state was the sole reason for my previous attempt (pull request #291) to change SwigcptrClassName to a struct type.

Thread safety also raises another point. Looking at the current documentation I think either "23.4.5.1 Go Class Memory Management" [2] or "runtime.SetFinalizer" [3] needs an update to clarify/emphasize that DeleteClassName will be run from a different thread in case a finalizer is used. I guess updating "23.4.5.1 Go Class Memory Management" would be the right place.

Ian, what do you think of all this? To me it feels like opening a can of worms...

[1] https://github.com/swig/swig/blob/master/Examples/test-suite/python/disown_runme.py#L24
[2] http://www.swig.org/Doc3.0/SWIGDocumentation.html#Go_class_memory
[3] http://golang.org/pkg/runtime/#SetFinalizer

**Comment by ianlancetaylor** [comment]
I think the return type of NewClassName can be changed if the .swig file uses an explicit %feature.

Go calls into C++ can always come from any thread.  Goroutines move around between threads as they execute.  You're right that this should probably be mentioned explicitly in the SWIG docs.

I agree that this is a can of worms and I'm not sure it's necessary for SWIG to do anything.

**Comment by michael-schaller** [comment]
Good point about changing NewClassName if the "finalizer" feature is enabled. That would work without breaking existing code. It would also allow to add a boolean to represent the ownership state.

Should I open a new bug regarding SWIG and threads? Is there any cgo documentation regarding this topic? Should people who aren't entirely sure about the thread safety of a C/C++ library use only one Goroutine that is locked to the OS thread via runtime.LockOSThread to communicate with the library?

The big remaining question is if this is all worth the effort. Surely one can write this all manually but SWIG would allow to automate it significantly as the feature could be enabled selectively or for a complete SWIG interface. Implementing this could also help reducing the risk of memory leaks and make it easier to use wrapped C++ code... But enough with the sales pitch. ;-)

Ian, should I give it a try or do you think this is too much of a can of worms?

**Comment by ianlancetaylor** [comment]
I'm not aware of any docs on cgo and threads.  Sure, open an issue to add some notes to the SWIG docs.  Using runtime.LockOSThread with a single goroutine is not so much a way to address thread safety as a way to work with C/C++ libraries that use Thread Local Storage.  If the issue is thread safety without TLS, then you need some sort of mutex controlling access to the library but you don't need to restrict yourself to a single goroutine.

As far as whether automatic finalizers are worth the effort, I don't know.

**Comment by michael-schaller** [comment]
I've opened issue #374 regarding thread safety and TLS.

Regarding the automatic finalizers... Let's finish the plan and then I'll look into it how hard it is actually to implement and how good I feel about it. Once I have code ready I feel happy about I'll let you have a look. How does that sound?

Let's discuss the plan for automatic finalizers in a Go document:
https://docs.google.com/document/d/1ZWcvVYuxrXLOCDD5jAtcITVDwbDOTfj5lXnAKgRE9c0/edit?usp=sharing

**Comment by michael-schaller** [comment]
Ian, I've spent a lot of time to thoroughly play with this and I came to the conclusion that it is **not** worth to implement automatic finalizers. The more I've played with this it felt more and more wrong and like a violation of what Go stands a lot for - explicit code. But let me start in the beginning...

If someone wraps a small C++ code base with SWIG then **the** way to go is to use **defer** to ensure that the destructor is called:
``` go
func UseCppStuff(...) ... {
	o := NewClassName(...)
	defer DeleteClassName(o)

	// Use C++ object, handle errors and return whatever is to return
	...
}
```
Go's **defer** nicely fits C++'s RAII idiom. I have a slightly more elaborate example here: https://github.com/michael-schaller/go-swig-examples/tree/master/issue289-example1

Now with increasing complexity of the C++ code base to wrap using **defer** becomes harder and harder and handing around wrapped C++ objects or object hierarchies in various parts of ones Go code can easily make it very hard to use **defer** at the right place. Not to mention that the user of the wrapped C++ code needs to know how to use the C++ code as well. Which is rarely the case... **sigh**

The solution for some other target languages of SWIG is to track the object ownership in the target language and as soon as there are no references from the target language to a C++ object anymore the destructor (DeleteClassName) will be called automatically from the target language. We've discussed this for Go with a lot of detail in this bug and there is a long list of caveats with implementing this for Go:
* Go finalizers have limitations as documented here: https://golang.org/pkg/runtime/#SetFinalizer
  + Unlike Go's **defer** using a Go finalizer is not RAII compliant as Go finalizers aren't deterministic
  + Go finalizers don't work with C++ destructors that touch thread-local storage as the finalizer most likely runs in a different OS thread
  + Go finalizers require a pointer to an object but the constructor (NewClassName) doesn't return a pointer type
  + The Go finalizer needs to be removed in case the ownership of an object is transferred back to C++ (disown)
* C++ object hierarchies need to be replicated in Go so that the finalizer for a Go object doesn't run prematurely
* ...

In the beginning Go finalizers sound like a nice way to hide the wrapped C++ code and to make it easy to write bindings to a C++ library that behave like idiomatic Go code. Unfortunately this is often a lie as the user of such bindings often still requires knowledge of the underlying C++ library. For an instance if a wrapped C++ object is given back to C++ code (disown) then the wrapped C++ object shouldn't be used anymore from the Go code. So in reality with growing complexity of a C++ library it is more and more unlikely that the usage of Go finalizers will result in better and easier to use bindings. **sigh**

In the end I came to the conclusion that Go's finalizers aren't the right answer to this problem. I've wanted to use something like Go's **defer** and my current solution looks a lot like a context manager in Python:
``` go
func WithClassName(<constructor args>, f func(ClassName, ...interface{}) error, data ...interface{}) error {
	o := NewClassName(<constructor args>)
	defer DeleteClassName(o)
	return f(o, data...)
}

func UseClassName(o ClassName, data ...interface{}) (err error) {
	// Use ClassName object and additional data and return error.
}

func main() {
	WithClassName(<constructor args>, UseClassName, <additional data>)
}
```
I have a slightly more elaborate example here: https://github.com/michael-schaller/go-swig-examples/tree/master/issue289-example2

As this code uses **defer** the user can't forget to call the destructor and it nicely fits C++'s RAII idiom. If there are C++ object hierarchies then these will always be destructed in the reverse order of construction which is nice because it is deterministic and explicit. I think we should forget about automatic finalizers but we already have manual finalizers in the documentation. Maybe it was an error to document the usage of a finalizer in the first place...

Ian, what do you think?

**Comment by ianlancetaylor** [comment]
That does all sound reasonable.  Thanks for thinking about it.

**Comment by michael-schaller** [comment]
Great! So what would you like to see of all this in the documentation?
I'm happy to send a pull request...

**Comment by ianlancetaylor** [comment]
No clear idea.  Documentation is not my forte.

**Comment by michael-schaller** [comment]
Alrighty. Then let me send you a pull request so that we have something substantial to discuss. ;-)

**Comment by michael-schaller** [comment]
Ian, sorry for the delay with pull request #414. Please review.
