### ISSUE TITLE
How to access elements of a C++ image array (struct) with Lua?

### ISSUE THREAD

**Issue by Jonathhhan** [swig/swig#2894]
I have an array of this struct (`sd_image_t*`) as the return value of a function:
```
typedef struct {
    uint32_t width;
    uint32_t height;
    uint32_t channel;
    uint8_t* data;
} sd_image_t;
```
In C++ I can call `sd_image_t[n].data` while with SWIG created Lua bindings I can only call `sd_image_t.data` (which seems to be a pointer to all data of the struct). Is there a way to wrap it, so that I can call it like in C++?
Could `%naturalvar` help in my case? https://www.swig.org/Doc1.3/SWIGPlus.html#SWIGPlus_member_data
Here I tried to describe my issue too: https://forum.openframeworks.cc/t/swig-lua-binding-for-accessing-elements-of-an-image-array/43429

**Comment by ojwb** [comment]
You're looking at a really ancient version of the manual there (the last SWIG 1.3.x release was in 2009, the current release is SWIG 4.2.0).

See https://www.swig.org/Doc4.2/Lua.html#Lua_typemap_arrays for documentation discussing wrapping arrays for Lua.

**Comment by ojwb** [comment]
Question and answered so closing.

**Comment by Jonathhhan** [comment]
@ojwb thank you.
