### ISSUE TITLE
Python-wrapped C++/C code now featuring spurious "_object" class inheritance 

### ISSUE THREAD

**Issue by bbercoviciUspace** [swig/swig#2895]
A surprising regression just showed up in a project that uses SWIG 3.0.2 / GCC 9.4. This project features a number of C/C++ structures and classes that are exposed to Python. 

The issue can be described like so : the `MyStruct.py` file generated by SWIG that wraps the underlying structure `MyStruct` defined in `MyStruct.h` should feature a Python class `MyStruct` whose definition should start like in the following exemple : 

```
class MyStruct(object):
    def __init__(self):
        ...
        ...
```

In the present case, the wrapper class is instead defined as 

```
class MyStruct(_object):
    def __init__(self):
        ...
        ...
```

Note the leading underscore in `_object`. A number of issues ensue.

I will try to provide more details early next week. But I can't figure out how this happened, as the same project compiled on other systems doesn't feature this change.

**Comment by ojwb** [comment]
SWIG 3.0.2 is nearly 10 years old - you can't realistically expect us to still be supporting it.

However, try looking at the top of the generated wrapper file which should define `_object` - something like:

```
try:
    _object = object
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0
```

If you run your ancient SWIG version with `-modern` then this isn't generated and just `object` is used.  SWIG 4.0.0 made the effects of `-modern` the default, so with newer SWIG you won't see this anyway.

**Comment by bbercoviciUspace** [comment]
Hi @ojwb , you were absolutely right, thanks again !
