### ISSUE TITLE
#999 Not used by default in MSVC

### ISSUE THREAD

**Issue by bartoli** [swig/swig#2897]
It seems like #999  could work at least up to MSVC2015. But, the condition in SwigValueWrapper depends on __cplusplus value being >=2011XX, which by default is stuck to 199711 for MSVC (https://learn.microsoft.com/fr-fr/cpp/build/reference/zc-cplusplus?view=msvc-170) unless we are at least in MSVC2017 and have the option /Zc:__cplusplus

Could the condition be updated to also check _MSVC_LANG value?

**Comment by wsfulton** [comment]
SWIG expects a standards compliant compiler as it generates standards compliant code, `_MSVC_LANG` is not in the C or C++ standard. Please configure your compiler to be standards compliant or use a compiler that is standards compliant. You've already identified that the `/Zc:__cplusplus` option is required for MSVC to be compliant, so you do need to use this option. Related to #2860.

**Comment by bartoli** [comment]
I actually am with VS2015 compilers, where the /Zc poption was not availabe yet, hence why my request, since the compiler can build the code, but not unless i patch the condition.
I'll just patch my swig output

**Comment by wsfulton** [comment]
`__cplusplus` is just a macro so define it to an appropriate value using the `\D` cl.exe option or add it to the top of your generated wrapper code using `%begin`, for example:
```swig
%begin %{
#define __cplusplus 201103L
%}
```

**Comment by ojwb** [comment]
Redefining `__cplusplus` for the compiler like that would be undefined behaviour though (citation: https://en.cppreference.com/w/cpp/preprocessor/replace says "Attempts to redefine or undefine these macros result in undefined behavior.")
