### ISSUE TITLE
support primitive rvalue types

### ISSUE THREAD

**Issue by leeroyka** [swig/swig#2900]
swig 4.3.0

if you try wrap this function
```c++
void foo(int && value);
```
swig will generate (for c#):
```c#
public static void foo(SWIGTYPE_p_int value)
```

**Comment by wsfulton** [comment]
Moving an integer from a target language to C++ doesn't make much sense. However, you can treat it as an lvalue reference by applying the const lvalue reference typemaps as follows, it may give you want you want:
```swig
%apply const int & {int &&};
```

**Comment by leeroyka** [comment]
> Moving an integer from a target language to C++ doesn't make much sense. However, you can treat it as an lvalue reference by applying the const lvalue reference typemaps as follows, it may give you want you want:
> 
> ```c++
> %apply const int & {int &&};
> ```

Yes, you are right that it makes no  make sense to move the primitive types. However, due to the need for templates to be specialized in swig, it will be necessary to write `apply` separately for certain types. I would prefer if this could be handled natively.

```c++
foo(T && value);

%template(foo) foo<Movable>;
...
%template(foo) foo<float>;
%apply const float & {float &&}; /* not friendly */
```
