### ISSUE TITLE
Generated cpp results in C2664

### ISSUE THREAD

**Issue by serban-seeq** [swig/swig#2901]
This is on windows and c#.

Consider this swg file:
```
%{
#include <map>
%}
%include "std_map.i"
%include "std_wstring.i"
namespace std {
	%template(map_string_string) map<wstring, wstring>;
}
```

There's a change from 4.0.2 => 4.1.1 where the generate code for std::map (for example map_string_string_ContainsKey )is different in the following ways.
1. jarg2 type changes `wchar_t` => `unsigned short`
2. `Swig_csharp_UTF16ToWString` is called for `arg2_str` as well as defined at the top.

Now if I add this typemap:
`%typemap(ctype, out="BSTR") wstring, const wstring & "wchar_t *"`

Its going to change `jarg2`'s type from `unsigned short` => `wchar_t` but now compilation breaks because `Swig_csharp_UTF16ToWString expects` an `unsigned short` the error is:
`error C2664: 'std::wstring Swig_csharp_UTF16ToWString(const unsigned short *)': cannot convert argument 1 from 'wchar_t *' to 'const unsigned short *'`

The only solution I found was to write this awkward typemap but it feels like a hack
`%typemap(ctype, out="BSTR") wstring, const wstring & "unsigned short *"`

Is this expected behavior?

**Comment by wsfulton** [comment]
I can see this change from:
```c
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_map_string_string_ContainsKey(void * jarg1, wchar_t * jarg2) {
```
to
```c
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_map_string_string_ContainsKey(void * jarg1, unsigned short * jarg2) {
```
Which is part of a bunch of changes related to #1233, in particular 0fbd6cc364910a352ee01a90196f647b32076ef1 which uses `unsigned short *` instead of `wchar_t *` for the C type for marshalling. 

I don't quite follow, but if you were previously using
```swig
%typemap(ctype, out="BSTR") wstring, const wstring & "wchar_t *"
```
it makes sense to update for swig-4.1 to:
```swig
%typemap(ctype, out="BSTR") wstring, const wstring & "unsigned short *"
```
Hopefully that makes sense in which case this ticket can be closed.
