### ISSUE TITLE
SWIG parser not considering definitions inside hearders in header files   

### ISSUE THREAD

**Issue by datNurd** [swig/swig#2903]
I am trying to create a JNI warpper using SWIG 4.2. This wrapper is for, "fpdf_edit.h" a header file of pdfium (pdf parsing library by google). However, it throws the following error `/fpdf_edit.h:102: Error: Syntax error - possibly a missing semicolon (';').`

This is my .i file definition

```
%module fpdfedit_wrap
%{
#include "fpdfview.h"
#include "fpdf_edit.h"
%}
%include "fpdf_edit.h"
```

The code on line 102 mentioned in the error is `FPDF_EXPORT FPDF_DOCUMENT FPDF_CALLCONV FPDF_CreateNewDocument();` which has no syntactical issue

But the swig parser works when I change by swig interface file by adding `%include "fpdfview.h"` 

**Working swig interface definition**

```%module fpdfedit_wrap
%{
#include "fpdfview.h"
#include "fpdf_edit.h"
%}
%include "fpdfview.h"
%include "fpdf_edit.h"
```

what I observe is if the definitions are in a header file inside the SWIG parsing header file its throwing an error. The above line `FPDF_EXPORT FPDF_DOCUMENT FPDF_CALLCONV` definitions are inside the "fpdfview.h" header file declared in the line 13 of fpdf_edit.h file
[fpdfview.h.txt](https://github.com/swig/swig/files/15273986/fpdfview.h.txt)
[fpdf_edit.h.txt](https://github.com/swig/swig/files/15273987/fpdf_edit.h.txt)

My command `swig -c++ -java -o fpdfall_wrap.cxx -I/home/xxx/xxx/pdfium-linux-x64/include -v -outdir ./pdfiumjni fpdf_edit_jni.i`

Output :
```
Language subdirectory: java
Search paths:
   ./
   /home/xxx/x/pdfixum-linux-x64/include/
   ./swig_lib/java/
   /usr/local/share/swig/4.2.1/java/
   ./swig_lib/
   /usr/local/share/swig/4.2.1/
Preprocessing...
Starting language-specific parse...
/home/xxxxx/xxxxx/pdfium-linux-x64/include/fpdf_edit.h:102: Error: Syntax error - possibly a missing semicolon (';').
```
 
The problem that have with adding `%include "fpdfview.h"` is that the resulting .cxx file will contain code from `fpdfview.h` and dont want this as we dont intend to use it in our jni

**Comment by ojwb** [comment]
SWIG doesn't follow`#include` by default (as documented).  You can use `-includeall` if you really want it to, though if system headers get included by doing so you may not have a good time (see #2167 for more discussion of that).

> The problem that have with adding %include "fpdfview.h" is that the resulting .cxx file will contain code from fpdfview.h and dont want this as we dont intend to use it in our jni

You can use `%import` if you want SWIG to parse a header but not wrap classes, functions, etc in it (there's also `-importall` which implicitly imports each `#include`).

**Comment by datNurd** [comment]
Thank you this does the job for me closing the same.
