### ISSUE TITLE
Problem with unignoring symbols inside namespace. 

### ISSUE THREAD

**Issue by AnDevi** [swig/swig#2911]
I'm trying to use SWIG as is told in example: 
https://swig.org/Doc4.0/SWIGDocumentation.html#SWIG_chosen_unignore

I got class
```
namespace testing {
     class Star {
        public:
        Star() = default;
        ~Star() = default;
        void shine() {};
    };
}
```
this code from documentation work as long as `class Star` is outside of the `namespace testing`.
Now with testing I'm trying to use syntax like this:

```
// First attempt
%ignore ""; // Ignore everything
%rename("%s") testing::Star;
%rename("%s") testing::Star::Star;
%rename("%s") testing::Star::~Star;
%rename("%s") testing::Star::shine; // named method

// Second attempt
namespace testing {
  %ignore ""; // Ignore everything
  %rename("%s") Star;
  %rename("%s") Star::Star;
  %rename("%s") Star::~Star;
  %rename("%s") Star::shine; // named method
}
```
In both examples I'm not able to rename/unignore class Star and its methods, they are skipped. 
Should I use different syntax ? How to achieve that with classes nested in namespace ?

**Comment by ojwb** [comment]
You need to unignore the namespace as well.  You linked to a version of the manual that is five years old - if you look at the latest version of that manual section at https://swig.org/Doc4.2/SWIGDocumentation.html#SWIG_chosen_unignore it now notes:

> If <tt>Star</tt> was in the <tt>Galaxy</tt> namespace, you would need
to unignore the namespace, too, and add the namespace to all the
renames:
> `%rename("%s") Galaxy;`
> `%rename("%s") Galaxy::Star;`
> `%rename("%s") Galaxy::Star::Star;`
>  `...`

(See also #193.)
