### ISSUE TITLE
size_t changed from long to int between 4.2.1 and 4.2.0

### ISSUE THREAD

**Issue by christophe-calmejane** [swig/swig#2926]
Hi,

I'm trying to update a project from SWIG 4.2.0 to 4.2.1 and noticed a few differences.

Take this sample:
```swig
%module bug

%typemap(out, optimal="1") SWIGTYPE
%{
	$result = new $1_ltype($1);
%}

%inline %{
  class Test final
  {
    public:
      void set(size_t const v) noexcept
      {
        _v = v;
      }
      size_t get() const noexcept
      {
        return _v;
      }
    private:
      size_t _v{};
  };
%}
```

and generate csharp bindings.

This is 4.2.0:
```c++
SWIGEXPORT void SWIGSTDCALL CSharp_Test_set(void * jarg1, unsigned long jarg2) {
  Test *arg1 = (Test *) 0 ;
  size_t arg2 ;
  
  arg1 = (Test *)jarg1; 
  arg2 = (size_t)jarg2; 
  (arg1)->set(arg2);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_Test_get(void * jarg1) {
  unsigned long jresult ;
  Test *arg1 = (Test *) 0 ;
  size_t result;
  
  arg1 = (Test *)jarg1; 
  result = ((Test const *)arg1)->get();
  jresult = (unsigned long)result; 
  return jresult;
}
```

and this is 4.2.1:
```c++
SWIGEXPORT void SWIGSTDCALL CSharp_Test_set(void * jarg1, unsigned int jarg2) {
  Test *arg1 = (Test *) 0 ;
  size_t arg2 ;
  
  arg1 = (Test *)jarg1; 
  arg2 = (size_t)jarg2; 
  (arg1)->set(arg2);
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Test_get(void * jarg1) {
  unsigned int jresult ;
  Test *arg1 = (Test *) 0 ;
  size_t result;
  
  arg1 = (Test *)jarg1; 
  result = ((Test const *)arg1)->get();
  jresult = (unsigned int)result; 
  return jresult;
}
```

Notice the change from long to int when mapping the size_t type.

**Comment by wsfulton** [comment]
swig-4.2.0 and swig-4.2.1 both generate `unsigned int`. I think you perhaps are trying to upgrade swig-4.1.1 to swig-4.2.1 as swig-4.1.1 generates `unsigned long`.

Please see fb91d1fa25ba00f93b9870d84ec3cbc0739650d7 including the new documentation. You probably don't want to map to C type `unsigned long` as it is not as portable as mapping to `unsigned int` or `unsigned long long`. Solutions are outlined in the new documentation, see https://swig.org/Doc4.2/CSharp.html#CSharp_primitive_types.

**Comment by christophe-calmejane** [comment]
Thanks for the link to the new documentation, I was not aware of this modification.
My previous generated C# files say
```
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
```
So it's definitely not 4.1.1. But it's not 4.2.0 either for sure, since a version I built myself to include my #2650 fix which was not released yet and absolutely required for my projects (among for other changes that are not required anymore). Anyways, it doesn't really matter, what's important is the new version.

Regarding it, isn't it possible to have SWIG autodetect the arch and choose itself if size_t is 4 or 8 bytes?

**Comment by wsfulton** [comment]
A tagged release or a git sha from the official master branch would be best to identify versions going forwards.

Yes, SWIG aims to generate portable code, not platform specific code. In this case, `size_t` cannot be optimal for both 32-bit and 64-bit platforms, hence you have a choice as to treat `size_t` as 32-bit or 64-bit.

**Comment by christophe-calmejane** [comment]
> A tagged release or a git sha from the official master branch would be best to identify versions going forwards.
 
Yes, I was mislead by the fact you immediately change the version number to the next final release as soon as one is released. My projects use the same approach but use the last version digit for "beta" version (until the final build is ready) and/or append a tag to the build (commitID usually) that is reflected in the getVersion command.
Anyway, I need to use a custom version once again since I need to grab the last commit you pushed yesterday fixing the constexpr friend error.
Thanks for the support.
