### ISSUE TITLE
Overloaded constexpr friend functions error

### ISSUE THREAD

**Issue by christophe-calmejane** [swig/swig#2927]
Hi,

I've a project that used to define some function overload which used to compile and work fine with swig 4.2.0. It no longer compiles with swig 4.2.1 (C#).

Take the following example:
```swig
%module bug

%rename("isEqual") operator==(A const& lhs, A const& rhs) noexcept;
%rename("isEqual") operator==(B const& lhs, B const& rhs) noexcept;

%inline %{
  class A final
  {
    public:
      A(int const v) noexcept
        : _v(v)
      {
      }

      constexpr friend bool operator==(A const& lhs, A const& rhs) noexcept
      {
        return lhs._v == rhs._v;
      }
    private:
      int _v{};
  };
  class B final
  {
    public:
      B(int const v) noexcept
        : _v(v)
      {
      }

      constexpr friend bool operator==(B const& lhs, B const& rhs) noexcept
      {
        return lhs._v == rhs._v;
      }
    private:
      int _v{};
  };
%}
```

Swig 4.2.0 correctly generates this:
```c++
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_isEqual__SWIG_0(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  A *arg1 = 0 ;
  A *arg2 = 0 ;
  bool result;
  
  arg1 = (A *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "A const & is null", 0);
    return 0;
  } 
  arg2 = (A *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "A const & is null", 0);
    return 0;
  } 
  result = (bool)operator ==((A const &)*arg1,(A const &)*arg2);
  jresult = result; 
  return jresult;
}
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_isEqual__SWIG_1(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  B *arg1 = 0 ;
  B *arg2 = 0 ;
  bool result;
  
  arg1 = (B *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "B const & is null", 0);
    return 0;
  } 
  arg2 = (B *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "B const & is null", 0);
    return 0;
  } 
  result = (bool)operator ==((B const &)*arg1,(B const &)*arg2);
  jresult = result; 
  return jresult;
}
```

But swig 4.2.1 yell this error:
```
file.i:33: Error: 'isEqual' is multiply defined in the generated target language module in scope 'bugPINVOKE'.
file.i:18: Error: Previous declaration of 'isEqual'
```

The C# language supports function overloading, is there a reason why this is no longer compiling? It would be a pain to update the interface files everywhere I have this, and I don't even talk about all the users of my library that call `isEqual` in many many places.

Thanks.

**Comment by wsfulton** [comment]
Please check the versions you are using. This is a syntax error in swig-4.1.1 and earlier:
```swig
      constexpr friend bool operator==(A const& lhs, A const& rhs) noexcept
```
and swig-4.2.0 and swig-4.2.1 give the `multiply defined` Error. The bug is handling `constexpr friend`, it works as expected if `constexpr` is dropped. I'll look at a fix next.

**Comment by ojwb** [comment]
@wsfulton I suspect you had the same thought already, but just in case not there are at least a couple of places that check for `storage` being exactly `friend` rather than containing `friend` which seem likely to be the cause of this (and probably other problems with handling `constexpr friend`):

```
$ git grep 'Checkattr(.*"storage", "friend"'
Source/CParse/parser.y:    int isfriend = inclass && Checkattr(n, "storage", "friend");
Source/Swig/symbol.c:  } else if (!Checkattr(n, "storage", "friend") && !Checkattr(c, "storage", "friend")) {
```

Most places use `Strstr(Getattr(n, "storage"), "friend") == NULL` or similar, and I think these should too.

There may also be places which read the attribute into a variable and then test if it's exactly "friend" - I didn't spot any with a quick grep, but these are harder to grep for.

**Comment by wsfulton** [comment]
@ojwb, yes exactly, I think I've got them all now.
