### ISSUE TITLE
header conflict: TRUE/FALSE in  handy.h from perl5 and  javaprims.h from gcj

### ISSUE THREAD

**Issue by pooryorick** [swig/swig#293]
Building swig-3.0.2, "make check" resulted in this error:

```
checking Examples/perl5/java
example_wrap.cxx: In function 'int SWIG_AsCharPtrAndSize(SV*, char**, size_t*,  int*)':
example_wrap.cxx:1747: error: 'TRUE' was not declared in this scope
example_wrap.cxx: In function 'void _wrap_JvNewStringLatin1(PerlInterpreter*,
CV*)':
example_wrap.cxx:2147: error: 'FALSE' was not declared in this scope
example_wrap.cxx:2149: error: 'FALSE' was not declared in this scope
example_wrap.cxx: In function 'void _wrap_new_Example(PerlInterpreter*, CV*)':
example_wrap.cxx:2562: error: 'FALSE' was not declared in this scope
example_wrap.cxx:2564: error: 'FALSE' was not declared in this scope
example_wrap.cxx: In function 'void _wrap_Example_Add(PerlInterpreter*, CV*)':
example_wrap.cxx:2936: error: 'FALSE' was not declared in this scope
example_wrap.cxx:2938: error: 'FALSE' was not declared in this scope
example_wrap.cxx:2940: error: 'FALSE' was not declared in this scope
example_wrap.cxx:2942: error: 'FALSE' was not declared in this scope

../../Makefile:243: recipe for target 'perl5_cpp' failed
```

This is caused by a hack in gcc's gcj/javaprims.h, where TRUE and FALSE are
undefined in order to avoid a header conflict on Digital UNIX.  See
https://gcc.gnu.org/ml/java/2006-05/msg00123.html and
https://gcc.gnu.org/ml/java-patches/1999-q3/msg00110.html.

The proper fix is probably in gcc's court, but in the meantime, perhaps swig
should try to work around it somehow.

**Comment by ojwb** [comment]
Why are you including a Java-specific SWIG file when using SWIG/Perl?

**Comment by wsfulton** [comment]
This is one of the examples shipped with SWIG that tests Perl interaction with Java via CNI. We don't normally test these as we don't run tests with CNI installed on Travis.

**Comment by ojwb** [comment]
Wow, funky.

It looks like this is no longer the case with more recent versions of GCC (I checked 6.2.0), but maybe it is still worth addressing.  The patch above does assume the values of `TRUE` and `FALSE` which Perl uses won't change, but that seems a pretty safe assumption.  I'm not seeing a better way off the top of my head.

**Comment by ojwb** [comment]
GCJ was removed completely in GCC 7, and this example was removed by 5a9422d98003e47b4c01381f344646fca9a26d48 over 4 years ago, so this issue can be closed.
