### ISSUE TITLE
Running javascript test suite twice in a row fails due to "preproc_include_f withspace.h"

### ISSUE THREAD

**Issue by vadz** [swig/swig#2930]
The deps file created by node-gyp for the files with spaces in them is corrupt as can be seen by running

```console
$ make -C Examples/test-suite/javascript preproc_include.ctest
```

twice in a row: it succeeds the first time but fails the second one with

```
Release/.deps/./Release/obj.target/preproc_include/../preproc_include_wrap.o.d:129: *** missing separator.  Stop
make: *** [Makefile:133: preproc_include.ctest] Error 1
```

because the end of this file looks like this:

```
$ tail -n7 Examples/test-suite/javascript/preproc_include/build/Release/.deps/Release/obj.target/preproc_include_wrap.o.d
../../../../../../../../src/3rdparty/swig/Examples/test-suite/preproc_include_a.h:
../../../../../../../../src/3rdparty/swig/Examples/test-suite/preproc_include_b.h:
../../../../../../../../src/3rdparty/swig/Examples/test-suite/preproc_include_c.h:
../../../../../../../../src/3rdparty/swig/Examples/test-suite/preproc_include_f:
withspace.h:
\:
../../../../../../../../src/3rdparty/swig/Examples/test-suite/preproc_include_g.h:
```

which is clearly wrong.

I don't know whose fault it is (FWIW I'm using node-gyp@10.0.1), but this is rather inconvenient.

Workaround is to manually delete the `Examples/test-suite/javascript/preproc_include/build/Release/.deps/Release/obj.target/preproc_include_wrap.o.d` file before rerunning the test suite but it's annoying.

**Comment by ojwb** [comment]
Interestingly I don't get a failure - your `tail` command still shows slightly broken dependencies, but the file format is at least valid so no error:

```
/usr/include/nodejs/src/node_version.h:
../../../preproc_include_a.h:
../../../preproc_include_b.h:
../../../preproc_include_c.h:
../../../preproc_include_f:
withspace.h:
../../../preproc_include_g.h:
```

I'm using Debian unstable and its node-gyp 9.3.0-3 and gcc 13.2.0 packages.  I tried forcing older GCC and clang versions and the generated dependencies seem the same, which suggests to me that it isn't GCC generating these dependencies.  I did get some warnings about unsupported `-W` options so it does seem I successfully forced a different compiler to be used.

Digging a bit it looks like there's a sed hammer applied to the generated dependencies by `preproc_include/build/Makefile` which doesn't account for filenames containing whitespace.  I think this file must be generated by node-gyp.  I guess it got improved a bit since the version you're using.

I think all we can really do is add a workaround (e.g. `rm -f` that file before running the testsuite), or just mark this one testcase not to be run for node.

**Comment by vadz** [comment]
Thanks for testing! I admit I didn't look into the details of how node-gyp works, but yes, looking at this `Makefile` it does indeed seem to be broken for the filenames with spaces. The sad thing is that my version of node-gyp (10.0.1) is _newer_ than yours, so it looks like it regressed instead of being improved. I guess I could try fixing this myself, but I'd prefer to just remove this file before building this test, if it's acceptable.

The problem is that I don't see any non-ugly way to do it, I can only think of some very ad hoc hacks. Would you have any idea how could we force this, by chance? If not, I'll try to propose at least something...

I think this test is worth keeping, however, as it does test something which seems to work right now, even if it's hopefully a very rare case.

**Comment by vadz** [comment]
> > it looks like it regressed instead of being improved.
> 
> One thing I think may be different is I'm testing in-tree but it looks like you may be testing out-of-tree.

Yes, indeed, I never build in-tree and this is the difference, thanks.

> My best immediate idea (which doesn't seem great) is to stick something in `GYP_CFLAGS` which deletes the file:

Wow, I didn't think at all of doing it like this but this indeed works, thanks! I won't say it's great, but it's smaller than my idea with overriding `preproc_include.ctest` target entirely and so better, IMO.

> Faking up your generated output I get a failure and this patch resolves it.

I can confirm that applying this patch solves the problem.
 
> > I think this test is worth keeping, however, as it does test something which seems to work right now, even if it's hopefully a very rare case.
> 
> It's a useful regression test, but it is aiming to test SWIG's preprocessor (e.g that it handles spaces in header names) which is generic code so excluding it for a single target language seems reasonable to me.

Yes, I agree, sorry for not thinking this through originally.

So both excluding it from JS and applying your hack seem acceptable to me. I'll let @wsfulton choose which one is preferable (and, of course, I can make a PR for either of them, if necessary).

Thanks again!

**Comment by wsfulton** [comment]
> `+  preproc_include.ctest: GYP_CFLAGS = $(shell rm -f preproc_include/build/Release/.deps/Release/obj.target/preproc_include_wrap.o.d > /dev/null)`

I am puzzled as to how this fixes it as GYP_CFLAGS will be empty as rm does not output anything. If the idea is to just delete a file, then I don't see the link with GYP_CFLAGS.

Anyway, skipping the test just for Javascript is fine with a comment as to why. However, I prefer skipped tests to be implemented in the .i file in order to minimise build system witchcraft. I suggest splitting the test into two with the withspace tests in a separate test that is ignored by javascript with a `#if defined SWIGJAVASCRIPT`. I hate spaces in files, they should be banned!

**Comment by vadz** [comment]
The idea is indeed to just delete the file, but this nice hack only does it before making `preproc_include.ctest` instead of doing it always.

Anyhow, we could split the test as you propose, but why is it necessary if we're going to use `#ifndef SWIGJAVASCRIPT` anyhow?

FWIW this:

```diff
diff --git a/Examples/test-suite/javascript/preproc_include_runme.js b/Examples/test-suite/javascript/preproc_include_runme.js
index 5ec72b842..090fc27bc 100644
--- a/Examples/test-suite/javascript/preproc_include_runme.js
+++ b/Examples/test-suite/javascript/preproc_include_runme.js
@@ -14,10 +14,3 @@ if (preproc_include.multiply40(10) != 400)
 
 if (preproc_include.multiply50(10) != 500)
   throw "RuntimeError";
-
-if (preproc_include.multiply60(10) != 600)
-  throw "RuntimeError";
-
-if (preproc_include.multiply70(10) != 700)
-  throw "RuntimeError";
-
diff --git a/Examples/test-suite/preproc_include.i b/Examples/test-suite/preproc_include.i
index 9df3b5f63..3fa4f1310 100644
--- a/Examples/test-suite/preproc_include.i
+++ b/Examples/test-suite/preproc_include.i
@@ -24,6 +24,7 @@ int multiply50(int a) { return a*50; }
 
 %include INCLUDE_E
 
+#ifndef SWIGJAVASCRIPT
 %inline %{
 #define INCLUDE_F /*comments*/ "preproc_include_f withspace.h"/*testing*/
 #include INCLUDE_F
@@ -34,6 +35,7 @@ int multiply50(int a) { return a*50; }
 int multiply60(int a) { return a*60; }
 int multiply70(int a) { return a*70; }
 %}
+#endif // !SWIGJAVASCRIPT
 
 %define nested_include_1(HEADER)
 %include <HEADER>
```

is enough to solve the problem for me too, do you have a problem with just applying this patch?

**Comment by ojwb** [comment]
> is enough to solve the problem for me too, do you have a problem with just applying this patch?

LGTM, except it could be more targetted as this should work for Javascript other than node (so check for e.g. `BUILDING_NODE_EXTENSION` instead of `SWIGJAVASCRIPT`) and we really should note in a comment why we're skipping this.

**Comment by wsfulton** [comment]
Yup, that patch plus a refactor to only exclude the withspace.h testing works too. So move
```
#include /*oooo*/"preproc_include_g.h"/*ahhh*/
```
out of the excluded block.

**Comment by vadz** [comment]
I've submitted the link PR with the simplest possible change, please let me know if anything more/else is needed.
