### ISSUE TITLE
Ruby:  Read-only variables get a mystery null pointer type

### ISSUE THREAD

**Issue by gsteemso** [swig/swig#2939]
In attempting to use Swig with Ruby, a null pointer with the apparently nonexistent pointer type "rb_gvar_setter_t" is created when a read-only variable is wrapped. This blows up as soon as the compiler hits it because the type isn't declared anywhere, at least not that I can find, and I say that after having run the entire unpacked tarball through "grep".

The offending code is on line 2187 of the Swig source file "Source/Modules/ruby.cxx".

The intent behind the type name is obvious, but whatever was meant to go with it clearly didn't happen. Does anyone have any idea what exactly this was supposed to achieve, so it can be fixed?

**Comment by ojwb** [comment]
It's defined in the Ruby headers:

```
/usr/include/ruby-3.2.0/ruby/internal/variable.h:typedef void  rb_gvar_setter_t(VALUE val, ID id, VALUE *data);
```

Seems to be available after `#include <ruby.h>`:

```
$ printf '%s\n' '#include <ruby.h>' 'rb_gvar_setter_t *p;'|gcc `pkg-config --cflags ruby-3.2` -xc -c -
$
```

**Comment by gsteemso** [comment]
false alarm.  Turns out I was accidentally running too old of a Ruby (as opposed to the merely outdated one I thought I was running) and that definition simply hadn't been invented yet.  Marking this closed.
