### ISSUE TITLE
Keyword detection in JS is overeager

### ISSUE THREAD

**Issue by vadz** [swig/swig#2940]
When using JS backend (I'm using it with v8 emitter but I think it's the same for all the others), any variables using one of the names from `Lib/javascriptkw.swg` get renamed, but this seems wrong because keywords can be used as property names in JS and so there is no problem with using them for at least the member variables (but actually it looks like keywords can also be used for the function names too, as they're properties of the module object).

In particular, as a side effect of the merge of #2545, `yield` was added to the list of keywords and this broke previously working wrappers as expressions like `something.yield` don't work any more because it got renamed to `_yield`.

I'd like to fix this but I'm not sure how to do it, as `need_name_warning()` can't be customized per language and is called at parse time (via `Swig_name_make()`, `make_name()` and `add_symbols()` finally called by the parser itself when handling `c_declaration`). Any idea?

Trivial example reproducing the problem:

```
%module member

%inline {
struct MyStruct {
  double yield = 0.2;
};
}
```

**Comment by ojwb** [comment]
Take a look at `Lib/php/phpkw.swg` which handles keywords which only matter in certain contexts, e.g.:

```
/* Keyword, except ok as a function */
#define PHPKW_ok_as_function(x) %keywordwarn("'" `x` "' is a PHP keyword, renaming to 'c_" `x` "'",%$not %$isfunction,sourcefmt="%(lower)s",rename="c_%s") `x`
```

**Comment by vadz** [comment]
> Take a look at `Lib/php/phpkw.swg` which handles keywords which only matter in certain contexts

Thanks, it indeed was as simple as this!
