### ISSUE TITLE
Windows: Module use of python310.dll conflicts with this version of Python.

### ISSUE THREAD

**Issue by johnfea** [swig/swig#2946]
In both Linux and OSX I'm able to link swig wrapper code without linking against python shared library, in linux by just omitting -lpython and in OSX by adding parameters "-flat_namespace -undefined suppress" to ld. This works at runtime running from different versions of python.

However, in Windows I can't build swig wrapper dll without linking against python dll, otherwise I get undefined reference to `__imp_PyExc_TypeError' type linker errors.

At runtime this results in: "Module use of python310.dll conflicts with this version of Python." error when running from incompatible version of python, such as 311.

Is there a way to fix this issue in Windows? Compiler is x86_64-w64-mingw32-g++.

**Comment by vadz** [comment]
You need to use the stable Python ABI, then you can link with version-independent DLL. See `Py_LIMITED_API` in the docs.

**Comment by johnfea** [comment]
Thank you!
