### ISSUE TITLE
Error while compiling. No viable conversion from SwigValueWrapper

### ISSUE THREAD

**Issue by david-metrica** [swig/swig#2953]
We needed to implement a callback from c++. This callback is passed as a std::function to a method.
I found an answer from Flexo in StackOverflow that provides a std_function.i to solve this problem:
https://stackoverflow.com/a/32668302/22752295

My .i file contains the following lines:
```
%include "std_function.i"
%std_function(OnStart, void, int64_t);
```

Everything seems fine while generating the code, however, when I try to compile this from Android Studio, I get the following error:
` **error: no viable conversion from 'SwigValueWrapper<std::function<void (long long)>>' to 'base::Util::OnStart' (aka 'function<void (long)>').**`

If I take a look at the generated code, it seems like SWIG is generating a SwigValueWrapper.
`_SwigValueWrapper< std::function< void (long long) > > arg2 ;_`
Everything seems to compile, including setting the actual function to this wrapper:
`  arg2 = *argp2; `
However, this line is the one failing:
`  (arg1)->set_callback(arg2);`

It seems like there is no possible conversion from **SwigValueWrapper<std::function<void (long long)>>** to **std::function<void (long long)**.
Is there a way to disable the use of SwigValueWrapper or prevent this error from happening?

**Comment by ojwb** [comment]
There's `%feature("novaluewrapper")` (see manual for details).

If that's not enough to make it work, then since this `std_function.i` isn't part of SWIG I'd suggest talking to flexo.

**Comment by david-metrica** [comment]
I tried %feature("novaluewrapper") but I couldn't get it to work for this example.

Do you know how it would be applied in this case?

StackOverflow doesn't allow sending private messages and I can't comment on that post unless I have 50 reputation.
As far as I know, I have no way of contacting flexo. I searched for other profiles he might had but I wasn't able to find any information.
