### ISSUE TITLE
Support  Java 21

### ISSUE THREAD

**Issue by erezgeva** [swig/swig#2963]
Hi,

As we can test with "OpenJDK 64-Bit Server VM Temurin-21.0.3+9" on `windows.yml`.

It seems we need to upgrade out list implementation.
Attached a copy of the errors received during the tests.
[13_Test.txt](https://github.com/user-attachments/files/16267210/13_Test.txt)

**Comment by erezgeva** [comment]
> Closing as duplicate of #2767.
> 
> Windows testing is slower than on Linux, so generally we should continue to keep the large matrix of version tests on Linux rather than Windows.

You are right, #2767 describe the same error.
Seems like many report the same from different directions :-)

I do not insist on windows.
Personally, I prefer Linux.
That is why, I do not have Windows machine to test on :-)

**Comment by wsfulton** [comment]
Java 21 now working with recent commits, in particular with #3156 resolving the errors initially reported here.

**Comment by erezgeva** [comment]
Thanks @wsfulton.
Just a small question.
Where can we find a Java 21 test?
I do not see Java version on Linux tests.

**Comment by erezgeva** [comment]
Just run a test with Windows Java 21
https://github.com/erezgeva/swig/tree/refs/heads/win_java21
And fail.
https://github.com/erezgeva/swig/actions/runs/14266408154/job/39989188931
Same error:

> checking java testcase stl_no_default_constructor
> .\ListNoDefaultCtor.java:221: error: removeLast() in ListNoDefaultCtor cannot implement removeLast() in List
>   public void removeLast() {
>               ^
>   return type void is not compatible with NoDefaultCtor
>   where E is a type-variable:
>     E extends Object declared in interface List

**Comment by wsfulton** [comment]
https://github.com/swig/swig/actions/runs/14238060864/job/39901378991 is the latest master build using JDK 21. Please use that. I added a CI Windows test in the end as it was easy to find in our current set of CI machines.

**Comment by erezgeva** [comment]
Cool, Thanks @wsfulton -:)
I probably run the test before the fix was committed.
