### ISSUE TITLE
std_complex.i triggers new template warning

### ISSUE THREAD

**Issue by ojwb** [swig/swig#2965]
E.g.:

```
checking python testcase complextest (with run test)
../../../Lib/python/std_complex.i:14: Warning 330: Template forward class instantiation 'std::complex< double >' with name '__dummy_0__' is ineffective.
../../../Lib/python/std_complex.i:15: Warning 330: Template forward class instantiation 'std::complex< float >' with name '__dummy_1__' is ineffective.
```

`git bisect` says this was introduced by your recent change @wsfulton:

```
commit 8c8e27d246ed178495661a898aeffadfd9e5f9d9 (HEAD)
Author: William S Fulton <wsf@fultondesigns.co.uk>
Date:   Sat Jun 29 17:20:07 2024 +0100

    Add warning for ineffective %template instantiations
    
    on forward template class declarations. A full template class definition is
    required in order to wrap a template class as a proxy class.
    
    Also tidyup handling of classforward code (no observable changes in
    test-suite).

 Doc/Manual/Warnings.html                               |  1 +
 Examples/test-suite/errors/cpp_invalid_template.i      |  5 +++++
 Examples/test-suite/errors/cpp_invalid_template.stderr |  1 +
 Examples/test-suite/errors/cpp_template_forward.i      | 20 ++++++++++++++++++++
 Examples/test-suite/errors/cpp_template_forward.stderr |  4 ++++
 Examples/test-suite/template_specialization.i          |  4 +++-
 Source/CParse/parser.y                                 |  9 ++++++++-
 Source/CParse/templ.c                                  | 13 +++++++------
 Source/Include/swigwarn.h                              |  1 +
 9 files changed, 50 insertions(+), 8 deletions(-)
 create mode 100644 Examples/test-suite/errors/cpp_template_forward.i
 create mode 100644 Examples/test-suite/errors/cpp_template_forward.stderr
```

Not sure if this is actually an ineffective %template in our own code, or if the warning is mistriggering.

**Comment by ojwb** [comment]
Some other testcases trigger it directly:

```
checking python testcase template_nested
./../template_nested.i:79: Warning 330: Template forward class instantiation 'ns::OuterClass::Inner1< double >' with name 'T_OuterClassInner1Double' is ineffective.
./../template_nested.i:120: Warning 330: Template forward class instantiation 'ns::OuterClass::Inner2< double >' with name 'T_OuterClassInner2Double' is ineffective.
./../template_nested.i:127: Warning 330: Template forward class instantiation 'ns::OuterClass::Inner1< int >' with name 'T_OuterClassInner1Int' is ineffective.
./../template_nested.i:128: Warning 330: Template forward class instantiation 'ns::OuterClass::Inner2< ns::NormalClass >' with name 'T_OuterClassInner2NormalClass' is ineffective.
./../template_nested.i:129: Warning 330: Template forward class instantiation 'ns::OuterClass::Inner2< int >' with name 'T_OuterClassInner2Int' is ineffective.
```

and:

```
checking python testcase template_nested_typemaps
./../template_nested_typemaps.i:30: Warning 330: Template forward class instantiation 'Breeze::Typemap< int >' with name '__dummy_0__' is ineffective.
./../template_nested_typemaps.i:37: Warning 330: Template forward class instantiation 'Breeze::TypemapShort< short >' with name '__dummy_1__' is ineffective.
```

**Comment by vadz** [comment]
This seems like a real problem, at least with the warning, because looking at the last example (`template_nested_typemaps`), `%template` uses the already defined C++ template, so it's not about forward declarations at all.

In any case, this is really annoying. FWIW I recommend running the test suite with the recently added `ECHO_PROGRESS=:` on make command line to allow seeing problems like this, otherwise it's too easy to not notice them.

**Comment by wsfulton** [comment]
When I developed this I looked at all the warnings, but not every single target language - it's warning free for Java. I'm looking at this one now.

**Comment by ojwb** [comment]
As well as Python, we're also getting warning #330 for:

* D: https://github.com/swig/swig/actions/runs/9985419098/job/27596233477#step:8:471
* Go: https://github.com/swig/swig/actions/runs/9985419098/job/27596233849#step:8:477
* Javascript: https://github.com/swig/swig/actions/runs/9985419098/job/27596235250#step:8:481
* Lua: https://github.com/swig/swig/actions/runs/9985419098/job/27596235745#step:8:480
* mzscheme: https://github.com/swig/swig/actions/runs/9985419098/job/27596248058#step:8:604
* Ocaml: https://github.com/swig/swig/actions/runs/9985419098/job/27596248175#step:8:477
* Octave: https://github.com/swig/swig/actions/runs/9985419098/job/27596236183#step:8:483
* Perl: https://github.com/swig/swig/actions/runs/9985419098/job/27596236330#step:8:480
* PHP: https://github.com/swig/swig/actions/runs/9985419098/job/27596236899#step:8:487
* Ruby: https://github.com/swig/swig/actions/runs/9985419098/job/27596240262#step:8:504
* Scilab: https://github.com/swig/swig/actions/runs/9985419098/job/27596240891#step:8:480
* Tcl: https://github.com/swig/swig/actions/runs/9985419098/job/27596241020#step:8:477

**Comment by ojwb** [comment]
More of a cosmetic problem, but it'd also be better if we didn't report the `with name '__dummy_0__'` part in the `%template()` case as the name `__dummy_0__` just seems to be made up by SWIG, but maybe that's hard to avoid.

I guess it could skip it if the name matches `/^__dummy_\d+__$/` or similar if there's not a better way to detect since that's a name reserved for the implementation in C++ so shouldn't appear in user code.
