### ISSUE TITLE
java class names

### ISSUE THREAD

**Issue by mwolfthal** [swig/swig#2978]
My C++ class Toolkit becomes a Java class toolkit. Is there a way to force generated Java classes to begin with uppercase?

**Comment by supsm** [comment]
You can use [%rename](https://www.swig.org/Doc4.2/SWIGDocumentation.html#SWIG_advanced_renaming)

**Comment by mwolfthal** [comment]
I don't see any documentation for using %rename for classes, only methods.

**Comment by supsm** [comment]
There is an example of that in [5.4.7.5](https://www.swig.org/Doc4.2/SWIGDocumentation.html#SWIG_chosen_unignore)
```swig
// Unignore chosen class 'Star'
%rename("%s") Star;
```
Additionally (although not explicitly documented), %interface_impl and %interface_custom internally rely on %rename to rename classes (see [swiginterface.i](https://github.com/swig/swig/blob/74a8aafac0378a2231590a519d4d89f9c4dfb7fb/Lib/java/swiginterface.i#L64))

**Comment by mwolfthal** [comment]
I don't see how to make it work yet, but in the meantime I also don't get why a C++ class "Toolkit" has been lowercased to begin with, especially since in java the standard is that class names are capitalized.

**Comment by mwolfthal** [comment]
OK getting there. Is there a way to control the names of the output java class files?

**Comment by supsm** [comment]
> I also don't get why a C++ class "Toolkit" has been lowercased to begin with, especially since in java the standard is that class names are capitalized.

That is indeed weird, SWIG is supposed to preserve casing

> Is there a way to control the names of the output java class files?

The names of the java proxy class files are the same as the class name, which is required in java. The main module class (for globals) and the JNI class are determined by the module name specified with `%module`. You can also customize the name of the JNI class with [jniclassname](https://www.swig.org/Doc4.2/SWIGDocumentation.html#Java_imclass):
```
%module(jniclassname="name") modulename
```

**Comment by ojwb** [comment]
SWIG doesn't lowercase class names by default - e.g. see the `class` example:

```
cd Examples/java/class
make
```

This generates e.g. `Shape.java` with `public class Shape {`, etc.

I suspect you have set up a pattern rename aimed at renaming methods (or something else) which is affecting your classes too.  If so, you can add a suitable condition such as `%$not %$isclass` to that `%rename`.  If that's not the problem you'll need to provide an example.

**Comment by ojwb** [comment]
No response for a month so assuming resolved.
