### ISSUE TITLE
Pure Java interfaces

### ISSUE THREAD

**Issue by supsm** [swig/swig#2983]
Is it possible to define a java interface without also creating an implementation? Sometimes, an implementation is not necessary, but it seems that there is no option to avoid generating the implementation proxy class.

**Comment by wsfulton** [comment]
Please provide more details of the requirement, bearing in mind that SWIG is a tool to wrap C++ code whereas a pure Java interface in my mind does not involve any C++ and is something that can be written in Java by hand.

Perhaps of relevance: You can add any Java interface to a wrapped Java proxy class using `%typemap(javainterfaces)`.

**Comment by supsm** [comment]
The issue is actually pretty niche now that I think of it. I think what I really want is just some way to define arbitrary java code without needing a c++ class at all to extend.

**Comment by ojwb** [comment]
> I think what I really want is just some way to define arbitrary java code without needing a c++ class at all to extend.

Just put it in its own `.java` file?

**Comment by supsm** [comment]
Hmm, is there some way to make swig do that though? The package or file location may differ

**Comment by wsfulton** [comment]
No, not applicable. If you want a hand-written .java file, then create it and add it to your build system.
