### ISSUE TITLE
More restrictive derived member fails to compile with directors in java

### ISSUE THREAD

**Issue by supsm** [swig/swig#2991]
When a C++ virtual member function has a more restrictive access specifier in a derived (e.g. public in base and protected in derived), and directors are enabled, swig generated java code fails to compile because this is not possible in java.

When directors are disabled, the protected member in the derived class is not wrapped in the proxy class, so there is no issue.

This is another "language feature" issue where some C++ code can simply not be accurately translated into java (also see #2975). For this specific issue, I suggest that proxy class access specifiers are simply "promoted" to the least restrictive access present in parent classes. In the example below, this means `D.func()` in java will be public.

Obviously this solution is not ideal since sometimes APIs want to hide members in derived classes, but I think this is not any worse than the alternative (leaving out the declaration in the derived class) since the method will be inherited on the java side anyways, and virtually dispatched on the C++ side. As such, a warning should be provided along with this access promotion.

Example code:
```swig
%module(directors = "1") test

%feature("director");

%inline
%{
class C
{
public:
	virtual ~C() {}
	virtual void func() {}
};

class D : public C
{
public:
	virtual ~D() {}
protected:
	virtual void func() {}
};
%}
```

Error when compiling java:
```
.\D.java:60: error: func() in D cannot override func() in C
  protected void func() {
                 ^
  attempting to assign weaker access privileges; was public
1 error
```

**Comment by wsfulton** [comment]
I suggest you take a look at https://swig.org/Doc4.2/Java.html#Java_allprotected in the manual.

**Comment by supsm** [comment]
I'm not sure if that is relevant to this issue, `allprotected` appears to only deal with non-virtual protected functions (here we are dealing with virtual functions). The problem is that java does not allow derived classes to make member functions more restrictive. The translation is technically correct, just not valid in java. In the example above, C.java contains
```java
public void func() {
  if (getClass() == C.class) testJNI.C_func(swigCPtr, this); else testJNI.C_funcSwigExplicitC(swigCPtr, this);
}
```
whereas D.java (where D derives from C) contains
```java
protected void func() {
  if (getClass() == D.class) testJNI.D_func(swigCPtr, this); else testJNI.D_funcSwigExplicitD(swigCPtr, this);
}
```
This is invalid in java because `func()` is protected in the derived class but public in the base class.

**Comment by wsfulton** [comment]
I see, this an unfortunate mismatch between C++ and Java. Currently you can deal with this by either:

1. Ignoring the method using %ignore, use:
```swig
%ignore D::func;
```
2. Change the access modifier, in your case, use:
```swig
%feature("java:methodmodifiers") D::func "public"
```

I am not sure the suggested solution of detecting this and making the method public is the best default as it could all too easily change the intended API usage, even if a warning is provided. Ignoring the method with a warning might be marginally better, but we'd then need a new feature to deal with this, which would be no easier to use than option 2 above. An automated way to promote the access will be scuppered by user's other use of the "java:methodmodifiers" feature up the inheritance chain (or at least quite hard to implement correctly) and use of overloaded methods. We have a kind of similar problem for C# and D which require a virtual/override/new keyword on the C++ virtual methods and it is too hard to get always get right. I hope the manual options given above work okay for you.

**Comment by supsm** [comment]
Thank you for the manual workarounds.

I'm not convinced, though, that ignoring is the superior option. On the java side, the public method from the base class will be inherited and visible in the derived class, and invoking it will simply cause the derived class function to be dispatched virtually on the C++ side. Perhaps `@Deprecated` or something similar could be used to discourage use on the java side.

**Comment by wsfulton** [comment]
I think this is quite an obscure problem and will require quite a bit of SWIG development to get this implemented reliably with an auto conversion of protected to public. I propose leaving it as is and I can document these manual fixes for users to choose what to do.

SWIG getting involved in deprecating user's API's is a can of worms and I'm not at all keen on this being a default. Documenting adding `@Deprecated` would be no different to doing this for any other API, so don't know that this is worth documenting as a manual workaround for this problem, but maybe I missed something as it will still require one of the two options to solve as well.
