### ISSUE TITLE
std_filesystem.i doesn't declare std::filesystem

### ISSUE THREAD

**Issue by ma569** [swig/swig#2993]
Hi!

I have defined an alias for a nested namespace and I was wondering if that is supported in swig? Swig docs say that nested namespaces are supported so I'm assuming that it is my lack of knowledge of swig. Here is a minimum example which explains my problem:

```
// example.h
#pragma once
#include <filesystem>

namespace fs = std::filesystem; // doesn't work
namespace foo {
  namespace bar {
    namespace baz {
    }
  }
}

namespace tt = foo::bar::baz; // works

struct Coordinate {
  double latitude, longitude;
};

```
```
// example.i
%module Example

%include "std_filesystem.i"

%{
#include "example.h"
%}

%include "include/example.h"
```

When I compile this, I get the following error:

```
Error: Unknown namespace 'std::filesystem'
```

I'm using swig 4.2 and C++20. I'm assuming that swig can't find std::filesystem namespace. Thank you in advance

**Comment by ojwb** [comment]
You don't give the SWIG command line, or say what target language this is for but it seems we only have `Lib/python/std_filesystem.i` so presumably it's Python.  However that doesn't seem to actually declare `std::filesystem` for SWIG, which is presumably why SWIG doesn't know about it.

**Comment by ojwb** [comment]
Retitling as the problem doesn't seem to be with aliasing nested namespaces (as `namespace tt = foo::bar::baz; // works` also suggests).

This change makes your example work.  Not sure if we should actually be declaring anything inside the namespace as well.

```
diff --git a/Lib/python/std_filesystem.i b/Lib/python/std_filesystem.i
index ffed417f..f5e9cc52 100644
--- a/Lib/python/std_filesystem.i
+++ b/Lib/python/std_filesystem.i
@@ -8,6 +8,11 @@
 #include <filesystem>
 %}
 
+namespace std {
+  namespace filesystem {
+  }
+}
+
 %fragment("SWIG_std_filesystem", "header") {
 SWIGINTERN PyObject *SWIG_std_filesystem_importPathClass() {
   PyObject *module = PyImport_ImportModule("pathlib");
```

@wsfulton Looks like you've mostly worked on this support.

**Comment by ma569** [comment]
thank you for looking into it. Sorry, I forgot to mention. Yes it is python. Here is the full command. I'm using cmake:
`/usr/local/bin/cmake -E make_directory <workspace>/example/build/CMakeFiles/Example.dir <workspace>/example/build <workspace>/example/build/CMakeFiles/Example.dir
/usr/local/bin/cmake -E touch <workspace>/example/build/CMakeFiles/Example.dir/ExamplePYTHON.stamp
/usr/local/bin/cmake -E env SWIG_LIB=<workspace>/venv/lib/python3.11/site-packages/swig/data/share/swig/4.2.1 <workspace>/venv/bin/swig4.0 -python -outdir <workspace>/example/build -c++ -interface _Example -o <workspace>/example/build/CMakeFiles/Example.dir/ExamplePYTHON_wrap.cxx <workspace>/example/Example.i`
