### ISSUE TITLE
Remove support for specifying SWIG type strings in interface files?

### ISSUE THREAD

**Issue by ojwb** [swig/swig#2998]
`TYPE_RAW` is actually the SWIG-specific "reverse quoted string" syntax, but it looks to have ended up being used in places in the grammar which make no sense, probably partly due to people copying and adapting grammar rules without really understanding them, and maybe partly due to the name being a bit confusing since C++11 (it's nothing to do with C++11 raw strings).

E.g. currently this parses:

```
enum : `WTF?` { XYZZY };
```

GCC and clang (correctly) error on the first backtick.

I'll try to eliminate the entirely bogus uses at least (since they just make the grammar harder to follow), and maybe try to move the uses that are actually needed to more appropriate grammar rules, but I probably won't get to it for a while so opening a ticket as a reminder.

I think we should rename `TYPE_RAW` too, since the `raw` part is confusing since C++11, and the `TYPE_` part was always confusing since it suggests it's like `TYPE_VOID`, `TYPE_BOOL`, `TYPE_INT`, etc which are the parser tokens for `void`, `bool`, `int`, whereas it's actually more like `STRING` and `WSTRING` (tokens for string and wide-string literals).  Maybe `REVERSE_QUOTE_STRING` as that's what the documentation seems to call it:

```
Doc/Devel/scanner.html:SWIG_TOKEN_RSTRING           Reverse quote string (`str`)
```

The user docs cover it, but don't seem to name it.

**Comment by ojwb** [comment]
It seems this is in fact an intended feature - from `Extending.html`:

> If you want to experiment with type encodings, the raw type strings can be inserted into an interface file using backticks <span>``</span> wherever a type is expected.  For instance, here is an extremely perverted example:                                                        
                                                                         
``` 
`p.a(10).p.f(int, p.f(int).int)` foo(int, int (*x)(int));
```

It seems there's no test coverage at all for this feature - I tried removing all instances of `TYPE_RAW` from the grammar and `check-php-test-suite` still passes.

@wsfulton Is this actually a useful feature?  The motivating example in the documentation can be written as a C/C++ declaration, as `Extending.html` even goes on to say:

> This corresponds to the immediately obvious C declaration:

```
(*(*foo(int, int (*)(int)))[10])(int, int (*)(int));
```

Admittedly that's hard to read, but SWIG's type string isn't easy to read either.

**Comment by ojwb** [comment]
Now I realise what this actually is, `TYPE_RAW` seems a less terrible name.

I also spotted the CHANGES entry adding it:

```
8/15/00 : beazley
          Secret developer feature.  Since datatypes are now represented as 
          strings internally, you can bypass limitations of the parser and
          create a wild datatype by simply enclosing the raw string encoding  
          in backticks (``) and sticking it in the interface file anywhere a
          type is expected.  For example, `a(20).a(10).p.f(int,int)`.  This 
          feature is only intended for testing (i.e., you want to see what
          happens to your language module if it gets a reference to a pointer
          to an array of pointers to functions or something). 
          *** SICK HACK ***
```

Some arguments for removal:

* Doesn't seem a useful feature (if you want to test such a type, you can specify it via C/C++ syntax)
* Appears to have no test coverage
* There's potential for a future C++ version to define a standard meaning for backticks, which would probably make it awkward to continue to support this
* If we're ever going to move to using an existing C/C++ parser, we'd either need to drop this feature or modify that parser to support this too
* Exposes the otherwise internal SwigType representation, so we couldn't move to a different representation without breaking this feature

**Comment by wsfulton** [comment]
I don't use this 'secret' feature and don't see a real need for it, so fine by me to remove it.
