### ISSUE TITLE
Java array typemap of type signed char[] cannot be applied to type const char* in swig v4.2.1

### ISSUE THREAD

**Issue by Golden-Wang** [swig/swig#3000]
My use case will have C++ code be compiled with -fsigned-char. I want to typemap char pointer as array of signed char rather than string. I ran into this error when upgrading from an earlier version of swig to the latest v4.2.1. See the example below:
### test.i
```c++
%module test
%include "arrays_java.i"

%apply signed char[] {const char*};

%include test.h

%{
void bar(const char *s) {
    return;
}

int main() {
    const char *foo = "hello world";
    bar(foo);
    return 0;
}
%}
```
### test.h
```c++
void bar(const char*);
```
### Bash Commands
```bash
swig -c++ -java -package com.test -outdir . test.i
g++ -I/opt/jdk1.8.0_212/include -I/opt/jdk1.8.0_212/include/linux test_wrap.cxx
```
### Error
```bash
test_warp.cxx: In function 'void Java_com_test_testJNI_bar(JNIEnv*, jclass, jbyteArray)':
test_wrap.cxx:915:44: error: invalid conversion from 'char**' to 'signed char**' [-fpermissive]
  915 |   if(!SWIG_JavaArrayInSchar(jenv, &jarr1, (char **)&arg1, jarg1)) return ;
```
### Versions
I found v4.2.0 and v4.2.1 both have this error.
This error does not happen in v4.1.1 and earlier versions, where the example given above can be compiled successfully.
I narrowed down the breaking change to commit 7bba06b by @wsfulton .
Please let me know if my use case is valid and any recommended alternatives.

**Comment by bryanhatwood** [comment]
@Golden-Wang I ran into the same issue and found a solution.

Try adding:
```
%include "typemaps.i"
```

and changing your `%apply` to:
```
%apply signed char *INPUT{ const char* };
```
or if you need the byte array to be mutable:
```
%apply signed char *INOUT { const char* };
```

**Comment by wsfulton** [comment]
I'd like to point out that the suggestion from @bryanhatwood is relevant only if your `const char *` is a pointer to a single character, which is not the case for @Golden-Wang's use case which is for full arrays as the arrays_java.i library has been chosen.

**Comment by wsfulton** [comment]
I think the change in 7bba06b should be left as it generally highlights a potentially invalid cast leading to unexpected results. The typemaps can be changed to the previous casts if determined to be safe.

If `-fsigned-char` effectively makes `char` and `unsigned char` the same type, I'd have thought the compiler would not require a cast. Anyway, if `char` arrays can be safely cast to `signed char` arrays, then make the change via typemaps. If you run `swig -E` on your code, you'll be able to find the typemaps after SWIG preprocessing. Copy them and modify with the appropriate casts to override the versions you've applied from arrays_java.i. I've shown the original typemaps from the preprocessed output in comments below and then made the changes for your example:

```swig
%include "arrays_java.i"

%apply signed char[] {const char *};
/*
%typemap(in) signed char[] (jbyte *jarr)
%{  if (!SWIG_JavaArrayInSchar(jenv, &jarr, ($&1_ltype)&$1, $input)) return $null; %}
*/
%typemap(in) const char * (jbyte *jarr)
%{  if (!SWIG_JavaArrayInSchar(jenv, &jarr, (signed char **)&$1, $input)) return $null; %}


/*
%typemap(argout) signed char[ANY], signed char[] 
%{ SWIG_JavaArrayArgoutSchar(jenv, jarr$argnum, ($1_ltype)$1, $input); %}
*/
%typemap(argout) const char * 
%{ SWIG_JavaArrayArgoutSchar(jenv, jarr$argnum, (signed char *)$1, $input); %}


%include test.h
...
```
