### ISSUE TITLE
How can multiple languages share a dynamic library？

### ISSUE THREAD

**Issue by ysx1993** [swig/swig#3003]
I have a C++ SDK project that I want to support both C# and JAVA calls via SWIG, and I'm having a problem with the following error when I put csharp_wrap.cpp and java_wrap.cpp into my project and compile them at the same time:
![image](https://github.com/user-attachments/assets/4eb0cf4a-c538-4fac-90f7-daecdf297bf1)

My intention is to have both CSharp's dynamic libraries(.dll) and Java's packages(.jar) share a single .dll/.so file, I don't want to generate separate .dll files for each language! Is there any way to solve this problem?

Thanks!

**Comment by ysx1993** [comment]
![image](https://github.com/user-attachments/assets/ad1a5c73-646e-437d-9362-69cabd2ecf6f)
![image](https://github.com/user-attachments/assets/7b420df4-7eaa-4d25-b285-9ab0dc270a24)

csharp and java generate callbacks with the same name causing compilation conflicts.

**Comment by ojwb** [comment]
Sorry, this isn't supported.
