### ISSUE TITLE
Parse storage_class more flexibly

### ISSUE THREAD

**Issue by ojwb** [swig/swig#302]
Spun off from issue#284.

Currently in `Source/CParse/parser.y`, the rule for `storage_class` has a hard-coded list of acceptable combinations, but is missing some valid combinations.  

We could add them all, but fundamentally this approach doesn't scale well due to combinatioral explosion.

I propose we parse storage classes like how `type_qualifier` is parsed, with checks for invalid cases (repeated storage class where this isn't valid and other invalid combinations).  This would address the missing cases without having a huge and hard to maintain list, and would also give much better error reporting (rather than the dreaded `Syntax error in input`).

**Comment by ojwb** [comment]
FYI I've resurrected a WIP I started on this some time ago, and it seems to be largely working.  Currently running the python testsuite - so far `li_std_vector_extra` failed, not sure why yet.  I also need to check the reported cases now work, and turn them into automated tests.

**Comment by christophe-calmejane** [comment]
Hi @ojwb , is there a way to get your WIP commits. I'm really blocked by my code base heavily using `constexpr friend bool operator==(...)` that SWIG cannot parse.

I found a workaround by `%define constexpr` before including the c++ header file, but since it disables all constexpr, I'm getting errors elsewhere on some files.

**Comment by ojwb** [comment]
@christophe-calmejane Pushed to https://github.com/ojwb/swig/tree/parse-storage-class-flexibly (branch point is b18b7536).

I should probably tidy this up, add test cases and merge it even if it doesn't solve as many cases as-is as I'd like.  Adding to the 4.2 milestone.

**Comment by ojwb** [comment]
I've force-pushed a cleaned up and rebased version, with some fixes for handling of `friend`.  This fixes two of the linked tickets - assuming CI passes everywhere (I tested PHP, Python and Java locally), I plan to merge this and worry about the others linked tickets as a separate change or changes.

**Comment by ojwb** [comment]
OK, merged.

Several of the remaining linked issues seem to be down to us rigorously segregating "storage_class" (which in SWIG's grammar doesn't actually seem to completely match the definition in the C++ grammar) and "type", whereas they're actually allowed to be intermingled.

This looks like a more involved change and I probably don't have the time or energy to look into it further in the near future.

**Comment by christophe-calmejane** [comment]
@ojwb thanks a lot, I confirm it solves most (if not all, couldn't test everything yet) of my parsing issues! No more need to `#define constexpr` to hack my way around SWIG parser :)

**Comment by christophe-calmejane** [comment]
@ojwb Any chance this `Syntax error in input` message is related to this whole parsing limitations (to your knowledge)?

```c++
class Foo
{
public
  static auto constexpr Bar = "Hello";
};
```

Thanks!

**Comment by ojwb** [comment]
That's #1125.  As I commented there yesterday, I have a fix in progress.

For this example it would not be able to deduce the type currently, but it would at least parse it (then warn and ignore it).  A string literal is fairly easy to deduce the type of, but I think we probably want to have an actual plan for type deduction rather than building a pile of ad-hoc hacks for special cases.

Once it's parsed, I suspect it can at least be wrapped with the same "provide a declaration with explicit type and `%ignore`" trick that works for many `declspec` cases.

**Comment by ojwb** [comment]
Oh actually, #1125 is for `static constexpr auto` and my fix doesn't handle `static auto constexpr`.  The issue with your variant is essentially the same issue as #2143 (it may not seem like it's the same problem, but SWIG handles both `constexpr` and `friend` as "storage classes" and accepts a group of them before the return type, which is what `auto` is here, but C++ doesn't actually segregate as rigidly).
