### ISSUE TITLE
CMake build system can use parser.h generated file from (potentially outdated) previous autoconf builds

### ISSUE THREAD

**Issue by rouault** [swig/swig#3022]
Doing just:
```
touch empty.i
./swig -o empty.cpp -module empty -python empty.i 
```

is broken since commit Sept 13th commit 4d2ba48b755b358df79b12316d5817dd037de347

It results in ``/home/even/install-swig-master/share/swig/4.3.0/swigfragments.swg:11: Error: Syntax error in input(1).``

CC @ojwb

**Comment by rouault** [comment]
hum, actually I only reproduce that using a CMake build, not an autoconf one

**Comment by rouault** [comment]
hum I can't actually reproduce that doing a clean CMake build. The issue arose when I refreshed my git clone from an older master to latest master. I presume ${PROJECT_BINARY_DIR}/Source/CParse/parser.c didn't get regenerated from ${SWIG_SOURCE_DIR}/CParse/parser.y

**Comment by ojwb** [comment]
Not fully regenerating the parser would explain it as that commit removed the `ILLEGAL` token so some of the other tokens would have got different numbers.  Sounds like a bug in the cmake build system.  It has long-known problems such as #2008 which nobody seems interested in fixing.  I'd recommend using the autoconf one.

**Comment by ojwb** [comment]
I think it's probably reasonable to simply not aim to support people switching build system without properly cleaning the tree in between.  The primary use-case for having both seems to be that Microsoft Windows users don't like having to install MSYS2 or similar.

Maybe the autotools system should generate these files in builddir.  The general idea is that srcdir should be able to be read-only, though the generated parser is something that's shipped in release tarballs so for a user building a release srcdir could be read-only (or if it can't, this particular case shouldn't be the problem).

**Comment by ojwb** [comment]
> I think it's probably reasonable to simply not aim to support people switching build system without properly cleaning the tree in between. The primary use-case for having both seems to be that Microsoft Windows users don't like having to install MSYS2 or similar.

Let's do that - it's very much a corner case we have more than enough real bugs to deal with.
