### ISSUE TITLE
 Nested struct not currently supported (ignored)

### ISSUE THREAD

**Issue by ethan256** [swig/swig#3033]
Anonymous structs in union are not supported when using swig to bridge go.

`c/c++` type as follow:
```c
// File: point.h
typedef unsigned int VzColorRGB;

// 3D Point + RGB
typedef union
{
	float fData[4];
	struct
	{
		float		x;
		float		y;
		float		z;
		VzColorRGB  nRGB;
	};
} SVzNLPointXYZRGBA;
```

swig interface file:
```
/* File: point.i */

%module point
%{
#include "point.h"
%}

%include "point.h"
```

swig command:  `swig -c++ -go -intgosize 64 -cgo point.i`

### Warn Message:
**point.h(14) : Warning 312: Nested struct not currently supported (ignored).**

### Generated go code:
```go
type SVzNLPointXYZRGBA interface {
	Swigcptr() uintptr
	SwigIsSVzNLPointXYZRGBA()
	SetFData(arg2 *float32)
	GetFData() (_swig_ret *float32)
}
```

I want to get the values of the structures x, y,z in union, or return the array fData.

### Expect go code: 
```go
type SVzNLPointXYZRGBA interface {
	Swigcptr() uintptr
	SwigIsSVzNLPointXYZRGBA()
	SetFData(arg2 []float32)
	GetFData() (_swig_ret []float32)
}
```

**Comment by ojwb** [comment]
The message is correct and nested struct support hasn't been implemented for Go yet (only for C#, Java and XML).

I don't know if/how you can get fdata wrapped as a Go array, but you should be able to wrap `x`, etc via `%extend`, something like:

```
%extend SVzNLPointXYZRGBA {
    float get_x() { return $self->x; }
}
```
