### ISSUE TITLE
E_STRICT is deprecated in "soon" to be released PHP 8.4

### ISSUE THREAD

**Issue by jpbion** [swig/swig#3037]
https://github.com/php/php-src/blob/php-8.4.0RC1/UPGRADING

Swig uses E_STRICT.

**Comment by ojwb** [comment]
> Swig uses E_STRICT.

It's not used in any PHP code we ship and SWIG doesn't generate PHP code at all any more (the wrapping is now all done via PHP's C API now).

The only reference to `E_STRICT` is in a list of reserved words which SWIG will automatically rename by default when wrapping to try to avoid generating target language code which won't work, and `E_STRICT` still needs to be avoided there:

```
$ php8.4 -r 'define("E_STRICT", 1);'
PHP Warning:  Constant E_STRICT already defined in Command line code on line 1
```

Is something actually failing for you with PHP 8.4?  I tried SWIG's test suite with it recently and everything passed.

**Comment by jpbion** [comment]
Nothing failing. I do notice it’s referenced in Lib/php/phpkw.swg so wanted to let you know.Sent from my iPhoneOn Sep 27, 2024, at 1:04 PM, Olly Betts ***@***.***> wrote:﻿

Swig uses E_STRICT.

It's not used in any PHP code we ship and SWIG doesn't generate PHP code at all any more (the wrapping is now all done via PHP's C API now).
The only reference to E_STRICT is in a list of reserved words which SWIG will automatically rename by default when wrapping to try to avoid generating target language code which won't work, and E_STRICT still needs to be avoided there:
$ php8.4 -r 'define("E_STRICT", 1);'
PHP Warning:  Constant E_STRICT already defined in Command line code on line 1

Is something actually failing for you with PHP 8.4?  I tried SWIG's test suite with it recently and everything passed.

**Comment by ojwb** [comment]
Ok, then there's nothing to do here.
