### ISSUE TITLE
[Ruby] Use of Config::CONFIG in configure does not work anymore with Ruby-2.2

### ISSUE THREAD

**Issue by pierre-labastie** [swig/swig#304]
In 2006 or so, the Config module was renamed to RbConfig, but there was the instruction "Config=RbConfig" in obsolete.rb (+ a warning that Config was obsolete), until Ruby-2.1. With Ruby-2.2, "obsolete.rb" has been suppressed. Yet, the configure script in SWIG still uses Config at some places, which leads to some bad behavior (specifically, RUBYSO=., instead of .so). Because of that, any test with a run test fails (the shared library module is named example., instead of example.so, and is not found by ruby).
Patching configure.ac is easy, unless one wants to keep compatibility with versions of Ruby before 2006 (I think versions 1.6 and below).

**Comment by wsfulton** [comment]
I'm sure we could detect the version of Ruby and then use RbConfig or Config as appropriate in configure.ac. Isn't that what configure.ac is trying to do anyway to do anyway:
```ruby
        # Try Ruby1.9+ first
        RUBYDIR=`($RUBY -rrbconfig -e 'print RbConfig::CONFIG[["rubyhdrdir"]] || $rubyhdrdir') 2>/dev/null`
```
Supporting 1.6 is a nice to have, but I'm not too concerned if it is no longer detected given how old 1.6 is.

**Comment by kkaempf** [comment]
Yes, backwards compatibility is possible but probably not worth the effort. Also all calls in configure.ac already have "-rrbconfig", ruby 1.6 would need "-rconfig" ;-)

**Comment by wsfulton** [comment]
Okey doke, I'll merge this in then. I can't test it against 2.2, but hopefully one of the newer OpenBuild platforms will have 2.2 and then turn on Ruby 2.2 testing.

**Comment by wsfulton** [comment]
Merged, thanks everyone.

**Comment by kkaempf** [comment]
I've tested it with a local Ruby 2.2 installation. ;-)
