### ISSUE TITLE
Question on loading the low-level C++ module with importlib using a custom moduleimport definition

### ISSUE THREAD

**Issue by n0phx** [swig/swig#3043]
I am working on a C++ library, and generated Python 3.7 bindings for it with swig 4.1.0
Based on the online documentation available, I believe I am using a configuration to which the docs refer to as both modules being global (both the pure python wrapper and the generated C++ module also). I am trying to customize the import process within this pure python wrapper module, such that the low-level C++ module is not imported globally, i.e. it is not put into `sys.modules`.

```py
%define MODULEIMPORT
"
import glob
import importlib.util
import os
import sys

rootdir = os.path.dirname(os.path.abspath(__file__))
(modpath,) = glob.glob(os.path.join(rootdir, '$module.*'))
spec = importlib.util.spec_from_file_location('$module', modpath)
$module = importlib.util.module_from_spec(spec)
spec.loader.exec_module($module)
"
%enddef

%module(moduleimport=MODULEIMPORT) mymodulename
```

I utilized this piece of code to customize module import, firmly believing that by utilizing this technique with importlib, I will be able to avoid installing the module in `sys.modules`, but this seems not to be the case. I have debugged it, and right after the line `importlib.util.module_from_spec(spec)` is executed, the module indeed appears in `sys.modules` , which I can only gather happens because the generated C++ wrapper contains code that installs itself into `sys.modules`. 

Is there any way to customize the behavior of the generated C++ module, such that it does not load itself into `sys.modules` ? (So far I can only think of actually deleting it from that map right at the end of my module import code, but I was wondering if there is a way to even prevent it happening in the first place?)

**Comment by ojwb** [comment]
Adding the module to `sys.modules` seems to be done by Python itself - see https://docs.python.org/3/extending/extending.html#the-module-s-method-table-and-initialization-function (my emphasis):

> [PyModule_Create()](https://docs.python.org/3/c-api/module.html#c.PyModule_Create) returns a pointer to the module object that it creates. It may abort with a fatal error for certain errors, or return NULL if the module could not be initialized satisfactorily. **The init function must return the module object to its caller, so that it then gets inserted into sys.modules.**

If you really don't want it there then deleting it seems the way to go.
