### ISSUE TITLE
Support feature("nothread***") for whole class.

### ISSUE THREAD

**Issue by andre-caldas** [swig/swig#3045]
I am working on a project where I want just some specific methods to release the GIL.

I am doing this:
```
 %module(package="Ogre", directors="1", threads="1") Ogre
...
%feature("nothread");
...
#ifdef SWIGPYTHON
/* Unlocks SIG when called from python */
%feature("nothread", "0") Ogre::Root::startRendering;
%feature("nothreadblock") Ogre::Root::startRendering;
#endif
```

But during this `startRendering` method, lots of callbacks from many different classes (all named `Xxx::Listener`) are evoked. For that reason, I have to protect them all with:
```
#ifdef SWIGPYTHON
/* Locks SIG when python is called from c++ */
%feature("nothread", "0") Ogre::MaterialManager::Listener::handleSchemeNotFound;
%feature("nothread", "0") Ogre::MaterialManager::Listener::afterIlluminationPassesCreated;
%feature("nothread", "0") Ogre::MaterialManager::Listener::beforeIlluminationPassesCleared;

/* Do not release lock when calling from python */
%feature("nothreadallow") Ogre::MaterialManager::Listener::handleSchemeNotFound;
%feature("nothreadallow") Ogre::MaterialManager::Listener::afterIlluminationPassesCreated;
%feature("nothreadallow") Ogre::MaterialManager::Listener::beforeIlluminationPassesCleared;


/* Locks SIG when python is called from c++ */
%feature("nothread", "0") Ogre::RenderSystem::Listener::eventOccurred;

/* Do not release lock when calling from python */
%feature("nothreadallow") Ogre::RenderSystem::Listener::eventOccurred;

... many, many more.

#endif
```

It would be nice if SWIG did (if it does not!) allow us to setup those features per class, instead of per method. This way, I could simply use `*::Listener` once and for all!!! :-)

PS: I am very very new to SWIG. Sorry if I am saying something silly! :-)

**Comment by ojwb** [comment]
You can add a condition to a feature to check the class name, e.g.:

```
%feature("nothreadallow", %$classname="Ogre::MaterialManager::Listener");
```

These conditions aren't all that well documented, but see `Lib/swig.swg` for some hints.

**Comment by andre-caldas** [comment]
Is it possible to set the value?
```
%feature("nothreadblock", "0", %$classname="Ogre::FrameListener");
```

**Comment by ojwb** [comment]
I believe so but just try it and see.

**Comment by andre-caldas** [comment]
> I believe so but just try it and see.

I only asked because I had spent a whole day trying it, but could not make it succeed. **Probably I am doing something wrong**, but I couldn't get  the "%$classname" hack to work.

But anyway, I figured out that what I wanted could be achieved without it. Since I thin it might help some one:
1. Enable threads.
2. Use a global feature "nothreadallow".
3. Allow threads for specific methods: `%threadallow Class::method;`.

```
%module(package="Ogre", directors="1", threads="1") Ogre
// ...
%feature("nothreadallow");
// ...
%threadallow Ogre::Root::startRendering;
%threadallow Ogre::Root::renderOneFrame;
%threadallow Ogre::Root::_updateAllRenderTargets;
```

This way, I got virtual methods with BLOCK and a few selected methods with ALLOW.

Thank you for your help. :-)

**Comment by ojwb** [comment]
Oh it looks like `%$classname`, etc are only supported in `%rename` and `%ignore`, not in `%feature`.

Glad you solved it despite my bad advice.

**Comment by andre-caldas** [comment]
> Glad you solved it despite my bad advice.

The best part of it was getting your advice!
It is very touching knowing that someone important and probably very busy is accessible to some random guy who is probably just clueless doing something wrong... :-)

**Comment by vadz** [comment]
Thanks @andre-caldas for documenting your solution and just a note for anybody else who stumbles upon this issue looking for how to do this: `%threadallow` is the equivalent of `%feature("nothreadallow","0")`, i.e. you can't use `%feature("threadallow") Some::Function;`, it really needs to be this specific form because there is no `threadallow` feature, only the negated one.

(no prizes for guessing how I wasted the last 15 minutes)
