### ISSUE TITLE
Can't call MT5 CMTManagerAPIFactory.CreateManager() via SWIG with Golang

### ISSUE THREAD

**Issue by rts-gordon** [swig/swig#3049]
Hi there, 
   Thanks for SWIG the great tool, it saved a lot of time for coding with C/C++.

   My project call MT5 Manager API via SWIG with Golang, I created the mt5api.i interface file, and run swig to generate mt5api.go/mt5api_wrap.cxx/mt5api_wrap.h files, but there are some errors on CMTManagerAPIFactory.CreateManager(). 

way 1:
```
func Connect() {
  var ApiFactory CMTManagerAPIFactory = NewCMTManagerAPIFactory()
  ApiFactory.Initialize()
 ...
  var ApiManager IMTManagerAPI
  ret0 := ApiFactory.CreateManager(uint(MTManagerAPIVersion), &ApiManager)
  fmt.Printf("CreateManager: %d, ApiManager=%d\n", ret0, ApiManager.Swigcptr())
...
}
```

errors:
```
panic: interface conversion: *mt5api.IMTManagerAPI is not mt5api.IMTManagerAPI: missing method Allocate
```

way 2:
```
func Connect() {
  var ApiFactory CMTManagerAPIFactory = NewCMTManagerAPIFactory()
  ApiFactory.Initialize()
 ...
  var ApiManager SwigcptrIMTManagerAPI
  ret0 := ApiFactory.CreateManager(uint(MTManagerAPIVersion), &ApiManager)
  fmt.Printf("CreateManager: %d, ApiManager=%d\n", ret0, ApiManager.Swigcptr())
...
}
```

errors:
```
CreateManager: 3, ApiManager=0
Exception 0xc0000005 0x0 0x0 0x7ff7c4e9321f
PC=0x7ff7c4e9321f
signal arrived during external code execution

runtime.cgocall(0x7ff7c4e87b00, 0xc000177a50)
        C:/software/go64/src/runtime/cgocall.go:157 +0x3e fp=0xc000177a28 sp=0xc0001779f0 pc=0x7ff7c47192be
mt5api._Cfunc__wrap_IMTManagerAPI_Connect__SWIG_0_mt5api_7cabe5d500421f26(0x0, 0xc0003ba0a0, 0x435, 0xc000478cf0, 0xc000515268, 0x0, 0x7530)
        _cgo_gotypes.go:11398 +0x56 fp=0xc000177a50 sp=0xc000177a28 pc=0x7ff7c4de3076
...
```

 I tried many ways and asked ChatGPT for help, but still can't passing the correct IMTManagerAPI pointer or reference to CreateManager. I thought the IMTManagerAPI is a virtual class in cpp,  maybe there are somethings I missed in SWIG interface file.

SWIG interface file:
```
// SWIG's director feature permits a Go type to act as the subclass of a C++ class.
%module(directors="1") mt5api
%{
#include <windows.h>
#include "Include\MT5APIManager.h"
#include "Include\MT5APIConstants.h"
#include "Include\MT5APILogger.h"
#include "Include\MT5APITools.h"
#include "Include\MT5APITypes.h"
%}

%include <typemaps.i>
%include "carrays.i"

%inline %{
#define LPCSTR char*
%}

typedef __time32_t time_t;
typedef long long __time32_t;

%include "windows.i"
%include "Include\\MT5APIManager.h"
%include "Include\\MT5APIConstants.h"
%include "Include\\MT5APILogger.h"
%include "Include\\MT5APITools.h"
%include "Include\\MT5APITypes.h"
```

Does anyone interesting in MT5 and would take a look at this? Thank you very much.

Operation System: Windows 10
Swig version: windows v4.2.1
Golang version: v1.22.1
MingW-W64 version: v14.2.0

**Comment by chaozgz** [comment]
Have the same question here. It is because of CreateManager accepting a pointer of pointer?
```
inline MTAPIRES CMTManagerAPIFactory::CreateManager(UINT version,IMTManagerAPI **manager)
```

**Comment by rts-gordon** [comment]
@chaozgz 
Did you try %feature("director") in swig interface file?

**Comment by chaozgz** [comment]
no, I didn't. Did you solve this problem?

**Comment by chaozgz** [comment]
I tried
```
%feature("director") IMTManagerAPI;
%include "MT5APIManager.h"
```
and a new problem comes up. I need to deal with the `type` special word in Golang because it's a reserved word.

**Comment by rts-gordon** [comment]
Not yet, maybe this is a hard way.

**Comment by ojwb** [comment]
> I need to deal with the `type` special word in Golang because it's a reserved word.

SWIG should automatically rename that for you, and that seems to happen in a quick test:

```
$ cat type.i
%module x
%inline %{
int type() { return 42; }
%}
$ swig -c++ -go type.i
type.i:3: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
```

And the generated `x.go` has:

```
func Xtype() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_Xtype_x_534e9c0b253a155e())
	return swig_r
}
```

If that's not working for you, please open a **SEPARATE** ticket for it (since it's an unrelated issue except for being to do with Go) with a small, self-contained reproducer.

I don't know about the original issue raised here - can you reduce it to a small, self-contained reproducer?

**Comment by rts-gordon** [comment]
Hi @ojwb 
   Thanks for reply. Yes, swig can rename type to Xtype, it is only an warning.

   Can you please take a look at: why can't pass the "var ApiManager IMTManagerAPI" to CreateManager()?  or how to create an instance of IMTManagerAPI for passing? you know, IMTManagerAPI is pure virtual class defined in .h file, it can't be instanced.

**Comment by ojwb** [comment]
That's why I asked for a small, self-contained reproducer - it's too hard to usefully investigate without one.

Your interface file above include several headers you don't provide, but even with them I'd need to work out how to build everything and I don't use microsoft windows so I'd have to adjust the parts that are specific to that.  And once I had it actually building, there's still a lot of stuff obscuring the actual problem I'd need to strip away.  You presumably know your code much better than I do (which is not at all) so you're really best placed to minimise things to a small, self-contained reproducer.

**Comment by rts-gordon** [comment]
I can offer the MT5 Manager header files and some golang files those generated via Swig, they are publics. What else can I do for the "small, self-contained reproducer"? Is a  windows docker image include all files a better way?

**Comment by ojwb** [comment]
> What else can I do for the "small, self-contained reproducer"?

A docker image would not  help.

To be clear, the ideal is something that's no more than (say) a screenful of code, and if not a single file, only a handful of files.

It seems you have a very large and complicated multi-file reproducer - typically to turn that in to a small, self-contained reproducer you'd just cut away irrelevant parts and inline included files, checking it still reproduces the problem as you go until you have something where you can't remove anything more and have it still reproduce the problem.

In doing this it may well become obvious to you what the problem is - and if not, you should have something you can show to someone else and they are likely to be able to understand without investing a lot of time.

I'm afraid it does requires you to do more work, but it means someone is much more likely to help you.  We're all volunteers here, not paid support staff, and we struggle to keep on top of bug reports, so ones which would take disproportionate time to investigate are likely to languish.  You're getting helped for free, so we expect you to do some work to help us help you.

**Comment by rts-gordon** [comment]
@ojwb  thanks for your remind. Here is the "small, self-contained reproducer", but still have a lot of code.

1, There are some mt5 manager api cpp header files, I only use `MT5APIManager.h`,
2, There is a swig interface file `mt5api.i`,
3, There are `mt5api_wrap.cxx` and `mt5api.go` those generated with `mt5api.i` via swig tool, 
4, There is a main golang file `connect.go` to call `CMTManagerAPIFactory.CreateManager`.

Below are related codes of those files:
1, MT5APIManager.h
```
class CMTManagerAPIFactory
  {
private:
   HMODULE           m_hmodule;
   MTManagerVersion_t m_mtversion;
   MTManagerCreate_t m_mtmanager;
   MTAdminCreate_t   m_mtadmin;
   MTManagerCreateExt_t m_mtmanager_ext;
   MTAdminCreateExt_t m_mtadmin_ext;

public:
                     CMTManagerAPIFactory(void) : m_hmodule(NULL),m_mtversion(NULL),m_mtmanager(NULL),m_mtadmin(NULL),m_mtmanager_ext(NULL),m_mtadmin_ext(NULL) {}
                    ~CMTManagerAPIFactory(void) { Shutdown(); }
   //--- initialize & shutdown
   MTAPIRES          Initialize(LPCWSTR dll_path=NULL);
   MTAPIRES          Shutdown(void);
   //--- manager creation
   MTAPIRES          CreateManager(UINT version,IMTManagerAPI **manager);
   MTAPIRES          CreateAdmin(UINT version,IMTAdminAPI **admin);
...
  };

inline MTAPIRES CMTManagerAPIFactory::CreateManager(UINT version,IMTManagerAPI **manager)
  {
//--- check parameters
   if(!manager)
      return(MT_RET_ERR_PARAMS);
//--- check members & parameters
   if(!m_hmodule || (!m_mtmanager && !m_mtmanager_ext))
      return(MT_RET_ERROR);
//--- create manager
   return(m_mtmanager_ext ? m_mtmanager_ext(version,NULL,manager) : m_mtmanager(version,manager));
  }

class IMTManagerAPI
  {
public:
   //--- interface release
   virtual void      Release(void)=0;
   //--- Manager license check
   virtual MTAPIRES  LicenseCheck(MTLicenseCheck& check)=0;
   //--- memory management
   virtual void*     Allocate(const UINT bytes)=0;
   virtual void      Free(void* ptr)=0;
...
}
```

2, mt5api.i
```
// SWIG's director feature permits a Go type to act as the subclass of a C++ class.
%module(directors="1") mt5api
%{
#include <windows.h>
#include "Include\MT5APIManager.h"
#include "Include\MT5APIConstants.h"
#include "Include\MT5APILogger.h"
#include "Include\MT5APITools.h"
#include "Include\MT5APITypes.h"
%}

%include <typemaps.i>
%include "carrays.i"

%inline %{
#define LPCSTR char*
%}

typedef __time32_t time_t;
typedef int __time32_t;

%include "windows.i"
%include "Include\\MT5APIManager.h"
%include "Include\\MT5APIConstants.h"
%include "Include\\MT5APILogger.h"
%include "Include\\MT5APITools.h"
%include "Include\\MT5APITypes.h"
```

**Comment by ojwb** [comment]
That's not self-contained - what about the four other header files you include?  Are they not needed?  If so, why are you still including them?

And where's `connect.go`?

Also the C++ code there clearly won't compile because there's no `;` at the end of the classes, so you clearly haven't actually tested this works.

`MTAPIRES` isn't defined anywhere, and nor are the types like `MTManagerVersion_t`.

Sorry, you've exhausted my patience and good-will at this point.  Maybe some other maintainer can help you.

**Comment by rts-gordon** [comment]
sorry for many related codes, other header files can be ignore.
3, mt5api_wrap.cxx
```
CMTManagerAPIFactory *_wrap_new_CMTManagerAPIFactory_mt5api_c5382ade726bc97a() {
  CMTManagerAPIFactory *result = 0 ;
  CMTManagerAPIFactory *_swig_go_result;
  
  
  result = (CMTManagerAPIFactory *)new CMTManagerAPIFactory();
  *(CMTManagerAPIFactory **)&_swig_go_result = (CMTManagerAPIFactory *)result; 
  return _swig_go_result;
}
```

3, mt5api.go
```
type CMTManagerAPIFactory interface {
	Swigcptr() uintptr
	SwigIsCMTManagerAPIFactory()
	Initialize(a ...interface{}) uint
	Shutdown() (_swig_ret uint)
	CreateManager(a ...interface{}) uint
	CreateAdmin(a ...interface{}) uint
	Version(arg2 *uint) (_swig_ret uint)
}

func NewCMTManagerAPIFactory() (_swig_ret CMTManagerAPIFactory) {
	var swig_r CMTManagerAPIFactory
	swig_r = (CMTManagerAPIFactory)(SwigcptrCMTManagerAPIFactory(C._wrap_new_CMTManagerAPIFactory_mt5api_c5382ade726bc97a()))
	return swig_r
}

type IMTManagerAPI interface {
	Swigcptr() uintptr
	SwigIsIMTManagerAPI()
	Release()
	LicenseCheck(arg2 MTLicenseCheck) (_swig_ret uint)
	Allocate(arg2 uint) (_swig_ret uintptr)
	Free(arg2 uintptr)
	ProxySet(arg2 MTProxyInfo)
	Connect(a ...interface{}) uint
	Disconnect()
...
}
```

4, connect.go
```
package mt5api

import (
	"fmt"
	"unicode/utf16"
	"unsafe"
)

var (
	ApiFactory CMTManagerAPIFactory = NewCMTManagerAPIFactory()
)

const (
	MT5_CONNECT_TIMEOUT_MS = 30000
)

// Connect to MT5
func Connect(host string, login int, password string) (CMTManagerAPIFactory, error) {
	ret4 := ApiFactory.Initialize()
	fmt.Printf("Initialize: %d\n", ret4)

	var version uint
	if ret := ApiFactory.Version(&version); EnMTAPIRetcode(ret) != MT_RET_OK {
		return nil, fmt.Errorf("failed to get API version: %d", ret)
	}
	fmt.Printf("API version: %d\n", version)

	var ApiManager IMTManagerAPI
	ret0 := ApiFactory.CreateManager(uint(MTManagerAPIVersion), &ApiManager)
	fmt.Printf("CreateManager: %d, ApiManager=%d\n", ret0, ApiManager.Swigcptr())

	// Use the SwigcptrIMTManagerAPI instance
	//ApiManager = swigManager
	ret1 := ApiManager.Connect(STR2WSTR(host), uint64(login), STR2WSTR(password), STR2WSTR(""), uint64(0), uint(MT5_CONNECT_TIMEOUT_MS))
	fmt.Printf("Connect: %d\n", ret1)

	return ApiFactory, nil
}
```

**Comment by rts-gordon** [comment]
there are some errors when I run the connect.go: go run connect.go:
```
Initialize: 0
API version: 3550
panic: interface conversion: *mt5api.IMTManagerAPI is not mt5api.IMTManagerAPI: missing method Allocate
```

**Comment by rts-gordon** [comment]
Here are  `MTAPIRES` defined in MT5APIType.h, `MTManagerVersion_t `is not the key point:
```
typedef UINT MTAPIRES;
```

**Comment by rts-gordon** [comment]
@ojwb  Anyway, thanks for your time and help.

**Comment by asaka1234** [comment]
Just like this:


var ins mt5api.IMTManagerAPI
dp2 := mt5api.SwigcptrIMTManagerAPI(unsafe.Pointer(&ins))
ret0 := manager.CreateManager(uint(mt5api.MTManagerAPIVersion), dp2)
fmt.Printf("CreateManager: %d, ApiManager=%d\n", ret0, manager.Swigcptr())

**Comment by asaka1234** [comment]
try this:

var ins mt5api.IMTManagerAPI
dp2 := mt5api.SwigcptrIMTManagerAPI(unsafe.Pointer(&ins))
dp3 := mt5api.SwigcptrIMTManagerAPI(unsafe.Pointer(&dp2))
ret0 := manager.CreateManager(uint(mt5api.MTManagerAPIVersion), dp3)
fmt.Printf("CreateManager: %d, ApiManager=%+v\n", ret0, dp3)

ret1 := dp2.Connect(STR2WSTR(addr), uint64(login), STR2WSTR(password), STR2WSTR(""), uint64(0), uint(30000))

**Comment by rts-gordon** [comment]
@asaka1234 
  Many many thanks for you, yes I can call the function CMTManagerAPIFactory.CreateManager(), there are too much C Pointer traps.

  I still can't Connect to the MT server, I think maybe the issues on converting golang string to LPCWSTR that MT5 used, there are the STR2WSTR function, can you please give me more advices?   Thank you again.

```
// Convert Go string to LPCWSTR
func STR2WSTR(str string) LPCWSTR {
	utf16Str := utf16.Encode([]rune(str + "\x00"))                 // Add null terminator
	return SwigcptrLPCWSTR(uintptr(unsafe.Pointer(&utf16Str[0]))) // Create SwigcptrLPCWSTR
}
```

error message:
```
Initialize: 0
API version: 3550
CreateManager: 0, ApiManager=824634833296
Exception 0xc0000005 0x0 0xffffffffffffffff 0x7fff33944dd4
PC=0x7fff33944dd4
signal arrived during external code execution
runtime.cgocall(0x7ff6640c4f3f, 0xc00010f770)
	C:/software/go64/src/runtime/cgocall.go:157 +0x3e fp=0xc00010f710 sp=0xc00010f6d8 pc=0x7ff66343ab5e
library-metatrader/mt5api._Cfunc__wrap_IMTManagerAPI_Connect__SWIG_0_mt5api_cf5724f68710b53e(0x2410e010478, 0xc0005009a0, 0x3f8, 0xc0005009c0, 0xc0004e24f0, 0x0, 0x7530)
	_cgo_gotypes.go:11398 +0x59 fp=0xc00010f770 sp=0xc00010f710 pc=0x7ff663e4eff9
library-metatrader/mt5api.SwigcptrIMTManagerAPI.Connect__SWIG_0(0x2410e010478, {0x7ff664c0af20, 0xc0004e24d8}, 0x3f8, {0x7ff664c0af20, 0xc0004e24e8}, {0x7ff664c0af20, 0xc0004e2500}, 0x0, 0x7530)
	C:/job/library-metatrader/mt5api/mt5api.go:2243 +0x22e fp=0xc00010f878 sp=0xc00010f770 pc=0x7ff663e7afce
library-metatrader/mt5api.SwigcptrIMTManagerAPI.Connect(0x2410e010478, {0xc00010fb30, 0x6, 0x6})
	C:/job/library-metatrader/mt5api/mt5api.go:2265 +0x4b0 fp=0xc00010f940 sp=0xc00010f878 pc=0x7ff663e7b7f0
library-metatrader/mt5api.Connect({0xc000724613, 0xf}, 0x3f8, {0xc0005005b0, 0xd})
	C:/job/library-metatrader/mt5api/connect.go:52 +0x85b fp=0xc00010fc18 sp=0xc00010f940 pc=0x7ff663e48fbb
tsapi/service.(*MT5Service).Connect(0xc0007738f0)
	C:/job/service/mt_service_mt5.go:27 +0x9b fp=0xc00010fce8 sp=0xc00010fc18 pc=0x7ff663ede0bb
main.main()
...
```

**Comment by asaka1234** [comment]
try this:

> addr := "127.0.0.1:443"
	login := 1
	password := "1234"

	pAddr, _ := syscall.UTF16PtrFromString(addr)
	sAddr := mt5api.SwigcptrLPCWSTR(unsafe.Pointer(&pAddr))

	pPassword, _ := syscall.UTF16PtrFromString(password)
	sPassword := mt5api.SwigcptrLPCWSTR(unsafe.Pointer(&pPassword))

	pSec, _ := syscall.UTF16PtrFromString("")
	sSec := mt5api.SwigcptrLPCWSTR(unsafe.Pointer(&pSec))

	ret1 := dp2.Connect(sAddr, uint64(login), sPassword, sSec, uint64(1), uint(30000)) //PUMP_MODE_USERS
	fmt.Printf("Connect: %d\n", ret1)

	cnt := dp2.UserTotal()
	fmt.Printf("count: %d\n", cnt)

**Comment by rts-gordon** [comment]
@asaka1234 
  Thanks again for your help.

  The "StringToUTF16Ptr" function has deprecated and I changed to "UTF16PtrFromString", but the Connection return 3, that means "Invalid parameters". I am sure the login and password are correct because I can connect to server with them via Web API.

  Is this error in STR2WSTR()?

**Comment by asaka1234** [comment]
By the way , also you can try windows.StringToUTF16Ptr()

**Comment by rts-gordon** [comment]
@asaka1234 
  A big step, I can connect MT server with your help. I want get user info from server without PUMP mode, but the user.Login() is '0' and the user name if empty, maybe the call of UserRequest or convert SwigcptrLPCWSTR to string is not correct, may I ask you take a look, thanks a lot. 

```
pAddr, _ := syscall.UTF16PtrFromString(addr)
sAddr := mt5api.SwigcptrLPCWSTR(unsafe.Pointer(&pAddr))
...

ret1 := dp2.Connect(sAddr, uint64(login), sPassword, sSec, uint64(0), uint(30000)) 

user := dp2.UserCreate()
result := dp2.UserRequest(uint64(1000), user)  // login 1000 is exist.
if user.Swigcptr() != 0 {
	name := syscall.UTF16ToString(*(*[]uint16)(unsafe.Pointer(user.Name().(SwigcptrLPCWSTR))))
	fmt.Printf("User request: %d, login:%d, name: %s\n", result, user.Login(), name)
}

Output: User request: 0, login:0, name: 
```

**Comment by asaka1234** [comment]
Unfortunately, mt5 manager api does not support gcc!  I already inquiry that with official support.
So i think the right way is to use python sdk if you don't  want to use c/c++.

**Comment by rts-gordon** [comment]
Many thanks for your help.

It is a hard way to call mt5 api via golang and swig.

**Comment by asaka1234** [comment]
@rts-gordon  I finally  found a way to calll mt5 manager api via golang and swig.  if you interested, pls call me.

**Comment by rts-gordon** [comment]
@asaka1234 

 Wonderful, may I know how to do this?
