### ISSUE TITLE
Crash with \uDCFC and similar unicode symbols in `std::string`.

### ISSUE THREAD

**Issue by kontura** [swig/swig#3051]
We have a CI test that started failing on Fedora >= 41 and I believe its triggered by some change in Python update 3.12 -> 3.13.

I have reduced the reproducer to `example.h`:
```cpp
#include <string>

std::string concat(const std::string & test) {
    return test + "end";
}
```
and `example.i`:
```
/* File : example.i */
%module example

%{
#include "example.h"
%}

%include std_string.i

%include "example.h"
```

And critically run with:
```python
import example

p = "./\uDCFC.conf"
print(example.concat(p))
```

It crashes in `SWIG_MangledTypeQueryModule` because it gets `0` as both `start` and `end` `swig_module_info`. It gets there from `SWIG_Python_TypeQuery(std::string *)` because `SWIG_GetModule(0)` returns `0`. I am don't know why that happens.

With python3.12 it throws `TypeError: in method 'concat', argument 1 of type 'std::string const &'`.

I have originally reported it to Fedora Python: https://bugzilla.redhat.com/show_bug.cgi?id=2318762.

**Comment by ojwb** [comment]
It's useful to specify the SWIG version you're using when reporting a bug.

I can reproduce with git master and 4.2.1 at least.

**Comment by wsfulton** [comment]
There is a missing `PyErr_Clear()` after an exception is set in `SWIG_AsCharPtrAndSize()` handling the invalid encoded unicode string. `SWIG_Python_TypeQuery()` then calls Python C APIs with the pending exception and this shouldn't be done. Fix coming up shortly.
