### ISSUE TITLE
Precedence of CAST is wrong

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#3058]
Rebuild of `hamlib` package is failing with swig 4.3.0 in Fedora Rawhide. The error is:

```
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Hamlib.bs blib/arch/auto/Hamlib/Hamlib.bs 644
make[4]: Leaving directory '/builddir/build/BUILD/hamlib-4.5.5-build/hamlib-4.5.5/bindings'
LD_LIBRARY_PATH=../src/.libs perl ../bindings/perltest.pl
Can't call method "set_conf" without a package or object reference at ../bindings/perltest.pl line 13.
Perl 5.040000 test, version: Hamlib 4.5.5
make[3]: *** [Makefile:1115: check-perl] Error 255
```

The issue is caused because lots of definition is missing in `bindings/Hamlib.pm` e.g. `RIG_MODEL_DUMMY `.   You can check Hamlib.pm generated by  [SWIG 4.2.1](https://jplesnik.fedorapeople.org/swig43/hamlib/Hamlib.pm.421) and  [SWIG 4.3.0](https://jplesnik.fedorapeople.org/swig43/hamlib/Hamlib.pm.430).  

The script `perltest.pl` uses `RIG_MODEL_DUMMY` for creating the object and that the reason why it fails.

The missing items are defined in `hamlib-4.5.5/include/hamlib/riglist.h`

I find out the content of `Hamlib.pm` was changed since github commit 384125609.

[Source of Hamlib](https://jplesnik.fedorapeople.org/swig43/hamlib/hamlib-4.5.5.tar.gz)
[Result directory build with SWIG 4.2.1](https://jplesnik.fedorapeople.org/swig43/hamlib/hamlib-421.tar)
[Result directory build with SWIG 4.3.0](https://jplesnik.fedorapeople.org/swig43/hamlib/hamlib-430.tar)

**Comment by ojwb** [comment]
That commit indeed seems to be the cause, but it was just meant to ensure everything was actually initialised so we didn't carry over values from previous tokens in the same stack slot.  I slightly wonder if there was a latent bug doing so has brought to light, but probably more likely I just got part of it wrong.  It was a bit fiddly to do in places.

It looks like a lot of constants are now rejected with e.g.:

```
../include/hamlib/riglist.h:67: Warning 304: Unsupported constant value (ignored)
```

With 4.2.1 there are no warnings at all.  Not sure what's going on yet.

**Comment by ojwb** [comment]
Preprocessing turns the `#define` for `RIG_MODEL_DUMMY` turns into:

```
%constant RIG_MODEL_DUMMY = ((0)*1000+(1));
```

An apparently minimal reproducer is:

```
%module x
%constant A = (0)*1+2;
```

The problem is connected to how `(0)*1` gets parsed - unhelpfully the grammar handles this as a cast `(0)` applied to a pointer dereference of `1` (yes, this is stupid but it seems hard to fix).  In the parser rule for this cast case we check the `0` and see should see it doesn't seem to be a type and fix things up to handle it as a subexpression.

The grammar rule for a cast gets cast `(0)` applied to `*1+2` which seems wrong as a cast should have higher precedence than addition.  This precedence problem was already present, but it looks like we failed to clear the special `unary_arg_type` field so we got the right result but for the wrong reason.  My change to properly initialise these tokens meant that lucky accident no longer happens.

Fixing the precedence of casts fixes my minimised reproducer and also hamlib - the generated `.pm` is identical to the 4.2.1 version except for the SWIG version number in a comment.

This is the patch:

```
diff --git a/Source/CParse/parser.y b/Source/CParse/parser.y
index a229e2e7..f3ed4040 100644
--- a/Source/CParse/parser.y
+++ b/Source/CParse/parser.y
@@ -1793,7 +1793,6 @@ static String *add_qualifier_to_declarator(SwigType *type, SwigType *qualifier)
 %token <str> DOXYGENSTRING
 %token <str> DOXYGENPOSTSTRING
 
-%precedence CAST
 %left  QUESTIONMARK
 %left  LOR
 %left  LAND
@@ -1809,7 +1808,7 @@ static String *add_qualifier_to_declarator(SwigType *type, SwigType *qualifier)
 %left  LSHIFT RSHIFT
 %left  PLUS MINUS
 %left  STAR SLASH MODULO
-%precedence UMINUS NOT LNOT
+%precedence UMINUS NOT LNOT CAST
 %token DCOLON
 
 %type <node>     program interface declaration swig_directive ;
```

The precedence has been wrong for `CAST` since the oldest version of the grammar in the git history, dated 2002-11-30!

It seems an obvious fix, but I think needs some careful testing.

**Comment by ojwb** [comment]
@wsfulton If we're doing a 4.3.1 I think this should be included.  While the underlying problem with the precedence of casts is ancient, fixing this precedence seems the simplest and most satisfactory way to fix this regression.

**Comment by ojwb** [comment]
@jplesnik If you're after a patch to get hamlib building then this should work:

```
diff -ru hamlib-4.5.5-orig/include/hamlib/riglist.h hamlib-4.5.5/include/hamlib/riglist.h
--- hamlib-4.5.5-orig/include/hamlib/riglist.h	2023-04-06 00:31:23.000000000 +1200
+++ hamlib-4.5.5/include/hamlib/riglist.h	2024-10-27 07:57:28.657348430 +1300
@@ -30,7 +30,7 @@
 // With a max of 1000 models per backend we get total a model number range of 1001-33001
 // This MAX was 100 prior to 2020-02-18 and Icom was close to running out of the 100 range
 #define  MAX_MODELS_PER_BACKEND 1000
-#define RIG_MAKE_MODEL(a,b) ((a)*MAX_MODELS_PER_BACKEND+(b))
+#define RIG_MAKE_MODEL(a,b) (MAX_MODELS_PER_BACKEND*(a)+(b))
 #define RIG_BACKEND_NUM(a) ((a)/MAX_MODELS_PER_BACKEND)
 
 /*! \file riglist.h
diff -ru hamlib-4.5.5-orig/include/hamlib/rotlist.h hamlib-4.5.5/include/hamlib/rotlist.h
--- hamlib-4.5.5-orig/include/hamlib/rotlist.h	2023-04-06 00:31:23.000000000 +1200
+++ hamlib-4.5.5/include/hamlib/rotlist.h	2024-10-27 07:56:54.140716718 +1300
@@ -24,7 +24,7 @@
 #define _ROTLIST_H 1
 
 //! @cond Doxygen_Suppress
-#define ROT_MAKE_MODEL(a,b) ((a)*100+(b))
+#define ROT_MAKE_MODEL(a,b) (100*(a)+(b))
 #define ROT_BACKEND_NUM(a) ((a)/100)
 //! @endcond
 
```

It does patch the C header which isn't ideal, but the meaning is unchanged so it seems reasonable as a short-term workaround.

**Comment by ojwb** [comment]
> It seems an obvious fix, but I think needs some careful testing.

My main concern was that `%prec CAST` is specified for parenthesised subexpressions and we don't want the precedence of those to change, but in fact that precedence doesn't actually get used to resolve operator evaluation order (the parentheses wrap the whole subexpression and so enforce an order).  It's just there to resolve shift/reduce conflicts.
