### ISSUE TITLE
Allow recursive typedef resolution when applying typemap

### ISSUE THREAD

**Issue by marcosatti** [swig/swig#3064]
I have some code like this, which an %apply doesn't work for directly:

```
%include stdint.i
%include typemaps.i
...
typedef uint32_t library_word_t;
...
%apply(library_word_t *OUTPUT) { library_word_t *value };
```

I get a "can't apply ... no typemaps are defined" error.

However, if I introduce another typemap apply for `uint32_t`, it works as expected:

```
%include stdint.i
%include typemaps.i
...
typedef uint32_t library_word_t;
...
%apply(uint32_t *OUTPUT) { library_word_t *OUTPUT};
%apply(library_word_t *OUTPUT) { library_word_t *value };
```

Having a look at `typemap.c:504`, I can see only a single typedef resolution is implemented (and in this case, `uint32_t` resolves to `unsigned int` which is defined).

I don't want to include multiple intermediate `%apply` statements as ideally the `library_word_t` is typedef'd at build time by the user, meaning I won't know which intermediate types to put in.

Is it possible to implement recursive typedef resolution?

Sorry if this has been discussed before, couldn't find a previous issue on it.

**Comment by wsfulton** [comment]
Yes, this seems reasonable. I've got a patch for this now which I'll commit.

**Comment by marcosatti** [comment]
Great thanks for that, much appreciated!
