### ISSUE TITLE
Version 4.3 fails to initialize Java enums properly when unsigned ints are used in C++

### ISSUE THREAD

**Issue by markok314** [swig/swig#3070]
This issue occurs because Java does not support unsigned integers, and handling of ints
changed in SWIG 4.3
This code used to work in SWIG 4.2:
C++:

    enum A {
        x = 0x80000000
    };

The generated Java code compiles:

    public enum A {
        x(0x80000000),  // javac assigns -2.147.483.648 to x
        ...

SWIG 4.3 generates Java enum as:

    public enum A {
        x(2.147.483.648),
        ...

which does not compile, because the literal value is outside of range for signed 32-bit integers.
I guess SWIG should generate:

    x(-2.147.483.648),

in such cases, which would be compatible with the old behavior and existing client code.
SWIG could also use type 'long' for the swigValue member of the enum, but this would break the existing client code.

**Comment by ojwb** [comment]
Exactly what enum wrapping options are you using?

The java code you show isn't produced by default from the input snippet you provide (using current git master SWIG):

```
$ cat test.i
%module x
%inline %{
enum A {
    x = 0x80000000
};
%}
$ swig -c++ -java test.i
$ grep 'x(' *.java
$
```

**Comment by markok314** [comment]
Right, my bad. The missing info for generating enums:

    %include "enums.swg"
    %javaconst(1);

so complete test.i:

    %module x

    %include "enums.swg"
    %javaconst(1);

    %inline %{
    enum A {
        x = 0x80000000
    };
    %}

will generate:

    public enum A {
      x(2147483648);
      ...

**Comment by ojwb** [comment]
Thanks, that works for me too.  Will have a poke.

**Comment by ojwb** [comment]
> I guess SWIG should generate:
> ```
> x(-2.147.483.648),
> ```
> in such cases, which would be compatible with the old behavior and existing client code.

I think it's cleaner to instead emit larger (or perhaps all) unsigned integer literals initialising Java enums as hex so that the implicit conversion that Java does here can take effect like it used to.  I have a working patch but still need to sort out a regression test, etc.

**Comment by markok314** [comment]
Yes, hex values would be a good solution.

**Comment by wsfulton** [comment]
Hi @ojwb. Does `%javaconst(1)` still output the value into Java code as parsed from the C code? I'm not following all the details of these changes, but it should not try doing anything clever other than dump out what was parsed. If the C value is not turn out to be a valid Java value, the documentation shows how to work around this. I just wanted to check that this is still the case.
