### ISSUE TITLE
static constexpr auto generate error type 

### ISSUE THREAD

**Issue by jackiearcobaleno** [swig/swig#3074]
swig version: 4.2.1
os: ubuntu 22.04

1. declare with "constexpr auo" , result success
   `
    static constexpr auto Success = "Success";
   `
2.  declare with "constexpr auo" , result failed
   `
    static constexpr auto SUCCESS = "SUCCESS";
   `

on the second condition, cxx wrap convert with the code :
`
  SWIG_Python_SetConstant(d, "State_SUCCESS",SWIG_From_unsigned_SS_int(static_cast< unsigned int >(State::SUCCESS)))
`

expect result:
`
  SWIG_Python_SetConstant(d, "State_SUCCESS",SWIG_FromCharPtr(State::SUCCESS))
`

how can it convert with the right type of code ? @wsfulton

**Comment by ojwb** [comment]
Works for me with both 4.2.1 and git master - the constants are both wrapped as strings:

```
$ cat test.i
%module x
%inline %{
struct State {
 static constexpr auto Success = "Success";
 static constexpr auto SUCCESS = "SUCCESS";   
};
%}
$ swig -c++ -python test.i
$ grep SetConstant test_wrap.cxx 
SWIG_Python_SetConstant(PyObject *d, PyObject *public_interface, const char *name, PyObject *obj) {   
SWIG_Python_SetConstant(PyObject *d, const char *name, PyObject *obj) {   
  SWIG_Python_SetConstant(d, "State_Success",SWIG_FromCharPtr(State::Success));
  SWIG_Python_SetConstant(d, "State_SUCCESS",SWIG_FromCharPtr(State::SUCCESS));
```

(I'd also be really surprised if the case of the constant's name or content made any difference here.)

Please provide a complete reproducer.

**Comment by ojwb** [comment]
No response so closing as unreproducible.
