### ISSUE TITLE
Error: CPP #error "Unsupported architecture". Use the -cpperraswarn option to continue swig processing

### ISSUE THREAD

**Issue by wangshiyang** [swig/swig#3087]
my Environment: 
macos:15.2 x86_64
python version: 3.11.10
swig version: 
`
SWIG Version 4.2.1

Compiled with /Applications/Xcode_15.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ [Darwin]

Configured options: +pcre

Please see https://www.swig.org for reporting bugs and further information
`

When I use pip install m2crypto==0.40.1, an error occurs:
`INFO:spawn:swig -python -py3 -I/usr/local/include -I/Library/Developer/CommandLineTools/usr/lib/clang/16/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include "-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)" -I/usr/local/include -I/Library/Developer/CommandLineTools/usr/lib/clang/16/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include "-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)" -I/Users/xxxx/opt/anaconda3/envs/python3.11.10/include/python3.11 -I/usr/include/openssl -includeall -modern -builtin -outdir /private/var/folders/d_/f5d257050b1g1h8xtxnpxfr00000gp/T/pip-install-fn7rv1um/m2crypto_47e165cda08a48f19c3aa6e93e463980/src/M2Crypto -o src/SWIG/_m2crypto_wrap.c src/SWIG/_m2crypto.i
      Deprecated command line option: -py3. Ignored, this option is no longer supported.
      Deprecated command line option: -modern. Ignored, this option is now always on.
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:81: Warning 204: CPP #warning, ""Unsupported compiler detected"".
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:1037: Error: CPP #error "Unsupported architecture". Use the -cpperraswarn option to continue swig processing.
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/types.h:39: Error: CPP #error "architecture not supported". Use the -cpperraswarn option to continue swig processing.
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/_types.h:36: Error: CPP #error "architecture not supported". Use the -cpperraswarn option to continue swig processing.
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/endian.h:39: Error: CPP #error "architecture not supported". Use the -cpperraswarn option to continue swig processing.
      /Library/Developer/CommandLineTools/usr/lib/clang/16/include/stdint.h:20: Warning 202: Could not evaluate expression '__STDC_HOSTED__ && __has_include_next(<stdint.h>)'
      /Library/Developer/CommandLineTools/usr/lib/clang/16/include/stdint.h:20: Warning 202: Use of undefined function-like macro`

**Comment by wsfulton** [comment]
Please raise this problem with the project that owns this, which I expect is pip or m2crypto as they will be responsible for the pip install.
