### ISSUE TITLE
Default argument regression 3.0.2 to 3.0.4

### ISSUE THREAD

**Issue by blowekamp** [swig/swig#309]
I just updated my project from SWIG 3.0.2 to 3.0.4 and I am now getting the following syntax error for python:

:   File "/dev/shm/SimpleITK/SimpleITK-build/Testing/Installation/PythonVirtualenv/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 7141
4:     def SetOptimizerAsConjugateGradientLineSearch(self, learningRate, numberOfIterations, convergenceMinimumValue=1e-6, convergenceWindowSize=10, lineSearchLowerLimit=0, lineSearchUpperLimit=5.0, lineSearchEpsilon=0.01, lineSearchMaximumIterations=20, estimateLearningRate, maximumStepSizeInPhysicalUnits=0.0):
4: SyntaxError: non-default argument follows default argument

Here is the C++ line it is generated from:
https://github.com/SimpleITK/SimpleITK/blob/57d648744586e48fe26cf077d65ab6cd8ba0e642/Code/Registration/include/sitkImageRegistrationMethod.h#L134-L144

It looks like the enum default argument is omitted.

**Comment by vadz** [comment]
What are the exact SWIG command line options that you use?

**Comment by blowekamp** [comment]
This is my command line with some "-I"s removed:
/dev/shm/SimpleITK/Swig/bin/swig -python -DSWIGWORDSIZE64 -features autodoc=1 -keyword -outdir /dev/shm/SimpleITK/SimpleITK-build/Wrapping -c++ -o /dev/shm/SimpleITK/SimpleITK-build/Wrapping/SimpleITKPYTHON_wrap.cxx /home/blowekamp/src/SimpleITK/Wrapping/SimpleITK.i

**Comment by vadz** [comment]
It must be the same thing as #296 then: it was supposed to be fixed in 3.0.4, but the fix in it doesn't work when `-keyword` is used. It should be really fixed by afba5b755af2494ad1bdf29117289d69543c97db now however.
