### ISSUE TITLE
-fastdispatch changes typemap / extend functionality

### ISSUE THREAD

**Issue by larsoner** [swig/swig#3090]
@wsfulton from the discussion in https://github.com/swig/swig/pull/3089#discussion_r1882976180, I made a MWE [here](https://gist.github.com/larsoner/3c85cd573aa647bb799ff6baefa0a58b) that shows how having `-fastdispatch` on produces different class construction options than with it off.

You should be able to do:
```
$ git clone git@gist.github.com:3c85cd573aa647bb799ff6baefa0a58b.git swig
$ cd swig
$ make
...
python -c "from example import MyClass, DEEP_COPY; print(f'{MyClass(1., DEEP_COPY)}')"
* MyClass: received a PyObject
** Received a float 1.000000 turned to 1
<example.MyClass; proxy of <Swig Object of type 'Example::MyClass *' at 0x735d244d0330> >
```
to see that all five class-construction tests work with `-fastdispatch` on in the Makefile.

Then removing `-fastdispatch` from the Makefile, the fifth test should fail, and you can see it never even tries the `new_Example_MyClass` function because it doesn't print the `* MyClass: received a PyObject`:
```
$ sed -i 's/-fastdispatch -python/-python/g' Makefile
$ make
...
python -c "from example import MyClass, DEEP_COPY; print(f'{MyClass(1., DEEP_COPY)}')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/larsoner/python/gists/swig/example.py", line 67, in __init__
    _example.MyClass_swiginit(self, _example.new_MyClass(*args))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Wrong number or type of arguments for overloaded function 'new_MyClass'.
  Possible C/C++ prototypes are:
    Example::MyClass::MyClass()
    Example::MyClass::MyClass(int const)
    Example::MyClass::MyClass(Example::MyClass const &,Example::DeepCopy const)
    Example::MyClass::MyClass(PyObject *)

make: *** [Makefile:38: test5] Error 1
```
Notably, `test4` passes in both cases which just constructs using a single arg `MyClass(1.)`, suggesting that `%extend Example::MyClass` is available in some cases still to support a `float` arg. It's the `test5` that fails, which makes use of a float and a const enum where SWIG does not.

If this is intended behavior (or something that will take a long time to fix!), I'm happy to update https://github.com/swig/swig/pull/3089. Given that the command-line option is worded as:
```
     -fastdispatch   - Enable fast dispatch mode to produce faster overload dispatcher code
```
This to me suggests the switch should only affect speed, not functionality / class-construction options of the produced code, so it should also be updated.

But from reading the [Typemap scope docs](https://www.swig.org/Doc4.2/Typemaps.html#Typemaps_nn12) I also wonder if I'm doing something fishy / incorrect here and with `-fastdispatch` things just happen to (accidentally) work, and maybe there's a better way to get all the tests to pass? One option would be to extend the constructor to support pyobj and the constant, but this gets a bit unwieldy for larger wrappers where there are multiple arguments, all of which could be native types or something that should be typemapped.

**Comment by wsfulton** [comment]
Your example is missing a typecheck typemap for MyClass& which is required for using a type in overloaded methods. I'd try fix that first. https://swig.org/Doc4.3/Typemaps.html#Typemaps_overloading.

**Comment by larsoner** [comment]
Okay, added this:
```
    %typecheck(SWIG_TYPECHECK_POINTER) MyClass& {
        if (PyFloat_Check($input))
            $1 = 1;
        else if (SWIG_IsOK(SWIG_ConvertPtr($input, 0, 0, 0)))
            $1 = 1;
        else
            $1 = 0;
    }
```
and it does now work without `-fastdispatch`! I'll close this since this seems like a bug in our implementation, then, but feel free to reopen if you think any docs/behavior should change at the `swig` end.
