### ISSUE TITLE
Python kwargs not working in swig 3.0.4 and 3.0.3 with default arguments of class type.

### ISSUE THREAD

**Issue by lballabio** [swig/swig#310]
Hello,
    when using `%feature("kwargs")` with a method or a constructor, swig 3.0.4 tries to generate corresponding keyword arguments in the generated Python code (as opposed to 3.0.3 and later, that just generated a `(self, *args, **kwargs)` signature).

Unfortunately, swig seems to add the corresponding default arguments in the signature only if they are of a built-in type. Short example:

    %module Test

    class Foo {
      public:
        Foo();
    };

    class Bar {
        %feature("kwargs") m1;
        %feature("kwargs") m2;
      public:
        void m1(double x, double y=1.0);
        void m2(double x, const Foo& f = Foo());
    };

With options `-c++ -python`, the above generates in `Test.py`:

    class Bar(object):
        ...
        def m1(self, x, y=1.0):
            return _Test.Bar_m1(self, x, y)

        def m2(self, x, f):
            return _Test.Bar_m2(self, x, f)

that misses the default argument in `m2`. The bug is particularly nasty when a default argument of a class type follows one of a built-in type. If we replace the declaration of `Bar` in the interface file with:

    class Bar {
        %feature("kwargs") m2;
      public:
        void m2(double x, double y=1.0, const Foo& f = Foo());
    };

the generated Python class is:

    class Bar(object):
        ...
        def m2(self, x, y=1.0, f):
            return _Test.Bar_m2(self, x, y, f)

which is not valid Python code.

swig 3.0.3 gets the above method right because it generates the signature `m2(self, *args, **kwargs)`, but it fails when wrapping functions. The interface:

    %feature("kwargs") g; 
    void g(double x=1.0, const Foo& f = Foo());

generates the invalid code:

    def g(x=1.0, f):
        return _Test.g(x, f)
    g = _Test.g

Strangely, the above also reassigns `g` after defining it. But the interpreter never gets there and stops at the incorrect declaration. If you don't give a default argument to `x`, you get

    def g(x, f):
        return _Test.g(x, f)
    g = _Test.g

which defines a function that misses the default argument, but then redefines it as the native `_Test.g` so the incorrect one is thrown away and the bug is hidden.

**Comment by vadz** [comment]
I suppose this is the same as #309 (which is itself a duplicate...), please reopen if it isn't, i.e. not fixed by the commit mentioned there.

**Comment by lballabio** [comment]
Yes, that last commit fixes it. There's still the strange construct

    def g(*args, **kwargs):
        return _Test.g(*args, **kwargs)
    g = _Test.g

in the generated Python code that defines a function and immediately overwrite it, but it does no harm.
