### ISSUE TITLE
SWIG generates deprecated symbols for guile 2.0 and up

### ISSUE THREAD

**Issue by Giels** [swig/swig#312]
Symbols such as scm_sym2var, or scm_module_lookup_closure and so on have been deprecated and have been removed from guile 2.1. As of version 3.0.4, SWIG still generates these symbols for guile bindings.

**Comment by ojwb** [comment]
I don't believe SWIG currently has an active guile maintainer, so if you want to see changes to the guile backend, you probably need to come up with a patch, and ensure the test suite passes after applying it with currently used versions of guile.

The last major guile contribution was adding support for guile 2.0 in April 2013 by @gjanssens, so you might want to see if Geert is interested in collaborating on this.

**Comment by ojwb** [comment]
Thanks for the analysis - indeed the only use (in `Lib/guile/guile_scm_run.swg`) is suitably protected:

```
#if defined (SCM_MAJOR_VERSION) && (SCM_MAJOR_VERSION < 2)

static SCM
scm_module_variable (SCM module, SCM sym)
{
  return scm_sym2var (sym, scm_module_lookup_closure (module), SCM_BOOL_F);
}
```

So I'm going to close this as there's no actual bug in this report.

@Giels - if you are seeing deprecated symbols which are used in a non-protected context in git master, please reopen.

> I don't know when swig plans its next release (configure is now primed for 4.0). These changes are worth passing to a wider audience though. Will there still be 3.0 maintenance releases ? If so, please do include my last two PR's.

I'm not sure what a realistic date for 4.0.0 is.  I don't think there's currently a plan for a 3.0.13, though it's going to be problematic if the gap extends too long.  Problem is I'm not sure we really have the developer time to usefully progress towards 4.0.0 and maintain 3.0.x in parallel.
