### ISSUE TITLE
Windows failures to detect word size

### ISSUE THREAD

**Issue by blowekamp** [swig/swig#321]
I am trying to update to SWIG 3.0.5 from SWIG 3.0.2. 

I am receiving a compilation error on the SWIG generated code  for Python, Java, CSharp, Lua on windows 32-bit:

fatal error C1189: #error :  "SWIG wrapped code invalid in 32 bit architecture, regenarete code using -DSWIGWORDSIZE32"

This looks related to recent changes to swigarch.i

**Comment by wsfulton** [comment]
I can't think of anything in 3.0.3 - 3.0.5 that would introduce this error. The last time swigarch.i changed was for 2.0.0 and that was just a change of the text in a comment. Can you provide a way to reproduce please?

**Comment by blowekamp** [comment]
My dashboard only produced this error once. It has not come back since. The logic there looked funny to me for windows ( always long == int ), and I forgot to look at the year in the git log :)

I think this was just caused by a funny windows build. All Looks OK now :)
