### ISSUE TITLE
Python with C++ default arguments

### ISSUE THREAD

**Issue by GregoryEAllen** [swig/swig#327]
I have a simple example that demonstrates the issue. Works in 3.0.2, but fails in 3.0.5.

foo.h
```
#ifndef __FOO_H__
#define __FOO_H__

class Foo {
  public:
	Foo(void);
	int Bar(float f=-1, bool b=1);
};

#endif
```

foo.cc
```
#include "foo.h"

Foo::Foo(void) {}
int Foo::Bar(float f, bool b)
{ return 0; }
```

SWIGTest.i
```
%module(directors="1") SWIGTest

%{
#include "foo.h"
%}
%include "foo.h"
```

test_SWIGTest.py
```
import SWIGTest

foo = SWIGTest.Foo()
foo.Bar(1.,True) # works
foo.Bar(1.) # fails
foo.Bar() # fails
```
CMakeLists.txt [I build with CMake.]
```
project(SWIGTest)
cmake_minimum_required(VERSION 2.6)

add_library(SWIGTest foo.cc)

configure_file(test_SWIGTest.py
	${CMAKE_CURRENT_BINARY_DIR}/test_SWIGTest.py COPYONLY)

FIND_PACKAGE(SWIG REQUIRED)
INCLUDE(${SWIG_USE_FILE})

find_package(PythonLibs 2.4)
include_directories(${PYTHON_INCLUDE_PATH})
include_directories(${CMAKE_CURRENT_SOURCE_DIR})

set_source_files_properties(SWIGTest.i PROPERTIES CPLUSPLUS ON)

swig_add_module(SWIGTest python SWIGTest.i foo.cc)
swig_link_libraries(SWIGTest ${PYTHON_LIBRARIES})

find_program(PYTHON2_EXECUTABLE python2 DOC "python interpreter, version 2.x")
if(NOT PYTHON2_EXECUTABLE)
	set(PYTHON2_EXECUTABLE python)
endif()

enable_testing()
add_test(test_SWIGTest ${PYTHON2_EXECUTABLE} test_SWIGTest.py)
```

It builds fine. When I run the test, I get a runtime error:
```
NotImplementedError: Wrong number or type of arguments for overloaded function 'Foo_Bar'.
 Possible C/C++ prototypes are:
   Foo::Bar(float,bool)
   Foo::Bar(float)
   Foo::Bar()
```
Works as expected in older swig.

**Comment by GregoryEAllen** [comment]
The above was on Arch Linux. Swig 3.0.5 is now out in MacPorts (which I use), and I can confim the same issue on the Mac. I've reverted back to swig 3.0.2.

**Comment by vadz** [comment]
I can see this and it's unrelated to the directors, here is the minimal change to the test suite reproducing the problem:
```
diff --git a/Examples/test-suite/default_args.i b/Examples/test-suite/default_args.i
index bcb8766..c8dad78 100644
--- a/Examples/test-suite/default_args.i
+++ b/Examples/test-suite/default_args.i
@@ -56,6 +56,11 @@
     void accelerate(speed s = SLOW) { }
   };

+  struct FloatAndBoolClass
+  {
+    int call(float f=-1, bool b=1) {}
+  };
+
   // casts
   const char * casts1(const char *m = (const char *) NULL) {
     char *ret = NULL;
diff --git a/Examples/test-suite/python/default_args_runme.py b/Examples/test-suite/python/default_args_runme.py
index 25bef14..d6caae3 100644
--- a/Examples/test-suite/python/default_args_runme.py
+++ b/Examples/test-suite/python/default_args_runme.py
@@ -13,6 +13,11 @@ def run(module_name):
   de.accelerate()
   de.accelerate(default_args.EnumClass.SLOW)

+  fb = default_args.FloatAndBoolClass()
+  fb.call(1., True)
+  fb.call(1.)
+  fb.call()
+
   if default_args.Statics_staticMethod() != 60:
     raise RuntimeError

```

Investigating...

**Comment by vadz** [comment]
The cause of this happening is actually pretty clear: `1` used as default argument is passed as an `int` from Python and received as such in C++ code and fails to be converted to bool by `SWIG_AsVal_bool()`. The only way of fixing this I see is to interpret ints with values of `0` and `1` specially in this function -- but this would, of course, allow passing them to any C++ function expecting a `bool` and I'm not sure if it's a good idea.

So another possibility is to just document that you should use `true` and not `1` as default value for boolean parameters in your C++ code which seems reasonable enough for me.

**Comment by GregoryEAllen** [comment]
I can confirm that changing to:
```
int Bar(float f=-1, bool b=true);
```
In both 3.0.2 and 3.0.5.

I was also surprised to find out that
```
foo.Bar(1.,1)
```
fails in both versions.

My expected behavior was that of C/C++: zero is false, and non-zero is true.

Given the behavior of the second example, I'd say the new way is more consistent (even if it's surprising to me).
My old-school habit of using 0 and 1 got me in trouble. I learned long before true and false were reliably present. :)

**Comment by GregoryEAllen** [comment]
I use bool b=1 in several places in my code base, and this was the only one that caused an issue. That surprised me.

If I add a constructor:
```
#ifndef __FOO_H__
#define __FOO_H__

class Foo {
  public:
	Foo(void);
	Foo(const char* c, bool b=1) {;}
	int Bar(float f=-1, bool b=true);
};

#endif
```
And then in my test:
```
foo = SWIGTest.Foo("c")
```
A default argument of bool b=1 works fine in this new constructor in both 3.0.2 and 3.0.5. Why here, but not in Bar(...)?

It also seems inconsistent that -1 is acceptable for a float. Why do ints get promoted to floats, but not to bools?

Perhaps SWIG_AsVal_bool() should promote ints according to C/C++/Python's rules?

**Comment by ojwb** [comment]
Converting int to bool wouldn't be a promotion, but rather a demotion - we don't accept a float where a function expects an int parameter.

FWIW, you can define `SWIG_PYTHON_LEGACY_BOOL` to get the pre-3.0.0 handling of bools - see the CHANGES file for details.

**Comment by wsfulton** [comment]
Oh dear, another Python default args regression :(. We'll need to fix this. But I'm struggling to see how to to always ensure good code is generated. It isn't acceptable to get users to change their C++ code. It also isn't acceptable to use SWIG_PYTHON_LEGACY as that is broken for boolean default args.

On the positive side, we have said that in 3.0.0 and later in order to use bool default args Python 2.3+ is needed, which means we can consider changing the generated python default argument and construct a bool from whatever the numeric value is, eg instead of:

```python
    def Bar(self, f=-1, b=1):
        return _example.Foo_Bar(self, f, b)
```

```
    def Bar(self, f=-1, b=bool(1)):
        return _example.Foo_Bar(self, f, b)
```

This would work for the range of numeric values we currently accept without switching to *args.

There is a problem with this though and we don't really know when we have to add in the bool conversion in the python code. Firstly C++ typedef's to bool ... we could fully resolve the type to see if it reduces to a bool, but getting this right in the presence of template traits and incomplete type information is not easy and probably not reliable. Secondly, we don't know when a user is using PyObject_IsTrue to handle boolean types. For example, if %apply is used for some type that SWIG does not resolve to C++ bool, then we won't get it right.

There is something I don't understand which needs investigation, and that is why the problem doesn't exist for a non-member function, that is a global function, say:

```swig
%inline %{
  int globalBar(float f=-1, bool b=1);
%}
```
These all work from Python:
```python
print example.globalBar()
print example.globalBar(1.)
print example.globalBar(1., False)
```

**Comment by ojwb** [comment]
To be clear, I wasn't suggesting `SWIG_PYTHON_LEGACY_BOOL` was a solution for the problem originally reported, but rather addressing the side question about why a Python integer isn't accepted by default where a C++ function expect `bool`.

**Comment by wldcordeiro** [comment]
I've run into this issue as well but in a slightly different context. Here is my traceback:

```
<ipython-input-2-8b68710809e4> in <module>()
----> 1 s = QuickfixServer("config/config.cfg")

/vagrant/projects/fixserver/server.py in __init__(self, config)
     16                 self.application,
     17                 self.store_factory,
---> 18                 self.config,
     19             )
     20             # acceptor.start()

/home/vagrant/.virtualenvs/zfx/lib/python3.4/site-packages/quickfix.py in __init__(self, application, storeFactory, settings, logFactory)
  58626   def __init__(self, application, storeFactory, settings, logFactory=None):
  58627     if logFactory is None:
> 58628         SocketAcceptorBase.__init__(self, application, storeFactory, settings)
  58629     else:
  58630         SocketAcceptorBase.__init__(self, application, storeFactory, settings, logFactory)

/home/vagrant/.virtualenvs/zfx/lib/python3.4/site-packages/quickfix.py in __init__(self, *args)
  58109 
  58110         """
> 58111         this = _quickfix.new_SocketAcceptorBase(*args)
  58112         try:
  58113             self.this.append(this)

NotImplementedError: Wrong number or type of arguments for overloaded function 'new_SocketAcceptorBase'.
  Possible C/C++ prototypes are:
    FIX::SocketAcceptor::SocketAcceptor(FIX::Application &,FIX::MessageStoreFactory &,FIX::SessionSettings const &)
    FIX::SocketAcceptor::SocketAcceptor(FIX::Application &,FIX::MessageStoreFactory &,FIX::SessionSettings const &,FIX::LogFactory &)
```

I also found this old mailing list message related to this http://swig.10945.n7.nabble.com/Wrongly-matching-prototypes-python-td6113.html

**Comment by vadz** [comment]
@wldcordeiro Sorry, I don't understand what does this have to do with this issue as I don't see any bool arguments in play. Is this another regression? If so, could you please open another ticket for it and try to provide a minimal example showing it?

**Comment by wldcordeiro** [comment]
@vadz this error doesn't seem to be related directly to booleans, or if it is the name of the issue should be changed.

**Comment by vadz** [comment]
I'd rather open another issue for it than change this one... As I wrote, ideal would be to provide the [simplest possible](http://sscce.org/) example reproducing it and open another issue with it. TIA.

**Comment by vadz** [comment]
@wsfulton wrote:
> There is something I don't understand which needs investigation, and that is why the problem doesn't exist for a non-member function

I think I can at least finally answer this: this is due to the strange (at least for me) redirection that SWIG sets up in the generated code for the global functions: in Python code we have something like
```python
def globalBar(b=1):
    return _module.globalBar(b)
globalBar = _module.globalBar
```
but for a similar member function we have just
```python
class C(_object):
    def memberFoo(self, b=1):
         return _module.C_memberFoo(self, b)
```
And the net result of this is that when the default argument is omitted, `globalBar()` wrapper gets 0 arguments while `memberFoo()` always gets 1.

Unfortunately we can't use the similar trick with member function (or at least my Python is insufficient for this), so this doesn't really help at all. But at least it explains the mystery...

**Comment by vadz** [comment]
AFAICS this is the only open issue left related to the default arguments in Python. Unfortunately I am still not sure what to do about it. My personal preference would actually be to do nothing as using `1` as default boolean value didn't always work even previously, so it would be more consistent to just never accept it.

Alternative is accepting 1 (or any integer?) for boolean arguments which seems rather dangerous to me.

**Comment by ojwb** [comment]
I think the most appropriate (and simplest) way to fix this is simply to check if the C++ parameter type is `bool`, and if so, convert it either `True` or `False` in the generated Python wrapper.  Testing that fix now - will commit shortly if it doesn't break anything.

**Comment by wsfulton** [comment]
```
typedef bool mybool;
There is still a regression compared to 2.0.12:

struct XX {
  void bar(mybool b = 0) {
    printf ("b=%d\n", b);
  }
};
```
XX().bar() fails with:
```
NotImplementedError: Wrong number or type of arguments for overloaded function 'XX_bar'.
  Possible C/C++ prototypes are:
    XX::bar(mybool)
    XX::bar()
```

**Comment by ojwb** [comment]
OK, though the bug as reported is fixed - that's a different (though related) case.
