### ISSUE TITLE
runtime.h: No such file or directory

### ISSUE THREAD

**Issue by pindamonhangaba** [swig/swig#342]
Trying to build a go project made from c++ code with swig and get this error:

```
# kytea
./kytea_gc.c:2:21: fatal error: runtime.h: No such file or directory
 #include "runtime.h"
                     ^
compilation terminated.
```

go version is 1.4.1
swig is 3.0.5

**Comment by DanielCheng** [comment]
use:
go tool 6c -I `go env GOROOT`/pkg/`go env GOOS`_`go env GOARCH` kytea_gc.c

But I suggest you write a Makefile file like swig-3.0.5/Example/go/simple/Makefile, then use make to build your library.

**Comment by ojwb** [comment]
Incorrect usage rather than a bug, closing.

**Comment by michelson** [comment]
which would be the the correct way to build this with go 1.5 ? I't seems that there is no 6c in go tool

when I run `go build mylib` i get the same error

`src/cimgui/mylib_gc.c:2:10: fatal error: 'runtime.h' file not found`

**Comment by shivanshuiitg** [comment]
I tried the above approach, but it says :
can't compile multiple files.
