### ISSUE TITLE
No error for %constant with missing semicolon

### ISSUE THREAD

**Issue by ptomulik** [swig/swig#346]
The following file causes swig to crash instead of report an error:

```
%module foo
%constant int BAR=0
```

**Comment by ojwb** [comment]
There seem to be two separate issues here - in 2.0.12, this doesn't crash, but exits with status 0 and no output.

The crash was introduced by the merge of support for nested classes in b63c4839, which doesn't account for the possibility that `top` might be `NULL` - I've pushed a fix for that.

**Comment by ojwb** [comment]
In the generated parser, we jump to `yyerrlab` and then this gets called:

```
        yyerror (YY_("syntax error"));
```

However, `yyerror()` is a no-op in SWIG, so we quietly ignore the problem.  I don't understand why SWIG avoids making use of bison's error handling features in this way, so I don't know how to fix this.

**Comment by ojwb** [comment]
I had another poke, and this patch gives us a suitable error for your case:

```
diff --git a/Source/CParse/parser.y b/Source/CParse/parser.y
index 4ce8f0e..65a5bdd 100644
--- a/Source/CParse/parser.y
+++ b/Source/CParse/parser.y
@@ -1716,6 +1716,10 @@ constant_directive :  CONSTANT identifier EQUAL definetype SEMI {
 		 Swig_warning(WARN_PARSE_BAD_VALUE,cparse_file,cparse_line,"Bad constant value (ignored).\n");
 		 $$ = 0;
 	       }
+	       | CONSTANT error {
+		 Swig_error(cparse_file, cparse_line, "%%constant directive seems to be missing semicolon.\n");
+		 $$ = 0;
+	       }
                ;
 
 /* ------------------------------------------------------------
```

However it adds another shift/reduce conflict to the grammar, which seems undesirable.

**Comment by wsfulton** [comment]
Yes, we shouldn't be adding more shift/reduce. There is meant to be a way to diagnose what is causing the extra shift/reduce and then put in appropriate change to avoid it, but this isn't something I've ever mastered.

**Comment by ojwb** [comment]
Still reproducible with current master (exits with no output, no files created, zero exit status).  Might have another bash at trying to make this give an error.
