### ISSUE TITLE
Can I use Swig to migrate my php code to c/c++ ?

### ISSUE THREAD

**Issue by topstarnetwork** [swig/swig#350]
Hello,
I am not a coder and would like to know if I can  use Swig to migrate my php code to c/c++ ?
What I mean is I want to translate my magento php based software into c/c++ so my question is, 
do I have to use  Swig for translating my whole software?

**Comment by ojwb** [comment]
That isn't something SWIG can do - SWIG allows existing C/C++ code to be called from PHP (and other languages).

You might want to look at HHVM: http://hhvm.com/

This isn't a bug in SWIG, so closing.
