### ISSUE TITLE
Swig directors in Java does not work when multiple modules are defined as directors

### ISSUE THREAD

**Issue by asibross** [swig/swig#353]
When 2 or more modules are defined using the %module(directors="1") directive, the wrappers generated includes a global method with the same signature.
"bool ExceptionMatches(JNIEnv *jenv, jthrowable throwable, const char *classname)".

This cause linkage issues (multiple definition of `Swig::ExceptionMatches(_JNIEnv*, _jthrowable*, char const*)`) since global functions are exposed outside the scope of the cpp file.
A possible fix is to wrap the function declaration in an anonymous namespace, or define it as static in the ../java/director.swg file.

**Comment by ojwb** [comment]
There's a mechanism for Python and PHP where you can define `SWIG_DIRECTOR_STATIC` when compiling the C++ wrapper and get an anonymous namespace instead of the `Swig` namespace.

I've just committed 7ba0652 which extends that to the other languages with director support.

For now you can work around this by just defining `Swig` to nothing when compiling the C++ wrapper - probably the simplest way is to add `-DSwig` to the C++ compiler options.

**Comment by asibross** [comment]
I'm not sure this is a valid solution for all languages. 
Specifically in Java, it will generate the following warnings:

In file included from <>_wrapper.cpp:671:0:
<>_wrapper.h:14:7: warning: 'SwigDirector_AuthenticationPal' has a field 'SwigDirector_AuthenticationPal::<anonymous>' whose type uses the anonymous namespace [enabled by default]
 class SwigDirector_AuthenticationPal : public AuthenticationPal, public Swig::Director {
       ^
<>_wrapper.h:14:7: warning: 'SwigDirector_AuthenticationPal' has a base '{anonymous}::Director' whose type uses the anonymous namespace [enabled by default]

**Comment by ojwb** [comment]
I don't seem to get that warning - what compiler and what version is that with?

It doesn't look like the compiler is warning about an actual problem (at least if there is a problem here, I'm failing to see what it is), but rather that this is an odd thing to be doing.  It would be good to try to avoid this warning though.

**Comment by asibross** [comment]
I'm using Android ndk (r10b) which as far as I know is using gcc as his compiler.
