### ISSUE TITLE
Octave 4.0 compatibility

### ISSUE THREAD

**Issue by rdmitry** [swig/swig#356]
Swig uses OCTAVE_ALLOCATOR, but it was deleted:

> *\* The configure option --enable-octave-allocator has been removed.
> The internal class <octave_allocator> declared in oct-alloc.h has been removed.  The header remains, but is deprecated.  The macros to access the class (DECLARE_OCTAVE_ALLOCATOR, DEFINE_OCTAVE_ALLOCATOR, and DEFINE_OCTAVE_ALLOCATOR2) are now unconditionally defined to be empty.

**Comment by ojwb** [comment]
Looks like this was addressed by PR #460, please reopen if not.
