### ISSUE TITLE
Feature Request: Specify the version string in PHP generated code

### ISSUE THREAD

**Issue by dhait** [swig/swig#360]
PHP language module emits a hardcoded "NO_VERSION_YET" for version identifier in the zend_module_entry structure.
See Source/Modules/php.cxx at about line 537:

```
Printf(s_init, "    NO_VERSION_YET,\n");
```

It would be nice to be able to specify a version string at swig time, so that (for example)

```
echo "The version is" . phpversion('MyModule') . '\n'
```

gives a useful version (such as a SemVer).

**Comment by ojwb** [comment]
A patch to address this would be great.
