### ISSUE TITLE
inclusion of numpy.i into swig distribution

### ISSUE THREAD

**Issue by rashadkm** [swig/swig#361]
Is it any chance that numpy.i could be included in the swig sources ?

It is currently located here  - https://github.com/numpy/numpy/tree/master/tools/swig. But could be bettter to have it in SWIG/Lib/python/
From the numpy/tools/README
"""It is ultimately hoped that numpy.i will be included as part of the SWIG distribution."""

**Comment by ojwb** [comment]
Have you asked the numpy developers why they've not submitted it for inclusion themselves?

This is really something we ought to do in coordination with them.  It would be counterproductive to end up shipping an unmaintained copy of an old numpy.i in SWIG while the actively maintained one lives on elsewhere.

I don't recall them ever asking, and a quick search doesn't turn up anything - perhaps they don't consider it ready for submission yet.

**Comment by wsfulton** [comment]
SWIG provides library code for C and C++ standard library components. I don't ever envisage it providing wrappers for 3rd party libraries like numpy as it is up to those 3rd party libraries to maintain the SWIG wrappers and @ojwb gives some good reasons why.
