### ISSUE TITLE
D swig : possibly wrong default library name on Linux

### ISSUE THREAD

**Issue by LaurentTreguier** [swig/swig#363]
I just tried working with SWIG (3.0.5) and tested it with simple C code. Then, I saw that when generating the D code for interfacing with C, the default name of the library for Linux (in file `XXX_wrap.d` at line 275) is `libXXX_wrap.so` instead of `./libXXX_wrap.so`. This resulted in the final executable not finding the library when trying to load it.

**Comment by wsfulton** [comment]
Your suggestion requires the current directory to be the same as the directory of the .so file, which may not be the case. You are expected to set LD_LIBRARY_PATH to where the .so file is as per any Unix library. This is what the examples under Examples/d do. Alternatively use the runpath by compiling with the -L-rpath= option, eg to use the current directory (as you want):
```
dmd -ofrunme -L-rpath=. *.d
```
