### ISSUE TITLE
ocaml test suite needs some love

### ISSUE THREAD

**Issue by amitkumarghatwal** [swig/swig#364]
Hi All,

I have been able to build/install SWIG successfully. The test suite gets configured as below:
/*************_/
The SWIG test-suite and examples are configured for the following languages:
ocaml perl5
/**_***********/

Perl5 test cases are passing , but when i run "make -k check" . i am getting the below errors.

/*************_/
checking Examples/ocaml/simple
File "swig.ml", line 159, characters 54-57:
Warning 20: this argument will not be used by the function.
/bin/sh: camlp4: command not found
File "swigp4.ml", line 18, characters 8-10:
Error: Syntax error
/**_***********/

From where do we install - camlp4 package ? Any pointers in this regards would be helpful.
Regards,
Amit

**Comment by ojwb** [comment]
You don't say what platform you're using, but on Debian, `camlp4` is in the package also called `camlp4`.

However, the ocaml test suite isn't in great shape currently, so you will still see failures - see my recent mailing list posts about that:

http://thread.gmane.org/gmane.comp.programming.swig.devel/23627

If you know enough about ocaml to solve those, help would be appreciated.  I know practically nothing about it.

**Comment by ojwb** [comment]
We should be probing for camlp4 rather than using the literal tool name in the makefile - I've fixed that, but it won't help the underlying testsuite problems.

**Comment by amitkumarghatwal** [comment]
Hello ojwb,

Sorry about not mentioning my setup. I have tried  running ocaml test suite on SLES12 platform. I personally don't have much info on camlp4.

I did try the ocaml test suite again after ur latest commit. It fails with different errors now though as below : 
/*********************************************/
checking Examples/ocaml/simple
File "swig.ml", line 159, characters 54-57:
Warning 20: this argument will not be used by the function.
File "swigp4.ml", line 18, characters 8-10:
Error: Syntax error
../../Makefile:898: recipe for target 'ocaml_static' failed
make[3]: *** [ocaml_static] Error 2
/*********************************************/

Has anyone able to successfully run the "ocaml test suite" on any platform ?

Regards,
Amit

**Comment by ojwb** [comment]
I doubt anyone has recently.  I had a go at a `git bisect` but didn't get anywhere useful.  I suspect it's a combination of changes to the ocaml toolchain which SWIG needs updating for, new testcases which highlight existing flaws in SWIG's ocaml backend, and possibly changes to the generic SWIG code which the ocaml backend hasn't been full updated for.

I don't think we have an active ocaml backend maintainer currently - the last ocaml-specific change I can see in CHANGES was over 4 years ago:

```
2011-02-14: wsfulton
            [Ocaml] Apply patch #3151788 from Joel Reymont. Brings Ocaml support up to date
            (ver 3.11 and 3.12), including std::string.
```

For me, `ocaml -version` reports:

````
The OCaml toplevel, version 4.01.0
```

**Comment by wsfulton** [comment]
The OCaml status has been completely unknown for many years as no-one is supporting it and it isn't in our regularly run set of tests because it is broken. @amitkumarghatwal  you are probably best off trying to match an older version of SWIG with an older version of OCaml or attempt to bring support up to date yourself if you need it and volunteer to be the OCaml maintainer going forwards.

**Comment by ojwb** [comment]
I've attempted to add it to the tests which travis runs, but in the "ignore failure" group, but travis isn't running it - I've no idea why not.

Incidentally, asked the Debian ocaml IRC channel about ocamldlgen and they thought it was obsoleted by ctypes.  It isn't used by default anyway, as the testsuite builds statically.

**Comment by ojwb** [comment]
> I've attempted to add it to the tests which travis runs, but in the "ignore failure" group, but travis isn't running it - I've no idea why not.

It seems you need to list "ignore failure" tests twice, so it should now get run.

**Comment by wsfulton** [comment]
#1386 has improved out-of-source OCaml builds of the test-suite.

There seems to be some parallel make problems lurking that need fixing as when using `make check-ocaml-test-suite -j8` to run the test-suite I get lots of errors like:
```
checking ocaml testcase argout
File "swig.ml", line 145, characters 29-39:
Error: The type of this expression, '_a c_obj_t ref,
       contains type variables that cannot be generalized
../../../Examples/Makefile:946: recipe for target 'ocaml_static_cpp' failed
make[2]: *** [ocaml_static_cpp] Error 2
Makefile:81: recipe for target 'add_link.cpptest' failed
make[1]: *** [add_link.cpptest] Error 2
checking ocaml testcase array_member
File "swig.mli", line 1:
Error: I/O error: swig.mli: No such file or directory
../../../Examples/Makefile:946: recipe for target 'ocaml_static_cpp' failed
make[2]: *** [ocaml_static_cpp] Error 2
Makefile:81: recipe for target 'anonymous_bitfield.cpptest' failed
```
Maybe there is some race condition around swig.ml/swig.mli?

**Comment by ZackerySpytz** [comment]
I've created #1401 to address the race conditions when running the OCaml test suite with parallel make.

**Comment by wsfulton** [comment]
The various recent commits have resulted in the examples and test-suite passing so I have taken OCaml out of the broken Travis languages in b82d3007f3754cf321838fe4e78115b2d8b3e85b . Pressure is now on to keep it working, which is just what is needed! Thanks for all those who have helped get it to this state.

There is some way to go for OCaml though as many tests are disabled in Examples/tests-suite/ocaml/Makefile.in and the C++11 tests are also not run as they don't work.

**Comment by ojwb** [comment]
The ocaml test suite has now had some love, so closing.
