### ISSUE TITLE
Missing smart pointer handling in Java director extra methods implementation

### ISSUE THREAD

**Issue by asibross** [swig/swig#370]
Even though I know shared_ptr isn't officially supported for directors in Java, so far it seems to have been working for me.
I recently tried to use the swigReleaseOwnership/swigTakeOwnership methods on my director enabled proxy class and I got a segmentation fault.

Further investigation into the generated wrapper code revealed that the c++ pointer is being wrongly cast into a non smart pointer, while it should have been cast into smart pointer as done correctly in the *_director_connect method.

This seems like a simple fix in the java.cxx file, in the emitDirectorExtraMethods(). It should check whether smartptr is enabled before emitting the cast code for the change_ownership method.

Am I missing something?

**Comment by wsfulton** [comment]
That seems reasonable.
 Please submit a patch with your fix.

**Comment by wsfulton** [comment]
This looks good. I think Java directors and smart pointers can count as supported, did you see something saying they weren't? We even have a test case for this. Could you modify it to demonstrate the problem and hence the fix? Just tweak Examples/test-suite/director_smartptr.i and/or Examples/test-suite/java/director_smartptr_runme.java.

**Comment by wsfulton** [comment]
Patch #417 applied to fix.
