### ISSUE TITLE
Go: Update of documentation needed regarding the new -cgo option

### ISSUE THREAD

**Issue by michael-schaller** [swig/swig#371]
As mentioned in issue #289 the Go documentation needs to be updated as the "-cgo" commandline option is missing.

"23.3.1 Additional Commandline Options" is missing the new "-cgo" commandline option. IMHO it would also be helpful to explain when to use "-cgo".

"23.3.2 Go Output Files" also needs an update with regards to the "-cgo" commandline option. "MODULE_gc.c" for an instance is not generated in case "-cgo" is used. Furthermore the commands to run SWIG directly are different depending on the presence of "-cgo".

FYI: @ianlancetaylor

**Comment by ianlancetaylor** [comment]
I see the changes in https://github.com/swig/swig/commit/9ad497c08e012b9fc5431486d982ea4053c53478 and I see them in my copy of the manual.  Where are you looking?  What have I forgotten to change?

**Comment by michael-schaller** [comment]
I was looking at http://www.swig.org/Doc3.0/SWIGDocumentation.html#Go. Apparently it is still the 3.0.5 documentation and not the documentation of the git master.

Ian, sorry for the fuzz. You did an excellent job with change 9ad497c.

**Comment by ojwb** [comment]
@michael-schaller The documentation on the website is for the latest released version.  It would be unhelpful to generate it from git master, as that may have features not available in any release yet.

**Comment by michael-schaller** [comment]
@ojwb Olly, that makes total sense to me. I just failed to look in the right place. ;-)
