### ISSUE TITLE
Python type error with typedef'd pointer types and NULL default argument

### ISSUE THREAD

**Issue by jspreston** [swig/swig#376]
When wrapping a typedef'd pointer type such as MyT in the following header:
```
typedef void *MyT;

void f3(int n,MyT t=NULL);

class MyClass{
public:
    void classprint2(int n,void *t=NULL);
    void classprint3(int n,MyT t=NULL);
};
```

the function `classprint3` is not callable without specifying an argument for `t`, it will give the following error:

```
Traceback (most recent call last):
  File "test_hello.py", line 24, in <module>
    hc.classprint3(2)
  File "/home/sci/jsam/code/Projects/Utah/tmp/swigtest/hello.py", line 119, in classprint3
    return _hello.MyClass_classprint3(self, n, t)
NotImplementedError: Wrong number or type of arguments for overloaded function 'MyClass_classprint3'.
  Possible C/C++ prototypes are:
    MyClass::classprint3(int,MyT)
    MyClass::classprint3(int)
```
This error does not occur with version 3.0.2, but does with 3.0.5 and HEAD (g6c76c7b  as of my last test). It seems to only come up with typedef'd pointer types in class member functions, I've created a full minimal example here:

https://gist.github.com/jspreston/cf702e2dae00c1c3717c

**Comment by vadz** [comment]
Should be fixed by 0eae8a8efaa5ce1d5c918542d34a23afd2f92c9e
