### ISSUE TITLE
Default argument handling for Python

### ISSUE THREAD

**Issue by juliamatt** [swig/swig#377]
(Excerpt from test.i)
...
#include "test.h"

%typemap( default ) double* param_opt
{
   $1 = NULL;
}

%rename( funcid ) Test::func( long** long_list_out, float min_val, float max_val,
										  long min_size, long max_size, long delta, 
										  double min_stab, long stable_dist,
										  long stable_mode, long count,
										  double* param_opt, long param_len_opt );

class Test
{
	public:
		Test( long img_id, long neigh, double thres_change );
		long func( long** long_list_out, float min_val, float max_val,
							  long min_size, long max_size, long delta, 
							  double min_stab, long stable_dist,
							  long stable_mode, long count,
							  double* param_opt, long param_len_opt );
};
...

( test.h declares:
  class Test
  {
	public:

		Test( long img_id, long neigh = 8, double thres_change = 3.0 );
		long func( long** cont_ids, float min_val, float max_val,
							  long min_size, long max_size, long delta,
							  double min_stab, long stable_dist = 0,
							  long stable_mode = 0, long count = 0,
							  double* param = NULL, long param_len = 0 );
  }
)

creates test.py by SWIG 3.0.5 on Windows (swigwin-3.0.5 installer):
...
class Test(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Test, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Test, name)
    __repr__ = _swig_repr

    def __init__(self, img_id, neigh, thres_change):
        this = _icono.new_Test(img_id, neigh, thres_change)
        try:
            self.this.append(this)
        except:
            self.this = this

    def funcid(self, min_val, max_val, min_size, max_size, delta, min_stab, stable_dist, stable_mode, count, param_opt):
        return _test.Test_funcid(self, min_val, max_val, min_size, max_size, delta, min_stab, stable_dist, stable_mode, count, param_opt)
    __swig_destroy__ = _test.delete_Test
    __del__ = lambda self: None
Test_swigregister = _test.Test_swigregister
Test_swigregister(Test)
...

And complains in Python (too few arguments) when calling test.Test().func() with less than 10 parameters.

Matt 

PS: Works for SWIG 2.0.9

**Comment by notroj** [comment]
Simpler repro case:

    %module default
    
    %typemap(default) double *
    {
       $1 = 0L;
    }
    
    %{
    int fish(int arg1, double *arg2);
    %}

    int fish(int arg1, double *arg2);

When built with "swig -python", SWIG 3.0.5 (and git master as of a few days ago) now produces Python code:

    def fish(arg1, arg2):
         return _default.fish(arg1, arg2)

Which does not allow arg2 to be omitted.  The old style wrapper allowed args2 to be omitted:

    def fish(*args):
      return _default.fish(*args)

**Comment by vadz** [comment]
Thanks @notroj, I'll try to have a look at this next week.

**Comment by swails** [comment]
From the commit log message of fdc6bbeda387fb49ab7dcdbb0f17e4645db3115c:

```
    Don't always use "*args" for all Python wrapper functions.
    
    Due to what seems like a bug introduced during Python 3 support merge, all the
    generated Python functions used the general "*args" signature instead of using
    the named parameters when possible.
    
    This happened due to is_primitive_defaultargs() always returning false for the
    functions without any default arguments as "value" passed to convertValue()
    was NULL in this case and convertValue() always returns false for NULL.
    
    Fix this by checking for value being non-NULL before calling convertValue().
    
    Doing this exposed several problems with the handling of unnamed, duplicate
    (happens for parameters called INOUT, for example) or clashing with keywords
    parameter names, so the code dealing with them had to be fixed too. Basically
    just use makeParameterName() consistently everywhere.
```

So this seems to be an intentional change.

**Comment by vadz** [comment]
The change is intentional but the typemap defining the default value should be taken into account.

**Comment by notroj** [comment]
Thanks!  That fixed my test case but not Subversion :(  I'm trying to work out what's special about the SVN case.

**Comment by notroj** [comment]
def svn_repos_create(path, unused_1, unused_2, config, fs_config, pool):
       """svn_repos_create(char const * path, char const * unused_1, char const * unused_2, apr_hash_t config, apr_hash_t fs_config, apr_pool_t pool) -> svn_error_t"""
        return _repos.svn_repos_create(path, unused_1, unused_2, config, fs_config, pool)

One thing I noticed... in the generated comments in the SWIG wrapper code, the pool type has lost its pointer.  It should be "apr_pool_t *pool".  Any ideas how this could happen or where I could start looking?

**Comment by vadz** [comment]
How is the `default` typemap defined for subversion (you can run `swig -debug-tmused|fgrep -w default` if unsure)?

**Comment by notroj** [comment]
That produces a lot of lines like:

    ....: Typemap for apr_pool_t *pool (default) : %typemap(default) apr_pool_t *

**Comment by notroj** [comment]
I tried with -debug-tmsearch too, this is for svn_repos_create with the wrapper function created as in my earlier comment, where the default typemap for apr_pool_t *pool should be picked up:

    .../include/svn_repos.h:470: Searching for a suitable 'default' typemap for: apr_pool_t *pool
      Looking for: apr_pool_t *pool
      Looking for: apr_pool_t *
      Using: %typemap(default) apr_pool_t *

**Comment by vadz** [comment]
Looking at `svn_types.swg` I see
```
%typemap(default, noblock=1) apr_pool_t *(apr_pool_t *_global_pool = NULL, PyObject *_global_py_pool = NULL)
...
```
which doesn't seem to apply to `svn_repos_create` above. Where is the typemap for just `apt_pool_t*` defined?

**Comment by notroj** [comment]
My understanding of SWIG is limited, so I don't understand why that wouldn't be the typemap for just "apr_pool_t*".  I think it is supposed to be.  The stuff in brackets after that is the list of temporary variables ("parms" in the SWIG manual), right?

**Comment by vadz** [comment]
Sorry, I was just wrong (being a mere mortal, my understanding of SWIG is limited as well...). I thought this was a multi-argument typemap, but I just didn't read it carefully enough.

Unfortunately I still can't reproduce the problem, the following test works just fine for me:
```
%module da

%typemap(default, noblock=1) pool_t
  * (pool_t* glob = NULL, PyObject *py_glob = NULL)
{
  $1 = glob;
};

%inline %{
typedef void* pool_t;

struct S {
  int from_pool(int n, pool_t* pool)
    { return pool ? n : 2*n; }
};

%}
```

**Comment by notroj** [comment]
I am debugging by throwing darts blindfold here now but, there are two similar loops through tmaps in Python.cxx and they work differently: make_autodocParmList() has:

      String *tm = Getattr(p, "tmap:in");
      if (tm) {
	pnext = Getattr(p, "tmap:in:next");
	if (checkAttribute(p, "tmap:in:numinputs", "0")) {
	  continue;
	}
      } else {
	pnext = nextSibling(p);
      }

whereas is_representable_as_pyargs() has:

      String *tm = Getattr(p, "tmap:in");
      if (tm) {
	pnext = Getattr(p, "tmap:in:next");
	if (checkAttribute(p, "tmap:in:numinputs", "0")) {
	  continue;
	}
      }
      if (!pnext) {
	pnext = nextSibling(p);
      }

**Comment by vadz** [comment]
I admit I don't know which one is correct (the difference between them is what happens if "in" typemap is defined but `in:next` is not), but I don't think it changes anything here (you could always try changing the code to check though...).

OTOH I wonder if `is_repr_as_pyargs()` should be doing something about `tmap:default:next`... I am not really sure about anything here though, it would be really great to have a simple way of reproducing this to see what's going on with the typemaps.

**Comment by notroj** [comment]
Ignore that.  Try this dart throw:

The *first* argument to that function is triggering the numinputs=0 case which bails out early.

    %module default

    %{
    typedef double foo_t;
    typedef float bar_t;

    int fish(foo_t **arg1, int arg2, bar_t *arg3);
    %}

    %typemap(in, numinputs=0) foo_t ** (foo_t temp) "$1 = &temp;";

    %typemap(default, noblock=1) bar_t *
    {
       $1 = 42;
    }
    
    int fish(foo_t **arg1, int arg2, bar_t *arg3);

Produces...

    def fish(arg2, arg3):
        return _default.fish(arg2, arg3)

**Comment by notroj** [comment]
Ran 127 tests in 3.359s

OK

woot!

**Comment by notroj** [comment]
I'm basically still throwing darts here since I don't understand that next/nextSibling API, but I hacked that function to work like this:

https://gist.github.com/notroj/8688bd78322b25d4365c#file-python-cxx-hack

and now the SVN SWIG stuff builds & passes tests.

**Comment by vadz** [comment]
Thank you for debugging this! I freely admit that I have absolutely no idea about what is `tmap:in:next` and how is it supposed to be handled, but it still seems like a bad idea to remove the code dealing with it, so I'll make a version preserving it but still using `nextSibling()` in case it's not specified.
