### ISSUE TITLE
Cannot ignore methods when using allprotected directors

### ISSUE THREAD

**Issue by sablefr** [swig/swig#378]
Hi,

first thank you for that great tool!

I think I found an issue when using directors with the allprotected feature: it is not possible to ignore a method.
For example, you can add the following line in the Examples/test-suite/allprotected.i example:
%ignore ProtectedBase::virtualMethod;

You would then expect that method to be ignored from the director, but if you look at the generated binding, you will find the following line:
std::string SwigDirector_ProtectedBase::virtualMethod() const

Thank you in advance for any fix.
Best regards

Sebastien

**Comment by sablefr** [comment]
Maybe be related to (and fixed by) issue #544.

**Comment by ojwb** [comment]
Yes, this is the same issue and #544 has much more detail so closing this as a duplicate.  Thanks.
