### ISSUE TITLE
lisp support

### ISSUE THREAD

**Issue by phil0stine** [swig/swig#384]
I have seen reference to a lack of lisp maintenance, and I don't see anything in Examples that would indicate active lisp support. 

I do, however, see interface files in the `Lib/allegrocl` directory that seems to at least provide _some_ capability (for using `std::string`, for example). Unfortunately, the most basic example I can come up with using `std::string` fails. Are there working examples of something like this in the wild?

**Comment by wsfulton** [comment]
Unfortunately there aren't any allegrocl examples shipped with SWIG and the state of allegrocl is unknown as there aren't any tests. I suggest googling for a std::string example or asking or searching on the [SWIG mailing lists](http://swig.org/mail.html). You could also adapt one of the SWIG examples from another language that you are familiar with.
