### ISSUE TITLE
feature("director") and feature("ref") don't work together

### ISSUE THREAD

**Issue by LindleyF** [swig/swig#402]
When feature("director") and feature("ref") are used together, the method named by ref (we'll call it AddRef()) is called prior to swig_connect_director(). This would be fine, since the ref feature is always going to point to an existing method, not a generated method.

However, the generated SwigDirector_T class does not initialize its swig_override array in the constructor, which means that at the time AddRef() is called, it's filled with random garbage. Usually it will think it has to look for a Java method to call, not find one, and throw "null upcast object".

This array should be zero'd in the constructor.

**Comment by ojwb** [comment]
Fixed by #403.

**Comment by wsfulton** [comment]
Re-opened as #403 needs further work.

**Comment by ojwb** [comment]
Fixed by #413.

**Comment by wsfulton** [comment]
#403 enhanced by #413.
