### ISSUE TITLE
filter  - replace multiple  characters

### ISSUE THREAD

**Issue by gogliko** [swig/swig#406]
hi, i use swig and want replace some characters this my code : 
{% filter replace(' ', '-', 'g') | replace ('a' , '$','g')  %}a b c d e f g {% endfilter %}

error : 
SyntaxError: Unexpected identifier in file C:\****  \front\views\index.html. [object Object]

**Comment by wsfulton** [comment]
This is not valid swig syntax. Please read the manual.
