### ISSUE TITLE
Using Python shared_ptr breaks naked pointer callback

### ISSUE THREAD

**Issue by phil0stine** [swig/swig#411]
For an interface file like the following
```c
%module(directors="1") circle_test_py
%include "typemaps.i"
%include "cpointer.i" 
 //%include "boost_shared_ptr.i"

%{
#include "cp_tst.hpp"
%}

//%shared_ptr(Circle);
%feature("director") CirclePrint;

%include "cp_tst.hpp"
```
and c++ file
```c++
class Circle {
public:
  Circle() : r_(1){}
  Circle(int r) : r_(r) {};
  ~Circle() {}
  int r_;
 };

class CirclePrint {
public:
  CirclePrint(){}
  virtual ~CirclePrint(){}
  virtual void shared_p_cb(const boost::shared_ptr<Circle>& c) 
  {
    std::cout<<"Shared base r "<<c->r_<<std::endl;
    print_cb(c.get());
  }
  virtual void print_cb(const Circle* c) {std::cout<<"Base r "<<c->r_<<std::endl; }
...
```
the Python test
```python
import circle_test_py

class CirclePrintDerived(circle_test_py.CirclePrint):
    def __init__(self, *args, **kwargs):
        super(CirclePrintDerived, self).__init__(*args, **kwargs)

    def print_cb(self, c):
        print 'Derived r', c
        print c
...
```
yields `Derived r <circle_test_py.Circle; proxy of <Swig Object of type 'Circle *' at 0x7f05a411c1b0> >
` as I would expect. However, if I uncomment the shared pointer related lines in the interface file, the same code yields `Derived r <Swig Object of type 'Circle *' at 0x7fee482cc1b0>`, and thus the callback object has not been properly transformed into a `Circle` object.

**Comment by wsfulton** [comment]
typemaps.i and boost_shared_ptr.i are orthogonal as they both override the default typemaps. You'll have to use one or the other or provide your own typemaps for the INPUT, OUTPUT, INOUT typemaps that support shared_ptr. A shared_ptr implementation of typemaps.i should be possible by combining the shared_ptr typemaps and those in typemaps.i.

It also doesn't surprise me that %types used in cpointer.i is not compatible with the "smartptr" feature used in boost_shared_ptr.i as the "smartptr" feature is internally implemented using %types. I suggest taking cpointer.i and rewriting it using shared_ptr.

**Comment by phil0stine** [comment]
I will give your suggestion a shot, thanks for the quick response.
