### ISSUE TITLE
A quick question: Does it require C++ source code if I want to link a C++.so to Go?

### ISSUE THREAD

**Issue by czhou** [swig/swig#412]
I am very new to C++ as well as SWIG, my question is:
I have a third-party C++ library which only contains a bunch of .h files and 2 xxx.so,
and I want to use them in my Go project, however, I don't have the source code of that 3-party C++ lib,
can I still invoke the functions in those so files with SWIG please?

thank you in advance.

**Comment by vadz** [comment]
You don't need to have sources for the library being wrapped and you definitely shouldn't use the issue tracker for asking questions, please do it on the [mailing list](https://lists.sourceforge.net/lists/listinfo/swig-user) instead.
