### ISSUE TITLE
[Go] How to call a C++ method from within a Go method on a director?

### ISSUE THREAD

**Issue by michael-schaller** [swig/swig#418]
Maybe I'm missing something essential here but how do I call a C++ method from within a Go method on a director?

According to the SWIG documentation (23.4.7) I would assume that this is possible. Quote from the documentation:
*"The Go code may of course call other methods on itself, and those methods may be defined either in Go or in C++."*

I've created a simple example. The full source can be found here:
https://github.com/michael-schaller/go-swig-examples/tree/master/director-example1

The example is based around this abstract C++ class:
``` C++
class Progress
{
	public:
		Progress(int s) : total_steps(s) { steps_done = 0; };
		virtual ~Progress() {};

		void StepDone() { steps_done++; OnStepDone(); };
		float Percent() { return float(steps_done) / float(total_steps) * 100.0; };
		virtual void OnStepDone() = 0;

	private:
		int total_steps;
		int steps_done;
};
```

If I test this code in C++ I end up with this C++ code:
``` C++
class CppProgress : public Progress
{
	public:
		CppProgress(int s) : Progress(s) {};
		virtual ~CppProgress() {};

		virtual void OnStepDone() { printf("Current percent: %f\n", this->Percent()); fflush(stdout); };
};

void ProgressTest(Progress *p, int steps) {
	for (int step = 0; step < steps; step++) {
		printf("Step %d done.\n", step + 1);
		fflush(stdout);
		p->StepDone();
	}
}
```

The output of the C++ test is:
```
Step 1 done.
Current percent: 20.000000
Step 2 done.
Current percent: 40.000000
Step 3 done.
Current percent: 60.000004
Step 4 done.
Current percent: 80.000000
Step 5 done.
Current percent: 100.000000
```

If I try to implement similar Go test code then I wonder how I would access the C++ Percent() method. My example Go code looks like this:
``` Go
type GoProgress struct{}

func (p *GoProgress) OnStepDone() {
	// How to call Percent()? Percent is not a method on GoProgress.
	fmt.Printf("Current percent: %f\n", 0.0)
}

func MakeProgress(steps int) Progress {
	return NewDirectorProgress(&GoProgress{}, steps)
}
```

@ianlancetaylor 
Ian, could you shed some light on this? How can I call a C++ method from within a Go method on a director? Is the documentation wrong or did I miss something essential?

**Comment by michael-schaller** [comment]
I've played a bit with this problem and the cleanest solution I could come up with so far is this one:
``` Go
type GoProgress struct {
	Progress
}

func (gp *GoProgress) IsGoProgress() {}

func (gp *GoProgress) OnStepDone() {
	fmt.Printf("Current percent: %f\n", gp.Percent())
}

func NewGoProgress(steps int) *GoProgress {
	gp := &GoProgress{}
	p := NewDirectorProgress(gp, steps)
	gp.Progress = p
	// Note: Now gp and p form a cycle and runtime.SetFinalizer doesn't work
	// anymore on either. This is unfortunate because this means a finalizer
	// can't be used to automatically free Progress.
	return gp
}

func DeleteGoProgress(gp *GoProgress) {
	DeleteDirectorProgress(gp.Progress)
	gp.Progress = nil // This breaks the cycle between gp and p.
}
```

Unfortunately this solution has the flaw that runtime.SetFinalizer can't be used to automatically free Progress as GoProgress and the underlying Progress form a cycle. I wished Go would support weak references or there would be a runtime.SetCycleBreakingFinalizer because then a finalizer on GoProgress would call DeleteGoProgress which would break the cycle.

Ian, what do you think?

**Comment by michael-schaller** [comment]
@ianlancetaylor friendly ping.

**Comment by ianlancetaylor** [comment]
I have nothing useful to add.  As far as I know, you are correct: if you want to call C++ methods from the Go methods, you need to hold a copy of the value created by NewDirectorType, and call methods on that.  You're right that this means that finalizers will be unreliable; the only fix I see is to define a Go type that holds an instance of the Go type passed NewDirector, and the C++ pointer, and send everything through that type.

**Comment by michael-schaller** [comment]
Gotcha. Why didn't I think of that? Updated example:
``` Go
type GoProgress struct {
	// Embedding a "patched" Progress object is the Go "equivalent" of
	// inheritance.
	Progress
}

func (gp *GoProgress) IsGoProgress() {
	// This method differentiates GoProgress from Progress and so a Progress
	// object can't be used where a GoProgress object is required. A GoProgress
	// object can still be used where a Progress object is required.
}

type overwriteOnProgress struct {
	// The "patched" Progress object is embedded here as well to allow Go
	// methods that overwrite C++ methods to use the rest of the underlying
	// Progress C++ object.
	Progress
}

func (oop *overwriteOnProgress) OnStepDone() {
	fmt.Printf("Current percent: %f\n", oop.Percent())
}

func NewGoProgress(steps int) *GoProgress {
	// Create "patched" Progress object (pp) that has selected virtual methods
	// overwritten with Go methods (oop). This forms a cycle between the
	// "patched" Progress object (pp) and the overwritten methods on Progress
	// (oop).
	oop := &overwriteOnProgress{}
	pp := NewDirectorProgress(oop, steps) // "patched" Progress object
	oop.Progress = pp

	// Embed the "patched" Process object in an GoProgress object so that
	// the type system can properly distinguish between a Progress and a
	// GoProgress object.
	gp := &GoProgress{Progress: pp}
	runtime.SetFinalizer(gp, deleteGoProgress)
	return gp
}

func deleteGoProgress(gp *GoProgress) {
	DeleteDirectorProgress(gp.Progress)
}
```

The new code example nearly feels like proper inheritance. :-)

The only thing that is missing is a Go equivalent for the "super" method. In this example SWIG automatically creates the CppProgress.SwigGetProgress() "super" method. My first guess would be that I could call GoProgress.Swigcptr() and cast it to SwigcptrProgress. That should give me an "unpatched" Progress object... I would need to test that though...

Anyhow... Ian, how do you like the new code example? Would you like to see something like that in the SWIG documentation?

**Comment by ianlancetaylor** [comment]
Sure, something like that looks good for the docs.  Thanks.

SWIG should already give you a function that you can use to call the super method.  In this case there should be a DirectorProgressOnStepDone function whose first argument is type Progress.

**Comment by michael-schaller** [comment]
Great. I'll look into updating the documentation and send you a pull request... Can be 1-2 weeks though. ;-)

**Comment by michael-schaller** [comment]
Hi Ian,

I'm currently working on easy to understand example code for the documentation update and I'm puzzled by one thing.

I have an abstract C++ class named FooBarAbs and SWIG doesn't create a constructor wrapper for it as long as the director feature is disabled. So far so expected. As soon as I enable the director feature for the FooBarAbs class SWIG creates the constructor wrapper NewFooBarAbs. If I try to use this constructor I'm getting the Go panic "accessing abstract class or protected constructor".

Ian, why does SWIG create NewFooBarAbs and NewDirectorFooBarAbs in this case if NewFooBarAbs is seemingly useless? Is this a bug or is there some intention/use case behind it?

Best,

Michael


The C++ class definition is:
``` C++
class FooBarAbs
{
public:
	FooBarAbs() {};
	virtual ~FooBarAbs() {};

	virtual std::string FooBar() {
		return this->Foo() + ", " + this->Bar();
	};

protected:
	virtual std::string Foo() = 0;
	virtual std::string Bar() = 0;
};
```

Code generated with director feature **disabled**:
``` Go
type FooBarAbs interface {
	Swigcptr() uintptr
	SwigIsFooBarAbs()
	FooBar() (_swig_ret string)
}

func DeleteFooBarAbs(arg1 FooBarAbs) {...}
```

Code generated with director feature **enabled**:
``` Go
type FooBarAbs interface {
	Swigcptr() uintptr
	SwigIsFooBarAbs()
	DirectorInterface() interface{}
	FooBar() (_swig_ret string)
}

func NewFooBarAbs() (_swig_ret FooBarAbs) {...} // Panics because the class is abstract.
func DeleteFooBarAbs(arg1 FooBarAbs) {...}

func NewDirectorFooBarAbs(v interface{}) FooBarAbs {...}
func DeleteDirectorFooBarAbs(arg1 FooBarAbs) {...}

func DirectorFooBarAbsFooBar(p FooBarAbs) string {...}
```

**Comment by ianlancetaylor** [comment]
I think it's a bug.  I can't think of any reason to create NewFooBarAbs.

**Comment by michael-schaller** [comment]
I also couldn't think of a reason why this would be useful. Reading the director documentation for other languages like Java, C# or Python didn't reveal an use case either.

Ian, shall I open a bug for you for this issue?

**Comment by ianlancetaylor** [comment]
Sure, thanks.

**Comment by michael-schaller** [comment]
Back to this issue. Ian, I have some more questions about the design of the director implementation.

Let's assume this example C++ class:
``` C++
class Example
{
public:
	Example() {};
	virtual ~Example() {};
};
```

With the director feature enabled this Go interface will be generated for the Example class:
``` Go
type Example interface {
        Swigcptr() uintptr
        SwigIsExample()
        DirectorInterface() interface{}
}
```

Furthermore two types implement the Example interface.
The first implementation is very close to how the wrapper code without the director feature looks like:
``` Go
type SwigcptrExample uintptr

func (p SwigcptrExample) Swigcptr() uintptr {
        return (uintptr)(p)
}

func (p SwigcptrExample) SwigIsExample() {
}

func (p SwigcptrExample) DirectorInterface() interface{} {
        return nil
}

func NewExample() (_swig_ret Example) {
        var swig_r Example
        swig_r = (Example)(SwigcptrExample(C._wrap_new_Example_example_61a265aabc5980ce()))
        return swig_r
}

func DeleteExample(arg1 Example) {
        _swig_i_0 := arg1.Swigcptr()
        C._wrap_delete_Example_example_61a265aabc5980ce(C.uintptr_t(_swig_i_0))
}
```

The second implementation is the actual director implementation:
``` Go
type _swig_DirectorExample struct {
        SwigcptrExample
        v interface{}
}

func (p *_swig_DirectorExample) Swigcptr() uintptr {
        return p.SwigcptrExample.Swigcptr()
}

func (p *_swig_DirectorExample) SwigIsExample() {
}

func (p *_swig_DirectorExample) DirectorInterface() interface{} {
        return p.v
}

func NewDirectorExample(v interface{}) Example {
        p := &_swig_DirectorExample{0, v}
        p.SwigcptrExample = SwigcptrExample(C._wrap__swig_NewDirectorExampleExample_example_61a265aabc5980ce(C.int(s$
        return p
}

func DeleteDirectorExample(arg1 Example) {
        _swig_i_0 := arg1.Swigcptr()
        C._wrap_DeleteDirectorExample_example_61a265aabc5980ce(C.uintptr_t(_swig_i_0))
}

//export Swiggo_DeleteDirector_Example_example_61a265aabc5980ce
func Swiggo_DeleteDirector_Example_example_61a265aabc5980ce(c int) {
        swigDirectorLookup(c).(*_swig_DirectorExample).SwigcptrExample = 0
        swigDirectorDelete(c)
}
```

Questions:
1) Why are the two implementations for the Example interface completely independent? For an example why doesn't NewExample look like this?
``` Go
func NewExample() (_swig_ret Example) {
        return NewDirectorExample(nil)
}
```
Is this because the code generation via SWIG is easier this way or is this because of some sort of backwards compatibility?


2) What is the difference between DeleteExample and DeleteDirectorExample? Is the only real difference the swigDirectorDelete call? Isn't it dangerous to even have DeleteExample in case of a director? In theory a user could use NewDirectorExample and then use DeleteExample to free it. This wouldn't run swigDirectorDelete though...


3) Why isn't there a "Super" or "Unpatched" method like this?
``` Go
func (p *_swig_DirectorExample) Super() Example {
        return &_swig_DirectorExample{p.SwigcptrExample, nil}
}
```
Wouldn't that be better than several DirectorExample* functions?

**Comment by ianlancetaylor** [comment]
1) There simply isn't any reason to tie a normal Example to the version of Example that implements the director feature.  It is also true that SWIG code generation is easier that way.

2) DeleteExample and DeleteDirectorExample both exist as counterparts to NewExample and NewDirectorExample.  As far as I can see the right thing will happen if you accidentally pass the result of NewDirectorExample to DeleteExample.  Either way the virtual destructor will be called.  But it's true that it might not work if the destructor is not virtual.  So, don't do that.

3) I didn't think of having a Super method.  I think it would work.

The SWIG support was mostly hacked together until it worked and passed the SWIG testsuite.  Don't be too surprised by a lack of clear design.

**Comment by michael-schaller** [comment]
Hmm... I guess the answer to my next question is "no" because of backwards compatibility but no harm in asking anyway... ;-)

So how about changing the director design before documenting it completely?

**Comment by ianlancetaylor** [comment]
How would you propose changing it?

As you say, removing the the existing Director<Class><Function> methods would not be appropriate, because it could break existing code.

**Comment by michael-schaller** [comment]
That depends on the question if we can deprecate functions by means of displaying a warning.
Then I would propose the following for directors:

1) Let NewExample just call NewDirectorExample(nil). NewDirectorExample stays unchanged.
2) Let DeleteExample do what currently DeleteDirectorExample does. The new DeleteDirectorExample just calls DeleteExample and prints a deprecation warning that DeleteExample should be used instead.
3) Deprecate the DirectorInterface method unless it serves any purpose I'm not aware of. If it is needed can it be made private?
4) Add an Undirected method (the Super/Unpatched method we've discussed). I'm not sure if Undirected should be private though.
5) Deprecate the DirectorExample* functions. Mention in the deprecation warning that the Undirected method should be used.

This would give us the following for the Example class:
``` Go
type Example interface {
        Swigcptr() uintptr
        SwigIsExample()
        DirectorInterface() interface{}  // Deprecated and maybe private
        Undirected() Example  // Maybe private
}

func NewExample() (_swig_ret Example) {
        return NewDirectorExample(nil)
}

func NewDirectorExample(v interface{}) Example {...}

func DeleteExample(arg1 Example) {
        // Same code as previously DeleteDirectorExample
        ...
}

func DeleteDirectorExample(arg1 Example) {
        os.StdErr.WriteString("DeleteDirectorExample is deprecated and will be removed by XXX. Use DeleteDirector instead.")
        DeleteDirector(arg1)
}

// Deprecated DirectorExample* functions.
```

That should make directors a lot more straightforward to use in Go. Furthermore the deprecated 
functions/methods could be removed by a specific date or SWIG version. I would propose SWIG 4.0.

What do you think Ian? Would it be worth the effort?

**Comment by ianlancetaylor** [comment]
I guess I don't understand why your proposal makes things significantly different for the person writing SWIG files.  What becomes easier?

**Comment by michael-schaller** [comment]
Sorry for not elaborating on that, Ian.

1. Construction/destruction is more straightforward. In any case there is only one destructor and so there is no confusion which one to use. Enabling the director feature only adds a second constructor that is only used if a "patched" version of the object is needed. This makes it easy to use the wrapper in an "unpatched" and "patched" context.

2. The DirectorExample* functions to call the "unpatched" methods are weird to use. It is a lot more natural to call an Undirect method that gives one the same interface with the undirected methods. This also makes the code a lot more readable because frankly "Director<ClassName><MethodName>" isn't great to read and if you have classes or methods that are similar it can be really hard to distinguish between these functions.

**Comment by ianlancetaylor** [comment]
Case 1 makes sense to me, except that for backward compatibility we would keep both destructors anyhow.

Case 2 I don't personally find convincing.  it would be a better design to start with, but the advantages don't seem to me to be sufficiently compelling to force code to change.

**Comment by michael-schaller** [comment]
> it would be a better design to start with

That is exactly the point I'm trying to make. :-)

So far neither case 1 or case 2 have any documentation whatsoever and hence it can be that someone is currently using the wrong destructor and/or completely missed the "unpatched" functions as they are not part of the interface that represents a C++ class.

To be frank I wonder who is successfully using the director feature at the moment... I couldn't find any public project on searchcode.com - besides SWIG examples - that would use a director in Go...

**Comment by ianlancetaylor** [comment]
I know there is code inside Google that uses directors, and it is possible that there is code elsewhere as well.

**Comment by michael-schaller** [comment]
Yes, that's why I've proposed to not break the existing code, but to print deprecation warnings. The new code can then be documented and the old code can be removed later. Both code path can coexist for a while...

**Comment by ianlancetaylor** [comment]
I'm sorry to be annoying about this, but I find that deprecation warnings are completely useless.  They are simply buried in a blizzard of build outputs.

If the current code were broken and could not be used correctly, we would change it.  But it's not broken, so let's not change it.

**Comment by michael-schaller** [comment]
> I'm sorry to be annoying about this, but I find that deprecation warnings are completely useless.

You're not annoying at all. On the contrary I value the constructive discussion with you.

> They are simply buried in a blizzard of build outputs.

Agreed. After all that's why the Go compiler doesn't print warnings.

> But it's not broken, so let's not change it.

Is there an alternative, like having a %feature("newdirector") and %feature("olddirector") to have two code paths? %feature("director") could then default to %feature("olddirector") for the time being but the %feature("newdirector") would be documented...

**Comment by ianlancetaylor** [comment]
I've thought about it but I'm having a hard time feeling comfortable with it.  The suggested new API is really only a little bit better.  I do not expect people to write large amounts of SWIG wrapper code using directors.  I'm not convinced that it's worth making the system more complex.

**Comment by michael-schaller** [comment]
Alrighty. That is absolutely fair. At least no one can complain that we didn't discuss it. ;-)
Ian, I'll send you a pull request in the next days with the new documentation...

**Comment by michael-schaller** [comment]
Ian, thank you for the review and merge.  Don't worry about the time it took.  This was certainly low priority and not the easiest topic. ;-)

Before we close this bug how about the existing 'callback' and 'extend' examples?  I didn't update those with the last pull request and they aren't on par with the updated documentation.  Would you like me to update these as well or is something even obsolete and should be deleted?

**Comment by ianlancetaylor** [comment]
I suspect that they can be deleted.  Do you see anything useful in them that isn't in your new example?

**Comment by michael-schaller** [comment]
I'll have a look tomorrow and send you a pull request.  Do you see any issue with just deleting them?  Someone might have linked to these examples and removing them would break these links...

**Comment by ianlancetaylor** [comment]
I'm not worried about deleting them.

**Comment by michael-schaller** [comment]
I had a look on the 'callback' and 'extend' examples and both don't add anything that wouldn't be covered by the new director documentation/example.  I've opened pull request #486 to remove these examples.

Furthermore the 'callback' example has been copied to the Go source tree:
https://golang.org/misc/swig/callback/

@ianlancetaylor 
1. Should the callback example also be deleted from the Go source tree?  Would you like to see a different example added to the Go source tree?
2. Please review pull request #486.  Please also have a look on the whole ```Examples/go/index.html``` file if it needs further updates with regards to the build commands.

**Comment by ianlancetaylor** [comment]
The example in the Go source tree is mainly a sanity check.  I don't think there is any real need to update it.

I updated Examples/go/index.html, thanks for pointing it out.

**Comment by michael-schaller** [comment]
The examples in the Go source tree are IMHO a bit more than a sanity check as the Swig documentation links them as well:
http://www.swig.org/Doc3.0/SWIGDocumentation.html#Go_examples

Do you still think that this is fine?  Shouldn't there be more Swig sanity checks in the Go source tree anyway?

**Comment by ianlancetaylor** [comment]
I forgot about the link from the SWIG docs.  I suppose I don't care much one way or another.  I'd be happy to remove that reference from the SWIG docs.

The SWIG sanity checks in the Go source tree are somewhat helpful but they are not run by default and are not run on the builders.  That would need to be addressed before any thought of expanding them.

**Comment by michael-schaller** [comment]
How about removing the Swig examples from the Go source tree and replacing them with a script that fetches and uses the examples from the Swig source tree?  Then there would only be one canonical location for these examples...

**Comment by ianlancetaylor** [comment]
It's important to be able to run Go tests without a network connection.

**Comment by michael-schaller** [comment]
How about an automatic sync that happens from time to time like the automatic update of the contributors file?

**Comment by ianlancetaylor** [comment]
There are too many examples in the SWIG source tree.  There is no need to copy them all to the Go source tree.  The point of having them in the Go tree is to test that changes to the Go tree don't break SWIG, it's not to replace the SWIG documentation.

Since the point is to test the Go/SWIG interaction, an automated sync would not make sense.  An occasional manual sync, looking at the results to see if it makes sense, would be fine.

**Comment by michael-schaller** [comment]
Makes sense.  What does that mean for the current examples in the Go source tree?  Is an update/sync needed?  If yes, how would that look like in your opinion?  Would you remove the 'callback' example and add the 'director' example instead? ...?

**Comment by wsfulton** [comment]
Please do not delete these examples. All the target languages that support directors have these two and I would like common examples across all target languages with identical inputs and similar output. If you want to add more examples perhaps you should add them as test cases instead. Alternatively updating the current examples across all target languages is another option.

**Comment by michael-schaller** [comment]
William, I understand your wish to keep the examples similar across target languages but looking at the examples for various target languages this is clearly currently not the case.  Because of this I don't understand why new/more examples should be added as tests or why all current examples should be updated across all target languages...

I'm happy to revert the last commit and to update the 'callback' and 'extend' examples to match the 'director' example.  I'm not happy to touch other target languages than Go as this is about Go's documentation and examples.

**Comment by michael-schaller** [comment]
@wsfulton @ianlancetaylor 
Ian, William, could you two please discuss this matter and let me know what you've agreed on?

**Comment by wsfulton** [comment]
I don't really understand why these two examples were replaced. Is it just to provide fewer examples?

Why does the new example have to use Foo and Bar in the name? These names are just unimaginative, at least the old examples had some basic idea using normal English names that they were trying to solve. Please use something more tangible.

**Comment by ianlancetaylor** [comment]
@michael-schaller Let's revert the commit and restore the examples.  Keeping similar examples across several languages, even if not identical, is a compelling argument.  Thanks.

**Comment by michael-schaller** [comment]
@wsfulton The new 'director' example has been added as part of the new documentation for how to use the director feature with Go: https://htmlpreview.github.io/?https://github.com/swig/swig/blob/master/Doc/Manual/Go.html#Go_director_classes

The example is deliberately simple and covers all the necessary points that an user needs to know to safely use the director feature.  The previous documentation and the 'callback' and 'extend' examples were dangerous under this regard as they weren't type safe (see 23.4.7.6).  Once the documentation was updated the 'callback' and 'extend' examples would have also needed an update.  To Ian and me they looked obsolete though and have been removed in favor of the new 'director' example.

William, does that sufficiently explain why the old director examples got removed and a new one got added?

**Comment by michael-schaller** [comment]
@ianlancetaylor Alrighty. With the next pull request I will revert the removal of the 'callback' and 'extend' examples and will update them to match the new documentation.

**Comment by wsfulton** [comment]
I see. As we are putting the extend and callback examples back in, it sounds like they should be fixed to be typesafe. Presumably that is possible?

Can you please use proper English too in the Example code, FooBarAbs should be FooBarAbstract from my reading of the docs, I had no idea what Abs was without reading the docs.

**Comment by michael-schaller** [comment]
@wsfulton It's possible to update the old examples. Renaming FooBarAbs to FooBarAbstract SGTM. I'll add it to the pull request as well.

**Comment by michael-schaller** [comment]
@ianlancetaylor 
Ian, thank you for merging the pull request.

How about the examples in the Go source tree now that the examples in the Swig source tree have been updated?

Furthermore do you see any chance that the examples in the Swig source tree could use 'go build' and '.swig/.swigcxx' interface files?  Currently the fact that 'go build' has support for Swig and uses '.swig/.swigcxx' interfaces files (and not the Swig typical '.i') is a bit hidden in the 'Go Output Files' section of the documentation and hence someone new to Swig and Go might overlook this easy way to get started.

**Comment by ianlancetaylor** [comment]
I think the examples in the Go tree are best handled as simple sanity tests to make sure that SWIG works.  I don't want to be fiddling around updating them.  Let's keep the documentation in SWIG.

The problem with using go build in the SWIG example directory is that older versions of Go don't support using it with SWIG.  At some point we can stop worrying about those old versions, but for now I'd rather be able to easily test that old versions of Go work with current versions of SWIG.

**Comment by michael-schaller** [comment]
Alrighty.  So the examples in the Go source tree stay as they are and the examples in the Swig source tree won't use 'go build' for the foreseeable time.

How about removing the link to the examples in the Go source tree from the documentation then?
How about reworking/splitting the 'Go Output Files' section of the documentation to recommend to use 'go build' as a first step?

**Comment by ianlancetaylor** [comment]
> How about removing the link to the examples in the Go source tree from the documentation then?
> How about reworking/splitting the 'Go Output Files' section of the documentation to recommend to use 'go build' as a first step?

Both sound fine to me.  Thanks.

**Comment by michael-schaller** [comment]
Looks like this bug is done for good.  I have a few more topics with regards to SWIG and the Go documentation.  How about these topics:
* Add C++ exception handling to the Go documentation.
* Discuss if there is a way to extend a Go interface that represents a C++ class via the SWIG interface.  This would make it easier to add Go methods to a C++ class.  The currently documented way requires a lot of work and it would be nice to have something easier.
* Discuss Go as a SWIG source language.  Now that Go 1.5 can be used from C it would be awesome if Go could be made a source language so that SWIG can generate wrappers for all currently supported target languages so that they can interact with Go.

Ian, what do you think about these topics?  Should I open bugs for these to discuss them?

**Comment by ianlancetaylor** [comment]
I guess I don't know what there is to say about C++ exception handling in Go.  The gc and gccgo compilers actually behave differently there.  Do the other SWIG languages discuss C++ exceptions?

I suppose I'm fine with a better mechanism for extending a C++ class, but it's not something I plan to work on.  It's an amusing feature but it's really hard to imagine a real program using it.

I agree that it would be cool to make Go a SWIG source language but, again, I don't plan to work on it.

**Comment by michael-schaller** [comment]
I think we don't need to write much about C++ exception handling in Go.  Just sorts of the best practices and/or a small example.  What do you mean by "gc and gccgo compilers actually behave differently there"?  If the handling on the Go side is different per compiler should maybe the recommendation be to deal with C++ exceptions on the C++ side?  As a side note most target languages have a subsection about C++ exception handling.

When it comes to extending the wrapper for a C++ class then I only know that the C# target language supports that with the help of the 'cscode' typemap:  http://www.swig.org/Doc3.0/SWIGDocumentation.html#CSharp_extending_proxy_class
If there would be a similar typemap for Go then it would be easy to extend a Go interface that represent a C++ class.  Just use the typemap to add a method to the Go interface and implement the new method in a standalone .go file in the same package.  That would be a lot easier than what we currently have documented:  http://www.swig.org/Doc3.0/SWIGDocumentation.html#Go_adding_additional_code
The question that remains if this change is worth the effort...

I wonder how Go as a SWIG source language would work.  First of all SWIG would need to "understand" Go code in SWIG interface files.  Functions aren't easy though as the '//export' needs to be directly before the function definition and thus '//export' would let SWIG generate a lot of "pass-through" functions to call the actual Go functions.  Arrays I hope shouldn't be a problem but I'm not so sure about slices and maps.  On the Go side functions can be written to access/modify values of these types but how these types would be represented on the target language side is I guess something that would need to be implemented for each and every target language.  For an instance for a Python wrapped Go map SWIG would need to generate wrapper code so that the Go map is accessible like a Python dict.  Even worse would be the situation with structs/methods/interfaces.  Representing these properly in target languages might be a major pain...  Maybe it would be better to make the gomobile/bind stuff standalone and extend it instead of bothering with SWIG.  Having something like this might increase the impact of Go drastically as it allows to integrate Go code into existing non C/C++ projects and gives the possibility to migrate them to Go...

I can add C++ exception handling to the documentation as long as it isn't much  work.  I can also look into extending Go interfaces easily if you think it can be done with minimal effort and you think it is worth the effort.  Having some kind of tool that allows to wrap Go code to make it accessible from other target languages would make a lot of sense to me and if you can see a need for it we might should discuss this as a 20% project within Google...

Ian, what do you think?

**Comment by wsfulton** [comment]
The more documentation there is for each target language the better, I think. Especially if it has small examples solving real world problems. 

The 'cscode' typemap has turned out not to be a good approach to adding target language specific code to proxy classes as it can only be used once. A better approach is used in python with %shadow and %pythoncode which are just using %insert.

A large part of SWIG is the parser which parses C and C++. All the handling in the target languages would have to be quite different too. Hence extending SWIG to support other input languages would require a whole new tool in my mind. I wouldn't choose the SWIG technology again for another input language either, I'd base it around one the existing Go compilers.

**Comment by ianlancetaylor** [comment]
Yes, I think that for Go any C++ exceptions should be handled on the C++ side.

**Comment by michael-schaller** [comment]
After thinking thoroughly about these topics...

I think that Go shouldn't be a source language for SWIG for the reasons William mentioned.  I'll experiment with better extension of a Go interface that represents a C++ class once I have the need and more importantly good examples.  Last but not least I'm struggling a bit with C++ exceptions as I don't regularly have to deal with them and hence I think that I'm not a good choice to document them.  Because of that I'll open an issue to get exception handling document but won't work on it myself (sorry).

And that's it for this bug. Finally. ;-)
