### ISSUE TITLE
swig 3.0.5 handles varargs incorrectly

### ISSUE THREAD

**Issue by vharron** [swig/swig#420]
Host OS: OS X 10.9.5
Distribution: homebrew
Version: 3.0.5
XCode: 6.2 (others probably work too)

Repro steps:
% git clone http://llvm.org/git/lldb.git
% cd lldb
% xcodebuild -configuration Debug -target desktop

% egrep SetErrorStringWithFormat scripts/interface/SBError.i 
    SetErrorStringWithFormat (const char *format, ...);

SWIG 3.0.5:
% egrep -A2 SetErrorStringWithFormat build/Debug/lldb.py 
    def SetErrorStringWithFormat(self, format):
        """SetErrorStringWithFormat(SBError self, str const * format) -> int"""
        return _lldb.SBError_SetErrorStringWithFormat(self, format)

SWIG 3.0.2 or 2.0.11:
vharron-macpro3:test vharron$ egrep -A2 SetErrorStringWithFormat
../DerivedData/lldb/Build/Products/Debug/lldb.py 
    def SetErrorStringWithFormat(self, *args):
        """SetErrorStringWithFormat(SBError self, str const * format) -> int"""
        return _lldb.SBError_SetErrorStringWithFormat(self, *args)

**Comment by vadz** [comment]
As always, having a [simple example](http://sscce.org/) reproducing the problem would be helpful, working with entire lldb is not really simple. In particular, I think the problem might be related to use of some non-default SWIG options but I don't even know what is the exact command line used in this case.

**Comment by wsfulton** [comment]
Please re-open with a simple example, we don't have xcodebuild.
