### ISSUE TITLE
SWIG fails to correctly handle multiple inheritance in the target language

### ISSUE THREAD

**Issue by Ingener74** [swig/swig#422]
``` c++
#include <iostream>

using namespace std;

void A::testA() {
    cout << __PRETTY_FUNCTION__ << endl;
}

void B::testB() {
    cout << __PRETTY_FUNCTION__ << endl;
}

void C::testC() {
    cout << __PRETTY_FUNCTION__ << endl;
}

void D::testD() {
    cout << __PRETTY_FUNCTION__ << endl;
}

void E::testE(B*) {
    cout << __PRETTY_FUNCTION__ << endl;
}

void F::testF(C*) {
    cout << __PRETTY_FUNCTION__ << endl;
}

void T::testT(D*) {
    cout << __PRETTY_FUNCTION__ << endl;
}

```

``` c++
#ifndef APPS_PYTHON_SWIGTEST_SWIGFOO_H_
#define APPS_PYTHON_SWIGTEST_SWIGFOO_H_
#ifdef SWIG
    %feature("director") A;
    %feature("director") B;
    %feature("director") C;
    %feature("director") D;
#endif

class A {
public:
    virtual ~A() = default;
    virtual void testA();
};

class B: virtual public A {
public:
    virtual ~B() = default;
    virtual void testB();
};

class C: virtual public A {
public:
    virtual ~C() = default;
    virtual void testC();
};

class D: virtual public A {
public:
    virtual ~D() = default;
    virtual void testD();
};

class E {
public:
    virtual ~E() = default;
    virtual void testE(B*);
};

class F {
public:
    virtual ~F() = default;
    virtual void testF(C*);
};

class T {
public:
    virtual ~T() = default;
    virtual void testT(D*);
};


#endif /* APPS_PYTHON_SWIGTEST_SWIGFOO_H_ */
```

``` swig
%module(directors="1") SwigTest
%{

#include "SwigFoo.h"

%}

%include "SwigFoo.h"
```
# first case

``` python
#!/usr/bin/env python

import SwigTest as st

class Test(st.B, st.C, st.D):
    def __init__(self):
        st.B.__init__(self)
        st.C.__init__(self)
        st.D.__init__(self)

def main():

    test = Test()

    e = st.E()
    e.testE(test)

    f = st.F()
    f.testF(test)

    t = st.T()
    t.testT(test)

    pass

if __name__ == '__main__':
    main()
```
### output

Traceback (most recent call last):
  File "/home/pavel/workspace/Algoritms-Patterns-Tests/apps/python/swig_test.py", line 27, in <module>
    main()
virtual void E::testE(B*)
  File "/home/pavel/workspace/Algoritms-Patterns-Tests/apps/python/swig_test.py", line 19, in main
    f.testF(test)
  File "/home/pavel/workspace/Algoritms-Patterns-Tests/build-linux/apps/python/SwigTest/SwigTest.py", line 325, in testF
    return _SwigTest.F_testF(self, arg2)
TypeError: in method 'F_testF', argument 2 of type 'C *'
# second case

``` python
#!/usr/bin/env python

import SwigTest as st

class Test(st.B, st.C, st.D):
    def __init__(self):
        st.C.__init__(self)
        st.B.__init__(self)
        st.D.__init__(self)

def main():

    test = Test()

    e = st.E()
    e.testE(test)

    f = st.F()
    f.testF(test)

    t = st.T()
    t.testT(test)

    pass

if __name__ == '__main__':
    main()
```
### output

Traceback (most recent call last):
  File "/home/pavel/workspace/Algoritms-Patterns-Tests/apps/python/swig_test.py", line 27, in <module>
    main()
  File "/home/pavel/workspace/Algoritms-Patterns-Tests/apps/python/swig_test.py", line 16, in main
    e.testE(test)
  File "/home/pavel/workspace/Algoritms-Patterns-Tests/build-linux/apps/python/SwigTest/SwigTest.py", line 304, in testE
    return _SwigTest.E_testE(self, arg2)
TypeError: in method 'E_testE', argument 2 of type 'B *'
# third case

``` python
#!/usr/bin/env python

import SwigTest as st

class Test(st.B, st.C, st.D):
    def __init__(self):
        st.B.__init__(self)
        st.D.__init__(self)
        st.C.__init__(self)

def main():

    test = Test()

    e = st.E()
    e.testE(test)

    f = st.F()
    f.testF(test)

    t = st.T()
    t.testT(test)

    pass

if __name__ == '__main__':
    main()
```
### output

Traceback (most recent call last):
  File "/home/pavel/workspace/Algoritms-Patterns-Tests/apps/python/swig_test.py", line 27, in <module>
    main()
  File "/home/pavel/workspace/Algoritms-Patterns-Tests/apps/python/swig_test.py", line 22, in main
    t.testT(test)
  File "/home/pavel/workspace/Algoritms-Patterns-Tests/build-linux/apps/python/SwigTest/SwigTest.py", line 346, in testT
    return _SwigTest.T_testT(self, arg2)
TypeError: in method 'T_testT', argument 2 of type 'D _'
virtual void E::testE(B_)
virtual void F::testF(C*)
### conclusion

multiple inheritance, the second call to the constructor takes an error

**Comment by ojwb** [comment]
Reproducible with current git master.

It looks to me like the problem here is actually that SWIG only seems to consider the parent type as determined by the first parent class constructor to be called, so in the first testcase `test` is a `B` and hence you can pass it to `E::testE(B*)` but not `F::testF(C*)`.  And similarly for the other two testcases.

**Comment by ojwb** [comment]
I found a patch in the old sourceforge patch tracker which had stalled because the submitter failed to respond when asked for a reproducer: https://sourceforge.net/p/swig/bugs/1379/

It turns out this is the same problem you've hit, and applying that patch to the appropriate place fixes your three examples.  Here's the patch I tested:

```
--- a/Lib/python/pyrun.swg
+++ b/Lib/python/pyrun.swg
@@ -785,6 +785,7 @@ SwigPyObject_append(PyObject* v, PyObject* next)
     PyErr_SetString(PyExc_TypeError, "Attempt to append a non SwigPyObject");
     return NULL;
   }
+  ((SwigPyObject *)next)->next = sobj->next;
   sobj->next = next;
   Py_INCREF(next);
   return SWIG_Py_Void();
```

I'll adapt your examples to make a regression testcase and the merge this patch.
