### ISSUE TITLE
The type or namespace name 'HandleRef' could not be found

### ISSUE THREAD

**Issue by radagastr** [swig/swig#423]
I use Swig to generate c# file from c++. If I use ClassLibrary as a project , I do not get any error but in order to support multi platform , I have to use PortableLibrary. However while using PortableLibrary generated c# files get errors which is " The type or namespace name 'HandleRef' could not be found ". I am using System.Runtime.InteropServices and there is mscorlib in my References. I do not know where is wrong? How can I solve this problem?

**Comment by wsfulton** [comment]
SWIG requires .NET 2 or later by default and uses HandleRef. It sounds like your environment doesn't support HandleRef. If so, what is the equivalent for HandleRef in PortableLibrary? Once you know this, you could rewrite the existing typemaps to use it. 

There are some alternative SWIG typemaps available on the swig-user mailing list by David Piepgrass for the .NET Compact framework (Windows mobile) that avoids HandleRef so please search for these from http://swig.org/mail.html as I think PortableLibrary has evolved out of Windows mobile.

**Comment by radagastr** [comment]
is there any example of how to rewrite typemaps so avoid HandleRef?
