### ISSUE TITLE
SWIG creating director for class with private destructor

### ISSUE THREAD

**Issue by tmaslach** [swig/swig#425]
I have the following simple case that doesn’t work – generating python code:  
## swigtest.i:

```
%{
#include "swigtest.h"
%}
%include "swigtest.h"
```
## swigtest.h

```
// I need a director generated for MyBase
class MyBase
{
public:
  MyBase() {}
  virtual ~MyBase() {}
};

// I don’t need (and can’t have) a director for MyDerived
class MyDerived : public MyBase // Comment out : public MyBase and it will work..
{
public:
  virtual void Test() {}
private:
  MyDerived() {}
  virtual ~MyDerived() {}
};
```

If one runs with the following command line:

```
swig -Ilib/python -Ilib/std -Ilib -c++ -python -modern -directors -module swigtest swigtest.i
```

and then build, I get a compiler error:

```
d:\software\swig_bugs\private_constructor\swigtest_wrap.cxx(3566) : error C2248: 'MyDerived::~MyDerived' : cannot access private member declared in class 'MyDerived'
```

If I comment out the ‘: public MyBase’, everything works fine. SWIG detects that MyDerived is not accessible, prints out a warning, and doesn’t wrap it. 

I believe the problem is that SWIG sees MyBases constrtor/destructor as public, so it thinks MyDerived (which inherits those) has an accessible constructor, destructor – thus creating a director for the class.  Of course, that is wrong, so compiler error.

This was found with swig2.0.11, I have no tried swig3.X

**Comment by ojwb** [comment]
With current git master, there's a warning from SWIG with or without the `: public MyBase`:

```
swigtest.h:11: Warning 517: Director class 'MyDerived' can't be constructed
```

And compilation fails in both cases.

The simple workaround is just to tell SWIG you don't want a director for `MyDerived` - modify `swigtest.i` like so:

```
%{
#include "swigtest.h"
%}
%feature(nodirector) MyDerived;
%include "swigtest.h"
```

SWIG should probably spot this and disable the director for itself.

**Comment by tmaslach** [comment]
As William asked for it, here is the message I get when I run swig against the header file with ": public MyBase" not commented out:

swigtest.h(9) : Warning 517: Director class 'MyDerived' can't be constructed

I get this warning in swig 2.0.10.  I have not tried 3.0 as I just got a new machine and am still setting it up..

**Comment by ojwb** [comment]
Same warning with current git master (and again with or without the `: public MyBase`).

> SWIG should probably spot this and disable the director for itself.

While it would be nice to auto-disable directors for `MyDerived` as well as warning, the point at which the warning is currently emitted is much too late to do that so that's not the trivial change one might hope.

There's a clear warning and it's easy to disable directors for individual classes, so given that this has seen no progress for 8 years I think it's most realistic to close this.
