### ISSUE TITLE
Enum initialized with enum generates invalid Java code

### ISSUE THREAD

**Issue by LindleyF** [swig/swig#431]
If a C++ file initializes one enum with another, using enumtypeunsafe.swg, incorrect java code is emitted:

C++:
namespace test {
class MyTest {
  enum {
     VALUE = 10
  };
  enum {
     OTHERVALUE = VALUE;
  }
};
}

Emits this Java:
public final static int OTHERVALUE = test::MyTest::VALUE;

which of course doesn't parse.

**Comment by wsfulton** [comment]
Your code doesn't compile. When corrected and adding in %javaconst, I can replicate what you report. The solution is to remove %javaconst(1) altogether or override it for the problematic cases as shown below.

```
%include <enumtypeunsafe.swg>

%javaconst(1);
%javaconst(0) test::MyTest::OTHERVALUE;

%inline %{
  namespace test {
    class MyTest {
    public:
      enum {
        VALUE = 10
      };
      enum {
        OTHERVALUE = VALUE
      };
    };
  }
%}
```
Please read the docs at http://swig.org/Doc3.0/Java.html#Java_enumerations

**Comment by LindleyF** [comment]
I eventually figured out that %javaconst was the problem, yes. It took a long time to track that down though.
