### ISSUE TITLE
Swig 3.0.5 generates broken C# code

### ISSUE THREAD

**Issue by darksylinc** [swig/swig#433]
Download the RakNet repository:
https://github.com/OculusVR/RakNet

Go to DependentExtensions/Swig and run:
MakeSwig.bat "../../Source"

It should run Swig and dump it in:
DependentExtensions\Swig\SwigOutput\SwigCSharpOutput

This is an example of the generated Packet.cs:
http://pastebin.com/JpGNr4S9

It uses 'HandleRef' and 'IntPtr' all over the place without full namespace and without declaring "using System.Runtime.InteropServices;" either which ends up in build errors.

Many other C# files share the same problem, making it a royal PITA to add the namespaces by hand.

**Comment by vadz** [comment]
SWIG does use `global::System.Runtime.InteropServices` prefix by default, if it doesn't generate it in your case there must be some reason, most likely a custom `imtype` typemap which doesn't use the correct prefix. But this must be specific to your code and you should be able to find (and fix) it there.

**Comment by darksylinc** [comment]
Thanks for the (very!) quick response. The code is not really mine. It's RakNet which was originally meant to be used with Swig 2.x
I'm not a Swig expert either.

I can see they do set custom imtypes in https://github.com/OculusVR/RakNet/blob/master/DependentExtensions/Swig/SwigInterfaceFiles/arrays_csharp.i

specifically, I can see they do:

%typemap(imtype)  CTYPE FIXED[] "IntPtr"

which looks very suspicious. Is there a "right" way to prefix it? or may be it's just
%typemap(imtype)  CTYPE FIXED[] "global::System.Runtime.InteropService.IntPtr" ??

**Comment by vadz** [comment]
You need to either fully qualify the type here or add a `using System.Runtime.InteropService;` to the generated code, which can be done using `csimports` typemap.

But while looking at this I realized there is [SWIG2_CSHARP](http://www.swig.org/Doc3.0/CSharp.html#CSharp_introduction_swig2_compatibility) that can be predefined to do the latter for you. I don't recommend using it though, it's easy enough to fix the custom typemaps and this is more future-proof.

In any case, this isn't a bug in SWIG, so I'm closing this one.
