### ISSUE TITLE
SWIG generate broken Python code with --builtin and -O

### ISSUE THREAD

**Issue by amaeldoe** [swig/swig#436]
Hi,

Since commit 416277b3a56646c2934ca9ee542a3f36d4f9a436, SWIG will generate broken Python code when --builtin and -O option are used :

<pre>
_prelude.cxx: In function ‘PyObject* _wrap_SwigPyIterator_incr(PyObject*, PyObject*)’:
_prelude.cxx:6107:62: erreur: invalid conversion from ‘int’ to ‘PyObject* {aka _object*}’ [-fpermissive]
     return _wrap_SwigPyIterator_incr__SWIG_1(self, argc, argv);
                                                              ^
_prelude.cxx:6107:62: erreur: too many arguments to function ‘PyObject* _wrap_SwigPyIterator_incr__SWIG_1(PyObject*, PyObject*)’
_prelude.cxx:6069:22: note: declared here
 SWIGINTERN PyObject *_wrap_SwigPyIterator_incr__SWIG_1(PyObject *self, PyObject *args) {
                      ^
_prelude.cxx: In function ‘PyObject* _wrap_SwigPyIterator_decr(PyObject*, PyObject*)’:
_prelude.cxx:6199:62: erreur: invalid conversion from ‘int’ to ‘PyObject* {aka _object*}’ [-fpermissive]
     return _wrap_SwigPyIterator_decr__SWIG_1(self, argc, argv);
                                                              ^
_prelude.cxx:6199:62: erreur: too many arguments to function ‘PyObject* _wrap_SwigPyIterator_decr__SWIG_1(PyObject*, PyObject*)’
_prelude.cxx:6161:22: note: declared here
 SWIGINTERN PyObject *_wrap_SwigPyIterator_decr__SWIG_1(PyObject *self, PyObject *args) {
</pre>

**Comment by vadz** [comment]
As always, it would be very helpful to have a minimal self-contained example reproducing the problem. Could you please make one?

**Comment by amaeldoe** [comment]
Sorry, I got no time to do that right now, but I will if I get some free time. However, as I understand it, it should be very straightforward to reproduce with a minimal C++ wrapped class using builtin and -O.

**Comment by wsfulton** [comment]
The test-suite reproduces this using SWIG_FEATURES="-O -builtin". I'll take a look...

**Comment by wsfulton** [comment]
It is a combination of these options: -fastunpack -modernargs -builtin with overloading such as
```
struct Hey {
  void hohum(int i = -1) {}
};
```
