### ISSUE TITLE
[C#] Directors and non-RTTI compilation

### ISSUE THREAD

**Issue by Sghirate** [swig/swig#437]
Currently the director implementation for C# relies on dynamic_casts, thus requiring RTTI to be enabled, when compiling the generated cpp code. However, I do not understand the need for dynamic_cast (instead of static_cast) in that context (to me it seems like the type in *_connect can't be much else than the derived director class) and with static_casts it is compiling and seems to function perfectly fine.

So my question would be:
Why do directors use *dynamic_cast* instead of *static_cast*? 
Am I missing/misunderstanding something?

If there is no reason against using static_cast, I would like to change that in order to allow for non-RTTI compilation.

**Comment by ojwb** [comment]
Closing in favour of PR #449.
