### ISSUE TITLE
Memory not being initialized when using C++ and typemaps in carrays.i

### ISSUE THREAD

**Issue by crayxt** [swig/swig#440]
Hi,
Commenting in closed PRs seemed like bad habit, opening a new issue.
In PR https://github.com/swig/swig/pull/208 @tsuna improved array_functions in file https://github.com/swig/swig/blob/master/Lib/carrays.i#L25 
In the same file at line https://github.com/swig/swig/blob/master/Lib/carrays.i#L84 I see almost the same function. Should it also be improved with adding () after the [nelements]?

thanks,

**Comment by wsfulton** [comment]
Yes, good spot. I'll fix these up plus a few more inconsistent memory initializations between C and C++ in the typemaps.
