### ISSUE TITLE
Command line parsing fails when using -external-runtime

### ISSUE THREAD

**Issue by t-moe** [swig/swig#441]
Normally I use swig like:

    swig -c++ -python  bla.i

Which runs fine. Now I wanted to add the external-runtime parameter:

     swig -c++ -python -external-runtime bla_wrap.h bla.i

Which gives me:

    swig error : Unrecognized option bla.i
    Use 'swig -help' for available options.

I can't specify a interface file anymore. No matter where I place it in the argument list.

I use Swig 3.0.5

**Comment by wsfulton** [comment]
You need to invoke swig to generate the runtime file separate to your interface file generation. See the docs, which I've just enhanced a little to clarify.

**Comment by t-moe** [comment]
ah, I see.
Thanks.
