### ISSUE TITLE
Can't parse function pointer typedef.

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [swig/swig#450]
I'm trying to parse a file using the following:

    swig -sexp -module foobar -o test.lisp test.h

I get the following error:

    test.h:1: Error: Syntax error in input(2).

The contents of test.h are:

    typedef int (char * callback_type) (int fd, char *buffer, int length);

This is similar to [this bug](https://github.com/swig/swig/issues/171), except it can't possibly be resolved by adding preprocessor definitions.

**Comment by ojwb** [comment]
That's not a valid function pointer typedef - the first `char` shouldn't be there - here's what GCC says:

```
test.c:1:14: error: expected identifier or ‘(’ before ‘char’
 typedef int (char * callback_type) (int fd, char *buffer, int length);
              ^
```

GCC and SWIG are both happy with:

```
typedef int (* callback_type) (int fd, char *buffer, int length);
```
