### ISSUE TITLE
GCC warning about uninitialized variable in overload functions dispatcher

### ISSUE THREAD

**Issue by oliora** [swig/swig#453]
Generated overload functions dispatcher causes warning under g++ 4.9.2, like `warning: ‘argv[0]’ may be used uninitialized in this function [-Wmaybe-uninitialized]`. My SWIG version is 3.0.2.

I propose a patch to fix this error: https://gist.github.com/oliora/b19f20c4b374e99be4af

PS. I did not tested the patch and I know nothing about how SWIG generates the wrapper, so probably this patch doesn't do what it should. But at least you can got my idea through it :)

**Comment by oliora** [comment]
Just to note, the overload functions dispatcher is alos used for C++ function having default parameters.

**Comment by Kagetsuki** [comment]
@oliora I think "fork → patch → test → pull request" may be a better way to get things done. 3.0.2 is also not the edge version - this may already be fixed. Please test on edge.

**Comment by ojwb** [comment]
Yes, a pull request against master is much better as we can see if the
tests pass in the automatic builds.

**Comment by ojwb** [comment]
Closing now we have a PR.
