### ISSUE TITLE
Website (swig.org) is down

### ISSUE THREAD

**Issue by ChristianSiegert** [swig/swig#466]
http://www.swig.org is down. Do you know when it will be up again?

**Comment by wsfulton** [comment]
Thanks for reporting this, I've asked Dave Beazley to take a look.

**Comment by wsfulton** [comment]
It might have something to do with Sourceforge being 'in disaster recovery mode' as posted on Twitter [#SourceForge](https://twitter.com/hashtag/SourceForge?src=hash)

**Comment by vadz** [comment]
SF seems to be back up.
