### ISSUE TITLE
Nested class not supported warning for protected classes

### ISSUE THREAD

**Issue by cj-mcdonald** [swig/swig#469]
Sig 3.0.6 contains a change to suppress warning 325 "Nested class not currently supported" when the nested class has already been explicitly ignored with "%ignore"; which is great as I prefer to explicitly ignore any nested classes or structs, rather suppress the warning globally.

But  it's not working for protected nested classes, as shown with the following example:

```
%module Nested

%ignore Parent::Nested1;
%ignore Parent::Nested2;

class Parent
{
public:
    struct Nested1 {};

protected:
    struct Nested2 {};
};
```

Warning 325 is always output for Nested2, regardless of the %ignore.
I'm generating Tcl wrappers.

**Comment by wkalinin** [comment]
Proposed fix is in https://github.com/swig/swig/pull/470

**Comment by wkalinin** [comment]
Merged the fix, seems to be harmless.
