### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64 clang

### ISSUE THREAD

**Issue by Cescfangs** [swig/swig#479]
>using Mac OS X 10.10.4 64bit

I tried following this [tutorial](http://www.swig.org/tutorial.html) to build a python module, I didn't intalled `gcc` complier, thought it would work with `clang`, however, when ran
`ld -shared example.o example_wrap.o -o _example.so `
I got the error meaagge: 'ld: symbol(s) not found for architecture x86_64'

**Comment by vadz** [comment]
It is definitely possible to use SWIG with clang. You don't even show which symbols are missing but my guess would be that you need to link with clang and not ld.

**Comment by Cescfangs** [comment]
tried with `clang` already, in fact I followed this [answer](http://stackoverflow.com/questions/14782925/compiling-c-with-swig-on-mac-os-x) which supposed to  work using:
`clang -lpython -dynamclib example.o example_wrap.o -o _example.so`

however, failed again with the same error:

`clang: warning: argument unused during compilation: '-dynamclib'
Undefined symbols for architecture x86_64:
  "_PyInstanceMethod_New", referenced from:
      _SWIG_PyInstanceMethod_New in example_wrap.o
  "_PyModule_Create2", referenced from:
      _PyInit__exam in example_wrap.o
  "_PyUnicode_Concat", referenced from:
      _SwigPyObject_repr in example_wrap.o
  "_PyUnicode_FromFormat", referenced from:
      _SwigPyPacked_repr in example_wrap.o
      _SwigPyPacked_str in example_wrap.o
      _SwigPyObject_repr in example_wrap.o
  "_PyUnicode_FromString", referenced from:
      _SWIG_Python_str_FromChar in example_wrap.o
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by vadz** [comment]
You have a typo in your options, see the first line.

**Comment by Cescfangs** [comment]
typo in `c` file?
```C
/* File: example.c */
#include "example.h"
int fact(int n) {
    if (n < 0){
   /* This should probably return an error, but this is simpler */
        return 0; }
    else  if (n == 0) {
            return 1;
                    }
    else {
            /* testing for overflow would be a good idea here */
            return n * fact(n-1);
          }
 }

```

**Comment by ojwb** [comment]
@Cescfangs did fixing that typo resolve your issue?

**Comment by Cescfangs** [comment]
No, I figured it out using distutils.

**Comment by ojwb** [comment]
OK, closing then.

**Comment by berezovskyi** [comment]
Same problem. Use `$(python3-config --ldflags)` instead of `-lpython`.

**Comment by yuanzeluo** [comment]
> Same problem. Use `$(python3-config --ldflags)` instead of `-lpython`.

tried but got `ld: -stack_size option can only be used when linking a main executable`, do you have any thoughts? Thanks!
