### ISSUE TITLE
[Lua] operator __lt__  wrapped, but disfunctional ?

### ISSUE THREAD

**Issue by SebDyn** [swig/swig#480]
Hi, I use Lua 5.2 (and 5.3) using SWIG 3.0.2 (and 3.0.4). I have a Matrix class using the C++ operator

```
Matrix Matrix::operator<(double x) const;
```

This operator should be translated into SWIG code using the **lt** Lua operator to override "<" in Lua. 

Interestingly I get the following behaviour:

```
A = Matrix(....)
print( swig_type( A < 3 ) ); -- output should be Matrix
-- output: boolean (wrong)
print( swig_type( A:__lt(3) ); -- output should be Matrix
-- output: Matrix (correct)
```

Is there any workaround for that? Or is it not possible to everride the </> operators using a recent Lua anymore?

**Comment by ojwb** [comment]
https://www.lua.org/pil/3.2.html says (my emphasis):

> Lua provides the following relational operators:
>
>    <   >   <=  >=  ==  ~=
>
> All these operators **always result in true or false**.

So it indeed seems not to be possible.
