### ISSUE TITLE
A typedef using uint64_t fails with TypeError 

### ISSUE THREAD

**Issue by pmgpmg** [swig/swig#495]
Here is the smallest test case I could create:

File TestCase.h
```c
#include <stdlib.h>
#include <inttypes.h>
#include <stdio.h>
typedef unsigned long long int TYPE1; 
typedef uint64_t TYPE2; 
class TestCase
{
public:
  static int          myTest1(TYPE1 xx) 
	{
		return xx+7;
	}
  static int          myTest2(TYPE2 xx) 
	{
		return xx+17;
	}

};
```
File TestCase.i
```
%module TestCase 
%{
#include "TestCase.h"
%}
%include "TestCase.h"
```
Makefile:
```makefile
CORE = -I/usr/lib/x86_64-linux-gnu/perl/5.20/CORE
all:
	/sw/swig/bin/swig -perl5 -c++ TestCase.i
	g++ -std=c++0x -c -fpic -I. TestCase.h  TestCase_wrap.cxx  -fPIC $(CORE)
	g++ -shared  TestCase_wrap.o  -o TestCase.so
	perl runme.pl
```
File runme.pl:
```perl
#! /usr/bin/perl

use strict ;
use warnings ;

use TestCase ;
my $n1 = TestCase::TestCase::myTest1(1) ;
print "HERE $n1\n" ; 
my $n2 = TestCase::TestCase::myTest2(1) ;

print "HERE $n2\n" ; 
```

Results from perl runme.pl
```
HERE 8
TypeError in method 'TestCase_myTest2', argument 1 of type 'TYPE2' at runme.pl line 9.
```

**Comment by pmgpmg** [comment]
I am running the latest version of swig
swig -version

SWIG Version 3.0.7

Compiled with g++ [x86_64-unknown-linux-gnu]

Configured options: +pcre

**Comment by pmgpmg** [comment]
The includes should read
#include <stdlib.h>
#include <inttypes.h>
#include <stdio.h>

**Comment by pmgpmg** [comment]
include <stdlib.h>  
include <inttypes.h>
include <stdio.h>

**Comment by pmgpmg** [comment]
These are the includes
stdlib.h inttypes.h stdio.h

**Comment by wsfulton** [comment]
I've updated the original comment with Markdown formatting so that your code displays correctly, please read up about it using the links on this page.

**Comment by wsfulton** [comment]
In order to get these types in C you need to ```#include <stdint.h>``` and for SWIG you need to ```%include <stdint.i>```. I see you have used inttypes.h for which there is a SWIG inttypes.i file you could use instead (which in turn includes stdint.i).

**Comment by pmgpmg** [comment]
Thanks for the help.
