### ISSUE TITLE
Swig allocates an output arg of type char * as a simple char

### ISSUE THREAD

**Issue by ScarletTanager** [swig/swig#496]
In my `.i` file:

```
%rename(wrapped_doStuff) doStuff(unsigned char *out);
%apply unsigned char *OUTPUT {unsigned char *out};
extern int doStuff(unsigned char *out);
%insert(go_wrapper) %{
    func DoStuff(input string) (result string, err error) {
        buf := make([]byte, len(input))
        r := Wrapped_doStuff(buf)
        if (1 != r) {
            err := errors.New("Doing stuff failed")
            return "", err
        }

        return bytes.NewBuffer(buf).String(), nil
    }
%}
```

The generated C wrapper has this:

```
intgo _wrap_wrapped_doStuff_pkgmod_d2069b27810db7e0(_goslice_ _swig_go_0) {
    unsigned char *arg1 = (unsigned char *) 0 ;
    unsigned char temp1 ; /* Not a typo - this is a char, not a char* */
    int result;
    intgo _swig_go_result;

    {
        if (_swig_go_0.len == 0) {
            _swig_gopanic("array must contain at least 1 element");
        }
        arg1 = &temp1; /* This is what strikes me as incorrect...? */
    }
    result = (int)doStuff(arg1); /* This is where I get the SIGSEGV */
```

I posted this as a question at http://stackoverflow.com/questions/31927866/getting-segmentation-fault-from-swig-generated-code-using-golang-when-passing-in as well, in case this turns out to be a user issue.

**Comment by ScarletTanager** [comment]
I've written test code showing this which can be found [here.](https://github.com/ScarletTanager/tmlib)

The workaround I came up with is to create this typemap:

    %typemap(gotype) char *outbuf %{[]byte%}
    %typemap(in) char *outbuf {
    	char tbuf[sizeof($input)];
    	$1 = (char *)&tbuf;
    }
    %typemap(argout) char *outbuf {
    	memcpy($input.array, $1, $input.cap);
    	$input.len = strlen($1);
    }

Critically, I think any fix has to handle writing back to the array element of the gostring struct, simply shuffling pointers hasn't worked in any of my attempts.

**Comment by tmc** [comment]
@ScarletTanager is this still an issue with more recent versions of swig? Lots of improvements have gone in.

**Comment by dominikh** [comment]
@tmc I can reproduce this with 3.0.12 and 4.0.0 built from 56f5b1c3c.

**Comment by piratf** [comment]
Still meeting this bug from 4.0.2. God this took me two days to find out why this slice not work.
Any solutions?

For now I have to modify the generated code.

**Comment by piratf** [comment]
Looking at this part of the code, perhaps the solution is to use "INOUT" instead of "OUTPUT".
https://github.com/swig/swig/blob/1ec44da352d781bd29759f0017128c6e3ed01a98/Lib/go/typemaps.i#L266-L271

No need to manually modify the generated code now.
