### ISSUE TITLE
Swig Creates Uninitialized Referenc on the Stack.

### ISSUE THREAD

**Issue by mehoggan** [swig/swig#497]
Using version 3.0.7 of swig I get the following build errors when using a std::vector<boost::intrusive_ptr<const T>> , wher boost::intrusive_ptr<const T> is typedefed as ConstTPtr.

/home/mhoggan/Devel/Earthscape/soft/src/EarthCore/EarthCoreOpsApi/Swig/Rtl_EarthCoreOpsApiJava.cpp:57333:74: error: ‘result’ declared as reference but not initialized
   std::vector< EarthScape::Core::ConstResultDetailPtr >::const_reference result;^M
                                                                          ^
/home/mhoggan/Devel/Earthscape/soft/src/EarthCore/EarthCoreOpsApi/Swig/Rtl_EarthCoreOpsApiJava.cpp:57341:12: error: passing ‘const value_type {aka const boost::intrusive_ptr<const EarthScape::Core::ResultDetail>}’ as ‘this’ argument of ‘boost::intrusive_ptr<T>& boost::intrusive_ptr<T>::operator=(const boost::intrusive_ptr<T>&) [with T = const EarthScape::Core::ResultDetail]’ discards qualifiers [-fpermissive]
     result = std_vector_Sl_EarthScape_Core_ConstResultDetailPtr_Sg__get(arg1,arg2);^M
            ^
/home/mhoggan/Devel/Earthscape/soft/src/EarthCore/EarthCoreOpsApi/Swig/Rtl_EarthCoreOpsApiJava.cpp:57348:77: error: cannot declare pointer to ‘std::vector<boost::intrusive_ptr<const EarthScape::Core::ResultDetail> >::const_reference {aka const class boost::intrusive_ptr<const EarthScape::Core::ResultDetail>&}’
   *(std::vector< EarthScape::Core::ConstResultDetailPtr >::const_reference **)&jresult = new std::vector< EarthScape::Core::ConstResultDetailPtr >::const_reference((const std::vector< EarthScape::Core::ConstResultDetailPtr >::const_reference &)result); ^M
                                                                             ^
/home/mhoggan/Devel/Earthscape/soft/src/EarthCore/EarthCoreOpsApi/Swig/Rtl_EarthCoreOpsApiJava.cpp:57348:251: error: new cannot be applied to a reference type
   *(std::vector< EarthScape::Core::ConstResultDetailPtr >::const_reference **)&jresult = new std::vector< EarthScape::Core::ConstResultDetailPtr >::const_reference((const std::vector< EarthScape::Core::ConstResultDetailPtr >::const_reference &)result);

The resulting code looking like:

SWIGEXPORT jlong JNICALL Java_nokia_earthcore_earthcoreopsapi_EarthCoreOpsApiModuleJNI_VectorResultDetailPtr_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  std::vector< EarthScape::Core::ConstResultDetailPtr > *arg1 = (std::vector< EarthScape::Core::ConstResultDetailPtr > *) 0 ;
  int arg2 ;
  std::vector< EarthScape::Core::ConstResultDetailPtr >::const_reference result;

  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< EarthScape::Core::ConstResultDetailPtr > **)&jarg1;
  arg2 = (int)jarg2;
  try {
    result = std_vector_Sl_EarthScape_Core_ConstResultDetailPtr_Sg__get(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }

  *(std::vector< EarthScape::Core::ConstResultDetailPtr >::const_reference **)&jresult = new std::vector< EarthScape::Core::ConstResultDetailPtr >::const_reference((const std::vector< EarthScape::Core::ConstResultDetailPtr >::const_reference &)result);
  return jresult;
}

For more details please contact:
matthew.hoggan@here.com

**Comment by wsfulton** [comment]
You need to provide a cutdown example to get any useful advice. Is this a change from previous versions of SWIG or something new you are trying to develop?

**Comment by ojwb** [comment]
No response from submitter in close to a year so closing.

Please supply the requested information if you wish to reopen this issue.
