### ISSUE TITLE
swig 3.0.2 does not handle #defines in secondary header files well

### ISSUE THREAD

**Issue by jengelh** [swig/swig#499]
esl.i:
```
%module(directors="1") esl
%include "esl.h"
```
esl.h:
```
#include "def.h"
class FooBar _final {
};
```
def.h:
```
#if __cplusplus >= 201100L
#       define _final final
#       define _override override
#else
#       define _final
#       define _override
#endif
```
Command that is executed: `swig -c++ -python esl.i`.
What is observed:
* swig 3.0.2 treats "_final" like a variable and emits code for it.
```
grep final esl_wrap.cxx
SWIGINTERN const char *_wrap__final_get(ClientData clientData SWIGUNUSED, Tcl_Interp *interp, char *name1, char *name2, int flags) {
```
What is expected:
* do not generate code for it.
Additional info:
* If I put the contents of def.h directly into esl.h, swig will not generate code for _final.

**Comment by ojwb** [comment]
This is as documented at http://swig.org/Doc3.0/Preprocessor.html#Preprocessor_nn2 :

```
By default, the #include is ignored unless you run SWIG with the
-includeall option.   The reason for ignoring traditional includes
is that you often don't want SWIG to try and wrap everything included
in standard header system headers and auxiliary files.
```

There's also `-importall` if you don't want to wrap everything from every included header.
