### ISSUE TITLE
Syntax error parsing methods named after reserved word

### ISSUE THREAD

**Issue by sablefr** [swig/swig#504]
Hi,

I am running swig on C++ header files to generate Python bindings.
There is a class however which causes an issue. It looks like this:

class Foo {
public:
        Foo or(Foo a, Foo b);
        Foo and(Foo a, Foo b);
        Foo not(Foo a);
};

Swig will fail to parse such a file: Error: Syntax error in input.

I suppose this is because "or", "and" and "not" are reserved words in Python.
I could not get swig to ignore or rename those methods either.
My only solution for the moment is to comment those lines.

Thanks in advance

Sebastien

**Comment by vadz** [comment]
It's more likely because all these identifiers are reserved words in C++...

**Comment by ojwb** [comment]
GCC and clang both give errors on this too, e.g. from GCC:

```
$ g++ -Wall -W 504.cc -o /dev/null -c
504.cc:3:5: error: expected unqualified-id before ‘or’ token
 Foo or(Foo a, Foo b);
     ^
504.cc:4:5: error: expected unqualified-id before ‘and’ token
 Foo and(Foo a, Foo b);
     ^
504.cc:5:5: error: expected unqualified-id before ‘not’ token
 Foo not(Foo a);
     ^
```

Closing as invalid.

**Comment by sablefr** [comment]
Thank you for analyzing this issue.
It is possible to have gcc compile it properly by using the -fno-operator-names option.
Visual Studio supports it natively apparently, not sure about clang.
I will try to workaround it.

**Comment by ojwb** [comment]
SWIG generally aims to support the standard ISO C and C++ languages, not all the various vendor extensions to them.
