### ISSUE TITLE
How to create a node extension from C program using swig?

### ISSUE THREAD

**Issue by HmidiSlim** [swig/swig#507]
I'm actually trying to create node js module  from a C program.I have my C program which called example.c
and I have example.i then I run this command:
swig -javascript -node example.i
then
 
sudo npm install -g node-gyp 
node-gyp configure
node-gyp build 
I got so many errors which are located in example_wrapper
but when I change the extension of the example.c to example.cxx and I generate it with
swig -javascript -node  -c++ example.i
I got the example module and the application works well.
Does not the C option not supported for swig ??

**Comment by wsfulton** [comment]
Yes, C is supported as long as it is compatible with C++ which is what Node requires. You should use the -o option to generate a C++ file and compile it with a C++ compiler. See http://swig.org/Doc3.0/Javascript.html#Javascript_node_extensions. If the docs aren't clear enough, please provide a patch to clarify.
