### ISSUE TITLE
typedef anonymous struct following by "::" make the parser crashes

### ISSUE THREAD

**Issue by edauphin** [swig/swig#508]
Hello everyone,

I faced a "Segmentation fault" using swig on a big cpp project. I finally isolated the piece of code that reproduce simply the problem. (And I also provide the workaround).

Here is a sample of the faulty code:

    namespace bar {
		int foo();
	}

	class Zork
	{
		public:
  		typedef struct {
	    std::string string;
  		} AStruct;

  		friend int bar::foo();
	};

So this cpp piece of code make swig crashes, when this one works.

    namespace bar {
		int foo();
	}

	class Zork
	{
		public:
  		typedef struct AStruct {
	    std::string string;
  		} AStruct;

  		friend int bar::foo();
	};

I'm using the 3.0.7 version of swig.

Thanks in advance to correct this bug,
Best Regards,
Etienne

**Comment by wsfulton** [comment]
@wkalinin, looks like it might be a nested struct bug if you fancy taking a look?

**Comment by wkalinin** [comment]
Merged fix to master in ec93b01a09d0e2d1bfd88d83f9bd1447cddc36a5, I guess the issue can be closed now.
