### ISSUE TITLE
configure script does not check for yacc

### ISSUE THREAD

**Issue by mistralol** [swig/swig#510]
Looks like the configure script does not check that yacc is installed

mkdir -p Lib
echo "/* SWIG warning codes */" > Lib/swigwarn.swg
cat Source/Include/swigwarn.h | grep "^#define WARN\|/\*.*\*/\|^[ \t]*$" | sed 's/^#define \(WARN.*[0-9][0-9]*\)\(.*\)$/%define SWIG\1 %enddef\2/' >> Lib/swigwarn.swg
make[1]: Entering directory '/home/james/tmp/swig/swig-rel-3.0.7/Source'
/bin/bash ../Tools/config/ylwrap CParse/parser.y y.tab.c CParse/parser.c y.tab.h `echo CParse/parser.c | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output CParse/parser.output -- yacc -d
../Tools/config/ylwrap: line 176: yacc: command not found
Makefile:973: recipe for target 'CParse/parser.c' failed
make[1]: *** [CParse/parser.c] Error 127
make[1]: Leaving directory '/home/james/tmp/swig/swig-rel-3.0.7/Source'
Makefile:37: recipe for target 'source' failed
make: *** [source] Error 2

**Comment by wsfulton** [comment]
yacc is not needed by users, only developers who need to install a whole of dependencies to get SWIG to build and install, please see http://swig.org/svn.html. 

SWIG does check for yacc/bison. You should see it in this part of the configure output:
```
Checking packages required for SWIG developers.
Note : None of the following packages are required for users to compile and install SWIG from the distributed tarball

checking for bison... bison -y
```
