### ISSUE TITLE
Require an ISO C++ compiler?

### ISSUE THREAD

**Issue by ojwb** [swig/swig#513]
ISO C++ happened in 1998, which is 17 years ago now - I think it's now reasonable to simply require an ISO C++ compiler, which means we can drop workarounds for pre-ISO compilers (the example I noticed is a fallback definition of `bool` if the compiler doesn't provide it).

Any objections?

**Comment by wsfulton** [comment]
I thought we already needed an ISO compiler! Anway, what is the motivation for this change? Perhaps put in a pull request so we can see the change. I'm a bit concerned about needlessly breaking stuff on the 3.0.x releases. Perhaps it should go into 3.1?

**Comment by ojwb** [comment]
If we're assuming an ISO C++ compiler it's just needless cruft in the code, and removing it has as about as much chance of breaking something as leaving it in does.

Individually such things only have a small impact, but once you start stacking them up you end up with a code base which is harder to work with, especially for new contributors.  I feel ought to clean up such things when I see them, or else the codebase slowly slides towards a state where cleaning it up becomes a daunting task.  Technical debt and all that.

**Comment by ojwb** [comment]
(I also suspect you're right that we do actually meed an ISO C++ compiler, though we don't seem to actually document that as a requirement - perhaps at this point it just goes without saying.)

**Comment by wsfulton** [comment]
+1 for cleanups to keep the code clean(ish). I'm not sure where this cruft is so am happy to review.

The compiler requirements are in section "2.8 SWIG and freedom" where it mentions ANSI C programming. Also in Windows.html it mentions we support ISO C/C++. But yes, having a standards based compiler is required and goes without saying, but we purposefully use a very small subset of the standard.

**Comment by ojwb** [comment]
OK, fixed in efcaa8fdaca0e25013d50d9b2c4239988d90eaf4.
