### ISSUE TITLE
Fix building of setools package

### ISSUE THREAD

**Issue by wsfulton** [swig/swig#515]
I notice that Fedora contains a patch called naming.c.setools for SWIG, some details here: https://lists.fedoraproject.org/archives/list/scm-commits%40lists.fedoraproject.org/message/WOINS7TNZTMH66Q3RPG2ADFO4OLXN3DO/ . This patch doesn't look right to me. Could anyone help me recreate the build problem in setools and I'll look at alternative fixes.

```patch
diff -up swig-2.0.7/Source/Swig/naming.c.setools swig-2.0.7/Source/Swig/naming.c
--- swig-2.0.7/Source/Swig/naming.c.setools	2011-12-11 17:29:51.000000000 +0100
+++ swig-2.0.7/Source/Swig/naming.c	2012-06-27 16:21:21.248375130 +0200
@@ -215,11 +215,11 @@ String *Swig_name_member(const_String_or
     Append(r, f);
   }
   cname = Char(rclassname);
-  if ((strncmp(cname, "struct ", 7) == 0) || ((strncmp(cname, "class ", 6) == 0)) || ((strncmp(cname, "union ", 6) == 0))) {
-    cname = strchr(cname, ' ') + 1;
-  }
   replace_nspace(r, nspace);
   Replace(r, "%c", cname, DOH_REPLACE_ANY);
+  if ((strncmp(cname, "struct ", 7) == 0) || ((strncmp(cname, "class ", 6) == 0)) || ((strncmp(cname, "union ", 6) == 0))) {
+    Replace(r, " ", "_", DOH_REPLACE_FIRST);
+  }
   Replace(r, "%m", membername, DOH_REPLACE_ANY);
   /*  name_mangle(r); */
   Delete(rclassname);
```

**Comment by wsfulton** [comment]
I found the details of the bug at https://bugzilla.redhat.com/show_bug.cgi?id=830249. It was fixed for swig-2.0.8. We need a Fedora person to remove the patch from Fedora and test it as it is still being applied to Fedora's swig-3.0.7.

**Comment by xadhoom** [comment]
Even in rhel7 (or CentOS7) the patch is shipped with swig 2.0.10, and it breaks the building of other sources, like nfqueue-bindings.
Removing the patch in the rpm and rebuilding fixes it. I'll try to open an issue to upstream.

**Comment by jplesnik** [comment]
I'll remove the patch from Fedora and test it asap.

**Comment by jplesnik** [comment]
I removed the patch from all Fedoras. 
Fix it in RHEL won't be so fast.

**Comment by wsfulton** [comment]
Thanks, closing.
