### ISSUE TITLE
C#: DllImport EntryPoint parameter does not match C# function name. This causes trouble with Unity3Ds il2cpp

### ISSUE THREAD

**Issue by beschulz** [swig/swig#516]
Usually this is not a problem. But Unity3Ds il2cpp ignores this parameter and tries to "import" these method names as they are spelled out.

A probable workaround would be to rename 'SWIGRegisterExceptionCallbacksArgument_MixpanelSDK' to 'SWIGRegisterExceptionArgumentCallbacks_MixpanelSDK' (in C#) and to prepend 'CSharp_' to the generated method names.

**Comment by wsfulton** [comment]
This sounds like a limitation of Unity3D and I guess the il2cpp tool is adjusted or used in such a way to deal with valid C# code. I suggest raising this as a bug against the il2cpp tool, or if you want SWIG to generate wrappers that works around this tool's limitation, submit a patch to do so.
