### ISSUE TITLE
Python: disown causes a second attempt to delete the object

### ISSUE THREAD

**Issue by dpistelli** [swig/swig#517]
I'm using the latest swig for Windows with builtin wrappers for Python. As soon as I allocate a director class from Python I call disown on it, so that I can eventually delete it from C++.

When I delete the object from C++, the program crashes. From the debugger I see that the director dtor calls Py_DECREF on the Python object, which then triggers _wrap_delete_MyClass_closure, which in turn calls _wrap_delete_MyClass, which internally deletes again the same C++ object and thus the crash.

I have tried only with builtin wrappers, I don't know whether this happens also when the -builtin option is omitted. I hope this helps.

**Comment by ojwb** [comment]
A small self-contained example demonstrating the problem would help.

Testing if it's specific to `-builtin` would also help.

**Comment by dpistelli** [comment]
I finally had the time to make a small sample and couldn't reproduce the issue. Then I found the problem: in my own code I was calling disown from C++ instead of Python and by doing so I called the wrong function, namely 'swig_disown' instead of 'swig_pyobj_disown'.

I apologize for having opened a bug report.

**Comment by ojwb** [comment]
Thanks for letting us know - closing.
