### ISSUE TITLE
[Go] Documentation lacks section about handling C++ exceptions

### ISSUE THREAD

**Issue by michael-schaller** [swig/swig#518]
The Go documentation doesn't have a section about how to handle C++ exceptions.  It would be nice if such a section would explain what the best practices are with regards to C++ exception handling, when these best practices apply (or don't apply) and small examples (if necessary).

In issue #418 this got briefly discussed and @ianlancetaylor made these comments:

https://github.com/swig/swig/issues/418#issuecomment-135781191

> I guess I don't know what there is to say about C++ exception handling in Go.
> The gc and gccgo compilers actually behave differently there.

https://github.com/swig/swig/issues/418#issuecomment-137326213

>  I think that for Go any C++ exceptions should be handled on the C++ side.

**Comment by ojwb** [comment]
There's still not a section on exceptions and it does seem like it would be helpful, but if @ianlancetaylor doesn't know what they is to say about it I'm not sure this ticket is usefully actionable by anyone.

We could add a paragraph which just says "For Go any C++ exceptions should be handled on the C++ side." if that seems to help?  And maybe something about the gc/gccgo difference if someone can explain what that actually is?  @michael-schaller asked in #418 but I couldn't see a response to that.

**Comment by cminyard** [comment]
Have you read the section about the "throws" typemap?  It map exceptions directly into Go panics.  They do not collect the what() from the exception (which I'm going to add an issue about), but it does work.

**Comment by ojwb** [comment]
That's essentially "handling the exceptions on the C++ side", isn't it?  The actual C++ exception isn't being allowed to propagate into Go code there.
