### ISSUE TITLE
[javascript][node] incorrect exception handing with function overload

### ISSUE THREAD

**Issue by microcai** [swig/swig#519]
in generated code,
swig uses  args.Length() to dispatch different overloaded functions, but when exception occurs, 
```
    if(errorHandler.err.IsEmpty()) {
      return;
    }
```
and the execution falls to 

```
  SWIG_exception_fail(SWIG_ERROR, "Illegal arguments for function xxxx");
```

therefore, when ever exceptions thrown, it's always  "Illegal arguments" .

**Comment by ojwb** [comment]
Now covered by PR #520, closing.

**Comment by ojwb** [comment]
Oops, didn't actually close this - doing so now.
