### ISSUE TITLE
C++ - only blocks are not propagated through %include

### ISSUE THREAD

**Issue by LindleyF** [swig/swig#521]
http://www.swig.org/Doc1.3/Typemaps.html#Typemaps_nn49 says that we can reduce generated code size by factoring out static functions inside of %{ %} blocks.

However, if this is done inside a swig file that is %include'd from another swig file, the outer swig file sees the typemaps but does not see the definitions they rely on.

A workaround is to put the %{ %} block into a %define and then invoke it after the %include, but this is not ideal.

**Comment by ojwb** [comment]
I use this technique in my interface files, and it seems to work fine within a `%include`-d file.  Can you provide a small, self-contained testcase which demonstrates your problem?

And what SWIG version are you using?

BTW, you're looking at the docs for 1.3.x.  The current release series is 3.0.x, though I don't see a corresponding section: http://www.swig.org/Doc3.0/Typemaps.html

**Comment by LindleyF** [comment]
I'll work on a small example when I have time. For now, I'm using 2.10 with a few newer commits patched in.

**Comment by LindleyF** [comment]
I think I understand better now what the problem is. %include works fine as you say, but %import does not.

Specifically, if A.swig defines a block %{ void MyHelperCFunction() { ... } %}, and typemaps in A.swig make use of MyHelperCFunction(), and then B.swig %includes A.swig, everything is fine.

However, if C.swig then %imports B.swig, it will try to use the typemaps from A.swig as they relate to B, but will not have the definition of MyHelperCFunction available.

**Comment by wsfulton** [comment]
I think that section has disappeared from the docs because it doesn't work with a mix of %import and %include and there is now a better way. Use typemap fragments instead: http://www.swig.org/Doc3.0/Typemaps.html#Typemaps_fragments.
