### ISSUE TITLE
[Python] C++ wrapper for overloaded function chooses wrong overload.

### ISSUE THREAD

**Issue by andwei** [swig/swig#525]
Using SWIG Version 2.0.12 (Ubuntu 15.04 package repo).
There are a number of preconditions for the issue to occur, therefore the minimal example is already rather long (actually, it was quite difficult to reproduce the issue on purpose). Also, some arguably not very good practises are necessary to reproduce the issue. However, as it leads to rather hard-to-understand runtime issues, I still think it is worth looking into, and should probably throw an error instead of silently building everything.

Given the following simple example involving two classes:

classA.h:
```c++
#ifndef CLASS_A_H_
#define CLASS_A_H_

namespace theNamespace {

class ClassA {
public:
    ClassA() {}
};

}

#endif
```
classB.h:
```c++
#ifndef CLASS_B_H_
#define CLASS_B_H_

#include "classA.h"

namespace theNamespace {

class ClassB {
public:
    ClassB() {}
};

void foo(ClassA& lhs, const ClassB& rhs);

}

#endif
```

classB.cc:
```c++
#include "classA.h"
#include "classB.h"
#include <iostream>

namespace theNamespace {

void foo(ClassA& lhs, const ClassB& rhs) {
    std::cout << "Called ClassB overload" << std::endl;
}

}
```

foo.h:
```c++
#ifndef FOO_H_
#define FOO_H_

#include "classA.h"
#include <cstdint>

namespace theNamespace {

void foo(ClassA& lhs, const ClassA& rhs);    
void foo(ClassA& lhs, const bool& rhs);

}
#endif
```
foo.cc:
```c++
#include "foo.h"
#include <iostream>

namespace theNamespace {

void foo(ClassA& lhs, const ClassA& rhs) {
    std::cout << "Called ClassA overload" << std::endl;
}

void foo(ClassA& lhs, const bool& rhs) {
    std::cout << "Called bool overload" << std::endl;
}

}
```
namespace.h
```c++
#ifndef NAMESPACE_H_
#define NAMESPACE_H_
using namespace theNamespace;
#endif
```

and the interface file overload.i:
```
%module(directors="1") overload
%{
#include "foo.h"
#include "classA.h"
#include "classB.h"
#include "namespace.h"
%}

%include "foo.h"
%include "classA.h"
%include "classB.h"
%include "namespace.h"
```

simple build script:
```c++
#!/bin/bash
g++ -fpic classB.cc -c -std=c++11
g++ -fpic foo.cc -c -std=c++11
swig -threads -c++ -python -I. -o overload_wrap.cc overload.i 
g++ -fpic -I. -I/usr/include/python2.7 -c overload_wrap.cc -std=c++11
g++ -shared overload_wrap.o classB.o foo.o -o _overload.so
```

and even simpler python script:
```python
#!/usr/bin/python
import overload
a = overload.ClassA()
b = overload.ClassB()
overload.foo(a, a)
overload.foo(a, b)
```
leads to output:
```
Called ClassA overload
Called bool overload
```

Checking the generated wrapper code (`overload_wrap.cc`), we get for `foo()`:
```c++
SWIGINTERN PyObject *_wrap_foo(PyObject *self, PyObject *args) {
  int argc;
  PyObject *argv[3];
  int ii;
  
  if (!PyTuple_Check(args)) SWIG_fail;
  argc = args ? (int)PyObject_Length(args) : 0;
  for (ii = 0; (ii < 2) && (ii < argc); ii++) {
    argv[ii] = PyTuple_GET_ITEM(args,ii);
  }
  if (argc == 2) {
    int _v;
    void *vptr = 0;
    int res = SWIG_ConvertPtr(argv[0], &vptr, SWIGTYPE_p_theNamespace__ClassA, 0);
    _v = SWIG_CheckState(res);
    if (_v) {
      int res = SWIG_ConvertPtr(argv[1], 0, SWIGTYPE_p_theNamespace__ClassA, 0);
      _v = SWIG_CheckState(res);
      if (_v) {
        return _wrap_foo__SWIG_0(self, args);
      }
    }
  }
  if (argc == 2) {
    int _v;
    void *vptr = 0;
    int res = SWIG_ConvertPtr(argv[0], &vptr, SWIGTYPE_p_theNamespace__ClassA, 0);
    _v = SWIG_CheckState(res);
    if (_v) {
      {
        int res = SWIG_AsVal_bool(argv[1], NULL);
        _v = SWIG_CheckState(res);
      }
      if (_v) {
        return _wrap_foo__SWIG_1(self, args);
      }
    }
  }
  if (argc == 2) {
    int _v;
    void *vptr = 0;
    int res = SWIG_ConvertPtr(argv[0], &vptr, SWIGTYPE_p_theNamespace__ClassA, 0);
    _v = SWIG_CheckState(res);
    if (_v) {
      int res = SWIG_ConvertPtr(argv[1], 0, SWIGTYPE_p_theNamespace__ClassB, 0);
      _v = SWIG_CheckState(res);
      if (_v) {
        return _wrap_foo__SWIG_2(self, args);
      }
    }
  }
  
fail:
  SWIG_SetErrorMsg(PyExc_NotImplementedError,"Wrong number or type of arguments for overloaded function 'foo'.\n"
    "  Possible C/C++ prototypes are:\n"
    "    theNamespace::foo(ClassA &,ClassA const &)\n"
    "    theNamespace::foo(ClassA &,bool const &)\n"
    "    theNamespace::foo(theNamespace::ClassA &,theNamespace::ClassB const &)\n");
  return 0;
}
```
For some reason that I do not completely understand, the check for `SWIG_AsVal_bool` is put before the check for ClassB and succeeds for some object passed from python code to the function.

The following actions change the behavior:
* The issue ceases to exist, if the order of includes is correctly changed to include classA.h before foo.h; in this case, the order of checks changes (checks for bool last) and the correct overload will be called.

* SWIG throws an exception, if the final `%inlcude "namespace.h"` is missing (it then can not find any suitable overload for `foo.overload(a,a)`). Removing `foo.overload(a,a)`, the correct overload for `foo.overload(a,b)` is called

* A compile time error is caused, if the `using namespace theNamespace` directive is neither included into the wrapper via the header or directly given in the interface file, which is ok, because it cannot be known to SWIG, that ClassA is a member of namespace theNamespace, when it parses foo.h.

Somehow, due to the `%include "namespace.h"`, SWIG on the one hand uses the "correct" `SWIGTYPE_p_theNamespace__ClassA` type in the overload-resolving code for `foo()` and does not fail to find an overload, but at the same time does not order the steps of overload resolution correctly.

I'm aware that using `using namespace` in headers is bad practice (and consequently removed it from the code that originally caused the issue for me). Still, the shown constellation leads to really mean runtime behavior and should probably rather fail to compile or at least throw an runtime error. 

If I got something completely wrong, some clarification would be nice :)

**Comment by ojwb** [comment]
There was a fix related to overload resolution of bool from Python in the release after the one you're using (3.0.0):

```
            [Python] Change in default behaviour wrapping C++ bool. Only a Python True or False
            will now work for C++ bool parameters. This fixes overloading bool with other types.
            Python 2.3 minimum is now required for wrapping bool.
```

Thanks for supplying a reproducer, but it unfortunately seems to be missing `namespace.h` so I can't tell if everything is resolved now or not.

Please test with a newer release, and if it's still not fully working, provide `namespace.h`.

**Comment by andwei** [comment]
Hi, thanks for your reply (unfortunately, the notice was placed in my probable spam folder, therefore the late reply). I updated my original post to contain the rather simple namespace.h.

**Comment by ojwb** [comment]
Thanks for confirming.
