### ISSUE TITLE
C++11 noexcept should propagate to director classes

### ISSUE THREAD

**Issue by VojtechFried** [swig/swig#526]
Tested with python.
Say I have an interface class IFoo:

``` c++
class IFoo 
{
public:
    virtual void bar() noexcept = 0;
};
```

Swig generates a director class:

``` c++
class SwigDirector_IFoo : public Strs::DocPlatform::IFoo, public Swig::Director {
public:
    SwigDirector_IFoo(PyObject *self);
    virtual void bar();
...
};
```

The compiler then complains, that "overriding virtual function has less restrictive exception specification than base class virtual member function". Swig should put C++11 noexcept to bar method of SwigDirector_IFoo.

**Comment by wsfulton** [comment]
Patch #975 fixed this.
