### ISSUE TITLE
javamethodmodifiers causes syntax error for C# target

### ISSUE THREAD

**Issue by dlifshitz-maca** [swig/swig#527]
I have the following in my input file:
```
%javamethodmodifiers SomeNamespace::SomeClass::someFunction() "";
```

When I run swig with the csharp target I get the following error:
```
MyInput.i(50) : Error: Syntax error - possibly a missing semicolon.
```

Shouldn't swig ignore the javamethodmodifiers for C#?

Workaround is to wrap it in `#if defined(SWIGJAVA)`

**Comment by vadz** [comment]
I don't think it's a bug, `%javaxxx` are defined in `java.swg` which is only included when Java is used, similarly to `%csharpxxx` and so on and I don't see how could they possibly not be an error when `java.swg` is not parsed at all. You do have to check for `SWIGJAVA` when using this macro, although it is probably fine (even though useless in non-Java case) to directly use `%feature("java:methodmodifiers")`.

**Comment by dlifshitz-maca** [comment]
Your explanation makes sense, though it's pretty awkward to have to wrap those lines. I'll stick with %feature("java:methodmodifiers"). It still seems out of place for javamethodmodifiers to be a feature instead of a typemap like javaclassmodifiers.

**Comment by dlifshitz-maca** [comment]
I also found out that there are duplicate director names when using multiple targets. I had to use this ugly workaround too: http://swig.10945.n7.nabble.com/Prefix-on-director-classes-tp6425p6426.html
