### ISSUE TITLE
Overloaded templated methods mishandled by SWIG C++ -> Python

### ISSUE THREAD

**Issue by r-owen** [swig/swig#529]
Ever since SWIG 3.0.3 we have been unable to generate working SWIG Python wrappers for our C++ code in one of our packages. The original code creates a C++ object called PropertyList which is simlar to a Python OrderedDict, but has an optional attached comment for each field (we use it wrap FITS headers). I was finally able to pare it down to a simple example.

The header file is as follows:

    #ifndef LSST_DAF_BASE_PROPERTYLIST
    #define LSST_DAF_BASE_PROPERTYLIST

    #include <string>

    #include "boost/shared_ptr.hpp"

    namespace lsst {
    namespace daf {
    namespace base {

    class PropertyList {
    public:
        PropertyList(void) {};

        virtual ~PropertyList(void) {};

        template <typename T> void set(std::string const& name, T const& value, bool inPlace=true) {};

        void set(std::string const& name, boost::shared_ptr<PropertyList> const& value, bool inPlace=true) {};

        template <typename T> void set(std::string const& name, T const& value, std::string const& comment, bool inPlace=true) {};
    };

    }}} // namespace lsst::daf::base

    #endif

The .cc implementation simply instantiates one template type:

    #include "lsst/daf/base/PropertyList.h"

    namespace lsst {
    namespace daf {
    namespace base {

    #define INSTANTIATE(t) \
        template void PropertyList::set<t>(std::string const& name, t const& value, bool inPlace); \
        template void PropertyList::set<t>(std::string const& name, t const& value, std::string const& comment, bool inPlace);

    INSTANTIATE(int)

    }}} // namespace lsst::daf::base

The SWIG .i file:

    %define daf_base_DOCSTRING
    "Wrap daf_base PropertyList"
    %enddef

    %feature("autodoc", "1");
    %module(package="lsst.daf.base", docstring=daf_base_DOCSTRING) baseLib

    %{
    #include "boost/shared_ptr.hpp"
    #include "lsst/daf/base/PropertyList.h"
    %}

    %include "std_string.i"

    %shared_ptr(lsst::daf::base::PropertyList);

    %include "lsst/daf/base/PropertyList.h"

    // This has to come after PropertyList.h
    %define PropertyListAddType(type, typeName)
        %template(set ## typeName) lsst::daf::base::PropertyList::set<type>;
        %extend lsst::daf::base::PropertyList {
    static std::type_info const TYPE_ ## typeName = typeid(type);
    }
    %enddef

    PropertyListAddType(int, Int)

Here is a unit test that shows the failure modes.

    #!/usr/bin/env python2
    import unittest

    from lsst.daf.base import PropertyList

    class PropertyListTestCase(unittest.TestCase):
        """A test case for PropertyList."""
        def test1(self):
            '''Test setInt(name, value)

            Works with SWIG 3.0.2, but fails with SWIG 3.0.3-3.0.7 with the error:
                TypeError: setInt() takes at least 4 arguments (3 given)

            The baseLib.py setInt method generated by SWIG 3.0.7 is as follows:

            def setInt(self, name, value, comment, inPlace=True):
                """
                setInt(PropertyList self, std::string const & name, int const & value, bool inPlace=True)
                setInt(PropertyList self, std::string const & name, int const & value)
                setInt(PropertyList self, std::string const & name, int const & value, std::string const & comment, bool inPlace=True)
                setInt(PropertyList self, std::string const & name, int const & value, std::string const & comment)
            """
            '''
            apl = PropertyList()
            apl.setInt("int", 1)

        def test2(self):
            """Test setInt(name, value, inPlace)

            Works with SWIG 3.0.2 but fails with SWIG 3.0.3 through 3.0.7 with the error:
                NotImplementedError: Wrong number or type of arguments for overloaded function 'PropertyList_setInt'.
                  Possible C/C++ prototypes are:
                    lsst::daf::base::PropertyList::set< int >(std::string const &,int const &,bool)
                    lsst::daf::base::PropertyList::set< int >(std::string const &,int const &)
                    lsst::daf::base::PropertyList::set< int >(std::string const &,int const &,std::string const &,bool)
                    lsst::daf::base::PropertyList::set< int >(std::string const &,int const &,std::string const &)

            For the SWIG-generated setInt method see test1 doc string
            """
            apl = PropertyList()
            apl.setInt("int", 1, True)

    if __name__ == "__main__":
        unittest.main()

The code works with SWIG 3.0.2 and fails as described with 3.0.3 and 3.0.7. I can make the failures go away by doing any one of the following:
- Eliminate the 2nd "set" method (retaining the 1st and 3rd methods)
- Eliminate the 3rd "set" method (retaining the 1st and 2nd methods)
- Remove the optional "inPlace" argument from all three "set" methods

**Comment by wsfulton** [comment]
This is related to the change in handling of Python default arguments. See #327. Until this particular manifestation of the bug is fixed, you can work around it by adding the following before SWIG parses any of the set methods:
```swig
%feature("python:cdefaultargs") set;
```
