### ISSUE TITLE
Inconsistent parsing of typedef

### ISSUE THREAD

**Issue by xypron** [swig/swig#531]
The sequence of typedefs and structure definitions has not influence on C but swig creates very different wrappers:

Example 1

```
%module M1

%{
typedef struct foo * foo;
struct foo {
  double x;
  double y;
};
struct foo *bar(foo value);
%}
typedef struct foo * foo;
struct foo {
  double x;
  double y;
};
foo bar(foo value);
```

generates

```
public class M1 {
  public static SWIGTYPE_p_foo bar(SWIGTYPE_p_foo value) {
    long cPtr = M1JNI.bar(SWIGTYPE_p_foo.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_foo(cPtr, false);
  }

```

Example 2

```
%module M2

%{
struct foo {
  double x;
  double y;
};
typedef struct foo * foo;
struct foo *bar(foo value);
%}
struct foo {
  double x;
  double y;
};
typedef struct foo * foo;
foo bar(foo value);
```

generates

```
public class M2 {
  public static foo bar(foo value) {
    long cPtr = M2JNI.bar(foo.getCPtr(value), value);
    return (cPtr == 0) ? null : new foo(cPtr, false);
  }
```

Examples 1 and 2 should have resulted in the same wrapping.

Obviously example 2 currently gives a more useful wrapping as the elements of struct foo are easily accessible, so this kind of mapping is what we should always receive.

The problem struck me when trying to wrap the GLPK library (https://www.gnu.org/software/glpk/).

**Comment by ojwb** [comment]
With SWIG 4.0.2 the first case is now handled as you want - the two examples generate identical code except for `M1` vs `M2`.

Not sure exactly when this got fixed.
