### ISSUE TITLE
csharp: CLS compliance: renaming of parameters colliding with keywords

### ISSUE THREAD

**Issue by xypron** [swig/swig#532]
SWIG C# can be used to wrap native libraries as common language interface compatible assemblies.
If I want to use the assemblies with other languages like Visual Basic these assemblies should comply to the Common Language Specification (CLS).

Lib/csharp/csharpkw.swg defines rename rules to avoid collisions with keywords. Unfortunately these rules prepend an underscore. Parameters starting with underscores are not CLS compliant.

Hence the rules should be changed to append the underscore instead of prepending it:

```
#define CSHARPKW(x) %keywordwarn("'" `x` "' is a C# keyword, renaming to '" `x` "_'",rename="%s_")  `x`
```

**Comment by ojwb** [comment]
@xypron Seems a reasonable change - could you submit a PR, making sure the testsuite is updated to match this change?

**Comment by xypron** [comment]
@ojwb 

See pull request #786 

I tested with 

    make check-csharp-examples
    make check-csharp-test-suite

I could not find any changes necessary in the test-suite.
