### ISSUE TITLE
Python: unintuitive EOL removal for avoiding "Line indented less..." errors

### ISSUE THREAD

**Issue by jdonald** [swig/swig#535]
This issue is similar to #475 as these errors began with a regression in SWIG 3.0.6 :

```
Leap.i(991) : Error: Line indented less than expected (line 3 of %pythoncode or %insert("python") block) as no line should be indented less than the indentation in line 1
Leap.i(1009) : Error: Line indented less than expected (line 16 of %pythoncode or %insert("python") block) as no line should be indented less than the indentation in line 1
```

But while the problem in #475 and the subsequent fix in SWIG 3.0.7 is related to docstrings, we still see a regression in cases without docstrings.

Judging from the test cases checked in, our code blocks such as
```
%extend Leap::Vector {
%pythoncode {
  def to_float_array(self): return [self.x, self.y, self.z]
  def to_tuple(self): return (self.x, self.y, self.z)
%}}
```

can be made to work in SWIG 3.0.6/3.0.7 via :
```
%extend Leap::Vector {
%pythoncode {
  def to_float_array(self): return [self.x, self.y, self.z]
  def to_tuple(self): return (self.x, self.y, self.z)%}}
```

but this is messy and uintuitive. I find it similar to imagining if `#endif` directives were to land at the end of source line content in C.

Some more details of this example can be found in a [forum thread](https://community.leapmotion.com/t/error-for-python-3-4-3-wrapper/4164) on the Leap Motion website.

Shouldn't we allow an end-of-line at the end of a `%pythoncode` block, and not count that as an extra line of length 0 that could cause "Line indented less than expected" errors, just as this had worked in SWIG 3.0.5 and earlier?

**Comment by ojwb** [comment]
```
%extend Leap::Vector {
%pythoncode {
  def to_float_array(self): return [self.x, self.y, self.z]
  def to_tuple(self): return (self.x, self.y, self.z)
%}}
```

I think your problem is the `%` before the closing `}` - the `%pythoncode` block didn't start with `%{`, so this `%` is presumably parsed as part of the block contents, not part of the delimiter.

**Comment by ojwb** [comment]
As noted, the problem appears to be a stray `%` in the example - if I process this example (minimally extended to make it valid):

```
namespace Leap {
struct Vector {};
}

%extend Leap::Vector {
%pythoncode {
  def to_float_array(self): return [self.x, self.y, self.z]
  def to_tuple(self): return (self.x, self.y, self.z)
%}}
```

like so:

```
$swig -module issue535 -python -c++ issue535.i
issue535.i:9: Error: Line indented less than expected (line 3 of %pythoncode or %insert("python") block) as no line should be indented less than the indentation in line 1
```

Then the output `issue535.py` contains:

```
    def to_float_array(self): return [self.x, self.y, self.z]
    def to_tuple(self): return (self.x, self.y, self.z)
    %
```

This seems an issue with this example rather than swig, and there's been no further feedback from the submitter for over 3 months, so closing.

**Comment by jdonald** [comment]
Sorry for not responding to close this out sooner. I did test your fix locally in October, and it appeared to work then. I meant to loop back here once the fix had been incorporated into our release, but that got postponed.

As the issue is now most certainly on our end, it's fine to close this out.

**Comment by ojwb** [comment]
Thanks for confirming.
