### ISSUE TITLE
enums in nested classes are oddly named

### ISSUE THREAD

**Issue by fahhem** [swig/swig#537]
```c++
struct Outer {
  struct Inner {
    enum InnerEnum {
      EnumMember,
    };
  };
};
```

I had initially put: %ignore "" at the top of the interface file to then put %rename("%s") Outer; and friends in the file. I could get all the nested structs (thanks for that vkalinin!), but no matter what I put after rename, I couldn't get the inner enum members to show up in the output.

I tried: Outer::Inner::InnerEnum::EnumMember, Outer::Inner:EnumMember, Outer::Inner::InnerEnum, Outer::EnumMember, EnumMember etc, and most combinations of them.

I ended up going with %rename($ignore, %$isclass) ""; which solved my problem indirectly, but I'd prefer to document what it should have been or potentially fix it.

Any guidance would be greatly appreciated!

**Comment by wkalinin** [comment]
What is your target language, and what exactly are you trying to do?

**Comment by fahhem** [comment]
Python. I got everything else to show up, all the nested structs, functions, etc. The last part was getting the enum members to show up and I couldn't 'unignore' them

**Comment by wkalinin** [comment]
I thought nested structures support is not implemented in python language module. Do you use %feature ("flatnested") ?

**Comment by fahhem** [comment]
Yes, sorry, I'm using flatnested.

**Comment by wkalinin** [comment]
I don't understand what's wrong then, and what are you truing to do. With %feature("flatnested");
struct Outer {
  struct Inner {
    enum InnerEnum {
      EnumMember,
    };
  };
};
is equivalent to 

struct Outer {};
 struct Inner {
    enum InnerEnum { EnumMember,   };
};
And as far as I can see it works ok.

What are you trying to unignore and why it was ignored in the first place?

Or you are trying to ignore one specific enum member?

**Comment by fahhem** [comment]
No, at work the policy is to ignore everything at the top and then unignore only the things we want exposed (to make discovery of exposed methods easier, etc). So I have: %ignore "" at the top as an 'ignoreall' macro, and then I unignore everything else with the %rename("%s") macro. However, there was nothing I could put after that rename macro that would get the enum members to show back up.

**Comment by wkalinin** [comment]
The following test case works for me:
%module Nested
%feature("flatnested");
%ignore "" ;
%rename ("Outer") Outer;
%rename ("Inner") Outer::Inner;
%rename ("InnerEnum") Outer::Inner::InnerEnum;
%rename ("EnumMember") Outer::Inner::EnumMember;
struct Outer {
  struct Inner {
    enum InnerEnum {
      EnumMember,
    };
  };
};

**Comment by fahhem** [comment]
Thanks for bothering with this!

So the policy is to use "%s" in the rename. The following gets Inner to be a top-level class, but nothing else.

```c++
%module Nested
%feature("flatnested");
%ignore "" ;
%rename ("%s") Outer;
%rename ("%s") Outer::Inner;
%rename ("%s") Outer::Inner::InnerEnum;
%rename ("%s") Outer::Inner::EnumMember;
struct Outer {
  struct Inner {
    enum InnerEnum {
      EnumMember,
    };
  };
};
```

**Comment by fahhem** [comment]
Okay, it seems that my last example actually works. I must not have tried that combination before, though in hindsight it seems intuitive since that's how each part is referred to with C++ (non-class) enums.
