### ISSUE TITLE
Python 3.5, -builtin, excess elements in struct initializer

### ISSUE THREAD

**Issue by jim-easterbrook** [swig/swig#539]
In Python 3.5 there is a new PyAsyncMethods member in the PyHeapTypeObject struct.
(See https://docs.python.org/3/c-api/typeobj.html#async-object-structures)
This appears to be causing "excess elements in struct initializer" errors when I try to compile a simple module using SWIG 3.0.7 with the -builtin option.

SWIG module `example_module.i`:
```
%module example

%inline %{
typedef struct test {
  int i;
} test;
%}
```

`setup.py`:
```
from distutils.core import setup, Extension

example_module = Extension(
    '_example',
    sources = ['example_module.i'],
    swig_opts = ['-builtin'],
    )

setup(
    name = 'example',
    version = '0.0.0',
    ext_modules = [example_module],
    py_modules = ['example'],
    )
```

**Comment by wsfulton** [comment]
Fixed in ef001de5240c1e05494e23b933b687f3f266045c

**Comment by pmakowski** [comment]
As I said in comment for commit https://github.com/swig/swig/commit/ef001de5240c1e05494e23b933b687f3f266045c
I'm not sure that this bug is really solved
see for example when we try to build libprelude with Python3.5 under Mageia
we are using swig 3.0.7 with this patch http://svnweb.mageia.org/packages/cauldron/swig/current/SOURCES/swig-3.0.7-python35.patch?revision=902918&view=markup

**Comment by wsfulton** [comment]
Where is _prelude.cxx being generated? Presumably this is generated by SWIG, but it isn't showing in the build log. Without the source or info on how you invoke SWIG, it is rather hard to know what is going on. I've run the entire SWIG test-suite with python 3.5 and your compile flags for _prelude.cxx and I can't replicate your errors.

**Comment by pterjan** [comment]
The problem was that libprelude was not regenerating it with the fixed swig, adding --with-swig=yes to configure fixed it, thank you for the fix.
