### ISSUE TITLE
R bindings missing include can cause compilation failure

### ISSUE THREAD

**Issue by binarycrusader** [swig/swig#555]
The 'R' language bindings file "Lib/r/rrun.swg" calls fprintf(), but fails to include stdio.h resulting in compilation failure with some compilers that have strict rules about declarations.

```
Swig bindings for R call fprintf but fail to include stdio.h.
diff -ru swig-3.0.5/Lib/r/rrun.swg swig-3.0.5.new/Lib/r/rrun.swg
--- swig-3.0.5/Lib/r/rrun.swg   2015-01-31 09:51:17.000000000 -0800
+++ swig-3.0.5/Lib/r/rrun.swg   2015-10-23 14:03:31.679583617 -0700
@@ -20,6 +20,7 @@

 #include <Rdefines.h>
 #include <Rversion.h>
+#include <stdio.h>
 #include <stdlib.h>
 #include <assert.h>
```

**Comment by ojwb** [comment]
@joequant Looks reasonable, but I don't know much about the R backend so I'm reluctant to just make changes to it - could you take a look?
