### ISSUE TITLE
Linking errors for simply Python test

### ISSUE THREAD

**Issue by hellmersjl3ds** [swig/swig#556]
I'm trying to get the simple python example working using Visual Studio 2008.  The code is compiling fine, but the linker is giving me a bunch of messages like...

example_wrap.obj : error LNK2019: unresolved external symbol __imp__PyString_AsString referenced in function _SWIG_Python_str_AsChar

I assume that there is a library or something that that I need to add a dependency for, but I'm at a loss as to what it maybe.

**Comment by vadz** [comment]
Yes, you need to link with the (correct) `python.lib`. SWIG documentation for Python does describe this.

**Comment by hellmersjl3ds** [comment]
The problem was I was using the 64-bit version of Python, and VS 2008 is 32-bit.  Switching to the 32-bit version fixed the problem.  Thanks.
