### ISSUE TITLE
Templates and ValueWrapper

### ISSUE THREAD

**Issue by CodingAiolos** [swig/swig#558]
In `SwigType_alttype` in "typesys.c" is setting `use_wrapper` to true for all templates. `use_wrapper = !n || !GetFlag(n, "feature:novaluewrapper");` is always true, because of `!n`. This doesn't seem to be the intention of the developer.

``` c++
n = Swig_symbol_clookup(td, 0);
if (n) {
    if (GetFlag(n, "feature:valuewrapper")) {
      use_wrapper = 1;
    } else {
      if (Checkattr(n, "nodeType", "class")
          && (!Getattr(n, "allocate:default_constructor")
          || (Getattr(n, "allocate:noassign")))) {
        use_wrapper = !GetFlag(n, "feature:novaluewrapper") || GetFlag(n, "feature:nodefault");
      }
    }
} else {
    if (SwigType_issimple(td) && SwigType_istemplate(td)) {
      use_wrapper = !n || !GetFlag(n, "feature:novaluewrapper");
    }
}
```

Edit: corrected typsys to typesys

**Comment by ojwb** [comment]
We don't seem to have a `typsys.c` - I'm assuming you mean `typesys.c`...

Marcelo (who's no longer active in SWIG development, so sadly we probably can't ask him about it) appears to have added exactly (and only) the `!n || ` part in 36b16faeab41de5097483b3ae3cba0f7fce9340b.

The commit message doesn't really seem to match this change.

@TimoWiegel How does removing the `!n || ` part affect the testsuite?

**Comment by TimoWiegel** [comment]
Because it is the `else` Block of the `if (n)`, it isn't possible to get the feature, so this can't be the solution to the problem. It seems to be the problem, that there is no symbol generated for the template (maybe only unnamed), to store the features in.

```C++
n = Swig_symbol_clookup(td, 0);
if (n) {
//...
else {
   use_wrapper = !n || !GetFlag(n, "feature:novaluewrapper");
}
```

**Comment by ojwb** [comment]
The code in question was changed back in 2017 in 7d6808daabef22143c6d417759910ccc059e8d21 to `use_wrapper = 1;` and William said in #1139 :

> This is just badly written code rather than a bug.

So closing this ticket too.
