### ISSUE TITLE
D swig : missing override on overridden methods (new requirement since D 2.063)

### ISSUE THREAD

**Issue by timotheecour** [swig/swig#56]

**Comment by ojwb** [comment]
Looks like this would address the second issue mentioned above (but really, please don't report multiple issues in one ticket):

```
diff --git a/Source/Modules/d.cxx b/Source/Modules/d.cxx
index b7283eac..ede048ff 100644
--- a/Source/Modules/d.cxx
+++ b/Source/Modules/d.cxx
@@ -2708,10 +2708,10 @@ private:
 	modifiers = Copy(mods_override);
       } else {
 	modifiers = Copy(is_public(n) ? public_string : protected_string);
+      }
 
-	if (Getattr(n, "override")) {
-	  Printf(modifiers, " override");
-	}
+      if (Getattr(n, "override")) {
+	Printf(modifiers, " override");
       }
 
       if (is_smart_pointer()) {
```

Looks like `destructmethodmodifiers` might need similar treatment.

I've no idea about the D language though, so maybe that's a bad idea.  Really this needs addressing by someone who knows D.  Would one want to be able to prevent SWIG from automatically adding `override`?

**Comment by ojwb** [comment]
@dnadlinger Any thoughts on the patch in the comment above?

**Comment by ojwb** [comment]
@wsfulton Do you have much knowledge of D?  If so, does my patch above look like the right approach?

**Comment by wsfulton** [comment]
I'll have a look, I've got a vague understanding of what is going on, but not enough to solve all the errors with the new versions of D.

BTW, I was going to suggest discuss removing/deprecating D during the 4.2 dev cycle if there isn't someone contributing to fixing this soon as the last working version of D is now ancient.

**Comment by ojwb** [comment]
The patch in #2570 seems to fix both the testcases above.  For the first the generated code now includes `override` on `foo`:

```
  public override int foo() {
    auto ret = swig.dlib_im.B_foo(cast(void*)swigCPtr);
    return ret;
  }
```

And for the second we now generate:

```
  @property override SWIGTYPE_p_String album() const {
    SWIGTYPE_p_String ret = new SWIGTYPE_p_String(x_im.Tag4_album(cast(void*)swigCPtr), true);
    return ret;
  }
```
