### ISSUE TITLE
Directors try to handle methods marked as final in a subclass.

### ISSUE THREAD

**Issue by chrisdembia** [swig/swig#564]
I used `%feature("director") MyClass;`. `MyClass` has a virtual method `virtual void MyClass::foo();` that is marked `final` in a subclass: `void Subclass::foo() final;`. SWIG still attempts to make `Subclass::foo()` a director method. This can be fixed by using `%feature("nodirector") MyClass::foo;`, but that is undesirable, as other subclasses of `MyClass` in my target language might want to implement `foo()`.

**Comment by ojwb** [comment]
SWIG's current support for `final` (which was new in C++11) only amounts to having it in the grammar - it doesn't do anything with the information.  See `Source/CParse/parser.y` for details.

Does `%feature("nodirector") SubClass::foo;` provide a better work-around?

If so, it seems it shouldn't be too hard to add a `final` attribute to the nodes for such methods, then later use that attribute to automatically handle them as if feature `nodirector` had been specified.

Also, do you have a small, self-contained example of this?

**Comment by ojwb** [comment]
@chrisdembia Any response to the questions in my earlier comment?

**Comment by chrisdembia** [comment]
Thank you for responding promptly after I posted this issue. I apologize for being a delinquent bug-reporter!

> Does %feature("nodirector") SubClass::foo; provide a better work-around?

Ah if this works, I believe this would achieve my desired behavior.

> If so, it seems it shouldn't be too hard to add a final attribute to the nodes for such methods, then later use that attribute to automatically handle them as if feature nodirector had been specified.

I don't really understand this sentence...are you describing how my desired behavior could be implemented in SWIG? I know nothing about the SWIG code base :/

> Also, do you have a small, self-contained example of this?

Not right now, and I'm not sure I can spend time producing one. Feel free to close this issue until I can be more responsible!

**Comment by ojwb** [comment]
> >  If so, it seems it shouldn't be too hard to add a final attribute to the nodes for such methods, then later use that attribute to automatically handle them as if feature nodirector had been specified.

> I don't really understand this sentence...are you describing how my desired behavior could be implemented in SWIG?

Yes - I was suggesting we could mark the node in SWIG's parse tree corresponding to the method to indicate that it is `final`, and then when generating code treat that marking as if the user has specified `%feature("nodirector")` for the method.  This assumes manually specifying achieves what's wanted.

> I know nothing about the SWIG code base :/

I wasn't necessarily suggesting you needed to implement it, though providing a patch is usually the fastest way to get something done around here.

I think it's worth keeping the issue open - it seems a valid issue, and it should be possible for someone to fabricate a test case from the information given (it would just save time if you had something suitable).

**Comment by chrisdembia** [comment]
Thank you for explaining.

**Comment by ZackerySpytz** [comment]
I've created a PR for this issue: #1483.
