### ISSUE TITLE
SystemError when calling C++ destructor with Python 3.5 coroutine

### ISSUE THREAD

**Issue by msornay** [swig/swig#567]
Hello,

I'm not really sure what is happening here. The generated `delete_Foo` call apparently does something now illegal when the StopIteration raised when returning from the coroutine is handled : https://bugs.python.org/issue23571

I have a minimal example using Swig master (4c0db9d83daeaf6fe0b7292ade512ba8da7f5571) :

`foo.h` : 
```c++
class Foo {};
```

`foo.i` : 
```
%module foo 
%{                               
  #include "foo.h"   
%}

%include "foo.h" 
```

`bug.py` : 
```python
import asyncio    
import foo   

async def hello():
    f = foo.Foo()  

r = asyncio.get_event_loop().run_until_complete(hello()) 
```

Compilation (g++ 4.9.2) : 
```
$ swig -python -py3 -c++ foo.i
$ g++ -c foo_wrap.cxx -I /usr/local/include/python3.5m/ -fPIC
$ g++ -shared foo_wrap.o -o _foo.so
$ python3 bug.py
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    r = asyncio.get_event_loop().run_until_complete(hello())
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
SystemError: <built-in function delete_Foo> returned a result with an error set
```

**Comment by wsfulton** [comment]
I expect the patch in #560 will fix this. Can you try it out and report back?

**Comment by msornay** [comment]
Just tested it. It is fixed by #560

**Comment by wsfulton** [comment]
Closing as the patch has been merged to master.

**Comment by ojwb** [comment]
`CHANGES` says the #560 patch was in release 3.0.8.

Using git tag rel-3.0.12 the reproducer above doesn't reproduce the problem.  Also works fine with git master.

I'm using the Debian package of python 3.5 (python3.5-minimal 3.5.4-4) (so I had to adjust `/usr/local` to `/usr` in the compilation commands above).

**Comment by ralphsb** [comment]
Apologies, I was using an up to date binary but a stale Lib folder. Updating the Lib folder to rel-3.0.12 fixed the issue. Thanks for the quick response.
