### ISSUE TITLE
stdint.i typedefs

### ISSUE THREAD

**Issue by andy-slac** [swig/swig#568]
Hi, I'm having an issue with the code generated for one of the C++ methods that accepts a vector of uint64_t integers. I think this is due to inconsistency in typedefs for uint64_t in SWIG and gcc (this is happening with gcc 4.8 on Ubuntu 14.04 with swig3.0 installed from repo). Here is is the simplest test case that reproduces my problem:

    # test.i
    %module test
    %{
    #include <vector>
    #include <stdint.h>
    void testMethod(std::vector<uint64_t> const& v) {}
    %}
    
    %include <std_vector.i>
    %include <stdint.i>
    
    %template(VectorUint64) std::vector<uint64_t>;
    
    void testMethod(std::vector<uint64_t> const& v);

And here is the error that I see:

    % swig3.0 -v
    Must specify an input file. Use -help for available options.
    root@ubuntu1404:~/tmp# swig3.0 -version

    SWIG Version 3.0.2

    Compiled with g++ [x86_64-unknown-linux-gnu]

    Configured options: +pcre

    Please see http://www.swig.org for reporting bugs and further information

    % swig3.0 -python -c++ test.i
    %  g++ -I/usr/include/python2.7 -c -o test_wrap.o test_wrap.cxx
    test_wrap.cxx: In function ‘std::vector<long long unsigned int, std::allocator<long long unsigned int> >* std_vector_Sl_uint64_t_Sg____getslice__(std::vector<long unsigned int>*, std::vector<long long unsigned int, std::allocator<long long unsigned int> >::difference_type, std::vector<long long unsigned int, std::allocator<long long unsigned int> >::difference_type)’:
    test_wrap.cxx:4671:42: error: cannot convert ‘std::vector<long unsigned int>*’ to ‘std::vector<long long unsigned int, std::allocator<long long unsigned int> >*’ in return
           return swig::getslice(self, i, j, 1);
                                              ^
    test_wrap.cxx: In function ‘std::vector<long long unsigned int, std::allocator<long long unsigned int> >* std_vector_Sl_uint64_t_Sg____getitem____SWIG_0(std::vector<long unsigned int>*, PySliceObject*)’:
    test_wrap.cxx:4691:47: error: cannot convert ‘std::vector<long unsigned int>*’ to ‘std::vector<long long unsigned int, std::allocator<long long unsigned int> >*’ in return
           return swig::getslice(self, id, jd, step);
                                                   ^
    ..... a lot more errors

To me it looks like swig has typedef for uint64_t which resolves to `unsigned long long int` and g++ believes that the same typedef must be `unsigned long int`. It is also interesting to see that swig-generated code uses resolved type name (`unsigned long long int`) instead of uint64_t.

Is there any workaround for making SWIG typedefs consistent with native compiler typedefs?

**Comment by wsfulton** [comment]
Look in stdint.i and you can see that if define SWIGWORDSIZE64 you will get what you need:

```
#if defined(SWIGWORDSIZE64)
typedef unsigned long int	uint64_t;
#else
typedef unsigned long long int	uint64_t;
#endif
```

**Comment by andy-slac** [comment]
I know about `-DSWIGWORDSIZE64`, the problem with that is that need for that macro is platform-specific, it is needed on some 64-bit platforms but is not needed on another. I'd appreciate more portable mechanism for that, without such mechanism I have to resort to complicated configure-time tests to figure out whether this macro is needed. 

I think swig could be made more flexible in that respect if it used typedef name (like uint64_t) in generated code instead of replacing it with its own incorrect type. Would that be too hard to implement? I may be able to help but I have zero knowledge of swig code, if you think It's doable and can give me some pointers I could start looking at it.

**Comment by wsfulton** [comment]
uint64_t and similar fixed size types are not portable and are fairly new to the C standard. Hence all the typemaps are specified in terms of traditional and portable types - int, long etc. 

Probably the proper fix is to supply actual typemaps for these new types rather than apply some other ones that we currently do. That is going to be quite a tedious undertaking, but would require adding in these types to the current supported integral types. This will be needed in the executable and all the different language typemaps and quite a few tests too. Just to be upfront about this, I am only likely merge something new like this into master if all the languages are supported, not just a subset. I would search for something like "unsigned long" in the Source and Lib directories to see the type of places that would need changing. Tests would be by expanding Examples/test-suite/li_stdint.i

**Comment by jleni** [comment]
Any news with respect to this issue? It does not seem to be really fixed. Would it be possible to reopen?

**Comment by jcowles** [comment]
From my perspective, the Swig-specific problem is that the code generated by std_vector.i is not self consistent, for example:

```
SWIGINTERN std::vector< uint64_t > *new_std_vector_Sl_uint64_t_Sg___SWIG_2(int capacity){
        std::vector< unsigned long long >* pv = 0;
        if (capacity >= 0) {
          pv = new std::vector< unsigned long long >();
          pv->reserve(capacity);
       } else {
          throw std::out_of_range("capacity");
       }
       return pv;
      }
```

So yes, uint64_t may not be portable, but the code generated by Swig here uses uint64_t for the return value, but unsigned long long for the temporary variable to be returned, which directly triggers the portability issue.

Is that not the case?

**Comment by wsfulton** [comment]
The code generated by SWIG will depend on whether or not you use `#define SWIGWORDSIZE64` before including stdint.i. This is very much a workaround that needs improving as this generates platform specific code. Another workaround (also platform specific is to use %apply:
```
%apply unsigned long long { uint64_t }
%include <std_vector.i>
%template(VectorUint64) std::vector<uint64_t>;
```
The proper fix is to add in typemaps in terms of C99 stdint.h types in addition to the platform specific C89 types (int, unsigned int etc). That's quite a big job. Let's leave this issue to contain workarounds and someone can open a new ticket to discuss the implementation of this. It will be quite a big undertaking.

**Comment by nioncode** [comment]
I think I am facing a similar issue and am unable to solve it. I'm testing this on Linux 64bit, with SWIG Version 4.0.1.
@wsfulton can you suggest a workaround for this example?

demo.h:
```cpp
#include <limits>
#include <cstdint>
#include <vector>

std::vector<uint64_t> generateNumbers() {
	auto x = std::vector<uint64_t>();
	x.push_back(UINT32_MAX + 1);
	x.push_back(UINT32_MAX + 2);
	x.push_back(UINT32_MAX + 3);
	return x;
}

uint64_t generateNumber() {
	return UINT32_MAX + 4;
}

int main() {
	return 0;
}
```

swig file:
```swig
%module Demo

%{
#include "demo.h"
%}

%include "stdint.i"
%include "typemaps.i"
%include "std_vector.i"
%template(VecUint64) std::vector<uint64_t>;

%include demo.h
```

Compiling with:
```sh
swig -c++ -csharp demo.i
g++ demo_wrap.cxx
```

This leads to compilation errors, e.g.:
> error: cannot convert ‘std::vector<long long unsigned int>*’ to ‘std::vector<long unsigned int>*’ in return

Trying to apply your workaround, by compiling with:
```sh
swig -c++ -csharp -DSWIGWORDSIZE64 demo.i
g++ demo_wrap.cxx
```

This compiles without errors, HOWEVER, my c# code uses `uint` instead of `ulong` in the vector and will thus truncate the values to 32bit. I tried to use a typedef or `%apply`, but it either fails to compile or the resulting type is `uint` and not `ulong`.

**Comment by Mizux** [comment]
Personally I've got lot of inconsistency in typemaps for .Net (and Java)  so I'm currently using this:
```swig
#if defined(SWIGCSHARP)
#if defined(SWIGWORDSIZE64)
%define PRIMITIVE_TYPEMAP(NEW_TYPE, TYPE)
%clear NEW_TYPE;
%clear NEW_TYPE *;
%clear NEW_TYPE &;
%clear const NEW_TYPE &;
%apply TYPE { NEW_TYPE };
%apply TYPE * { NEW_TYPE * };
%apply TYPE & { NEW_TYPE & };
%apply const TYPE & { const NEW_TYPE & };
%enddef // PRIMITIVE_TYPEMAP
PRIMITIVE_TYPEMAP(long int, long long);
PRIMITIVE_TYPEMAP(unsigned long int, unsigned long long);
#undef PRIMITIVE_TYPEMAP
#endif // defined(SWIGWORDSIZE64)
#endif // defined(SWIGCSHARP)
```
ref: https://github.com/google/or-tools/blob/stable/cmake/doc/swig.md#swig-int64_t-management-stuff

Hope it will help you

**Comment by nioncode** [comment]
@Mizux thank you so much for the fast reply, it works wonderfully! I tried for hours today to get this to work and almost considered copying the c# sources that swig generates on Windows to my Linux builds in the CI pipeline. Your solution is much nicer, thank you.

I think this would also be fixed by #650.

**Comment by MaxBarraclough** [comment]
`stdint.i` still contains non-portable typedefs. Are there really platforms out there that still don't define the fixed-width integer types in their `stdint.h` header?

*edit* In line with @wsfulton's comment, I [see](https://github.com/swig/swig/blob/3b822ee60c9195283f461120252fdf34b7328050/Lib/stdint.i#L17) this:

```C
#if defined(SWIGWORDSIZE64)
typedef long int		int64_t;
#else
typedef long long int		int64_t;
#endif
````

This is 'theoretically' non-portable as the C/C++ standards do not guarantee that this will behave as hoped. Beyond that, I don't see why it should work in practice:

(edited in May 2026 as I had these the wrong way around)

* In Windows/MSVC/AMD64, `long int` is 32-bit
* In GNU-Linux/GCC/AMD64, `long int` is 64-bit
* (See [Wikipedia](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models))

In both platforms, the standard `stdint.h` (C) and `cstdint` (C++) headers correctly define `int64_t`/`std::int64_t`.

**Comment by h-vetinari** [comment]
Continuing this issue in https://github.com/swig/swig/issues/2923.
