### ISSUE TITLE
Unix installation and configure

### ISSUE THREAD

**Issue by ivan-ushakov** [swig/swig#569]
I'm trying to build Swig on OS X. From documentation `1.12.2 Unix installation`:

    $ ./configure
    $ make
    $ make install

But I don't see `configure` script inside swig directory. Maybe there must be additional step and would be nice to see it in documentation.

**Comment by ojwb** [comment]
Those docs are for building from a released tarball - when building from the git repo see:

http://swig.org/svn.html

The important points are (a) you need more tools installed and (b) run `./autogen.sh`.
