### ISSUE TITLE
Python testcase li_boost_array failed on ARM

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#579]
I tried to build swig 3.0.8 for Fedora, but I got following error on ARM build machine. 

    checking python testcase li_boost_array (with run test)
    Traceback (most recent call last):
      File "li_boost_array_runme.py", line 36, in <module>
        compare_containers(arrayOutVal(), [-2, -1, 0, 0, 1, 2])
      File "li_boost_array_runme.py", line 17, in compare_containers
        compare_sequences(pythonlist, swigarray)
      File "li_boost_array_runme.py", line 14, in compare_sequences
        failed(a, b, "elements are different")
      File "li_boost_array_runme.py", line 6, in failed
        raise RuntimeError, msg + " " + str(list(a)) + " " + str(list(b))
    RuntimeError: elements are different [254, 255, 0, 0, 1, 2] [-2, -1, 0, 0, 1, 2]
    Makefile:102: recipe for target 'li_boost_array.cpptest' failed
    make[1]: *** [li_boost_array.cpptest] Error 1

gcc: 5.3.1
python: 3.5.1

All test passed and swig was successfully built on x86_64 and i686.

**Comment by wsfulton** [comment]
I added this test to swig-3.0.8 to test the new array support. @jplesnik I don't suppose you have an ARM machine handy that you could allow me to log on to and investigate? If not, any emulators you can recommend, QEMU presumably?

**Comment by ahnolds** [comment]
I claim `char` is unsigned on ARM (or at least with your particular Fedora ARM box and compiler combination).  The signedness of char is implementation dependent, and [this article](http://www.arm.linux.org.uk/docs/faqs/signedchar.php) at least claims char is unsigned on ARM machines.  This seems more like a problem in the li_boost_array.i file than anything else, although maybe @wsfulton will disagree.  If you change line 34 of Examples/test-suite/li_boost_array.i from

      const char carray[] = { -2, -1, 0, 0, 1, 2 };

to

      const signed char carray[] = { -2, -1, 0, 0, 1, 2 };

does the test pass?

**Comment by jplesnik** [comment]
Thank you for quick response. The test pass with your changes on ARM buildsystem. It also fixed the test for other architectures like ppc, s390.

**Comment by ahnolds** [comment]
Any other failures from any of those platforms you're aware of while we're at it?  I'll submit a pull request with this one and any others I can diagnose remotely:)

**Comment by ismail** [comment]
https://github.com/swig/swig/pull/580 will fix this. Tested on PPC, PPC64, PPC64LE (and x86 of course).

**Comment by wsfulton** [comment]
#580 has now been merged to master
