### ISSUE TITLE
Java/CSharp sources input argument conversion

### ISSUE THREAD

**Issue by diorcety** [swig/swig#58]
In java.cxx and csharp.cxx at multiple lines you make the conversion of input argument by your own one.

It will better to use "in" typemap to do so.

**Comment by ojwb** [comment]
Line 3397 on that date is the second line here:

```
    if (Len(smartptr)) {
      Printf(code_wrap->code, "  %s *obj = (%s *)objarg;\n", smartptr, smartptr);
      Printf(code_wrap->code, "  // Keep a local instance of the smart pointer around while we are using the raw pointer\n");
      Printf(code_wrap->code, "  // Avoids using smart pointer specific API.\n");
      Printf(code_wrap->code, "  %s *director = dynamic_cast<%s *>(obj->operator->());\n", dirClassName, dirClassName);
    }
```

This is just converting the pointer to the object that the method is being called on from `void*` to a pointer to the appropriate type - this isn't a real parameter to the method, so the `in` typemap isn't appropriate here.

This seems invalid to me, so closing.

@diorcety If you still think there's a problem here, please supply an example showing how/why the current handling is wrong.
