### ISSUE TITLE
SWIG 3.0.8 regression - Python wrapping fails for modules that contain an "Exception" class

### ISSUE THREAD

**Issue by benmwebb** [swig/swig#583]
The following code code can be wrapped just fine with SWIG 3.0.7 but fails with SWIG 3.0.8:

test.h:

    class Exception { };

test.i:

    %module test
    %include "test.h"
    %{
    #include "test.h"
    %}

Then compiled with something like `swig -python -c++ test.i && g++ -o _test.so test_wrap.cxx`
and tested with `echo "import test; t = test.Exception()" | python`

This fails in 3.0.8 because various parts of the SWIG-generated code are protected with `try: ... except Exception:` blocks, and since `Exception` isn't qualified, Python gets confused and thinks you mean the class defined in `test.h`. (3.0.7 does not fail because the protecting block is simply `try: ... except:`.)

A simple solution would be to use `except __builtins__.Exception` instead, which should be valid Python in Python 1.5 through Python 3.4 at least, or go back to the plain "except" block from 3.0.7. I'm happy to create a pull request for either solution if that helps.

**Comment by wsfulton** [comment]
#509 from @sjoerdjob is the original pull request. ```except __builtins__.Exception``` is preferable to reverting #509.

**Comment by sjoerdjob** [comment]
Great to see it's being solved so quickly. Yes, I missed the case of people redefining `Exception`.

Is there any chance somebody is going to be defining `__builtin__` as well (causing another regression)?

**Comment by benmwebb** [comment]
I suppose it's possible somebody might define a `__builtin__` object, but IMHO they should expect all sorts of things to start going awry if they override random `__xxx__` things.

A related issue, of course, is that other exception classes are used unqualified throughout SWIG-generated code (e.g. `AttributeError`) so things will also act a little oddly if people have those in their C++ code.
