### ISSUE TITLE
support of vector of typemapped object.

### ISSUE THREAD

**Issue by autosquid** [swig/swig#587]
I succeeded in typemapped opencv::Mat  from/to numpy ndarray,
and also typemapped `std::vector<cv::Mat>` with `std_vector.i`:
```
%template(ImVec) std::vector<cv::Mat>;
```

But, in python, I found my vector binding does not work as the return, which means:

```
int f(std::vector<cv::Mat>);
```
binding works well, while
```
std::vector<cv::Mat> g()
```
does not.

In python, the type of return of ```g``` is a tuple of `cv::Mat*`, while I expect it 
to be tuple or vector of proxy object of cv::Mat(*).

**Comment by wsfulton** [comment]
You probably don't have the type information for Mat available when g() is parsed. Also try move %template before g() is parsed and after Mat is parsed. A sample demonstrating the problem is needed to investigate any further.
