### ISSUE TITLE
Feature: Copy canvas content to clipboard

### ISSUE THREAD

**Issue by r-englund** [swig/swig#592]
It would be very nice if we could have a button in each canvas processor that puts a copy of the image in that canvas to the clipboard.
QT has this functionality (http://doc.qt.io/qt-5.5/qclipboard.html#setImage), but the canvas does not know about QT. Maybe we can have some virtual functions to help writing to clipboard (maybe also read from) similarly to how we FileObservers

**Comment by vadz** [comment]
This doesn't seem to be appropriate here -- wrong project perhaps?

**Comment by r-englund** [comment]
Ops, im so sorry, had the wrong project selected :)
