### ISSUE TITLE
Assertion `DohGetattr(n, "sym:name")' failed

### ISSUE THREAD

**Issue by jlippuner** [swig/swig#594]
SWIG cannot handle enum classes inside other classes. Here's a minimal example that produces triggers an assertion:

    // file test.hpp
    class Class {
    private:
      enum class Enum {
        Foo,
        Bar
      };
    };

    // file test.i
    %module test

    %{
    #include "test.hpp"
    %}

    %include "test.hpp"

Then running `swig -python -c++ test.i` produces

    swig: ../../Source/Modules/lang.cxx:1657: virtual int Language::enumDeclaration(Node*): Assertion `DohGetattr(n, "sym:name")' failed.
    Aborted (core dumped)

Note that this works with SWIG 3.0.2, but it fails with the failed assertion shown above with both 3.0.7 and 3.0.8. I did not test any version sin between.

**Comment by quang-ha** [comment]
Same problem with me. It works with enum class defined as public class though...

**Comment by ojwb** [comment]
`git bisect` shows this as introduced by 77b338151ef25b9ce1ffd88bbab931379ddea3b3

@wsfulton made that change: "Simplify/improve strongly typed enum implementation for Java"
