### ISSUE TITLE
Swig.exe build error  with Visual Studio 2013 and make

### ISSUE THREAD

**Issue by bartoli** [swig/swig#595]
I tried to build swig on windows, using the ./configure && make, with the compiler of visual studio 2013
Compilation of c files seems fine. But for cxx files cl.exe displays a warning D9035 that -o has been deprecated. This results in Source/Modules/*.cxx being compiled to  Sources/*.obj instead of the expected Sources/Modules/*.obj, where the link line will look for them.
I solved it manually in my case by modifying -o to /Fo in Sources/Makefile.in. For future releases, i think the -o used in Makefile.in should be put in a variable that depends on the compiler (maybe there is even already a variable generated by autoconf for this?)

**Comment by denisdemais** [comment]
hi. suggestion:
try to uses the precompiled win32 version or buils using cygwin

**Comment by bartoli** [comment]
I managed to build completely it in that environment (except ccache) with only the mentionned modification. I'll keep this version, i don't want to install gcc and all its dependencies in cygwin just for swig
It was just a suggestion to improve the portability of the build scripts

**Comment by wsfulton** [comment]
See http://swig.org/Doc3.0/Windows.html#Windows_cygwin_mingw for building SWIG on Windows. A CMakeLists.txt would improve the Windows experience, see the swig-devel mailing list for discussions about this earlier this year.
