### ISSUE TITLE
csharp: duplicate symbols in generated C++ code from multiple SWIG modules

### ISSUE THREAD

**Issue by pjohangustavsson** [swig/swig#604]
Yes, this is in the context where classes sharing names belong to different namespaces are wrapped. At least offer the option to include the namespace identifier in the C++ wrapper code function names. P/Invoke does not enforce any naming conventions the way JNI does, and the Java module of SWIG does not suffer from this issue.

**Comment by wsfulton** [comment]
SWIG does not support symbols with the same name in different namespaces, this is all documented. You can use the %nspace feature to solve this problem. If this isn't working, then please provide some specifics.

**Comment by pjohangustavsson** [comment]
%nspace is a feature that affects how C# or Java code is generated, not C++ wrapper code. Another feature or %module setting might be an option? I believe many would desire something like that.

**Comment by wsfulton** [comment]
%nspace does affect the c++ code generated by mangling in the C++ namespace into the C PInvoke functions. I still don't know what this issue is about as you are not providing any specifics.

**Comment by pjohangustavsson** [comment]
Either way, using %nspace while -namespace is used for a module is not a good idea when the SWIG interface file is intended to represent a namespace that sits at global scope. 

Assume a namespace Logging. You have a logging.i file you pass to SWIG with -namespace Logging. In the original C++ code, Logging contains a class Context that is troublesome. I do %nspace Logging::Context in logging.i. In C# this becomes Logging.Logging.Context. If I remove the -namespace argument, %nspace works but I am left to enable that feature for all classes, else the logging.i file becomes troublesome to %import in other modules. 

Maybe the problem is this: the -namespace argument isn't working for C# the same as the -package argument works for Java. In other words, the -namespace argument do not mangle the names of the PInvoke wrapper functions, while -package do. Is this an issue or by design?

**Comment by pjohangustavsson** [comment]
I've made a patch which checks if -namespace is set and formats the wrapper function names from a formatted string (using Printf) which I then pass to SWIG_name_register, as follows:

String mangled = NewStringf("");
Printf(mangled, "CSharp_%s_%%f", namespc);
SWIG_name_register("wrapper", mangled);
Delete(mangled);

Works like a charm, but will also put wrappers of symbols found at global scope in that namespace as well, but requires less effort by far to adjust than the other way around. Please introduce this patch. I will request a pull shortly. 

PS I think it's ludicrous that you're not using cmake. Took me less than one hour to setup a rough cmake script and successfully build swig on Windows with VS2015.

**Comment by wsfulton** [comment]
I'll look out for the patch.

Regarding Windows development, we test Visual C++ using cccl as we have a very extensive test-suite which is Makefile based. The problem with CMake is everyone is happy to knock up an unmaintainable or nearly working CMakeLists.txt file, but no-one has put in the effort to finish it off. Whether that is ludicrous or not, is a matter of opinion. CMake has been brought up on two recent threads on the swig-devel mailing list with lots of information about CMake in them. Please join that discussion if you wish. Phineas Campbell has even been persuaded to work on it in the very near future.

**Comment by vadz** [comment]
FWIW there is really no need for CMake to build SWIG under Windows, it's so simple to build that you can create a project file for it in less than 5 minutes -- the fact that it took "less than one hour" to do it with CMake is pretty funny in this context.

The test suite is another matter...

**Comment by pjohangustavsson** [comment]
fulton: tests have been running for a while now, should finish within the hour. I also take back what I said about cmake. 

vadz: I hear what you're saying, but manually creating VS projects from existing sources using the IDE is nothing but masochistic. The "less than one hour" also included figuring out the swigconfig.h, fixing missing dependencies and not really keeping track of the time. Not knowing the walk is a cake walk is also to walk with caution. Next time you run. 

Thanks for all your time. I'll do my best to contribute whenever I can.

**Comment by wsfulton** [comment]
Patch is #605 and has been committed.
