### ISSUE TITLE
Argument parse error due to fastunpack, modernargs, compactdefaultargs, and builtin

### ISSUE THREAD

**Issue by derkuci** [swig/swig#607]
When combining -builtin -O together with %feature("compactdefaultargs"), SWIG Python (3.0.8) fails to correctly parse member functions with one argument.  Here's an example:
```
/* File : example.h */
struct Shape {
  void move(double) {}
};
```
```
/* File : example.i */
%module example
%feature("compactdefaultargs");
%{
#include "example.h"
%}
%include "example.h"
```
```
# file: runme.py
import example
s = example.Shape()
s.move(2.0)
```
and the error output:
```
$ swig -python -c++ -builtin -fastunpack -modernargs example.i
$ g++ -g -o _example.so -shared -fPIC -I /usr/include/python2.7 example_wrap.cxx
$ python runme.py
Traceback (most recent call last):
  File "runme.py", line 6, in <module>
    s.move(2.0)
TypeError: in method 'Shape_move', argument 2 of type 'double'
```
The example can work through if we just use -builtin or -O, but not both.

**Comment by derkuci** [comment]
My limited knowledge about SWIG's internals led me to the following snippet in `Source/Modules/python.cxx`:
```
    if (builtin && funpack && !overname && !builtin_ctor && !GetFlag(n, "feature:compactdefaultargs")) {
      String *argattr = NewStringf("%d", tuple_arguments);
      Setattr(n, "python:argcount", argattr);
      Delete(argattr);
    }
```
The attribute "python:argcount" is not set when %feature("compactdefaultargs") is present, and hence the subsequent code generation could only print out METH_VARARGS for member functions with one argument, which conflicts with the argument parse code guided by the other parameters (-fastunpack -modernargs).

I am not sure what a proper fix is.  I boldly removed the check `&& !GetFlag(n, "feature:compactdefaultargs")` from that code snippet, and that did the trick for me.

**Comment by wsfulton** [comment]
Do you know if this is a regression and was working in older versions (eg swig-2.0.12, swig-3.0.2) or has it always been there?

**Comment by derkuci** [comment]
I tried swig 2.0.8 and swig 3.0.2 on a Fedora 18 system.  The issue was there (got TypeError).

**Comment by derkuci** [comment]
@wsfulton just in case you didn't notice, I've submitted a pull request #610 to fix this issue.  Could you give your opinion on that when you have a chance?  Thanks.
