### ISSUE TITLE
Request a Windows C++ PHP example

### ISSUE THREAD

**Issue by ronigonzalez** [swig/swig#608]
Request a Windows C++ PHP example with Visual Studio.
On Linux running OK, but impossible compile in Windows, 
no qualified documentation found specific for PHP - C++ On Windows
Please Help me !

**Comment by ojwb** [comment]
It's not a development environment I use.  You'll probably have more success asking on the SWIG mailing list, which will reach other SWIG users.

**Comment by ronigonzalez** [comment]
Thanks for your replay ojwb! Finally I implemented it directly with zend in windows.
Best regards,
Roni

**Comment by wsfulton** [comment]
@ronigonzalez Given you managed to get this to work, would you be able to contribute the visual studio project files for the Examples\php\class (C++ code) and Examples\php\simple (C code) for other SWIG users? This would be a very valuable contribution. A simple expansion of the instructions at http://www.swig.org/Doc3.0/Windows.html#Windows_visual_studio would then explain how to use it.

**Comment by ojwb** [comment]
@wsfulton I think "I implemented it directly with zend in windows" means "I didn't use SWIG".

**Comment by ronigonzalez** [comment]
Hi ojwb! Sorry for my bad english ! :-) that is correct, I' didn't use SWIG on Windows.
I was not able to get WUIG ( C++ <-> PHP ) working in Windows like in linux.
Sorry !
