### ISSUE TITLE
Ignoring/renaming member of typedef struct

### ISSUE THREAD

**Issue by manu-m** [swig/swig#609]
How can I ignore/rename a member of typedef struct like:

``` c
typedef struct 
{
    int i;
    int j;
} struct1;
```

Using `%ignore struct1::j` doesn't work. What am I doing wrong?

**Comment by wsfulton** [comment]
```struct1``` is a typedef name so won't work for scoping. Unnamed structs like this are one of the cases where there is no scope to target the members. Your options are not ideal if you can't modify the source code. If this struct is in a header called structs.h consider:
```c
typedef struct 
{
    int i;
//    int j;
} struct1;
%ignore struct1;
%include <structs.h>
```
or do a global ignore, but this will ignore all symbols with this name:
```
%ignore j;
```
or the most targeted ignore I could come up with is the following which ignores **all** member variables of type int called j:
```
%rename("$ignore", %$isvariable, "match$ismember"="1", "match$type"="int") j;
```
I was hoping to be able to match the parentNode too, but I couldn't get it to work.

**Comment by manu-m** [comment]
Thank you very much for your hints. I can't modify the definition of the struct because it is also used in project that is compliant to MISRA and MISRA only allows to define a struct in the way I outlined above.

So I have to find an alternative solution.

**Comment by ojwb** [comment]
> `struct1` is a typedef name so won't work for scoping. Unnamed structs like this are one of the cases where there is no scope to target the members.

Would it work for SWIG to treat `struct1` as the name of the struct for scoping purposes when it is otherwise unnamed?

Or is that going to open up a whole other can of worms?

**Comment by wsfulton** [comment]
Yeah, I don't want to go there. One of the two suggestions needs to be used and has been in the GSL link.
