### ISSUE TITLE
Error after updating to Swig 3.0.8

### ISSUE THREAD

**Issue by dbogdanov** [swig/swig#611]
Swig 3.0.8 breaks my [project](https://github.com/MTG/gaia) when building python bindings from C++ with an error 

```
Assertion failed: (!Getattr(n, "defaultargs")), function update_defaultargs, file parser.y, line 667.
Abort trap: 6
```

Tested on OSX with swig installed from Homebrew. Swig 3.0.4 worked just fine. I wonder what did this update change.

**Comment by wsfulton** [comment]
This is related to the fix for #529. Can you please provide a cutdown testcase to replicate this or if that isn't easy, run swig with the -E option and pipe this preprocessed output into a file I can access.

**Comment by ahnolds** [comment]
Forked in the hope something would jump out at me, but nope.  Here's the preprocessed output: https://raw.githubusercontent.com/ahnolds/gaia/swig/swig_preprocessed

**Comment by wsfulton** [comment]
What were the exact command line options that caused the assert and were the same used to generate the preprocessed output?

**Comment by ahnolds** [comment]
The full command during the build process seems to have been the following

    /usr/local/bin/swig -c++ -python -w451 \
    -o /home/alec/experiments/gaia/build/src/bindings/gaia2.swigwrap_1.cxx \
    -I/home/alec/experiments/gaia/build/src \
    -I/home/alec/experiments/gaia/src \
    -I/home/alec/experiments/gaia/build/src/bindings \
    -I/home/alec/experiments/gaia/src/bindings \
    -I/home/alec/experiments/gaia/build/src/metrics \
    -I/home/alec/experiments/gaia/src/metrics \
    -I/home/alec/experiments/gaia/build/src/3rdparty \
    -I/home/alec/experiments/gaia/src/3rdparty \
    -I/usr/include/python2.7 \
    -I/usr/include/x86_64-linux-gnu/python2.7 \
    -I/usr/include/qt4 \
    -I/usr/include/qt4/QtCore \
    -DGAIA_VERSION="2.4.4" -DGAIA_GIT_SHA="v2.4.4-20-g62af748" -DHAVE_QTCORE=1 \
    -DHAVE_QTGUI=1 -DHAVE_QTUITOOLS=1 -DHAVE_QTNETWORK=1 -DHAVE_QTOPENGL=1 \
    -DHAVE_QTSQL=1 -DHAVE_QTSVG=1 -DHAVE_QTTEST=1 -DHAVE_QTXML=1 \
    -DHAVE_QTXMLPATTERNS=1 -DHAVE_QTWEBKIT=1 -DHAVE_QT3SUPPORT=1 \
    -DHAVE_QTHELP=1 -DHAVE_QTSCRIPT=1 -DHAVE_QTDECLARATIVE=1 \
    -DPYTHONDIR="/usr/local/lib/python2.7/dist-packages" \
    -DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages" -DHAVE_PYTHON_H=1 \
    -DNDEBUG -D_FORTIFY_SOURCE=2 -DNDEBUG -D_FORTIFY_SOURCE=2 -DQT_SHARED \
    ../src/bindings/gaia.swig

I generated the preprocessed output with exactly the same command, just with the `-E` flag inserted immediately following the `-w451` flag.  However, I will note that I get exactly the same error for

    /usr/local/bin/swig -c++ -python ../src/bindings/gaia.swig

And the same preprocessed output for

    /usr/local/bin/swig -c++ -python -E ../src/bindings/gaia.swig

You also get the same warning and the same preprocessed output (except the %includefile paths lose the leading ..) if you run without the right relative path from the main directory instead of a build subdirectory.

**Comment by dbogdanov** [comment]
Thanks for posting that for me! Is there any more information required?

**Comment by wsfulton** [comment]
Although everything needed to debug it is has been provided, it'll be less work for me if a small standalone example is provided.

**Comment by wsfulton** [comment]
@dbogdanov can you provide this?

**Comment by wsfulton** [comment]
I used the preprocessed output which replicated the assertion, then narrowed it down to this simple code:
```
%inline %{
namespace gaia2 {

struct Filter {};
struct SearchResults {};
//struct SearchPoint {};
//struct DataSet {};

template <typename SearchPointType, typename DataSetType>
class BaseSearchSpace {};

template <typename SearchPointType, typename DataSetType>
class BaseResultSet {};
}
%}

%extend gaia2::BaseResultSet<gaia2::SearchPoint, gaia2::DataSet> {

  void _get(int n, int offset = 0) {}

  %insert("python") %{
    def get(self, n, offset = 0):
      return self._get(n, offset)
  %}
}

%template(ResultSet) gaia2::BaseResultSet<gaia2::SearchPoint, gaia2::DataSet>;
```
It's something to do with the %extend, templates and default args. Hmmm, now to fix it...
