### ISSUE TITLE
javapackage typemap is only applied to function's return type

### ISSUE THREAD

**Issue by manu-m** [swig/swig#618]
I have a module (called example-core) that defines some basic types that are used by other modules. The core module is defined as follows:
```
%module ExampleCore

SWIG_JAVABODY_METHODS(public, public, SWIGTYPE);

%include <std_vector.i>
%template(CharVector) std::vector<char>;
```
SWIG is invoked with `com.example.core` for package parameter, so SWIG creates a resulting Java class called `com.example.core.CharVector`. Up to here everthing works quite well.

Another module has a class that represents a director. This class contains a method that expects and returns `std::vector<char>` on C++ side. To use corresponding `CharVector` from core module on Java side I define some typemaps to import and use the correct type. The complete interface file for this module is defined as follows:
```
%module(directors="1") ExampleRequest

SWIG_JAVABODY_METHODS(public, public, SWIGTYPE);

%import "../example-core/example-core.i"

%feature("director") RequestHandler;

%pragma(java) jniclassimports=%{
import com.example.core.CharVector;
%}
%typemap(javaimports) RequestHandler "import com.example.core.CharVector;";
%typemap(javapackage) std::vector<char> "com.example.core";

%inline %{
#include <vector>

class RequestHandler
{
protected:
    virtual void onInit();
    virtual std::vector<char> onRequest(const std::vector<char>& data) = 0;
    
public:
    void launch()
    {
        this->onInit();
        std::vector<char> data;
        data.push_back(1);
        data.push_back(2);
        auto requestResult = this->onRequest(data);
    }
};
%}
```

As you can see in the following code snippet the C++ wrapper code defines that the onRequest method expects a `com.example.request.CharVector` and not a `com.example.core.CharVector` (but the return type is correct!). Due to this wrong signature definition I get a NoSuchMethod Exception.
```cpp
static struct {
  const char *mname;
  const char *mdesc;
  jmethodID base_methid;
} methods[] = {
  {
    "onInit", "()V", NULL 
  },
  {
    "onRequest", "(Lcom/example/request/CharVector;)Lcom/example/core/CharVector;", NULL 
  }
};
```
If I change the signature definition as follows, it works as expected.
```cpp
    "onRequest", "(Lcom/example/core/CharVector;)Lcom/example/core/CharVector;", NULL 
```

So the question is: is my javapackage typemap incorrect or incomplete or is it a bug in SWIG?

**Comment by wsfulton** [comment]
Take a look at the documentation on ```%typemap(javapackage)``` at http://swig.org/Doc3.0/Java.html#Java_directors_typemaps, in particular it says:

> SWIG looks up the package based on the actual type (plain Foo, Foo pointer and Foo reference), so it is important to associate all three types with the desired package.

With your code, I get:
```c
    {
      "onRequest", "(LCharVector;)Lcom/example/core/CharVector;", NULL 
    }
```
so, I don't think you have fully provided everything. However, given what the docs say, you should instead use:

```swig
%typemap(javapackage) const std::vector<char>&, std::vector<char> "com.example.core";
```
which gives what you want.
