### ISSUE TITLE
%#if is sometimes not converted to #if in generated C++ code

### ISSUE THREAD

**Issue by LindleyF** [swig/swig#622]
I have two typemap(in) definitions which are identical except for one taking a type by value and the other by const reference. Both typemaps contain something like:

%#if defined(ANDROID)
DoSomething();
%#endif

For the value typemap, this works as expected, becoming
#if defined(ANDROID)
DoSomething();
#endif

in the generated code; but for the const ref typemap, it's propagated exactly, showing up in the C++ as:
%#if defined(ANDROID)
DoSomething();
%#endif
which obviously doesn't work.

**Comment by wsfulton** [comment]
Probably the two typemaps are using different delimeters. Take a look at http://www.swig.org/Doc3.0/Preprocessor.html#Preprocessor_delimiters and the next section http://www.swig.org/Doc3.0/Preprocessor.html#Preprocessor_typemap_delimiters.

If not, please post an example.

**Comment by ojwb** [comment]
No response from submitter for 4 months, so closing.

@LindleyF If it's not just due to different delimiters, please post an example as wsfulton requested and we can reopen.
