### ISSUE TITLE
Incorrect conversion between unsigned long long and BigInteger

### ISSUE THREAD

**Issue by matejvasek** [swig/swig#623]
Some values of BigInteger are not converted correctly. For instance -1 is converted to 255.

To fix the issue I had to replace:
$1 = ($1 << 8) | ($1_type)(unsigned char)bae[i];"
with:
$1 = ($1 << 8) | ($1_type)(char)bae[i];
in java.swg

I am running 64-bit linux, gcc version 4.8.5. Tried with various version of Java.

**Comment by wsfulton** [comment]
```char``` is unsigned on some operating systems, so possibly you meant to change the cast to ```signed char``` or better still ```jbyte```.

However, more fundamentally, ```unsigned long long``` is an unsigned type, so passing negative numbers is not expected. I presume you would like it contain the value if you were to cast it to the signed type ```signed long long```? That seems fair enough, except your patch breaks positive numbers. For example, 128 is converted to 18446744073709551488 in C++. 

Here is some test code I used:
```swig
%inline %{
#include <iostream>
long long gogo(unsigned long long ull) {
  std::cout << "C++  " << ull << " " << (long long)ull << std::endl;
  return (long long)ull;
}
%}
```
```java
import java.math.BigInteger;

public class runme {
  static {
    try {
        System.loadLibrary("example");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. See the chapter on Dynamic Linking Problems in the SWIG Java documentation for help.\n" + e);
      System.exit(1);
    }
  }

  public static void main(String argv[]) 
  {
    String[] numbers = {"127", "128", "255", "256", "0", "-1", "-126", "-127", "-128", "-254", "-255", "-256"};
    for (String number : numbers) {
      BigInteger bi = new BigInteger(number);
      long longReturn = example.gogo(bi);
      if (bi.longValue() != longReturn)
        System.out.println("Conversion to long failed, in:" + bi + " out:" + longReturn);
    }
  }
}
```

**Comment by matejvasek** [comment]
Thanks for your reply.

You are right the patch is really incorrect -- works only for values within one byte.
I tried to fix it:

`
arg1 = 0;
arg1 = (arg1 << 8) | (unsigned long long)(char)bae[0];
    for(i=1; i<sz; i++) {
    arg1 = (arg1 << 8) | (unsigned long long)(unsigned char)bae[i];
}`

Cast to char instead of unsigned char is applied only on first byte.

Your test now prints following (I added some extra values to test):

`String[]numbers =
    {
    "127", "128", "255", "256", "0", "-1", "-126", "-127", "-128", "-254",
	"-255", "-256", "6000000", "0", "-600000", "18446744073709551615", "18446744073709551616"};`

C++  127 127
C++  128 128
C++  255 255
C++  256 256
C++  0 0
C++  18446744073709551615 -1
C++  18446744073709551490 -126
C++  18446744073709551489 -127
C++  18446744073709551488 -128
C++  18446744073709551362 -254
C++  18446744073709551361 -255
C++  18446744073709551360 -256
C++  6000000 6000000
C++  0 0
C++  18446744073708951616 -600000
C++  18446744073709551615 -1
C++  0 0

Is it correct now?

I understand that converting negative value to unsigned type is not completely sensible, but returning 255 for -1 or -2 is last thing one would expect. I would expect it either throw an exception or overflow like C/C++ does.

Why I do care about this?
I came upon this issue while porting llvm-j form JNA to JNI, since JNA doen't work with newer version of llvm (generator for JNA generated invalid java code).
API of llvm  contains function
`LLVMValueRef 	LLVMConstInt (LLVMTypeRef IntTy, unsigned long long N, LLVMBool SignExtend)` and it looks like it counts with overflowing. If I pass 18446744073709551615 (max unsigned long long), produced bitcode contains -1 instead of 18446744073709551615.

When I call:
`LLVMConstInt(TypeRef.int32Type().type(), new BigInteger("18446744073709551615"), 1)`
produced bitcode looks like:
`store i32 -1, i32* %a`

I might be missing something. I would be glad if you corrected me.

**Comment by ojwb** [comment]
I don't know about overall, but this part isn't portable since plain `char` can be either signed or unsigned (it's unsigned on ARM, at least on Linux):

> Cast to char instead of unsigned char is applied only on first byte

You need to explicitly use `signed char` if you want a signed char type:
