### ISSUE TITLE
[node.js] addons crash with calling constructor without new

### ISSUE THREAD

**Issue by 3rduncle** [swig/swig#626]
Hello,
I swig a simple class like this:

``` cpp
class Base {
public:
        Base(const int& y, const int& m, const int& d)
                : year(y), month(m), day(d)
        {
        }
        int year;
        int month;
        int day;
};
```

and wrap.i like this:

```
%{
#include "base.h"
%}
%include "base.h"
```

when I call the constructor of swiged Base, I got this **CRASH** install of **Exception**

``` js
> var BASE = require('.');
undefined
> var a = BASE.Base(1, 2, 3);
```

``` cpp
FATAL ERROR: v8::Object::SetAlignedPointerInInternalField() Internal field out of bounds
```

Is this a bug? Swig version is 3.0.7

**Comment by ianmacs** [comment]
This is a bug in my opinion. But I'm not involved with Swig and do not know their stance on crashes. And I do not know node.js internals enough to judge whether the missing `new` can be detected by the wrapper code, i.e., whether this can be fixed by Swig at all.

**Comment by p2k** [comment]
It can be fixed, but we have two options:
1) Throw an exception (which can be caught on the JS side without crash)
2) Be "nice" and return a new object anyway (by detecting whether it is a function or constructor call and translating it)

I've seen both approaches in various JavaScript projects, so I'm not sure what's best. More strict or more relaxed?

**Comment by p2k** [comment]
On second thought, the way inheritance works dictates that we should go the first route. Internally, we check if the internal field count is right and if not, throw an error. This way things work as expected and unintended use is prohibited. Will make a pull request soon.
