### ISSUE TITLE
[PHP] Wrong code generation for attribute "feature:director:except"

### ISSUE THREAD

**Issue by SergeySeroshtan** [swig/swig#627]
When use [Exception unrolling](http://www.swig.org/Doc3.0/SWIGDocumentation.html#Php_nn3_4) feature:
```
%feature("director:except") {
    if ($error == FAILURE) {
        throw Swig::DirectorMethodException();
    }
}
```
generated code is not correct, i.e. when add this feature to the `php/callback` example, then get:
```cpp
void SwigDirector_Callback::run() {
  ...
  int error;
  ...
  call_user_function(EG(function_table), (zval**)&swig_self, &funcname, result, 0, args TSRMLS_CC);
  {
    if (error == FAILURE) {
      throw Swig::DirectorMethodException();
    }
  }
  ...
}
```
Local variable **error** is not initialized and not defined later, which leads to the unpredictable behavior.
[This patch](https://github.com/swig/swig/files/161113/php_feature_director_except_fix.txt) fix this issue and generate next code:
```cpp
void SwigDirector_Callback::run() {
  ...
  int error;
  ...
  error = call_user_function(EG(function_table), (zval**)&swig_self, &funcname, result, 0, args TSRMLS_CC);
  {
    if (error == FAILURE) {
      throw Swig::DirectorMethodException();
    }
  }
  ...
}
```
Now local variable `error` contains result of the function  `call_user_function()`.

**Comment by ojwb** [comment]
That does indeed look like the cause of the problem.

Any chance you could work whatever your latest iteration of this fix is up into a PR with a simple regression test?

**Comment by SergeySeroshtan** [comment]
I'll try to add the regression test as soon as possible.

**Comment by SergeySeroshtan** [comment]
Thanks a lot for this fix. I was very busy to provide PR with appropriate regression tests.
