### ISSUE TITLE
[javascript] How can I get a char* OUTPUT from c++ to javascript ?

### ISSUE THREAD

**Issue by liangxinhui** [swig/swig#638]
I have a c++ interface like this:

`int foo(char* pStrOut);`

the `pStrOut` is an output argument. I want deal with it in javascript as String.

I searched in the swig example of  `javascript`, and didn't get it.

Please help me, thanks!

**Comment by ptomulik** [comment]
I think, you should rather send this question to the swig-user mailing list.

http://www.swig.org/mail.html
https://sourceforge.net/p/swig/mailman/swig-user/
https://lists.sourceforge.net/lists/listinfo/swig-user

**Comment by ojwb** [comment]
Yes, this is a question, not a SWIG bug or enhancement.
