### ISSUE TITLE
Java integer types do not work correctly with -DSWIGWORDSIZE64

### ISSUE THREAD

**Issue by johnwason** [swig/swig#646]
On most systems, `int64_t` is the same as `long long`, and  `uint64_t` is the same as `unsigned long long`.  On gcc Linux x86_64 however, `int64_t` becomes `long` and `uint64_t` becomes `unsigned long`.  To handle this the switch `-DSWIGWORDSIZE64` is used.  While Python and C# handle this switch correctly, Java does not.  It tries to typedef `int64_t` to a java `int` when `-DSWIGWORDSIZE64` is specified because it sees the `long`/`unsigned long` types. It should be converting `int64_t` to a java `long` and `uint64_t` to `BigInteger` in all cases. It should detect that `-DSWIGWORDSIZE64` is defined and translate accordingly.

**Comment by Mizux** [comment]
My 2 cents currently I use this workaround
```swig
%include "typemaps.i"
...
#if defined(SWIGJAVA)
#if defined(SWIGWORDSIZE64)
%define PRIMITIVE_TYPEMAP(NEW_TYPE, TYPE)
%clear NEW_TYPE;
%clear NEW_TYPE *;
%clear NEW_TYPE &;
%clear const NEW_TYPE &;
%apply TYPE { NEW_TYPE };
%apply TYPE * { NEW_TYPE * };
%apply TYPE & { NEW_TYPE & };
%apply const TYPE & { const NEW_TYPE & };
%enddef // PRIMITIVE_TYPEMAP
PRIMITIVE_TYPEMAP(long int, long long);
PRIMITIVE_TYPEMAP(unsigned long int, long long);
#undef PRIMITIVE_TYPEMAP
#endif // defined(SWIGWORDSIZE64)
#endif // defined(SWIGJAVA)
```
ref: https://github.com/google/or-tools/blob/stable/cmake/doc/swig.md
