### ISSUE TITLE
This file requires compiler and library support for the ISO C++ 2011 standard

### ISSUE THREAD

**Issue by algorys** [swig/swig#648]
Hello,

I'm trying to use SWIG to connect some shared library with Python. I managed to use it for a simple class  in c++ and that's working great. Now I want to use it for a more complex project.

but when I try to compile, i've the following error :

```
cd /home/mea/PycharmProjects/swigelec/build/elecswig && /usr/local/bin/swig -python -includeall -outdir /home/mea/PycharmProjects/swigelec/build/elecswig -c++ -I/home/mea/workspace/repos/corealpi/include -I/usr/include/c++/5.2.1 -I/usr/include/python2.7 -o /home/mea/PycharmProjects/swigelec/build/elecswig/elecPYTHON_wrap.cxx /home/mea/PycharmProjects/swigelec/elecswig/src/elec.i
/usr/include/c++/5.2.1/bits/c++0x_warning.h:32: Error: CPP #error "This file requires compiler and library support for the \
ISO C++ 2011 standard. This support is currently experimental, and must be \
enabled with the -std=c++11 or -std=gnu++11 compiler options.". Use the -cpperraswarn option to continue swig processing.
```

If i look inside `/usr/include/c++/5.2.1/bits/c++0x_warning.h` at line 32, I have the following : 

```
#if __cplusplus < 201103L
#error This file requires compiler and library support for the \
ISO C++ 2011 standard. This support is currently experimental, and must be \
enabled with the -std=c++11 or -std=gnu++11 compiler options.
#endif
```

Here is my config : 

CMakeLists : 
```
project(elecswig)

include_directories(${COREALPI_DIR}/include)
include_directories(/usr/include/c++/5.2.1)

find_package(SWIG REQUIRED)
include(${SWIG_USE_FILE})

find_package(PythonLibs)
include_directories(${PYTHON_INCLUDE_PATH})

set_source_files_properties(src/elec.i PROPERTIES CPLUSPLUS ON)
set_source_files_properties(src/elec.i PROPERTIES SWIG_FLAGS "-includeall")

link_directories(${COREALPI_LIBRARY})

swig_add_module(elecswig python src/elec.i)

swig_link_libraries(elecswig
    ${PYTHON_LIBRARIES}
    elec
)
```

I've include .h inside my elec.i

```
#define __linux__ 1
#define __GNUC__ 4

%module elecswig
%{
    #include "ca/elec/model/modelvoltagedrop.h"
%}

%include "ca/elec/model/modelvoltagedrop.h"
```

I'm not expert in C++ and all specificities of this language...

Is there a way to activate c++11 with swig somewhere ?

I've to precise I can compile some c++11 code for other project...

Or does I have to precise something in `elec.i` ?

Thanks for help.

**Comment by algorys** [comment]
Here is the solution :

After hours of tests, I found reason why it was not working. In the CMakeLists :

set_source_files_properties(src/elec.i PROPERTIES SWIG_FLAGS "-includeall")
include all libraries and dependencies, anyway of compiler use. And if you have 2 version of libstdc++ and gcc/g++, it seems he can't find the good libraries to link / use.

If I remove it, CMake does the job. I have no more unable to find or c++11 problems.

I've to use g++-5 to make it work too (4.9 seems miss some features for c++11) and add the good namespace and include.

Now I've access to my shared library in Python.

Do you think @wsfulton there is an issue ?

**Comment by ojwb** [comment]
`-includeall` tells SWIG to follow `#include` and parse the resulting headers.  In my experience, that's rarely what you want - getting SWIG to parse your system and/or compiler headers is rarely useful.

But if you really want to do that, use `-cpperraswarn` as the error you got suggested:

```
Use the -cpperraswarn option to continue swig processing.
```

**Comment by algorys** [comment]
Hello @ojwb 

I doesn't want to parse system headers but the project is a core who use low level function. That's why I have some errors like this I think.

Thank you anyway for the help.
