### ISSUE TITLE
failing to identify class-method in using directive

### ISSUE THREAD

**Issue by fschlimb** [swig/swig#655]
SWIG doesn't find a method for 'using' in class which is used via 'using' itself.
The following simple code gives the error

``````
swig -c++ -python using_member.i
using_member.i:16: Warning 315: Nothing known about 'A::get'.```
``````

```
%module using_member;

namespace interface1
{
    class A
    {
    public:
        int get(int);
    };
}
using interface1::A;

class B : public A
{
 public:
    using A::get;
    int get(double);
};
```

Note that `using A::interface1::get;` works fine. Unfortunately fixing it this way in the C++ code is not an option.

Also note that SWIG correctly identifies `A` when it's declared as the base-class, but not when searching for the method in the `using` directive.

Because of the latter this looks like it could be a simple fix. I'd be willing to invest some time in fixing it myself but would need some hints as I am not familiar with the SWIG code.

Any idea and/or help?

**Comment by wsfulton** [comment]
This will be a problem in the symbol table management and lookup (symbol.c). There is probably a Swig_symbol_clookup call which fails and causes the warning. I suspect there is a missing recursive using lookup (ie not following all using nodes).

For learning about SWIG source and its quirks, take a look at http://swig.org/Doc3.0/Extending.html and the development docs, especially the debugging section in Doc/Devel/internals.html#7. I notice that when using the -debug-csymbols option, the output is:

```
example.i:19: Warning 315: Nothing known about 'A::get'.
CSYMBOLS start  =======================================
===================================================
 -
  swig (namespace)
  interface1 (namespace)
  A (using)
  std (namespace)
  B (class)
===================================================
std::initializer_list -
  T (templateparm)
===================================================
swig -
  SwigPtr_PyObject (class)
  SwigVar_PyObject (class)
===================================================
interface1 -
  A (class)
===================================================
std -
  initializer_list<(T)> (template)
  initializer_list (template)
===================================================
B -
  get (using)
```
So looks like ```B::get``` has been added into the symbol table, so the problem is likely to be in the lookup.

**Comment by wsfulton** [comment]
BTW, there are other 'using' bugs that you might stumble across and be aware of while researching this. If you remove all the namespaces from your code, then consider this:
```c++
class B : public A
{
 public:
    using A::get; // line 4
    int get(double, double); // line 5
};
```
If you swap lines 4 and 5 around, the generated code for overloading doesn't work (for one of the swapped combinations, I don't recall which).

**Comment by tamuratak** [comment]
How about using %extend?

````
class B : public A
{
public:
  %extend{
    int get(int i){
      return $self->get(i);
    }
  }
  int get(double);
};
````

**Comment by fschlimb** [comment]
Thanks, but I can't edit the C++ headers.
With the actual code SWIG not only issues a warning but also seg-faults. So I need a fix in SWIG.

**Comment by tamuratak** [comment]
What I mean is to replace A::get in the SWIG code with the %extend{}
without editing C++ headers. I think the following SWIG code will generate
a desired  using_member_wrap.cxx.

````
%module using_member;

namespace interface1
{
    class A
    {
    public:
        int get(int);
    };
}
using interface1::A;

class B : public A
{
 public:
   %extend{
     int get(int i){
       return $self->get(i);
     }
   }
    int get(double);
};
````

**Comment by fschlimb** [comment]
Hm, don't think I understand.
A and B are both taken from C++ headers, Neither I can change.
The situation is actually more complicated:
A defines more than one "get" and I need to rename them.
Yes i could copy all get overloads from the A header and add with extend. This would of course not fix the seg-fault. Moreover, this would be very tedious as this happens in ~ 70 files...

**Comment by tamuratak** [comment]
Ok, I understand. Sorry for bothering you.

**Comment by fschlimb** [comment]
Thanks. Any idea is appreciated!

**Comment by fschlimb** [comment]
I stepped through the execution and here is where I think the problem is:
#1  0x000000000052931c in symbol_lookup_qualified (name=0x7ffff6eda130, symtab=0x7ffff7f5c950, prefix=0x7ffff6eda110, local=0, checkfunc=0x0) at Swig/symbol.c:1041
1041        st = Getattr(symtabs, cqname);

This should find 'A'  as a "using", but the table has no entry for it:

(gdb) sp symtabs
Hash(0x7ffff7f5ca10) {
  '' : Hash(0x7ffff7f5c950) {.....},
  'std::initializer_list' : Hash(0x7ffff7f8fbf0) {.....},
  'swig' : Hash(0x7ffff6ece970) {........},
  'interface1' : Hash(0x7ffff6ed8010) {........},
  'std' : Hash(0x7ffff7f8f7f0) {........},
  'B' : Hash(0x7ffff6ed8b30) {......},
  'swig::SwigPtr_PyObject' : Hash(0x7ffff6eced50) {......},
  'swig::SwigVar_PyObject' : Hash(0x7ffff6ecfe90) {.....},
  'interface1::A' : Hash(0x7ffff6ed8210) {.....},
}
(gdb) sp cqname
A

@wsfulton Where can I find the "using" declarations? I expected them to be here (assuming this is the table which -debug-csymbols prints).

**Comment by wsfulton** [comment]
I'm not sure without spending time debugging, but ```'interface1::A' : Hash(0x7ffff6ed8210) {.....},``` looks like it is the using node. You can check by expanding symtabs to show 2 levels -> ```swigprint symtabs 2```. As you'd expect in C++ symbol resolution, the resolution of any symbol is non-trivial and I suspect the resolution is not following using nodes.

**Comment by fschlimb** [comment]
After some experimenting I had a fix for the simple case above. Unfortunately it turned out to be not generic enough (and for that too complicated).

The issue is that when climbing up the node-tree, the only check for the existence of the currently tried node (e.g. current scope + prefix) is made by inspecting the "global" table ```symtabs```. It never find the using node as these are not added to the ```symtabs``` hash. 
It seems all that is needed is adding such "using" nodes to ```symtabs```. Unfortunately I could not figure out how this could be done.

@wsfulton Any hint?

---
These "using" nodes are only found in "symtabs/csymtabs", never as a member of a node, e.g. not like 'A' is found in node 'interface'.

**Comment by wsfulton** [comment]
Sorry, I don't have time to debug this myself so all I can offer is an observation and suggestion. That is, both C++ class inheritance and 'using' inherit symbols into a scope. They both use Swig_symbol_inherit to implement this. I was going to suggest debugging the following to see what should happen as the symbol lookup should be the same:
```c++
namespace interface1
{
    class A
    {
    public:
        typedef int Integer;
        int get(int);
    };
}
//using interface1::A;

class B : public interface1::A
{
 public:
//    using A::get;
      void foo(A::Integer);
//    int get(double);
};
```
Given that this unfortunately also fails, perhaps ```Swig_symbol_inherit()``` needs closer examination for a bug. Surely this adds the using node to the symbol tables.

**Comment by wsfulton** [comment]
Just found this in symbol.c:
```
/* -----------------------------------------------------------------------------
 * Swig_symbol_inherit()
 *
 * Inherit symbols from another scope. Primarily for C++ inheritance and
 * for using directives, such as 'using namespace X;'
 * but not for using declarations, such as 'using A;'.
```
mmm, not sure why, maybe because using declarations only introduce one symbol rather than many. My hunch is then that the symbol lookup/resolution probably is the area to focus on.

**Comment by fschlimb** [comment]
Thanks for your help. With this kind of support I should be able to get it done.

Yes, the using directive which fails creates a scope with a single entry in the "inherit" list (of course pointing to the right class type). This data/type hierarchy however seems unrelated to what is used in the lookup mechanics.

I still think that the only missing bit is that when creating the using node all we need is adding an entry in the global ```symtabs``` hash. I simply couldn't figure out how/where this could be done.
If that's not the right thing, the lookup mechanics need significant changes, e.g. we'd need to explicitly walk down all child nodes of the nodes that we visit during the current up-walk. 

Though, adding it to the ```symtabs``` hash looks ok as far as I can see from how it is used elsewhere.
If you have any idea how I can get the using node into this hash please let me know, I'd really appreciate it!

This issue is very pressing on my side, so any hints/thoughts/observations are welcome!

**Comment by wsfulton** [comment]
Seems reasonable. Try it out. The way to check the change is okay is by running 'make partialcheck-python-testsuite' after a clean and compare the generated code before and after the change. I wouldn't expect any changes. Similarly for a couple of other languages. Also try more complex but similar examples and to test-suite.

**Comment by fschlimb** [comment]
Seems I made it.

The using directive is properly parsed and looked up. Examples like the above seem to always work. Even %rename is correctly inherited.

However, if the using class does not overwrite the get method the using directive has no effect in some cases (with overloading). I could not yet reproduce this in a small case, So I probably need to do debugging on the real code (which is big). 

Can you give me similar hints on where to look for this kind of issue?

**Comment by wsfulton** [comment]
> The using directive is properly parsed and looked up. Examples like the
above seem to always work. Even %rename is correctly inherited.
>
Do you mean you made a change that sort of nearly works?

> However, if the using class does not overwrite the get method the using
directive has no effect in some cases (with overloading). I could not yet
reproduce this in a small case, So I probably need to do debugging on the
real code (which is big).
>
Not sure I fully follow.

Sometime using doesn't work when overloaded with a declaration as in your
definition of B. Try swap the order of the get declaration with the using
statement. Sometimes one way works and the other doesn't.

**Comment by fschlimb** [comment]
Yes, I made change that nearly works. It seems to do exactly what it supposed to as long as the inherited class (C++-)overloads the method from the parent.

I didn't try swapping, but the code above is treated properly.

What doesn't work is if I remove the overload from B.but keep the using. At least in my real code it doesn't. It would simply not produce any wrapper for things like ```B::get```. It does work find for simple cases, so i could not yet create a small reproducer. 

I am certain that the lookup during parsing woks right even for the real case.

I do not get a warning, it silently refuses to produce the wrapper. So I have no good idea on where to start looking. Any idea?

**Comment by fschlimb** [comment]
I found a small reproducer for the remaining issue. It's about renaming.

The following code does *not* add the ```great```[er] methods to B:
```
%module using_member;

%rename(greater) one::two::three::interface1::A::great(int);
%rename(greater) one::two::three::interface1::A::great(float);

namespace one {
    namespace two {
    namespace three {
        namespace interface1
        {
            class A
            {
            public:
                int great(int);
                int great(float);
            };
        }
        using interface1::A;
    }
    }
    namespace twotwo {
    namespace threetwo {
    class B : public two::three::A
    {
    public:
        using two::three::A::great;
        in jj();
    };
    }}
}
```

However, replacing the 2 ```%rename``` statements with a single
````
%rename(greater) one::two::three::interface1::A::great;
```
surprisingly does work as intended.

Note: without any %renaming I also get the ```great``` methods into B, as intended.

Any thought will be appreciated.

**Comment by wsfulton** [comment]
I would use ```swig -debug-module 1,2``` for debugging if you havn't already. I suspect there is a bug in TypePass::usingDeclaration which is called during stage 2 of the parsing to patch in overloaded methods that the using declaration implies. Look at defining ```DEBUG_OVERLOADED``` in typepass.cxx for further debugging. The other bit of code which you might want to look at is overload.cxx which is used by Python and the other scripting languages during overloading handling, such as using the typecheck typemaps for generating the dispatch function during overload type resolution. Overloaded function handling is quite different in the scripting languages the statically typed languages (Java, C#). If the everything looks okay in Java but not Python, then suspect the code in overload.cxx, otherwise it is probably typepass.cxx.

**Comment by wsfulton** [comment]
For the %rename problem, look at stage 3 of the parsing, in particular ```Allocate::function_is_defined_in_bases```. Also look for patching of the using node into the linked list of overloaded methods being done incorrectly as just mentioned. The linked list of methods may not be correctly done in stage 2. Hence you may see different behaviour changing the order of the using and real method declarations with the same name.

**Comment by wsfulton** [comment]
Regarding https://github.com/swig/swig/issues/655#issuecomment-211439933, please see 79a1bbee8b36bf05e42a5c7aaf80ee005101aaad, which introduces a new warning which should explain. Now you will see:
```
using_member.i:51: Warning 526: Using declaration one::two::three::interface1::AA::great, with name 'great', is not actually using
using_member.i:39: Warning 526: the method from one::two::three::interface1::AA::great(int), with name 'greater', as the names are different.
using_member.i:51: Warning 526: Using declaration one::two::three::interface1::AA::great, with name 'great', is not actually using
using_member.i:40: Warning 526: the method from one::two::three::interface1::AA::great(float), with name 'greater', as the names are different.
```
Also #1840 is closely related with further references/explanations.
