### ISSUE TITLE
Non-template base class treated incorrectly if in different namespace and has same name as derived template class

### ISSUE THREAD

**Issue by fschlimb** [swig/swig#656]
This issue involves templates, namespaces and inheritance. The issue is about inheriting from a base-class with the same name but in in a different namespace. Additionally, the derived class is a template class while the parent class is not. 

I could boil it down to the following very simple reproducer (using 2 modules to get around the naming issue with flattened namespaces):

File ta.i:

```
%module ta

namespace NA
{
    struct Parameter {};
}
// eof ta.i
```

File tt.i:

```
%module tt
%import(module="ta") "ta.i"
namespace NB
{
    template <typename T>
        struct Parameter : public NA::Parameter {};
    %template(Pi) Parameter<int>;
}
// eof tt.i
```

SWIG complains about 

```
tt.i:1: Warning 401: Nothing known about base class 'NA::Parameter< int >'. Ignored.
tt.i:1: Warning 401: Maybe you forgot to instantiate 'NA::Parameter< int >' using %template.
```

The resulting Python wrapper defines “Parameter” in tt.py but it doesn’t inherit from ta.Parameter, which it should do.

Note1: SWIG incorrectly thinks NA::Parameter is a template, but in fact it is not!
Note2: Strangely SWIG reports the error in line 1.

Observation1: Renaming NA::Parameter (to “Para”, say) makes SWIG happy and the resulting code is correct.
Observation2: If NB::Parameter is not a template, all works fine, too.
Observation3: deriving from “::NA::Parameter” issues an even stranger message: 
`tt.i:1: Warning 401: Nothing known about base class ''. Ignored.”`

I'd be willing to invest some time in fixing it myself but would need some hints as I am not familiar with the SWIG code.

Any idea and/or help?

**Comment by wsfulton** [comment]
I verified that this is fixed by fa00622614d35716b429b12aa9dc1bde8e4b586d, see #1484.
