### ISSUE TITLE
single quote in #error directive causes parsing problem

### ISSUE THREAD

**Issue by jmp321** [swig/swig#657]
swig fails to process the following input:

```
#if 0
#error swig can't parse this!
#endif
```

Fails with `Error: Missing #endif for conditional starting on line 1`
Either we have to remove the single quote character, or surround the entire error message with double quotes.  But compilers seem to be less strict about this.   MSVC automatically treats the entire line as a single token and does not care what strange characters you want to include, or if you surround the whole message with double quotes or not.   gcc also tolerates it, but reports a warning about the unmatched single quote.

**Comment by ojwb** [comment]
Still reproducible with git master.  Given GCC issues a warning about this, it seems pretty low priority but it's probably not a complicated fix either.
