### ISSUE TITLE
syntax error if default argument from member function

### ISSUE THREAD

**Issue by jmp321** [swig/swig#660]
I would like to wrap a function that has a default argument initialized by calling a member function of some object.  e.g.:

```
void myfunc(int val=obj.get());
```

Swig does not like the dot character and fails during parsing: `Error: Syntax error in input(1).`

Workaround for now is to replace it with a modified interface with a dummy value for the default arg that does not have a dot.

```
void myfunc(int val=obj_get());
```

and if using the compactdefaultargs feature, then obj_get() is no longer just a dummy value.  It needs to actually be defined:

```
%{
int obj_get() {return obj.get();}
%}

%feature("compactdefaultargs");

void myfunc(int val=obj_get());
```

**Comment by ojwb** [comment]
Previously reported as https://sourceforge.net/p/swig/bugs/1081/ which contains this useful info:

> Response from William:
>
> This seems to be a general parsing bug. Non numeric expressions containing . or -> are not parsable. Please log as a bug. Workaround is to simplify the expression, eg:
>
> ```
> int GetTestClassSomeFunc() {
> return GetTestClass().someFunc();
> }
> void useSomeFunc( int i=GetTestClassSomeFunc() );
> ```
>
> or persuade someone or yourself to fix the bug. The fix to this is going to be somewhere around exprcompound in parser.y. Please add this info to the bug report.

**Comment by ojwb** [comment]
Looks like the grammar is easy to modify for a change - this compiles with no extra conflicts and the example here processes:

```
--- a/Source/CParse/parser.y
+++ b/Source/CParse/parser.y
@@ -6550,6 +6550,12 @@ exprsimple     : exprnum {
                | exprmem {
                    $$ = $1;
                }
+              | exprmem LPAREN RPAREN {
+                   $$ = $1;  // FIXME
+              }
+              | exprmem LPAREN valexpr RPAREN {
+                   $$ = $1;  // FIXME
+              }
                | string {
                    $$.val = $1;
                     $$.type = T_STRING;
```

(`exprmem` already handles `obj.get` and `obj->get` and more complex combinations for us.)

The values assigned to `$$` need sorting out though.
