### ISSUE TITLE
Segmentation fault for Nested Struct with rename

### ISSUE THREAD

**Issue by krblock** [swig/swig#662]
```
$ cat t.swg
%module A 

%rename($ignore) B::C;

namespace B {
    class C {
    public:
        struct D {
        };
    };

    class E {
    public:
        typedef C::D D;
    };

    struct F
    {
        const E::D func();
    };
}
```

Swig 2.0.12 just ignored the nested struct, but 3.0.8 gets segfault.
```
$ ~/work/swig/swig-2.0.12/bin/swig -c++ -java t.swg
t.swg:8: Warning 325: Nested struct not currently supported (D ignored)

$ ~/work/swig/swig-3.0.8/bin/swig -c++ -java t.swg
Segmentation fault: 11
```

**Comment by vadz** [comment]
I can reproduce this, looks like this ought to be simple to fix, checking...

**Comment by vadz** [comment]
Hmm, sorry, no, not as simple as this. Fixing the crash is, of course, simple, but the generated code is not correct as it still references `D` in Java, but it doesn't exist. I'm not sure what is the right thing to do here, should we just ignore `func` too in this case? I wonder what 2.x did with it?

**Comment by krblock** [comment]
Here is what 2.0.12 generated:

$ cat AJNI.java 
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class AJNI {
  public final static native long new_E();
  public final static native void delete_E(long jarg1);
  public final static native long F_func(long jarg1, F jarg1_);
  public final static native long new_F();
  public final static native void delete_F(long jarg1);
}


$ cat F.java 
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class F {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected F(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(F obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AJNI.delete_F(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_B__C__D func() {
    return new SWIGTYPE_p_B__C__D(AJNI.F_func(swigCPtr, this), true);
  }

  public F() {
    this(AJNI.new_F(), true);
  }

}

**Comment by vadz** [comment]
OK, so it just exported `D` as opaque type instead of ignoring `func()` as I thought. I am not sure if this really makes that much sense, but why not, we probably could do this by using the descriptor instead of the name in this case.

P.S. Please use triple backquotes around the code you paste to prevent it from being mangled (I've edited your comments to insert them), i.e. do

    ```
    like this
    ```

(but without the indentation).

**Comment by wsfulton** [comment]
Yes, with ```B::C``` being ignored, it should result in a type wrapper class / opaque type, so the fix looks okay to me. @wkalinin, may want to have a look too.

**Comment by wkalinin** [comment]
If B::C is ignored then everything nested in it should be ignored as well, so, in this case should not getProxyName() just check if the symbol is ignored and return null, so that replacement "SWIGTYPE%s" name would be generated in the caller? As I see it, it should check the whole parent chain, including namespaces. Is missing "sym:name" a correct indication that a symbol is ignored?

**Comment by wkalinin** [comment]
Also, the same bug is present in C# module.

**Comment by wkalinin** [comment]
Taking silence for a sign of agreement I propose the following improvement of Vadim's fix: https://github.com/swig/swig/pull/681 (I didn't find his change in his branch to PR it there instead)

**Comment by wsfulton** [comment]
Yes, agreed it makes sense if all the nested classes are also ignored.
