### ISSUE TITLE
need help wrapping c++ lib

### ISSUE THREAD

**Issue by michelson** [swig/swig#667]
Hello!, thanks for this library, I've been trying to wrap a library to use in a go package, I'm still really new in this kind of thing, and I'm a newbie in C++ programming, so I'm writting here looking for some hint in how to do it.

the library itself is cimgui https://github.com/Extrawurst/cimgui

and these are the steps I taking to build the wrapping files

first git clone cimgui repo then `git submodule init ; git submodule update`
then I've created the Swig file with this content:

```
 /* example.i */
%module cimgui
%{
#include "cimgui.h"
%}

/* Parse the header file to generate wrappers */
%include "cimgui.h"
```

and the command to build the wrap class is:
`SWIG -go -gccgo  -intgosize 64 cimgui.swig`

finnaly when I try to compile the imgui_wrap.c, or when try with `go build` fails with too many errors
the commands I've tried so far to do this are:

`gcc -c cimgui.cpp cimgui_wrap.c`

and also `go build`

```
...
In file included from ./cimgui_wrap.c:272:
./cimgui.h:26:12: error: unknown type name 'ImGuiIO'
./cimgui.h:27:12: error: unknown type name 'ImGuiStyle'
./cimgui.h:28:12: error: unknown type name 'ImDrawData'
./cimgui.h:33:47: error: unknown type name 'ImGuiStyle'
...
```

Why these types are unknown ? how can I tell the program to recognize those types ?

thanks

**Comment by myd7349** [comment]
It seems that all these types are declared in `imgui.h`. So you need to modify the header section like this:
```c
%{
#include "../imgui/imgui.h"
#include "cimgui.h"
%}
```

However, since `imgui.i` is a C++ header file, you have to add an extra `-c++` option in order to make it work out:
```
SWIG -c++ -go -gccgo -intgosize 64 cimgui.swig
```

At last:
```
gcc -c cimgui.cpp cimgui_wrap.cxx
```

Give it a try!

**Comment by michelson** [comment]
Hi @myd7349 , thanks for your reply!

I've tried as you said, and the compilation of the wrap.cxx works fine! . Also I've moved the entire folder to my gopath $GOPATH/src/cimgui in order to build the go pkg as described in swig documentation, I think I almost there, but now I getting some errors when try to build the go package.

inside the go package directory `~/go/src/cimgui` I've run:

`$ go build cimgui.go`
and then 💥 
```
# command-line-arguments
./cimgui.go:39: missing function body for "SwigCgocall"
./cimgui.go:40: missing function body for "SwigCgocallDone"
./cimgui.go:41: missing function body for "SwigCgocallBack"
./cimgui.go:42: missing function body for "SwigCgocallBackDone"
./cimgui.go:45: missing function body for "_swig_wrap_Swig_free"
```

I'm using golang 1.5.2 version btw, as far as I know Swig supports golang 1.5 right ?

**Comment by ojwb** [comment]
> I'm using golang 1.5.2 version btw, as far as I know Swig supports golang 1.5 right ?

The manual implies it does.

Not a SWIG bug (and resolved anyway), so closing.

**Comment by michelson** [comment]
Hi @ojwb 
I'm sorry if I implied that it was a SWIG bug , it was not my intention.
I was only looking for some help with the wrapping procedure, as I stated on the title of this issue.
I'm a C++ noob, really. So this is a new subject for me.

I will send my questions on the mailing list

best

**Comment by njligames** [comment]
Kind of sucks that this is close with out a resolve, just a dead end.
