### ISSUE TITLE
Warning about unknown base class although derived class is ignored

### ISSUE THREAD

**Issue by cyr0n** [swig/swig#669]
%module swigtest
 
    %ignore ActualClass;

    enum State {
	INVALID = 0,
	VALID = 1
    };

    template<typename T>
    class TemplateClass {};

    class ActualClass : public TemplateClass<int> {};

I'm wrapping the above file to java.

Expected result: Only the `State` enum gets wrapped.
Actual result: Only the `State` enum gets wrapped, but the following warning appears:

    d:\swigtest>"D:\swigwin-3.0.8\swig.exe" -c++ -java swig_definition.i
    swig_definition.i(13) : Warning 401: Nothing known about base class 'TemplateClass< int >'. Ignored.
    swig_definition.i(13) : Warning 401: Maybe you forgot to instantiate 'TemplateClass< int >' using %template.

No files are generated for `TemplateClass` or `ActualClass` (as expected), but I would expect no warnings either.

**Comment by vadz** [comment]
Can this be worked around by ignoring `TemplateClass` too?

**Comment by cyr0n** [comment]
No, same warning.

**Comment by wsfulton** [comment]
I'll see if I can fix this for the next release, but in the meantime you can instantiate the template and then %ignore will work on it and suppress the warnings:
```swig
...
template<typename T>
class TemplateClass {};

%ignore TemplateClass<int>;
%template(TemplateClassInt) TemplateClass<int>;
...
```
