### ISSUE TITLE
Patch #201 breaks python module for functions with default args

### ISSUE THREAD

**Issue by thejta** [swig/swig#673]
In swig 3.0.3 or greater, #201 causes this error at import time of the generate python module:
```
    def ecmdLooperInit(io_target, i_looptype, io_state, i_mode=ECMD_DYNAMIC_LOOP):
NameError: name 'ECMD_DYNAMIC_LOOP' is not defined
```

That's because the ECMD_DYNAMIC_LOOP constant isn't defined until further down in the python module.
```
_ecmd.ECMD_DYNAMIC_LOOP_swigconstant(_ecmd)
ECMD_DYNAMIC_LOOP = _ecmd.ECMD_DYNAMIC_LOOP
```
If a manually move that definition before the function references it, everything works.  It looks like enums need to be generated in the module before function definitions.

I can workaround this problem for now by enabling the compactdefaultargs feature.

**Comment by wsfulton** [comment]
Posting generated code isn't particularly helpful without the input code. Please supply the c++ code and options to SWIG that causes this.

**Comment by thejta** [comment]
I haven't had a chance to create a reduced set test case.  Here is the function and typedef C++ code:
```
typedef enum {
  ECMD_LOOP_TYPE_UNKNOWN, 
  ECMD_SELECTED_TARGETS_LOOP, 
  ECMD_SELECTED_TARGETS_LOOP_DEFALL, 
  ECMD_SELECTED_TARGETS_LOOP_VD,
  ECMD_SELECTED_TARGETS_LOOP_VD_DEFALL, 
  ECMD_ALL_TARGETS_LOOP
} ecmdLoopType_t;

uint32_t ecmdLooperInit (ecmdChipTarget & io_target, ecmdLoopType_t i_looptype, ecmdLooperData& io_state, ecmdLoopMode_t i_mode = ECMD_DYNAMIC_LOOP);
```
The swig options are: /usr/bin/swig  -c++ -python

**Comment by wsfulton** [comment]
This minimal testcase works fine with swig-3.0.8:
```swig
%inline %{
struct ecmdChipTarget {};
struct ecmdLooperData {};

typedef enum {
  ECMD_LOOP_TYPE_UNKNOWN, 
} ecmdLoopType_t;

typedef enum {
  ECMD_DYNAMIC_LOOP
} ecmdLoopMode_t;

uint32_t ecmdLooperInit (ecmdChipTarget & io_target, ecmdLoopType_t i_looptype, ecmdLooperData& io_state, ecmdLoopMode_t i_mode = ECMD_DYNAMIC_LOOP) { return 0; }
%}
```
The ```ECMD_DYNAMIC_LOOP = _ecmd.ECMD_DYNAMIC_LOOP``` code is generated before it is used in the .py file. If the parsing order is incorrect then you get the problem you describe. I suspect you are not parsing the real headers in the same order that is required by a C++ compiler (and SWIG). The problem can be replicated with:
```swig
%inline %{
struct ecmdChipTarget {};
struct ecmdLooperData {};

typedef enum {
  ECMD_LOOP_TYPE_UNKNOWN, 
} ecmdLoopType_t;
%}

%{
// This is what the C compiler parses
typedef enum {
  ECMD_DYNAMIC_LOOP
} ecmdLoopMode_t;

uint32_t ecmdLooperInit (ecmdChipTarget & io_target, ecmdLoopType_t i_looptype, ecmdLooperData& io_state, ecmdLoopMode_t i_mode = ECMD_DYNAMIC_LOOP) { return 0; }
%}

// This is what SWIG parses
uint32_t ecmdLooperInit (ecmdChipTarget & io_target, ecmdLoopType_t i_looptype, ecmdLooperData& io_state, ecmdLoopMode_t i_mode = ECMD_DYNAMIC_LOOP) { return 0; }

typedef enum {
  ECMD_DYNAMIC_LOOP // oops - defined after it is used
} ecmdLoopMode_t;
```
You should correct the order of parsing if this is what you are doing. You can also use the ```python:cdefaultargs``` feature to revert to the old behaviour, see http://swig.org/Doc3.0/Python.html#Python_default_args

**Comment by thejta** [comment]
The order of the parsing in the include statements was the cause of the problem, but was never exposed in our setup until the compactdefaultargs behavior change.  Sorry for the bug FUD and thanks a lot for the help.
