### ISSUE TITLE
Default -intgosize to sizeof(void*)

### ISSUE THREAD

**Issue by dontpanic92** [swig/swig#683]
If we remove the `intgosize` parameter test in `go.cxx`, cgo will complain about not finding `ptrdiff_t` and `size_t`:

```
error: unknown type name 'ptrdiff_t'
 typedef ptrdiff_t intgo;
error: unknown type name 'size_t'
 typedef size_t uintgo;
```

So `stddef.h` should be added into cgo_comment section when it is decided to support default intgosize.

**Comment by ojwb** [comment]
I see the docs for `-intgosize` say:

>This option is currently required during the transition from Go 1.0 to Go 1.1, as the size of `int` on
64-bit x86 systems changes between those releases (from 32 bits to 64 bits).  In the future the option may become optional, and SWIG will assume that the size of `int` is the size of a C pointer.

Since Go is ancient history (at least in Go terms) it seems we're now at the point where that should be done (or decided to not be desirable after all) so I'm going to make this ticket about that as having a ticket for something that needs to be done if/when we do something else doesn't really seem justified in itself.

**Comment by ojwb** [comment]
@ianlancetaylor Does defaulting `-intgosize` as suggested above seem like a sensible change for SWIG 4.1.0?

**Comment by ianlancetaylor** [comment]
The main thing I would be concerned about is cross-compiling.  Can we assume that SWIG is compiled on the same system as we are generating code for?  If so, `sizeof(void*)` is fine.  If not, it's not.

**Comment by ojwb** [comment]
> Can we assume that SWIG is compiled on the same system as we are generating code for?

No, and indeed generally we aim to have SWIG generate code that will work on any system (so the current `-intgosize` is really an undesirable wart).

Perhaps I've misunderstood, but I'd interpreted the suggestion to "remove the `intgosize` parameter test" above as being that SWIG/Go would not need `-intgosize` but would instead generate code which was portable in the way SWIG generally does.

If the suggestion is just to remove `-intgosize` but hardwire the setting based on `sizeof(void*)` for the architecture SWIG is run on, that's definitely worse than the current situation.  I tend to think even providing a default based on `sizeof(void*)` would be less helpful overall - it would avoid needing `-intgosize` in simple cases, but create a trip hazard for anyone intending to ship pre-generated files for SWIG-generated Go bindings as it would work fine in local testing, but then not work for those using architectures with a different word size.  Having to specify `-intgosize` at least makes the issue hard to miss.

I've just had a look at what `-intgosize` does, and it essentially just seems to define `SWIGGO_INTGO_SIZE` to 32 or 64 (or in a code path that can't currently be taken, to 0).  It seems the `0` path has handling and causes `ptrdiff_t` to be used for `intgo` and `size_t` for `uintgo`, so it does look to me like making `-intgosize` optional should work as I'd assumed.  I'll create a PR to test this.

**Comment by ojwb** [comment]
I note the docs say "SWIG will assume that the size of <tt>int</tt> is the size of a C pointer" but I think that's not quite correct: `sizeof(size_t)` and `sizeof(ptrdiff_t)` could be less than `sizeof(void*)` on a segmented memory system couldn't they?  It's been a while but I think that was the case with some DOS memory models.  I guess Go doesn't target such systems?   (I don't know of any current such platforms, but I'm not very familiar with e.g. the embedded world.)

**Comment by ianlancetaylor** [comment]
Your pull request looks good to me.  Thanks.
