### ISSUE TITLE
typemap(out) and typemap(argout) Conflict

### ISSUE THREAD

**Issue by jroose** [swig/swig#684]
SWIG can't seem to use both argout and out on functions.  If both out and argout are defined, it appears that SWIG prefers the argout and overrides the return value referenced by out.  

This is a big problem for me because I am trying to wrap the OpenCL BLAS bindings with a SWIG generated Python module.  There are several allocation functions that return a cl_mem (allocated memory on a GPU device) while simultaneously setting an error code using an argout style cl_int\* argument.  

Suggested Possible Solutions:
    1. typemap(argout) could be extended to use typemap(argout,numoutputs=0) in which case typemap(argout) would not override typemap(out)
    2. If there was an %exception_argout decorator, it would solve this special case
    3. If multiple outputs were handled in a coherent manner, such as building and returning a tuple in Python, a workaround could be implemented.    

Here's an example of a clblas function that exhibits this problem:
cl_mem clblasCreateMatrix(cl_context context, clblasOrder order, size_t rows, size_t columns, size_t elemsize, size_t padding, size_t *ld, size_t *fullsize, cl_int *err);

In this case, I need my Python wrapper function to return cl_mem, but it also needs to check the result of the cl_int\* pointed to by the err argument, and throw a SWIG_exception_fail if it's nonzero.  

Given the current set of documented SWIG features, a workaround does not seem possible here without drastic measures like writing a wrapper function for each of these functions, which SWIG could generate yet another wrapper for.

**Comment by ojwb** [comment]
The return value shouldn't get overridden - what's meant to happen in this situation is that the wrapped function returns multiple values, and testing that's exactly what happens:

```
$ cat test.i
%module test

%inline %{

int func(int *OUTPUT) {
   *OUTPUT = 2;
   return 1;
}

%}
$ swig -python test.i
$ gcc `python3-config --includes` -shared -fPIC test_wrap.c -o _test.so
$ python3 -c 'import test; print(test.func())'
[1, 2]
```

This doesn't seem to be reproducible, so closing.  If it's still not working for you, please supply a minimal self-contained example which demonstrates your problem.
