### ISSUE TITLE
Smart pointer to %ignored class doesn't expose inherited methods in SWIG 3.0.9

### ISSUE THREAD

**Issue by lballabio** [swig/swig#690]
Here is a short example:

    %module Test
    
    class Foo {
      public:
        void foo();
    };
    
    %ignore Bar;
    class Bar : public Foo {
      public:
        void bar();
    };
    
    template <class T>
    class Ptr {
      public:
        T* operator->();
    };
    
    %template(BarPtr) Ptr<Bar>;

When processed by SWIG 3.0.8, the interface above generates Python wrappers in which the `BarPtr` class defines both the `bar` and `foo` methods.  When processed by SWIG 3.0.9, the `BarPtr` class only defines the `bar` method and discards the inherited one.

**Comment by wsfulton** [comment]
This is due to #669. I'll put together a better fix.

**Comment by lballabio** [comment]
Thanks!
