### ISSUE TITLE
Swig C++ -> R : Missing last comma in member lists for classes with method overloads

### ISSUE THREAD

**Issue by bartoli** [swig/swig#697]
We noticed last december that our output R files were missing the last comma of our public member  list. We assumed we would simply work around it by reducing the quantity of public members variables and adding more accessor methods instead.
But now we get the same behaviour for the generated accessor list 

Ex : 
`vaccessors = c('setmember1', 'setMember1', 'hasMember1', 'removeMember1', 'setMember2', 'setMember3', 'getMember2''getMember3');`

Possible hint :
Notice how there is twice setMember1 (the source c++ class has 2 overloads of the method). Maybe at some point the swig R generator counts the distinct member names, to find out how many commas are needed?

To confirm it i did a few tests 
- Add more members --> still only one comma is missing
- Add more members and remove the overloaded methods --> no comma missing, even though there are more members than originally
- Add a third overload to the method --> a second comma is missing

This is with swig 3.0.8

**Comment by ojwb** [comment]
> Maybe at some point the swig R generator counts the distinct member names, to find out how many commas are needed?

Yes, looks like that's exactly the issue.  Do you have a small, self-contained testcase for this?

**Comment by bartoli** [comment]
[swig-697-testcase.zip](https://github.com/swig/swig/files/526448/swig-697-testcase.zip)

See attached folder. Just run make from a console with swig in the PATH.

Please note that i didn't manage to reproduce it at first, the output R file had no vaccessors list. Then i found this ( [https://sourceforge.net/p/swig/mailman/message/35071142/]) and indeed i have to have overloaded methods that end with get for them to be put in vaccessors

**Comment by wsfulton** [comment]
@joequant would you mind taking another look at this issue which I also brought up earlier in May 2016?

**Comment by joequant** [comment]
Oh sure.  I'll fix it over the weekend.

**Comment by ojwb** [comment]
@joequant If you have some spare SWIG-time this weekend after dealing with this issue, there are 3 other issues and 2 PRs which are R-specific which it would be great if you could take a look at:

https://github.com/swig/swig/labels/R

**Comment by joequant** [comment]
Yes.  I'll fix them this week.

**Comment by wsfulton** [comment]
Hi @joequant, will you get a chance to do this?

**Comment by joequant** [comment]
Will try to get around in the next day or two.  Been swamped with other
work.

**Comment by wsfulton** [comment]
Thanks @joequant. Could you add your recent changes into the CHANGES.current file please. Thanks.

**Comment by bartoli** [comment]
Thanks for the fix. The commit fixes the comma error.
What about the issue of the mailing list that vacessors contains only the methods that end with get?
What triggers it seems to be `ptr = &ptr[Len(dup) - 3];` in the same area as the commit. Is there a reason for explicitly looking for get at the end of the method name, and not comparing the first characters of the method name instead when looking for accessor methods?

**Comment by joequant** [comment]
No good reason.  If you can open up a PR and then put in a test case, I'll
fix.
