### ISSUE TITLE
[Python] PyFloat_FromDouble is not defined

### ISSUE THREAD

**Issue by pizzafroide** [swig/swig#706]
Here is a really simple SWIG example generating a file that won't compile because `PyFloat_FromDouble` is not defined.
```cpp
%inline %{
    static const double foo = 0.0;
%}
```

**Comment by m7thon** [comment]
I just tried this with current SWIG and python 2.4, 2.7 and 3.4 and it works fine.

Can you please state the SWIG versions and Python versions you are using, and the exact commands you use to swig and compile?

**Comment by pizzafroide** [comment]
I did, my bad... Thanks!
