### ISSUE TITLE
go.cxx: Use of variable after 'free'

### ISSUE THREAD

**Issue by avalluri** [swig/swig#710]
In function oneClassDirectorMethod() of go.cxx, The 'Wrapper *dummy' has used after it's been freed(DelWrapper).

```
Wrapper *dummy = NewWrapper();
emit_attach_parmmaps(parms, dummy);
DelWrapper(dummy);

Swig_typemap_attach_parms("godirectorin", parms, w);
Swig_typemap_attach_parms("goin", parms, dummy);
Swig_typemap_attach_parms("goargout", parms, dummy);
```

**Comment by wsfulton** [comment]
@avalluri could you put a fix for this as well as all your other recent issues into a pull request?

**Comment by avalluri** [comment]
@wsfulton , Sure I work on that.
