### ISSUE TITLE
Python index operators with -builtin not possible

### ISSUE THREAD

**Issue by SimplyKnownAsG** [swig/swig#722]
I've spent a lot of time trying to figure out how to get the C++ `operator[]` to be correctly wrapped for Python with `-builtin`. My definition of correctly is that on the python side, I should get the equivalent of `__getitem__` and `__setitem__`. I think I understand why this is difficult, but I'd like to make sure there isn't some way this could be done.

I believe some reasons that `operator[]` is not / cannot be defined in `pyopers.swg` are:
- In C++ the `operator[]` method should return a reference so that it can also support assignment operations.
- In Python this could take [**four** difference slots](https://docs.python.org/2/c-api/typeobj.html):

```
%feature("python:slot", "sq_item", functype="ssizeargfunc") *::operator[];
%feature("python:slot", "sq_ass_item", functype="ssizeargfunc") *::operator[];
%feature("python:slot", "mp_subscript", functype="binaryfunc") *::operator[];
%feature("python:slot", "mp_ass_subscript", functype="objobjargproc") *::operator[];
```

I have a simple array implementation that uses `operator[]`, `-builtin` with

```
%rename("__getitem__") *::operator[];
%feature("python:slot", "sq_item", functype="ssizeargfunc") *::operator[];
```

defined.

When the return type is a reference (i.e. `double&`) Python says the type is `<Swig Object of type 'double *' at 0x0000000003E2DA08>`. When the return type is a value (i.e. `double`), Python gives the value. Both of these results make sense, but it is a bit of a pain that I cannot seem to get this to work.

Are there swig `%feature`, `%rename` operations that can be used to get `operator[]` to work as expected? I haven't fully looked at what is done for `std::vector` and `std::map`s yet, but I imagine the answer is out there!

**Comment by mromberg** [comment]
Supporting operator[] in 100% C++ is not even a straight forward exercise for the reason you mentioned above.  Often a proxy class is needed just to deal with this in C++

https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Temporary_Proxy

  All this messy code would be involved before swig would even take a peek at the C++.  Then swig would have to try to create another layer of proxies (meta proxy?) for the scripting language to use.

  If it were me, I'd try really hard (using things like %extend if needed) to wrap the C++ in a way to not expose this type of interface to the scripting language.

**Comment by m7thon** [comment]
Here is what I used once to get exactly this working for a simple C++ `Sequence` class using `-builtin`:

```c++
class Sequence {
...
};
%extend Sequence { %COLLECTION(ItemType) };
```

where my `%COLLECTION` macro is defined in a file `collection.i` that needs to be `%included`. In your case, I guess `ItemType` would be `double`.

```c++
%include "exception.i"

%{
#include <cassert>
#include <stdexcept>
%}

%define %RANGE_ERROR
{ try { $action }
        catch(std::out_of_range) { SWIG_exception(SWIG_IndexError, "Index out of bounds"); }
}
%enddef // %RANGE_ERROR                                                                                                                                         

%define %LENGTH
%feature("python:slot", "sq_length", functype="lenfunc") __len__;
long __len__() const { return $self->size(); }
%enddef // LENGTH                                                                                                                                               

%define %GETITEM(ITEM_TYPE)
%feature("python:slot", "mp_subscript", functype="binaryfunc") __getitem__;
%exception __getitem__ %RANGE_ERROR;
ITEM_TYPE __getitem__(long i) {
        if (i < 0) i = i + $self->size();
        if ((i < 0) or (i >= $self->size()))
                throw std::out_of_range("Index out of bounds");
        return (*($self))[i];
}
%enddef // %GETITEM(ITEM_TYPE)                                                                                                                                  

%define %SETITEM(ITEM_TYPE)
%feature("python:slot", "mp_ass_subscript", functype="objobjargproc") __setitem__;
%exception __setitem__ %RANGE_ERROR;
void __setitem__(long i, const ITEM_TYPE& val) {
        if (i < 0) i = i + $self->size();
        if ((i < 0) or (i >= $self->size()))
                throw std::out_of_range("Index out of bounds");
        (*($self))[i] = val;
}
%enddef // %SETITEM(ITEM_TYPE)

%define %COLLECTION(ITEM_TYPE)
%LENGTH
%GETITEM(ITEM_TYPE)
%SETITEM(ITEM_TYPE)
%enddef // %COLLECTION(ITEM_TYPE)                                                                                                                               

%define %COLLECTION_RO(ITEM_TYPE)
%LENGTH
%GETITEM(ITEM_TYPE)
%enddef // %COLLECTION(ITEM_TYPE)                                                                                                                               
```

**Comment by SimplyKnownAsG** [comment]
@mromberg, thanks for the reply.

@m7thon, does it matter whether you use `mp_subscript` vs. `sq_item`? I thought I had unsuccessfully tried `mp_subscript` but maybe it was just a part of my whack-a-mole solution finding process. If it doesn't matter which is used then could your solution be made more general to update `pyopers.swg`?

If no update to `pyopers.swg` is sensible. I had difficulty following the reasoning available on [stack](http://stackoverflow.com/questions/16466351/how-to-use-swig-to-wrap-a-c-operator-in-a-template-class-inside-a-namespace) [exchange](http://stackoverflow.com/questions/22736389/how-to-extend-c-class-in-python-with-operator-using-swig), which generally results in [answers](http://stackoverflow.com/questions/34482723/how-to-create-a-target-language-agnostic-iterable-swig-c-object-without-using) that talk about pure Python implementations rather the SWiG/C++ implementations. Could SWiG have a more meaningful warning message stating that `operator[]` cannot be easily overloaded and point to some of the documentation?

**Comment by m7thon** [comment]
> does it matter whether you use mp_subscript vs. sq_item?

AFAIK, no.

> could your solution be made more general to update pyopers.swg?

Maybe. Currently, `*::operator[]` is simply ignored. I never thought about why this is not wrapped automatically. It is a bit more tricky than the other operators, since you do need to handle the getting and setting separately, and also need to deal with the case that `*::operator[]` may not be defined at all.

> ... reasoning available on stack exchange...

As far as I can see, they only deal with proxy classes, not using `-builtin`. Apart from that, they do exactly the same thing: extend the class by a suitable `__getitem__` method. For builtin, you also need to assign this to the appropriate slot.

> ...warning message stating that `operator[]` cannot be easily overloaded...

I think you mean "easily" -> "automatically" and "overloaded" -> "wrapped"

> ...documentation

on how to deal with `*::operator[]` specifically. Yes, that'd be nice.
