### ISSUE TITLE
[Python] generated wrapper produces "undeclared identifier" error

### ISSUE THREAD

**Issue by gregorleban** [swig/swig#725]
I'm trying to use SWIG to generate a python library from my c++ code. The generated wrap file contains c++ code that does not compile. The error I get on several places is "undeclared identifier error". Below is a small c++ sample and generated code in the wrap file:

```
class TFOut: public TSOut{
...
static PSOut New(const TStr& FNm, const bool& Append=false) {
  return PSOut(new TFOut(FNm, Append));
}
...
}
```

The generated code below contains a use of `res2` variable that is not declared anywhere. This type of missing errors occur tens of times in my code and I don't know what could be the reason for it. Any help would be appreciated.

```
SWIGINTERN PyObject *_wrap_TFOut_New__SWIG_0(PyObject *SWIGUNUSEDPARM(self), int nobjs, PyObject **swig_obj) {
  PyObject *resultobj = 0;
  TStr *arg1 = 0 ;
  bool *arg2 = 0 ;
  void *argp1 = 0 ;
  int res1 = 0 ;
  bool temp2 ;
  bool val2 ;
  int ecode2 = 0 ;
  PSOut result;

  if ((nobjs < 2) || (nobjs > 2)) SWIG_fail;
  res1 = SWIG_ConvertPtr(swig_obj[0], &argp1, SWIGTYPE_p_TStr,  0  | 0);
  if (!SWIG_IsOK(res1)) {
    SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "TFOut_New" "', argument " "1"" of type '" "TStr const &""'"); 
  }
  if (!argp1) {
    SWIG_exception_fail(SWIG_ValueError, "invalid null reference " "in method '" "TFOut_New" "', argument " "1"" of type '" "TStr const &""'"); 
  }
  arg1 = reinterpret_cast< TStr * >(argp1);
  ecode2 = SWIG_AsVal_bool(swig_obj[1], &val2);
  if (!SWIG_IsOK(ecode2)) {
    SWIG_exception_fail(SWIG_ArgError(ecode2), "in method '" "TFOut_New" "', argument " "2"" of type '" "bool""'");
  } 
  temp2 = static_cast< bool >(val2);
  arg2 = &temp2;
  {
    try {
      result = TFOut::New((TStr const &)*arg1,(bool const &)*arg2);
    }
    catch (PExcept E)
    {
      printf(E->GetMsgStr().CStr());
      printf("\n");
    }
    catch (...){
      printf("Unknown exception\n");
    }
  }
  resultobj = SWIG_NewPointerObj((new PSOut(static_cast< const PSOut& >(result))), SWIGTYPE_p_TPtT_TSOut_t, SWIG_POINTER_OWN |  0 );
  if (SWIG_IsTmpObj(res2)) {
    resultobj = SWIG_Python_AppendOutput(resultobj, SWIG_From_bool((*arg2)));
  } else {
    int new_flags = SWIG_IsNewObj(res2) ? (SWIG_POINTER_OWN |  0 ) :  0 ;
    resultobj = SWIG_Python_AppendOutput(resultobj, SWIG_NewPointerObj((void*)(arg2), SWIGTYPE_p_bool, new_flags));
  }
  return resultobj;
fail:
  return NULL;
}
```

**Comment by gregorleban** [comment]
In case it is relevant, I'm adding also here the commandline used to generate the wrapper file:

    swig -D_CMPWARN -D__stdcall -DSW_SNAPPY -python -c++ -w302,312,317,325,362,383,384,389,401,503,508,509 -O -I../../snap/snap-core -I../../snap/snap-adv -I../../snap/glib-core snap.i

**Comment by mromberg** [comment]
> The error I get on several places is "undeclared identifier error"

I'm guessing the problem lies in your .i file.  Specifically you should look for this:

%{
#include "awesomelib.h"   // This needs to be here for your C++ compiler to see awesomelib

// You should put any other headers here that awesomelib.h may be depend on.  Swig only
// needs to see the declarations of things it is wrapping.  But it is not a real compiler.  It will
// generate code using what it sees even if it has not seen enough to fully understand what
// all the types are.  Check the swig docs for details.
%}

// This is the "include" for swig to see it.  Note that swig parses this header and creates wrapper
// code.  But it is *not* a full compiler and you must use the above include for the real compiler
// to see the header as well.
%include awesomelib.h

**Comment by m7thon** [comment]
The offending code 
```c++
if (SWIG_IsTmpObj(res2)) {
    resultobj = SWIG_Python_AppendOutput(resultobj, SWIG_From_bool((*arg2)));
  } else {
    int new_flags = SWIG_IsNewObj(res2) ? (SWIG_POINTER_OWN |  0 ) :  0 ;
    resultobj = SWIG_Python_AppendOutput(resultobj, SWIG_NewPointerObj((void*)(arg2), SWIGTYPE_p_bool, new_flags));
  }
```

looks like it was generated by some "argout" typemap that was applied to one of the function arguments. Such an "argout" typemap must always go together with a corresponding "in" typemap that defines the variable `res` (the number gets appended automatically). So it seems in your case an "argout" typemap got applied, but the corresponding "in" typemap did not.

**Comment by bjaraujo** [comment]
I get the same issue using StdVectorDouble

 if (SWIG_IsTmpObj(res2)) {


Error	C2065	'res2': undeclared identifier

**Comment by wsfulton** [comment]
The closest I can get to generating the code provided is using:
```swig
%include <typemaps.i>
%apply bool& INOUT { const bool& Append }

%exception TFOut::New
  {
    try {
      $action
    }
    catch (PExcept E)
    {
//      printf(E->GetMsgStr().CStr());
      printf("\n");
    }
    catch (...){
      printf("Unknown exception\n");
    }
  }

%inline %{
struct PExcept {};
class TFOut;
struct PSOut {
  PSOut(TFOut * = 0) {}
};
struct TStr {};
struct TSOut {};
class TFOut: public TSOut{
  TFOut(const TStr& FNm, const bool& Append) {}
public:
static PSOut New(const TStr& FNm, const bool& Append=false) {
  return PSOut(new TFOut(FNm, Append));
}
};
%}
```
It is nearly the same and it compiles fine. I suggest using the `-debug-tmused` option to debug which typemaps are being applied and to use the `-E` option to debug the preprocessed output further.

Closing as user error, please re-open with a cut down test case to replicate the problem.
