### ISSUE TITLE
[Python] %varargs does not work with member functions

### ISSUE THREAD

**Issue by pizzafroide** [swig/swig#726]
First things first, here is a use case:
```c++
%module example

%{
	struct A
	{
		A(int value) : value(value) {}
		int value;
	};

	struct Foo
	{
		double foo(double d) { return d; };
		double foo(double d, A const & a1) { return d + a1.value; };
		double foo(double d, A const & a1, A const & a2) { return d + a1.value + a2.value; };
	};

	double bar(double d) { return d; };
	double bar(double d, A const & a1) { return d + a1.value; };
	double bar(double d, A const & a1, A const & a2) { return d + a1.value + a2.value; };
%}

struct A { A(int); };

struct Foo
{
	%varargs(2, A const & = 0) foo;
	double foo(double d, ...);
};

%varargs(2, A const & = 0) bar;
double bar(double d, ...);
```

`PyObject_Length` returns the maximum number of arguments instead of the number of arguments actually passed to `Foo::foo()` which leads to a `Wrong number or type of arguments for overloaded function 'Foo_foo'.` error message (or to a segmentation fault when using pointers instead of references).

There is a workaround though: using a `%typemap(in)` and a custom `%feature("action")`.

**Comment by pizzafroide** [comment]
Actually, it works fine when `%feature("python:cdefaultargs")` is used.

**Comment by m7thon** [comment]
`%varargs` works perfectly fine. SWIG does not except `0` (an `int`) as an object of type `A`. So you could use:

```c++
struct Foo
{
    %varargs(2, A const & = A(0)) foo;
    double foo(double d, ...);
};

%varargs(2, A const & = A(0)) bar;
double bar(double d, ...);
```

Also, if you are merely setting default values, you can also use the (imo cleaner) syntax, which even works when wrapping C:

```c++
struct Foo
{
    double foo(double d, A const & a1 = A(0), A const & a2 = A(0));
};

double bar(double d, A const & a1 = A(0), A const & a2 = A(0));
```

**Comment by pizzafroide** [comment]
Actually the default value `0` stands for `NULL` (or `nullptr`). I need to use a null pointer default value since, in my "real" code, the `A` class is abstract. The syntax is strange but works fine since, in swig, references are considered as pointers (if you see what I mean). Also, in my code, the `Foo::foo()` function really uses variadic arguments; something like:
```c++
template<typename... A> double foo(double d, A const &... a) 
```
(And I don't want to write 10 overloads of `foo` in my swig code.)

But, as I said earlier using `%feature("python:cdefaultargs")` fixes the bug. 
```c++
struct Foo
{
    %varargs(10, A const & = nullptr) foo;
    %feature("python:cdefaultargs") foo;
    double foo(double d, ...);
};
```
