### ISSUE TITLE
Possible to "ignore/remove" an argument in target language? 

### ISSUE THREAD

**Issue by thisiscam** [swig/swig#729]
So I had a c interface that looks like:

`int* get_array(int input, int *size); //return value is pointer to array, size will be output array's size`

I would like to translate the above into C#, possibly one that looks like

`public static int[] get_array(int input)`

Now, to do this, the c-wrapper and modulePInvoke's signature should not change, but the module's interface should drop the second argument, which I have used a typemap like

```
%typemap(csin) int  *size "ref length" 
%typemap(imtype) int *size "ref int"
%typemap(imtype) int* get_array() "IntPtr"
%typemap(cstype) int* get_array() "int[]"
%typemap(csout) int* get_array {
    int length;
    IntPtr tmp = $imcall;
    int[] ret = new int[length];
    Marshal.Copy(tmp, ret, 0, length);
    return ret;
  }
```

which produces 
```
// module.cs:
public static int[] get_array(int input, SWIGTYPE_p_int size) {
	int length;
    IntPtr tmp = bddPINVOKE.get_array(r, ref length);
     int[] ret = new int[length];
     Marshal.Copy(tmp, ret, 0, length);
     return ret;
  }

// modulePInvoke.cs
[global::System.Runtime.InteropServices.DllImport("...", EntryPoint="...")]
  public static extern IntPtr get_array(int jarg1, ref int jarg2);
```

Ok, almost there, but is there a way for me to drop the "SWIGTYPE_p_int numbers"  in module.cs? Preferably other than writing another overloaded wrapper function?

Note that this feature(if not implemented already), will enable marshaling of return array in C#, which is useful due to lack of JNI.

**Comment by wsfulton** [comment]
This works for me:
```swig
%include <typemaps.i>
%apply int *OUTPUT {int *size}

%typemap(imtype) int* get_array() "global::System.IntPtr"
%typemap(cstype) int* get_array() "int[]"
%typemap(csout) int* get_array {
    global::System.IntPtr tmp = $imcall;
    int length = size;
    int[] ret = new int[length];
    global::System.Runtime.InteropServices.Marshal.Copy(tmp, ret, 0, length);
    return ret;
  }
```

**Comment by thisiscam** [comment]
Hi @wsfulton, thanks for the suggestion. I think the solution still keeps the second parameter "size"? But I guess maybe you are right that it's probably fine.. and creating a wrapper to make it cleaner is the way to go.

**Comment by ojwb** [comment]
I think the extra magic runes you're looking for are:

```
%typemap(in) (int input, int * size) {
    $1 = $input;
    $2 = NULL;
}
```

That's assuming passing `NULL` for `size` works - if not you'll need something like `int dummy; $2 = &dummy;` instead.
