### ISSUE TITLE
Nested namespace in %template not suitably qualified in generated code

### ISSUE THREAD

**Issue by xhao79** [swig/swig#732]
In my python context:

```
Ubuntu: 45~14.04.1
Python:  3.4.3
SWIG:    SWIG Version 2.0.11
         Compiled with g++ [x86_64-unknown-linux-gnu]
         Configured options: +pcre
```

if define the x.i as:

```
%include <std_list.i>
%include <std_complex.i>
namespace std {
    %template(ComplexList)        list<complex<double> >;
}
```

there will be compiling error. But it works if x.i:

```
%include <std_list.i>
%include <std_complex.i>
%template(ComplexList) std::list< std::complex<double> >;
```

There is no compiling error about the template statement.
[http://stackoverflow.com/questions/38023521/swig-how-to-pass-list-of-complex-from-c-to-python](url)

**Comment by luav** [comment]
This is **Issue is Invalid**:
```c++
namespace std {
    %template(ComplexList)        list<complex<double> >;
}
```
declares SWIG `%template(ComplexList)` in the `std` namespace, but `%template(ComplexList) std::list< std::complex<double> >;`  declares the SWIG template in the global namespace. Of course the behavior is different as it explicitly coded.

```c++
%template(ComplexList) std::list< std::complex<double> >;
```
is the same as
```c++
using namespace std;
%template(ComplexList) list< complex<double> >;
```

**Comment by ojwb** [comment]
I don't think I agree this is invalid.  According to the manual `ComplexList` here "is the name of the instantiation in the **target language**" (my emphasis).  So the current C++ namespace doesn't seem like it should matter.

It looks to me like the issue is that the generated code has `std::list< complex< double > >` - i.e. only `list` gets `std::` qualified, and `complex` doesn't.

This is quite easy to work around though, by adding `using std::complex;` to the generated code.  This amended interface file generates a compilable wrapper for me (I tested with `swig -python -c++ x.i`):

```
%module x
%{
#include <list>
#include <complex>
using std::complex;
%}

%include <std_list.i>
%include <std_complex.i>
namespace std {
    %template(ComplexList)        list<complex<double> >;
}
```

**Comment by luav** [comment]
Thank you Olly, you are right.
I have missed "there will be compiling error" statement. Just the title itself *"%template works differently in namespace std{} or not"* is not really relevant and could be updated. The usage behavior is really different (which is not the issue) as explicitly coded if the type declared inside any namespace (including `std`) vs the global namespace for the *target language*.  
I would change the title to something like "%template parameters namespace missed by SWIG for the interfaces ".

**Comment by wsfulton** [comment]
This is a problem specific to std::complex in the scripting languages because the templated class is not defined in std_complex.i. Hence there is no type information for SWIG to know that complex is in the std namespace.

**Comment by ojwb** [comment]
@wsfulton Isn't that still a bug though?

**Comment by wsfulton** [comment]
@ojwb, maybe you missed my commit which closed this bug report by adding in the missing type information? Or are you referring to something else being a bug?

**Comment by ojwb** [comment]
@wsfulton Sorry, yes somehow totally I missed the "in e01cfd7" bit.
