### ISSUE TITLE
[C#] Wrong inheritance modifier since SWIG 3.0.9: CS0114

### ISSUE THREAD

**Issue by Cpt-Kork** [swig/swig#733]
> SWIG 3.0.9: Improved C++ multiple inheritance support for Java/C# wrappers

Changes introduced with SWIG 3.0.9 appear to break inheritance support when working with modules, 3.0.8 works just fine.

C++: Project **B** and its SWIG interface file:

``` c++
// module: B
// file: /path/to/B/Base.h
class Base {
public:
    virtual void Calculate();
};
```

```
// module: B
// file: /path/to/B/swig.i
%module B
%include "/path/to/B/Base.h"
```

C++: Project **C** and its SWIG interface file:

``` c++
// module: C
// file: /path/to/C/Class.h
class Class : Base {
public:
//    virtual void Calculate(); // not overridden here
};
```

```
// module: C
// file: /path/to/C/swig.i
%module C
%import " /path/to/B/swig.i"
%include "/path/to/C/Class.h"
```

C++: Project **D** and its SWIG interface file:

``` c++
// module: D
// file: /path/to/D/Derived.h
class Derived : Class {
public:
    virtual void Calculate(); // but here
};
```

```
// module: D
// file: /path/to/D/swig.i
%module D
// %import " /path/to/B/swig.i" // <- does not help
%import " /path/to/C/swig.i"
%include "/path/to/D/Derived.h"
```

C# generated files:

``` c#
// module B
public class Base : IDisposable {
    public virtual void Calculate() { /*...*/ }
}
```

``` c#
// module C
public class Class : Base, IDisposable {
//    public virtual void Calculate() { /*...*/ } // <- no Calculate, since not in C++
}
```

Broken inheritance modifier since 3.0.9:

``` c#
// module D
public class Derived : Class, IDisposable {
    public virtual void Calculate() { /*...*/ } // Since SWIG 3.0.9: CS0114: 'Derived.Calculate()' hides inherited member 'Base.Calculate()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword.
}
```

Whereas, everything's fine in 3.0.8:

``` c#
// module D
public class Derived : Class, IDisposable {
    public override void Calculate() { /*...*/ } // SWIG 3.0.8: OK
}
```

**Comment by Cpt-Kork** [comment]
Sorry to bump this issue, but the described bug is still present in the current SWIG release v3.0.11 which leaves our code full of CS0114 compiler errors. I'm kindly asking you to merge the fix proposed in #734.
Thanks!

**Comment by wsfulton** [comment]
I overlooked this for the last release, but I think the patch is okay, I'll probably merge it after checking it fairly soon.

**Comment by Cpt-Kork** [comment]
Thank you very much, I would highly appreciate that 👍 
It would allow us to use the latest SWIG releases once again.

**Comment by wsfulton** [comment]
Patch #734 has now been merged to master
