### ISSUE TITLE
swig syntax error with <openssl/safestack.h>

### ISSUE THREAD

**Issue by jamercee** [swig/swig#747]
Attempting to migrate M2Crypto to OpenSSL 1.1.0 on windows, bumped into swig pre-processor error. How to reproduce the error:

```
mkdir tmp
cd tmp
git clone https://github.com/openssl/openssl.git
echo %include "openssl/safestack.h" > safe.i
swig -Iopenssl/include -python swig.i

```

Results in the error:

**openssl\include\openssl\safestack.h(151) : Error: Syntax error in input(1).**

Platform:
```
SWIG Version 3.0.10
Windows 8.1 Professional

```

Any advice on how I can troubleshoot this?

**Comment by jamercee** [comment]
I discovered the source of the issue. Swig does not accept/allow the Microsoft Visual C "__inline" function decorator (https://msdn.microsoft.com/en-us/library/aa299373%28v=vs.60%29.aspx?f=255&MSPPError=-2147217396). Any ideas what is the correct way to convince swig to accept this a valid decorator?

**Comment by geefr** [comment]
Defining it to nothing on the swig command line should pursuade it to
process.

swig -D__inline <Rest of args>

That is assuming swig doesn't give inline functions special treatment


On 13 July 2016 at 15:52, jamercee <notifications@github.com> wrote:

> I discovered the source of the issue. Swig does not accept/allow the
> Microsoft Visual C "__inline" function decorator (
> https://msdn.microsoft.com/en-us/library/aa299373%28v=vs.60%29.aspx?f=255&MSPPError=-2147217396).
> Any ideas what is the correct way to convince swig to accept this a valid
> decorator?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/swig/swig/issues/747#issuecomment-232380203>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AKk-BCrIdROfY8IPri1xvNSe1KlbG4c8ks5qVPuggaJpZM4JKorN>
> .
>



-- 
--------------------
Gareth Francis
www.gfrancisdev.co.uk

**Comment by ojwb** [comment]
There's also `windows.i` which defines `__inline` to be empty, along with various other things you might need for code written for MSVC:

```
%include <windows.i>
```

It's documented here: http://swig.org/Doc3.0/Windows.html#Windows_interface_file

**Comment by jamercee** [comment]
This is a good solution -- thanks much.
