### ISSUE TITLE
Python3 bytes object to C++ std::string

### ISSUE THREAD

**Issue by chenguoguo** [swig/swig#752]
Is there an easy way to pass bytes object in Python3 to std::string in C++? In my case I'm passing raw data from Python to C++ for processing. By using std_string.i I can pass a string object in Python to std::string in C++. However, in Python3 string now has unicode and cannot really represent the raw data as in Python2.x. Is there a way to pass bytes from python to C++? Or this is simply not doable? Thanks in advance!

**Comment by ojwb** [comment]
```
#define SWIG_PYTHON_STRICT_BYTE_CHAR
```

See the Python chapter of the manual for details: http://www.swig.org/Doc3.0/Python.html#Python_nn77
