### ISSUE TITLE
obsolete debian directory

### ISSUE THREAD

**Issue by nschloe** [swig/swig#774]
It hasn't been touched in 10 years and is hopelessly outdated. The actual Debian files are maintained by Debian itself, see https://sources.debian.net/src/swig/3.0.8-0/.

**Comment by ojwb** [comment]
Wow, that's some ancient cruft.  It uses debhelper compat level 3 (currently only 5 and up are supported) and tries to run `./autogen-debian.sh`, which seems to have been removed before the code was first put into CVS.  Clearly nobody's tried to actually use this for years - removed.
