### ISSUE TITLE
SWIG Platform Preprocessor Define

### ISSUE THREAD

**Issue by rwslord** [swig/swig#776]
I might just be glancing over it, but I can't seem to find a way to hide things from swig when compiling for Linux, but make them visible to swig when compiling for Windows.
`#ifdef _WIN32` doesn't seem to work.

Looking at documentation for swig 1.3, there was a preprocessor define of `SWIGWIN`. But it looks like this was removed in SWIG 2.x+

**Comment by vadz** [comment]
I don't think it would be a good idea to define any symbols depending on the platform SWIG is running under as it would make SWIG output platform-dependent by default. If you really need this, it's simple enough to just define `SWIG_FOR_WINDOWS` or something like this at your build system level.

**Comment by wsfulton** [comment]
Yes, SWIG generates platform independent code by design if you provide the same inputs on each platform. If you want to alter that, then use your own macros to do so.
