### ISSUE TITLE
swig's std_except.i is missing the std::bad_cast exception

### ISSUE THREAD

**Issue by q-p** [swig/swig#783]
This exception occurs for example when the target of a `dynamic_cast` is a reference instead of a pointer (e.g. `dynamic_cast<Bar &>(*this)`).

The fix would be to add
```
  %std_exception_map(bad_cast, SWIG_TypeError); // or maybe SWIG_RuntimeError?
```
to std_except.i

**Comment by wsfulton** [comment]
Yes, okay. I'd probably also prefer TypeError over RuntimeError.
