### ISSUE TITLE
greaterthan and lessthan syntax error in template

### ISSUE THREAD

**Issue by chaffra** [swig/swig#80]
I am getting the error below when trying to wrap boost::units.

'''/usr/include/boost/units/quantity.hpp:50: Error: Syntax error in input(1).
error: command 'swig' failed with exit status 1'''

i think it is related to the > symbol in the line below. Is there any workaround to wrap this while it is being fixed in swig? 

struct is_narrowing_conversion_impl : mpl::bool_< (sizeof(Source) > sizeof(Destination)) > {};

**Comment by gokceneraslan** [comment]
That bug also hit me in Eigen headers: https://bitbucket.org/eigen/eigen/src/60f8b0f18340337e036b566bc583c77deb52f965/Eigen/src/Core/PlainObjectBase.h?at=default&fileviewer=file-view-default#PlainObjectBase.h-142

**Comment by ojwb** [comment]
I wondered if we could at least support `<` and `>` when in a subexpression inside `(` ... `)` which looks like it would cover all the examples here, in #635 and in the older linked issue in the SF tracker.  The Eigen link above doesn't work for me now so I can't easily check that.  This wouldn't be a completely perfect solution, but would fix some cases.

I had a quick try and managed to avoid introducing any reduce/reduce conflicts (which is great) but handling `<` introduces 2 new shift/reduce conflicts (which we ideally want to avoid).  I'll mull this over and see if I can figure out how to make it work without any new conflicts, but if someone with bison expertise wants to take a look please say.

**Comment by wsfulton** [comment]
Great tactical solution @ojwb
