### ISSUE TITLE
Python builtin pickling not working with new import approach in SWIG-3.0.9

### ISSUE THREAD

**Issue by wsfulton** [swig/swig#808]
The following SWIG example implements the `__reduce__ `method for pickling. It fails when invoked with ```swig -c++ -python -builtin example.i```

```swig
%module example

%include <std_string.i>

%extend PickleMe {
#if 0
// Note: %pythoncode can't be used with -builtin
%pythoncode %{
def __reduce__(self):
    print "In Python __reduce__"
    return (type(self), (self.msg, ))
%}
#else
  // Equivalent to Python code above
  PyObject *__reduce__() {
    std::cout << "In C++ __reduce__" << std::endl;
    PyObject *args = PyTuple_New(1);
%#if PY_VERSION_HEX >= 0x03000000
    PyTuple_SetItem(args, 0, PyUnicode_FromStringAndSize(self->msg.c_str(), self->msg.size()));
%#else
    PyTuple_SetItem(args, 0, PyString_FromStringAndSize(self->msg.c_str(), self->msg.size()));
%#endif

    swig_type_info *ty = SWIGTYPE_p_PickleMe;
    SwigPyClientData *data = (SwigPyClientData *)ty->clientdata;
#if defined(SWIGPYTHON_BUILTIN)
    PyObject *callable = (PyObject *)data->pytype;
#else
    PyObject *callable = data->klass;
#endif
    Py_INCREF(callable);

    PyObject *ret = PyTuple_New(2);
    PyTuple_SetItem(ret, 0, callable);
    PyTuple_SetItem(ret, 1, args);
    return ret;
  }
#endif
}

%inline %{
#include <iostream>
struct PickleMe {
  std::string msg;
  PickleMe(const std::string& msg) : msg(msg) {
    std::cout << "Constructor " << " [" << msg << "]" << std::endl;
  }
};
%}
```

With SWIG-3.0.8 the output is all good:
```
Constructor  [hi there]
p msg:  hi there
In C++ __reduce__
reduce:  (<type 'example.PickleMe'>, ('hi there',))
In C++ __reduce__
Constructor  [hi there]
p msg:  hi there
```
If -builtin is not used, the output is also the same. However, with -builtin and SWIG-3.0.10 and current master, output is:

```
Constructor  [hi there]
p msg:  hi there
In C++ __reduce__
reduce:  (<type 'example.PickleMe'>, ('hi there',))
In C++ __reduce__
Traceback (most recent call last):
  File "runme.py", line 12, in <module>
    ds = pickle.dumps(p)
  File "/usr/lib/python2.7/pickle.py", line 1380, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 400, in save_reduce
    save(func)
  File "/usr/lib/python2.7/pickle.py", line 300, in save
    self.save_global(obj)
  File "/usr/lib/python2.7/pickle.py", line 754, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <type 'example.PickleMe'>: it's not found as importlib.PickleMe
```
Interestingly python 2.6.9 is okay, but python 2.7 and later are no good (I tested python 2.7.11 and 3.5.2).

Related to #612. @mromberg, could you please take a look? @m7thon, your patch to help fix -builtin with the new relative import changes in  #691 is also related in.

**Comment by mromberg** [comment]
The block of code which is raising the exception in pickle.py is:

```python
 try:
            __import__(module)
            mod = sys.modules[module]
            klass = getattr(mod, name)
except (ImportError, KeyError, AttributeError):
            raise PicklingError(
                "Can't pickle %r: it's not found as %s.%s" %
                (obj, module, name)) 
```

  So obj, module and name must be set to:

obj = example.PickleMe
module = importlib
name = PickleMe

  But I have no idea why module is importlib instead of example.   What is the other code involved in this example?  There seems to be a runme.py file involved.  Where is it?  What is in it?  Where are the files example.py and _example.so located?  What is the PYTHONPATH set to?

 The obj seems to be set right.  But for some reason pickle.py is not getting the module object right.  I'm not an expert with python pickling but I'd guess it may have something to do with how the example module was loaded.  

  I kinda remember -builtin has python code in the shadow wrapper that does something like 'from _foo import *'.   I remember seeing something like that and having low level alarms go off in my head.  What if __file__ __dir__ and other module attributes are being messed with when -builtin does this?

**Comment by mromberg** [comment]
The bit of code which sets/find the module is right on top of the snippet posted above (from pickle.py):

```python
module = getattr(obj, "__module__", None)
if module is None:
    module = whichmodule(obj, name)
```

  So, it would be interesting to see what example.__module__ is set to.  I'm guessing 'importlib'.  If so, then the next question is why.  If example.py does do a 'from _example import *' and this copies __module__ from _example.so then __module__ must be set to 'importlib' there as well.

**Comment by wsfulton** [comment]
Sorry, I forgot the runme.py file:
```python
import example
import pickle

def show(p):
  print "p msg: ", p.msg

p = example.PickleMe("hi there")
show(p)

r = p.__reduce__()
print "reduce: ", r
ds = pickle.dumps(p)
newp = pickle.loads(ds)
show(newp)
```

**Comment by wsfulton** [comment]
Just use the runme.py file in one of the SWIG's examples such as Examples/python/class and replace example.i with the interface code given, then run make. Note that PYTHONPATH=$PWD, ie current directory containing _example.so, example.py and runme.py.

**Comment by mromberg** [comment]
More clues/information:

```
>>> import _example
>>> _example.PickleMe.__class__
<class 'importlib.SwigPyObjectType'>
>>> _example.PickleMe.__class__.__module__
'importlib'
>>>
```

  SwigPyObjectType looks funny in that it's __module__ is also importlib.  This type lives in _example.so.  It is not clear to me who is suppose to set a __module__ attribute on this thing.  It could be that it needs to be set in the C code (in which case it may be a swig bug).  Or, it could be the job of the loader (in which case importlib or some other part of python is getting it wrong).  Adding to the confusion is the type stuff going on in the example.i interface.

  I'll keep digging...

**Comment by mromberg** [comment]
The code produced by swig without using the -builtin switch is interesting.  This way example.PickleMe.__class__ is type and example.PickleMe.__class__.__module__ is __builtin__.  I'm suspecting somehow SwigPyObjectType is not being seen by python as a builtin type and importlib has no clue about where it was defined.

  I'll have to try and find out where SwigPyObjectType is defined and see if swig is suppose to be doing something to either define it as a builtin or help the module loader know what module it is defined in.  Is this type defined in each swig module?

**Comment by mromberg** [comment]
I'm not 100% certain of about this.  But I think the code swig is spitting out for new types (in particular for builtins) is not right.  See:

https://docs.python.org/2/c-api/typeobj.html

In particular the bit about tp_name.  My take is that swig should be setting tp_name to "_example.PickleMe" or setting "__module__" to "_example".  Since it is currently not doing either of these things I think the undefined behavior mentioned below is what is going on.  Switching to importlib changes the undefined behavior to something else.  The last thing this section mentions is problems with pickle...

> char* PyTypeObject.tp_name
> 
>     Pointer to a NUL-terminated string containing the name of the type. For types that are accessible as module globals, the string should be the full module name, followed by a dot, followed by the type name; for built-in types, it should be just the type name. If the module is a submodule of a package, the full package name is part of the full module name. For example, a type named T defined in module M in subpackage Q in package P should have the tp_name initializer "P.Q.M.T".
> 
>     For dynamically allocated type objects, this should just be the type name, and the module name explicitly stored in the type dict as the value for key '__module__'.
> 
>     For statically allocated type objects, the tp_name field should contain a dot. Everything before the last dot is made accessible as the __module__ attribute, and everything after the last dot is made accessible as the __name__ attribute.
> 
>     If no dot is present, the entire tp_name field is made accessible as the __name__ attribute, and the __module__ attribute is undefined (unless explicitly set in the dictionary, as explained above). This means your type will be impossible to pickle.

**Comment by mromberg** [comment]
The following quick "hack" to example.i makes the failure go away providing some evidence that swig needs to do something different with tp_name and or the "__module__" attribute in the type dict:

`
#if defined(SWIGPYTHON_BUILTIN)
    PyObject *tdict = data->pytype->tp_dict;
    PyMapping_SetItemString(tdict, (char *)"__module__",
      PyString_FromString("_example"));
//    PyObject_Print(tdict, stdout, 0);
    PyObject *callable = (PyObject *)data->pytype;
#else
    PyObject *callable = data->klass;
#endif
`

**Comment by wsfulton** [comment]
Yes, it seems that tp_name should be ```_example.PickleMe``` instead of ```example.PickleMe```, but it didn't make any difference when I tried. Although setting ```__module__``` as you suggest seems to work, it doesn't follow the recommendations of the documentation as the builtin type defined by SWIG is a statically allocated type (so it seems). I'm reluctant to change this unless this is properly understood as am not sure what else will break. Needs some more investigation...

**Comment by wsfulton** [comment]
I am about to modify your posts so that the underscores are visible... I suggest you use the Preview option before posting markup here.

**Comment by wsfulton** [comment]
Ah, I see @ojwb beat me to it these edits :)

**Comment by ojwb** [comment]
Yeah, I was struggling to follow (though fixing the markup didn't entirely help).

**Comment by mromberg** [comment]
> Yes, it seems that tp_name should be _example.PickleMe instead of example.PickleMe, but it didn't make any difference when I tried. Although setting __module__ as you suggest seems to work, it doesn't follow the recommendations of the documentation as the builtin type defined by SWIG is a statically allocated type (so it seems). I'm reluctant to change this unless this is properly understood as am not sure what else will break. Needs some more investigation...

  Yes.  setting tp_name did not seem to make pickle happy for me either.   Some of the code I did see inside pickle.py did check for the "__module__" attribute directly.  So, it may be that for pickle to work a type needs to have that attribute. 

  But unanswered questions such as what part of python does set the name and module attributes if just tp_name is set (and is an absolute path)?  I'd guess the loader does.  Or tries to.  That may be the reason importlib is showing up as the module in some cases.  I'm not sure.

  Also, the reduce() method does return a callable of a type that may or may not be confusing python.  Some experiments I did showed objects out of the example module looking fine (they showed example as the module).  But the type returned by reduce was wrong.  So, I'm not 100% certain that the callable returned by reduce is right.  In theory an objects reduce method could return any callable type (even ones originating in different modules).  So, this object could be extra sensitive to having attributes set on it?  I'm not sure.

  It may also be that there is some kinda bug with importlib on python2.7 (I have not tried it with python3 yet).  I'll keep looking...

**Comment by wsfulton** [comment]
Same problem but different error message with python 3.5.2:
```
Traceback (most recent call last):
  File "runme3.py", line 13, in <module>
    ds = pickle.dumps(p)
_pickle.PicklingError: Can't pickle <class '_example.PickleMe'>: attribute lookup PickleMe on importlib._bootstrap failed
```
Setting ```__module___``` to ```_example``` makes it work so Python 2.7 is much like 3.5. That doesn't rule out a bug in importlib though. I've tried correcting tp_name to ```_example.PickleMe``` too and that is also no good. I'd like to find out more about exactly what the statically and dynamically allocated type object means in order to follow the recommendations.

PS, if you run: ```make clean check PY3=1``` in one of the Python examples directory, it will automatically work with python 3 (assuming configure found it). Also ```make check SWIG=echo``` will run everything except it won't invoke swig, so is a good way to experiment as ti allows you to manually edit the SWIG generated files.

**Comment by wsfulton** [comment]
https://docs.python.org/3/c-api/typeobj.html states "dynamic subtypes (subtypes created by a class statement)" indicating that dynamically allocated types are types created in Python via  ```class```. So the SWIG proxy classes (when not using -builtin) will be dynamic types. When using -builtin, the types are not created like this, so they must be statically defined types. I still can't see what SWIG is doing wrong in the definition and setting up of the PyTypeObject, but will continue to re-examine this. 

The base class ```SwigPyObject``` looks suspicious. It does not have a module in its name, but in order for %import to work, it makes sense that this base class is not package specific as all SWIG generated classes ought to have one common base. When using %import, each class imported is imported from a different module.

**Comment by mromberg** [comment]
I think SwigPyObject may be causing the confusion.  If I use example.i directly (no hack I mentioned 
above) and this bit of runme.py driver code:

`import example
import pickle

o = example.PickleMe("spam")
ro = o.__reduce__()[0]
print ro.__class__
print ro.__class__.__module__
`

  I get:

` > python2.7 runme.py
Constructor  [spam]
In C++ __reduce__
<class 'importlib.SwigPyObjectType'>
importlib
`

  I think having a common base class SwigPyObject is a fine thing.  But I do think it should be in a module of some kind.  If python can see it as a base class then parts of python (like pickle) will want to know where it came from.  Right now it is not even in `__builtin__`.  I think it would be a better idea for swig to create a new module of some sort to hold things like PyObjectType.  It could be called __swigbuiltin__ or something.

**Comment by wsfulton** [comment]
So SwigPyObjectType is the metaclass for SwigPyObject, so we might have to start looking more closely at metaclasses to solve this and whether it should be in a module. I suspect that these not being in a module is a problem, there are plenty of builtin types that are not. I thought the following was interesting as ```inspect.getmodule``` thinks they are in ```__builtin__```:
```
>>> p = example.PickleMe("hi there")
Constructor  [hi there]
>>> for t in p.__class__.__mro__:
...     print t, " : ", inspect.getmodule(t)
... 
<type 'example.PickleMe'>  :  <module 'importlib' from '/usr/lib/python2.7/importlib/__init__.pyc'>
<type 'SwigPyObject'>  :  <module '__builtin__' (built-in)>
<type 'object'>  :  <module '__builtin__' (built-in)>
```
So SwigPyObject seems okay, but not the metaclass:
```
>>> print "metaclass:", p.__class__.__class__, inspect.getmodule(p.__class__.__class__)
metaclass: <class 'importlib.SwigPyObjectType'> <module 'importlib' from '/usr/lib/python2.7/importlib/__init__.pyc'>
```

If we get rid of the importlib to do the importing and simply use what we used to do in SWIG-3.0.8 and earlier by modifying example.py with just this:
```
import _example
from _example import *
```
then things are better:
```
>>> for t in p.__class__.__mro__:
...     print t, " : ", inspect.getmodule(t)
... 
<type 'example.PickleMe'>  :  <module 'example' from 'example.pyc'>
<type 'SwigPyObject'>  :  <module '__builtin__' (built-in)>
<type 'object'>  :  <module '__builtin__' (built-in)>
```
and so does the metaclass:
```
>>> print "metaclass:", p.__class__.__class__, inspect.getmodule(p.__class__.__class__)
metaclass: <class 'example.SwigPyObjectType'> <module 'example' from 'example.pyc'>
```
It feels like importlib is broken. I think we should find some other builtin types in a module that are shipped with Python in the standard library and see if importlib works with them. That will also be a useful reference for comparing how the builtin type is defined/configured.

**Comment by wsfulton** [comment]
datetime.date is a builtin type in the standard library and does work okay when importing it in a similar way with importlib. I'll look more closely at the builtin implementation of this tomorrow and tweak PickleMe to do something similar by dropping the inheritance from SwigPyObject.

**Comment by mromberg** [comment]
> It feels like importlib is broken.

  I took a look at what was in importlib on python2.7.  And there is not really much there.  It consists of just two functions that mostly examine/modify the name/package and then call __import__().   I was told by Bret Cannon (python core developer) that one should use importlib.import_module() rather than directly using __import__().  
 
    I did some experiments and found that if one simply does 'import _example', then the swig types are assigned/placed in the __main__ module.  But if __import__ or importlib is used then SwigPyObject is not placed in the main module.   It is placed into the importlib package/module.  And I think I have a theory as to why.

  Since these types do not have a module set the python import machinery is assigning them to whatever module is currently in scope.  When the raw import statement was done (before swig used importlib) then the current module scope was example (example.py).  But with importlib the current module is importlib.

  So, reverting back to doing "import _example" would "fix" things.  But I think this may be relying on shaky ground.  I'm not sure python does define any behavior for static types that don't have a module.  And my guess is that the behavior is undefined.  Anything else would mean that importlib.import_module() could not do the job it exists for.

**Comment by wsfulton** [comment]
That is interesting. I still don't know that the lack of a package is a problem though. I had already tried modifying tp_name to include a module name for the 3 other  PyTypeObject types in SWIG:

- SwigPyObject
- SwigPyPacked
- swig_static_var_getset_descriptor

Needless to say it didn't make a difference. Not all the builtin types shipped with Python are in modules and they don't have issues with importlib.

I think the problem is with the SwigPyObjectType metaclass. Just removing this line in the setup of each builtin type:
```
  SwigPyBuiltin_SetMetaType(builtin_pytype, metatype);
```
fixes the problems with importlib and picklilng. So next steps to me are:
1) Figure out if the setup of the metaclass is done correctly (I've not really looked at them before).
2) SwigPyObjectType is only used for setting static member variables (not functions) and perhaps there is an alternative approach? Only one test (cpp_static.i) broke in the test-suite with this change.
3) Maybe importlib is broken for custom metaclasses?

**Comment by mromberg** [comment]
This issue with python itself and metaclasses seems very similar (the module is getting set wrong):

http://bugs.python.org/issue503837

  This bug is marked as fixed in python.  But in the above case the metaclass exists in a .py file.  Wonder if there still exists a similar bug for when the metaclass is builtin?  I imagine it is not very common for anyone to be using metaclasses as new builtin types.

**Comment by wsfulton** [comment]
I've fixed this by setting up the SwigPyObjectType metaclass as a builtin type.

However, like @mromberg, I'm not entirely happy with the status of the module and it applies to all these types:
* SwigPyObjectType
* SwigPyObject
* SwigPyPacked
* swig_static_var_getset_descriptor

They have not been added into any module. Normally builtin types are added to a module using `PyModule_AddObject`. For example (after my fix), the following patch ensures PySwigObject is a type
```
diff --git a/Lib/python/pyinit.swg b/Lib/python/pyinit.swg
index 2cc5828..b8ce1d9 100644
--- a/Lib/python/pyinit.swg
+++ b/Lib/python/pyinit.swg
@@ -416,6 +416,8 @@ SWIG_init(void) {
 
 #ifdef SWIGPYTHON_BUILTIN
   swigpyobject = SwigPyObject_TypeOnce();
+  Py_INCREF(swigpyobject);
+  PyModule_AddObject(m, "SwigPyObject", (PyObject *)swigpyobject);
 
   SwigPyObject_stype = SWIG_MangledTypeQuery("_p_SwigPyObject");
   assert(SwigPyObject_stype);
```
So then SwigPyObject can be viewed/used more normally:
```python
>>> import example
>>> p = example.PickleMe("hi there")
Constructor  [hi there]
>>> p.__class__.__mro__
(<type 'example.PickleMe'>, <type 'SwigPyObject'>, <type 'object'>)
>>> isinstance(p, example._example.SwigPyObject)
True
>>> dir(example._example.SwigPyObject)
['__class__', '__cmp__', '__delattr__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__hex__', '__init__', '__int__', '__le__', '__long__', '__lt__', '__ne__', '__new__', '__oct__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'acquire', 'append', 'disown', 'next', 'own']
```
Although I'd expect it to be available as displayed in the `__mro__` call as `SwigPyObject` and not just `example._example.SwigPyObject`.
