### ISSUE TITLE
Macro '%std_nodefconst_type' redefined

### ISSUE THREAD

**Issue by ashokbugude** [swig/swig#809]
I am using Ubuntu 16.04 and swig 3.0.8

I am trying to install voxelsdk https://github.com/3dtof/voxelsdk which makes use of swig 3.0

I am getting below errors while installing voxel sdk 

```
zayyon@zayyon-Lenovo-ideapad-300-15ISK:~/Downloads/voxelsdk-master/build$ sudo make install
[sudo] password for zayyon: 
[ 31%] Built target voxel
[ 32%] Swig source
/home/zayyon/Downloads/voxelsdk-master/Voxel/SWIG/standard_container.i:120: Error: Macro '%std_nodefconst_type' redefined,
/usr/share/swig3.0/std/std_container.i:135: Error: previous definition of '%std_nodefconst_type'.
Voxel/SWIG/CMakeFiles/_Voxel.dir/build.make:61: recipe for target 'lib/python2.7/VoxelPYTHON_wrap.cxx' failed
make[2]: *** [lib/python2.7/VoxelPYTHON_wrap.cxx] Error 1
CMakeFiles/Makefile2:174: recipe for target 'Voxel/SWIG/CMakeFiles/_Voxel.dir/all' failed
make[1]: *** [Voxel/SWIG/CMakeFiles/_Voxel.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

I tried raising the issue with voxelsdk https://github.com/3dtof/voxelsdk/issues/89 but couldn't get much help.
Could you please help resolving the issue

**Comment by ojwb** [comment]
This seems like a bug in voxel to me - they're redefining a macro SWIG defines (and has since ~2004).  It's sad they closed your ticket, but I don't really see how we can help.

**Comment by ashokbugude** [comment]
Could you please suggest any code changes that could be made by me in that particular file or anywhere so that the macro is not defined again

**Comment by ashokbugude** [comment]
I tried commenting the line where macro was redefined but unable to resolve the issue

**Comment by ojwb** [comment]
Sorry - I don't know how you'd fix this without digging into the voxel code, which I really don't have time to get sucked into.  If the voxel developers aren't interested, you could try asking on the swig-user mailing list.

Not a SWIG bug, so closing.
