### ISSUE TITLE
syntax error near unexpected token 'fi'

### ISSUE THREAD

**Issue by Andreas237** [swig/swig#815]
Greetings,

In advance- sorry for my lack of etiquette, this is my first contribution.

There are erroneous tokens in the "configure" file.

Line 5855 and line 5975 have "else" tokens that should be removed.  The script works fine from there.

To recreate:
 $ git clone https://github.com/swig/swig.git
 $ cd swig
 $ ./autogen.sh
 **$ ./configure --prefix=/some/directory**
 $ make
 $ make install

**Comment by ojwb** [comment]
I can't reproduce this, and lines 5855 and 5975 for me don't seem to correspond to yours.

What versions of the autotools are you using?  Output of these commands would be useful:

```
autoconf --version
automake --version
```

And what does the generated `configure` file look like around lines 5855 and 5975?

**Comment by ojwb** [comment]
Output of this might also be interesting:

```
sh -n configure && echo OK
```

That says `OK` for me.

**Comment by ojwb** [comment]
No response from submitter for several weeks, so closing as incomplete. If you want to pursue this issue, please provide the requested information and we can reopen.

**Comment by chunfantasy** [comment]
Error:

```
Checking packages required for SWIG developers.
Note : None of the following packages are required for users to compile an
d install SWIG from the distributed tarball

checking for bison... no
checking for byacc... no

Checking for installed target languages and other information in order to
compile and run
the examples and test-suite invoked by 'make check'.
Note : None of the following packages are required for users to compile an
d install SWIG from the distributed tarball

./configure: line 5932: syntax error near unexpected token `fi'
./configure: line 5932: `fi'

```

autoconf (GNU Autoconf) 2.69
automake (GNU automake) 1.15
