### ISSUE TITLE
SWIG with .NET Core errors

### ISSUE THREAD

**Issue by paolo8417** [swig/swig#820]
Hi,
I'm using SWIG with .NET Core and  when I try to compile the .Net Core application I've these errors on the generated wrapperPINVOKE.cs:

> wrapperPINVOKE.cs(56,51): error CS0234: The type or namespace name 'ApplicationException' does not exist in the namespace 'System' (are you missing an assembly reference?)
> wrapperPINVOKE.cs(86,51): error CS0234: The type or namespace name 'SystemException' does not exist in the namespace 'System' (are you missing an assembly reference?)
> wrapperPINVOKE.cs(143,34): error CS0234: The type or namespace name 'ApplicationException' does not exist in the namespace 'System' (are you missing an assembly reference?)

cause in .NET Core global::System.ApplicationException and global::System.SystemException doesnt' exists.
If I manually replace global::System.SystemException and global::System.ApplicationException with global::System.Exception it works.

Is there a way to fix it without replace it manually?

**Comment by wsfulton** [comment]
The code that generates this is configurable, but it will mean copy/pasting/editing quite a lot of the input files. I am surprised that these pretty fundamental exceptions are missing in .NET core, is that really right? If someone is familiar with .NET core we can work together to try figure out how to support .NET core. Maybe some preprocessor trickery to rename them or something when .NET core is present.

**Comment by crule42** [comment]
Apparently there are no plans to add these exceptions back in to .net core: 
([https://github.com/dotnet/corefx/issues/4222])
"Regarding ApplicationException we believe that creating that type was a mistake and are trying to move away from it. "

**Comment by paolo8417** [comment]
> "Regarding ApplicationException we believe that creating that type was a mistake and are trying to move away from it. "

Ok, thanks. 

> The code that generates this is configurable 


Now, I need something to avoid me to manually replace the exception for each compilation.
Which is the Swig configuration that replaces on the PINVOKE the unhandled exception global::System.ApplicationException and global::System.SystemException with global::System.Exception?!

**Comment by wsfulton** [comment]
https://github.com/dotnet/corefx/issues/4222 is now closed as ApplicationException has been added to .net standard 1.7 which will be in .net standard 2.0 as part of .net corefx 1.2 scheduled for Spring 2017, according to https://github.com/dotnet/core/blob/master/roadmap.md. I can't see an easy way to get a preview release of this, but I would like to try it out and make sure there are no other problems with SWIG generated code with this new .net standard.

@paolo8417, in the meantime, you will have to use a number of different SWIG customization features to modify the code. Sorry, I don't have time to give full details but a simpler approach might be to copy and modify the library files as all usage of ApplicationException is in the library. See `swig -v` to see the search paths being used.

**Comment by ojwb** [comment]
Closing as a duplicate in favour of #1299.
