### ISSUE TITLE
Typemap getter and setter methods mapped to attributes with %attributeval

### ISSUE THREAD

**Issue by retuxx** [swig/swig#822]
I'm using %attributeval to map getter and setter methods to 'native' attributes. My getter/setter pair is of type `std::vector<float>`. Therefore, I have implemented a typemapping that is supposed to map a vector to an array (for PHP). Unfortunately, it seems like %attributeval restructures the code such that my typemapping is not applied anymore. Is it possible to let the %attribute macros work together with regular in and out typemappings?

**Comment by retuxx** [comment]
I found that I need to use the pointer typemaps when matching methods mapped to attributes using %attribute(val|ref).

**Comment by letmaik** [comment]
I just stumbled upon the same problem but with `%attribute2`. Your solution worked. Thanks!
