### ISSUE TITLE
Release Swig 3.0.10 have problems with configure file

### ISSUE THREAD

**Issue by malliwi88** [swig/swig#824]
The compressed archive that is available in Sources Swig 3.0.10 have problems with the configuration file.

I've downloaded the official website here
The indications for anyone who may have the same problem.

**Comment by ojwb** [comment]
> The indications for anyone who may have the same problem. 

You haven't said anything clear about what your problem actually is...

Please say what command you ran, paste the output you get, and tell us what you expected to happen instead.

**Comment by ojwb** [comment]
No response from submitter for several weeks, so closing as incomplete.  If you want to pursue this issue, please provide sufficient information that we can understand what your problem is, and we can reopen.
