### ISSUE TITLE
Official Objective-C Support?

### ISSUE THREAD

**Issue by iOS-univera** [swig/swig#827]
Hi,

I'm curiously asking there will be a official support for Objective-C in the next releases?

**Comment by wsfulton** [comment]
Objective C is partly implemented in this branch: https://github.com/swig/swig/tree/gsoc2012-objc and needs further work to fix. The test-suite should be run to find the current status. Here is what we last saw on Travis (Linux): https://travis-ci.org/swig/swig/jobs/98608723. Travis testing needs setting up on OSX too by someone interested in helping as the original author didn't quite get it into a state that is good enough to be merged into master.

**Comment by soha-adel** [comment]
Any updates regarding this branch ?
and Is there other alternatives ?

**Comment by wsfulton** [comment]
I havn't heard of anything, it requires a volunteer to work on it.

**Comment by pvmiseeffoC** [comment]
Can I volunteer?
I'd love to have some contribution to SWIG!

**Comment by wsfulton** [comment]
@pvmiseeffoC of course you can! The information I posted earlier in this issue still stands. First thing would be for you to clone the branch into your own Github repo, setup a Travis account and update it to show us the state of it on Travis. Then research the previous work done and analyse what works and doesn't work in order to come up with a plan of action to get it up to scratch. See http://swig.org/Doc4.0/Introduction.html#Introduction_target_languages for info on what is needed to get a new target language module into the Experimental status in order to be included into mainline SWIG.

**Comment by pvmiseeffoC** [comment]
Nice, I've checked out the branch and I'll research what has been implemented already whenever I have free time.
There's 130ish commits in the branch so it will probably take me a lot of time to process what has been done and to familiarize myself with the inner workings of swig.
If I need help for something, do I ask here or do I write an email to the swig-devel group?
If there's a startup guide for new contributors I'd love to check it out as well!

**Comment by MattKang** [comment]
@pvmiseeffoC let me know if you need some help with this. Just checked out the branch last night and was able to merge `master` and get it working. Need to get the automated testing and Travis stuff working next. It appears that function overloading is currently unsupported

Personally interested in getting this going given the current state of djinni, and more generally, cross-platform moblie C++ dev

**Comment by wsfulton** [comment]
@pvmiseeffoC, you'll find the most useful information for new contributors by following the link I posted above. You should come across http://swig.org/Doc4.0/Extending.html#Extending. Also see the development docs in Doc/Devel subdirectory.

For general development questions, the swig-devel mailing list is probably the best place. Good luck!

**Comment by MattKang** [comment]
@wsfulton are there any guidelines for git contributions and PRs?

**Comment by wsfulton** [comment]
http://swig.org/svn.html contains general developer info. That page links to some generic pull request instructions. So in a nutshell, just follow good practice for pull requests We're pretty flexible, but pay a lot more attention to pull requests that include a test along with an enhancement/fix.

However, if you are adding in Objective-C support, that is a whole different ball game and the info you need for new language modules is in the links I posted earlier. For feedback as you develop the Objective-C module towards the documented 'Experimental Status', I suggest you point to your own repository and discuss progress in an issue dedicated specifically to Objective-C.

**Comment by wsfulton** [comment]
Hi @MattKang, just wondering how you are getting on with this?

**Comment by MattKang** [comment]
@wsfulton Haven't been able to work on it the last few weeks, unfortunately. Priorities at work shifted away from our mobile interfaces, but I'm back on that now and will be giving attention to it. Will keep everyone updated here!

@pvmiseeffoC any update on your end?

**Comment by pvmiseeffoC** [comment]
I haven't been able to do much the last month.
I've looked at the last 30 or 40 commits in the branch.
I guess today I'll make my own fork of the branch and start looking at how other modules are implemented as reference

**Comment by pvmiseeffoC** [comment]
@wsfulton how do I setup a Travis account?

**Comment by ojwb** [comment]
Closing in favour of #1873.
