### ISSUE TITLE
Go swig document for go-1.5 and above needed to be changed

### ISSUE THREAD

**Issue by cczhong11** [swig/swig#829]
@ojwb
now in go-1.5 and later version, 6g 6c is [replaced](https://golang.org/doc/go1.5#compiler_and_tools) by go tool compile. However, go tool compile [can only compile go file](https://golang.org/cmd/compile/#hdr-Compiler_Directives)
From this [golang official wiki](https://github.com/golang/go/wiki/GcToolchainTricks) we cannot use 6c in the 1.5 version and above
therefore I don't know how to install go package manually
```
% swig -go example.i
% gcc -c code.c # The C library being wrapped.
% gcc -c example_wrap.c
% go tool 6g example.go
% go tool 6c example_gc.c
% go tool pack grc example.a example.6 example_gc.6 code.o example_wrap.o
% go tool 6g main.go
% go tool 6l main.6
```

**Comment by ojwb** [comment]
@cczhong11 Why did you @-mention me?  I don't maintain SWIG's Go backend...

**Comment by zuraff** [comment]
Hi, why this got closed? This is a true issue, no clue how to use swig + go.

**Comment by tamama** [comment]
Does SWIG still support C++ => Go for Go-1.5 ?

**Comment by tamama** [comment]
SWIG-Go seems to be rather inactive?

**Comment by ojwb** [comment]
A bug report that been closed for nearly 5 years really isn't a good place to ask general questions - the mailing list would be a better choice.

The Go builds in SWIG's CI are green and test 1.3, 1.8, 1,12 and 1.16.  If something specific isn't working with a recent Go version, please file a new bug report with a self-contained reproducer.
