### ISSUE TITLE
Stop using SourceForge for holding releases.

### ISSUE THREAD

**Issue by AraHaan** [swig/swig#835]
I personally hate SourceForge at least have a option to not download from SourceForge the binaries to their platform like Windows on github or something (I hate SourceForge as they sometimes inject malware into installers).

**Comment by ojwb** [comment]
This isn't an issue in the source code, and would really be better raised on the mailing list than here.

**Comment by wsfulton** [comment]
SourceForge have stopped the practise of injecting code into binaries, and I'm not aware of them ever doing it to SWIG releases. A new host for storing and distributing binaries would be fine if someone wanted to initiate this work... modify build and deployment scripts, web links and documentation etc. All the other SF facilities would need moving too, thinkgs like news and website hosting.
