### ISSUE TITLE
Incorrect generated code when tag name and typedef name are identical.

### ISSUE THREAD

**Issue by davedissian** [swig/swig#838]
Consider the following interface file:
```
%module Broken

%inline {
typedef struct Test Test;
void function(Test* test);
struct Test {
      int foo;
};
}
```

This produces the following module class:
```
public class Broken {
  public static void function(SWIGTYPE_p_Test test) {
    BrokenJNI.function(SWIGTYPE_p_Test.getCPtr(test));
  }
}
```

It seems to be assuming that the Test struct only has a forward declaration, despite providing an implementation later. The Test class is generated in Java, but `function` doesn't make use of it.

I'm happy to take a look at fixing this bug, if anyone has any pointers of where to look in the SWIG codebase?

**Comment by wsfulton** [comment]
Not entirely sure, however, if the class name is not available, `JAVA::getProxyName` does not return a valid name, and then the type wrapper name, SWIGTYPE_p_Test in this case, will be used instead. You'll need to look at `Language::classLookup`. It is probably going to be some symbol table or symbol table search problem and could be rather mucky to fix as SWIG doesn't support . Use the `-debug` command line options and have a good look at the docs in the Doc/Devel subdirectory and at http://swig.org/Doc3.0/Extending.html. 

You code is rather odd though, surely you meant to have:
```
/*typedef*/ struct Test {
    int foo;
};
```

**Comment by ojwb** [comment]
I wonder if this (12.5 year old!) bug is related: https://sourceforge.net/p/swig/bugs/429/

**Comment by davedissian** [comment]
@wsfulton My bad, the implementation of the class should be:

```
typedef struct Test {
    int foo;
} Test;
```
