### ISSUE TITLE
Hash function support broken

### ISSUE THREAD

**Issue by rom1011** [swig/swig#843]
I have a has function for a custom object defined as
```
  %feature("python:slot", "tp_hash", functype="hashfunc") __hash__;
  long __hash__(void)
  {
    return calculate hash here();
  }
```
In swig 3.0.10 this is converted to a int type PyObject
```
 #define SWIG_From_long   PyInt_FromLong 
```
But the closure SWIGPY_HASHFUNC_CLOSURE uses PyLong_Check() which fails for a int.

It is working fine in swig 3.0.0

**Comment by wsfulton** [comment]
This is due to this change: 2e1595a4d07eaa3434f7e1a451bcf01cfad6f0e1. I'll commit a fix shortly.
