### ISSUE TITLE
[python] swig_import_helper can obfuscate user-level errors

### ISSUE THREAD

**Issue by Yurlungur** [swig/swig#848]
When swig generates python wrappers for a module named `example`, it produces two files:
`_example.so` (in linux for example) and `example.py`. In `example.py` there's a code snippet that looks something like this (for Python 2. I assume it's similar for Python 3.):

```python
def swig_import_helper():
    import importlib
    pkg=__name__.rpartition('.')[0]
    mname = '.'.join((pkg,'_example')).lstrip('.')
    try:
        return importlib.import_module(mname)
    except ImportError:
        return importlib.import_module('_example')
```

The issue is that `ImportError`. If some dependencies are missing or misplaced, importing the swig wrappers may raise a "no such file or directory" error for some static library the code depends on, such as mpi. And this will appear in Python as an `ImportError`. The except will thus get triggered and `importlib.import_module('_example')` will get called.

This will be fine in many cases. However, if `_example` is one module in a multi-module package, then the naming will be wrong and the import will fail. To the user, this will look like the search path for the modules is somehow wrong when, in fact, the real problem is the environment (for example a linking error or an incorrect `LD_LIBRARY_PATH`).

I propose that the try-except block be changed to:

```python
    try:
        return importlib.import_module(mname)
    except ImportError as err:
        if '_example' in err.message:
            return importlib.import_module('_example')
        else:
            raise err
```

I believe the relevant changes can be made [here](https://github.com/swig/swig/blob/master/Source/Modules/python.cxx#L829) and I'm happy to do so and submit a pull request. However, before I did that, I wanted to check with the community to make sure my proposal made sense.

Thanks in advance for your feedback!

**Comment by ojwb** [comment]
The `if '_example' in err.message:` test seems a bit crude - what are the `err.message` values it's trying to discriminate between exactly?

**Comment by Yurlungur** [comment]
Thanks for the feedback!

I found this error while wrapping code that depended on MPI. And because I linked against the wrong MPI library, the raised `ImportError` that I'd like to see has the message

```
ImportError: libmpicxx.so.3: cannot open shared object file: No such file or directory
```

however, because the try-except block gets triggered and `return importlib.import_module('_example')` gets called, I see the following message:

```
ImportError: No module named _example
```

So I suppose what I'm trying to distinguish between is "no module named X" and "no such file or directory." The reason I used `if '_example' in err.message:` was because I figured the error would be of the second form.

**Comment by ojwb** [comment]
There's a possibility of a false match in certain cases though.  Say I have an `plot` module I create using SWIG and one of the libraries used behind the scenes is `libwx_gtk2u_plot-2.8.so.0` - the `ImportError` message if that's not found would be:

```
ImportError: libwx_gtk2u_plot-2.8.so.0: cannot open shared object file: No such file or directory
```

But this contains the substring `_plot`, so your check would mistake this for the second case.

I guess this is no worse than what currently happens, and most cases are improved, but I wonder if there's a way to solve this without looking at `err.message`.

**Comment by Yurlungur** [comment]
That's a good point. We could further specify, I suppose, by asking for `err.message` to include `No module named` (or alternatively for it *not* to contain the phrase `No such file or directory`).

There doesn't seem to be any information in `err` other than `message`. But maybe there is a safe way to check if a module can be imported without using try-catch. I will play with a few things and see if any are reliable.

**Comment by ojwb** [comment]
Looking at the boilerplate text is prone to issues if that text undergoes i18n, and also with rewording of error messages in future Python versions, so avoiding looking at the message at all would be better if possible.

Failing that, if we are going to inspect the message perhaps it's best not to try to overthink this - the change as proposed should improve this in many cases, and the corner ones like my `plot` one will behave as now.

Also SWIG's boilerplate Python import code is likely to get significantly simplified in SWIG 3.1.x when we drop support for older Python versions, which may make this easier to solve fully.

**Comment by Yurlungur** [comment]
How about something like this (taken from [this stackoverflow question](http://stackoverflow.com/questions/14050281/how-to-check-if-a-python-module-exists-without-importing-it))?

For Python2:

```python
import importlib,pkgutil
pkg=__name__.rpartition('.')[0]
mname = '.'.join((pkg,'_example')).lstrip('.')
if pkgutil.find_loader(mname) is not None:
    importlib.import_module(mname)
else:
    importlib.import_module('_example')
```

and for Python3 the syntax is similar, but instead of `pkgutil`, we have `importlib.find_loader(mname)` for versions before 3.4 and `importlib.util.find_spec(mname) ` for versions >= 3.4

**Comment by mromberg** [comment]
The code in question here revolves around swig supporting the C part of a module being in either the same package as the pure python half or in the global namespace.  So, the swig import helper code needs to cover both cases.

  It would be nice if python itself had more fine grained exceptions.   But it does not.  ImportError covers both the "can't find the file" and "file failed to load" cases.  So, swig can't easily tell the difference without digging deeper into the python import machinery.

  And this python machinery differs depending on what python version is being used.   SWIG supports so many different python versions that using things like find_loader makes one a bit of a python historian.

  Examining the message string attached to the exception is clearly not a good thing to do.  But compared to the alternative (lots more python version specific code in the swig import helper), I'm not sure if it is not the better of two bad alternatives.

**Comment by wsfulton** [comment]
@mromberg, in swig-3.1 we can make some non-backwards compatible changes. Does it make sense to drop the support for importing the low level C/C++ module, such as `_mod.so` from the global namespace? From my understanding, this seems to be the key to making the import simpler and not having to catch the ImportError. This could be the default and a user is always able to use the custom module importing introduced for swig-3.0.11 in 2a42031b085d8f4568aa90dede879ea008e1611b to change it back.

Secondly, the import logic currently special cases version 2.7 and 2.6 only and for earlier versions just a simple `import _example` is run. So, I don't think we need to be Python historians to successfully use @Yurlungur's suggestion as we only need to test it for 2.6 and 2.7. Catching exceptions as normal code flow is best avoided if possible.

**Comment by mromberg** [comment]
> in swig-3.1 we can make some non-backwards compatible changes. Does it make sense to drop the support for importing the low level C/C++ module, such as _mod.so from the global namespace?

  Removing _mod.so existing in the global namespace would not be a backwards compatible change in swig-3.0.  Because the import helper code would and still does load this module into the global namespace.   Many swig users which statically link this module into an embeded application put the shadow (.py) file in a package but do not put the C module into any package at all.

  So, I think swig-3.0 needs to keep doing this.   I think it would make a whole bunch of sense to think about these two modules for swig-3.1.   They really are (to python) two separate and distinct modules.  Yet swig sorta treats them as a public and private part of the wrapper.

  I think swig should make some decisions about these modules and the packages they exist in.   Should they always be in the same package (right now they dont have to be)?   If they can exist in different packages should the module interface file (.i) have some hint about where they might be found?  This directly addresses the problem we have with the swig interface being split into two parts which are python modules.   I think swig-3.1 should make life easier for both swig and users by making locating one module from another easier and well documented.

  I'm fairly certain David Beasley created swig back when python did not even have packages.   So, it is easy to see why packages are somewhat problematic.  Swig-3.1 sounds like a great opportunity to clear up (and clean up) the swig implementation of python packages.

**Comment by mromberg** [comment]
> It would be nice if python itself had more fine grained exceptions. But it does not. ImportError covers both the "can't find the file" and "file failed to load" cases.

  Oh!  Python-3.6 now covers this:

https://docs.python.org/3.6/whatsnew/3.6.html#other-language-changes

**Comment by Yurlungur** [comment]
So to summarize, it seems that the lesser of two evils is (for older Python versions) to check the text of the ImportError. 

But for python 3.6 and later, we can use the more fine-grained errors available?

**Comment by mromberg** [comment]
In my opinion, what would be ideal is for some future version of swig (3.1 or later?) to specify that the C module must be in the same package as the shadow (.py) module.   If this were to be done (along with dropping support for antiquated python versions) then the import code in the .py module could be massively simplified.  And the test that is causing the trouble reported in this issue would not even need to be done.

  But if swig continues to allow the .so module to live in either a package or the global namespace then this sort of test will continue to be needed.  And, as can be seen with python-3.6, will continue to involve swig wrapper code doing conditionals based on python version numbers.   It would be nice to make as much of this as possible go away.

**Comment by ojwb** [comment]
> In my opinion, what would be ideal is for some future version of swig (3.1 or later?) to specify that the C module must be in the same package as the shadow (.py) module

My (admittedly probably underinformed) impression is that putting both in the same package is regarded as good Python practice, and the extra flexibility doesn't seem to actually offer anything useful, so this sounds good to me.  Currently SWIG makes it harder than is ideal to follow this "good practice" route.

**Comment by minrk** [comment]
On Python 2, there is [`imp.find_module('name')`](https://docs.python.org/2/library/imp.html#imp.find_module), so there is a version of @Yurlungur's fix for every version back to 2.6, I believe.

```python
try:
    from pkgutil import find_loader
except ImportError:
    # py < 3.3
    from imp import find_module 
```

**Comment by ojwb** [comment]
It would be useful if someone could put all the pieces together and open a PR with a proposed patch.

**Comment by wsfulton** [comment]
This needs addressing and swig-4.0.0 offers an opportunity to knowingly break backwards compatibility. I propose we implement one of the ideas discussed here which addresses the fundamental problem of having the exception handling just to support 'split modules'. The solution will require the two generated modules to either exist in the same package or both must be global modules. Support for 'split modules' could be easily restored if needed using the `moduleimport` attribute in `%module`:
```swig
%module(moduleimport="import $module") mymodule
```
The default generated code will simply remove the try except block and change from:
```python
def swig_import_helper():
    import importlib
    pkg = __package__ if __package__ else __name__.rpartition('.')[0]
    mname = '.'.join((pkg, '_example')).lstrip('.')
    try:
        return importlib.import_module(mname)
    except ImportError:
        return importlib.import_module('_example')
_example = swig_import_helper()
```
to
```python
def swig_import_helper():
    import importlib
    pkg = __package__ if __package__ else __name__.rpartition('.')[0]
    mname = '.'.join((pkg, '_example')).lstrip('.')
    return importlib.import_module(mname)
_example = swig_import_helper()
```
Any objections?

**Comment by wsfulton** [comment]
I don't see a need for using `import_module` now instead of `import`. We can use simpler code instead:
```python
if __package__ or __name__.rpartition('.')[0]:
    from . import _example
else:
    import _example
```
Note that we don't use `import_module` when using `-builtin`, the code is:
```python
if __package__ or __name__.rpartition('.')[0]:
    from ._example import *
else:
    from _example import *
```

**Comment by ojwb** [comment]
Simpler sounds good if it works, and not having to import `importlib` should make modules load a bit faster.

`__name__.rfind('.') > 0` should be equivalent to `__name__.rpartition('.')[0]`, more clearly expresses what's being tested, and it's also a little faster from a quick timed tests.

**Comment by wsfulton** [comment]
Yes, good point, not importing importlib will be a bit faster. I couldn't replicate rfind being faster though. I added a 3rd option which should also be an equivalent and easily readable:
```
$ python2.7 -m timeit 'n="pkg1.mod1";x=n.rpartition(".")[0]'
10000000 loops, best of 3: 0.099 usec per loop
$ python2.7 -m timeit 'n="pkg1.mod1";x=n.rfind(".") > 0'
10000000 loops, best of 3: 0.112 usec per loop
$ python2.7 -m timeit 'n="pkg1.mod1";x="." in n[1:]'
10000000 loops, best of 3: 0.0462 usec per loop
```
Could you please try the 3rd approach on your system and check it isn't slower than the original? These microbenchmarks aren't particularly reliable, but still let's get some idea if we are to make a change based on performance.

**Comment by ojwb** [comment]
I think your benchmarking is slightly flawed.

For `n.rfind(".") > 0` you're benchmarking the entire condition that we need to check, but for `n.rpartition(".")[0]` you're not including evaluating the string result in a boolean context in the code being benchmarked.  That's not a big cost, but including that tips the balance to approximately what I saw:

```
$ python2.7 -m timeit 'n="pkg1.mod1";x = True and n.rfind(".") > 0'
10000000 loops, best of 3: 0.115 usec per loop
$ python2.7 -m timeit 'n="pkg1.mod1";x = True and n.rpartition(".")[0]'
10000000 loops, best of 3: 0.126 usec per loop
```

Your third option still wins by a significant margin (though all these times are tiny for something that's run once per module load):

```
$ python2.7 -m timeit 'n="pkg1.mod1";x = True and "." in n[1:]'
10000000 loops, best of 3: 0.0702 usec per loop
```

**Comment by wsfulton** [comment]
Yes, because it is simpler and faster and I don't believe package names can begin with a '.', see https://www.python.org/dev/peps/pep-0008/#package-and-module-names

**Comment by andreatramacere** [comment]
Hi,
I I have a problem related to this change. With swig 3.0.12 no issues, but with swig 4 The _example.so is not found (python3.7 conda3 and Mac OS 10.12.6). Actually the _example.so  is named something like "_example.cpython-37m-darwin.so", and is properly resolved only using importlib. Is there anything I am  missing?
Thanks!
