### ISSUE TITLE
[Question] How to see C++ function invocations behind the SWIG interface

### ISSUE THREAD

**Issue by ed2742** [swig/swig#855]
I'm working on TensorFlow and I want to know the relationship between each Python function and the correspondent C++ functions behind the SWIG interface. In other words, I want to be able to know exactly which C++ functions are invoked for every line of Python code of my TensorFlow application.
Is it doable?
Thank You

**Comment by ojwb** [comment]
Questions are better asked on the mailing list - many more people read that.

If you want to know statically, look at the generated wrapper code.

If you want to know dynamically, look at tools such as `ltrace`.
