### ISSUE TITLE
Java std_vector.i missing push_back

### ISSUE THREAD

**Issue by blowekamp** [swig/swig#856]
I just tried to build my library with the current swig master ( e6b270b6dc04c6719a7cd7ce7c8a38cceb55243b).  I had to update usage for JAVA's wrapped std::vector class from using the "push_back" method to the "add" method. The push_pack is missing from the generated VectorUInt32.java (etc.) files. While I haven't narrowed down the issue I think it is basically just:

%include <std_vector.i>
namespace std
{
  %template(VectorInt32) vector<int32_t>;
}

After updating a little code to the "add" method everything else for Sharp, Java, Lua, Python, R, Ruby, Tcl works for me.

Is this a known regression or compatibility issue?

Thanks!

**Comment by wsfulton** [comment]
Java has always renamed push_back to add so there is no regression here. Perhaps you were using a customised version of std_vector.i or are using something like %extend to add in push_back. Please re-open if you find a problem with SWIG itself rather than your wrappers.

**Comment by blowekamp** [comment]
There is a change in behavior  from 3.0.10 to the current swig master with Java. "add" in missing from the 3.0.10 wrapping, but push_back is there. Where as with master there is no push_back but there is an add method.

This is just from changing the swig version. I have been using this JAVA vector push_back method since before 3.0.  I am trying to narrow down a test case....

**Comment by blowekamp** [comment]
It looks like rename is required to produce the change in behavior:
```
%module java_std_vector
%rename("%(firstlowercase)s", %$isfunction ) "";

%include <std_vector.i>
namespace std
{
%template(VectorInt32) vector<int32_t>;
}
```

Thought 3.0.10 the above produced wrapping for the vector class with "push_back" and no "add", but with the current master there is **no** "push_back" but now there is the "add" method.

Looks like there may have been core change to the way multiple rename occur?

**Comment by wsfulton** [comment]
Your `%rename`:
```
%rename("%(firstlowercase)s", %$isfunction ) "";
```
is a global rename rule and was being incorrectly applied to std::vector::push_back in swig-3.0.10.  If you look in std_vector.i you will see this:
```
namespace std {    
    template<class T> class vector {
        ...
        %rename(add) push_back;
        void push_back(const value_type& x);
```
The more specific %rename changing push_back to add should have precedence over the global rename you specify. In swig-3.0.10 and earlier there was a bug where this was not the case. 7268f58c4c019353d987689d80bd22eedfbfc423 fixes this.

If you still want this method to be called push_back instead of add, you will have to add a specific override of the %rename in std_vector.i, so change your code to:
```
%module java_std_vector
%rename("%(firstlowercase)s", %$isfunction ) "";

%include <std_vector.i>
%rename("push_back") std::vector::push_back;
%rename("empty") std::vector::empty;
namespace std
{
%template(VectorInt32) vector<int32_t>;
}
```
Note that the `empty` function is normally renamed `isEmpty` in the same way. This %rename fix is specifically for templates, so you will find other STL containers that are affected and not just in Java.

**Comment by blowekamp** [comment]
Thank you for the explanation and added documentation.

**Comment by ojwb** [comment]
@wsfulton While that change is a bug fix, should we also mark it as a potential incompatibility?  It's clear it can change the behaviour of user code.

**Comment by wsfulton** [comment]
Yes, see the commit link above.

**Comment by ojwb** [comment]
Oh, sorry - I looked at the most recent entries in `CHANGES.current`, but of course this is an older one.

**Comment by balagansky-work** [comment]
> If you still want this method to be called push_back instead of add, you will have to add a specific override of the %rename in std_vector.i, so change your code to:
> 
> ```
> %module java_std_vector
> %rename("%(firstlowercase)s", %$isfunction ) "";
> 
> %include <std_vector.i>
> %rename("push_back") std::vector::push_back;
> %rename("empty") std::vector::empty;
> namespace std
> {
> %template(VectorInt32) vector<int32_t>;
> }
> ```
> 
> Note that the `empty` function is normally renamed `isEmpty` in the same way. This %rename fix is specifically for templates, so you will find other STL containers that are affected and not just in Java.

At least with 4.3.0 / with our code, that rename does not appear to work for push_back.

Instead I used `%extend` like this:

```
%extend std::vector {
  void pushBack(const value_type& x) {
    self->push_back(x);
  }
}
```

I also tried to get both empty and isEmpty, but was for some reason unable to. It's a small thing, but any ideas on how to accomplish that? Using %extend like above to define isEmpty does not work for some reason. I even tried renaming isEmpty to isEmpty.

**Comment by wsfulton** [comment]
You can add back in the old `empty` method like this:

```swig
%module java_std_vector

%include <std_vector.i>

%extend std::vector {
%proxycode %{
  // Old API
  @Deprecated
  public boolean empty() {
    return isEmpty();
  }
%}
}
namespace std
{
%template(VectorInt32) vector<int32_t>;
}
```
