### ISSUE TITLE
Inline Python Constructor Breaks for Any Object

### ISSUE THREAD

**Issue by iamtrask** [swig/swig#863]
Here's how to reproduce problem... it's a slight tweak on the Python "class" example. In short, I'm getting undefined behavior based on where I initialize my "Circle" object.
```
import example

holder = example.ShapeHolder()
circle = example.Circle(10) # initialize circle BEFORE holder method
holder.add(circle) 
shape = holder.get()
shape.area() # works fine

print(circle.thisown) # returns True
print(shape.thisown) # returns False

holder = example.ShapeHolder()
holder.add(example.Circle(10)) # initialize circle in holder method
shape = holder.get()

print(circle.thisown) # returns True
print(shape.thisown) # returns False
shape.area() # breaks <<< THIS IS THE ISSUE
```
------------------HOW TO REPRODUCE---------------------
```
/* File : example.h */

class Shape {
public:
  Shape() {
    nshapes++;
  }
  virtual ~Shape() {
    nshapes--;
  }
  double  x, y;
  void    move(double dx, double dy);
  virtual double area() = 0;
  virtual double perimeter() = 0;
  static  int nshapes;
};

class ShapeHolder {
  public:
    Shape* shape;
  void add(Shape* shape);
  Shape* get();
};

class Circle : public Shape {
private:
  double radius;
public:
  Circle(double r) : radius(r) { }
  virtual double area();
  virtual double perimeter();
};

class Square : public Shape {
private:
  double width;
public:
  Square(double w) : width(w) { }
  virtual double area();
  virtual double perimeter();
};
```

```
/* File : example.cxx */

#include "example.h"
#define M_PI 3.14159265358979323846

/* Move the shape to a new location */
void Shape::move(double dx, double dy) {
  x += dx;
  y += dy;
}

int Shape::nshapes = 0;

double Circle::area() {
  return M_PI*radius*radius;
}

double Circle::perimeter() {
  return 2*M_PI*radius;
}

double Square::area() {
  return width*width;
}

double Square::perimeter() {
  return 4*width;
}


void ShapeHolder::add(Shape* shape) {	
	this->shape = shape;
}

Shape* ShapeHolder::get() {
	return this->shape;
}
```

```
/* File : example.i */
%module example

%{
#include "example.h"
%}

/* Let's just grab the original header file here */
%include "example.h"
```

**Comment by iamtrask** [comment]
Note: when I pass by value instead of by pointer I get a different behavior

import example

holder = example.ShapeHolder()
circle = example.Circle(10) # initialize circle BEFORE holder method
holder.add(circle) 
shape = holder.get()
shape.area() # works fine

print(circle.thisown) # returns True
print(shape.thisown) # returns True

holder = example.ShapeHolder()
holder.add(example.Circle(10)) # initialize circle in holder method
shape = holder.get()

print(circle.thisown) # returns True
print(shape.thisown) # returns True
# shape.area() # breaks


-----------------REPRODUCING------------

/* File : example.cxx */

#include "example.h"
#define M_PI 3.14159265358979323846

/* Move the shape to a new location */
void Shape::move(double dx, double dy) {
  x += dx;
  y += dy;
}

int Shape::nshapes = 0;

double Circle::area() {
  return M_PI*radius*radius;
}

double Circle::perimeter() {
  return 2*M_PI*radius;
}

double Square::area() {
  return width*width;
}

double Square::perimeter() {
  return 4*width;
}


void ShapeHolder::add(Circle shape) {	
	this->shape = &shape;
}

Circle ShapeHolder::get() {
	return *this->shape;
}


/* File : example.h */

class Shape {
public:
  Shape() {
    nshapes++;
  }
  virtual ~Shape() {
    nshapes--;
  }
  double  x, y;
  void    move(double dx, double dy);
  virtual double area() = 0;
  virtual double perimeter() = 0;
  static  int nshapes;
};

class Circle : public Shape {
private:
  double radius;
public:
  Circle(double r) : radius(r) { }
  virtual double area();
  virtual double perimeter();
};

class ShapeHolder {
  public:
    Circle *shape;
  void add(Circle shape);
  Circle get();
};

class Square : public Shape {
private:
  double width;
public:
  Square(double w) : width(w) { }
  virtual double area();
  virtual double perimeter();
};

**Comment by iamtrask** [comment]
but sadly i can't pass the abstract base class by value... has to be by reference :(

**Comment by iamtrask** [comment]
I've found that this actually comes down to passing in the constructor to a method that does some sort of casting.

%inline %{
/* C++-style cast */
Shape *CircleToShape(Circle *b) {
  return dynamic_cast<Shape*>(b);
}
%}

shape = example.CircleToShape(example.Circle(10))
shape.area() # still breaks

**Comment by iamtrask** [comment]
Scratch that... no casting required... it's just when you pass the constructor into a method (as a ptr)

%{
#include "example.h"
%}
%inline %{
/* C++-style cast */
Circle *CircleToShape(Circle *b) {
  return b;
}
%}

circle = example.CircleToShape(example.Circle(10))
circle.area() # breaks

**Comment by iamtrask** [comment]
Stranger development... 

import example

c = example.CirclePtrToCircle(example.Circle(10))
c.area() # works fine

c = example.CirclePtrToCirclePtr(example.Circle(10))
c.area() # doesn't work

------- ADDITIONAL CODE TO REPRODUCE-----

/* File : example.i */
%module example

%include <pyabc.i>

%{
#include "example.h"
%}
%inline %{
/* C++-style cast */
Circle CirclePtrToCircle(Circle* b) {
  return *b;
}
Circle* CirclePtrToCirclePtr(Circle* b) {
  return b;
}
%}

/* Let's just grab the original header file here */
%include "example.h"

**Comment by ojwb** [comment]
Your comments would be much easier to read if you put "```" before and after code, as this would stop github from mangling them by interpreting punctuation as markdown formatting - I've made an edit to your most recent comment to show.

**Comment by iamtrask** [comment]
Brilliant. Will do in the future. Thank you.

**Comment by ojwb** [comment]
You need to tell SWIG to "disown" objects passed to `ShapeHolder::add()` - you can do that by using this `example.i` instead in your original example:

```
/* File : example.i */
%module example

%apply SWIGTYPE *DISOWN { Shape *shape };

%{
#include "example.h"
%}

/* Let's just grab the original header file here */
%include "example.h"
```

Note this will apply to any `Shape*` parameter named `shape`.

Then it's up to the C++ API to handle ownership of the object - in this case it doesn't and if a new object is set then the old one is leaked, but that's really a poorly designed C++ API and there's not a lot SWIG can do about that for you.

Turns out this wasn't a SWIG bug, so closing.
