### ISSUE TITLE
Java requires objects in vector to be default constructable (C# doesn't)

### ISSUE THREAD

**Issue by RatanRSur** [swig/swig#866]
So I'm generating C# and Java bindings for a C++ project and when compiling the Java wrapper, I run into a problem that I don't for the C# wrapper, namely, that, the fill constructor complains there is no default constructor for CustomType.

Here is why I believe this is happening:

For the `newblahblahCustomType(int x)` the C# generated wrapper calls the default vector constructor followed by `reserve`, whereas the Java generated wrapper calls the fill constructor.

Is there a reason for this difference in behavior?

**Comment by wsfulton** [comment]
This isn't clear what the problem is. You mention the Java wrappers fail because there is no default constructor, but you say the C# generated wrapper calls the default constructor. Please post a minimal example of the problem, it probably isn't going to be more than a handful of lines.

**Comment by ojwb** [comment]
@wsfulton "the C# generated wrapper calls the default **vector** constructor" (my emphasis)

If I follow, the code generated for Java requires the objects in the vector to be default constructable while the code generated for C# avoids this requirement.

But as usual, a reproducer would make it clearer what the issue is, and make it easier for someone to investigate.

**Comment by RatanRSur** [comment]
Yes @ojwb , that is what I meant. Repro:

CustomClass.cpp:
```
class CustomClass{
    private:
        CustomClass();
};
```

CustomClass.i:
```
%module CustomClass
%include <std_vector.i>
%template(CustomClassVector) std::vector<CustomClass>;
```

Swig commands:
`swig -c++ -csharp -o cs_wrap.cxx CustomClass.i`
`swig -c++ -java -o java_wrap.cxx CustomClass.i`

Relevant section from cs_wrap.cxx:
```
SWIGINTERN std::vector< CustomClass > *new_std_vector_Sl_CustomClass_Sg___SWIG_2(int capacity){
        std::vector< CustomClass >* pv = 0;
        if (capacity >= 0) {
          pv = new std::vector< CustomClass >();
          pv->reserve(capacity);
       } else {
          throw std::out_of_range("capacity");
       }
       return pv;
      }
```

Relevant section from java_wrap.cxx:
```
SWIGEXPORT jlong JNICALL Java_CustomClassJNI_new_1CustomClassVector_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  std::vector< CustomClass >::size_type arg1 ;
  std::vector< CustomClass > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (std::vector< CustomClass >::size_type)jarg1; 
  result = (std::vector< CustomClass > *)new std::vector< CustomClass >(arg1);
  *(std::vector< CustomClass > **)&jresult = result; 
  return jresult;
}
```

**Comment by RatanRSur** [comment]
any update on this?

**Comment by wsfulton** [comment]
The std::vector constructors you are looking at for C# and Java are doing different things, so they are not equivalent.

They are different as C# is is trying to provide wrappers that are more a natural fit in the target language and not a perfect one to one mapping of the std::vector API.

You can solve this problem by just ignoring the vector constructor that cannot be called for CustomClass:
```swig
%ignore std::vector<CustomClass>::vector(size_type);
```

**Comment by RatanRSur** [comment]
Ok, thanks!
