### ISSUE TITLE
CFFI multiple constructors

### ISSUE THREAD

**Issue by gitfoxi** [swig/swig#868]
If a class has multiple constructors, it will `defcfun` them all with the same lisp name. This screws up the CLOS definitions also.

```
(cffi:defcfun ("_wrap_ARRAY_COMPLEX_init__SWIG_0" ARRAY_COMPLEX_init) :void
  (self :pointer)
  (arg1 :pointer))

(cffi:defcfun ("_wrap_ARRAY_COMPLEX_init__SWIG_1" ARRAY_COMPLEX_init) :void
  (self :pointer))
```

**Comment by ojwb** [comment]
I don't think we have an active maintainer for the CFFI backend currently, but if you can provide clean patches with suitable testcases to address this and the other issues, we should be able to get them applied.

**Comment by gitfoxi** [comment]
I notice this problem affects all overloaded functions as well.

**Comment by wsfulton** [comment]
Closing all open CFFI issues as CFFI has been disabled, please see #1447.
