### ISSUE TITLE
Incomplete/unflushed output files when SWIG is used as distributed tool of Incredibuild 

### ISSUE THREAD

**Issue by pjohangustavsson** [swig/swig#881]
Note: I am not entirely sure if this is the fault of Incredibuild or SWIG itself,  the main reason I'm submitting the issue herehowever  is because it's easiest to fix by modifying the SWIG source code by adding one line, whereas it's very probable the hooks Incredibuild use to host distributed processes needs structural adjustments with side-effects only they know the vastness of. I beg you to judge the issue accordingly. 

By using Incredibuild with the appropriate license for the task, we accelerate all our builds of both C/C++ code and execution of SWIG across our local network. Happening only when SWIG generates wrapper code this way, some of the generated files are sent back to the initiator machine either as empty files or incomplete, as if it happens before any final flushs can happen. This only happens about one in twenty builds, but due to the many frequent rebuilds we do it really adds up and causes otherwise stable branches and trunk become falsely unstable. 

I discovered a simple fix for this issue by adding a `std::this_thread::sleep(200ms)` right before SWIG's main function returns, hinting at Incredibuild's placement of it's hook for an exit handler for distributed processes (not verified), causing files to be fetched before the OS itself ends the process and flushes any file buffers. Other tools not included in Incredibuild's list of supported tools do not have this issue.

Should we discuss this tricky to reproduce issue and what could be done? The relevancy of this issue is up to you devs to judge.

**Comment by ojwb** [comment]
This doesn't sound like an appropriate hack to inflict on all SWIG users.  I certainly don't want to have to wait an extra 0.2 seconds every time I run SWIG for no good reason - a full testsuite run is already slow enough. without taking that much extra time for every testcase for every language being tested.

Also the code you suggest requires C++11, and SWIG doesn't currently require C++11 support.

**Comment by wsfulton** [comment]
This really is an Incredibuild problem. As SWIG is open source, they can download it and replicate your setup. About 10 years ago I distributed SWIG using Incredibuild and didn't have this problem. The distribution is meant to work with any executable, so I suggest you send them the Build Monitor (.ib_mon) file with Logging level set to Detailed. If you can turn off or change your virus checkers, I'd try that too as they cause no end of problems with their tentacles into the operating system file calls.

But I agree with @ojwb that adding in a randomly chosen delay on exit isn't something that we'll accept. I suggest you put in this kind of workaround by writing a simple wrapper program or script that invokes swig then delays before exiting if you can't get Incredibuild to fix it.

I'm closing, but if you get any updates, please post back.
