### ISSUE TITLE
SWIG on Windows fails with unclear message if generated paths are too long 

### ISSUE THREAD

**Issue by a-betenev** [swig/swig#882]
When SWIG generates default type wrappers (SWIGTYPE_p_...) for complex C++ templates, the name of the resulting wrapper class can become quite long. Together with path to the current folder the full file name can exceed the limit of Windows file system (~ 260 symbols). The error message produced by SWIG in this case is confusing:

"Unable to open file : No such file or directory"

The problem is reproduced for CSharp target on Windows 7 and 10, with swigwin-3.0.6, 3.0.7, and 3.0.11. 
To reproduce, use simplified synthetic environment:

1. In command prompt, create folder with long name:

> cd /d c:\
c:\> md  0_________10________20________30________40________50________60________70________80________90________100_______110_______120_______130_______140_______150_______160_______170_______180_______190_______200_______210_______220_______230_______

2. Put example.i from SWIG tutorial (http://www.swig.org/tutorial.html) to that folder

3. Run SWIG:

c:\0_________10________20________30________40________50________60________70________80________90________100_______110_______120_______130_______140_______150_______160_______170_______180_______190_______200_______210_______220_______230_______> c:\swigwin-3.0.11\swig.exe -csharp example.i
Unable to open file : No such file or directory

At minimum, error message shall be improved to help the user to spot the problem. Perhaps some alternative functions can be used to access files (e.g. page https://msdn.microsoft.com/ru-ru/library/windows/desktop/aa365247(v=vs.85).aspx mentions Unicode versions of WinAPI functions that allow paths up to 32,767 characters).

**Comment by wsfulton** [comment]
Locations that will need to be patched using a non-standard file open command are:
```
~/swig/github/swig (master=)$ grep fopen -r -w Source/ 
Source/DOH/file.c:  file = fopen(filen, mode);
Source/Swig/include.c:  f = fopen(Char(filename), "r");
Source/Swig/include.c:      f = fopen(Char(filename), "r");
```
Patches welcome, but must be portable and work with older versions of Windows too (say Windows XP). There may be other file i/o functions, but those are the main ones and there are more in the CCache directory for ccache-swig.

**Comment by a-betenev** [comment]
I believe the first-level problem is on line 686 in csharp.cxx: there NULL (file pointer) is passed to error reporting macro FileErrorDisplay() instead of file name. The fix should be straightforward:

~~~~~
diff --git a/Source/Modules/csharp.cxx b/Source/Modules/csharp.cxx
index 9cc6d60..423c5a4 100644
--- a/Source/Modules/csharp.cxx
+++ b/Source/Modules/csharp.cxx
@@ -683,7 +683,7 @@ public:
       String *filen = NewStringf("%s%s.cs", dir, name);
       File *f = NewFile(filen, "w", SWIG_output_files());
       if (!f) {
-	FileErrorDisplay(f);
+	FileErrorDisplay(filen);
 	SWIG_exit(EXIT_FAILURE);
       }
       Append(filenames_list, Copy(filen));
~~~~~

**Comment by wsfulton** [comment]
I see, I'll apply this shortly as a last minute addition to swig-3.0.12, which is due for release today. If you provide me your email address in the next hour I'll commit it using your name. FileErrorDisplay is used a lot, but this is the only instance of this bug that I could see.

**Comment by a-betenev** [comment]
Sorry for late reply -- it would be great to see the fix in the new version! no real need to use my name.

**Comment by wsfulton** [comment]
I've closed this, but patches as mentioned earlier are welcome in a new pull request.

**Comment by SamuelEnglard** [comment]
Adding the manifest as shown in https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#enable-long-paths-in-windows-10-version-1607-and-later should allow SWIG to support long paths on newer versions of Windows without needing to change any code

**Comment by a-betenev** [comment]
Interesting, thank you for sharing this

**Comment by wsfulton** [comment]
If someone wants to add in a manifest to the build system for Windows, we can add `longPathAware` to it.
