### ISSUE TITLE
Inability to generate raw string literals for Python docstrings

### ISSUE THREAD

**Issue by glowthrower** [swig/swig#889]
Although the Python docstring functionality in SWIG is generally
pretty good, it seems to be lacking the ability to emit docstrings as
raw string literals. This is a problem for me, because I want to be
able to produce RST-formatted docstrings that can be used by the
sphinx tool, and in particular, I want to use the `:math:`
functionality of RST to embed LaTeX in my documentation. (I feel that
this is probably useful functionality for other people as well,
particularly those working in research or scientific fields.)

For example, consider the following desired output (only the docstring
is interesting):

```
def foo(rho, x):
    r"""Calculate :math:`D^\nu \rho(x)`."""
    return True
```

The use of a raw string literal is necessary to avoid having the `\n`
and `\r` interpreted as escape characters during generation of sphinx
documentation. There does not appear to be any way to produce such
output using SWIG.

In fact, it's a bit fiddly even to get SWIG to output the docstring
with the forward slashes as intended, even in the case of standard
string literals. Consider the following SWIG interface definition,
which attempts to attach the given docstring to four symbols:

```
%module docstringTest

%{
#define SWIG_FILE_WITH_INIT
void func0(double* foo, int bar, char** baz);
void func1(double* foo, int bar, char** baz);
void func2(double* foo, int bar, char** baz);
void func3(double* foo, int bar, char** baz);
%}

%feature("docstring") func0 {Calculate :math:`D^\nu \rho(x)`.};
void func0(double* foo, int bar, char** baz);

%feature("docstring") func1 %{Calculate :math:`D^\nu \rho(x)`.%};
void func1(double* foo, int bar, char** baz);

%feature("docstring") func2 "Calculate :math:`D^\nu \rho(x)`.";
void func2(double* foo, int bar, char** baz);

%feature("docstring", "Calculate :math:`D^\nu \rho(x)`.") func3;
void func3(double* foo, int bar, char** baz);
```

Of these four, only the first two emit docstrings in the generated
Python code that retain the forward slashes unescaped. (On my Mac, at
least.)

I've done a bit of poking through the code, and I have a couple of
ideas for how this functionality could be added in a tidy way while
maintaining backwards compatibility (although I don't think I can fix
the mangling of the forward slashes during parsing of the .i file --
but I'd be happy to be wrong!). I'm more than happy to do this and and
submit a pull request, but before I go and throw time at it, I wanted
to see if maybe I was missing something or making an obvious error.

(I've also noticed a couple of slight inconsistencies with produced
docstrings and PEP257, which I think I can tidy up as well.)

**Comment by vadz** [comment]
Sorry, I don't have time to test this myself now, but at least some docstrings are now generated as raw Python strings in the doxygen branch of SWIG, see #170. So it might be worth checking if things are any different (and hopefully better) there.

**Comment by wsfulton** [comment]
Checking the doxygen branch is a good idea, it'll be interesting to see how/if it handles this. If no good, I propose we use C++11 raw string literals which are specifically there to help with escaping problems and it is an equivalent feature to the Python raw string literal. It should convert the string into an escaped C string into the generated C/C++ code where needed for full compatibility with C and C++ prior to C++11, and a raw python string literal for the Python pydoc code. I think it should only be triggered when a C++11 raw string literal is detected and not when a {} or %{ %} brace is used for the string for full backwards compatibility.

There are fixes required, currently:
```swig
%feature("docstring") func2 R"(Calculate :math:`D^\nu \rho(x)`.)"
void func2(double* foo, int bar, char** baz);
```
generates into the .py file:
```python
def func2(foo, bar, baz):
    """(Calculate :math:`D^\nu \rho(x)`.)""""
    return _example.func2(foo, bar, baz)
```
and the C/C++ wrapper file:
```c++
	 { (char *)"func2", _wrap_func2, METH_VARARGS, (char *)"(Calculate :math:`D^\\nu \\rho(x)`.)\""},
```
The leading and trailing brackets and trailing " need to be zapped and the Python layer requires a leading `r` to be added.

PEP257 fixes are also useful, but please put in separate patch. We run pep8 in the test-suite already if it is installed, so I presume any tests for your fixes should be found by pep8.

**Comment by glowthrower** [comment]
Thanks for the tips!

vadz is correct: the `doxygen` branch can indeed produce raw literals for docstrings. It actually does this (if I'm reading the code correctly) for literally every docstring, regardless of whether or not the `-doxygen` flag has been given on the command line.

There seem to be two particularly relevant commits in the `doxygen` branch. The first is 29d1bba70a, which is where the raw string literal output (and some relevant testing) was first added. The second is 16548cced0, which tidies up the docstring code a little.

This functionality seems to have been added almost as a side-note in that branch, and the logic is deeply intertwined with the doxygen functionality. Although the switch to all-raw, all-the-time seems to have been made on the (sound) basis that doxygen comments very often include forward slashes, I do wonder if it might be considered to break backwards compatibility and should only have been done when the `-doxygen` flag was enabled... Perhaps there are corner cases where the user does NOT want a raw string literal. (Perhaps something to do with Unicode?)

Anyway, this means that, if I use the `doxygen` branch and either of the `{}` or `%{%}` input forms in my `.i` files, I can get what I want. (The standard string literal input forms still behave badly, and that makes sense.) However, it seems unclear when, or indeed if the `doxygen` branch will be merged with `master`. It doesn't feel like a great solution for me to switch over to using a stale branch and fall behind `master`.

Can I suggest that I try and integrate similar functionality directly into `master` as a distinct patch? I could try and cherry-pick from `doxygen`, but it would be messy -- as mentioned, the code there really is tied to the doxygen functionality.

I like the idea of mapping C++11 raw string literals to raw docstrings — it seems like a clean solution, and I don't like using `{}` and `%{%}` delimited literals anyway (they confuse my editor!). But it's not really clear to me how to nicely detect a raw string literal in the Python module code -- the output from, e.g. `-debug-module 4` suggests that it will have already been parsed into a `String` by that stage, and the only distinguishing features are the leading/trailing parentheses and the extra `\"` at the end. (I could use those as an indicator, of course, but it feels hacky.) Is there something obvious I'm missing?

(Also, I’ve noticed from playing around that the parser is very finicky about raw string literals. If I run SWIG over an interface file containing, say, an unterminated standard string literal, I get a nice error message telling me what happened. If I include a broken raw string literal — for example, `R”(Missing trailing parenthesis”` — then I just get a segfault. Is this worth opening a separate issue over?)

**Comment by vadz** [comment]
FWIW I disagree that the string syntax used in SWIG code should determine the syntax used in Python. The contents of the string literal should be preserved, whatever it is, and however it's expressed, be it `"\\rho"` or `R("\rho")`.

And -- sorry in advance for my traditional "Carthago delenda est" plea, William -- I'd also like to note that any changes to the docstring generation would almost inevitably result in non-trivial conflicts with the Doxygen branch, so it would be nice to postpone doing them until after the merge.

**Comment by wsfulton** [comment]
I've fixed the seg fault for unterminated raw strings in dee6b075a83468bacb39a1d9970d2c65f3e68d9b. While C++11 raw strings are supported in a few obvious use cases, they need further work. A raw string should 'just work' when writing out the python docstring. I'm not sure what is required to fix them, such as the final `\"` without taking a good look. 

@vadz, I agree that any valid C/C++ string (raw strings or traditional) should be suitably escaped in the python doc. The raw strings are, as they were intended to be, an easier form to write strings with backslashes in and would be a good option to write docstrings for SWIG users, but not a mandatory approach to writing docstring with escape characters.

If the doxygen branch is not backwards compatible, that is okay if it is fixing bugs. However, if it is misinterpreting the C string as something other than a C string when creating the docstring, then this would be a bug as the SWIG parser parses C strings as C strings.

**Comment by wsfulton** [comment]
@glowthrower, if you want to use the doxygen approach, I don't suggest you try and cherry pick it and merge into 3.0.x versions, but rather work on the doxygen branch. If you want code that is officially released sooner, I suggest minimal changes to master for the next 3.0.x version. However, it is my intention, to try and garner development and developers to work on a 3.1 version based on the doxygen branch. I'd like to make it my main focus in the near future, but I can't tell how long this will take to make an official release though. I'll post something on the swig-devel mailing list soon.

**Comment by vadz** [comment]
@wsfulton I'll try to take a look, this change did seem suspicious to me when I first saw it, but I don't remember the details and whether I did anything about it or not.

**Comment by ojwb** [comment]
@glowthrower BTW, I think you have slash direction confused - `\` is a backward slash, `/` is a forward slash...

**Comment by jschueller** [comment]
as #170 has been merged, maybe we could close this

**Comment by vadz** [comment]
Yes, I think this one can be closed. The problem of the change in Doxygen branch being incompatible already has its own issue #1273.
