### ISSUE TITLE
SWIG_Python_ConvertFunctionPtr: dead code

### ISSUE THREAD

**Issue by srepmub** [swig/swig#892]
coverity notes that the 'if (ty)' condition is always true, so the code under 'else' is logically dead.

I guess if 'ty' is 0, then 'desc' becomes 0, and we will return SWIG_ERROR. so 'ty' cannot be 0 further down.

**Comment by srepmub** [comment]
here's a patch for this. hope it's fine as is:

https://gist.github.com/srepmub/184b74150178b171893196bf9638643c

**Comment by ojwb** [comment]
Please open a PR.

**Comment by srepmub** [comment]
https://github.com/swig/swig/pull/899

**Comment by ojwb** [comment]
#899 merged, closing.  Thanks.
