### ISSUE TITLE
Scilab: Use of ":" with typemap (int* IN, int IN_SIZE)

### ISSUE THREAD

**Issue by rdbyk** [swig/swig#894]
For an ":" input, one gets IN_SIZE=1,
IMHO it should be IN_SIZE=-1, so that within a
wrapped function the usage of ":" can be detected.

**Comment by wsfulton** [comment]
This doesn't make any sense to me. Can you demonstrate whatever the problem is with an example? @smarchetto, maybe this makes sense to you in a Scilab context?

**Comment by rdbyk** [comment]
It makes only sense in a Scilab context, e.g.

%include <matrix.i>
SYM* func(SYM* a, int* IN, int IN_SIZE)

is used to wrap a "func" that takes within Scilab two inputs: "a" and a vector of integers (int* IN, int IN_SIZE). It is quite common to interpret a vector of integers as element indices of another object,
i.e. for some extraction or insertion operation. Scilab provides a shorthand ":" to specify all elements
of an object. Using the predefined typemap (int* IN, int IN_SIZE) it is currently not possible to detect
whether "func" was called in Scilab with a ":" input argument, cf. below

func(a, [1,2,3]) // => IN_SIZE = 3  // Ok
func(a, [1])       // => IN_SIZE = 1  // Ok
func(a, [])         // => IN_SIZE = 0  // Ok
func(a, :)          // => IN_SIZE = 1  // Not Ok!

**Comment by smarchetto** [comment]
`func(a, :)` is not correct syntaxically (how can we be sure the operator `:` applies on `a` ?) Correct syntax is `func(a(:))`. See the [colon](https://help.scilab.org/doc/5.5.2/en_US/colon.html) help page for more details.

I didn't test it but I am quite sure the mapping works here, with INT_SIZE equals to the size of the a.

**Comment by rdbyk** [comment]
Ok, so lets look at the thing from a slightly different angle, suppose you want to implement an extraction
operation for an object of type "T" and you want to overoad Scilab's extraction operation A(i), afaik one
has to implement funtion "%T_e_(i,a)", now let's assume that this function calls func(a,i) ...

Anyway, if "func(a,:)" is not syntactically correct, as you say, then this should be detected, what do you think?  Either automatically by the code behind the typmap (int* IN, int IN_SIZE) or as I suggested this detection should be made possible (e.g. by setting IN_SIZE=-1 in case of a ":" argument) and left to the implementor of "func", so he can decide what to do in case of ":" arguments.

One last remark, the typemap (int* IN, int IN_SIZE) reports IN_SIZE=1 for a ":" argument, so is 1 the
correct length of ":"? I think it wouldn't hurt or break anything to report IN_SIZE=-1 for a ":" argument.

**Comment by smarchetto** [comment]
Well, your syntax is indeed correct. I don't really see the purpose of evaluating the `:` operator (on a variable) "later", but it is used in the case of the overloading of the extraction.
It seems we have an issue here if `IN_SIZE` equals 1 in such situation. Maybe this issue affects only Scilab 5 and not Scilab 6, I will check all this, thanks for reporting.

**Comment by rdbyk** [comment]
FYI, I experienced this using Scilab 5.

In the typemap (int* IN, int IN_SIZE) you'll find "$2 = rowCount * colCount;".
For a ":" argument  rowCount and colCount are both set properly to "-1", which leads to
IN_SIZE = (-1)*(-1) = 1.

Thanks in advance for looking at this.

**Comment by ojwb** [comment]
@smarchetto Did you get a chance to check into this?

**Comment by ojwb** [comment]
@davidcl Perhaps you could take a look at this?  I think it really needs someone with specific scilab knowledge.

**Comment by davidcl** [comment]
I will take a look. FYI there is some internal types representing this `:` value ; mapping them might be useful.
