### ISSUE TITLE
converity: PyTuple_Check(args) dereferences args, but args is NULL checked later

### ISSUE THREAD

**Issue by srepmub** [swig/swig#896]
the following patch makes sure that the 'PyTuple_Check(args)' does not derefence 'args' before the subsequent NULL check:

https://gist.github.com/srepmub/003ad31170991ff69be0cc5a3bd51ab5

**Comment by ojwb** [comment]
Please open a PR.

**Comment by srepmub** [comment]
https://github.com/swig/swig/pull/901

**Comment by ojwb** [comment]
Thanks - PR was merged long ago so closing.
