### ISSUE TITLE
[cpp11] Parser does not support 'throw(.*) override|final' - Error: Syntax error in input(3)

### ISSUE THREAD

**Issue by assambar** [swig/swig#905]
Say we have the following in a Foo.h, which we included in Foo.i

      07 class Foo : public Bar {
      ...
      15       Foo GetFoo() throw (Foo::BarException) override;

Parsing the .i file would fail with
`Foo.h:15: Error: Syntax error in input(3).`

--

**Workaround** (e.g. with python):
Add -Doverride and -Dfinal to the swig commandline
`swig -py3 -c++ -python -w503 -Ifoo/include -DSWIG_64 -D__GNUC__=4 -Doverride -Dfinal -outdir 'build/foo_py' -o 'foo_py_wrap.cpp' 'foo/foo.i`

--

**Suggested Fix**
The problem is in the definition of `exception_specification` in `Source/CParse/parser.y`
It does not contain the said case, but this should add it:

               | THROW LPAREN parms RPAREN virt_specifier_seq {
                          $$.throws = $3;
                          $$.throwf = NewString("1");
                          $$.nexcept = 0;
               }

Here is a sample diff:
[samplefix.txt](https://github.com/swig/swig/files/781104/samplefix.txt)

**Comment by ojwb** [comment]
"samplefix.txt" seems to be empty!

But anyway please open a PR (pull request) for your proposed patch - then it'll get automatically tested for most supported target languages on 3 platforms. If you just give us a patch file, we'd have to do all that testing by hand before we can be confident about merging.

It would be good to include a testcase which exercises this, to make sure the fix doesn't regress in the future.

**Comment by assambar** [comment]
Cool. Will do that early next week.
Thanks!

**Comment by assambar** [comment]
Done - [https://github.com/swig/swig/pull/908](https://github.com/swig/swig/pull/908)
