### ISSUE TITLE
Travis job SWIGLANG=ocaml not running

### ISSUE THREAD

**Issue by kwwette** [swig/swig#912]
I noticed when looking at #909 that the Travis job `SWIGLANG=ocaml` is not actually running. From https://docs.travis-ci.com/user/customizing-the-build#Rows-that-are-Allowed-to-Fail it looks like jobs must be included both in `matrix` and in `allow_failures`, as is the case for the `SWIGLANG=python SWIG_FEATURES=-O job`. The `SWIGLANG=ocaml` is only listed in `allow_failures`, and therefore isn't actually run. Just wanted to flag this in case that wasn't the intention.

**Comment by ojwb** [comment]
Looks like my fault when I first added it, will fix.
