### ISSUE TITLE
const std::string is incorrectly generating string constants

### ISSUE THREAD

**Issue by eddielong** [swig/swig#913]
We don't want to have function calls and just constants defined on the Java side. To achieve this we do:

```
#ifdef SWIG
#define const %constant
#endif

const std::string MY_STRING = "";
const std::string MY_STRING_2 = "OK";

#ifdef SWIG
#undef const
#endif
```

Running swig this generates in Java:

```
public final static String MY_STRING = \0;
public final static String MY_STRING_2 = OK;
```

I would expect to get the right strings created in Java.

**Comment by ojwb** [comment]
What version of SWIG are you using?

And did this work in older versions of SWIG?  I wonder if this could be fall-out from #781 which was merged in 3.0.11.

The example you give is incomplete, so I can't easily check for myself.

**Comment by eddielong** [comment]
I've attached a zip with a .i file and output files. 

[std__string_issue.zip](https://github.com/swig/swig/files/807449/std__string_issue.zip)

Swig config:

SWIG Version 3.0.12

Compiled with clang++ [x86_64-apple-darwin16.3.0]

Configured options: +pcre

**Comment by ricardolyn** [comment]
I can confirm that is happening the same to me on version 3.0.12

**Comment by ojwb** [comment]
Anyone care to answer my other question?

> And did this work in older versions of SWIG? I wonder if this could be fall-out from #781 which was merged in 3.0.11.

**Comment by eddielong** [comment]
I'm new to swig, this is the only version I've attempted.

**Comment by ricardolyn** [comment]
@ojwb I don't know if this issue happens on older versions

**Comment by ojwb** [comment]
I tested with 3.0.10 (more precisely, Debian package version 3.0.10-1.1 which may have extra patches), and that also gives output missing the quotes.  Not sure where that's going wrong, but it seems it isn't fall-out from #781.

**Comment by ojwb** [comment]
With SWIG 4.0.2 and git master, the generated output is now:

```
  public final static String MY_STRING = testJNI.MY_STRING_get();
  public final static String MY_STRING_2 = testJNI.MY_STRING_2_get();
```

so the issue reported here has been addressed.  I'm not sure exactly when.

Adding `%javaconst(1);` to the testcase reinstates the bad output, but we have #1907 open for that issue.
