### ISSUE TITLE
compilation fails on OS Yosemite with "suffix or operands invalid for `movq'"

### ISSUE THREAD

**Issue by sarblyth** [swig/swig#915]
Hi,
I have tried to install and compile SWIG according to the instructions (Mac OS 10.10.2 Yosemite). 
I've made sure to upgrade my Xtools via the App store,
then:
>> brew install git automake pcre boost
(I left out the Lua and Guile stuff as I don't need those)
I then tried to compile as:
$ ./autogen.sh
 $ ./configure ----with-php=no --with-php5=no --without-php --without-php5
 $ make
(I don't need the php stuff) but get the following error (it's the same error whether configure with the flags or without the flags above):

g++ -DHAVE_CONFIG_H   -I../Source/Include -I../Source/CParse -I../Source/Include -I../Source/DOH -I../Source/CParse -I../Source/Preprocessor -I../Source/Swig -I../Source/Modules -I/usr/local/Cellar/pcre/8.39/include  -g -O2 -Wall -W -ansi -pedantic -MT Modules/php.o -MD -MP -MF $depbase.Tpo -c -o Modules/php.o Modules/php.cxx &&\
	mv -f $depbase.Tpo $depbase.Po
/var/folders/_5/tgb877j14s73szw5g1_x815w0000gn/T//ccnyPqzJ.s:7034:suffix or operands invalid for `movq'
/var/folders/_5/tgb877j14s73szw5g1_x815w0000gn/T//ccnyPqzJ.s:7086:suffix or operands invalid for `movq'
make[2]: *** [Modules/php.o] Error 1
make[1]: *** [all] Error 2
make: *** [source] Error 2

Any suggestions on how to get around this would be very welcome!
Thanks
Sarah

**Comment by ojwb** [comment]
> `----with-php=no --with-php5=no --without-php --without-php5`

`----with-php=no` isn't a valid option.  Also, `--with-php5=no` and ` --without-php5` should be entirely equivalent.

This looks like a toolchain bug to me - there's no assembler code in SWIG, so the compiler seems to be producing code which the assembler doesn't understand.

What's the output of:

```
which g++
g++ --version
```

I thought that on OS X, `g++` was actually clang these days, but I also thought clang produced object files directly rather than generating a temporary file of assembler code.

**Comment by sarblyth** [comment]
I get the following:

>>which g++
/usr/local/bin/g++

>>g++ --version
g++ (GCC) 6.2.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by vadz** [comment]
You're clearly using a non-Apple build of g++ which seems to be buggy. The most obvious solution is to stop using it and just use the default system compiler (clang). If you do absolutely want to use gcc, it's possible too, of course, but it's up to you to find a working binary or build it yourself.

In any case, this really doesn't have anything to do with SWIG, so closing.

**Comment by ojwb** [comment]
GCC and clang should both work in general, but there does indeed seem to be something amiss with your build of GCC and/or the assembler it's using.

You can specify a particular compiler to use when configuring SWIG like so:

```
./configure CXX=/usr/bin/clang++ CC=/usr/bin/clang
```

**Comment by sarblyth** [comment]
Thank you so much for pointing this out. I tried explicitly making clang the compiler as you suggested and it worked! Much appreciated!
