### ISSUE TITLE
Swig fails to deal w/"static" or "const * const"

### ISSUE THREAD

**Issue by stevemadsenblippar** [swig/swig#936]
Swig version: 3.0.12

Very simple: want a string literal defined in single place which can be accessed from
both C++ and Java; as noted in issue https://github.com/swig/swig/issues/913
`std::string` is a poor choice since quotes are stripped, so using `char *` instead.

Would hope something like this would work:

`     #ifdef SWIG`
`    #define const %constant`
`    #endif`
`    static const char * const MyConstStrA = "aaa_";`
`    static const char * const MyConstStrB = "bbb_";`
`#ifdef SWIG`
`#undef const`
`#endif`

but swig can't deal with second `const` and will fail with e.g.
`MyHeader.hpp:NN: Warning 305: Bad constant value (ignored).`
If `static` keyword is used (with or without second `const`) swig error will be e.g.
`MyHeader.hpp:NN: Error: Syntax error in input(1).`

Unfortunately if we remove those to allow swig to parse the input e.g.
`#ifdef SWIG`
`#define const %constant`
`#endif`
`    const char * MyConstStrA = "aaa_";`
`    const char * MyConstStrB = "bbb_";`
`#ifdef SWIG`
`#undef const`
`#endif`

swig will parse flawlessly, but then clang will fail to build due to multiple definition error.

**Comment by ojwb** [comment]
I don't think this is a bug - with your `#define const %constant` you get:

```
static %constant char * %constant MyConstStrA = "aaa_";
```

And that's clearly not valid.
