### ISSUE TITLE
Upgrading swig 2.08 to swig 3.0.12 error

### ISSUE THREAD

**Issue by dalgos-adsk** [swig/swig#941]
Hello,

So sorry if this is a newb question, but I am stuck on this for a while now, hopefully this is an easy thing for any of your guys. 
We are trying to upgrade from 2.0.8 to 3.0.12. Python API went fine, but now the c# one is giving me issues. Unfortunately, I need to be integrating this on someone else's work, and its very cryptic for me. 
In one of our .i files, we have the following line :
 
```
%define EVENT_CLEANUP_REGISTER(CLASS)
%typemap(cscode) MMessage_BEFORE_CLEANUP_REGISTER ## CLASS = MMessage;
%typemap(cscode) MMessage %{
	$typemap(cscode, MMessage_BEFORE_CLEANUP_REGISTER ## CLASS)
	private static System.Collections.Generic.Dictionary<Assembly, MMessage> _ ## CLASS ## Map;
    internal static System.Collections.Generic.Dictionary<Assembly, MMessage> CLASS ## Map
    {
        get 
        {
            if (_ ## CLASS ## Map == null)
            {
                _ ## CLASS ## Map = new System.Collections.Generic.Dictionary<Assembly, MMessage>();
                MMessageManager.Add(typeof(CLASS), _ ## CLASS ## Map);
            }

            return _ ## CLASS ## Map;
        }
    }
%}
%typemap(cscode) CLASS ## _BEFORE_CLEANUP_REGISTER = CLASS;
%typemap(cscode) CLASS %{
	$typemap(cscode, CLASS ## _BEFORE_CLEANUP_REGISTER)
	private System.Collections.Generic.List<IDisposable> evtDisposeList = new System.Collections.Generic.List<IDisposable>();
%}
%typemap(csimports) CLASS ## _IMPORTS_BEFORE_CLEANUP_REGISTER = SWIGTYPE;
%typemap(csimports) CLASS %{
	$typemap(csimports, CLASS ## _IMPORTS_BEFORE_CLEANUP_REGISTER)
	using System.Reflection;
%}
...
%enddef
```
Everything worked fine in 2.0.8, although now upgrading to 3.0.12 is giving me the following error :
`error : Can't copy typemap (csimports) SWIGTYPE = MLockMessage_IMPORTS_BEFORE_CLEANUP_REGISTER`

Looks like the issue is happening on this line :

`%typemap(csimports) CLASS ## _IMPORTS_BEFORE_CLEANUP_REGISTER = SWIGTYPE;
`

Why is this failing now in 3.0.12. Also what was the previous developer trying to do here  ?
Thanks in advance for the help :)

**Comment by wsfulton** [comment]
In 2.0.8, there is a "csimports" typemap for SWIGTYPE:
https://github.com/swig/swig/blob/8f16b81a4fb03bb66fb96e030559afdc852629c1/Lib/csharp/csharp.swg#L818
In 3.0.12, this typemap no longer exists because those imports are no longer required as the C# types are fully qualified. Assuming your code base doesn't override the "csimports" typemap for SWIGTYPE, the fix is to just remove the lines, shown as commented out instead:
```swig
// %typemap(csimports) CLASS ## _IMPORTS_BEFORE_CLEANUP_REGISTER = SWIGTYPE;
%typemap(csimports) CLASS %{
	// $typemap(csimports, CLASS ## _IMPORTS_BEFORE_CLEANUP_REGISTER)
	using System.Reflection;
%}
```
Or if you like, define a "csimports" typemap for SWIGTYPE to do nothing and then leave the code in the EVENT_CLEANUP_REGISTER macro as is.
