### ISSUE TITLE
Invalid Metadata File

### ISSUE THREAD

**Issue by novamahend** [swig/swig#946]
I want to use SWIG to wrap my dynamic library written in C++ to be used in C#. I've followed this tutorial (http://www.swig.org/tutorial.html), then I got my .so dynamic library.

I use mono in Raspberry Pi 3 to compile my .cs sourcecode : 
gmcs /reference:libTestSwigLib.so Test.cs
 I got this error:
error CS0009: Metadata file `/home/pi/projects/TestSwig/libTestSwigLib.so' does not contain valid metadata
Compilation failed: 1 error(s), 0 warnings

May you can help my problem. Thankyou.

**Comment by wsfulton** [comment]
Sounds like a build problem peculiar to your environment. Not a SWIG issue.
