### ISSUE TITLE
Python: Typemap not applied to polymorphic function's arguments

### ISSUE THREAD

**Issue by dvdkon** [swig/swig#954]
Polymorphic functions and typemaps both work by themselves, but not when combined. `return_int` is a polymorphic function using no custom typemaps, `print_arr1` is a non-polymorphic function using a custom typemap and `print_arr2` is a polymorphic function using a custom typemap and the only one that doesn't work.
This works in C#.

Sample .i file:

	%module swigtest
	%{
	#include <stdio.h>

	int return_int(int x) {
		return x;
	}

	int return_int() {
		return 4; //Chosen by fair dice roll
	}

	void print_arr1(char **str, int strn) {
		for(int i = 0; i < strn; i++) {
			printf("%s\n", str[i]);
		}
	}

	void print_arr2(char **str, int strn) {
		printf("print_arr3 called with all arguments\n");
		for(int i = 0; i < strn; i++) {
			printf("%s\n", str[i]);
		}
	}

	void print_arr2(char **str) {
		printf("print_arr3 called with only one argument\n");
	}

	void print_arr2() {
		printf("print_arr3 called with no arguments\n");
	}

	%}

	//From: http://swig.org/Doc3.0/SWIGDocumentation.html#Python_nn59
	// This tells SWIG to treat char ** as a special case
	%typemap(in) char ** {
		/* Check if is a list */
		if (PyList_Check($input)) {
		int size = PyList_Size($input);
		int i = 0;
		$1 = (char **) malloc((size+1)*sizeof(char *));
		for (i = 0; i < size; i++) {
			PyObject *o = PyList_GetItem($input, i);
			if (PyString_Check(o)) {
			$1[i] = PyString_AsString(PyList_GetItem($input, i));
			} else {
			free($1);
			PyErr_SetString(PyExc_TypeError, "list must contain strings");
			SWIG_fail;
			}
		}
		$1[i] = 0;
		} else {
		PyErr_SetString(PyExc_TypeError, "not a list");
		SWIG_fail;
		}
	}

	int return_int(int x);
	int return_int();
	void print_arr1(char **str, int strn);
	void print_arr2(char **str, int strn);
	void print_arr2(char **str);
	void print_arr2();

Build commands:

	swig -c++ -python swigtest.i
	g++ -c swigtest_wrap.cxx -I/usr/include/python3.6m -fPIC
	ld -shared swigtest_wrap.o -o _swigtest.so -lstdc++

Test commands:

	python3
	>>> from swigtest import *
	>>> return_int(10)
	10
	>>> return_int()
	4
	>>> print_arr1([b"Hello", b"SWIG"], 2)
	Hello
	SWIG
	>>> print_arr2([b"Hello", b"SWIG"], 2)
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	NotImplementedError: Wrong number or type of arguments for overloaded function 'print_arr2'.
	  Possible C/C++ prototypes are:
		print_arr2(char **,int)
		print_arr2(char **)
		print_arr2()

	>>> print_arr2([b"Hello", b"SWIG"])
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	NotImplementedError: Wrong number or type of arguments for overloaded function 'print_arr2'.
	  Possible C/C++ prototypes are:
		print_arr2(char **,int)
		print_arr2(char **)
		print_arr2()

	>>> print_arr2()
	print_arr3 called with no arguments

**Comment by ojwb** [comment]
You need to supply a `typecheck` typemap for SWIG to dispatch overloaded methods correctly - add this to the `.i` file (next to the `in` typemap is suitable):

```
%typemap(typecheck) char ** { $1 = PyList_Check($input); }
```

Then:

```
>>> from swigtest import *
>>> print_arr2([b"Hello", b"SWIG"], 2)
print_arr3 called with all arguments
Hello
SWIG
>>> print_arr2([b"Hello", b"SWIG"])
print_arr3 called with only one argument
>>> print_arr2()
print_arr3 called with no arguments
>>> 
```

(The messages say print_arr**3** due to typos in your example code!)
