### ISSUE TITLE
callback failed in Examples/go/callback/gocallback.go

### ISSUE THREAD

**Issue by NETkiddy** [swig/swig#955]
The callback just failed as described in [issue#600](https://github.com/swig/swig/issues/600)
To fix this:
line 39 in gocallback.go:  

Change this:
```
func (p *goCallback) Run() {
	fmt.Println("GoCallback.Run")
}
```
To this:
```
func (p *overwrittenMethodsOnCallback) Run() {
	fmt.Println("GoCallback.Run")
}
```
Then the callback worked.

**Comment by ojwb** [comment]
Please create a pull request for your proposed change - then it'll be automatically tested by the CI system.
