### ISSUE TITLE
Make swig.exe multithreaded.

### ISSUE THREAD

**Issue by Botzman** [swig/swig#978]
Performance of swig.exe does not scale with number of CPU cores. This makes swig.exe the ugliest bottleneck in the build process on a 32+ CPU cores servers.

**Comment by vadz** [comment]
This is such a pie-in-the-sky ticket that I'm not sure if it's really worth to keep it opened. Of course, it would be great to parallelize SWIG, but this would be highly untrivial and would likely require rewriting it from the ground up.

**Comment by wsfulton** [comment]
This would require a huge rewrite and then result in limited scalability as the processing of C code (the SWIG syntax is just an extension of C code) is essentially sequential. You're better off parallelizing your usage of swig.exe by breaking your wrappers into smaller modules. The same applies to C code, where you create multiple .c files and then parallelize using make -j to invoke multiple instances of the C compiler at once. Further performance improvements can also be obtained via ccache-swig and for a well modularised SWIG project, often results in good cache hit rates.
