### ISSUE TITLE
PyUnicode_AS_STRING is defined in Lib/python/pyhead.swg:#define PyString_AS_STRING(x) PyUnicode_AS_STRING(x) but not defined in Python

### ISSUE THREAD

**Issue by ycollet** [swig/swig#987]
When trying to compile an interface for Python 3.5, I met an error during compilation: PyUnicode_AS_STRING ID not found

I found PyUnicode_AS_STRING is defined in Lib/python/pyhead.swg:#define PyString_AS_STRING(x) 

But PyUnicode_AS_STRING is not defined in the python headers.

**Comment by ojwb** [comment]
As far as I can see, there are only two uses of this macro - both are in `Lib/python/builtin.swg` and both are guarded such that they aren't used with Python 3:

```
#if PY_VERSION_HEX >= 0x03000000
    PyErr_Format(PyExc_AttributeError, "cannot modify read-only attribute '%.50s.%.400S'", type->tp_name, name);
#else 
    PyErr_Format(PyExc_AttributeError, "cannot modify read-only attribute '%.50s.%.400s'", type->tp_name, PyString_AS_STRING(name));
#endif
  } else {
#if PY_VERSION_HEX >= 0x03000000
    PyErr_Format(PyExc_AttributeError, "type '%.50s' has no attribute '%.400S'", type->tp_name, name);
#else
    PyErr_Format(PyExc_AttributeError, "type '%.50s' has no attribute '%.400s'", type->tp_name, PyString_AS_STRING(name));
#endif
```

So it looks to me like this define is just dead code for Python3, and should probably be removed.

All I can think is that you're using this macro explicitly in your interface file.  If not, please can you provide a small, self-contained example which reproduces this (please include the SWIG command line to process it).

**Comment by ojwb** [comment]
I can find no evidence that `PyUnicode_AS_STRING()` ever existed outside of SWIG, and this fallback macro is only defined for Python >= 3 but `PyString_AS_STRING` is only used for Python < 3 so I'm going to push a change to remove it (once the testsuite has passed locally).

The issue actually reported here seems like it must be in the user's interface file, and they've not responded with a reproducer in 4.5 years so closing.  If you can reproduce this problem and you aren't using `PyString_AS_STRING` in your interface file, please reopen and provide a self-contained reproducer.
