### ISSUE TITLE
using Cmake with Swig - Not creating wrapper(_wrap.C and .py file)

### ISSUE THREAD

**Issue by deepika094** [swig/swig#988]
i read all the documention on cmake website and even on swig. Swig website elaborates all swig option but that is not beneficial for people using cmake. (we cant pass -c++ -o with swig in cmake) Though i tried setting OUTDIR path and sayiing CPLUSPLUS ON but even now my project is creating Module.so file but not .py file and Module_wrap.C file . Without these files i cant do anything obviosly. Even i am not sure internally swig used the wrapper file while making .so.

**Comment by ojwb** [comment]
cmake's support for SWIG is maintained by the cmake team, not by us - please direct any questions about it to them.
