### ISSUE TITLE
Unable to generate Java interface from C++ interface

### ISSUE THREAD

**Issue by gitrainbow** [swig/swig#990]
Hello, SWIG community:

I faced with the problem while generating Java interface from C++ interface using SWIG 3.0.12
Suppose I have struct ia which is C++ interface and I want to get Java interface class ia:
inter.hpp :
struct ia {
  virtual void a() = 0;
};

struct a : ia{
  void a() override {};
};

inter.i : 
%include <swiginterface.i>
%{
#include "inter.hpp"
%}
%include "inter.hpp"
%interface(ia);
%interface_impl(a);

Command I use for Java interface generation:
 swig -java -c++ -module testmodule inter.i

and generated ia.java file contains:
public class ia { ... some generated code ... }

However I expect to get:
public interface ia {... some generated code ...}

If I am doing something wrong, please correct me.
Thanks in advance

**Comment by wsfulton** [comment]
Put your `%interface` declarations before SWIG parses the code for which you are applying the interface.

**Comment by gitrainbow** [comment]
Thank you, this solved the problem
