### ISSUE TITLE
file generated with autodoc enabled don't define functions explicitly and can cause crashes 

### ISSUE THREAD

**Issue by technic** [swig/swig#992]
just by taking example from the documentation
with autodoc I get
```
def fact(n):
    """fact(int n) -> int"""
    return _example.fact(n)
# This file is compatible with both classic and new-style classes
```

without autodoc I get
```
def fact(n):
    return _example.fact(n)
fact = _example.fact
# This file is compatible with both classic and new-style classes.
```

In the second case whatever function is defined with `def`, it is overridden with a function from module object.  That is robust, because in case of optional parameters in function their type cannot be always determined correctly.  For class methods it like in the second case regardless autodoc.

in particular my c++ function is like `void f(SmartPtr<Class> ptr = 0)` that is converted to `f(ptr=0)` instead of `f(ptr=None)` and creates run time exception when called without arguments.

**Comment by technic** [comment]
Is there any update on that?

**Comment by wsfulton** [comment]
There are quite a few ways to customize default arguments. Please start at http://swig.org/Doc3.0/Python.html#Python_default_args. Also, SWIG won't know that your SmartPtr class is a smart pointer and 0 is a null pointer and not an integral value. If you use `void f(SmartPtr<Class> ptr = nullptr)` or `void f(SmartPtr<Class> ptr = NULL)` as a better indication that it is a null pointer. SWIG will then use None in the default mode.

For SWIG 4.0.0, the second definition of the proxy method will no longer be generated, see issue #639 and the summary of this change here:
https://github.com/swig/swig/blob/5c21de71c7c1c4187ed48049ac448cb5d189badc/CHANGES.current#L88-L107

**Comment by technic** [comment]
Hi, thanks for the reply.
I changed to `NULL` or `nullptr`, but this didn't help to change the default python value.
Should I use `%typemap(typecheck)` then? Currently I have only defined `%typemap(in)` and `%typemap(out)` for my `SmartPtr<Class>`?
Maybe the answer is in the documentation, sorry.

**Comment by wsfulton** [comment]
Read the docs. You do need a typecheck typemap for overloaded methods / defaulted methods to work, but this won't change the default value used in Python. You'll need to post a cut down testcase to demonstrate 'None' not being generated in the Python code if you need help with that.
